;;; nelisp-native-stackset-u5-test.el --- U5 stack mutation lowering -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'ert)
(require 'nelisp-bytecode-native-rooted-cfg-contract)
(require 'nelisp-bytecode-native-rooted-cfg-constructor-contract)
(require 'nelisp-aot-compiler)
(load (expand-file-name "support/native-stackset-u5-fixtures.el"
                        (file-name-directory (or load-file-name buffer-file-name))) nil t)
(ert-deftest u5/gnu-interpreter-qualifies-independent-reference ()
  (dolist (fixture (native-stackset-u5-fixtures))
    (dolist (args (nth 2 fixture))
      (setq u5-remaining 3 u5-history nil)
      (let ((expected (apply (nth 1 fixture) args)) (history (copy-sequence u5-history)))
        (setq u5-remaining 3 u5-history nil)
        (should (equal expected (native-stackset-u5-reference (nth 1 fixture) args)))
        (should (equal history u5-history))))))
(ert-deftest u5/frame-plan-and-shared-artifact ()
  (dolist (fixture (native-stackset-u5-fixtures))
    (let* ((input (nelisp-bytecode-compiler-input-build (nth 1 fixture)))
           (frame (plist-get input :frame-result))
           (plan (nelisp-bytecode-native-rooted-cfg-plan input))
           (emitted (nelisp-bytecode-native-rooted-cfg-shared-emit-build
                     plan nelisp-bytecode-native-rooted-cfg-contract-shared-entry))
           (contract (nelisp-bytecode-native-rooted-cfg-contract-create-shared-v2 input plan emitted)))
      (should (eq (plist-get frame :status) 'complete))
      (should (eq (plist-get plan :status) 'complete))
      (should (eq (plist-get emitted :status) 'complete))
      (should (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract))
      (should (if (memq (car fixture) '(swap swap2))
                  (nelisp-bytecode-native-rooted-cfg-contract-f1-p contract)
                (nelisp-bytecode-native-rooted-cfg-contract-constructor-p contract)))
      (unless (memq (car fixture) '(swap swap2))
        (should-not (plist-get plan :gateway-imports))
        (should (eq (plist-get (nelisp-bytecode-native-rooted-cfg-emit plan "u5_structured") :status) 'complete))
        (should-not (cl-some (lambda (op) (eq (plist-get op :opcode) 'dup))
                            (plist-get (car (plist-get plan :blocks)) :operations))))
      (should (plist-get (nelisp-aot-compile-to-link-unit (plist-get emitted :form)) :text)))))
(ert-deftest u5/invalid-offset-count-and-depth-refused ()
  (dolist (row '(((178 1 135) 1) ((179 0 1 135) 2) ((178 0 135) 0)
                 ((182 129 135) 1) ((182 255 135) 127) ((182 2 135) 1)))
    (should (eq (plist-get (nelisp-bytecode-frame-ir-build
                           (apply #'unibyte-string (car row)) [] (cadr row)) :status) 'malformed)))
  (dolist (code '((178) (179 0) (182)))
    (should (eq (plist-get (nelisp-bytecode-frame-ir-build
                           (apply #'unibyte-string code) [] 2) :status) 'malformed)))
  (let* ((fixture (assq 'set256 (native-stackset-u5-fixtures)))
         (original (nth 1 fixture))
         (fn (make-byte-code 514 (aref original 1) [] 254)))
    (should-not (eq (plist-get (nelisp-bytecode-native-rooted-cfg-plan
                               (nelisp-bytecode-compiler-input-build fn)) :status) 'complete))))
(ert-deftest u5/cyclic-root-budget-and-preserve-empty-refused ()
  (let* ((prefix (apply #'unibyte-string (make-list 255 137)))
         (fn (make-byte-code 514
                             (concat prefix (unibyte-string 179 0 0 137 130 255 0)) [] 257))
         (input (nelisp-bytecode-compiler-input-build fn))
         (plan (nelisp-bytecode-native-rooted-cfg-plan input)))
    (should (eq (plist-get (plist-get input :frame-result) :status) 'complete))
    (should (eq (plist-get plan :status) 'unsupported))
    (should (equal (plist-get plan :reason) "root-slot limit exceeded")))
  (should (eq (plist-get (nelisp-bytecode-frame-ir-build
                          (unibyte-string 182 128 192 135) [1] 0) :status) 'malformed))
  (should (eq (plist-get (nelisp-bytecode-frame-ir-build
                          (unibyte-string 182 0 192 135) [1] 0) :status) 'complete)))
(ert-deftest u5/stack-transfer-token-identity ()
  (let* ((frame (nelisp-bytecode-frame-ir-build (unibyte-string 178 1 135) [] 2))
         (ops (plist-get (aref (plist-get frame :blocks) 0) :instructions)))
    (should (equal (plist-get (aref ops 0) :inputs) '((:entry 0 1))))
    (should (equal (plist-get (aref ops 1) :inputs) (plist-get (aref ops 0) :outputs)))))
(provide 'nelisp-native-stackset-u5-test)
