;;; nelisp-native-template-win64-test.el --- Win64 stencil proofs -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'ert)
(require 'nelisp-native-template)
(require 'nelisp-native-template-win64-pin)
(defmacro nelisp-template-win64-test--with-target (&rest body)
  `(let ((nelisp-native-load--build-target 'windows-x86_64)
         (nelisp-native-template--selected-target nil)
         (nelisp-native-template-stencil-version nelisp-native-template-stencil-version)
         (nelisp-native-template-fragment-abi nelisp-native-template-fragment-abi)
         (nelisp-native-template-library-sha256 nelisp-native-template-library-sha256)
         (nelisp-native-template-library-source-key nelisp-native-template-library-source-key)
         (nelisp-native-template-library-inventory nelisp-native-template-library-inventory)
         (nelisp-native-template--library-path nelisp-native-template--library-path)
         (nelisp-native-template--snapshot nil))
     ,@body))
(defun nelisp-template-win64-test--hex (hex)
  (apply #'unibyte-string
         (cl-loop for i from 0 below (length hex) by 2
                  collect (string-to-number (substring hex i (+ i 2)) 16))))
;; Independent instruction references: pushes, SUB RSP, argument moves,
;; two stack stores, CALL rel32, CMP/Jcc and inverse pops/RET.
(defconst nelisp-template-win64-test--references
  '((prologue . "555341544155415641574881ec380000004989cc4989d549c7c00000000049c7c10000000048c7c00000000048894424204889442428e8000000004881f8000000000f84000000004989c6")
    (epilogue . "4881c438000000415f415e415d415c5b5dc3")
    (call . "4c89e14c89ea49c7c00000000049c7c10000000048c7c000000000488944242048c7c0000000004889442428e8000000004881f8000000000f8500000000")
    (frame . "4c89e14c89ea49c7c00000000049c7c10000000048c7c000000000488944242048c7c0000000004889442428e8000000004881f8000000000f8500000000")
    (status-branch . "48c7c1000000004839cb0f8500000000")))
(ert-deftest nelisp-template-win64-reference-fragments ()
  (nelisp-template-win64-test--with-target
   (let ((library (nelisp-native-template-open-library)))
     (dolist (row nelisp-template-win64-test--references)
       (should (equal (plist-get (cdr (assq (car row) (plist-get library :fragments))) :bytes)
                      (nelisp-template-win64-test--hex (cdr row)))))
     (should (equal (plist-get (cdr (assq 'poll (plist-get library :fragments))) :bytes)
                    (nelisp-template-win64-test--hex (cdr (assq 'call nelisp-template-win64-test--references)))))
     ;; Entry RSP=8 mod16, six pushes and 56-byte frame => aligned CALL.
     (should (= 0 (mod (- 8 (* 6 8) 56) 16)))
     (should (>= 56 (+ 32 (* 2 8))))
     (should (equal (mapcar (lambda (h) (plist-get h :name))
                           (plist-get (cdr (assq 'frame (plist-get library :fragments))) :holes))
                    '(state action arguments result nl_native_frame_v2 failure))))))
(ert-deftest nelisp-template-win64-register-sentinel-contract ()
  (nelisp-template-win64-test--with-target
   (nelisp-native-template-open-library)
   (should (equal (plist-get nelisp-native-template-fragment-abi :callee-saved)
                  '(rbp rbx rdi rsi r12 r13 r14 r15 xmm6 xmm7 xmm8 xmm9 xmm10 xmm11 xmm12 xmm13 xmm14 xmm15)))
   (should-not (cl-intersection '(rdi rsi xmm6 xmm7 xmm8 xmm9 xmm10 xmm11 xmm12 xmm13 xmm14 xmm15)
                               (plist-get nelisp-native-template-fragment-abi :clobbers)))
   (load (expand-file-name "test/support/windows-native-sentinel.el") nil t)
   (should (string-match-p (regexp-quote (unibyte-string #x57 #x56 #x41 #x54)) windows-native-sentinel--code))
   (should (string-match-p (regexp-quote (unibyte-string #x3d #xff #xff 0 0)) windows-native-sentinel--code))
   (should (fboundp 'windows-native-sentinel-with-entry))))
(ert-deftest nelisp-template-win64-reference-negative-controls ()
  (let ((linux (nelisp-native-template-open-library)))
    (dolist (name '(prologue epilogue call frame))
      (should-not (equal (plist-get (cdr (assq name (plist-get linux :fragments))) :bytes)
                         (nelisp-template-win64-test--hex (cdr (assq name nelisp-template-win64-test--references)))))))
  (nelisp-template-win64-test--with-target
   (let* ((library (nelisp-native-template-open-library))
          (bytes (plist-get (cdr (assq 'call (plist-get library :fragments))) :bytes)))
     (aset bytes 0 #x90)
     (should-not (equal bytes (nelisp-template-win64-test--hex (cdr (assq 'call nelisp-template-win64-test--references))))))))
(ert-deftest nelisp-template-win64-refuses-wrong-abi-and-byte-before-copy ()
  (nelisp-template-win64-test--with-target
   (nelisp-native-template-select-target)
   (let* ((original-path nelisp-native-template--library-path)
          (snapshot (with-temp-buffer (set-buffer-multibyte nil)
                      (insert-file-contents-literally original-path) (buffer-string)))
          (path (make-temp-file "win64-stencil-"))
          (copies nelisp-native-template--copy-count)
          (maps nelisp-native-load--trusted-map-count))
     (unwind-protect
         (dolist (control '(byte abi sysv))
           (let ((nelisp-native-template--snapshot nil)
                 (nelisp-native-template--library-path path)
                 (nelisp-native-template-library-sha256 nelisp-native-template-library-sha256)
                 (bytes (copy-sequence snapshot)))
             (pcase control
               ('byte (aset bytes 4 (logxor 1 (aref bytes 4))))
               ('abi (let ((library (nelisp-native-template--read-library bytes)))
                       (setf (plist-get library :abi) '(wrong-abi))
                       (setq bytes (concat (nelisp-native-template--print library) "\n")
                             nelisp-native-template-library-sha256 (secure-hash 'sha256 bytes))))
               ('sysv (setq bytes (with-temp-buffer (set-buffer-multibyte nil)
                                   (insert-file-contents-literally
                                    (expand-file-name "nelisp-native-template.nelst" (file-name-directory original-path)))
                                   (buffer-string))
                            nelisp-native-template-library-sha256 (secure-hash 'sha256 bytes))))
             (let ((coding-system-for-write 'no-conversion)) (write-region bytes nil path nil 'silent))
             (should-error (nelisp-native-template-open-library))
             (should (= copies nelisp-native-template--copy-count))
             (should (= maps nelisp-native-load--trusted-map-count))))
       (delete-file path)))))
(ert-deftest nelisp-template-win64-manifest-bridge-abi-and-proof ()
  (nelisp-template-win64-test--with-target
   (cl-letf (((symbol-function 'nelisp-native-load-running-binary-sha256) (lambda () (make-string 64 ?a))))
     (let* ((library (nelisp-native-template-open-library))
            (recipe (list :descriptor 0 :code (unibyte-string 192 137 66 135) :constants [42] :stack-depth 4))
            (certificate (nelisp-native-template-validate recipe))
            (manifest (nelisp-native-template-manifest recipe certificate
                        (nelisp-native-template-assemble certificate library))))
       (should (equal (plist-get manifest :target) (nelisp-native-load--target-v2)))
       (should (equal (plist-get manifest :runtime-abi) "nelisp-runtime-raw-v2:win64:v1"))
       (dolist (row (append (plist-get manifest :gc-entries)
                           (plist-get (plist-get manifest :native) :imports)
                           (plist-get (plist-get manifest :native) :exports)))
         (should (equal (plist-get row :abi) "nelisp-runtime-raw-v2:win64:v1")))
       (should-not (nelisp-native-template-check manifest))))))
(ert-deftest nelisp-template-win64-refuses-target-change-after-selection ()
  (nelisp-template-win64-test--with-target
   (nelisp-native-template-open-library)
   (let ((nelisp-native-load--build-target nil))
     (should-error (nelisp-native-template-open-library)))))
(ert-deftest nelisp-template-win64-cache-dispatch-and-virtualalloc ()
  (require 'nelisp-native-cache)
  (require 'nelisp-native-windows)
  (nelisp-template-win64-test--with-target
   (let ((nelisp-native-cache-backend 'template) (copies 0) (maps 0))
     (cl-letf (((symbol-function 'nelisp-native-budget-check) (lambda (_) t))
               ((symbol-function 'nelisp-native-template-compile)
                (lambda (function) (setq copies (1+ copies)) (list 'template function)))
               ((symbol-function 'nelisp-native-windows-map)
                (lambda (size) (setq maps (1+ maps)) (should (= size 4096)) 65536))
               ((symbol-function 'syscall-direct) (lambda (&rest _) (error "Unexpected Linux syscall"))))
       (should (equal (nelisp-native-cache-compile 'fixture) '(template fixture)))
       (should (= copies 1))
       (should (= (nelisp-native-load--mmap 4096 nil) 65536))
       (should (= maps 1))
       (let ((nelisp-native-cache-backend 'gccjit))
         (should-error (nelisp-native-cache-compile 'fixture)))
       (should (= copies 1))))))
(provide 'nelisp-native-template-win64-test)
