;;; nelisp-native-cfg-grammar-test.el --- Raw CFG backend grammar -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'ert)
(require 'nelisp-native-gccjit)
(require 'nelisp-aot-compiler)
(load (expand-file-name "support/native-cfg-grammar-fixtures.el"
                        (file-name-directory (or load-file-name buffer-file-name))) nil t)

(defconst native-cfg-test-diamond
  '(cfg 1 entry (block entry nil (branch env left right))
        (block left ((setq ticket 7)) (jump join))
        (block right ((setq ticket 9)) (jump join))
        (block join nil (return ticket))))

(defun native-cfg-test-form (body)
  `(defun cfg_probe (env ticket argument-count root-count) ,body))

(defun native-cfg-test-gcc-calls (body)
  (let ((calls nil) (serial 4096) (nelisp-native-gccjit--contexts nil))
    (cl-letf (((symbol-function 'nelisp-native-gccjit--call)
               (lambda (name &rest args) (push (cons name args) calls) (setq serial (1+ serial))))
              ((symbol-function 'nelisp-native-gccjit--cstring) #'identity)
              ((symbol-function 'nelisp-native-gccjit--array) #'identity))
      (nelisp-native-gccjit-lower (native-cfg-test-form body) nil))
    (nreverse calls)))

(ert-deftest native-cfg/diamond-each-block-once ()
  (let* ((ast (nelisp-native-cfg-grammar-aot-form native-cfg-test-diamond))
         (calls (native-cfg-test-gcc-calls native-cfg-test-diamond))
         (unit (nelisp-aot-compile-to-link-unit (native-cfg-test-form native-cfg-test-diamond)))
         (labels (cl-remove-if-not (lambda (f) (eq (car-safe f) 'aot-landing-label)) (cddr (nth 2 ast)))))
    (should (= (length labels) 5)) ; four physical blocks plus one exit
    (should (= (length (delete-dups (mapcar #'cadr labels))) 5))
    (should (= (cl-count "gcc_jit_function_new_block" calls :key #'car :test #'equal) 6))
    (should (= (cl-count "gcc_jit_block_end_with_conditional" calls :key #'car :test #'equal) 1))
    (should (= (cl-count "gcc_jit_block_end_with_jump" calls :key #'car :test #'equal) 4))
    (should (> (length (plist-get unit :text)) 0))))

(ert-deftest native-cfg/shared-join-and-entry-order ()
  (let ((cfg '(cfg 1 start (block join nil (return ticket))
                  (block left ((setq ticket 1)) (jump join))
                  (block right ((setq ticket 2)) (jump join))
                  (block start nil (branch env left right)))))
    (should (= (length (nelisp-native-cfg-grammar-validate cfg)) 4))
    (should (plist-get (nelisp-aot-compile-to-link-unit (native-cfg-test-form cfg)) :text))
    (should (native-cfg-test-gcc-calls cfg))))

(ert-deftest native-cfg/typed-labels-do-not-collide ()
  (let* ((symbol (intern "1"))
         (cfg `(cfg 1 1 (block 1 nil (jump ,symbol)) (block ,symbol nil (return 513)))))
    (should (plist-get (nelisp-aot-compile-to-link-unit (native-cfg-test-form cfg)) :text))
    (should (native-cfg-test-gcc-calls cfg))))

(ert-deftest native-cfg/structured-local-named-cfg ()
  (let ((form '(let ((cfg 0)) (setq cfg env) cfg)))
    (should (native-cfg-test-gcc-calls form))
    (should (plist-get (nelisp-aot-compile-to-link-unit (native-cfg-test-form form)) :text)))
  (should (native-cfg-test-gcc-calls '(let ((cfg env)) (cfg 1 a (block a (cfg 0) (return cfg)))))))

(ert-deftest native-cfg/dispatch-and-status ()
  (let ((cfg '(cfg 1 entry (block entry nil (dispatch env ((-1 a) (9223372036854775807 b)) miss))
                  (block a nil (return 513)) (block b nil (status 2)) (block miss nil (return 512)))))
    (dolist (arch '(x86_64 aarch64))
      (should (plist-get (nelisp-aot-compile-to-link-unit (native-cfg-test-form cfg) :arch arch) :text)))
    (should (= (cl-count "gcc_jit_block_end_with_conditional" (native-cfg-test-gcc-calls cfg)
                        :key #'car :test #'equal) 2))))

(ert-deftest native-cfg/boxed-constant-canonical-plan ()
  (require 'nelisp-bytecode-native-rooted-cfg-shared-emit)
  (let* ((byte-compile-warnings nil)
         (input (nelisp-bytecode-compiler-input-build
                 (byte-compile '(lambda (x) (cfg-id "boxed constant")))))
         (plan (nelisp-bytecode-native-rooted-cfg-plan input))
         (emitted (nelisp-bytecode-native-rooted-cfg-shared-emit-build plan "boxed_probe")))
    (should (eq (plist-get plan :status) 'complete))
    (should (eq (plist-get emitted :status) 'complete))
    (should (plist-get (nelisp-aot-compile-to-link-unit
                       (native-cfg-grammar-fixtures-lower (plist-get emitted :form))) :text))))

(ert-deftest native-cfg/refuse-malformed-before-gcc-effects ()
  (dolist (cfg '((cfg 2 a (block a nil (return 0)))
                 (cfg 1 a (block a nil (jump absent)))
                 (cfg 1 absent (block a nil (return 0)))
                 (cfg 1 a (block a nil (return 0)) (block a nil (return 1)))
                 (cfg 1 a (block a nil (branch env a absent)))
                 (cfg 1 a (block a nil (dispatch env ((1 a) (1 a)) a)))
                 (cfg 1 a (block a nil (jump a)))
                 (cfg 1 a (block a nil (return 0)) (block b nil (return 1)))
                 (cfg 1 a (block a nil (return 0 1)))
                 (cfg 1 a (block a nil (bogus 0)))))
    (should-error (nelisp-native-cfg-grammar-validate cfg))
    (should-error (nelisp-aot-compile-to-link-unit (native-cfg-test-form cfg)))
    (let ((effects nil))
      (cl-letf (((symbol-function 'nelisp-native-gccjit--call) (lambda (&rest _) (setq effects t))))
        (should-error (nelisp-native-gccjit-lower (native-cfg-test-form cfg) nil)))
      (should-not effects))))

(ert-deftest native-cfg/structured-lane-and-qualification-lowering ()
  (let* ((form (native-cfg-test-form '(let ((x env)) (if (= ticket 0) (setq x 7) (setq x 9)) (+ x 1))))
         (raw (native-cfg-grammar-fixtures-lower form)))
    (should (plist-get (nelisp-aot-compile-to-link-unit form) :text))
    (should (plist-get (nelisp-aot-compile-to-link-unit raw) :text))
    (should (native-cfg-test-gcc-calls (nth 3 raw)))))

(provide 'nelisp-native-cfg-grammar-test)
