;;; nelisp-native-corpus-u10-load-test.el --- Transparent loader witnesses -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'ert)
(require 'cl-lib)
(defvar nelisp-native-load--raw-v2-check-count 0)
(defvar nelisp-native-load--rooted-cfg-outer-validation-count 0)
(defvar nelisp-bytecode-native-rooted-cfg-contract--validation-count 0)
;; Read only the real helper; the standalone driver's main loop is not a host test.
(with-temp-buffer
  (insert-file-contents (or (getenv "U10_TEST_DRIVER")
                            (expand-file-name "standalone-native-corpus-u10-driver.el"
                                              (file-name-directory load-file-name))))
  (let (form)
    (while (not (and (eq (car-safe form) 'defun) (eq (cadr form) 'u10-load)))
      (setq form (read (current-buffer))))
    (eval form t)))

(ert-deftest u10-load/public-path-and-exact-mapped-header ()
  (dolist (phase '("compile" "load"))
    (dotimes (mutation 5)
      (let* ((directory (make-temp-file "u10-load-host-" t))
             (first (expand-file-name "first" directory))
             (later (expand-file-name "later" directory))
             (function (vector 'retained)) (header (list :root-count 7))
             (native (lambda () 42)) (calls 0) (compiles 0) (constructs 0)
             (nelisp-native-load--raw-v2-check-count 0)
             (nelisp-native-load--rooted-cfg-outer-validation-count 0)
             (nelisp-bytecode-native-rooted-cfg-contract--validation-count 0))
        (unwind-protect
            (cl-letf (((symbol-function 'u10-assert)
                       (lambda (value label) (unless value (error "%s" label))))
                      ((symbol-function 'nelisp-native-cache-file)
                       (lambda (fn)
                         (should (eq fn function))
                         (setq calls (1+ calls))
                         (if (= calls 1) first later)))
                      ((symbol-function 'nelisp-native-cache-compile)
                       (lambda (fn)
                         (setq compiles (1+ compiles))
                         (should (equal (nelisp-native-cache-file fn) first))
                         (write-region "published" nil first nil 'silent)
                         (should (equal (nelisp-native-cache-file fn) later))
                         ;; Compile validation is permitted, load validation is not.
                         (setq nelisp-native-load--raw-v2-check-count 1)))
                      ((symbol-function 'nelisp-native-cache--callable-from-entry)
                       (lambda (address actual-header addresses constants &optional _owner)
                         (should (= address 123)) (should (eq actual-header header))
                         (should (eq addresses 'addresses)) (should (eq constants function))
                         (setq constructs (1+ constructs)) native))
                      ((symbol-function 'nelisp-native-cache-load)
                       (lambda (fn)
                         (should (equal (nelisp-native-cache-file fn)
                                        (if (equal phase "compile") later first)))
                         (when (= mutation 1) (nelisp-native-cache-compile fn))
                         (when (= mutation 2)
                           (setq nelisp-native-load--raw-v2-check-count 99))
                         (when (= mutation 3)
                           (nelisp-native-cache--callable-from-entry 123 header 'addresses fn))
                         (unless (= mutation 4)
                           (nelisp-native-cache--callable-from-entry 123 header 'addresses fn)))))
              (if (> mutation 0)
                  (should-error (u10-load function phase))
                (let ((pair (u10-load function phase)))
                  (should (eq (car pair) native)) (should (= (cadr pair) 123))
                  (should (eq (nth 2 pair) header)) (should (equal (nth 3 pair) first))
                  (should-not (nth 4 pair))
                  (should (= calls (if (equal phase "compile") 3 1)))
                  (should (= compiles (if (equal phase "compile") 1 0)))
                  (should (= constructs 1)))))
          (delete-directory directory t))))))
