;;; nelisp-bytecode-native-rooted-stack-test.el --- rooted stack plan tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'bytecomp)
(require 'nelisp-bytecode-native-rooted-stack)
(require 'nelisp-bytecode-compiler-input)
(require 'nelisp-native-load)
(require 'nelisp-runtime-reload-abi)
(require 'nelisp-bytecode-native-package)

(defun nelisp-bytecode-native-rooted-stack-test--source-input (form)
  "Compile FORM with GNU bytecomp and extract its checked input."
  (let* ((dir (make-temp-file "rooted-stack" t))
         (file (expand-file-name "fixture.el" dir))
         (elc (concat file "c")) result)
    (unwind-protect
        (progn
          (with-temp-file file
            (insert ";;; -*- lexical-binding: t; -*-\n")
            (prin1 form (current-buffer)) (insert "\n"))
          (unless (byte-compile-file file)
            (error "GNU byte compiler did not produce fixture"))
          (load elc nil t t)
          (let ((compiled (symbol-function
                           'nelisp-bytecode-native-rooted-stack-fixture)))
            (setq result
                  (nelisp-bytecode-compiler-input-build
                   (make-byte-code (aref compiled 0) (aref compiled 1)
                                   (aref compiled 2) (aref compiled 3)))))
          result)
      (delete-directory dir t))))

(defun nelisp-bytecode-native-rooted-stack-test--run-plan (input plan arguments)
  "Interpret PLAN over evaluator values in INPUT using ARGUMENTS."
  (let ((roots (make-vector (plist-get plan :required-root-count) nil)))
    (cl-loop for root in (plist-get plan :initial-roots)
             for value in arguments do (aset roots root value))
    (dolist (entry (plist-get plan :constant-roots))
      (aset roots (cdr entry) (aref (plist-get input :constants) (car entry))))
    (dolist (op (plist-get plan :operations))
      (let* ((values (mapcar (lambda (root) (aref roots root))
                             (plist-get op :inputs)))
             (result (pcase (plist-get op :operation)
                       ('car (car (car values)))
                       ('cdr (cdr (car values)))
                       ('cons (cons (car values) (cadr values)))))
             (out (car (plist-get op :outputs))))
        (aset roots out result)))
    (aref roots (plist-get plan :final-root))))

(ert-deftest nelisp-bytecode-native-rooted-stack/plans-compiled-compositions ()
  (skip-unless (equal emacs-version "31.1"))
  (let* ((input (nelisp-bytecode-native-rooted-stack-test--source-input
                 '(defun nelisp-bytecode-native-rooted-stack-fixture (x)
                    (cons nil (car (cdr x))))))
         (plan (nelisp-bytecode-native-rooted-stack-plan input)))
    (should (eq (plist-get input :status) 'complete))
    (should (= (plist-get input :argument-descriptor) 257))
    (should (= (plist-get input :required-argument-count) 1))
    (should (eq (plist-get plan :status) 'complete))
    (should (equal (mapcar (lambda (op) (plist-get op :operation))
                           (plist-get plan :operations))
                   '(cdr car cons)))
    (should (= (length (plist-get plan :constant-roots)) 1))
    (should (= (plist-get plan :final-root) 5))
    (let* ((arg (list 'a 'b))
           (result (nelisp-bytecode-native-rooted-stack-test--run-plan
                    input plan (list arg)))
           (expected (funcall (symbol-function
                               'nelisp-bytecode-native-rooted-stack-fixture) arg)))
      (should (equal result expected))
      (should (eq (car result) (car expected)))
      (should (eq (cdr result) (cdr expected)))))
  (let* ((input (nelisp-bytecode-native-rooted-stack-test--source-input
                 '(defun nelisp-bytecode-native-rooted-stack-fixture (a b)
                    (cons a (cdr b)))))
         (plan (nelisp-bytecode-native-rooted-stack-plan input)))
    (should (eq (plist-get plan :status) 'complete))
    (should (= (plist-get input :argument-descriptor) 514))
    (should (= (plist-get input :required-argument-count) 2))
    (should (equal (plist-get plan :initial-roots) '(1 2)))
    (should (equal (mapcar (lambda (op) (plist-get op :operation))
                           (plist-get plan :operations))
                   '(cdr cons)))
    (let* ((a (cons 'identity nil)) (b (list 'x 'y))
           (result (nelisp-bytecode-native-rooted-stack-test--run-plan
                    input plan (list a b)))
           (expected (funcall (symbol-function
                               'nelisp-bytecode-native-rooted-stack-fixture) a b)))
      (should (equal result expected))
      (should (eq (car result) a))
      (should (eq (cdr result) (cdr b)))))
  (let* ((input (nelisp-bytecode-native-rooted-stack-test--source-input
                 '(defun nelisp-bytecode-native-rooted-stack-fixture (a b)
                    (cons a (cons b (cdr b))))))
         (plan (nelisp-bytecode-native-rooted-stack-plan input))
         (ops (plist-get plan :operations))
         (a (cons 'a nil)) (b (cons 'b nil)))
    (should (eq (plist-get plan :status) 'complete))
    (should (equal (mapcar (lambda (op) (plist-get op :inputs)) ops)
                   '((2) (2 3) (1 4))))
    (should (equal (mapcar (lambda (op) (plist-get op :outputs)) ops)
                   '((3) (4) (5))))
    (should (= (plist-get plan :final-root) 5))
    (let ((result (nelisp-bytecode-native-rooted-stack-test--run-plan
                   input plan (list a b)))
          (expected (funcall (symbol-function
                              'nelisp-bytecode-native-rooted-stack-fixture) a b)))
      (should (equal result expected))
      (should (eq (car result) a))
      (should (eq (car (cdr result)) b))
      (should (eq (cdr (cdr result)) (cdr b))))))

(ert-deftest nelisp-bytecode-native-rooted-stack/refuses-noncomplete-and-unsupported-ir ()
  (should (eq (plist-get (nelisp-bytecode-native-rooted-stack-plan nil) :status)
              'unsupported))
  (let ((input (nelisp-bytecode-native-rooted-stack-test--source-input
                '(defun nelisp-bytecode-native-rooted-stack-fixture (x)
                   (if x (car x) (cdr x))))))
    (should (eq (plist-get (nelisp-bytecode-native-rooted-stack-plan input) :status)
                'unsupported)))
  (let* ((input (nelisp-bytecode-native-rooted-stack-test--source-input
                 '(defun nelisp-bytecode-native-rooted-stack-fixture (x) (car x))))
         (captured (copy-sequence input))
         (bad-depth (copy-sequence input))
         (bad-arity (copy-sequence input)))
    (setq captured (plist-put captured :closure-template-descriptor 'captured))
    (setq bad-depth (plist-put bad-depth :initial-stack-depth 0))
    (setq bad-arity (plist-put bad-arity :argument-count "bad"))
    (dolist (invalid (list captured bad-depth bad-arity))
      (should (eq (plist-get (nelisp-bytecode-native-rooted-stack-plan invalid) :status)
                  'unsupported)))))

(ert-deftest nelisp-bytecode-native-rooted-stack/refuses-noop-before-effects ()
  (skip-unless (equal emacs-version "31.1"))
  (let* ((input (nelisp-bytecode-native-rooted-stack-test--source-input
                 '(defun nelisp-bytecode-native-rooted-stack-fixture (x) 42)))
         (plan (nelisp-bytecode-native-rooted-stack-plan input))
         (attested 0) (compiled 0))
    (should (eq (plist-get plan :status) 'complete))
    (should-not (plist-get plan :operations))
    (cl-letf (((symbol-function 'nelisp-native-load-running-binary-sha256)
               (lambda () (setq attested (1+ attested)) nil))
              ((symbol-function 'nelisp-native-load-raw-v2-compile-file)
               (lambda (&rest _) (setq compiled (1+ compiled)))))
      (should (eq (plist-get (nelisp-bytecode-native-rooted-stack-build input "noop.nelr")
                             :status)
                  'unsupported))
      (should (equal (plist-get (nelisp-bytecode-native-rooted-stack-build input "noop.nelr")
                                :reason)
                     "raw rooted stack requires a gateway operation"))
      (should (= attested 0))
      (should (= compiled 0)))))

(ert-deftest nelisp-bytecode-native-rooted-stack/builds-authenticated-source-and-gates-effects ()
  (skip-unless (equal emacs-version "31.1"))
  (let* ((input (nelisp-bytecode-native-rooted-stack-test--source-input
                 '(defun nelisp-bytecode-native-rooted-stack-fixture (a b)
                    (cons a (cdr b)))))
         (directory (make-temp-file "rooted-stack-build" t))
         (artifact (expand-file-name "unit.nelr" directory))
         (attested 0) (compiled 0) source-text result)
    (unwind-protect
        (cl-letf (((symbol-function 'nelisp-native-load-running-binary-sha256)
                   (lambda () (setq attested (1+ attested)) "runtime-sha"))
                  ((symbol-function 'nelisp-runtime-reload-contract-matches-p)
                   (lambda () t))
                  ((symbol-function 'nelisp-native-load-raw-v2-compile-file)
                   (lambda (source output tag binary call1-template rooted-stack-spec)
                     (setq compiled (1+ compiled))
                     (should (equal tag "gnu31-rooted-stack-v1"))
                     (should (equal binary "runtime-sha"))
                     (should-not call1-template)
                     (should (eq (plist-get rooted-stack-spec :input) input))
                     (should (equal (plist-get rooted-stack-spec :plan)
                                    (nelisp-bytecode-native-rooted-stack-plan input)))
                     (with-temp-buffer
                       (insert-file-contents source)
                       (setq source-text (buffer-string)))
                     (with-temp-file output (insert "verified artifact"))
                     (list :artifact-sha256
                           (nelisp-bytecode-native-package-raw-file-sha256 output)))))
          (let ((nelisp-runtime-reload-gc-contract nil))
            (setq result (nelisp-bytecode-native-rooted-stack-build input artifact)))
          (should (eq (plist-get result :status) 'complete))
          (should (equal (plist-get result :entry-name) "nl_native_stack_probe_v1"))
          (should (equal (plist-get result :gateway-imports)
                         '("nl_native_cdr_v2" "nl_native_cons_v2")))
          (should (string-match-p "extern-call nl_native_cdr_v2 env ticket 2 3 0 0"
                                  source-text))
          (should (string-match-p "extern-call nl_native_cons_v2 env ticket 1 3 4 0"
                                  source-text))
          (should (string-match-p "258" source-text))
          (should (string-match-p "257" source-text))
          (should (string-match-p "t gateway-status" source-text))
          (should (equal (plist-get result :runtime-binary-sha256) "runtime-sha"))
          (should (nelisp-bytecode-native-rooted-stack-authenticated-result-p result))
          (should-not (nelisp-bytecode-native-rooted-stack-authenticated-result-p
                       (copy-sequence result)))
          (let ((backup (expand-file-name "backup.nelr" directory)))
            (copy-file artifact backup)
            (with-temp-buffer (insert "tamper") (append-to-file (point-min) (point-max) artifact))
            (should-not (nelisp-bytecode-native-rooted-stack-authenticated-result-p result))
            (copy-file backup artifact t))
          (setq result (plist-put result :entry-name "forged"))
          (should-not (nelisp-bytecode-native-rooted-stack-authenticated-result-p result))
          (should (= attested 1)) (should (= compiled 1)))
      (delete-directory directory t)))
  (let ((attested 0) (compiled 0))
    (cl-letf (((symbol-function 'nelisp-native-load-running-binary-sha256)
               (lambda () (setq attested (1+ attested)) "runtime-sha"))
              ((symbol-function 'nelisp-native-load-raw-v2-compile-file)
               (lambda (&rest _) (setq compiled (1+ compiled)))))
      (should (eq (plist-get (nelisp-bytecode-native-rooted-stack-build nil "unused.nelr")
                             :status)
                  'unsupported))
      (should (= attested 0)) (should (= compiled 0)))))

(provide 'nelisp-bytecode-native-rooted-stack-test)
;;; nelisp-bytecode-native-rooted-stack-test.el ends here
