;;; -*- lexical-binding: t; -*-
(require 'cl-lib) (require 'nelisp-standalone-build) (require 'nelisp-cc-evalport-combiner-apply)
(defun am-def (n p) (or (cl-find-if (lambda (f) (eq (cadr f) n)) p) (error "Missing %S" n)))
(let* ((variant (or (getenv "AM_VARIANT") "positive")) (output (getenv "AM_OUTPUT"))
       (base #x39000000) (slot (+ base 128)) (text (+ base 256))
       (original (mapcar (lambda (n) (copy-tree (am-def n nelisp-standalone--applyfn-bytecode-helpers))) '(wf_bytecode_optional_marker_p wf_bytecode_rest_marker_p)))
       (candidate (copy-tree original)) (legacy nil) (forms nil) (count 0))
 ;; Authentic pre-change production definitions, embedded for a durable fixture.
 (setq legacy (copy-tree '((defun wf_bytecode_optional_marker_p (sym) (let* ((buf (alloc-bytes 9 1))) (seq (ptr-write-u64 buf 0 7020671367832956710) (ptr-write-u8 buf 8 108) (nl_apply_sym_eq_bytes sym buf 9))))
(defun wf_bytecode_rest_marker_p (sym) (let* ((buf (alloc-bytes 5 1))) (seq (ptr-write-u64 buf 0 500152234534) (nl_apply_sym_eq_bytes sym buf 5)))))))
 (unless (cl-every (lambda (f) (eq (car (nth 3 f)) 'symbol-name-eq)) original) (error "Expected canonical literal marker predicates"))
 (pcase variant
  ("old-zero" (setq candidate (copy-tree legacy)))
  ("bad-optional" (setq candidate (cl-subst "&optionam" "&optional" candidate :test #'equal)))
  ("bad-rest" (setq candidate (cl-subst "&resu" "&rest" candidate :test #'equal))))
 (unless (or (equal variant "positive") (not (equal candidate original))) (error "Inactive marker mutant"))
 (setq legacy (cl-subst 'am_old_optional 'wf_bytecode_optional_marker_p (cl-subst 'am_old_rest 'wf_bytecode_rest_marker_p legacy)))
 (cl-labels ((emit (x) (push x forms)) (check (x) (setq count (1+ count)) (emit `(if ,x 0 (when (= failure 0) (setq failure ,count))))))
  (dolist (name '("" "&" "&optional" "&optionam" "&optionalx" "x&optional" "&rest" "&resu" "&restx" "x&rest" "foo" ":keyword" "?" "日本語" "&rest\0" "&OPTIONAL"))
   (let ((bytes (encode-coding-string name 'utf-8)))
    (emit `(ptr-write-u64 ,slot 0 4)) (emit `(ptr-write-u64 ,slot 8 ,(length bytes)))
    (emit `(ptr-write-u64 ,slot 16 ,text)) (emit `(ptr-write-u64 ,slot 24 ,(length bytes)))
    (dotimes (i (length bytes)) (emit `(ptr-write-u8 ,text ,i ,(aref bytes i))))
    (cl-loop for old in '(am_old_optional am_old_rest) for new in '(wf_bytecode_optional_marker_p wf_bytecode_rest_marker_p) for match in '("&optional" "&rest") do
     (emit `(ptr-write-u64 ,base 0 0))
     (check `(= (,old ,slot) ,(if (equal name match) 1 0)))
     (check `(= (ptr-read-u64 ,base 0) 1))
     (emit `(ptr-write-u64 ,base 0 0))
     (check `(= (,new ,slot) ,(if (equal name match) 1 0)))
     (check `(= (ptr-read-u64 ,base 0) 0)))))
  (let ((source `(seq
    (defun nl_alloc_bytes (size align) (let ((p (ptr-read-u64 ,base 16))) (seq (ptr-write-u64 ,base 16 (+ p 32)) (ptr-write-u64 ,base 0 (+ (ptr-read-u64 ,base 0) 1)) p)))
    ,(am-def 'nl_apply_sym_eq_bytes (cdr nelisp-cc-evalport-combiner-apply--source))
    ,@legacy ,@candidate
    (defun audit_run () (let ((failure 0)) (seq (syscall-direct 9 ,base 1048576 3 50 -1 0)
     (ptr-write-u64 ,base 16 ,(+ base 4096)) ,@(nreverse forms)
     (ptr-write-u64 ,base 8 failure) (syscall-direct 1 1 ,base 16 0 0 0) failure)))
    (defun _start () (syscall-direct 60 (audit_run) 0 0 0 0 0)))))
   (nelisp-link-units output (list (nelisp-standalone--compile-to-unit "marker-audit.o" source)) "_start")
   (with-temp-file (concat output ".source.el") (prin1 source (current-buffer)))
   (princ (format "MARKER-UNIT-COMPILED variant=%s checks=%d\n" variant count)))))
