;;; nelisp-obarray-parity-test.el --- focused obarray parity -*- lexical-binding: t; -*-

(let ((a (obarray-make))
      (b (obarray-make))
      (results nil))
  (let* ((x (intern "nelisp-obarray-id" a))
         (y (intern "nelisp-obarray-id" a))
         (z (intern "nelisp-obarray-id" b))
         (global (intern "nelisp-obarray-id")))
    (push (list 'identity (eq x y) (not (eq x z)) (not (eq x global))
                (eq (intern-soft "nelisp-obarray-id" a) x)
                (null (intern-soft x b))
                (eq global (intern "nelisp-obarray-id")))
          results))
  (push (list 'object (obarrayp a) (not (vectorp a)) (type-of a)) results)
  (push (list 'miss (null (intern-soft "nelisp-obarray-missing" a))
              (null (intern-soft "nelisp-obarray-missing"))) results)
  (let* ((custom-nil (intern "nil" a))
         (custom-t (intern "t" a)))
    (push (list 'special-names (not (eq custom-nil nil))
                (eq custom-nil (intern "nil" a))
                (not (eq custom-t t))
                (eq custom-t (intern "t" a)))
          results))
  (let* ((x (intern "nelisp-obarray-remove" a))
         (removed (unintern "nelisp-obarray-remove" a))
         (miss (null (intern-soft "nelisp-obarray-remove" a)))
         (y (intern "nelisp-obarray-remove" a)))
    (push (list 'remove removed miss
                (not (eq x y)) (null (intern-soft x a))) results))
  (intern "nelisp-obarray-iter-b" a)
  (intern "nelisp-obarray-iter-a" a)
  (let (seen)
    (mapatoms (lambda (s) (push (symbol-name s) seen)) a)
    (push (list 'map (sort seen #'string<)) results))
  (push (list 'gc (let ((s (intern "nelisp-obarray-gc" a)))
                    (garbage-collect)
                    (and (eq s (intern-soft s a))
                         (eq s (intern "nelisp-obarray-gc" a)))))
        results)
  (push (list 'forged-record
              (obarrayp (record 'obarray (make-hash-table :test 'equal))))
        results)
  (push (list 'size
              (mapcar (lambda (n)
                        (condition-case e
                            (progn (obarray-make n) 'ok)
                          (wrong-type-argument 'wrong-type-argument)))
                      '(nil 0 1 -1 1.5 "x")))
        results)
  (princ (format "%S\n" (nreverse results))))

;;; nelisp-obarray-parity-test.el ends here
