;;; nelisp-native-list-u3a-test.el --- U3a list lowering -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'ert)
(require 'nelisp-bytecode-native-rooted-cfg-contract)
(require 'nelisp-bytecode-native-rooted-cfg-constructor-contract)
(require 'nelisp-bytecode-native-rooted-cfg-safe-contract)
(require 'nelisp-native-load)
(load "support/native-list-u3a-fixtures.el" nil t t)
(ert-deftest u3a/ordered-operands-and-both-shared-contracts ()
  (skip-unless (equal emacs-version "31.1"))
  (dolist (row (native-list-u3a-fixtures))
    (let* ((fn (apply #'native-list-u3a-function row))
           (input (nelisp-bytecode-compiler-input-build fn))
           (plan (nelisp-bytecode-native-rooted-cfg-plan input))
           (op (car (last (plist-get (car (plist-get plan :blocks)) :operations) 2))))
      (should (eq (plist-get input :status) 'complete))
      (should (eq (plist-get plan :status) 'complete))
      (should (< (plist-get plan :required-root-count) 256))
      (should (= (plist-get op :argument-count) (cadr row)))
      (should (equal (plist-get op :argument-roots)
                     (if (> (cadr row) 4)
                         (cons 1 (make-list (1- (cadr row)) 2))
                       (number-sequence 1 (cadr row)))))
      (should (eq (plist-get op :opcode) (if (> (cadr row) 32) 'list-build 'primitive-call)))
      (let* ((emitted (nelisp-bytecode-native-rooted-cfg-shared-emit-build
                       plan nelisp-bytecode-native-rooted-cfg-contract-shared-entry))
             (contract (nelisp-bytecode-native-rooted-cfg-contract-create-shared-v2 input plan emitted)))
        (should (eq (plist-get emitted :status) 'complete))
        (should (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract))
        (should (nelisp-bytecode-native-rooted-cfg-contract-f1-p contract)))))
  ;; A DAG join has selector phis, not the physical banks used by cycles.
  ;; Keep those selectors valid when a long list follows the diamond.
  (let* ((fn (native-list-u3a-join-function))
         (input (nelisp-bytecode-compiler-input-build fn))
         (plan (nelisp-bytecode-native-rooted-cfg-plan input))
         (emitted (nelisp-bytecode-native-rooted-cfg-shared-emit-build
                   plan nelisp-bytecode-native-rooted-cfg-contract-shared-entry)))
    (should (plist-get plan :phis))
    (should (eq (plist-get emitted :status) 'complete))
    (should (nelisp-bytecode-native-rooted-cfg-contract-valid-p
             (nelisp-bytecode-native-rooted-cfg-contract-create-shared-v2 input plan emitted)))))
(ert-deftest u3a/gnu-order-identity-and-count-boundaries ()
  (dolist (row (native-list-u3a-fixtures))
    (let* ((count (cadr row)) (args (native-list-u3a-args count))
           (result (apply (apply #'native-list-u3a-function row) args))
           (expected (native-list-u3a-expected-values args count)))
      (should (= (length result) count))
      (cl-mapc (lambda (a b) (should (eq a b))) result expected)))
  ;; There is no extended LISTN opcode in GNU 31.1. Refuse rather than
  ;; truncate an out-of-range count into a different instruction stream.
  (dolist (count '(-1 256 65535))
    (should-error (native-list-u3a-function 175 count))))
(ert-deftest u3a/underflow-truncation-and-stack-storage-refused ()
  (dolist (op '(67 68 69 70))
    (should-not (eq (plist-get (nelisp-bytecode-compiler-input-build
                               (make-byte-code 0 (unibyte-string op 135) [] 1)) :status) 'complete)))
  (dolist (code (list (unibyte-string 175) (unibyte-string 175 1 135)))
    (should-not (eq (plist-get (nelisp-bytecode-compiler-input-build
                               (make-byte-code 0 code [] 1)) :status) 'complete)))
  (let* ((valid (native-list-u3a-function 175 255))
         (fn (make-byte-code (aref valid 0) (aref valid 1) (aref valid 2) 254)))
    (should-not (eq (plist-get (nelisp-bytecode-native-rooted-cfg-plan
                               (nelisp-bytecode-compiler-input-build fn)) :status) 'complete))))
(ert-deftest u3a/frozen-list-value-and-defensive-family-copy ()
  ;; GNU 31.1's cached LIST subr trampoline recurses after FSET/restoration.
  ;; Test the value registry without installing that unrelated host trampoline.
  (let ((native-comp-enable-subr-trampolines nil)
        (value (nelisp-native-funcall-v2-initializer 'list))
        (original (symbol-function 'list)) (restore (symbol-function 'fset)) actual)
    (unwind-protect
        (progn (funcall restore 'list (lambda (&rest _) 'poison))
               (setq actual (nelisp-native-funcall-v2-initializer 'list)))
      (funcall restore 'list original))
    (should (eq value actual)))
  (dolist (op '(67 68 69 70 175))
    (let ((row (nelisp-native-funcall-v2-primitive op)))
      (should (eq (cadr row) 'list))
      (setcar (cdr row) 'poison)
      (should (eq (cadr (nelisp-native-funcall-v2-primitive op)) 'list)))))
(ert-deftest u3a/error-retains-earlier-mutation-and-stops-later-effect ()
  (let ((cell (cons 'before 'tail)))
    (should (equal (condition-case err (funcall (native-list-u3a-mutation-error) cell [live])
                     (error err)) '(wrong-type-argument listp 7)))
    (should (equal cell '(changed . tail)))))
(provide 'nelisp-native-list-u3a-test)
