;;; -*- lexical-binding: t; -*-
(require 'cl-lib) (require 'nelisp-aot-compiler) (require 'nelisp-standalone-build)
(dolist (f '(val-load sexp-clone-into cons-construct nlconsbox-alloc nlconsbox-set-car nlconsbox-set-cdr nlconsbox-clone nlvector-clone nlstr-clone nlchartable-clone nlboolvector-clone nlcell-clone nlrecord-clone nlrecord-slot-ptr)) (require (intern (format "nelisp-cc-%s" f))))
(defun af-def (name) (with-temp-buffer (insert-file-contents (or (getenv "AF_SOURCE") "scripts/nelisp-standalone-build.el")) (goto-char (point-min)) (search-forward (format "(defun %s " name)) (goto-char (match-beginning 0)) (read (current-buffer))))
(defun af-find (tree head) (cond ((equal (car-safe tree) head) tree) ((consp tree) (or (af-find (car tree) head) (af-find (cdr tree) head)))))
(let* ((variant (or (getenv "AF_VARIANT") "positive")) (output (getenv "AF_OUTPUT")) (base #x3c000000)
       (func (+ base 256)) (box (+ base 320)) (data (+ base 400)) (frame (+ base 512)) (dst (+ base 1024)) (out (+ base 1408))
       (code (+ base 1504)) (constants (+ base 1536)) (newcode (+ base 1568)) (newconstants (+ base 1600))
       (helper (af-def 'wf_bytecode_function_frame)) (wrapper (af-def 'wf_bytecode_execute))
       (seed (af-find (af-def 'wf_bytecode_execute_frame) '(if (= done 0) (< arg-index initial-slots) 0)))
       (count 0) checks)
 ;; The matched condition is the car of the actual WHILE tail: use the
 ;; complete canonical loop, not a reimplementation of the seeding algorithm.
 (setq seed (cl-labels ((walk (x) (cond ((and (eq (car-safe x) 'while) (equal (cadr x) '(if (= done 0) (< arg-index initial-slots) 0))) x) ((consp x) (or (walk (car x)) (walk (cdr x))))))) (walk (af-def 'wf_bytecode_execute_frame))))
 (unless seed (error "Missing canonical seed loop"))
 (pcase variant
  ("bad-tag" (setq helper (cl-subst nil '(/= (sexp-tag func) 17) helper :test #'equal)))
  ("bad-frame" (setq helper (cl-subst '(wf_bytecode_execute_frame (record-slot-ref-ptr func 1) (record-slot-ref-ptr func 2) (record-slot-ref-ptr func 3) env out 0 argc maxargs rest 0) '(wf_bytecode_execute_frame (record-slot-ref-ptr func 1) (record-slot-ref-ptr func 2) (record-slot-ref-ptr func 3) env out 0 argc maxargs rest frame) helper :test #'equal)))
  ("bad-jit" (setq helper (cl-subst 0 '(wf_bytecode_try_jit_frame func 0 argc env out frame) helper :test #'equal)))
  ("bad-descriptor" (setq helper (cl-subst '(ptr-read-u64 (record-slot-ref-ptr func 0) 8) '(ptr-read-u64 descriptor 8) helper :test #'equal)))
  ("bad-code-order" (setq helper (cl-subst 'saved-code '(record-slot-ref-ptr func 1) helper :test #'equal)) (setq helper (cl-subst '((descriptor (record-slot-ref-ptr func 0)) (saved-code (record-slot-ref-ptr func 1))) '((descriptor (record-slot-ref-ptr func 0))) helper :test #'equal)))
  ("bad-arity" (setq helper (cl-subst nil '(< argc mandatory) helper :test #'equal)))
  ("bad-optional" (setq seed (cl-subst 0 '(wf_write_nil dst) seed :test #'equal)))
  ("bad-rest" (setq seed (cl-subst '(wf_bytecode_build_args initial-frame 0 (- initial-argc initial-maxargs) dst) '(wf_bytecode_build_args initial-frame initial-maxargs (- initial-argc initial-maxargs) dst) seed :test #'equal))))
 (cl-labels ((emit (x) (push x checks))
             (check (x) (emit `(if ,x 0 (seq (ptr-write-u64 ,base 24 ,(cl-incf count)) (syscall-direct 1 1 ,base 32 0 0 0) (syscall-direct 60 2 0 0 0 0 0)))))
             (slot (p tag a b c) (cl-loop for x in (list tag a b c) for k from 0 do (emit `(ptr-write-u64 ,p ,(* k 8) ,x))))
             (setup (descriptor argc)
              (slot func 17 box 0 0) (emit `(ptr-write-u64 ,box 32 ,data)) (emit `(ptr-write-u64 ,box 48 4))
              (emit `(ptr-write-u64 ,data 0 ,(+ (* descriptor 4) 1))) (emit `(ptr-write-u64 ,data 8 ,code)) (emit `(ptr-write-u64 ,data 16 ,constants)) (emit `(ptr-write-u64 ,data 24 33))
              (emit `(ptr-write-u64 ,base 0 0)) (emit `(ptr-write-u64 ,base 8 0)) (emit `(ptr-write-u64 ,base 48 0)) (emit `(ptr-write-u64 ,base 56 ,argc))
              (slot out 99 88 77 66) (dotimes (i 8) (slot (+ dst (* i 32)) 99 88 77 66)))
             (word (p k x) (check `(= (ptr-read-u64 ,p ,(* k 8)) ,x))))
  (slot code 14 0 0 0) (slot constants 8 0 0 0) (slot newcode 14 0 0 0) (slot newconstants 8 0 0 0)
  (dotimes (i 6) (slot (+ frame (* i 32)) 2 (+ 10 i) (+ 100 i) (+ 200 i)))
  ;; Eligibility gate is before any descriptor dereference or JIT callback.
  ;; The dynamic dispatcher boundary is an explicit stub here; its actual
  ;; shape/binding/unbind/epoch implementation has a separate native fixture.
  (dolist (tag '(0 2 7 8 12 18)) (setup 0 0) (emit `(ptr-write-u64 ,func 0 ,tag)) (check `(= (wf_bytecode_function_frame ,func ,frame 0 77 ,out) 2)) (word base 0 0) (word base 1 0) (word out 0 99))
  (dolist (size '(0 1 2 3)) (setup 0 0) (emit `(ptr-write-u64 ,box 48 ,size)) (check `(= (wf_bytecode_function_frame ,func ,frame 0 77 ,out) 2)) (word base 0 0))
  (dolist (word0 '(3 7)) (setup 0 0) (emit `(ptr-write-u64 ,data 0 ,word0)) (check `(= (wf_bytecode_function_frame ,func ,frame 0 77 ,out) 2)) (word base 0 0))
  ;; All four fixed/optional result words and frame indexes, plus fresh rest
  ;; construction with immediate children and no mutation of caller operands.
  (dolist (row '((0 0 0 0) (257 1 1 0) (768 0 3 0) (768 2 3 0) (897 1 3 1) (897 2 3 1) (897 6 3 1) (128 6 0 1)))
   (pcase-let ((`(,descriptor ,argc ,maximum ,rest) row))
    (setup descriptor argc) (check `(= (wf_bytecode_function_frame ,func ,frame ,argc 77 ,out) 0))
    (word base 0 1) (word base 1 1) (word base 8 frame) (word base 9 0) (word base 10 code) (word base 11 constants)
    (dotimes (i maximum)
     (if (< i argc) (cl-loop for x in (list 2 (+ 10 i) (+ 100 i) (+ 200 i)) for k from 0 do (word (+ dst (* i 32)) k x))
      (dotimes (k 4) (word (+ dst (* i 32)) k 0))))
    (when (= rest 1)
     (if (<= argc maximum) (dotimes (k 4) (word (+ dst (* maximum 32)) k 0))
      (progn (emit `(setq cursor ,(+ dst (* maximum 32))))
       (dotimes (i (- argc maximum))
        (word 'cursor 0 7) (word 'cursor 2 0) (word 'cursor 3 0)
        (check `(= (ptr-read-u64 (ptr-read-u64 cursor 8) 0) ,(+ (* (+ 10 maximum i) 4) 1)))
        (if (= i (1- (- argc maximum))) (check '(= (ptr-read-u64 (ptr-read-u64 cursor 8) 8) 3))
         (emit '(setq cursor (ptr-read-u64 (ptr-read-u64 cursor 8) 8))))))))
    (dotimes (i 6) (cl-loop for x in (list 2 (+ 10 i) (+ 100 i) (+ 200 i)) for k from 0 do (word (+ frame (* i 32)) k x)))))
  ;; Normalized errors do not enter execution, and handled/error JIT outcomes
  ;; are returned before checking otherwise-invalid argument counts.
  (dolist (row '((-1 0 3) (32768 0 3) (257 0 4) (257 2 4)))
   (setup (nth 0 row) (nth 1 row)) (check `(= (wf_bytecode_function_frame ,func ,frame ,(nth 1 row) 77 ,out) 1)) (word out 0 (nth 2 row)) (word base 1 0))
  (dolist (mode '(1 2)) (setup 257 0) (emit `(ptr-write-u64 ,base 48 ,mode)) (check `(= (wf_bytecode_function_frame ,func ,frame 0 77 ,out) ,(if (= mode 1) 0 1))) (word base 0 1) (word base 1 0) (cl-loop for x in '(8 123 456 789) for k from 0 do (word out k x)))
  ;; Callback rewrites record descriptor and payload. Captured descriptor stays
  ;; old; code/constants/depth are read after the callback exactly as before.
  (setup 0 0) (emit `(ptr-write-u64 ,base 48 3)) (check `(= (wf_bytecode_function_frame ,func ,frame 0 77 ,out) 0)) (word base 10 newcode) (word base 11 newconstants) (word data 0 1029)
  ;; Existing nine-argument ABI stays exact and passes frame=0.
  (setup 0 0) (check `(= (wf_bytecode_execute ,code ,constants ,code 77 ,out 999 5 6 1) 0)) (word base 8 0) (word base 9 999) (word base 12 5) (word base 13 6) (word base 14 1)
  (let* ((common (cl-loop for f in '(val-load sexp-clone-into nlconsbox-alloc nlconsbox-set-car nlconsbox-set-cdr nlconsbox-clone nlvector-clone nlstr-clone nlchartable-clone nlboolvector-clone nlcell-clone nlrecord-clone nlrecord-slot-ptr) append (cdr (symbol-value (intern (format "nelisp-cc-%s--source" f))))))
         (source `(seq ,helper ,wrapper ,nelisp-cc-cons-construct--source ,@common
          ,@(mapcar #'af-def '(wf_bytecode_slot wf_bytecode_copy wf_copy32 wf_write_nil wf_bytecode_build_args))
          (defun nl_bind_clone_force_flag () 0) (defun nl_gc_in_arena (p) 0) (defun nl_gc_is_boot (p) 0)
          (defun nl_alloc_str (a b c) (syscall-direct 60 199 0 0 0 0 0)) (defun nl_alloc_symbol (a b c) (syscall-direct 60 199 0 0 0 0 0))
          ;; The source loop's list-only branch is exercised by the production
          ;; cold corpus; these stubs fail loudly if a frame test enters it.
          (defun nl_cons_car_ptr (p) (syscall-direct 60 197 0 0 0 0 0)) (defun nl_cons_cdr_ptr (p) (syscall-direct 60 197 0 0 0 0 0))
          (defun wf_bytecode_dynamic_function_frame (func formals frame argc env out) 2)
          (defun bf_invalid_byte_code_object (out) (seq (ptr-write-u64 out 0 3) 1))
          (defun bf_wrong_number_of_args (func argc) (seq (ptr-write-u64 ,out 0 4) 1))
          (defun wf_bytecode_try_jit_frame (func args argc env out frame)
            (seq (ptr-write-u64 ,base 0 (+ (ptr-read-u64 ,base 0) 1))
             (if (or (/= frame ,frame) (/= args 0) (/= env 77) (/= argc (ptr-read-u64 ,base 56))) (syscall-direct 60 196 0 0 0 0 0) 0)
             (if (= (ptr-read-u64 ,base 48) 3)
              (seq (ptr-write-u64 ,data 0 1029) (ptr-write-u64 ,data 8 ,newcode) (ptr-write-u64 ,data 16 ,newconstants) 0)
              (if (> (ptr-read-u64 ,base 48) 0)
               (seq (ptr-write-u64 out 0 8) (ptr-write-u64 out 8 123) (ptr-write-u64 out 16 456) (ptr-write-u64 out 24 789) (ptr-read-u64 ,base 48)) 0))))
          (defun wf_bytecode_execute_frame (code constants depth-p env out initial-args initial-argc initial-maxargs initial-rest initial-frame)
            (seq (ptr-write-u64 ,base 8 (+ (ptr-read-u64 ,base 8) 1))
             (ptr-write-u64 ,base 64 initial-frame) (ptr-write-u64 ,base 72 initial-args) (ptr-write-u64 ,base 80 code) (ptr-write-u64 ,base 88 constants)
             (ptr-write-u64 ,base 96 initial-argc) (ptr-write-u64 ,base 104 initial-maxargs) (ptr-write-u64 ,base 112 initial-rest)
             (if (> initial-frame 0) (audit_seed ,dst initial-args initial-argc initial-maxargs initial-rest initial-frame) 0) 0))
          (defun audit_seed (slots initial-args initial-argc initial-maxargs initial-rest initial-frame)
           (let ((done 0) (initial-slots (+ initial-maxargs initial-rest)) (arg-index 0) (arg-cursor initial-args)) (seq ,seed 0)))
          (defun nl_alloc_bytes (size align) (let ((p (ptr-read-u64 ,base 16))) (seq (ptr-write-u64 ,base 16 (+ p size)) p)))
          (defun audit_run () (let ((cursor 0)) (seq (syscall-direct 9 ,base 16777216 3 50 -1 0) (ptr-write-u64 (data-addr nl_arena_base) 0 ,base) (ptr-write-u64 ,base 192 1) (ptr-write-u64 ,base 16 ,(+ base 65536)) ,@(nreverse checks) (ptr-write-u64 ,base 24 0) (syscall-direct 1 1 ,base 32 0 0 0) 0)))
          (defun _start () (syscall-direct 60 (audit_run) 0 0 0 0 0)))))
   (nelisp-link-units output (list (nelisp-standalone--compile-to-unit "frame-audit.o" source) (nelisp-standalone--arena-base-slot-unit)) "_start")
   (with-temp-file (concat output ".source.el") (prin1 source (current-buffer)))
   (princ (format "FRAME-NATIVE-COMPILED variant=%s checks=%d\n" variant count)))))
