;;; nelisp-n3-reference.el --- GNU reference for N3 evaluator changes -*- lexical-binding: t; -*-
;; Native policy clause 2: eval's environments, semantic variable writes,
;; and special-form invocation require evaluator entry. Policy stays Lisp.
;; Run unchanged on GNU, then on the standalone with the watcher unit loaded.
(defmacro n3-row (name form)
  `(progn (princ ,name) (princ "|")
          (prin1 (condition-case err ,form (error (list 'ERR (car err)))))
          (terpri)))
(n3-row "eval-read" (eval '(+ n3q 1) '((n3q . 10))))
(n3-row "eval-write" (let ((e '((n3q . 10)))) (list (eval '(setq n3q 12) e) e)))
(n3-row "eval-duplicates" (eval 'n3q '((n3q . 10) (n3q . 20))))
(n3-row "eval-special-pair" (progn (defvar n3special 1) (let ((e '((n3special . 7)))) (list (eval '(setq n3special 8) e) e n3special))))
(n3-row "eval-share" (let* ((e (list (cons 'n3q 10))) (f (eval '(lambda () (setq n3q (1+ n3q))) e))) (setcdr (car e) 30) (list (funcall f) e (eval 'n3q e))))
(n3-row "eval-shadow" (let ((e '((n3q . 10)))) (list (eval '(let ((n3q 20)) (setq n3q 21)) e) e)))
(n3-row "eval-bare-special" (progn (setq n3dynamic 7) (eval '(let ((n3dynamic 8)) (symbol-value 'n3dynamic)) '(n3dynamic))))
(n3-row "eval-isolation" (eval '(let ((n3q 44)) (eval 'n3q t)) t))
(n3-row "eval-dynamic" (eval '(let ((n3q 44)) (eval 'n3q nil)) nil))
(n3-row "eval-dynamic-symbol-value" (eval '(let ((n3q 44)) (symbol-value 'n3q)) nil))
(n3-row "eval-dynamic-lambda" (let ((f (eval '(lambda () n3q) nil))) (eval `(let ((n3q 44)) (funcall ',f)) nil)))
(n3-row "eval-context-return" (let ((n3q 99)) (list (eval '3 t) n3q)))
(n3-row "eval-context-signal" (let ((n3q 99)) (list (condition-case nil (eval '(error "x") t) (error 'caught)) n3q)))
(n3-row "eval-context-throw" (let ((n3q 99)) (list (catch 'n3tag (eval '(throw 'n3tag 3) t)) n3q)))
(n3-row "eval-arity-zero" (eval))
(n3-row "eval-arity-three" (eval 1 t t))
(n3-row "eval-mode" (list (eval 'lexical-binding nil) (eval 'lexical-binding t)))
(n3-row "special-if" (list (subrp (symbol-function 'if)) (subr-name (symbol-function 'if)) (func-arity (symbol-function 'if)) (special-form-p (symbol-function 'if))))
(n3-row "special-all" (mapcar (lambda (s) (list s (fboundp s) (special-form-p s) (subrp (symbol-function s)) (func-arity s))) '(if quote function let let* setq while progn condition-case unwind-protect catch and or cond prog1 defvar defconst save-excursion save-current-buffer save-restriction interactive)))
(n3-row "special-alias" (progn (fset 'n3if (symbol-function 'if)) (n3if t 5 (error "unselected"))))
(n3-row "special-symbol-alias" (progn (fset 'n3if2 'if) (n3if2 nil (error "unselected") 6)))
(n3-row "special-functionp" (list (functionp (symbol-function 'if)) (functionp 'if) (functionp 'n3if) (functionp (symbol-function '+)) (functionp '+)))
(n3-row "special-funcall" (funcall #'if t 1 2))
(n3-row "special-apply" (apply #'if '(t 1 2)))
(n3-row "special-fset" (let ((f (symbol-function 'if))) (unwind-protect (progn (fset 'if (lambda (&rest xs) xs)) (eval '(if 1 2 3) t)) (fset 'if f))))
(n3-row "special-unbind" (let ((f (symbol-function 'if))) (unwind-protect (progn (fmakunbound 'if) (eval '(if t 1 2) t)) (fset 'if f))))
(defvar n3watched 0)
(defvar n3events nil)
(defun n3watch (s v op where) (push (list s v op (null where) (and (boundp s) (symbol-value s))) n3events))
(n3-row "watch-sequence" (progn (setq n3events nil n3watched 0) (add-variable-watcher 'n3watched #'n3watch) (unwind-protect (progn (set 'n3watched 1) (let ((n3watched 2)) (setq n3watched 3)) (makunbound 'n3watched) (reverse n3events)) (remove-variable-watcher 'n3watched #'n3watch))))
(n3-row "watch-remove" (progn (setq n3events nil) (add-variable-watcher 'n3watched #'n3watch) (set 'n3watched 1) (remove-variable-watcher 'n3watched #'n3watch) (set 'n3watched 2) (reverse n3events)))
(n3-row "watch-lexical" (let ((n3lexical 0)) (setq n3events nil) (add-variable-watcher 'n3lexical #'n3watch) (unwind-protect (progn (setq n3lexical 1) (let ((n3lexical 2)) (setq n3lexical 3)) n3events) (remove-variable-watcher 'n3lexical #'n3watch))))
(n3-row "watch-explicit-pair" (let ((env '((n3watched . 42)))) (setq n3events nil) (add-variable-watcher 'n3watched #'n3watch) (unwind-protect (list (eval '(setq n3watched 43) env) n3events env) (remove-variable-watcher 'n3watched #'n3watch))))
(n3-row "watch-recursion" (let ((f (lambda (s v op _where) (push (list s v op) n3events) (set s 999)))) (setq n3events nil n3watched 0) (add-variable-watcher 'n3watched f) (unwind-protect (progn (set 'n3watched 2) (list n3watched (reverse n3events))) (remove-variable-watcher 'n3watched f))))
(n3-row "watch-cross-recursion" (let ((f (lambda (_s v _op _where) (set 'n3other v)))) (setq n3events nil n3other 0 n3watched 0) (add-variable-watcher 'n3watched f) (add-variable-watcher 'n3other #'n3watch) (unwind-protect (progn (set 'n3watched 9) (reverse n3events)) (remove-variable-watcher 'n3watched f) (remove-variable-watcher 'n3other #'n3watch))))
(n3-row "watch-set-error" (let ((f (lambda (&rest _args) (error "watch")))) (setq n3watched 1) (add-variable-watcher 'n3watched f) (unwind-protect (list (condition-case e (set 'n3watched 2) (error (car e))) n3watched) (remove-variable-watcher 'n3watched f))))
(n3-row "watch-let-error" (let ((f (lambda (_s _v op _where) (when (eq op 'let) (error "watch"))))) (setq n3watched 1) (add-variable-watcher 'n3watched f) (unwind-protect (list (condition-case e (let ((n3watched 2)) n3watched) (error (car e))) n3watched) (remove-variable-watcher 'n3watched f))))
(n3-row "watch-unlet-error" (let ((f (lambda (_s _v op _where) (when (eq op 'unlet) (error "watch"))))) (setq n3watched 1) (add-variable-watcher 'n3watched f) (unwind-protect (list (condition-case e (let ((n3watched 2)) 3) (error (car e))) n3watched) (remove-variable-watcher 'n3watched f))))
(n3-row "watch-throw" (progn (setq n3events nil n3watched 1) (add-variable-watcher 'n3watched #'n3watch) (unwind-protect (list (catch 'n3tag (let ((n3watched 2)) (throw 'n3tag 3))) (reverse n3events)) (remove-variable-watcher 'n3watched #'n3watch))))
(n3-row "watch-alias" (progn (setq n3events nil n3alias 0 n3base 1) (add-variable-watcher 'n3alias #'n3watch) (defvaralias 'n3alias 'n3base) (remove-variable-watcher 'n3alias #'n3watch) (prog1 (reverse n3events) (setq n3events nil))))
(princ "N3-REFERENCE-DONE\n")
nil
