;;; nelisp-native-arithmetic-direct-test.el --- Shared builtin body controls -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(let ((path (or (getenv "NELISP_ARITHMETIC_SOURCE")
                (expand-file-name "../lisp/nelisp-native-arithmetic-v2.el"
                                  (file-name-directory load-file-name)))))
  (load path nil t))
(defconst nelisp-arithmetic-direct-test--body
  '(let* ((f (wf_any_float_arith args)))
     (if (= f 2)
         (bf_wrong_type_number_or_marker (wf_first_non_number_or_bignum args))
       (if (= f 1)
           (let* ((sc (alloc-bytes 32 8)))
             (seq (wf_fsum args 0 sc) (wf_copy32 out sc)))
         (wf_sum args 0 out)))))
(defconst nelisp-arithmetic-direct-test--builder
  (expand-file-name "../scripts/nelisp-standalone-build.el"
                    (file-name-directory load-file-name)))
(ert-deftest nelisp-arithmetic-direct-reader-table-identity ()
  (let* ((print-length nil) (print-level nil) (print-circle t)
         (print-escape-nonascii t)
         (table (with-temp-buffer
                  (insert-file-contents nelisp-arithmetic-direct-test--builder)
                  (search-forward "(defconst nelisp-standalone--applyfn-dispatch-table")
                  (goto-char (match-beginning 0))
                  (eval (nth 2 (read (current-buffer))) t))))
    (should (equal (caar table) '(:u8 "+")))
    (should (equal (cdar table) nelisp-arithmetic-direct-test--body))
    (should (= (length table) 107))
    (should (equal (secure-hash 'sha256 (prin1-to-string (cdr table)))
                   "b2f600e4dcb8ea4d8f313923d363c4cba73462d8986d43f2ddf84f8e6cabdd04"))))
(defun nelisp-arithmetic-direct-test--contains (tree node)
  (or (equal tree node)
      (and (consp tree)
           (or (nelisp-arithmetic-direct-test--contains (car tree) node)
               (nelisp-arithmetic-direct-test--contains (cdr tree) node)))))
(ert-deftest nelisp-arithmetic-direct-shared-body ()
  (let* ((body (nelisp-native-arithmetic-v2-plus-body))
         (source (nelisp-native-arithmetic-v2-direct-source))
         (helper (cadr source)))
    (should (equal body nelisp-arithmetic-direct-test--body))
    (should (equal helper (list 'defun 'nl_native_add_v2_plus '(args out) body)))
    (setcar body 'altered)
    (should (equal (nelisp-native-arithmetic-v2-plus-body)
                   nelisp-arithmetic-direct-test--body))
    (setcar (nth 2 helper) 'altered)
    (should (equal (nth 2 (cadr (nelisp-native-arithmetic-v2-direct-source))) '(args out)))
    (let ((nelisp-native-arithmetic-v2--plus-body '(wf_sum args 1 out))
          (nelisp-native-arithmetic-v2--direct-source '(seq counterfeit)))
      (should (equal (nelisp-native-arithmetic-v2-plus-body)
                     nelisp-arithmetic-direct-test--body))
      (should (equal (cadr (nelisp-native-arithmetic-v2-direct-source))
                     (list 'defun 'nl_native_add_v2_plus '(args out)
                           nelisp-arithmetic-direct-test--body))))
    (let ((saved-plus (copy-tree nelisp-native-arithmetic-v2--plus-body))
          (saved-direct (copy-tree nelisp-native-arithmetic-v2--direct-source))
          (before (nelisp-native-arithmetic-v2-direct-source)))
      (unwind-protect
          (progn (setcar nelisp-native-arithmetic-v2--plus-body 'counterfeit)
                 (setcar nelisp-native-arithmetic-v2--direct-source 'counterfeit)
                 (should (equal before (nelisp-native-arithmetic-v2-direct-source))))
        (setq nelisp-native-arithmetic-v2--plus-body saved-plus
              nelisp-native-arithmetic-v2--direct-source saved-direct)))))
(ert-deftest nelisp-arithmetic-direct-no-dispatcher ()
  (let* ((source (nelisp-native-arithmetic-v2-direct-source))
         (inner (cl-find 'nl_native_add_v2_inner (cdr source) :key #'cadr))
         (bindings (cadr (nth 3 inner))))
    (should (equal (mapcar #'car bindings) '(nil-slot first second tail args result)))
    (should (cl-every (lambda (binding)
                        (equal (cadr binding) '(nl_root_pin_reserve_v2 env token))) bindings))
    (should (nelisp-arithmetic-direct-test--contains inner '(nelisp_cons_construct second nil-slot tail)))
    (should (nelisp-arithmetic-direct-test--contains inner '(nelisp_cons_construct first tail args)))
    (should (nelisp-arithmetic-direct-test--contains inner '(nl_native_add_v2_plus args result)))
    (should-not (string-match-p "wf_bytecode_call_gateway\\|nl_alloc_symbol" (prin1-to-string source)))
    (should-not (cl-find "wf_bytecode_call_gateway" (nelisp-native-arithmetic-v2-direct-runtime-imports)
                         :key (lambda (row) (plist-get row :name)) :test #'equal))))
(ert-deftest nelisp-arithmetic-direct-owner-refusal ()
  (let ((before (nelisp-native-arithmetic-v2-dependency-context)))
    (should (eq (aref before 10) (symbol-function 'nelisp-native-arithmetic-v2-plus-body)))
    (should (equal (aref before 11) nelisp-arithmetic-direct-test--body))
    (cl-letf (((symbol-function 'nelisp-native-arithmetic-v2-plus-body) (lambda () '(altered))))
      (should-error (nelisp-native-arithmetic-v2-direct-source))
      (should-error (nelisp-native-arithmetic-v2-dependency-context)))))
(ert-run-tests-batch-and-exit)
