;;; nelisp-native-prims-u2b-test.el --- U2b frozen primitive lowering -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'ert)
(require 'nelisp-bytecode-native-rooted-cfg-contract)
(require 'nelisp-bytecode-native-rooted-cfg-constructor-contract)
(require 'nelisp-bytecode-native-rooted-cfg-safe-contract)
(require 'nelisp-native-load)
(load "support/native-prims-u2b-fixtures.el" nil t t)
(ert-deftest u2b/exact-family-ordered-roots-and-shared-contract ()
  (dolist (row native-prims-u2b-family)
    (let* ((input (nelisp-bytecode-compiler-input-build (native-prims-u2b-function row)))
           (plan (nelisp-bytecode-native-rooted-cfg-plan input))
           (op (car (plist-get (car (plist-get plan :blocks)) :operations))))
      (should (eq (plist-get input :status) 'complete))
      (should (eq (plist-get plan :status) 'complete))
      (should (eq (plist-get op :opcode) 'primitive-call))
      (should (equal (plist-get op :argument-roots) (number-sequence 1 (nth 2 row))))
      (should (= (plist-get op :argument-count) (nth 2 row)))
      (should (equal (plist-get plan :gateway-imports) '("nl_native_funcall_v2")))
      (let* ((emitted (nelisp-bytecode-native-rooted-cfg-shared-emit-build
                       plan nelisp-bytecode-native-rooted-cfg-contract-shared-entry))
             (contract (nelisp-bytecode-native-rooted-cfg-contract-create-shared-v2 input plan emitted)))
        (should (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract))
        (should (nelisp-bytecode-native-rooted-cfg-contract-f1-p contract))))))
(ert-deftest u2b/frozen-values-and-defensive-family-copy ()
  (dolist (row native-prims-u2b-family)
    (let* ((name (nth 1 row)) (original (nelisp-native-funcall-v2-initializer name))
           (cell (symbol-function name)) (restore (symbol-function 'fset)) actual)
      (unwind-protect
          (progn (funcall restore name (lambda (&rest _) 'poison))
                 (setq actual (nelisp-native-funcall-v2-initializer name)))
        (funcall restore name cell))
      (should (eq actual original))
      (let ((copy (nelisp-native-funcall-v2-primitive (car row))))
        (setcar (cdr copy) 'poison)
        (should (equal (nelisp-native-funcall-v2-primitive (car row)) row))))))
(ert-deftest u2b/underflow-and-unrelated-pending-opcode-refused ()
  (dolist (row native-prims-u2b-family)
    (let ((fn (make-byte-code 0 (unibyte-string (car row) 135) [] 0)))
      (should-not (eq (plist-get (nelisp-bytecode-compiler-input-build fn) :status) 'complete))))
  (should-not (nelisp-native-funcall-v2-primitive 80)))
(ert-deftest u2b/safe-contract-and-exit-layout-reconstruct ()
  (dolist (row native-prims-u2b-family)
    (let* ((input (nelisp-bytecode-compiler-input-build (native-prims-u2b-function row)))
           (plan (nelisp-bytecode-native-rooted-cfg-plan input 'safe-primitives-v3))
           (emitted (nelisp-bytecode-native-rooted-cfg-emit plan nelisp-bytecode-native-rooted-cfg-safe-contract-entry))
           (contract (nelisp-bytecode-native-rooted-cfg-safe-contract-create input plan emitted)))
      (should (nelisp-bytecode-native-rooted-cfg-safe-contract-valid-p contract))
      (let ((mutant (copy-tree contract)))
        (plist-put mutant :exit-root-base 1)
        (should-not (nelisp-bytecode-native-rooted-cfg-safe-contract-valid-p mutant))))))
(defun u2b-test-lisp-provider (name)
  "Execute the source provider with canonical GNU builtin values."
  (let (binding)
    (with-temp-buffer
      (insert-file-contents (locate-library "nelisp-native-funcall-v2.el" t))
      (goto-char (point-min))
      (condition-case nil
          (while t
            (let ((form (read (current-buffer))))
              (when (and (eq (car-safe form) 'let) (assq name (cadr form)))
                (setq binding (cadr (assq name (cadr form)))))))
        (end-of-file nil)))
    (should binding)
    (cl-labels ((host (form)
                 (cond ((and (eq (car-safe form) 'quote)
                             (eq (car-safe (cadr form)) 'builtin))
                        (list 'quote (symbol-function (cadr (cadr form)))))
                       ((consp form) (cons (host (car form)) (host (cdr form))))
                       (t form))))
      (eval (host binding) t))))
(ert-deftest u2b/nreverse-provider-gnu-mutation-and-error-data ()
  (let ((provider (u2b-test-lisp-provider 'nreverse-provider))
        (vm (native-prims-u2b-function '(159 nreverse 1)))
        (actual-cases (native-prims-u2b-cases 159)))
    (dolist (args (native-prims-u2b-cases 159))
      (should (equal (native-prims-u2b-observe vm args)
                     (native-prims-u2b-observe provider (pop actual-cases)))))
    (let ((cycle (list 'self)))
      (setcdr cycle cycle)
      (should (equal (native-prims-u2b-observe-cycle vm cycle)
                     (native-prims-u2b-observe-cycle provider cycle))))))
(ert-deftest u2b/prior-memq-initializer-ignores-public-cell ()
  ;; Exercise the runtime-token branch in GNU Emacs as well as standalone.
  (cl-letf (((symbol-function 'nelisp--eval-source-string) (lambda (&rest _) nil)))
    (let ((original (symbol-function 'memq)) (restore (symbol-function 'fset)) actual)
      (unwind-protect
          (progn
            (funcall restore 'memq (lambda (&rest _) 'poison))
            (setq actual (nelisp-native-funcall-v2-initializer 'memq)))
        (funcall restore 'memq original))
      (should (equal actual '(builtin memq))))))
(provide 'nelisp-native-prims-u2b-test)
