;;; nelisp-windows-cold-test.el --- Cold Windows boundary controls -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'ert)
(require 'cl-lib)
(defvar nelisp-windows-cold-test--file-helpers nil)
(let* ((root (expand-file-name ".." (file-name-directory load-file-name)))
       (source (if (getenv "COLD_TEST_BUILD_SOURCE")
                   (expand-file-name (getenv "COLD_TEST_BUILD_SOURCE"))
                 (expand-file-name "scripts/nelisp-standalone-build.el" root))))
  (let ((process-environment (cons "NELISP_STANDALONE_TARGET=windows-x86_64" process-environment)))
    (load source nil t)
    (setq nelisp-windows-cold-test--file-helpers nelisp-standalone--applyfn-fa-file-helpers))
  ;; Loading this test in a larger ERT process must not change its target's
  ;; constants. Keep the Windows file helpers privately for these controls.
  (load source nil t)
  (setq nelisp-standalone--repo-root root))

(defun nelisp-windows-cold-test--definition (forms name)
  (when (consp forms)
    (if (and (eq (car forms) 'defun) (eq (cadr forms) name)) forms
      (cl-some (lambda (form) (nelisp-windows-cold-test--definition form name)) forms))))

(defun nelisp-windows-cold-test--host-form (form)
  "Interpret the emitted DSL with mocked OS/memory primitives on the host."
  (if (atom form) form
    (pcase (car form)
      ('if `(if (let ((v ,(nelisp-windows-cold-test--host-form (nth 1 form))))
                   (if (numberp v) (/= v 0) v))
                ,(nelisp-windows-cold-test--host-form (nth 2 form))
              ,(nelisp-windows-cold-test--host-form (nth 3 form))))
      ('data-addr `(nelisp-windows-cold-test--address ',(cadr form)))
      ('extern-call `(nelisp-windows-cold-test--extern ',(cadr form)
                       ,@(mapcar #'nelisp-windows-cold-test--host-form (cddr form))))
      ((or 'seq 'nl_seq2) `(progn ,@(mapcar #'nelisp-windows-cold-test--host-form (cdr form))))
      (_ (mapcar #'nelisp-windows-cold-test--host-form form)))))

(defun nelisp-windows-cold-test--function (forms name)
  (let ((definition (nelisp-windows-cold-test--definition forms name)))
    (unless definition (error "Missing emitted function %s" name))
    (eval `(lambda ,(nth 2 definition)
             ,@(mapcar #'nelisp-windows-cold-test--host-form (nthcdr 3 definition))) t)))

(defun nelisp-windows-cold-test--contains (form name)
  (and (consp form)
       (or (eq (car form) name)
           (cl-some (lambda (child) (nelisp-windows-cold-test--contains child name)) form))))

(defun nelisp-windows-cold-test--os ()
  (let ((process-environment (cons "NELISP_STANDALONE_TARGET=windows-x86_64" process-environment)))
    (append (nelisp-standalone--reader-os-source-forms)
            (nelisp-standalone--reader-cold-source-forms))))

(ert-deftest nelisp-windows-cold-partial-io-and-failure ()
  "Run actual emitted loops against short transfers, EOF, errors and DWORD caps."
  (let* ((forms (nelisp-windows-cold-test--os))
         (memory (make-hash-table)) (limit 3) (ok 1) (calls nil))
    (cl-letf (((symbol-function 'nelisp-windows-cold-test--address) (lambda (_) 4096))
              ((symbol-function 'ptr-write-u32) (lambda (p off value) (puthash (+ p off) value memory)))
              ((symbol-function 'ptr-read-u32) (lambda (p off) (gethash (+ p off) memory 0)))
              ((symbol-function 'atomic-compare-exchange)
               (lambda (p old new) (if (= (gethash p memory 0) old) (progn (puthash p new memory) 1) 0)))
              ((symbol-function 'atomic-fetch-add)
               (lambda (p delta) (puthash p (+ (gethash p memory 0) delta) memory)))
              ((symbol-function 'alloc-bytes) (lambda (&rest _) (error "Arena allocation during cold I/O")))
              ((symbol-function 'nelisp-windows-cold-test--extern)
               (lambda (api _h p count counter _overlap)
                 (push (list api p count) calls)
                 (puthash counter (min count limit) memory) ok))
              ((symbol-function 'nl_os_read_file_handle)
               (nelisp-windows-cold-test--function forms 'nl_os_read_file_handle))
              ((symbol-function 'nl_os_write_file_handle)
               (nelisp-windows-cold-test--function forms 'nl_os_write_file_handle))
              ((symbol-function 'nl_fa_read_all)
               (nelisp-windows-cold-test--function nelisp-windows-cold-test--file-helpers 'nl_fa_read_all))
              ((symbol-function 'nl_fa_write_all)
               (nelisp-windows-cold-test--function nelisp-windows-cold-test--file-helpers 'nl_fa_write_all)))
      (dolist (function '(nl_fa_read_all nl_fa_write_all))
        (setq calls nil)
        (should (= (funcall function 7 100 8 0) 8))
        (should (equal (mapcar #'cadr (reverse calls)) '(100 103 106)))
        (setq limit 0)
        (should (= (funcall function 7 100 8 0) 0))
        (setq limit 3 ok 0)
        (should (= (funcall function 7 100 8 0) 0))
        (setq ok 1))
      (should (= (nl_os_read_file_handle -1 100 8) -1))
      (nl_os_write_file_handle 7 100 4294967296)
      (should (= (nth 2 (car calls)) 2147483647))
      (should (= (gethash 4096 memory) 0))
      (should (= (gethash 4112 memory) 0)))))

(ert-deftest nelisp-windows-cold-commit-before-publish ()
  "Both reservation paths commit; failure releases only the unpublished mapping."
  (let* ((process-environment (cons "NELISP_STANDALONE_TARGET=windows-x86_64" process-environment))
         (function (nelisp-windows-cold-test--function (nelisp-standalone--cold-domain-forms) 'nl_cold_grow_chunk0))
         (memory (make-hash-table)) (events nil) (commit 1) (size 65536))
    (puthash 8 1000 memory)
    (cl-letf (((symbol-function 'nelisp-windows-cold-test--address)
               (lambda (symbol) (if (eq symbol 'nl_arena_base) 8 16)))
              ((symbol-function 'ptr-read-u64)
               (lambda (p off) (if (= (+ p off) 1216) size (gethash (+ p off) memory 0))))
              ((symbol-function 'ptr-write-u64)
               (lambda (p off v) (push 'write events) (puthash (+ p off) v memory)))
              ((symbol-function 'nl_os_alloc_chunk) (lambda (_) (push 'reserve events) 2000))
              ((symbol-function 'nl_os_commit_range) (lambda (&rest _) (push 'commit events) commit))
              ((symbol-function 'nl_os_free_chunk) (lambda (&rest _) (push 'free events) 1))
              ((symbol-function 'nl_cold_realloc_chunk0) (lambda (&rest _) (push 'metadata events) 0)))
      (should (= (funcall function 32768) 0))
      (should (equal events '(commit)))
      (setq events nil commit 0)
      (should (= (funcall function 32768) -1))
      (should (equal events '(commit)))
      (setq events nil)
      (should (= (funcall function 131072) -1))
      (should (equal (reverse events) '(reserve commit free)))
      (should (= (gethash 8 memory) 1000))
      (setq events nil commit 1)
      (should (= (funcall function 131072) 0))
      (should (equal (cl-subseq (reverse events) 0 3) '(reserve commit write)))
      (should (= (gethash 8 memory) 2000)))))

(ert-deftest nelisp-windows-cold-diagnostic-and-emission ()
  "All rejection paths avoid allocation and compile through the Win64 emitter."
  (let ((forms (nelisp-windows-cold-test--os)))
    (dolist (name '(nl_cold_diag nl_cold_diag_bad_header nl_cold_diag_bad_reloc nl_cold_diag_bad_digest))
      (let ((definition (nelisp-windows-cold-test--definition forms name)))
        (should-not (nelisp-windows-cold-test--contains definition 'alloc-bytes))
        (should-not (nelisp-windows-cold-test--contains definition 'syscall-direct))
        (should (> (length (plist-get (nelisp-aot-compile-to-link-unit definition :arch 'x86_64 :format 'coff) :text)) 0))))
    (dolist (name '(nl_os_read_file_handle nl_os_write_file_handle nl_os_open_read nl_os_open_write_truncate nl_os_argv_init))
      (let ((definition (nelisp-windows-cold-test--definition forms name)))
        (should-not (nelisp-windows-cold-test--contains definition 'alloc-bytes))
        (should (> (length (plist-get (nelisp-aot-compile-to-link-unit definition :arch 'x86_64 :format 'coff) :text)) 0))))))

(ert-deftest nelisp-windows-cold-dump-commit-failure ()
  "A refused scratch commit releases the mapping before any write or open."
  (let ((function (nelisp-windows-cold-test--function
                   nelisp-windows-cold-test--file-helpers 'bf_arena_dump_image_stream))
        (events nil) (result nil))
    (cl-letf (((symbol-function 'wf_arg_ptr) (lambda (&rest _) 100))
              ((symbol-function 'nl_bi_make_cpath) (lambda (&rest _) 100))
              ((symbol-function 'alloc-bytes) (lambda (&rest _) 200))
              ((symbol-function 'ptr-read-u64) (lambda (&rest _) 0))
              ((symbol-function 'nl_align_up) (lambda (v _) v))
              ((symbol-function 'nl_mc_total) (lambda () 1048576))
              ((symbol-function 'nelisp-windows-cold-test--address) (lambda (_) 4096))
              ((symbol-function 'nl_mc_imgoff) (lambda (&rest _) 0))
              ((symbol-function 'nl_os_alloc_chunk) (lambda (_) (push 'reserve events) 8192))
              ((symbol-function 'nl_build_digest_stamped_p) (lambda () 1))
              ((symbol-function 'nl_os_commit_range) (lambda (&rest _) (push 'commit events) 0))
              ((symbol-function 'nl_os_free_chunk) (lambda (&rest _) (push 'free events) 1))
              ((symbol-function 'ptr-write-u64) (lambda (&rest _) (error "write before commit")))
              ((symbol-function 'nl_os_open_write_truncate) (lambda (&rest _) (error "open before commit")))
              ((symbol-function 'wf_write_int) (lambda (_out value) (setq result value))))
      (funcall function 100 200)
      (should (= result -1))
      (should (equal (reverse events) '(reserve commit free))))))

(ert-deftest nelisp-windows-cold-environment-allowlist ()
  (let* ((process-environment '("NELISP_STANDALONE_TARGET=windows-x86_64"
                                "SystemRoot=C:/Windows" "WINDIR=C:/Windows" "SystemDrive=C:"
                                "ComSpec=C:/Windows/System32/cmd.exe" "TEMP=C:/Temp" "TMP=C:/Temp"
                                "PATH=C:/User/bin" "HOME=C:/secret" "NELISP_NATIVE_CACHE=C:/secret"
                                "EMACSLOADPATH=C:/secret"))
         (environment (nelisp-standalone--cold-build-environment)))
    (should (member "SystemRoot=C:/Windows" environment))
    (should (member "TEMP=C:/Temp" environment))
    (should (member "PATH=C:/Windows/System32;C:/Windows" environment))
    (should-not (cl-some (lambda (v) (string-match-p "secret\\|User" v)) environment))))

(ert-deftest nelisp-windows-cold-process-reinit ()
  "Evaluate the real Windows reinit source against stale process-owned values."
  (let* ((process-environment '("NELISP_STANDALONE_TARGET=windows-x86_64"))
         (forms (nelisp-standalone--reader-cold-reinit-forms 'src 'cursor 'result 'pool 'out 'ctx 'builtin-sym))
         (find-call nil)
         (_finder (setq find-call (lambda (form)
                      (when (consp form)
                        (if (eq (car form) 'sexp-write-str-lit) form
                          (cl-some (lambda (child) (funcall find-call child)) form))))))
         (source (nth 2 (funcall find-call forms))))
    (cl-progv '(nelisp--environment process-environment temporary-file-directory user-emacs-directory
                nelisp-native-windows-directory-handles nelisp-native-cache--addresses nelisp-native-cache--gccjit-handles)
        '((("TEMP" . "C:/FreshTemp") ("APPDATA" . "C:/FreshApp")) ("stale=1") "stale" "stale"
          (1234) (5678) (9012))
      (eval (read (concat "(progn " source ")")))
      (should (member "TEMP=C:/FreshTemp" (symbol-value 'process-environment)))
      (should (equal (symbol-value 'temporary-file-directory) "C:/FreshTemp"))
      (should (equal (symbol-value 'user-emacs-directory) "C:/FreshApp/.emacs.d/"))
      (dolist (name '(nelisp-native-windows-directory-handles nelisp-native-cache--addresses nelisp-native-cache--gccjit-handles))
        (should-not (symbol-value name))))))

(ert-deftest nelisp-windows-cold-wine-full-recipe ()
  "The requested full image is produced by the PE with target paths and OS env."
  (let* ((directory (make-temp-file "windows-cold-recipe-" t))
         (binary (expand-file-name "reader.exe" directory))
         (image (concat binary ".cold"))
         (process-environment '("NELISP_STANDALONE_TARGET=windows-x86_64"
                                "NELISP_STANDALONE_NATIVE_COMPILER_COLD=1"
                                "NELISP_STANDALONE_COLD_RUNNER=wine" "WINEPREFIX=/chosen-prefix"
                                "HOME=/secret" "NELISP_NATIVE_CACHE=/secret"))
         (nelisp-standalone--native-cache-source-receipt nil)
         (native-comp-enable-subr-trampolines nil)
         (captured nil) (dump-environment nil))
    (unwind-protect
        (cl-letf (((symbol-function 'load) (lambda (&rest _) t))
                  ((symbol-function 'nelisp-standalone--target-runnable-on-host-p) (lambda (&rest _) nil))
                  ((symbol-function 'call-process)
                   (lambda (program _input _destination _display &rest args)
                     (cond ((equal program "winepath")
                            (should (equal (getenv "WINEPREFIX") "/chosen-prefix"))
                            (insert (concat "Z:" (nth 1 args) "\n")))
                           ((equal (car args) "cmd")
                            (insert "SystemRoot=C:/Windows\nWINDIR=C:/Windows\nTEMP=C:/Temp\nPATH=C:/secret\nHOME=C:/secret\n"))
                           (t
                            (should (equal program "wine"))
                            (should (equal (cadr args) "--eval"))
                            (setq captured (nth 2 args) dump-environment process-environment)
                            (with-temp-file image (insert "123"))
                            (insert "3"))) 0)))
          (nelisp-standalone--build-cold-image binary)
          (should (string-match-p "nelisp-native-cache-prepare-cold-compiler" captured))
          (should-not (string-match-p "prepare-cold-template" captured))
          (should (string-match-p "Z:.*nelisp-template-bytecode" captured))
          (should (member "SystemRoot=C:/Windows" dump-environment))
          (should (member "PATH=C:/Windows/System32;C:/Windows" dump-environment))
          (should (member "WINEPREFIX=/chosen-prefix" dump-environment))
          (should-not (cl-some (lambda (entry) (string-match-p "secret" entry)) dump-environment))
          (should (file-exists-p image)))
      (delete-directory directory t))))

(provide 'nelisp-windows-cold-test)
