;;; nelisp-native-corpus-u10-projection-test.el --- Projection integrity -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'ert)
(let ((load-path (cons (expand-file-name "support" (file-name-directory load-file-name)) load-path)))
  (require 'native-corpus-u10-projection))

(ert-deftest u10-projection/exact-readback-and-mutations ()
  (let* ((function (make-byte-code 0 (unibyte-string 192 135) [42] 1))
         (row (list :opcode 192 :function function :gnu '(42 "abc")))
         (expected (list row (list :opcode 193 :function function :gnu '(42))))
         (changed-code (make-byte-code 0 (unibyte-string 192 136) [42] 1))
         (mutations (list (list (plist-put (copy-sequence row) :function changed-code) (cadr expected))
                          (list (plist-put (copy-sequence row) :gnu '(43 "abc")) (cadr expected))
                          (list row) (list row row) (reverse expected)
                          (list (plist-put (copy-sequence row) :opcode 191) (cadr expected)))))
    (should (u10-projection-validate (copy-tree expected t) expected))
    (dolist (mutation mutations)
      (should-error (u10-projection-validate mutation expected)))
    (let ((protected (list function '((error nil (42))))))
      (should (u10-projection-validate (copy-tree protected t) protected))
      (should-error (u10-projection-validate (list changed-code (cadr protected)) protected))
      (should-error (u10-projection-validate (list function '((error nil (43)))) protected)))))

(ert-deftest u10-projection/write-authenticates-serialized-object ()
  (let ((directory (make-temp-file "u10-projection-" t))
        (function (make-byte-code 0 (unibyte-string 192 135) [42] 1)))
    (unwind-protect
        (let* ((rows (list (list :opcode 192 :function function :gnu '(42))))
               (metadata (u10-projection-write directory rows function '((error nil (42))))))
          (should (= (length metadata) 2))
          (dolist (unit metadata)
            (with-temp-buffer
              (set-buffer-multibyte nil)
              (insert-file-contents-literally (expand-file-name (concat (car unit) ".el") directory))
              (should (equal (cdr unit) (secure-hash 'sha256 (current-buffer))))))
          (cl-letf (((symbol-function 'u10-projection-validate)
                     (lambda (&rest _) (error "Broken readback"))))
            (should-error (u10-projection-write directory rows function nil))))
      (delete-directory directory t))))
