;;; nelisp-native-funcall-v2-exits-test.el --- Allocation proof controls -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'ert)
(require 'cl-lib)
(defvar f1b-domain-test-expected nil)
(defconst f1b-domain-test-root (expand-file-name ".." (file-name-directory (or load-file-name buffer-file-name))))
(defun f1b-domain-test-definition ()
  (with-temp-buffer
    (insert-file-contents (expand-file-name "templates/nelisp-native-rooted-abi-proof.el.in" f1b-domain-test-root))
    (goto-char (point-min))
    (let (form)
      (cl-labels ((walk (node)
                    (when (consp node)
                      (if (and (eq (car node) 'defun)
                               (eq (cadr node) 'nelisp-native-rooted-abi-proof--environment-domain-p))
                          (setq form node)
                        (walk (car node)) (walk (cdr node))))))
        (while (not form) (walk (read (current-buffer)))))
      (setq form (cl-subst 'f1b-domain-test-check 'nelisp-native-rooted-abi-proof--environment-domain-p form))
      (eval (cl-subst 'f1b-domain-test-expected 'nelisp-native-rooted-abi-proof--expected form) t))))
(defun f1b-domain-test-run (cold mutations &optional owner)
  (f1b-domain-test-definition)
  (let* ((arena 4096) (env (+ arena 1032)) (witness 8192)
         (size (if cold 287768576 268435456))
         (memory (make-hash-table))
         (f1b-domain-test-expected '(:arena-protocol (:header-domain single-u64-low32-size-low3-mark
                                                      :initial-chunk-bytes 268435456))))
    (dolist (pair (list (cons arena 1152) (cons (+ arena 704) (+ arena 768))
                       (cons (+ arena 768) arena) (cons (+ arena 776) size)
                       (cons (+ arena 792) (+ arena 1024)) (cons (+ arena 800) (+ arena size))
                       (cons (+ arena 1024) 128)
                       (cons witness (if cold arena 0)) (cons (+ witness 8) (if cold size 0))))
      (puthash (car pair) (cdr pair) memory))
    (dolist (pair mutations) (puthash (car pair) (cdr pair) memory))
    (cl-letf (((symbol-function 'ptr-read-u64) (lambda (address offset) (gethash (+ address offset) memory 0)))
              ((symbol-function 'ptr-call) (lambda (&rest _) (or owner env))))
      (f1b-domain-test-check arena env witness 1234))))
(ert-deftest f1b/domain-normal-and-authenticated-cold ()
  (should (f1b-domain-test-run nil nil))
  (should (f1b-domain-test-run t nil)))
(ert-deftest f1b/domain-larger-normal-descriptor-refused ()
  (should-error (f1b-domain-test-run nil '((4872 . 287768576) (4896 . 287772672))))
  (should-error (f1b-domain-test-run t '((8192 . 0) (8200 . 0)))))
(ert-deftest f1b/domain-cold-witness-bound-base-and-alignment ()
  (dolist (mutation '(((8192 . 4104)) ((8200 . 287768577)) ((8200 . 17179869184))))
    (should-error (f1b-domain-test-run t mutation))))
(ert-deftest f1b/domain-exact-owner-and-live-sized-block ()
  (should-not (f1b-domain-test-run t nil 5136))
  (dolist (word '(130 8 4294967288))
    (should-not (f1b-domain-test-run t (list (cons 5120 word))))))
(provide 'nelisp-native-funcall-v2-exits-test)
