;;; nelisp-eln-raw-call-metadata-test.el --- metadata argument guard -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(let ((root (getenv "NELISP_ROOT"))
      (overlay (file-name-directory
                (directory-file-name
                 (file-name-directory (or load-file-name buffer-file-name))))))
  (add-to-list 'load-path (expand-file-name "lisp" overlay))
  (when root
    (add-to-list 'load-path (expand-file-name "lisp" root))
    (add-to-list 'load-path (expand-file-name "packages/nl-ffi/src" root))))
(require 'nelisp-eln-raw-call)
(require 'nelisp-eln-metadata-arena)

(defmacro nelisp-eln-raw-call-metadata-test--mock-arena (&rest body)
  `(let ((nelisp-eln-metadata-arena--pool nil)
         (nelisp-eln-metadata-arena--live nil)
         (nelisp-eln-metadata-arena--base-lease nil)
         (next-address 1048584))
     (cl-letf (((symbol-function 'nelisp-eln-objects-symbol-base-acquire)
                (lambda () (vector 'lease (vector nil 2097152))))
               ((symbol-function 'nl-ffi-memory-allocate)
                (lambda (size)
                  (prog1 (vector size next-address)
                    (setq next-address (+ next-address size)))))
               ((symbol-function 'nl-ffi-memory-address)
                (lambda (owner) (aref owner 1)))
               ((symbol-function 'nl-ffi-memory-release) (lambda (_) t)))
       ,@body)))

(defun nelisp-eln-raw-call-metadata-test--assert-rejected (word)
  (let ((context (vector nelisp-eln-raw-call--context-marker
                         (vector 'owner 65536) (vector 'owner 69632) nil nil))
        (entered nil))
    (cl-letf (((symbol-function 'nelisp-eln-raw-call--ensure-trampoline)
               (lambda () (setq entered 'trampoline) 1))
              ((symbol-function 'nl-ffi-memory-address)
               (lambda (owner) (aref owner 1)))
              ((symbol-function 'nelisp-eln-raw-call--write-word)
               (lambda (&rest _) (setq entered 'write)))
              ((symbol-function 'ptr-call)
               (lambda (&rest _) (setq entered 'native) 0))
              ((symbol-function 'nelisp-eln-raw-call--read-word)
               (lambda (&rest _) 0)))
      (should-error (nelisp-eln-raw-call-word context 65536 (list word))
                    :type 'nelisp-eln-raw-call-error)
      (should-not entered)
      (should-not (aref context 3)))))

(ert-deftest nelisp-eln-raw-call/rejects-live-retired-and-reused-metadata-words ()
  (nelisp-eln-raw-call-metadata-test--mock-arena
   (let* ((token (nelisp-eln-metadata-arena-acquire))
          (arena (aref token 1))
          (address (nelisp-eln-metadata-arena-reserve token 8))
          (base (aref (aref nelisp-eln-metadata-arena--base-lease 1) 1))
          (signed (- address base))
          (words (list (+ address 5) signed
                       (nelisp-eln-abi-normalize-word signed))))
     (dolist (word words)
       (nelisp-eln-raw-call-metadata-test--assert-rejected word))
     (nelisp-eln-metadata-arena-release token)
     (dolist (word words)
       (nelisp-eln-raw-call-metadata-test--assert-rejected word))
     (let ((reused (nelisp-eln-metadata-arena-acquire)))
       (should (eq arena (aref reused 1)))
       (dolist (word words)
         (nelisp-eln-raw-call-metadata-test--assert-rejected word))
       (nelisp-eln-metadata-arena-release reused)))))

(ert-deftest nelisp-eln-raw-call/ordinary-nil-and-fixnum-words-still-call ()
  (let ((context (vector nelisp-eln-raw-call--context-marker 'argv 'out nil nil))
        (written nil)
        (called nil)
        (checker (symbol-function
                  'nelisp-eln-metadata-arena-projected-word-p)))
    (aset context 1 (vector 'owner 65536))
    (aset context 2 (vector 'owner 69632))
    (unwind-protect
        (progn
          (fmakunbound 'nelisp-eln-metadata-arena-projected-word-p)
          (cl-letf (((symbol-function 'nl-ffi-memory-address)
                     (lambda (owner) (aref owner 1)))
                    ((symbol-function 'nelisp-eln-raw-call--ensure-trampoline)
                     (lambda () 1))
                    ((symbol-function 'nelisp-eln-raw-call--write-word)
                     (lambda (_address offset word)
                       (push (cons offset word) written)))
                    ((symbol-function 'ptr-call)
                     (lambda (&rest _) (setq called t) 0))
                    ((symbol-function 'nelisp-eln-raw-call--read-word)
                     (lambda (&rest _) 123)))
            (should (= 123 (nelisp-eln-raw-call-word context 65536 '(0 17))))
            (should called)
            (should (equal (nreverse written) '((0 . 0) (8 . 17)
                                                (16 . 0) (24 . 0)
                                                (32 . 0) (40 . 0))))
            (should-not (aref context 3))))
      (fset 'nelisp-eln-metadata-arena-projected-word-p checker))))

(when (getenv "NELISP_METADATA_ARENA_STANDALONE")
  (let* ((token (nelisp-eln-metadata-arena-acquire))
         (address (nelisp-eln-metadata-arena-reserve token 8))
         (base (aref (aref nelisp-eln-metadata-arena--base-lease 1) 1))
         (word (+ address 5))
         (signed (- address base))
         (unsigned (nelisp-eln-abi-normalize-word signed))
         (argv (nl-ffi-memory-allocate 48))
         (out (nl-ffi-memory-allocate 8))
         (context (vector nelisp-eln-raw-call--context-marker argv out nil nil))
         (entered nil))
    (unwind-protect
        (progn
          (cl-letf (((symbol-function 'nelisp-eln-raw-call--ensure-trampoline)
                     (lambda () (setq entered t) 1))
                    ((symbol-function 'nelisp-eln-raw-call--write-word)
                     (lambda (&rest _) (setq entered t)))
                    ((symbol-function 'ptr-call)
                     (lambda (&rest _) (setq entered t) 0)))
            (dolist (candidate (list word signed unsigned))
              (should-error (nelisp-eln-raw-call-word context 65536
                                                      (list candidate))
                            :type 'nelisp-eln-raw-call-error)))
          (should-not entered)
          (should-not (aref context 3))
          (nelisp-eln-metadata-arena-release token)
          (princ "raw-call-metadata-standalone: PASS\n"))
      (nl-ffi-memory-release argv)
      (nl-ffi-memory-release out))))

(provide 'nelisp-eln-raw-call-metadata-test)
;;; nelisp-eln-raw-call-metadata-test.el ends here
