;;; Compare installed native definitions with the running interpreted prelude. -*- lexical-binding: t; -*-
(defvar fp-cases nil)
(defvar fp-root (getenv "FP_FIXTURE"))
(defvar fp-stems '("" "." ".." "../a" "a/../b" "a//b" "a/./b/" "~" "~/a/../b" "/" "//" "/../a" "/../../a" "/tmp/" "相対/名" "日本語/../電気/" "é/δ" "missing" "exists.txt" "subdir/"))
(let ((i 0))
  (while (< i 2000)
    (let* ((stem (nth (% i (length fp-stems)) fp-stems))
           (path (cond ((= i 0) (concat fp-root "/exists.txt"))
                       ((= i 1) (concat fp-root "/subdir/"))
                       ((= i 2) (concat fp-root "/missing"))
                       ((< i 20) stem)
                       ((= (% i 4) 0) (concat fp-root "/" stem))
                       ((= (% i 4) 1) stem)
                       ((= (% i 4) 2) (concat stem "/../p" (number-to-string i)))
                       (t (concat stem "/" (number-to-string i) "/")))))
      (setq fp-cases
            (cons (cond
                   ((eq fp-name 'expand-file-name)
                    (if (= (% i 3) 0) (list path) (list path (if (= (% i 3) 1) fp-root "relative/base"))))
                   ((eq fp-name 'directory-files)
                    (list path (= (% i 2) 0) (if (= (% i 3) 0) "[^.]" nil) t (if (= (% i 4) 0) 3 nil)))
                   ((eq fp-name 'locate-file)
                    (list path (list fp-root (concat fp-root "/missing")) (if (= (% i 2) 0) '("" ".el") nil)))
                   (t (list path))) fp-cases)))
    (setq i (1+ i))))
(setq fp-cases (nreverse fp-cases))
;; File existence's Lisp fast path must retain the old classifier's answers.
(when (eq fp-name 'file-exists-p)
  (let ((legacy (lambda (filename)
                  (let ((s (nelisp--syscall-stat filename)))
                    (or (eq s 'file) (eq s 'directory))))))
    (dolist (args (append fp-cases '((nil) (42) ([a]) ((a b)) ("a\0b"))))
      (let ((old (condition-case e (list 'value (apply legacy args)) (error (list 'error e))))
            (new (condition-case e (list 'value (apply fp-original args)) (error (list 'error e)))))
        (unless (equal old new) (error "Existence fast path changed %S: %S != %S" args new old))))
    (princ "P34-EXISTENCE-REFERENCE-PASS cases=2005\n")))

(defun fp-evaluate (function args)
  (condition-case err (list 'value (apply function args))
    (error (list 'error err))))
(unless fp-native
  (let ((sample nil) (i 0))
    (while (< i 40) (setq sample (cons (nth (* i 49) fp-cases) sample) i (1+ i)))
    (garbage-collect)
    (let ((start (float-time)) (round 0))
      (while (< round 3)
        (dolist (args sample) (fp-evaluate fp-name args))
        (setq round (1+ round)))
      (princ (format "FP-BASELINE|%s|seconds=%.9f|calls=120|\n" fp-name (- (float-time) start)))))
  (when (eq fp-name 'locate-file)
    (let ((dirs nil) (i 0))
      (while (< i 4083)
        (setq dirs (cons (concat fp-root "/synthetic/" (number-to-string i)) dirs) i (1+ i)))
      (garbage-collect)
      (let* ((start (float-time)) (result (locate-file "never-present" dirs '("" ".el" ".elc"))))
        (unless (null result) (error "Synthetic directory miss unexpectedly hit: %S" result))
        (princ (format "FP-LOCATE-MISS|interpreted|dirs=4083|suffixes=3|seconds=%.6f|result=%S|\n"
                       (- (float-time) start) result)))))
  (princ "FP-BASELINE-DONE\n")
  (throw 'fp-baseline-only t))
(defvar fp-reference nil)
(fset fp-name fp-original)
(dolist (args fp-cases) (setq fp-reference (cons (fp-evaluate fp-name args) fp-reference)))
(setq fp-reference (nreverse fp-reference))
(princ (format "FP-REFERENCE-DONE|%s|cases=2000|\n" fp-name))
(when (getenv "FP_NEGATIVE") (setcar fp-reference '(value deliberate-corruption)))
(fset fp-name fp-native)
(let ((reference fp-reference) (cases fp-cases) (count 0) (mismatches 0))
  (while cases
    (let ((actual (fp-evaluate fp-name (car cases))))
      (unless (equal actual (car reference))
        (setq mismatches (1+ mismatches))
        (when (< mismatches 4)
          (princ (format "FP-MISMATCH|%S|expected=%S|actual=%S|\n" (car cases) (car reference) actual)))
        (when (getenv "FP_NEGATIVE")
          (princ "FP-NEGATIVE-DETECTED\n")
          (error "Deliberately corrupted reference was detected"))))
    (setq reference (cdr reference) cases (cdr cases) count (1+ count))
    (when (or (= count 1) (= (% count 250) 0))
      (princ (format "FP-CORPUS-PROGRESS|%s|checked=%d|mismatches=%d|\n" fp-name count mismatches))))
  (princ (format "FP-PARITY|%s|cases=%d|mismatches=%d|\n" fp-name count mismatches))
  (unless (= mismatches 0) (error "Parity corpus mismatches: %d" mismatches)))
;; Avoid paying the entire corpus again just to measure: fixed mixed sample.
(defvar fp-sample nil)
(let ((i 0))
  (while (< i 40) (setq fp-sample (cons (nth (* i 49) fp-cases) fp-sample) i (1+ i))))
(defun fp-time (function)
  (fset fp-name function)
  (garbage-collect)
  (let ((start (float-time)) (n 0) (round 0))
    (while (< round 3)
      (dolist (args fp-sample) (fp-evaluate fp-name args) (setq n (1+ n)))
      (setq round (1+ round)))
    (list (- (float-time) start) n)))
(let* ((before (fp-time fp-original)) (after (fp-time fp-native)))
  (princ (format "FP-TIME|%s|interpreted=%.9f|native=%.9f|calls=%d|speedup=%.6f|\n"
                 fp-name (car before) (car after) (cadr before) (/ (car before) (car after)))))
(when (eq fp-name 'locate-file)
  (let ((dirs nil) (i 0))
    (while (< i 4083)
      (setq dirs (cons (concat fp-root "/synthetic/" (number-to-string i)) dirs) i (1+ i)))
    (dolist (implementation (list fp-original fp-native))
      (fset fp-name implementation)
      (garbage-collect)
      (let* ((start (float-time)) (result (locate-file "never-present" dirs '("" ".el" ".elc")))
             (seconds (- (float-time) start)))
        (unless (null result) (error "Synthetic directory miss unexpectedly hit: %S" result))
        (princ (format "FP-LOCATE-MISS|%s|dirs=4083|suffixes=3|seconds=%.6f|result=%S|\n"
                       (if (eq implementation fp-original) "interpreted" "native") seconds result))))))
(fset fp-name fp-original)
(princ "FP-BENCH-DONE\n")
