;;; Frame admission does not authorize native CALL execution. -*- lexical-binding: t; -*-
(require 'ert)
(require 'nelisp-bytecode-compiler-input)
(require 'nelisp-bytecode-native-rooted-cfg-plan)

(defun nelisp-input-call-test--function ()
  ;; Two original argument slots; CALL1, CONS, discard, then return X.
  (make-byte-code 514 (unibyte-string 1 1 33 1 66 136 135) [] 4))

(ert-deftest nelisp-input-call/genuine-callees-and-identity ()
  (skip-unless (equal emacs-version "31.1"))
  (let* ((wrapper (nelisp-input-call-test--function))
         (capture (list 'captured))
         (closure (lambda (x) (cons capture x)))
         (input (nelisp-bytecode-compiler-input-build wrapper)))
    (dolist (callee (list (lambda (x) x)
                         (lambda (x &optional y) (cons x y))
                         (lambda (x &rest tail) (cons x tail)) closure))
      (should (= (funcall wrapper callee 7) 7)))
    (should (eq (car (funcall closure 7)) capture))
    (should (eq (plist-get input :function) wrapper))
    (should (eq (plist-get input :status) 'complete))
    (should-not (plist-get input :call1-symbol-template-p))
    ;; Funcall lowers through the F1 generic call bridge since F2.
    (should (eq (plist-get (nelisp-bytecode-native-rooted-cfg-plan input) :status)
                'complete))))

(ert-deftest nelisp-input-call/counterfeits ()
  (let* ((f (nelisp-input-call-test--function))
         (ir (nelisp-bytecode-ir-validate (aref f 1) [] 2))
         (frame (nelisp-bytecode-frame-ir-build (aref f 1) [] 2)))
    (should (nelisp-bytecode-compiler-input--call-ir-supported-p ir frame))
    (dolist (mutation '(pc reason opcode nargs stack))
      (let ((bad (copy-tree ir t)) (bad-frame (copy-tree frame t)))
        (pcase mutation
          ('pc (plist-put bad :unsupported '((99 . unsupported-semantics))))
          ('reason (plist-put bad :unsupported '((2 . unknown-opcode))))
          ('opcode (aset (aref (plist-get bad :instructions) 2) 1 55))
          ('nargs (aset (aref (plist-get bad :instructions) 2) 3 2))
          ('stack (plist-put (aref (plist-get (aref (plist-get bad-frame :blocks) 0)
                                                   :instructions) 2) :inputs nil)))
        (should-not (nelisp-bytecode-compiler-input--call-ir-supported-p bad bad-frame))))))

(ert-deftest nelisp-input-call/malformed-and-unknown ()
  (dolist (code (list (unibyte-string 55 135) (unibyte-string 38)
                     (unibyte-string 33 135)))
    (should-not (eq (plist-get (nelisp-bytecode-compiler-input-build
                               (make-byte-code 0 code [] 2)) :status) 'complete))))

(ert-deftest nelisp-input-call/all-call-encodings ()
  (skip-unless (equal emacs-version "31.1"))
  (dotimes (index 8)
    (let* ((opcode (+ 32 index))
           (code (apply #'unibyte-string
                        (append '(192) (make-list index 193)
                                (cond ((= opcode 38) '(38 6))
                                      ((= opcode 39) '(39 7 0))
                                      (t (list opcode))) '(135))))
           (function (make-byte-code 0 code [ignore nil] (1+ index))))
      (should-not (funcall function))
      (should (eq (plist-get (nelisp-bytecode-compiler-input-build function) :status)
                  'complete)))))
