;;; nelisp-native-raw-file-test.el --- Raw reader cleanup controls -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
;; Native names must exist while capturing owners; the model tests the exact
;; internal implementation, without claiming native primitive authentication.
(dolist (name '(syscall-direct ptr-write-u8 ptr-read-bytes
               nelisp--target-os-code nelisp--target-arch-code))
  (unless (fboundp name) (fset name (lambda (&rest _) (error "Model only")))))
(require 'nelisp-native-raw-file)
(ert-deftest nelisp-native-raw-file-model-window-and-cleanup ()
  (dolist (mode '(success short close-failure))
    (let ((calls nil) (writes nil)
          (expected (unibyte-string 0 128 255 65)))
      (cl-letf (((symbol-function 'syscall-direct)
                 (lambda (number &rest args)
                   (push (cons number args) calls)
                   (cond ((= number 9) 4096) ((= number 2) 7)
                         ((= number 17) (if (eq mode 'short) 3 4))
                         ((= number 3) (if (eq mode 'close-failure) -1 0))
                         ((= number 11) 0) (t (error "Unexpected syscall")))))
                ((symbol-function 'ptr-write-u8)
                 (lambda (_base offset byte) (push (cons offset byte) writes)))
                ((symbol-function 'ptr-read-bytes)
                 (lambda (address size)
                   (should (= address 4099)) (should (= size 4)) expected)))
        (if (eq mode 'success)
            (should (equal (nelisp-native-raw-file--read "ab" 9 4) expected))
          (should-error (nelisp-native-raw-file--read "ab" 9 4)))
        (should (equal (mapcar #'car (reverse calls)) '(9 2 17 3 11)))
        (should (equal (reverse writes) '((0 . 97) (1 . 98) (2 . 0))))
        (should (= (nth 4 (assq 17 calls)) 9))))))
(ert-deftest nelisp-native-raw-file-bound-refuses-before-syscall ()
  (let ((calls 0))
    (cl-letf (((symbol-function 'syscall-direct)
               (lambda (&rest _) (setq calls (+ calls 1)) 0)))
      (dolist (args (list (list "a" -1 1) (list "a" 0 1048577)
                         (list "a" 134217728 1) (list "a\0b" 0 1)))
        (should-error (apply #'nelisp-native-raw-file--read args)))
      (should (= calls 0)))))

(ert-deftest nelisp-native-raw-file-platform-before-syscall ()
  (let ((original-owners nelisp-native-raw-file--owners))
    (unwind-protect
        (dolist (codes '((0 0) (1 0) (0 1) (2 0)))
          (let ((calls 0))
            (cl-letf (((symbol-function 'nelisp--target-os-code) (lambda () (car codes)))
                      ((symbol-function 'nelisp--target-arch-code) (lambda () (cadr codes)))
                      ((symbol-function 'subrp) (lambda (_) t))
                      ((symbol-function 'syscall-direct)
                       (lambda (&rest _) (setq calls (+ calls 1)) -1)))
              ;; Only simulate owner classes here; the actual native positive
              ;; is a separate bounded probe using the unchanged byte fixture.
              (setq nelisp-native-raw-file--owners
                    (mapcar (lambda (entry)
                              (cons (car entry) (symbol-function (car entry))))
                            original-owners))
              (should-error (nelisp-native-raw-file-read "a" 0 1))
              (should (= calls (if (equal codes '(0 0)) 1 0))))))
      (setq nelisp-native-raw-file--owners original-owners))))
