;;; nelisp-runtime-reload-abi-regression.el --- Shared host/native ABI controls -*- lexical-binding: t; -*-
(require 'cl-lib)
(require 'nelisp-native-load)
(require 'nelisp-runtime-reload-abi)
(defvar print-circle nil)
(defun nelisp-runtime-reload-abi-regression-assert (value name)
  (unless value (error "ABI assertion failed: %s" name))
  (princ (format "PASS %s\n" name)))

(defun nelisp-runtime-reload-abi-regression-run ()
  "Run all 51 cache controls with private memo state dynamically isolated."
  (let ((nelisp-runtime-reload--digest-cache nil))
(let ((calls 0) (hash (symbol-function 'secure-hash)))
  (cl-letf (((symbol-function 'secure-hash)
             (lambda (&rest args) (setq calls (1+ calls)) (apply hash args))))
    (nelisp-runtime-reload-contract-hash)
    (nelisp-runtime-reload-contract-hash)
    (nelisp-runtime-reload-abi-regression-assert (= calls 1) "unchanged-input-hash-once")))
(let* ((digest (nelisp-runtime-reload-contract-hash)) (words nil) (reads 0))
  (dotimes (i 8)
    (push (string-to-number (substring digest (* i 8) (* (1+ i) 8)) 16) words))
  (setq words (nreverse words))
  (cl-letf (((symbol-function 'nelisp--native-runtime-contract-word)
             (lambda (i) (setq reads (1+ reads)) (nth i words))))
    (nelisp-runtime-reload-abi-regression-assert (nelisp-runtime-reload-contract-matches-p) "native-match")
    (nelisp-runtime-reload-abi-regression-assert (= reads 8) "eight-native-words")
    (setcar words (1+ (car words)))
    (setq reads 0)
    (nelisp-runtime-reload-abi-regression-assert (not (nelisp-runtime-reload-contract-matches-p)) "native-mismatch")
    (nelisp-runtime-reload-abi-regression-assert (= reads 8) "eight-native-words-on-mismatch")))
(let* ((nelisp-runtime-reload-symbols (copy-tree nelisp-runtime-reload-symbols))
       (original (nelisp-runtime-reload-contract-hash)))
  (setcar nelisp-runtime-reload-symbols "changed-resolver")
  (nelisp-runtime-reload-abi-regression-assert (not (equal original (nelisp-runtime-reload-contract-hash))) "list-mutation")
  (let ((name (copy-sequence (car nelisp-runtime-reload-symbols))))
    (setcar nelisp-runtime-reload-symbols name)
    (setq original (nelisp-runtime-reload-contract-hash))
    (aset name 0 ?X)
    (nelisp-runtime-reload-abi-regression-assert (not (equal original (nelisp-runtime-reload-contract-hash))) "string-mutation")))
(let ((original (nelisp-runtime-reload-contract-hash)))
  (let ((returned (nelisp-runtime-reload-contract-hash)))
    (aset returned 0 ?X)
    (nelisp-runtime-reload-abi-regression-assert (equal original (nelisp-runtime-reload-contract-hash)) "returned-digest-is-private"))
  (cl-letf (((symbol-function 'secure-hash) (lambda (&rest _) (make-string 64 ?a))))
    (nelisp-runtime-reload-abi-regression-assert (equal (nelisp-runtime-reload-contract-hash) (make-string 64 ?a)) "hash-helper-replacement"))
  (nelisp-runtime-reload-abi-regression-assert (equal original (nelisp-runtime-reload-contract-hash)) "hash-helper-restoration"))
(let ((nelisp-runtime-reload-symbols (copy-tree nelisp-runtime-reload-symbols))
      (hash (symbol-function 'secure-hash)))
  (cl-letf (((symbol-function 'secure-hash)
             (lambda (&rest args)
               (prog1 (apply hash args)
                 (setcar nelisp-runtime-reload-symbols "changed-during-hash")))))
    (nelisp-runtime-reload-contract-hash)
    (nelisp-runtime-reload-abi-regression-assert (null nelisp-runtime-reload--digest-cache) "mutation-during-hash-not-cached")))
(dolist (bad (list (let ((v (list "cycle"))) (setcdr v v) v)))
  (let ((nelisp-runtime-reload-symbols bad))
    (nelisp-runtime-reload-abi-regression-assert (condition-case nil (progn (nelisp-runtime-reload-contract-hash) nil)
                 (error t)) "bounded-refusal")))
(let* ((shared (list "shared"))
       (nelisp-runtime-reload-symbols (list shared shared)))
  (nelisp-runtime-reload-abi-regression-assert (equal (nelisp-runtime-reload-contract-hash)
                    (nelisp-runtime-reload--contract-hash-slow)) "shared-acyclic-dag"))
(let ((calls 0) (hash (symbol-function 'nelisp-native-load-sha256)))
  (cl-letf (((symbol-function 'nelisp-native-load-sha256)
             (lambda (bytes) (setq calls (1+ calls)) (funcall hash bytes))))
    (nelisp-runtime-reload-contract-hash)
    (nelisp-runtime-reload-contract-hash)
    (nelisp-runtime-reload-abi-regression-assert (= calls 1) "loader-provider-context-hit")
    (let ((nelisp-native-load-page-bytes (+ nelisp-native-load-page-bytes 4096)))
      (nelisp-runtime-reload-contract-hash))
    (nelisp-runtime-reload-abi-regression-assert (= calls 2) "loader-page-config-invalidation")))
(dolist (bad (list (make-vector 49 nil)
                  (let ((cycle (list nil))) (setcdr cycle cycle) cycle)))
  (cl-letf (((symbol-function 'nelisp-native-load-sha256-dependency-context)
             (lambda () bad)))
    (nelisp-runtime-reload-contract-hash)
    (nelisp-runtime-reload-abi-regression-assert (null nelisp-runtime-reload--digest-cache) "malformed-provider-not-cached")))
(let* ((shared (list "shared\n"))
       (nelisp-runtime-reload-symbols (list shared shared))
       (print-circle nil))
  (nelisp-runtime-reload-contract-hash)
  (let ((print-circle t))
    (nelisp-runtime-reload-abi-regression-assert (equal (nelisp-runtime-reload-contract-hash)
                      (nelisp-runtime-reload--contract-hash-slow)) "printer-circle-transition")
    (setq nelisp-runtime-reload-symbols (list (list "shared\n") (list "shared\n")))
    (nelisp-runtime-reload-abi-regression-assert (equal (nelisp-runtime-reload-contract-hash)
                      (nelisp-runtime-reload--contract-hash-slow)) "printer-sharing-topology")
    (nelisp-runtime-reload-abi-regression-assert (null nelisp-runtime-reload--digest-cache) "printer-circle-bypass")))
(dolist (setting '((print-escape-newlines . t) (print-escape-control-characters . t)
                   (print-escape-nonascii . t) (print-escape-multibyte . t)
                   (print-integers-as-characters . t) (print-quoted . nil)
                   (print-symbols-bare . t) (print-gensym . t)
                   (print-continuous-numbering . t)
                   (print-charset-text-property . t)))
  (nelisp-runtime-reload-contract-hash)
  (let* ((symbol (car setting)) (present (boundp symbol))
         (old (and present (symbol-value symbol))))
    (unwind-protect
        (progn
          (set symbol (cdr setting))
          (nelisp-runtime-reload-abi-regression-assert (equal (nelisp-runtime-reload-contract-hash)
                            (nelisp-runtime-reload--contract-hash-slow)) "printer-dynamic-semantics")
          (nelisp-runtime-reload-abi-regression-assert (null nelisp-runtime-reload--digest-cache) "printer-dynamic-bypass"))
      (if present (set symbol old) (makunbound symbol)))))
(let* ((name (copy-sequence "nl_property_probe"))
       (nelisp-runtime-reload-symbols (list name)))
  (nelisp-runtime-reload-contract-hash)
  (put-text-property 0 1 'face 'bold name)
  (nelisp-runtime-reload-abi-regression-assert (equal (nelisp-runtime-reload-contract-hash)
                    (nelisp-runtime-reload--contract-hash-slow)) "property-added-parity")
  (nelisp-runtime-reload-abi-regression-assert (null nelisp-runtime-reload--digest-cache) "property-added-bypass")
  (set-text-properties 0 (length name) nil name)
  (nelisp-runtime-reload-abi-regression-assert (equal (nelisp-runtime-reload-contract-hash)
                    (nelisp-runtime-reload--contract-hash-slow)) "property-removed-parity")
  (put-text-property 3 4 'face 'bold name)
  (nelisp-runtime-reload-abi-regression-assert (equal (nelisp-runtime-reload-contract-hash)
                    (nelisp-runtime-reload--contract-hash-slow)) "property-after-zero-parity")
  (nelisp-runtime-reload-abi-regression-assert (null nelisp-runtime-reload--digest-cache) "property-after-zero-bypass"))
(dolist (value (list 65537 'unexpected-symbol (make-string 8193 ?x)))
  (let ((nelisp-runtime-reload-symbols (list value)))
    (nelisp-runtime-reload-abi-regression-assert (equal (nelisp-runtime-reload-contract-hash)
                      (nelisp-runtime-reload--contract-hash-slow)) "noncanonical-scalar-parity")
    (nelisp-runtime-reload-abi-regression-assert (null nelisp-runtime-reload--digest-cache) "noncanonical-scalar-bypass")))
(princ "ABI-MEMO-COMPLETE\n")

    t))
(provide 'nelisp-runtime-reload-abi-regression)

