;;; Native VM vector value, root, epoch and fallback controls. -*- lexical-binding: t; -*-
(load (expand-file-name "vm-vector-helpers.el" fp-out) nil t t)
(setq p35-vm-count 0)
(defun p35-vm-check (condition label)
 (setq p35-vm-count (1+ p35-vm-count))
 (unless condition (error "ARRAY-CONTROL-FAILED %S" label)))
(defun p35-vm-condition (function arguments)
 (condition-case e (list 'value (apply function arguments)) (error (list 'error (car e) (cdr e)))))
(dolist (name '(p35-vm-read p35-vm-write p35-vm-gc-read p35-vm-gc-write p35-vm-read-loop p35-vm-write-loop p35-vm-read-epoch p35-vm-write-epoch))
 (p35-vm-check (byte-code-function-p (symbol-function name)) (list 'bytecode name)))
(let ((values (list nil t 0 1 -1 -2 -2305843009213693952 2305843009213693951
                    'symbol :keyword (make-symbol "audit-uninterned") "ascii" "日本語"
                    1.5 (cons 'a 'b) (vector 1 2) 18446744073709551616)))
 (dolist (value values)
  (let* ((v (vector value)) (read (p35-vm-read v 0)))
   (p35-vm-check (equal value read) 'read-value)
   (when (or (consp value) (vectorp value) (stringp value) (symbolp value))
    (p35-vm-check (eq value read) 'read-identity))
   (p35-vm-check (equal (p35-vm-write v 0 value) value) 'write-return)
   (p35-vm-check (equal (p35-vm-read v 0) value) 'write-read)
   (when (or (consp value) (vectorp value) (stringp value) (symbolp value))
    (p35-vm-check (eq value (p35-vm-read v 0)) 'write-identity)))))
(let ((v (vector nil)))
 (p35-vm-check (eq (p35-vm-write v 0 v) v) 'self-write)
 (p35-vm-check (eq (p35-vm-read v 0) v) 'self-read))
(let* ((cell (cons 1 2)) (v (vector nil)))
 (p35-vm-write v 0 cell) (setcdr cell 99)
 (p35-vm-check (= (cdr (p35-vm-read v 0)) 99) 'later-cons-mutation))
(let ((v (vector nil)))
 (let ((value (p35-vm-gc-write v 0 (cons 'live 'boxed) #'garbage-collect)))
  (p35-vm-check (eq value (p35-vm-read v 0)) 'gc-write-root)
  (setcdr value 'survived)
  (garbage-collect)
  (p35-vm-check (equal (p35-vm-read v 0) '(live . survived)) 'gc-after-write)))
(p35-vm-check (equal (p35-vm-gc-read (vector (cons 'root 'live)) 0 #'garbage-collect) '(root . live)) 'gc-read-root)
(let ((v (vector 1 2 3)) (address (+ (ptr-read-u64 (string-to-number (getenv "FP_VM_ARENA_BASE") 16) 0) 88)))
 (p35-vm-read-epoch v 1 address) (p35-vm-write-epoch v 1 8 address)
 (p35-vm-check (= (p35-vm-read-epoch v 1 address) 0) 'read-epoch)
 (p35-vm-check (= (p35-vm-write-epoch v 1 9 address) 1) 'write-epoch))
;; Dedicated GNU bytecode ignores later rebinding of AREf/ASET themselves.
(let ((ar (symbol-function 'aref)) (aw (symbol-function 'aset)) (v (vector 7)))
 (unwind-protect
  (progn (fset 'aref (lambda (&rest ignored) 'wrong)) (fset 'aset (lambda (&rest ignored) 'wrong))
   (p35-vm-check (= (p35-vm-read v 0) 7) 'read-fset)
   (p35-vm-check (= (p35-vm-write v 0 8) 8) 'write-fset))
  (fset 'aref ar) (fset 'aset aw)))
;; The existing vector-shaped nemacs character table is a bridge, not raw slots.
(let ((read-old (and (fboundp 'emacs-char-table-aref) (symbol-function 'emacs-char-table-aref)))
      (write-old (and (fboundp 'emacs-char-table-aset) (symbol-function 'emacs-char-table-aset)))
      (calls nil) (v (vector '--nemacs-char-table nil nil nil nil nil nil)))
 (unwind-protect
  (progn
   (fset 'emacs-char-table-aref (lambda (array index) (setq calls (cons (list 'read index) calls)) 731))
   (fset 'emacs-char-table-aset (lambda (array index value) (setq calls (cons (list 'write index value) calls)) 732))
   (p35-vm-check (= (p35-vm-read v 0) 731) 'bridge-read)
   (p35-vm-check (= (p35-vm-write v 1 45) 732) 'bridge-write)
   (p35-vm-check (equal calls '((write 1 45) (read 0))) 'bridge-callback-order)
   (p35-vm-check (null (nelisp--raw-aref v 1)) 'bridge-no-raw-write))
  (if read-old (fset 'emacs-char-table-aref read-old) (fmakunbound 'emacs-char-table-aref))
  (if write-old (fset 'emacs-char-table-aset write-old) (fmakunbound 'emacs-char-table-aset))))
;; Snapshot exact conditions for differential old/new comparison.
(dolist (args (list (list [1] -1) (list [1] 1) (list [] 0) (list [1] nil) (list [1] 1.0) (list 7 0) (list "abc" 1) (list "abc" 9)))
 (p35-vm-check (equal (p35-vm-condition #'p35-vm-read args)
                         (p35-vm-condition #'aref args)) 'read-condition))
(dolist (args (list (list [1] nil 3) (list [1] 1.0 3) (list 7 0 3) (list (copy-sequence "abc") 1 90) (list (copy-sequence "abc") 9 90)))
 (p35-vm-check (equal (p35-vm-condition #'p35-vm-write args)
                         (p35-vm-condition #'aset args)) 'write-condition))

(princ (format "P35-VECTOR-VM-PASS controls=%d\n" p35-vm-count))

