;;; Interpreter-to-native boundary acceptance -*- lexical-binding: t; -*-
(require 'nelisp-native-cache)
(require 'nelisp-bytecode-native-consumer)
(setq nelisp-native-cache-backend (intern (getenv "FP_BACKEND")))
(defvar fp-name (intern (getenv "FP_NAME")))
(defvar fp-out (getenv "FP_OUT"))
(princ (format "P34-BOOT %s %s\n" fp-name (getenv "FP_PHASE")))
(defvar fp-function (nelisp-bytecode-native-consumer-read-elc-function
                    (expand-file-name (concat "input-" (symbol-name fp-name) ".elc") fp-out) fp-name))
(defvar fp-native nil)
(princ (format "P34-ARTIFACT file=%S\n" (nelisp-native-cache-file fp-function)))
(if (equal (getenv "FP_PHASE") "compile")
    (let ((file (nelisp-native-cache-file fp-function)))
      ;; Each compile receipt measures a fresh producer, never a cache hit.
      ;; FP_OUT owns this private cache; qualification artifacts are expendable.
      (when (and file (file-exists-p file)) (delete-file file))
      (when (and file (file-exists-p (concat file ".nelh"))) (delete-file (concat file ".nelh")))
      (let ((start (float-time)))
      (princ (format "P34-COMPILE file=%S seconds=%.9f\n"
                     (nelisp-native-cache-compile fp-function) (- (float-time) start)))))
  (setq fp-native (nelisp-native-cache-load fp-function))
  (unless fp-native (error "Native cache miss: %S" nelisp-native-cache--disabled-reason))
  (unless (or (eq nelisp-native-cache-backend 'template) (subrp fp-native))
    (error "Native boundary still uses an interpreted wrapper"))
  (princ (format "P34-CALLABLE direct=%S\n" (subrp fp-native)))
  (when (and (subrp fp-native) (memq fp-name '(p34-arith3 p34-optional p34-rest)))
    (unless (equal (func-arity fp-native)
                   (cond ((eq fp-name 'p34-arith3) '(3 . 3))
                         ((eq fp-name 'p34-optional) '(1 . 3)) (t '(1 . many))))
      (error "Native callable arity metadata mismatch"))
    (princ "P34-ARITY-METADATA-PASS\n"))
  (when (eq fp-name 'emacs-redisplay--ml-spans)
    (load (expand-file-name "gui-helpers.el" fp-out) nil t))
  (load (expand-file-name (concat "source-" (symbol-name fp-name) ".el") fp-out) nil t)
  (defvar fp-original (symbol-function fp-name))
  (defun fp-trust-counts ()
    (list nelisp-bytecode-native-rooted-cfg-contract--validation-count
          nelisp-native-load--rooted-cfg-outer-validation-count
          nelisp-native-load--raw-v2-check-count nelisp-native-load--trusted-map-count
          nelisp-native-template--validation-count))
  (defvar fp-trust-before (fp-trust-counts))
  (when (eq fp-name 'file-exists-p)
    (let ((owner (symbol-function 'nelisp--syscall-path-int)) (calls 0))
      (unwind-protect
          (progn
            (fset 'nelisp--syscall-path-int
                  (lambda (nr path mode) (setq calls (1+ calls)) -1))
            (unless (null (funcall fp-native "/tmp")) (error "Native OS call ignored rebound miss"))
            (fset 'nelisp--syscall-path-int
                  (lambda (nr path mode) (setq calls (1+ calls)) 0))
            (unless (eq (funcall fp-native "/tmp") t) (error "Native OS call ignored rebound hit"))
            (unless (= calls 2) (error "Native OS call bypassed live function cell"))
            (princ "P34-OS-REBINDING-PASS calls=2\n"))
        (fset 'nelisp--syscall-path-int owner))))

  (when (and (equal (getenv "FP_PHASE") "parity")
             (memq fp-name '(file-exists-p file-name-directory expand-file-name directory-files locate-file)))
    (load (expand-file-name "test/nelisp-native-boundary-file-corpus.el" (getenv "FP_ROOT")) nil t))
  (defvar fp-cases nil)
  (setq fp-cases
        (cond ((eq fp-name 'p34-arith3) '((2 3 4) (-2 3 4) (0 0 0) (9 -2 8) ("bad" 3 4) (2 0.5 4)))
              ((eq fp-name 'p34-optional) '((1) (1 2) (1 2 3) (nil nil nil)))
              ((eq fp-name 'p34-rest) '((1) (1 2) (1 2 3 4) (nil nil nil) (1 nil (a b) [v])))
              ((eq fp-name 'p34-values)
               (append '((nil nil) (t t) (42 42) (42 -42) (1.0 1.0)
                         (9223372036854775808 9223372036854775808)
                         (symbol symbol) (symbol other) ("same" "same")
                         ("a" "b") ((a b) (a b)) ([a] [a]))
                       (mapcar (lambda (value) (list value value))
                               (list (make-symbol "x") (cons 1 2) (vector 1) (copy-sequence "same")))))
              ((eq fp-name 'emacs-redisplay--ml-spans)
               '((nil nil nil 80 0) ("plain" nil nil 80 0 t)
                 ("" nil nil 80 0) (("a" "b") nil face 80 0 t)
                 ((:propertize "a" face bold) nil face 80 0)
                 ((:eval (+ 20 22)) nil nil 80 0)
                 ((4 "a") nil nil 80 0) ((missing "a" "b") nil nil 80 0)
                 ("ignored" nil nil 80 51) ("é日本語" nil face 80 0 t)))
              (t (mapcar (lambda (p)
                           (cond ((eq fp-name 'expand-file-name) (list p))
                                 ((eq fp-name 'directory-files) (list p nil nil t 3))
                                 ((eq fp-name 'locate-file) (list p (list fp-out) '("" ".el")))
                                 (t (list p))))
                         (list "" "." ".." "/" "/tmp/" "a//b" "a/../b" "é/日本語"
                               (expand-file-name "fixture/exists.txt" fp-out)
                               (expand-file-name "fixture/missing" fp-out))))))
  (defun fp-observe (fn args)
    (condition-case err (list 'value (apply fn args)) (error (list 'error err))))
  (let ((count 0) (values 0) (errors 0))
    (dolist (args fp-cases)
      (let ((expected (fp-observe fp-original args)) (actual (fp-observe fp-native args)))
        (unless (equal actual expected) (error "P34 mismatch %S: %S != %S" args actual expected))
        (if (eq (car expected) 'value) (setq values (1+ values)) (setq errors (1+ errors))))
      (setq count (1+ count)))
    (when (and (eq fp-name 'emacs-redisplay--ml-spans) (< values 3))
      (error "GUI parity lacks successful value cases: %d" values))
    (princ (format "P34-PARITY cases=%d\n" count))
    (princ (format "P34-PARITY-OBSERVATIONS values=%d errors=%d\n" values errors)))
  ;; Arity errors must be detected, even for the unbounded rest lane.
  (when (memq fp-name '(p34-optional p34-rest))
    (unless (eq (car (cadr (fp-observe fp-native nil))) 'wrong-number-of-arguments)
      (error "Missing required argument accepted"))
    (when (eq fp-name 'p34-optional)
      (unless (eq (car (cadr (fp-observe fp-native '(1 2 3 4)))) 'wrong-number-of-arguments)
        (error "Excess optional argument accepted"))))
  (when (eq fp-name 'p34-rest)
    (let* ((tail (list 'one 'two)) (result (apply fp-native 1 nil tail)))
      (setcar (nth 2 result) 'changed)
      (unless (equal tail '(one two)) (error "REST aliases APPLY input"))
      (princ "P34-REST-COPY-PASS\n")))
  (when (and (eq fp-name 'p34-values) (equal (getenv "FP_PHASE") "parity"))
    ;; The early GNU bytecode projection of EQUAL must retain recursive
    ;; vector/cons semantics. Opcode 154's shallow vector comparison cannot
    ;; certify plans merely because leaf predicate cases happen to agree.
    (let ((count 0))
      (dolist (case '(([a [b]] [a [b]] t) ([a [b]] [a [c]] nil)
                      ((a [b "日本語"]) (a [b "日本語"]) t)
                      ((a [b "日本語"]) (a [c "日本語"]) nil)
                      ((a . b) (a . b) t) ((a . b) (a . c) nil)
                      ([] [] t) ([] [nil] nil) (nil nil t) (nil t nil)
                      (1 1 t) (1 1.0 nil) (1.5 1.5 t) (1.5 2.5 nil)
                      (9223372036854775808 9223372036854775808 t)
                      ("a\\b\n日本語" "a\\b\n日本語" t)))
        (unless (eq (equal (nth 0 case) (nth 1 case)) (nth 2 case))
          (error "Structural EQUAL changed: %S" case))
        (setq count (1+ count)))
      (princ (format "P35-STRUCTURAL-EQUAL-PASS cases=%d\n" count)))
    (let ((checked 0))
      (dolist (value (list nil '(a b c) "abc" "日本語" [] [1 [2]]))
        (let ((copy (copy-sequence value)))
          (unless (and (equal value copy) (or (null value) (not (eq value copy))))
            (error "Projected shallow copy changed: %S" value))
          (when (and (vectorp value) (> (length value) 1))
            (unless (eq (aref value 1) (aref copy 1))
              (error "Projected copy became recursive"))))
        (setq checked (1+ checked)))
      (unless (condition-case nil (progn (copy-sequence '(a . b)) nil)
                (wrong-type-argument t))
        (error "Projected copy accepted an improper list"))
      (setq checked (1+ checked))
      (unless (= (cl-some (lambda (x) (and (> x 2) x)) '(0 2 3 4)) 3)
        (error "Projected cl-some changed its result"))
      (setq checked (1+ checked))
      (unless (and (cl-every (lambda (x) (>= x 0)) '(0 1 2))
                   (not (cl-every (lambda (x) (>= x 0)) '(0 -1 2))))
        (error "Projected cl-every changed its result"))
      (setq checked (1+ checked))
      (let ((calls 0))
        (unless (and (null (cl-some (lambda (_x) (setq calls (1+ calls))) nil))
                     (cl-every (lambda (_x) (setq calls (1+ calls))) nil)
                     (= calls 0))
          (error "Projected sequence helper called its predicate on empty input")))
      (setq checked (1+ checked))
      (unless (and (hash-table-p (make-hash-table :test 'eq))
                   (not (hash-table-p nil)) (not (hash-table-p '(1 2)))
                   (not (hash-table-p [hash-table])))
        (error "Projected hash-table-p changed its representation predicate"))
      (setq checked (+ checked 4))
      (dolist (pair (list (cons nil nil) (cons 7 nil) (cons '(1 2) nil)
                         (cons fp-function t) (cons (lambda () 1) t) (cons fp-native t)))
        (unless (eq (functionp (car pair)) (cdr pair))
          (error "Projected functionp changed callable classification"))
        (setq checked (1+ checked)))
      (dolist (pair (list (cons (lambda () 1) t) (cons fp-function nil)
                         (cons fp-native (eq nelisp-native-cache-backend 'template))))
        (unless (eq (interpreted-function-p (car pair)) (cdr pair))
          (error "Projected interpreted-function-p changed classification"))
        (setq checked (1+ checked)))
      (let* ((leaf (list 'inner)) (vector (vector leaf))
             (tree (cons leaf 'tail))
             (copy (copy-tree tree))
             (shallow (copy-tree vector)) (deep (copy-tree vector t)))
        (unless (and (equal tree copy) (not (eq tree copy))
                     (not (eq leaf (car copy))))
          (error "Projected copy-tree changed a dotted cons tree"))
        (setq checked (1+ checked))
        (unless (eq vector shallow) (error "COPY-TREE copied an unrequested vector"))
        (setq checked (1+ checked))
        (unless (and (equal vector deep) (not (eq vector deep))
                     (not (eq leaf (aref deep 0))))
          (error "COPY-TREE did not recursively copy a requested vector"))
        (setq checked (1+ checked))
        (unless (eq (copy-tree 'atom t) 'atom) (error "COPY-TREE changed an atom"))
        (setq checked (1+ checked)))
      (dolist (pair '((nil 0) ((a b) 2) ((a . b) nil)))
        (unless (equal (proper-list-p (car pair)) (cadr pair))
          (error "Projected proper-list-p changed a finite list"))
        (setq checked (1+ checked)))
      (unless (equal (plist-put nil 'a 7) '(a 7)) (error "PLIST-PUT empty result changed"))
      (setq checked (1+ checked))
      (let ((value (list 'a 1)))
        (unless (and (eq value (plist-put value 'a 2)) (equal value '(a 2)))
          (error "PLIST-PUT changed an existing key's mutation/identity")))
      (setq checked (1+ checked))
      (let ((value (list 'a 1)))
        (unless (and (eq value (plist-put value 'b 2)) (equal value '(a 1 b 2)))
          (error "PLIST-PUT append changed mutation/identity")))
      (setq checked (1+ checked))
      (let ((value (list (copy-sequence "key") 1)))
        (unless (and (eq value (plist-put value (copy-sequence "key") 2 #'equal))
                     (= (length value) 2) (= (cadr value) 2))
          (error "PLIST-PUT ignored its custom predicate")))
      (setq checked (1+ checked))
      (unless (condition-case nil (progn (plist-put '(a) 'b 2) nil)
                (wrong-type-argument t))
        (error "PLIST-PUT accepted a malformed unmatched list"))
      (setq checked (1+ checked))
      (princ (format "P35-HELPER-PROJECTION-PASS cases=%d\n" checked)))
    (let ((checked 0))
      (dolist (name '(mapc reverse vconcat nelisp--check-seq-list))
        (unless (byte-code-function-p (symbol-function name))
          (error "Sequence helper was not projected: %S" name))
        (setq checked (1+ checked)))
      (dolist (seq (list nil '(a b c) [] [a b c] "abc" "日本語"))
        (let ((seen nil))
          (unless (and (eq (mapc (lambda (x) (setq seen (cons x seen))) seq) seq)
                       (equal (nreverse seen) (append seq nil)))
            (error "MAPC changed order or input identity: %S" seq)))
        (setq checked (1+ checked)))
      (let ((calls 0))
        (unless (condition-case err
                    (progn (mapc (lambda (_x) (setq calls (1+ calls))) '(a . b)) nil)
                  (wrong-type-argument (and (equal err '(wrong-type-argument listp b)) (= calls 0))))
          (error "MAPC changed malformed-sequence precheck")))
      (setq checked (1+ checked))
      (let ((calls 0))
        (unless (condition-case err
                    (progn (mapc (lambda (x) (setq calls (1+ calls)) (when (eq x 'b) (error "callback"))) '(a b c)) nil)
                  (error (and (equal err '(error "callback")) (= calls 2))))
          (error "MAPC changed callback unwind")))
      (setq checked (1+ checked))
      (dolist (pair (list (list nil nil) (list '(a b c) '(c b a))
                         (list [] []) (list [a b c] [c b a])
                         (list "abc" "cba") (list "日本語" "語本日")))
        (let* ((seq (car pair)) (saved (copy-sequence seq)) (actual (reverse seq)))
          (unless (and (equal actual (cadr pair)) (equal seq saved)
                       (or (null seq) (not (eq seq actual))))
            (error "REVERSE changed value, type, input or copy identity")))
        (setq checked (1+ checked)))
      (dolist (pair (list (list nil []) (list '(nil nil) [])
                         (list (list '(a b) [c] "d") [a b c 100])
                         (list (list "日本語") [26085 26412 35486])))
        (unless (equal (apply #'vconcat (car pair)) (cadr pair))
          (error "VCONCAT changed concatenation: %S" pair))
        (setq checked (1+ checked)))
      (dolist (fn '(vconcat nelisp--check-seq-list))
        (unless (condition-case err (progn (funcall fn '(a . b)) nil)
                  (wrong-type-argument (equal err '(wrong-type-argument listp b))))
          (error "Sequence helper changed improper-list condition: %S" fn))
        (setq checked (1+ checked)))
      (dolist (seq (list nil '(a b) [] [a] "a"))
        (unless (eq (nelisp--check-seq-list seq) seq)
          (error "Sequence validation changed identity"))
        (setq checked (1+ checked)))
      (let ((seen nil))
        (mapc (lambda (_x) (setq seen (cons (copy-sequence (symbol-value 'seq)) seen))) '(1 2 3))
        (unless (equal (nreverse seen) '((1 2 3) (2 3) (3)))
          (error "MAPC projection changed dynamic callback scope")))
      (setq checked (1+ checked))
      (princ (format "P35-SEQUENCE-PROJECTION-PASS cases=%d\n" checked)))
    (let* ((owner (symbol-function 'nelisp-bytecode-jit--runtime-dispatch))
           (caller #[0 "\300\207" [7] 1]) (checked 0))
      (unless (and (byte-code-function-p owner) (listp (aref owner 0)))
        (error "Default JIT dispatcher did not preserve dynamic descriptor"))
      (setq checked (1+ checked))
      (dolist (args '(nil (1) (1 2) (1 2 3 4 5)))
        (unless (null (apply owner args)) (error "Default JIT dispatcher result changed"))
        (setq checked (1+ checked)))
      (unless (= (funcall caller) 7) (error "Default JIT dispatcher recursed or handled a call"))
      (setq checked (1+ checked))
      (unwind-protect
          (let ((calls 0))
            (fset 'nelisp-bytecode-jit--runtime-dispatch
                  (lambda (&rest _arguments) (setq calls (1+ calls)) (vector t 'handled)))
            (unless (and (eq (funcall caller) 'handled) (= calls 1))
              (error "JIT dispatcher replacement was not used"))
            (setq checked (1+ checked))
            (fset 'nelisp-bytecode-jit--runtime-dispatch
                  (lambda (&rest _arguments) (error "JIT replacement error")))
            (unless (condition-case err (progn (funcall caller) nil)
                      (error (equal err '(error "JIT replacement error"))))
              (error "JIT dispatcher replacement error was lost"))
            (setq checked (1+ checked)))
        (fset 'nelisp-bytecode-jit--runtime-dispatch owner))
      (unless (= (funcall caller) 7) (error "JIT dispatcher restoration failed"))
      (setq checked (1+ checked))
      (princ (format "P35-JIT-STUB-PROJECTION-PASS controls=%d\n" checked)))
    (let ((constants (aref (symbol-function 'vconcat) 2)) (private nil) (i 0))
      (while (< i (length constants))
        (let ((value (aref constants i)))
          (when (and (symbolp value) (not (eq value (intern (symbol-name value)))))
            (setq private t)))
        (setq i (1+ i)))
      (unless private (error "Prelude bytecode lost its private gensym")))
    (let ((original (symbol-function 'nelisp--check-seq-list))
          (tail-bound (boundp 'tail))
          (tail-value (and (boundp 'tail) (symbol-value 'tail))) (calls 0))
      (unwind-protect
          (progn
            (set 'tail 'outer-tail-sentinel)
            (fset 'nelisp--check-seq-list
                  (lambda (seq)
                    (unless (eq (symbol-value 'tail) 'outer-tail-sentinel)
                      (error "Prelude projection exposed its private tail binding"))
                    (setq calls (1+ calls))
                    (funcall original seq)))
            ;; The two input checks plus the Lisp vector constructor's rest
            ;; list check must all observe the unchanged public binding.
            (unless (and (equal (vconcat '(1 2) [3]) [1 2 3]) (= calls 3))
              (error "Prelude gensym callback check did not execute")))
        (fset 'nelisp--check-seq-list original)
        (if tail-bound (set 'tail tail-value) (makunbound 'tail))))
    (princ "P35-GENSYM-PROJECTION-PASS controls=2\n")
    (load (expand-file-name "test/nelisp-native-vm-vector-fixture.el" (getenv "FP_ROOT")) nil t t)
    (load (expand-file-name "test/nelisp-native-vm-arithmetic-fixture.el" (getenv "FP_ROOT")) nil t t)
    (load (expand-file-name "test/nelisp-native-vm-call-difference-fixture.el" (getenv "FP_ROOT")) nil t t)
    (load (expand-file-name "test/nelisp-native-vm-frame-cold-fixture.el" (getenv "FP_ROOT")) nil t t)
    (load (expand-file-name "test/nelisp-native-vm-dynamic-frame-cold-fixture.el" (getenv "FP_ROOT")) nil t t)
    (p35-vm-frame-run fp-out)
    (p35-vm-dynamic-frame-run fp-out)
    (let* ((owner (symbol-function 'nelisp--prn-symbol-escaped-uncached))
           (calls 0) (nelisp--prn-symbol-cache (make-hash-table :test 'equal)))
      (unwind-protect
          (progn
            (fset 'nelisp--prn-symbol-escaped-uncached
                  (lambda (s) (setq calls (1+ calls)) (funcall owner s)))
            (dolist (name '("plain" "12" "." "" "a b" "[a]" "日本語" "a\\b"))
              (let ((expected (funcall owner name)))
                (unless (and (equal (nelisp--prn-symbol-escaped name) expected)
                             (equal (nelisp--prn-symbol-escaped (copy-sequence name)) expected))
                  (error "Cached symbol escaping changed %S" name))))
            (unless (= calls 8) (error "Repeated symbols were not memoized: %d" calls))
            (let ((key (copy-sequence "mutable")) (value nil))
              (setq value (nelisp--prn-symbol-escaped key))
              (aset key 0 ?X) (aset value 0 ?Y)
              (unless (equal (nelisp--prn-symbol-escaped "mutable") "mutable")
                (error "Mutable key/result poisoned atom cache")))
            (let ((hit (nelisp--prn-symbol-escaped "mutable")))
              (aset hit 0 ?Z)
              (unless (equal (nelisp--prn-symbol-escaped "mutable") "mutable")
                (error "Cached HIT result exposed cache storage")))
            (dotimes (i 1100) (nelisp--prn-symbol-escaped (concat "symbol-" (number-to-string i))))
            (unless (= (hash-table-count nelisp--prn-symbol-cache) 1024)
              (error "Atom cache exceeded its capacity"))
            (princ "P35-ATOM-CACHE-PASS unique=1109 capacity=1024\n"))
        (fset 'nelisp--prn-symbol-escaped-uncached owner))))
  (when (equal (getenv "FP_PHASE") "timing")
    (defvar fp-calls (string-to-number (getenv "FP_CALLS")))
    (defvar fp-caller
      (nelisp-bytecode-native-consumer-read-elc-function
       (expand-file-name (concat "caller-" (symbol-name fp-name) ".elc") fp-out)
       (intern (concat "p34-caller-" (symbol-name fp-name)))))
    (defvar fp-call-attestation 0)
    (fset fp-name (lambda (&rest args)
                    (setq fp-call-attestation (1+ fp-call-attestation))
                    (apply fp-original args)))
    (if (eq fp-name 'p34-arith3) (funcall fp-caller 3)
      (funcall fp-caller 3 (if (eq fp-name 'file-exists-p) "/tmp" "/tmp/a")))
    (unless (= fp-call-attestation 3) (error "Caller did not execute its three target calls"))
    (princ "P34-CALLER-ATTESTATION calls=3\n")
    (defun fp-time (function)
      (fset fp-name function)
      (garbage-collect)
      (let ((start (float-time)))
        (let ((result (if (eq fp-name 'p34-arith3) (funcall fp-caller fp-calls)
                        (funcall fp-caller fp-calls (if (eq fp-name 'file-exists-p) "/tmp" "/tmp/a")))))
          (unless (equal result (cond ((eq fp-name 'p34-arith3) 14)
                                     ((eq fp-name 'file-exists-p) t) (t "/tmp/")))
            (error "Timing caller returned the wrong value: %S" result)))
        (- (float-time) start)))
    ;; One timing per fresh process: GC does not restore arena topology.
    (let* ((mode (getenv "FP_TIMING_MODE"))
           (seconds (fp-time (if (equal mode "native") fp-native fp-original))))
      (princ (format "P34-TIME mode=%s seconds=%.9f calls=%d\n" mode seconds fp-calls))))
  (fset fp-name fp-original)
  (unless (equal fp-trust-before (fp-trust-counts))
    (error "Trust checks repeated while calling native code"))
  (princ "P34-CALL-TRUST-DELTA=(0 0 0 0 0)\n"))
(princ "P34-DONE\n")
