;;; Atomic contract reconstruction controls -*- lexical-binding: t; -*-
(require 'ert)
(require 'nelisp-bytecode-native-rooted-cfg-contract)

(defun nelisp-contract-reconstruction-test--fixture (&optional shared guard)
  (let* ((input (nelisp-bytecode-compiler-input-build
                 (byte-compile (lambda (a b) (cons a b)))))
         (plan (nelisp-bytecode-native-rooted-cfg-plan input nil (or guard 'off)))
         (emitted (if shared
                      (nelisp-bytecode-native-rooted-cfg-shared-emit-build
                       plan nelisp-bytecode-native-rooted-cfg-contract-shared-entry)
                    (nelisp-bytecode-native-rooted-cfg-emit plan "nl_native_rooted_cfg_probe_v1")))
         (contract (if shared
                       (nelisp-bytecode-native-rooted-cfg-contract-create-shared-v2 input plan emitted)
                     (nelisp-bytecode-native-rooted-cfg-contract-create input plan emitted))))
    (unless contract (error "Genuine reconstruction fixture unavailable"))
    (list input plan emitted contract)))

(ert-deftest nelisp-contract-reconstruction/atomic-result ()
  (skip-unless (equal emacs-version "31.1"))
  (dolist (shared '(nil t))
    (let* ((fixture (nelisp-contract-reconstruction-test--fixture shared))
           (contract (nth 3 fixture))
           (record (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract :reconstruction)))
      (should (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract))
      (should (equal (plist-get record :input) (nth 0 fixture)))
      (should (equal (plist-get record :plan) (nth 1 fixture)))
      (should (equal (plist-get record :emitted) (nth 2 fixture)))
      (should (equal (plist-get record :expected-contract) contract))
      (let ((dialect (plist-get (plist-get record :input) :dialect-evidence)))
        (should-not (eq (plist-get dialect :dialect)
                        (plist-get (plist-get (nth 0 fixture) :dialect-evidence) :dialect)))
        (aset (plist-get dialect :dialect) 0 ?X)
        (should (equal (plist-get (plist-get (nth 0 fixture) :dialect-evidence) :dialect)
                       "GNU Emacs 31.1")))
      (should-not (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract :forged-mode)))))

(ert-deftest nelisp-contract-reconstruction/fresh-data-and-full-function ()
  (skip-unless (equal emacs-version "31.1"))
  (let* ((base (byte-compile (lambda (a b) (cons a b))))
         (input (nelisp-bytecode-compiler-input-build
                 (make-byte-code (aref base 0) (aref base 1) (aref base 2) (aref base 3) "mutable")))
         (plan (nelisp-bytecode-native-rooted-cfg-plan input nil 'off))
         (emitted (nelisp-bytecode-native-rooted-cfg-shared-emit-build
                   plan nelisp-bytecode-native-rooted-cfg-contract-shared-entry))
         (contract (nelisp-bytecode-native-rooted-cfg-contract-create-shared-v2 input plan emitted))
         (record (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract :reconstruction))
         (returned (plist-get record :input))
         (recipe (plist-get contract :input-recipe)))
    (should record)
    (should (byte-code-function-p (plist-get returned :function)))
    (should (equal returned (nelisp-bytecode-compiler-input-build (plist-get returned :function))))
    (should-not (eq (plist-get returned :function) (plist-get input :function)))
    (should-not (eq (plist-get returned :code) (plist-get recipe :code)))
    (unless (zerop (length (plist-get recipe :constants)))
      (should-not (eq (plist-get returned :constants) (plist-get recipe :constants))))
    (should-not (eq (aref (plist-get returned :function) 4) (plist-get recipe :metadata)))
    (aset (aref (plist-get returned :function) 4) 0 ?z)
    (should (equal (plist-get recipe :metadata) "mutable"))
    (let* ((original '("mutable" ["nested"]))
           (literal (nelisp-bytecode-native-rooted-cfg-contract--snapshot-data original 0)))
      (aset (car literal) 0 ?z)
      (aset (aref (nth 1 literal) 0) 0 ?z)
      (should (equal original '("mutable" ["nested"]))))
    (aset (plist-get returned :code) 0 0)
    (plist-put (plist-get record :expected-contract) :entry "forged")
    (should (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract))
    (let ((fresh (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract :reconstruction)))
      (should (equal (plist-get fresh :input) input))
      (should (equal (plist-get fresh :expected-contract) contract)))))

(ert-deftest nelisp-contract-reconstruction/resigned-mutations-refused ()
  (skip-unless (equal emacs-version "31.1"))
  (let ((contract (nth 3 (nelisp-contract-reconstruction-test--fixture t))))
    (dolist (mutation '((:entry "counterfeit") (:root-count 255)
                        (:entry-ast (defun counterfeit () 0))
                        (:imports ("nl_native_call_v2"))
                        (:input-recipe (:descriptor 0 :code "bad" :constants []
                                        :stack-depth 0 :function-length 7))
                        (:plan (:lowering-mode counterfeit))
                        (:arithmetic-guard-mode counterfeit)))
      (let ((changed (copy-tree contract t)))
        (plist-put changed (car mutation) (cadr mutation))
        (plist-put changed :digest (nelisp-bytecode-native-rooted-cfg-contract--digest changed))
        (should-not (nelisp-bytecode-native-rooted-cfg-contract-valid-p changed))
        (should-not (nelisp-bytecode-native-rooted-cfg-contract-valid-p changed :reconstruction))))
    (dolist (mode '(t :certificate (:reconstruction) (:input forged)))
      (should-not (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract mode)))))

(ert-deftest nelisp-contract-reconstruction/guard-mode-preserved ()
  (skip-unless (equal emacs-version "31.1"))
  (let* ((fixture (nelisp-contract-reconstruction-test--fixture t 'on))
         (contract (nth 3 fixture))
         (record (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract :reconstruction)))
    (should record)
    (should (equal (plist-get record :plan) (nth 1 fixture)))
    (should (eq (plist-get (plist-get record :plan) :arithmetic-guard-mode) 'on))
    (let ((changed (copy-tree contract t)))
      (plist-put (plist-get changed :plan) :arithmetic-guard-mode 'forged)
      (plist-put changed :digest (nelisp-bytecode-native-rooted-cfg-contract--digest changed))
      (should-not (nelisp-bytecode-native-rooted-cfg-contract-valid-p changed :reconstruction)))))

(ert-deftest nelisp-contract-reconstruction/one-rebuild-and-no-cache ()
  (skip-unless (equal emacs-version "31.1"))
  (let* ((contract (nth 3 (nelisp-contract-reconstruction-test--fixture t)))
         (original (symbol-function 'nelisp-bytecode-compiler-input-build)) (calls 0))
    (cl-letf (((symbol-function 'nelisp-bytecode-compiler-input-build)
               (lambda (function) (setq calls (1+ calls)) (funcall original function))))
      (should (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract :reconstruction))
      ;; Plan admission independently rebuilds INPUT too; retain that guard.
      (should (= calls 2))
      (should (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract :reconstruction))
      (should (= calls 4)))))

(ert-deftest nelisp-contract-reconstruction/snapshot-owner-replacement-refused ()
  (skip-unless (equal emacs-version "31.1"))
  (let ((contract (nth 3 (nelisp-contract-reconstruction-test--fixture t))))
    (cl-letf (((symbol-function 'nelisp-bytecode-native-rooted-cfg-contract--snapshot-data)
               (lambda (value _depth) value)))
      (should (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract))
      (should-not (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract :reconstruction)))))

(provide 'nelisp-bytecode-native-rooted-cfg-contract-reconstruction-test)

(ert-deftest nelisp-contract-reconstruction/large-flat-contract ()
  ;; This tests snapshot capacity, not admission of unsupported byte-code shapes.
  (let* ((shared (list (copy-sequence "shared")))
         (data (append (make-list 300 'operation) (list shared shared)))
         (copy (nelisp-bytecode-native-rooted-cfg-contract--snapshot-data data 0)))
    (should (equal copy data))
    (should (eq (nth 300 copy) (nth 301 copy)))
    (should-not (eq (nth 300 copy) shared))
    (aset (car (nth 300 copy)) 0 ?X)
    (should (equal (car shared) "shared"))))

(ert-deftest nelisp-contract-reconstruction/cyclic-nonrecipe-refused ()
  (skip-unless (equal emacs-version "31.1"))
  (let* ((contract (nth 3 (nelisp-contract-reconstruction-test--fixture t)))
         (cycle (list 'operation)))
    (setcdr cycle cycle)
    (plist-put (plist-get contract :plan) :blocks cycle)
    (should-not (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract :reconstruction))
    (let ((vector (vector nil)))
      (aset vector 0 vector)
      (should-error (nelisp-bytecode-native-rooted-cfg-contract--snapshot-data vector 0)))))

(ert-deftest nelisp-contract-reconstruction/cyclic-recipe-refused ()
  (skip-unless (equal emacs-version "31.1"))
  (let* ((contract (nth 3 (nelisp-contract-reconstruction-test--fixture t)))
         (cycle (list 'cycle)))
    (setcdr cycle cycle)
    (plist-put (plist-get contract :input-recipe) :constants (vector cycle))
    (should-not (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract :reconstruction))))
