;;; nelisp-native-prims-u2a-test.el --- U2a frozen primitive lowering -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'ert)
(require 'nelisp-bytecode-native-rooted-cfg-contract)
(require 'nelisp-bytecode-native-rooted-cfg-constructor-contract)
(require 'nelisp-bytecode-native-rooted-cfg-safe-contract)
(require 'nelisp-native-load)
(load "support/native-prims-u2a-fixtures.el" nil t t)
(ert-deftest u2a/exact-family-ordered-roots-and-shared-contract ()
  (dolist (row native-prims-u2a-family)
    (let* ((input (nelisp-bytecode-compiler-input-build (native-prims-u2a-function row)))
           (plan (nelisp-bytecode-native-rooted-cfg-plan input))
           (op (car (plist-get (car (plist-get plan :blocks)) :operations))))
      (should (eq (plist-get input :status) 'complete))
      (should (eq (plist-get plan :status) 'complete))
      (should (eq (plist-get op :opcode) 'primitive-call))
      (should (equal (plist-get op :argument-roots) (number-sequence 1 (nth 2 row))))
      (should (= (plist-get op :argument-count) (nth 2 row)))
      (should (equal (plist-get plan :gateway-imports) '("nl_native_funcall_v2")))
      (let* ((emitted (nelisp-bytecode-native-rooted-cfg-shared-emit-build
                       plan nelisp-bytecode-native-rooted-cfg-contract-shared-entry))
             (contract (nelisp-bytecode-native-rooted-cfg-contract-create-shared-v2 input plan emitted)))
        (should (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract))
        (should (nelisp-bytecode-native-rooted-cfg-contract-f1-p contract))))))
(ert-deftest u2a/frozen-values-and-defensive-family-copy ()
  (dolist (row native-prims-u2a-family)
    (let* ((name (nth 1 row)) (original (nelisp-native-funcall-v2-initializer name))
           (cell (symbol-function name)) (restore (symbol-function 'fset)) actual)
      (unwind-protect
          (progn (funcall restore name (lambda (&rest _) 'poison))
                 (setq actual (nelisp-native-funcall-v2-initializer name)))
        (funcall restore name cell))
      (should (eq actual original))
      (let ((copy (nelisp-native-funcall-v2-primitive (car row))))
        (setcar (cdr copy) 'poison)
        (should (equal (nelisp-native-funcall-v2-primitive (car row)) row))))))
(ert-deftest u2a/underflow-and-unrelated-pending-opcode-refused ()
  (dolist (row native-prims-u2a-family)
    (let ((fn (make-byte-code 0 (unibyte-string (car row) 135) [] 0)))
      (should-not (eq (plist-get (nelisp-bytecode-compiler-input-build fn) :status) 'complete))))
  (should-not (nelisp-native-funcall-v2-primitive 80)))
(ert-deftest u2a/safe-contract-and-exit-layout-reconstruct ()
  (dolist (row native-prims-u2a-family)
    (let* ((input (nelisp-bytecode-compiler-input-build (native-prims-u2a-function row)))
           (plan (nelisp-bytecode-native-rooted-cfg-plan input 'safe-primitives-v3))
           (emitted (nelisp-bytecode-native-rooted-cfg-emit plan nelisp-bytecode-native-rooted-cfg-safe-contract-entry))
           (contract (nelisp-bytecode-native-rooted-cfg-safe-contract-create input plan emitted)))
      (should (nelisp-bytecode-native-rooted-cfg-safe-contract-valid-p contract))
      (let ((mutant (copy-tree contract)))
        (plist-put mutant :exit-root-base 1)
        (should-not (nelisp-bytecode-native-rooted-cfg-safe-contract-valid-p mutant))))))
(defvar nelisp-stdlib--symbol-plists)
(defun u2a-test-lisp-provider (name)
  "Evaluate the exact source-owned provider with host canonical builtin values."
  (let (binding)
    (with-temp-buffer
      (insert-file-contents (locate-library "nelisp-native-funcall-v2.el" t))
      (goto-char (point-min))
      (condition-case nil
          (while t
            (let ((form (read (current-buffer))))
              (when (and (eq (car-safe form) 'let) (assq name (cadr form)))
                (setq binding (cadr (assq name (cadr form)))))))
        (end-of-file nil)))
    (should binding)
    (cl-labels ((host (form)
                 (cond ((and (eq (car-safe form) 'quote)
                             (eq (car-safe (cadr form)) 'builtin))
                        (list 'quote (symbol-function (cadr (cadr form)))))
                       ((consp form) (cons (host (car form)) (host (cdr form))))
                       (t form))))
      (eval (host binding) t))))
(ert-deftest u2a/frozen-lisp-providers-preserve-vm-data-and-store ()
  (let ((nth-provider (u2a-test-lisp-provider 'nth-provider))
        (get-provider (u2a-test-lisp-provider 'get-provider))
        (vm (native-prims-u2a-function '(56 nth 2)))
        (nelisp-stdlib--symbol-plists (make-hash-table :test #'eq)))
    (puthash 'u2a-value '(key present) nelisp-stdlib--symbol-plists)
    (dolist (args (native-prims-u2a-cases 56))
      (should (equal (condition-case err (apply nth-provider args) (error err))
                     (condition-case err (apply vm args) (error err)))))
    (should (eq (funcall get-provider 'u2a-value 'key) 'present))
    (should (eq (funcall get-provider nil 'key) nil))
    (should (equal (condition-case err (funcall get-provider 7 'key) (error err))
                   '(wrong-type-argument symbolp 7)))))
(ert-deftest u2a/gnu-boundary-oracles ()
  (dolist (opcode '(75 76))
    (let ((function (native-prims-u2a-function (assq opcode native-prims-u2a-family))))
      (dolist (args (native-prims-u2a-cases opcode))
        (let ((oracle (native-prims-u2a-oracle opcode args)))
          (when oracle
            (native-prims-u2a-reset)
            (should (equal oracle (car (native-prims-u2a-observe function args))))))))))
(provide 'nelisp-native-prims-u2a-test)
