;;; nelisp-native-call-v2-test.el --- CALL provider protocol model -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'bytecomp)
(require 'nelisp-native-call-v2)

(defun nelisp-call-test--lower (form)
  "Execute the actual DSL with host memory helpers."
  (cond ((atom form) form)
        ((eq (car form) 'seq) (cons 'progn (mapcar #'nelisp-call-test--lower (cdr form))))
        ((eq (car form) 'data-addr) 900)
        (t (mapcar #'nelisp-call-test--lower form))))
(eval (nelisp-call-test--lower (nelisp-native-call-v2-source)) t)

(defun nelisp-call-test--run (function args &optional config words)
  "Run the canonical DSL against authenticated host roots and return evidence."
  (let* ((memory (make-hash-table :test 'eql)) (reserved 0) (ended 0)
         (calls 0) (active 20) (env 10) (count 16)
         (output 7) (exit 8) (status nil) (before nil) (after nil))
    (cl-labels
        ((outer (i) (+ 1000 (* i 32)))
         (inner (i) (+ 10000 (* i 32)))
         (write (p object)
           (puthash p (cond ((null object) 0) ((eq object t) 1)
                           ((integerp object) 2)
                           ((symbolp object)
                            (if (eq (intern-soft (symbol-name object)) object) 4 16))
                           (t 5)) memory)
           (puthash (+ p 8) object memory)
           (puthash (+ p 16) 123 memory) (puthash (+ p 24) 456 memory))
         (read-object (p) (gethash (+ p 8) memory))
         (saved () (cl-loop for i from output to (+ exit 2)
                           collect (cl-loop for off in '(0 8 16 24)
                                            collect (gethash (+ (outer i) off) memory)))))
      (puthash 900 20000 memory)
      (dotimes (i count) (write (outer i) nil))
      (write (outer 0) 'marker) (write (outer 1) function)
      (cl-loop for arg in args for i from 2 do (write (outer i) arg))
      (write (outer output) 'untouched)
      (dolist (i '(8 9 10)) (write (outer i) 'old-exit))
      (setq before (saved))
      (cl-letf
          (((symbol-function 'ptr-read-u64)
            (lambda (p off) (gethash (+ p off) memory 0)))
           ((symbol-function 'ptr-write-u64)
            (lambda (p off value) (puthash (+ p off) value memory)))
           ((symbol-function 'nl_root_pin_slot_v2)
            (lambda (e token i)
              (cond
               ((and (= e env) (= token active) (= token 20) (< i count))
                (if (and (plist-get config :outer-fails) (> ended 0)) 0
                  (if (eql i (plist-get config :nonadjacent)) (+ (outer i) 8) (outer i))))
               ((and (= e env) (= token active) (= token 21) (< i reserved))
                (if (and (plist-get config :nested-fails) (> calls 0)) 0 (inner i)))
               (t 0))))
           ((symbol-function 'nl_root_pin_begin_v2)
            (lambda (_e)
              (if (plist-get config :begin-fails) 0
                (setq active 21)
                (puthash (- (inner 0) 32) 2 memory)
                (puthash (- (inner 0) 24) (outer 0) memory)
                (puthash (- (inner 0) 16) 20 memory)
                (puthash (- (inner 0) 8) (inner 0) memory) 21)))
           ((symbol-function 'nl_root_pin_reserve_v2)
            (lambda (_e _token)
              (if (>= reserved (or (plist-get config :reserve-limit) 20)) 0
                (let ((p (inner reserved)))
                  (setq reserved (1+ reserved))
                  (dotimes (i 4) (puthash (+ p (* i 8)) 0 memory)) p))))
           ((symbol-function 'nl_root_pin_end_v2)
            (lambda (_e _token)
              (setq ended (1+ ended) active 20)
              (if (plist-get config :end-fails) 0 1)))
           ((symbol-function 'wf_bytecode_call_gateway)
            (lambda (e function-slot slots first argc out)
              (setq calls (1+ calls))
              (should (= e env)) (should (= reserved (+ argc 7)))
              (should (= function-slot (inner 0))) (should (= slots function-slot))
              (should (= first 1)) (should (= out (inner (+ argc 2))))
              (should (eq (read-object function-slot) function))
              (let* ((copied (cl-loop for i from 1 to argc collect (read-object (inner i))))
                     (answer (if (plist-get config :gateway-refuses) '(2)
                               (nelisp-native-call-v2--reference-apply
                                function copied (plist-get config :catch-tags)))))
                (should (equal copied args))
                (garbage-collect)
                (when (plist-get config :link-fails)
                  (puthash (- (inner 0) 16) 99 memory))
                (cond ((= (car answer) 0) (write out (cadr answer)))
                      ((= (car answer) 1)
                       (puthash 20016 (or (plist-get config :bad-flag) (nth 1 answer)) memory)
                       (write 20024 (nth 2 answer)) (write 20056 (nth 3 answer))))
                (car answer)))))
        (setq status (apply #'nl_native_call_v2
                            (or words (list env 20 1 (length args) output exit)))))
      (setq after (saved))
      (list :status status :result (read-object (outer output))
            :exit (list (read-object (outer exit)) (read-object (outer (1+ exit)))
                        (read-object (outer (+ exit 2))))
            :kind-word (gethash (outer exit) memory)
            :before before :after after :calls calls :ended ended :active active
            :reserved reserved :flag (gethash 20016 memory 0)))))

(ert-deftest nelisp-call-v2-six-word-abi-and-exact-imports ()
  (let ((d (nelisp-native-call-v2-descriptor)) (imports (nelisp-native-call-v2-runtime-imports)))
    (should (equal (plist-get d :name) "nl_native_call_v2"))
    (should (eq (plist-get d :kind) 'func)) (should (= (plist-get d :arity) 6))
    (should (equal (plist-get d :params) '(u64 u64 u64 u64 u64 u64)))
    (should (eq (plist-get d :return) 'u64))
    (should (eq (plist-get d :calling-convention) 'sysv-amd64))
    (should (equal (mapcar (lambda (i) (plist-get i :name)) imports)
                   '("nl_arena_base" "nl_root_pin_begin_v2" "nl_root_pin_end_v2"
                     "nl_root_pin_reserve_v2" "nl_root_pin_slot_v2" "wf_bytecode_call_gateway")))
    (should (equal (mapcar (lambda (i) (plist-get i :arity)) (cdr imports)) '(1 2 2 3 6)))
    (should (equal (nth 2 (car (last (cdr (nelisp-native-call-v2-source)))))
                   '(env ticket call-base argc result-index exit-base)))))

(ert-deftest nelisp-call-v2-independent-canonical-snapshots ()
  (let* ((a (nelisp-native-call-v2-source)) (b (nelisp-native-call-v2-source))
         (context (nelisp-native-call-v2-dependency-context)))
    (should (equal a b)) (setcar (cdr a) 'mutated)
    (should (equal b (nelisp-native-call-v2-source)))
    (let ((nelisp-native-call-v2--source '(forged)))
      (should (equal b (nelisp-native-call-v2-source))))
    (setcar (aref context 1) 'mutated)
    (should (equal b (nelisp-native-call-v2-source)))
    (let ((d (nelisp-native-call-v2-descriptor)) (i (nelisp-native-call-v2-runtime-imports)))
      (setcar d :forged) (setcar (car i) :forged)
      (should (equal (plist-get (nelisp-native-call-v2-descriptor) :name) "nl_native_call_v2"))
      (should (equal (plist-get (car (nelisp-native-call-v2-runtime-imports)) :name) "nl_arena_base")))))

(ert-deftest nelisp-call-v2-snapshot-bounds ()
  (let ((cycle (list 'seq)))
    (setcdr cycle cycle) (should-error (nelisp-native-call-v2--snapshot cycle)))
  (should-error (nelisp-native-call-v2--snapshot (make-list 9000 0)))
  (should-error (nelisp-native-call-v2--snapshot (make-string 257 ?x)))
  (should-error (nelisp-native-call-v2--snapshot (propertize "abc" 'face 'bold)))
  (should-error (nelisp-native-call-v2--snapshot [0]))
  (let ((deep 0))
    (dotimes (_ 66) (setq deep (list deep)))
    (should-error (nelisp-native-call-v2--snapshot deep)))
  (let ((shared '(1 2)))
    (should (equal (nelisp-native-call-v2--snapshot (list shared shared)) '((1 2) (1 2))))))

(ert-deftest nelisp-call-v2-owner-check-before-helper-execution ()
  (dolist (owner '(nelisp-native-call-v2--snapshot nelisp-native-call-v2--copy-node
                   nelisp-native-call-v2-source nelisp-native-call-v2-descriptor
                   nelisp-native-call-v2-runtime-imports nelisp-native-call-v2-owner-valid-p))
    (let ((called nil))
      (cl-letf (((symbol-function owner) (lambda (&rest _) (setq called t) '(forged))))
        (should-error (nelisp-native-call-v2-dependency-context))
        (should-not called)))))

(ert-deftest nelisp-call-v2-no-runtime-macro-expansion ()
  (let ((source (nelisp-native-call-v2-source)))
    (cl-letf (((symbol-function 'cl-labels) '(macro . ignore))
              ((symbol-function 'when) '(macro . ignore))
              ((symbol-function 'unless) '(macro . ignore)))
      (should (equal source (nelisp-native-call-v2-source))))))

(ert-deftest nelisp-call-v2-builtin-zero-through-five ()
  (dotimes (argc 6)
    (let* ((args (number-sequence 1 argc)) (r (nelisp-call-test--run 'list args)))
      (should (= (plist-get r :status) 0)) (should (equal (plist-get r :result) args))
      (should (equal (plist-get r :exit) '(0 0 0)))
      (should (= (plist-get r :reserved) (+ argc 7)))
      (should (= (plist-get r :ended) 1)) (should (= (plist-get r :active) 20)))))

(ert-deftest nelisp-call-v2-source-free-bytecode-zero-through-five ()
  (let ((name 'nelisp-call-test-callee))
    (unwind-protect
        (dotimes (argc 6)
          (let* ((args (cl-loop for i below argc collect (intern (format "a%d" i))))
                 (fn (byte-compile (list 'lambda args (cons 'list args)))))
            (should (byte-code-function-p fn))
            (fset name fn)
            (let ((r (nelisp-call-test--run name (number-sequence 1 argc))))
              (should (= (plist-get r :status) 0))
              (should (equal (plist-get r :result) (number-sequence 1 argc))))))
      (fmakunbound name))))

(ert-deftest nelisp-call-v2-result-and-argument-identity ()
  (let* ((object (vector (list 'opaque) (make-symbol "id")))
         (r (nelisp-call-test--run 'identity (list object))))
    (should (= (plist-get r :status) 0)) (should (eq (plist-get r :result) object))))

(ert-deftest nelisp-call-v2-exact-signal-throw-quit ()
  (let ((tag (make-symbol "catch")) (value (vector 'payload)))
    (dolist (case (list (list 'signal (list 'error (list value)) '(1 error))
                       (list 'signal (list 'quit nil) '(1 quit))
                       (list 'throw (list tag value) (list 2 tag))))
      (let ((r (nelisp-call-test--run (car case) (cadr case) (list :catch-tags (list tag)))))
        (should (= (plist-get r :status) 1))
        (should (= (plist-get r :kind-word) 2))
        (should (equal (cl-subseq (plist-get r :exit) 0 2) (nth 2 case)))
        (should (eq (nth 2 (plist-get r :exit)) (if (eq (car case) 'throw) value (cadr (cadr case)))))
        (should (eq (plist-get r :result) 'untouched)) (should (= (plist-get r :flag) 0))
        (should (= (plist-get r :ended) 1))))))

(ert-deftest nelisp-call-v2-refusals-preserve-output-and-triple ()
  (dolist (words '((10 99 1 0 7 8) (99 20 1 0 7 8) (10 20 16 0 7 8)
                   (10 20 1 6 7 8) (10 20 1 -1 7 8) (10 20 0 0 7 8)
                   (10 20 255 1 7 8) (10 20 1 0 7 254)
                   (10 20 1 1 2 8) (10 20 1 0 8 8) (10 20 8 0 7 8)
                   (10 20 18446744073709551615 5 7 8)))
    (let ((r (nelisp-call-test--run 'list nil nil words)))
      (should (= (plist-get r :status) 2)) (should (= (plist-get r :calls) 0))
      (should (equal (plist-get r :before) (plist-get r :after)))
      (should (= (plist-get r :ended) 0))))
  (dolist (callee (list nil t 7 '(lambda () nil) (make-symbol "list")))
    (let ((r (nelisp-call-test--run callee nil)))
      (should (= (plist-get r :status) 2)) (should (= (plist-get r :calls) 0))
      (should (equal (plist-get r :before) (plist-get r :after))))))

(ert-deftest nelisp-call-v2-nonadjacent-window-refused ()
  (let ((r (nelisp-call-test--run 'identity '(1) '(:nonadjacent 2))))
    (should (= (plist-get r :status) 2)) (should (= (plist-get r :calls) 0))
    (should (equal (plist-get r :before) (plist-get r :after)))))

(ert-deftest nelisp-call-v2-begin-and-every-reserve-failure ()
  (let ((r (nelisp-call-test--run 'list nil '(:begin-fails t))))
    (should (= (plist-get r :status) 2)) (should (= (plist-get r :ended) 0)))
  (dotimes (limit 12)
    (let ((r (nelisp-call-test--run 'list '(1 2 3 4 5) (list :reserve-limit limit))))
      (should (= (plist-get r :status) 2)) (should (= (plist-get r :calls) 0))
      (should (= (plist-get r :ended) 1)) (should (= (plist-get r :active) 20))
      (should (equal (plist-get r :before) (plist-get r :after))))))

(ert-deftest nelisp-call-v2-post-call-failure-never-retries ()
  (dolist (config '((:nested-fails t) (:link-fails t) (:outer-fails t) (:end-fails t)
                    (:gateway-refuses t)))
    (let ((r (nelisp-call-test--run 'list '(1) config)))
      (should (= (plist-get r :status) 2)) (should (= (plist-get r :calls) 1))
      (should (= (plist-get r :ended) 1))))
  (let ((r (nelisp-call-test--run 'signal '(error nil) '(:bad-flag 3))))
    (should (= (plist-get r :status) 2)) (should (= (plist-get r :flag) 3))
    (should (equal (plist-get r :before) (plist-get r :after)))))

(ert-deftest nelisp-call-v2-reference-status-model ()
  (let* ((slots (vector 'marker 'identity (vector 'identity) nil nil 'old 'old 'old))
         (env (list :ticket 20 :slots slots)))
    (when (getenv "NELISP_CALL_REFERENCE_MUTANT")
      (cl-letf (((symbol-function 'nelisp-native-call-v2-reference) (lambda (&rest _) 0)))
        (should (= (nelisp-native-call-v2-reference env 99 1 1 4 5) 2))))
    (should (= (nelisp-native-call-v2-reference env 20 1 1 4 5) 0))
    (should (eq (aref slots 4) (aref slots 2)))
    (should (equal (cl-subseq slots 5 8) [nil nil nil]))
    (dolist (words '((99 1 1 4 5) (20 1 6 4 5) (20 1 1 2 5) (20 1 1 4 6)))
      (let ((before (copy-sequence slots)))
        (should (= (apply #'nelisp-native-call-v2-reference env words) 2))
        (should (equal before slots))))
    (aset slots 1 'signal) (aset slots 2 'quit) (aset slots 3 nil)
    (should (= (nelisp-native-call-v2-reference env 20 1 2 4 5) 1))
    (should (equal (cl-subseq slots 5 8) [1 quit nil]))))

;; The standard runner owns execution and its ert-focus.json report.
;;; nelisp-native-call-v2-test.el ends here
