;;; nelisp-stdlib-fringe-bitmap-test.el --- GNU fallback admission tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'nelisp-stdlib-fringe-bitmap)
(defconst nelisp-fringe-test--root (getenv "NELISP_GNU_BUILD_SOURCE_ROOT"))
(defun nelisp-fringe-test--genuine-form ()
  "Read the unique genuine conditional fallback without loading fringe.el."
  (unless nelisp-fringe-test--root (ert-skip "Pinned GNU source root is unconfigured"))
  (with-temp-buffer
    (insert-file-contents (expand-file-name "lisp/fringe.el" nelisp-fringe-test--root))
    (goto-char (point-min))
    (let (found)
      (while (re-search-forward "^(unless (fboundp 'define-fringe-bitmap)" nil t)
        (goto-char (match-beginning 0))
        (let ((form (read (current-buffer))))
          (unless (equal (cadr form) '(fboundp 'define-fringe-bitmap))
            (error "Unexpected GNU fallback guard"))
          (push (nth 2 form) found)))
      (unless (= (length found) 1) (error "GNU fallback extraction count differs"))
      (car found))))
(defmacro nelisp-fringe-test--terminal (&rest body)
  "Simulate admission inputs, never claim the GNU C provider is non-GUI."
  `(let ((font (lambda (&rest _) nil)))
    (unless nelisp-fringe-test--root (ert-skip "Pinned GNU source root is unconfigured"))
    (cl-letf (((symbol-function 'define-fringe-bitmap) nil)
             ((symbol-function 'nelisp-native-raw-file-read)
              (lambda (path start count)
                (with-temp-buffer
                  (set-buffer-multibyte nil)
                  (insert-file-contents-literally path nil start (+ start count))
                  (buffer-string))))
             ((symbol-function 'nelisp-bytecode-compiler-input-dialect)
              (lambda () '(:status pinned :runtime-evidence standalone-build-verified)))
             ((symbol-function 'nelisp-stdlib-terminal-output-install)
              (lambda () (fset 'internal-char-font font) 'installed))
             ((symbol-function 'internal-char-font) font)
             ((symbol-function 'selected-frame) (lambda () nil))
             ((symbol-function 'window-system) (lambda (&optional _) nil))
             ((symbol-function 'display-graphic-p) (lambda (&optional _) nil)))
     (let ((nelisp-stdlib-fringe-bitmap--owners
            (mapcar (lambda (owner) (cons (car owner) (symbol-function (car owner))))
                    nelisp-stdlib-fringe-bitmap--owners))
           (nelisp-stdlib-fringe-bitmap--installed-owner nil)
           (nelisp-stdlib-fringe-bitmap--terminal-font-owner nil))
       ,@body))))
(ert-deftest nelisp-fringe-exact-gnu-nongui-branch ()
  ;; GNU host can have graphical support even in batch.  Execute only the
  ;; genuine Lisp compile branch with its C function temporarily unbound.
  (should (equal (nelisp-fringe-test--genuine-form) nelisp-stdlib-fringe-bitmap--form))
  (cl-letf (((symbol-function 'define-fringe-bitmap) nil))
    (eval (list 'unless '(fboundp 'define-fringe-bitmap)
                (nelisp-fringe-test--genuine-form)) t)
    (should (equal (nth 3 (nelisp-fringe-test--genuine-form))
                   (define-fringe-bitmap 'test [0 1] 2 8 '(center t))))))
(ert-deftest nelisp-fringe-preserves-gnu-provider ()
  (let ((owner (symbol-function 'define-fringe-bitmap)))
    (should (eq 'preserved (nelisp-stdlib-fringe-bitmap-install nil)))
    (should (eq owner (symbol-function 'define-fringe-bitmap)))))
(ert-deftest nelisp-fringe-preserves-foreign-provider ()
  (cl-letf (((symbol-function 'define-fringe-bitmap) (lambda (&rest _) 'foreign)))
    (should (eq 'preserved (nelisp-stdlib-fringe-bitmap-install nil)))
    (should (eq 'foreign (define-fringe-bitmap nil nil)))))
(ert-deftest nelisp-fringe-installs-exact-fallback ()
  (nelisp-fringe-test--terminal
   (should (eq 'installed (nelisp-stdlib-fringe-bitmap-install nelisp-fringe-test--root)))
   (should (equal (nth 3 nelisp-stdlib-fringe-bitmap--form)
                  (define-fringe-bitmap 'test [0 1] 2 8 '(center t))))
   (should (equal (nth 3 nelisp-stdlib-fringe-bitmap--form)
                  (define-fringe-bitmap nil nil)))
   (should-error (define-fringe-bitmap 'test) :type 'wrong-number-of-arguments)
   (should (eq 'preserved (nelisp-stdlib-fringe-bitmap-install nelisp-fringe-test--root)))))
(ert-deftest nelisp-fringe-restores-missing-installed-provider ()
  (nelisp-fringe-test--terminal
   (should (eq 'installed (nelisp-stdlib-fringe-bitmap-install nelisp-fringe-test--root)))
   (fmakunbound 'define-fringe-bitmap)
   (should (eq 'installed (nelisp-stdlib-fringe-bitmap-install nelisp-fringe-test--root)))
   (should (equal (nth 3 nelisp-stdlib-fringe-bitmap--form)
                  (define-fringe-bitmap nil nil)))))
(ert-deftest nelisp-fringe-sourcepin-mutation ()
  (nelisp-fringe-test--terminal
   (cl-letf (((symbol-function 'nelisp-native-raw-file-read)
              (lambda (&rest _) (make-string 12900 ?x))))
     (let ((nelisp-stdlib-fringe-bitmap--owners
            (mapcar (lambda (owner) (cons (car owner) (symbol-function (car owner))))
                    nelisp-stdlib-fringe-bitmap--owners)))
       (should (equal (cadr (should-error (nelisp-stdlib-fringe-bitmap-install nelisp-fringe-test--root)))
                      "Fringe bitmap GNU source pin differs"))))
   (should-not (fboundp 'define-fringe-bitmap))))
(ert-deftest nelisp-fringe-payload-mutation ()
  (nelisp-fringe-test--terminal
   (let ((nelisp-stdlib-fringe-bitmap--form '(defun define-fringe-bitmap (&rest _) t)))
     (should (equal (cadr (should-error (nelisp-stdlib-fringe-bitmap-install nelisp-fringe-test--root)))
                    "Fringe bitmap source payload changed")))
   (should-not (fboundp 'define-fringe-bitmap))))
(ert-deftest nelisp-fringe-owner-mutation ()
  (nelisp-fringe-test--terminal
   (cl-letf (((symbol-function 'display-graphic-p) (lambda (&optional _) nil)))
     (should (string-match-p "Fringe bitmap dependency owner changed"
                             (cadr (should-error (nelisp-stdlib-fringe-bitmap-install nelisp-fringe-test--root))))))
   (should-not (fboundp 'define-fringe-bitmap))))
(ert-deftest nelisp-fringe-dialect-refusal ()
  (nelisp-fringe-test--terminal
   (cl-letf (((symbol-function 'nelisp-bytecode-compiler-input-dialect)
              (lambda () '(:status pinned :runtime-evidence host))))
     (let ((nelisp-stdlib-fringe-bitmap--owners
            (mapcar (lambda (owner) (cons (car owner) (symbol-function (car owner))))
                    nelisp-stdlib-fringe-bitmap--owners)))
       (should (equal (cadr (should-error (nelisp-stdlib-fringe-bitmap-install nelisp-fringe-test--root)))
                      "Fringe bitmap requires verified standalone runtime"))))
   (should-not (fboundp 'define-fringe-bitmap))))
(ert-deftest nelisp-fringe-graphical-refusal ()
  (nelisp-fringe-test--terminal
   (cl-letf (((symbol-function 'display-graphic-p) (lambda (&optional _) t)))
     (let ((nelisp-stdlib-fringe-bitmap--owners
            (mapcar (lambda (owner) (cons (car owner) (symbol-function (car owner))))
                    nelisp-stdlib-fringe-bitmap--owners)))
       (should (equal (cadr (should-error (nelisp-stdlib-fringe-bitmap-install nelisp-fringe-test--root)))
                      "Fringe bitmap requires the non-graphical substrate"))))
   (should-not (fboundp 'define-fringe-bitmap))))
(ert-deftest nelisp-fringe-public-owner-registration-lifecycle ()
  (nelisp-fringe-test--terminal
   (fmakunbound 'internal-char-font)
   (should (eq 'installed (nelisp-stdlib-fringe-bitmap-install nelisp-fringe-test--root)))
   (should (eq font nelisp-stdlib-fringe-bitmap--terminal-font-owner))
   (should (eq font (symbol-function 'internal-char-font)))
   (should (eq 'preserved (nelisp-stdlib-fringe-bitmap-install nelisp-fringe-test--root)))
   (should (eq font (symbol-function 'internal-char-font)))))
(ert-deftest nelisp-fringe-prebound-font-owner-refusal ()
  (nelisp-fringe-test--terminal
   (let ((foreign (lambda (&rest _) nil)))
     (fset 'internal-char-font foreign)
     (should (equal (cadr (should-error (nelisp-stdlib-fringe-bitmap-install nelisp-fringe-test--root)))
                    "Fringe bitmap terminal font owner differs"))
     (should (eq foreign (symbol-function 'internal-char-font)))
     (should-not nelisp-stdlib-fringe-bitmap--terminal-font-owner)
     (should-not (fboundp 'define-fringe-bitmap)))))
(ert-deftest nelisp-fringe-sealed-font-owner-mutation ()
  (nelisp-fringe-test--terminal
   (nelisp-stdlib-fringe-bitmap-install nelisp-fringe-test--root)
   (let ((foreign (lambda (&rest _) nil)))
     (fset 'internal-char-font foreign)
     (should (equal (cadr (should-error (nelisp-stdlib-fringe-bitmap-install nelisp-fringe-test--root)))
                    "Fringe bitmap terminal font owner differs"))
     (should (eq foreign (symbol-function 'internal-char-font)))
     (should (eq font nelisp-stdlib-fringe-bitmap--terminal-font-owner)))))
(ert-deftest nelisp-fringe-font-registration-exception-restoration ()
  (nelisp-fringe-test--terminal
   (cl-letf (((symbol-function 'nelisp-stdlib-terminal-output-install)
              (lambda ()
                (fset 'internal-char-font (lambda (&rest _) nil))
                (error "Registration exception"))))
     (setcdr (assq 'nelisp-stdlib-terminal-output-install
                   nelisp-stdlib-fringe-bitmap--owners)
             (symbol-function 'nelisp-stdlib-terminal-output-install))
     (should (equal (cadr (should-error (nelisp-stdlib-fringe-bitmap-install nelisp-fringe-test--root)))
                    "Registration exception"))
     (should (eq font (symbol-function 'internal-char-font)))
     (should-not nelisp-stdlib-fringe-bitmap--terminal-font-owner)
     (fmakunbound 'internal-char-font)
     (should-error (nelisp-stdlib-fringe-bitmap-install nelisp-fringe-test--root))
     (should-not (fboundp 'internal-char-font))
     (should-not (fboundp 'define-fringe-bitmap)))))
