;;; Canonical linear and branch import controls -*- lexical-binding: t; -*-
(require 'ert)
(require 'nelisp-native-load)
(require 'nelisp-bytecode-native-rooted-cfg-contract)
(ert-deftest nelisp-loader-linear-import-exact-canonical ()
  (let* ((input (nelisp-bytecode-compiler-input-build (byte-compile '(lambda (left right) (cons left right)))))
         (plan (nelisp-bytecode-native-rooted-cfg-plan input))
         (emitted (nelisp-bytecode-native-rooted-cfg-emit plan "nl_native_rooted_cfg_probe_v1"))
         (contract (nelisp-bytecode-native-rooted-cfg-contract-create input plan emitted))
         (manifest (nelisp-bytecode-native-rooted-cfg-contract-test--manifest contract)))
    (should (equal (plist-get contract :imports) '("nl_native_cons_v2")))
    (should (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract))
    (should (nelisp-native-load--raw-v2-rooted-cfg-contract-valid-slow-p manifest))
    (let ((mutant (copy-tree manifest)))
      (setf (plist-get (car (plist-get (plist-get mutant :native) :imports)) :arity) 5)
      (should-not (nelisp-native-load--raw-v2-rooted-cfg-contract-valid-slow-p mutant)))))
(ert-deftest nelisp-loader-branch-import-slot-remains-mandatory ()
  (let* ((input (nelisp-bytecode-native-rooted-cfg-contract-test--fixture))
         (plan (nelisp-bytecode-native-rooted-cfg-plan input))
         (emitted (nelisp-bytecode-native-rooted-cfg-emit plan "nl_native_rooted_cfg_probe_v1"))
         (contract (nelisp-bytecode-native-rooted-cfg-contract-create input plan emitted)))
    (should (member "nl_root_pin_slot_v2" (plist-get contract :imports)))
    (should (nelisp-native-load--raw-v2-rooted-cfg-contract-valid-slow-p
             (nelisp-bytecode-native-rooted-cfg-contract-test--manifest contract)))
    (setq contract (copy-tree contract))
    (setf (plist-get contract :imports) (remove "nl_root_pin_slot_v2" (plist-get contract :imports)))
    (setf (plist-get contract :digest) (nelisp-bytecode-native-rooted-cfg-contract-test--redigest contract))
    (should-not (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract))
    (should-not (nelisp-native-load--raw-v2-rooted-cfg-contract-valid-slow-p
                 (nelisp-bytecode-native-rooted-cfg-contract-test--manifest contract)))))
