;;; nelisp-bytecode-native-add-adapter-test.el --- Authenticated add planning -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'nelisp-bytecode-native-rooted-cfg-shared-emit)
(require 'nelisp-bytecode-native-rooted-cfg-contract)
(defun nelisp-bytecode-native-add-test--input ()
  (nelisp-bytecode-compiler-input-build
   (byte-compile '(lambda (left right) (+ left right)))))
(ert-deftest nelisp-bytecode-native-add-authentic-roots-and-exit ()
  (let* ((input (nelisp-bytecode-native-add-test--input))
         (plan (nelisp-bytecode-native-rooted-cfg-plan input))
         (operation (cl-find-if
                     (lambda (operation) (eq (plist-get operation :opcode) 'add))
                     (plist-get (car (plist-get plan :blocks)) :operations)))
         (emitted (nelisp-bytecode-native-rooted-cfg-shared-emit-build plan "add_test")))
    (should (eq (plist-get plan :status) 'complete))
    (should (eq (plist-get operation :opcode) 'add))
    (should (equal (plist-get operation :input-roots) '(1 2)))
    (should (= (plist-get operation :output-root) 3))
    (should (= (plist-get plan :exit-root-base) 4))
    (should (= (plist-get plan :required-root-count) 7))
    (should (eq (plist-get emitted :status) 'complete))
    (should (equal (plist-get emitted :additional-source)
                   (nelisp-native-arithmetic-v2-source)))
    (should (= (funcall (plist-get input :function) 19 23) 42))))
(ert-deftest nelisp-bytecode-native-add-forged-input-and-owner-refused ()
  (let* ((input (nelisp-bytecode-native-add-test--input))
         (plan (nelisp-bytecode-native-rooted-cfg-plan input))
         (forged (copy-tree input)))
    (plist-put forged :argument-count 3)
    (should (eq (plist-get (nelisp-bytecode-native-rooted-cfg-plan forged) :status)
                'unsupported))
    (cl-letf (((symbol-function 'nelisp-native-arithmetic-v2-source)
               (lambda () '(seq (defun nl_native_add_v2 () 0)))))
      (should (eq (plist-get
                   (nelisp-bytecode-native-rooted-cfg-shared-emit-build plan "add_test")
                   :status) 'unsupported)))))

(ert-deftest nelisp-bytecode-native-add-serialized-provider-mutation-refused ()
  (let* ((input (nelisp-bytecode-native-add-test--input))
         (plan (nelisp-bytecode-native-rooted-cfg-plan input))
         (emitted (nelisp-bytecode-native-rooted-cfg-shared-emit-build
                   plan nelisp-bytecode-native-rooted-cfg-contract-shared-entry))
         (contract (nelisp-bytecode-native-rooted-cfg-contract-create-shared-v2
                    input plan emitted))
         (print-length nil) (print-level nil)
         (roundtrip (car (read-from-string (prin1-to-string contract)))))
    (should (nelisp-bytecode-native-rooted-cfg-contract-valid-p roundtrip))
    (should (= (length (plist-get roundtrip :local-functions)) 4))
    (should-not (member "nl_native_add_v2" (plist-get roundtrip :imports)))
    (let ((forged (copy-tree roundtrip)))
      (plist-put (car (plist-get forged :runtime-imports)) :size 16)
      (plist-put forged :digest
                 (nelisp-bytecode-native-rooted-cfg-contract--digest forged))
      (should-not (nelisp-bytecode-native-rooted-cfg-contract-valid-p forged)))
    ;; Rehashing a changed local provider still cannot authenticate its body.
    (plist-put roundtrip :additional-source '(seq (defun nl_native_add_v2 () 0)))
    (plist-put roundtrip :digest
               (nelisp-bytecode-native-rooted-cfg-contract--digest roundtrip))
    (should-not (nelisp-bytecode-native-rooted-cfg-contract-valid-p roundtrip))))
