;;; resolver-family-test.el --- Full family dispatch controls -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(add-to-list 'load-path (expand-file-name "../lisp" (file-name-directory load-file-name)))
(require 'nelisp-native-load)

(ert-deftest nelisp-resolver-selects-only-complete-declared-family ()
  (let ((irrelevant 0) (relevant 0) (resolved 0)
        (manifest '(:native-rooted-cfg-contract-version "valid")))
    (cl-letf (((symbol-function 'nelisp-native-load--raw-v2-conditional-contract-valid-p)
               (lambda (&rest _) (setq irrelevant (1+ irrelevant)) nil))
              ((symbol-function 'nelisp-native-load--raw-v2-rooted-branch-contract-valid-p)
               (lambda (&rest _) (setq irrelevant (1+ irrelevant)) nil))
              ((symbol-function 'nelisp-native-load--raw-v2-rooted-branch-join-contract-valid-p)
               (lambda (&rest _) (setq irrelevant (1+ irrelevant)) nil))
              ((symbol-function 'nelisp-native-load-raw-v2-rooted-cfg-contract-valid-p)
               (lambda (candidate) (setq relevant (1+ relevant))
                 (equal (plist-get candidate :native-rooted-cfg-contract-version) "valid")))
              ((symbol-function 'nelisp-native-load--symbol-addr)
               (lambda (_name) (setq resolved (1+ resolved)) 123))
              ((symbol-function 'nelisp-native-load--raw-symbol-addr)
               (lambda (_name) (error "no unvalidated conditional address"))))
      (should (= (nelisp-native-load--raw-v2-symbol-addr "nl_root_pin_slot_v2" 'descriptor manifest) 123))
      (should (= irrelevant 0)) (should (= relevant 1)) (should (= resolved 1))
      (should-error (nelisp-native-load--raw-v2-symbol-addr
                     "nl_root_pin_slot_v2" 'descriptor
                     '(:native-rooted-cfg-contract-version "mutated")))
      (should (= relevant 2)) (should (= resolved 1))
      (dolist (bad '((:native-rooted-cfg-contract-version "valid"
                     :native-rooted-branch-contract-version "conflict")
                    (:native-rooted-cfg-contract-version "valid"
                     :native-rooted-cfg-contract-version "valid")
                    (:native-rooted-cfg-contract-version nil)))
        (should-error (nelisp-native-load--raw-v2-symbol-addr
                       "nl_root_pin_slot_v2" 'descriptor bad)))
      (should (= relevant 2)) (should (= resolved 1)))))

(ert-deftest nelisp-resolver-header-refuses-before-validator ()
  (let ((cycle (list :unused 1)))
    (setcdr (cdr cycle) cycle)
    (should (eq (nelisp-native-load--raw-v2-rooted-import-family cycle) 'refused)))
  (should (eq (nelisp-native-load--raw-v2-rooted-import-family '(:unused)) 'refused))
  (should (eq (nelisp-native-load--raw-v2-rooted-import-family
               (apply #'append (make-list 513 '(:unused 1)))) 'refused)))

(ert-deftest nelisp-resolver-all-five-family-dispatch-controls ()
  (let ((calls nil))
    (cl-letf (((symbol-function 'nelisp-native-load--raw-v2-conditional-contract-valid-p)
               (lambda (_manifest) (push 'conditional calls) t))
              ((symbol-function 'nelisp-native-load--raw-v2-rooted-branch-contract-valid-p)
               (lambda (_manifest) (push 'branch calls) t))
              ((symbol-function 'nelisp-native-load--raw-v2-rooted-branch-join-contract-valid-p)
               (lambda (_manifest) (push 'join calls) t))
              ((symbol-function 'nelisp-native-load-raw-v2-rooted-cfg-contract-valid-p)
               (lambda (_manifest) (push 'cfg calls) t)))
      (dolist (pair '((:native-rooted-conditional-contract-version . conditional)
                      (:native-rooted-branch-contract-version . branch)
                      (:native-rooted-branch-join-contract-version . join)
                      (:native-rooted-cfg-contract-version . cfg)
                      (:native-rooted-cfg-safe-v3-contract-version . cfg)))
        (setq calls nil)
        (should (nelisp-native-load--raw-v2-rooted-import-contract-valid-p
                 (list (car pair) "valid")))
        (should (equal calls (list (cdr pair))))))))
