;;; nelisp-native-buffer-u4c-test.el --- Frozen buffer lowering -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'ert)
(require 'nelisp-bytecode-native-rooted-cfg-contract)
(require 'nelisp-bytecode-native-rooted-cfg-constructor-contract)
(require 'nelisp-bytecode-native-rooted-cfg-safe-contract)
(require 'nelisp-native-load)
(load "support/native-buffer-u4c-fixtures.el" nil t t)
(ert-deftest u4c/exact-nine-opcodes-and-both-contracts ()
  (dolist (row native-buffer-u4c-family)
    (should (equal row (nelisp-native-funcall-v2-primitive (car row))))
    (let* ((input (nelisp-bytecode-compiler-input-build (native-buffer-u4c-function row)))
           (plan (nelisp-bytecode-native-rooted-cfg-plan input))
           (op (car (plist-get (car (plist-get plan :blocks)) :operations)))
           (args (plist-get op :argument-roots)))
      (should (eq (plist-get input :status) 'complete))
      (should (eq (plist-get plan :status) 'complete))
      (should (eq (plist-get op :opcode) 'primitive-call))
      (should (equal (plist-get plan :gateway-imports) '("nl_native_funcall_v2")))
      (should (= (plist-get op :argument-count) (nth 2 row)))
      (should (equal args (number-sequence 1 (nth 2 row))))
      (let* ((emitted (nelisp-bytecode-native-rooted-cfg-shared-emit-build
                       plan nelisp-bytecode-native-rooted-cfg-contract-shared-entry))
             (contract (nelisp-bytecode-native-rooted-cfg-contract-create-shared-v2 input plan emitted)))
        (should (eq (plist-get emitted :status) 'complete))
        (should (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract))
        (should (nelisp-bytecode-native-rooted-cfg-contract-f1-p contract)))
      (let* ((safe (nelisp-bytecode-native-rooted-cfg-plan input 'safe-primitives-v3))
             (emitted (nelisp-bytecode-native-rooted-cfg-emit safe nelisp-bytecode-native-rooted-cfg-safe-contract-entry)))
        (should (nelisp-bytecode-native-rooted-cfg-safe-contract-valid-p
                 (nelisp-bytecode-native-rooted-cfg-safe-contract-create input safe emitted)))))))
(ert-deftest u4c/frozen-values-and-defensive-table ()
  (let ((native-comp-enable-subr-trampolines nil))
    (dolist (row native-buffer-u4c-family)
      (let* ((name (cadr row)) (value (nelisp-native-funcall-v2-initializer name))
             (old (symbol-function name)) (restore (symbol-function 'fset)))
        (should (functionp value))
        (unwind-protect
            (progn (funcall restore name (lambda (&rest _) 'poison))
                   (should (eq value (nelisp-native-funcall-v2-initializer name))))
          (funcall restore name old)))
      (let ((copy (nelisp-native-funcall-v2-primitive (car row))))
        (setcar (cdr copy) 'poison)
        (should (equal row (nelisp-native-funcall-v2-primitive (car row))))))))
(ert-deftest u4c/gnu-results-errors-text-and-markers ()
  (dolist (row native-buffer-u4c-family)
    (let ((vm (native-buffer-u4c-function row))
          (value (nelisp-native-funcall-v2-initializer (cadr row))))
      (dolist (narrow '(nil t))
        (dolist (position (if narrow '(2 4 8) '(1 3 5 9)))
          (dolist (args (native-buffer-u4c-cases (car row)))
            (should (equal (native-buffer-u4c-observe vm args position narrow)
                           (native-buffer-u4c-observe value args position narrow)))))))))
(ert-deftest u4c/underflow-and-neighbor-slots-refused ()
  (dolist (row native-buffer-u4c-family)
    (when (> (nth 2 row) 0)
      (should-not (eq (plist-get (nelisp-bytecode-compiler-input-build
                                 (make-byte-code 0 (unibyte-string (car row) 135) [] 1)) :status) 'complete))))
  (dolist (opcode '(107 114 115 128)) (should-not (nelisp-native-funcall-v2-primitive opcode))))
(ert-deftest u4c/error-stops-later-effect-with-exact-data ()
  ;; A returned condition list must never impersonate a signaled condition.
  (dolist (opcode '(119 120 121 122 127))
    (let* ((args (if (memq opcode '(119 120)) '(bad nil) '(bad)))
           (fn (native-buffer-u4c-function (assq opcode native-buffer-u4c-family)))
           (observed (native-buffer-u4c-observe fn args 3 nil))
           (data (cadr (car observed))))
      (should (eq (caar observed) 'signal))
      (should-not (equal observed
                         (native-buffer-u4c-observe (lambda (&rest _) data) args 3 nil)))))
  (dolist (opcode '(123 124 125))
    (let ((observed (native-buffer-u4c-observe (native-buffer-u4c-error-function opcode) '(0 99) 3 nil)))
      (should (equal (car observed) (list 'signal (if (= opcode 125) '(args-out-of-range 0 99)
                                                    '(args-out-of-range current-buffer 0 99)))))
      (should (equal (cadr observed) "aé先中\n\tbé\nz")))))
(provide 'nelisp-native-buffer-u4c-test)
