;;; -*- lexical-binding: t; -*-
(require 'cl-lib) (require 'nelisp-aot-compiler) (require 'nelisp-standalone-build)
(dolist (f '(val-load sexp-clone-into cons-construct nlconsbox-alloc nlconsbox-set-car nlconsbox-set-cdr nlconsbox-clone nlvector-clone nlstr-clone nlchartable-clone nlboolvector-clone nlcell-clone nlrecord-clone)) (require (intern (format "nelisp-cc-%s" f))))
(defun al-find-def (name forms) (or (cl-find-if (lambda (x) (eq (cadr x) name)) forms) (error "Missing %S" name)))
(defun al-read-def (name file) (with-temp-buffer (insert-file-contents file) (goto-char (point-min)) (search-forward (format "(defun %s " name)) (goto-char (match-beginning 0)) (read (current-buffer))))
(defun al-arm (n form) (cond ((equal (car-safe form) (list '= 'base n)) form) ((consp form) (or (al-arm n (car form)) (al-arm n (cdr form))))))
(let* ((variant (or (getenv "AL_VARIANT") "positive")) (output (getenv "AL_OUTPUT"))
       (base #x3b000000) (slots (+ base 256)) (acc (+ base 448)) (scratch (+ base 480))
       (child (+ base 1024)) (child2 (+ base 1120))
       (pools (append nelisp-standalone--applyfn-bytecode-helpers nelisp-standalone--applyfn-core-helpers nelisp-standalone--applyfn-bf-helpers))
       (vm (al-find-def 'wf_bytecode_execute_frame pools))
       (old-vm '(cond ((= base 66) (let* ((right (wf_bytecode_slot slots (- sp 1))) (left (wf_bytecode_slot slots (- sp 2))) (tmp (alloc-bytes 32 8))) (seq (nelisp_cons_construct left right tmp) (wf_bytecode_copy left tmp) (setq sp (- sp 1))))) ((= base 67) (let* ((top (wf_bytecode_slot slots (- sp 1))) (nil-slot (alloc-bytes 32 8)) (tmp (alloc-bytes 32 8))) (seq (wf_write_nil nil-slot) (nelisp_cons_construct top nil-slot tmp) (wf_bytecode_copy top tmp)))) ((= base 68) (let* ((right (wf_bytecode_slot slots (- sp 1))) (left (wf_bytecode_slot slots (- sp 2))) (mark2 (nl_root_mark env)) (tail (nl_root_reserve env)) (nil-slot (alloc-bytes 32 8)) (tmp (alloc-bytes 32 8))) (seq (wf_write_nil nil-slot) (nelisp_cons_construct right nil-slot tail) (nelisp_cons_construct left tail tmp) (wf_bytecode_copy left tmp) (setq sp (- sp 1)) (nl_root_release env mark2))))))
       (construct (copy-tree nelisp-cc-cons-construct--source))
       (build (copy-tree (al-find-def 'wf_bytecode_build_args pools)))
       (old-build (cl-subst 'old_build_args 'wf_bytecode_build_args '(defun wf_bytecode_build_args (slots first n acc) (if (= n 0) 0 (let* ((tmp (alloc-bytes 32 8))) (seq (nelisp_cons_construct (wf_bytecode_slot slots (+ first (- n 1))) acc tmp) (wf_bytecode_copy acc tmp) (wf_bytecode_build_args slots first (- n 1) acc)))))))
       (check-count 0) checks defs)
 (dolist (n '(66 67 68))
  (dolist (kind '(old new))
   (let ((body (copy-tree (cdr (al-arm n (if (eq kind 'old) old-vm vm))))))
    (unless body (error "Missing VM opcode %d" n))
    (when (eq kind 'new)
     (cond ((equal variant "old-allocation") (setq body (copy-tree (cdr (al-arm n old-vm)))))
           ((equal variant "bad-nil") (setq body (cl-subst 7 3 body)))
           ((and (= n 68) (equal variant "bad-tail")) (setq body (cl-subst '(nelisp_cons_construct left left left) '(nelisp_cons_construct left right left) body :test #'equal)))))
    (push `(defun ,(intern (format "%s_op%d" kind n)) (env slots sp) (seq ,@body sp)) defs))))
 (cond ((equal variant "bad-order") (setq build (cl-subst 'first '(+ first (- n 1)) build :test #'equal)))
       ((equal variant "old-allocation") (setq build (cl-subst 'wf_bytecode_build_args 'old_build_args old-build)))
       ((equal variant "bad-alias")
        (setq construct (cl-subst '(seq (ptr-write-u64 result-slot 0 0) (extern-call nl_consbox_set_car box arg0)) '(extern-call nl_consbox_set_car box arg0) construct :test #'equal)))
       ((equal variant "bad-header") (setq construct (cl-subst '(ptr-write-u64 (+ result-slot 24) 0 99) '(ptr-write-u64 (+ result-slot 24) 0 0) construct :test #'equal))))
 (cl-labels ((emit (x) (push x checks))
             (check (x) (emit `(if ,x 0 (seq (ptr-write-u64 ,base 24 ,(cl-incf check-count)) (syscall-direct 1 1 ,base 32 0 0 0) (syscall-direct 60 2 0 0 0 0 0)))))
             (slot (p tag a b c) (cl-loop for x in (list tag a b c) for k from 0 do (emit `(ptr-write-u64 ,p ,(* k 8) ,x))))
             (reset () (emit `(ptr-write-u64 ,base 0 0)) (emit `(ptr-write-u64 ,base 8 0)))
             (header (p) (check `(= (ptr-read-u64 ,p 0) 7)) (check `(= (ptr-read-u64 ,p 16) 0)) (check `(= (ptr-read-u64 ,p 24) 0)))
             (word (p off val) (check `(= (ptr-read-u64 (ptr-read-u64 ,p 8) ,off) ,val))))
  ;; Genuine constructor aliasing: all four output words, both aliased operands,
  ;; distinct result, slot immediates and direct immediate nil word 3.
  (dolist (a '(nil t -2305843009213693952 -2 0 1 2305843009213693951))
   (dolist (b '(nil t -2 9))
    (dolist (alias '(left right separate))
     (let ((out (pcase alias ('left slots) ('right (+ slots 32)) (_ acc)))
           (ta (cond ((null a) 0) ((eq a t) 1) (t 2))) (tb (cond ((null b) 0) ((eq b t) 1) (t 2)))
           (wa (cond ((null a) 3) ((eq a t) 7) (t (+ (* a 4) 1)))) (wb (cond ((null b) 3) ((eq b t) 7) (t (+ (* b 4) 1)))))
      (slot slots ta (if (integerp a) a 0) 123 456) (slot (+ slots 32) tb (if (integerp b) b 0) 789 987)
      (when (eq alias 'separate) (slot out 99 88 77 66)) (reset)
      (check `(= (nelisp_cons_construct ,slots ,(+ slots 32) ,out) ,out)) (header out) (word out 0 wa) (word out 8 wb)
      (check `(= (ptr-read-u64 ,base 0) 1)) (check `(= (ptr-read-u64 ,base 8) 24))))))
  (slot slots 2 -2 123 456) (reset) (emit `(nelisp_cons_construct ,slots 3 ,slots)) (header slots) (word slots 0 -7) (word slots 8 3)
  ;; Boxed slot clones retain payload identity and all metadata; later mutation
  ;; remains visible through the shared payload, even when result aliases input.
  (dolist (tag '(3 4 5 7 8 13 14 16 18))
   (dolist (alias '(left right separate))
    (let ((out (pcase alias ('left slots) ('right (+ slots 32)) (_ acc))))
     (slot slots tag child 123 456) (slot (+ slots 32) tag child2 789 987)
     (emit `(ptr-write-u64 ,child 16 1)) (emit `(ptr-write-u64 ,child 24 1))
     (emit `(ptr-write-u64 ,child2 16 1)) (emit `(ptr-write-u64 ,child2 24 1))
     (reset) (emit `(nelisp_cons_construct ,slots ,(+ slots 32) ,out)) (header out)
     (emit `(setq view-a (ptr-read-u64 (ptr-read-u64 ,out 8) 0))) (emit `(setq view-b (ptr-read-u64 (ptr-read-u64 ,out 8) 8)))
     (dolist (row (list (list 'view-a tag child 123 456) (list 'view-b tag child2 789 987)))
      (cl-loop for x in (cdr row) for k from 0 do (check `(= (ptr-read-u64 ,(car row) ,(* k 8)) ,x))))
     (check `(= (ptr-read-u64 ,base 8) 88))
     (emit `(ptr-write-u64 ,child 0 741)) (emit `(ptr-write-u64 ,child2 0 852))
     (check '(= (ptr-read-u64 (ptr-read-u64 view-a 8) 0) 741)) (check '(= (ptr-read-u64 (ptr-read-u64 view-b 8) 0) 852)))))
  ;; Extracted old/new VM branches; allocator hook confirms the intermediate
  ;; LIST2 tail is in the still-published right operand before next allocation.
  (dolist (kind '(old new))
   (dolist (op '(66 67 68))
    (slot slots 2 11 99 88) (slot (+ slots 32) 2 -2 77 66) (reset)
    (emit `(ptr-write-u64 ,base 48 ,(if (and (eq kind 'new) (= op 68)) (+ slots 32) 0)))
    (emit `(ptr-write-u64 ,base 56 0))
    (check `(= (,(intern (format "%s_op%d" kind op)) 0 ,slots ,(if (= op 67) 1 2)) 1)) (header slots) (word slots 0 45)
    (if (= op 66) (word slots 8 -7)
     (if (= op 67) (word slots 8 3)
      (progn (emit `(setq view-a (ptr-read-u64 (ptr-read-u64 ,slots 8) 8))) (check '(> view-a 4096)) (header 'view-a) (word 'view-a 0 -7) (word 'view-a 8 3))))
    (check `(= (ptr-read-u64 ,base 8) ,(+ (pcase op (66 24) (67 24) (68 80)) (if (eq kind 'old) (if (= op 66) 32 64) 0))))
    (when (and (eq kind 'new) (= op 68)) (check `(= (ptr-read-u64 ,base 56) 1)))
    (emit `(ptr-write-u64 ,base 48 0))))
  ;; build_args: zero-count leaves the accumulator's entire slot unchanged;
  ;; selected input window, reverse traversal, order and improper tail retained.
  (dolist (kind '(old new))
   (dolist (n '(0 1 2 4))
    (dotimes (i 6) (slot (+ slots (* i 32)) 2 (+ 10 i) 0 0))
    (slot acc 2 99 777 888) (reset)
    (check `(= (,(if (eq kind 'old) 'old_build_args 'wf_bytecode_build_args) ,slots 1 ,n ,acc) 0))
    (if (= n 0) (cl-loop for x in '(2 99 777 888) for k from 0 do (check `(= (ptr-read-u64 ,acc ,(* k 8)) ,x)))
     (progn (emit `(setq view-a ,acc))
      (dotimes (i n) (header 'view-a) (word 'view-a 0 (+ (* (+ i 11) 4) 1))
       (if (= i (1- n)) (word 'view-a 8 397) (emit '(setq view-a (ptr-read-u64 (ptr-read-u64 view-a 8) 8)))))))
    (check `(= (ptr-read-u64 ,base 8) ,(+ (* n 24) (* (max 0 (1- n)) 32) (if (eq kind 'old) (* n 32) 0))))))
  (let ((source `(seq
     ,@(mapcar (lambda (n) (al-find-def n pools)) '(wf_bytecode_slot wf_bytecode_copy wf_copy32 wf_write_nil))
     ,construct ,build ,old-build ,@(nreverse defs)
     ,@(cl-loop for f in '(val-load sexp-clone-into nlconsbox-alloc nlconsbox-set-car nlconsbox-set-cdr nlconsbox-clone nlvector-clone nlstr-clone nlchartable-clone nlboolvector-clone nlcell-clone nlrecord-clone) append (cdr (symbol-value (intern (format "nelisp-cc-%s--source" f)))))
     (defun nl_bind_clone_force_flag () 0) (defun nl_gc_in_arena (p) 0) (defun nl_gc_is_boot (p) 0)
     (defun nl_alloc_str (a b c) (syscall-direct 60 199 0 0 0 0 0)) (defun nl_alloc_symbol (a b c) (syscall-direct 60 199 0 0 0 0 0))
     (defun nl_root_mark (env) 0) (defun nl_root_reserve (env) ,(+ base 2048)) (defun nl_root_release (env mark) 0)
     (defun nl_alloc_bytes (size align)
       (let ((p (ptr-read-u64 ,base 16)) (hook (ptr-read-u64 ,base 48)))
        (seq
         (when (and (> hook 0) (= (ptr-read-u64 ,base 0) 1))
          (if (and (= (ptr-read-u64 hook 0) 7) (= (ptr-read-u64 (ptr-read-u64 hook 8) 0) -7) (= (ptr-read-u64 (ptr-read-u64 hook 8) 8) 3))
            (ptr-write-u64 ,base 56 1) (syscall-direct 60 198 0 0 0 0 0)))
         (ptr-write-u64 ,base 16 (+ p size)) (ptr-write-u64 ,base 0 (+ (ptr-read-u64 ,base 0) 1))
         (ptr-write-u64 ,base 8 (+ (ptr-read-u64 ,base 8) size)) p)))
     (defun audit_run () (let ((failure 0) (view-a 0) (view-b 0)) (seq
       (syscall-direct 9 ,base 16777216 3 50 -1 0)
       (ptr-write-u64 (data-addr nl_arena_base) 0 ,base) (ptr-write-u64 ,base 192 1)
       (ptr-write-u64 ,base 16 ,(+ base 65536))
       ,@(nreverse checks)
       (ptr-write-u64 ,base 24 failure) (syscall-direct 1 1 ,base 32 0 0 0) (if (= failure 0) 0 2))))
     (defun _start () (syscall-direct 60 (audit_run) 0 0 0 0 0)))))
   (nelisp-link-units output (list (nelisp-standalone--compile-to-unit "list-audit.o" source) (nelisp-standalone--arena-base-slot-unit)) "_start")
   (with-temp-file (concat output ".source.el") (prin1 source (current-buffer)))
   (princ (format "CONS-NATIVE-COMPILED variant=%s checks=%d\n" variant check-count)))))
