;;; -*- lexical-binding: t; -*-
(require 'cl-lib) (require 'nelisp-standalone-build)
(defun ad-def (n pools) (or (cl-find-if (lambda (f) (eq (cadr f) n)) pools) (error "Missing %S" n)))
(let* ((variant (or (getenv "AD_VARIANT") "positive")) (output (getenv "AD_OUTPUT"))
       (pools (append nelisp-standalone--applyfn-bytecode-helpers nelisp-standalone--applyfn-core-helpers))
       (original (copy-tree (ad-def 'wf_bytecode_builtin_difference pools)))
       (helper (copy-tree original)) (arith (copy-tree (ad-def 'wf_bytecode_small_arithmetic pools)))
       (base #x3a000000) (fn (+ base 128)) (data (+ base 256)) (head (+ base 320)) (tail (+ base 384))
       (td (+ base 448)) (name (+ base 512)) (hb (+ base 576)) (nb (+ base 608)) (args (+ base 640)) (out (+ base 736))
       (minv -2305843009213693952) (maxv 2305843009213693951)
       (values '(-9223372036854775808 -2305843009213693953 -2305843009213693952 -2305843009213693951 -1073741824 -2 -1 0 1 2 1073741823 2305843009213693950 2305843009213693951 2305843009213693952 9223372036854775807))
       (cases nil) (functions nil) (calls nil) (serial 0))
 (pcase variant
  ("bad-head" (setq helper (cl-subst nil '(/= (symbol-name-eq head "builtin") 1) helper :test #'equal)))
  ("bad-name" (setq helper (cl-subst nil '(/= (symbol-name-eq name "-") 1) helper :test #'equal)))
  ("bad-tail" (setq helper (cl-subst nil '(/= (ptr-read-u64 tail-data 8) 3) helper :test #'equal)))
  ("bad-argc" (setq helper (cl-subst nil '(/= argc 2) helper :test #'equal)))
  ("bad-tag" (setq helper (cl-subst nil '(/= (sexp-tag function) 7) helper :test #'equal)))
  ("bad-op" (setq helper (cl-subst '(wf_bytecode_small_arithmetic args 2 92) '(wf_bytecode_small_arithmetic args 2 90) helper :test #'equal)))
  ("bad-copy" (setq helper (cl-subst '(ptr-write-u64 result 8 (ptr-read-u64 args 8)) '(wf_bytecode_copy result args) helper :test #'equal)))
  ("bad-allocation" (setcar (nthcdr 3 helper) `(seq (nl_alloc_bytes 32 8) ,(nth 3 helper)))))
 (unless (or (equal variant "positive") (not (equal helper original))) (error "Inactive mutant %s" variant))
 (cl-labels ((add (a b &optional changes eligible argc alias forced)
    (push (list a b changes (if (eq eligible 'no) nil t) (or argc 2) alias (or forced 0)) cases)))
  (dolist (a values) (dolist (b values) (add a b)))
  (dolist (tag '(0 1 3 4 5 7 8 13 14 16 17 18))
   (add 7 2 `((,args 0 ,tag))) (add 7 2 `((,(+ args 32) 0 ,tag))))
  (dolist (argc '(-1 0 1 3 10)) (add 7 2 nil 'no argc))
  (dolist (tag '(0 1 2 3 4 8 17 18)) (add 7 2 `((,fn 0 ,tag)) 'no))
  (dolist (word '(0 3 5 7 4096))
   (add 7 2 `((,data 0 ,word)) 'no) (add 7 2 `((,data 8 ,word)) 'no) (add 7 2 `((,td 0 ,word)) 'no))
  (dolist (tag '(0 1 2 3 5 8 14 16 17 18))
   (add 7 2 `((,head 0 ,tag)) 'no) (add 7 2 `((,tail 0 ,tag)) 'no) (add 7 2 `((,name 0 ,tag)) 'no))
  ;; Distinct wrong literals, prefixes, and improper/cyclic endings.
  (dolist (word '(0 7 5)) (add 7 2 `((,td 8 ,word)) 'no))
  (add 7 2 `((,td 8 ,tail)) 'no)
  (add 7 2 `((,hb 0 31078196194145635)) 'no)
  (add 7 2 `((,head 24 6)) 'no) (add 7 2 `((,head 24 8)) 'no)
  (add 7 2 `((,nb 0 43)) 'no) (add 7 2 `((,name 24 0)) 'no) (add 7 2 `((,name 24 2)) 'no)
  (add 7 2 nil nil 2 1) (add 7 2 nil nil 2 2)
  (add 7 2 nil nil 2 nil 1) (add 7 2 nil nil 2 nil 2))
 (setq cases (nreverse cases))
 (dolist (row cases)
  (cl-incf serial)
  (pcase-let* ((`(,a ,b ,changes ,eligible ,argc ,alias ,forced) row)
               (at (or (nth 2 (cl-find-if (lambda (c) (and (= (car c) args) (= (cadr c) 0))) changes)) 2))
               (bt (or (nth 2 (cl-find-if (lambda (c) (and (= (car c) (+ args 32)) (= (cadr c) 0))) changes)) 2))
               (ok (and eligible (= forced 0) (= at 2) (= bt 2) (<= minv a maxv) (<= minv b maxv) (<= minv (- a b) maxv)))
               (dest (cond ((eq alias 1) args) ((eq alias 2) (+ args 32)) (t out)))
               (forms nil) (n (intern (format "ad_case_%d" serial))))
   (cl-labels ((emit (f) (push f forms)) (write (p off v) (emit `(ptr-write-u64 ,p ,off ,v)))
               (slot (p tag v) (write p 0 tag) (write p 8 v) (write p 16 12345) (write p 24 54321))
               (check (f code) (emit `(if ,f 0 (when (= failure 0) (setq failure ,code))))))
    (write base 0 0) (write base 8 0) (write base 32 forced)
    (slot fn 7 data) (slot head 4 7) (write head 16 hb) (write head 24 7)
    (write hb 0 31078196194145634) (slot tail 7 td) (slot name 4 1) (write name 16 nb) (write name 24 1) (write nb 0 45)
    (write data 0 head) (write data 8 tail) (write td 0 name) (write td 8 3)
    (slot args 2 a) (slot (+ args 32) 2 b) (slot out 18 123)
    (dolist (c changes) (apply #'write c))
    (emit `(setq rc (wf_bytecode_builtin_difference ,fn ,args ,argc ,dest)))
    (check `(= rc ,(if ok 0 2)) 1)
    (check `(= (ptr-read-u64 ,base 8) ,(if eligible 1 0)) 2)
    (check `(= (ptr-read-u64 ,base 0) 0) 3)
    (if ok
     (progn
      (dolist (p (delete-dups (list args dest)))
       (check `(and (= (ptr-read-u64 ,p 0) 2) (= (ptr-read-u64 ,p 8) ,(- a b)) (= (ptr-read-u64 ,p 16) 0) (= (ptr-read-u64 ,p 24) 0)) 4))
      (unless (= dest (+ args 32)) (check `(and (= (ptr-read-u64 ,(+ args 32) 0) ,bt) (= (ptr-read-u64 ,(+ args 32) 8) ,b) (= (ptr-read-u64 ,(+ args 32) 16) 12345) (= (ptr-read-u64 ,(+ args 32) 24) 54321)) 5)))
     (progn
      (dolist (spec (list (list args at a) (list (+ args 32) bt b) (list out 18 123)))
       (check `(and (= (ptr-read-u64 ,(car spec) 0) ,(cadr spec)) (= (ptr-read-u64 ,(car spec) 8) ,(caddr spec)) (= (ptr-read-u64 ,(car spec) 16) 12345) (= (ptr-read-u64 ,(car spec) 24) 54321)) 6))))
    (push `(defun ,n () (let ((failure 0) (rc 0)) (seq ,@(nreverse forms) (if (/= failure 0) (ptr-write-u64 ,base 16 ,serial) 0) failure))) functions)
    (push `(when (= failure 0) (setq failure (,n))) calls))))
 (setcar (cdr arith) 'ad_real_arithmetic)
 (let ((source `(seq ,@ (nreverse functions)
    ,helper ,arith
    ,@(mapcar (lambda (n) (ad-def n pools)) '(wf_bytecode_slot wf_bytecode_copy wf_copy32 wf_write_int wf_write_t wf_write_nil))
    (defun wf_bytecode_small_arithmetic (slots sp op) (seq (ptr-write-u64 ,base 8 (+ (ptr-read-u64 ,base 8) 1)) (if (/= (ptr-read-u64 ,base 32) 0) (ptr-read-u64 ,base 32) (ad_real_arithmetic slots sp op))))
    (defun nl_alloc_bytes (size align) (seq (ptr-write-u64 ,base 0 (+ (ptr-read-u64 ,base 0) 1)) ,(+ base 4096)))
    (defun audit_run () (let ((failure 0)) (seq (syscall-direct 9 ,base 65536 3 50 -1 0) ,@(nreverse calls) (ptr-write-u64 ,base 24 failure) (syscall-direct 1 1 ,base 32 0 0 0) failure)))
    (defun _start () (syscall-direct 60 (audit_run) 0 0 0 0 0)))))
  (nelisp-link-units output (list (nelisp-standalone--compile-to-unit "call-diff-audit.o" source)) "_start")
  (with-temp-file (concat output ".source.el") (prin1 source (current-buffer)))
  (with-temp-file (concat output ".original.el") (prin1 original (current-buffer)))
  (princ (format "CALL-DIFF-UNIT-COMPILED variant=%s cases=%d\n" variant serial))))
