;;; Extracted production tagged-word equality audit. -*- lexical-binding: t; -*-
(require 'cl-lib)
(require 'nelisp-aot-compiler)
(require 'nelisp-standalone-build)
(require 'nelisp-cc-val-load)
(require 'nelisp-cc-sexp-clone-into)
(require 'nelisp-cc-jit-cons-car-ptr)
(require 'nelisp-cc-jit-cons-cdr-ptr)

(defvar audit-eq-base #x36000000)
(defvar audit-eq-next (+ audit-eq-base 4096))
(defvar audit-eq-init nil)
(defvar audit-eq-cases nil)
(defun audit-eq-alloc (size)
  (prog1 audit-eq-next (setq audit-eq-next (+ audit-eq-next (* 8 (/ (+ size 7) 8))))))
(defun audit-eq-write (p offset value)
  (push `(ptr-write-u64 ,p ,offset ,value) audit-eq-init))
(defun audit-eq-slot (tag payload &optional v16 v24)
  (let ((p (audit-eq-alloc 32)))
    (audit-eq-write p 0 tag) (audit-eq-write p 8 payload)
    (audit-eq-write p 16 (or v16 0)) (audit-eq-write p 24 (or v24 0)) p))
(defun audit-eq-cons (a b)
  (let ((p (audit-eq-alloc 16)))
    (audit-eq-write p 0 a) (audit-eq-write p 8 b)
    (audit-eq-slot 7 p)))
(defun audit-eq-string (tag text)
  (let* ((bytes (encode-coding-string text 'utf-8)) (p (audit-eq-alloc (length bytes))))
    (dotimes (i (length bytes)) (push `(ptr-write-u8 ,p ,i ,(aref bytes i)) audit-eq-init))
    (if (memq tag '(6 15))
        (let ((box (audit-eq-alloc 32)))
          (audit-eq-write box 8 p) (audit-eq-write box 16 (length bytes))
          (audit-eq-slot tag box))
      (audit-eq-slot tag (length bytes) p (length bytes)))))
(defun audit-eq-bignum (sign limbs)
  (let ((p (audit-eq-alloc (* 4 (length limbs)))))
    (cl-loop for limb in limbs for i from 0 do
             (push `(ptr-write-u32 ,p ,(* i 4) ,limb) audit-eq-init))
    (audit-eq-slot 13 sign p (length limbs))))
(defun audit-eq-case (name a b expected)
  (push (list name a b expected) audit-eq-cases))
(defun audit-eq-def (name pools)
  (or (cl-find-if (lambda (form) (and (eq (car-safe form) 'defun) (eq (cadr form) name))) pools)
      (error "Missing genuine helper %S" name)))
(defun audit-eq-word-call (offset)
  ;; Keep both-pointer recursion direct, preserving the pre-existing TCO edge.
  (let ((a `(ptr-read-u64 (ptr-read-u64 a 8) ,offset))
        (b `(ptr-read-u64 (ptr-read-u64 b 8) ,offset)))
    `(if (and (= (logand ,a 1) 0) (= (logand ,b 1) 0))
         (bf_equal2 ,a ,b)
       (bf_equal_words ,a ,b))))

(let* ((variant (or (getenv "AUDIT_EQ_VARIANT") "positive"))
       (output (or (getenv "AUDIT_EQ_OUTPUT") "target/p34/tagged-equal-positive"))
       (pools (append nelisp-standalone--applyfn-bf-helpers
                      nelisp-standalone--applyfn-core-helpers
                      nelisp-standalone--applyfn-m5-helpers
                      nelisp-standalone--fileio-forms-part1))
       (original (copy-tree (audit-eq-def 'bf_equal2 pools)))
       (old-arm '((= ta 7)
                  (if (= (bf_equal2 (nl_cons_car_ptr a) (nl_cons_car_ptr b)) 1)
                      (bf_equal2 (nl_cons_cdr_ptr a) (nl_cons_cdr_ptr b)) 0)))
       (new-arm `((= ta 7)
                  (if (= ,(audit-eq-word-call 0) 1)
                      ,(audit-eq-word-call 8) 0)))
       (candidate (copy-tree original))
       (legacy (cl-subst old-arm new-arm original :test #'equal))
       (old (cl-subst 'audit_old_equal 'bf_equal2 legacy))
       (word-slot (copy-tree (audit-eq-def 'bf_equal_word_slot pools)))
       (words (copy-tree (audit-eq-def 'bf_equal_words pools)))
       (leaf-names '(bf_eq2 m5_string_tag_p m5_streq m5_streq_bytes m5_byte_at m5_strlen
                    m5_length nl_str_charlen nl_str_charlen_c nl_aref_cache_slot
                    m5_list_len wf_cdr_has_more nl_bi_strptr nl_bi_strlen
                    nl_bignum_mag_cmp_eqlen nl_bignum_mag_cmp nl_bignum_cmp_bignum))
       (leaves (mapcar (lambda (name) (copy-tree (audit-eq-def name pools))) leaf-names))
       (decoder (audit-eq-def 'nl_sci_store_imm (cdr nelisp-cc-sexp-clone-into--source)))
       (loader (audit-eq-def 'nl_val_load (cdr nelisp-cc-val-load--source)))
       (ints (list (- (expt 2 61)) (- -1 (expt 2 30)) -3 -2 -1 0 1 2 3
                   (expt 2 30) (1- (expt 2 61)))))
  (when (equal legacy original) (error "Exact canonical word-reading tag7 arm missing"))
  (unless (equal (cl-subst new-arm old-arm legacy :test #'equal) original)
    (error "Legacy reconstruction differs outside exact tag7 arm"))
  ;; Bind only genuine string-cache data addresses into the private mmap.
  (setq leaves (cl-subst (+ audit-eq-base 256) '(data-addr nl_thread_parallel_ctx) leaves :test #'equal)
        leaves (cl-subst (+ audit-eq-base 512) '(data-addr nl_aref_cache_table) leaves :test #'equal))
  (pcase variant
    ("bad-shift" (setq word-slot (cl-subst 'shr 'sar word-slot)))
    ("bad-odd" (setq words (cl-subst '(if (= a b) 1 0)
                                   '(if (= a 3) (if (= b 3) 1 0) (if (= b 3) 0 1)) words :test #'equal)))
    ("bad-mixed-tag" (setq word-slot (cl-subst t '(= (ptr-read-u64 slot 0) 2) word-slot :test #'equal)))
    ("bad-cdr" (setq candidate (cl-subst 1 (audit-eq-word-call 8) candidate :test #'equal)))
    ("bad-pointer" (setq candidate
                         (cl-subst 1 '(bf_equal2 (ptr-read-u64 (ptr-read-u64 a 8) 0)
                                                 (ptr-read-u64 (ptr-read-u64 b 8) 0))
                                   candidate :test #'equal))))
  ;; Cartesian immediate/boxed-immediate matrix, including noncanonical odd T.
  (let ((values (list (cons 3 '(nil)) (cons 7 '(t)) (cons 11 '(t)) (cons 15 '(t))
                      (cons (audit-eq-slot 0 123) '(nil)) (cons (audit-eq-slot 1 456) '(t)))))
    (dolist (n ints)
      (push (cons (+ (* n 4) 1) (cons 'int n)) values)
      (push (cons (audit-eq-slot 2 n) (cons 'int n)) values))
    ;; Same 64-bit payload as an integer but a different tag must not match.
    (push (cons (audit-eq-slot 3 -2) '(float . -2)) values)
    (dolist (a values)
      (dolist (b values)
        (audit-eq-case "immediate-boxed-matrix" (car a) (car b)
                       (if (equal (cdr a) (cdr b)) 1 0)))))
  (dolist (ta '(5 6 14 15))
    (dolist (tb '(5 6 14 15))
      (audit-eq-case "string-cross-tag" (audit-eq-string ta "abc") (audit-eq-string tb "abc") 1)
      (audit-eq-case "string-unequal" (audit-eq-string ta "abc") (audit-eq-string tb "abd") 0)))
  (audit-eq-case "symbol-same-name" (audit-eq-string 4 "audit") (audit-eq-string 4 "audit") 1)
  (audit-eq-case "symbol-other-name" (audit-eq-string 4 "audit") (audit-eq-string 4 "other") 0)
  (dolist (tag '(8 9 10 11 12 16 17 18))
    (let ((a (audit-eq-slot tag (+ audit-eq-base 2048))))
      (audit-eq-case "opaque-same-slot" a a 1)
      (audit-eq-case "opaque-same-payload" a (audit-eq-slot tag (+ audit-eq-base 2048)) 1)
      (audit-eq-case "opaque-distinct-payload" a (audit-eq-slot tag (+ audit-eq-base 2056)) 0)))
  (dolist (bits (list 0 (- (expt 2 63)) #x3ff0000000000000 #x7ff8000000000000))
    (audit-eq-case "float-bits" (audit-eq-slot 3 bits) (audit-eq-slot 3 bits) 1))
  (audit-eq-case "float-signed-zero" (audit-eq-slot 3 0) (audit-eq-slot 3 (- (expt 2 63))) 0)
  (audit-eq-case "bignum-equal" (audit-eq-bignum 0 '(7 9 2)) (audit-eq-bignum 0 '(7 9 2)) 1)
  (audit-eq-case "bignum-different" (audit-eq-bignum 0 '(7 9 2)) (audit-eq-bignum 0 '(7 8 2)) 0)
  (audit-eq-case "bignum-sign" (audit-eq-bignum 0 '(7 9 2)) (audit-eq-bignum 1 '(7 9 2)) 0)
  (let* ((a (audit-eq-cons 5 -7)) (b (audit-eq-cons 5 -7))
         (c (audit-eq-cons 5 -11)))
    (audit-eq-case "nested-cons" (audit-eq-cons a a) (audit-eq-cons b b) 1)
    (audit-eq-case "nested-late-mismatch" (audit-eq-cons a a) (audit-eq-cons b c) 0)
    (audit-eq-case "nested-identical-pointer" a a 1))
  (setq audit-eq-cases (nreverse audit-eq-cases))
  (let* ((table (audit-eq-alloc (* 24 (length audit-eq-cases))))
         (left (audit-eq-cons 5 -7)) (right (audit-eq-cons 5 -7))
         (left-box (+ left 0)) (right-box (+ right 0))
         (allocation-fn (if (equal variant "old-zero") 'audit_old_equal 'bf_equal2))
         (pool-start (+ audit-eq-base #x100000)))
    (cl-loop for (_name a b expected) in audit-eq-cases for i from 0 do
             (audit-eq-write table (* i 24) a)
             (audit-eq-write table (+ (* i 24) 8) b)
             (audit-eq-write table (+ (* i 24) 16) expected))
    (nelisp-link-units output
     (list (nelisp-standalone--compile-to-unit "tagged-equality.o"
      `(seq
        (defun nl_alloc_bytes (size align)
          (let ((p (ptr-read-u64 ,audit-eq-base 40)))
            (seq (ptr-write-u64 ,audit-eq-base 32 (+ (ptr-read-u64 ,audit-eq-base 32) 1))
                 (ptr-write-u64 ,audit-eq-base 40 (+ p 32)) p)))
        ,decoder ,loader
        ,nelisp-cc-jit-cons-car-ptr--source ,nelisp-cc-jit-cons-cdr-ptr--source
        ,@leaves ,old ,word-slot ,words ,candidate
        (defun audit_run ()
          (let ((i 0) (failure 0) (old-result 0) (new-result 0) (expected 0))
            (seq
             (syscall-direct 9 ,audit-eq-base 16777216 3 50 -1 0)
             (ptr-write-u64 ,audit-eq-base 40 ,pool-start)
             ,@(nreverse audit-eq-init)
             ;; Allocate oracle runs before the general matrix.
             (ptr-write-u64 ,audit-eq-base 32 0)
             (if (= (audit_old_equal ,left-box ,right-box) 1) 0 (setq failure 10))
             (ptr-write-u64 ,audit-eq-base 0 (ptr-read-u64 ,audit-eq-base 32))
             (if (= (ptr-read-u64 ,audit-eq-base 0) 4) 0 (setq failure 11))
             (ptr-write-u64 ,audit-eq-base 32 0)
             (if (= (,allocation-fn ,left-box ,right-box) 1) 0 (setq failure 12))
             (ptr-write-u64 ,audit-eq-base 8 (ptr-read-u64 ,audit-eq-base 32))
             (if (= (ptr-read-u64 ,audit-eq-base 8) 0) 0 (setq failure 13))
             (while (and (= failure 0) (< i ,(length audit-eq-cases)))
               (ptr-write-u64 (ptr-read-u64 ,left 8) 0 (ptr-read-u64 ,table (* i 24)))
               (ptr-write-u64 (ptr-read-u64 ,right 8) 0 (ptr-read-u64 ,table (+ (* i 24) 8)))
               (ptr-write-u64 (ptr-read-u64 ,left 8) 8 3)
               (ptr-write-u64 (ptr-read-u64 ,right 8) 8 3)
               (setq expected (ptr-read-u64 ,table (+ (* i 24) 16)))
               (setq old-result (audit_old_equal ,left ,right))
               (setq new-result (bf_equal2 ,left ,right))
               (if (= old-result expected) 0 (setq failure 20))
               (if (= new-result expected) 0 (setq failure 21))
               (setq i (+ i 1)))
             ;; CAR mismatch must prevent touching invalid CDR word 0.
             (when (= failure 0)
               (ptr-write-u64 (ptr-read-u64 ,left 8) 0 5)
               (ptr-write-u64 (ptr-read-u64 ,right 8) 0 9)
               (ptr-write-u64 (ptr-read-u64 ,left 8) 8 0)
               (ptr-write-u64 (ptr-read-u64 ,right 8) 8 0)
               (if (= (audit_old_equal ,left ,right) 0) 0 (setq failure 22))
               (if (= (bf_equal2 ,left ,right) 0) 0 (setq failure 23)))
             (ptr-write-u64 ,audit-eq-base 16 i)
             (ptr-write-u64 ,audit-eq-base 24 failure)
             (syscall-direct 1 1 ,audit-eq-base 32 0 0 0)
             failure)))
        (defun _start () (syscall-direct 60 (audit_run) 0 0 0 0 0))))) "_start")
    (with-temp-file (concat output ".cases.el") (prin1 audit-eq-cases (current-buffer)))
    (with-temp-file (concat output ".candidate.el") (prin1 (list word-slot words candidate) (current-buffer)))
    (princ (format "TAGGED-EQUAL-COMPILED variant=%s cases=%d exact-original=%s\n"
                   variant (length audit-eq-cases) (secure-hash 'sha256 (prin1-to-string original))))))
