;;; nelisp-native-template-test.el --- Stencil boundary and refusal controls -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'ert)
(require 'nelisp-native-template)
(require 'nelisp-native-template-pin)
(defun nelisp-native-template-test--recipe (code &optional constants descriptor maximum)
  (list :descriptor (or descriptor 0) :code (apply #'unibyte-string code)
        :constants (or constants [42]) :stack-depth (or maximum 4)))
(ert-deftest nelisp-native-template-patches-boundaries ()
  (dolist (kind nelisp-native-template-hole-grammar)
    (dolist (value (list (- (expt 2 31)) -1 0 (1- (expt 2 31))))
      (let* ((bytes (unibyte-string 0 0 0 0))
             (fragment (list :bytes bytes :holes (list (list :name 'x :kind kind :width 4 :signed t :mask '(0 0 0 0) :offset 0)))))
        (should (nelisp-native-template-check-holes fragment))
        (nelisp-native-template-patch32 bytes 0 value)
        (should (= (logand value #xffffffff)
                   (+ (aref bytes 0) (ash (aref bytes 1) 8) (ash (aref bytes 2) 16) (ash (aref bytes 3) 24))))))
    (dolist (value (list (1- (- (expt 2 31))) (expt 2 31)))
      (should-error (nelisp-native-template-patch32 (unibyte-string 0 0 0 0) 0 value)))))
(ert-deftest nelisp-native-template-grammar-negative-controls ()
  (let* ((lib (nelisp-native-template-open-library)) (fragment (cdr (assq 'copy (plist-get lib :fragments)))))
    (dolist (change '((:width . 8) (:signed . nil) (:kind . pointer) (:offset . -1) (:mask . (1 0 0 0))))
      (let* ((broken (copy-tree fragment)) (hole (car (plist-get broken :holes))))
        (setf (plist-get hole (car change)) (cdr change))
        (should-error (nelisp-native-template-check-holes broken))))
    (let* ((broken (copy-tree fragment)) (holes (plist-get broken :holes)))
      (setf (plist-get (cadr holes) :offset) (plist-get (car holes) :offset))
      (should-error (nelisp-native-template-check-holes broken)))))
(ert-deftest nelisp-native-template-library-refuses-before-copy-map ()
  (let* ((snapshot (with-temp-buffer (set-buffer-multibyte nil)
                                    (insert-file-contents-literally nelisp-native-template--library-path) (buffer-string)))
         (path (make-temp-file "stencils-"))
         (copies nelisp-native-template--copy-count) (maps nelisp-native-load--trusted-map-count))
    (unwind-protect
        (dolist (control '(byte stale hole absent))
          (let* ((nelisp-native-template--snapshot nil) (nelisp-native-template--library-path path)
                 (nelisp-native-template-library-sha256 nelisp-native-template-library-sha256)
                 (library (nelisp-native-template--read-library snapshot))
                 (bytes (copy-sequence snapshot)))
            (pcase control
              ('byte (aset bytes 4 (logxor 1 (aref bytes 4))))
              ('absent (setq nelisp-native-template-library-sha256 nil))
              ('stale (setf (plist-get library :abi) '(stale)))
              ('hole (setf (plist-get (car (plist-get (cdr (assq 'copy (plist-get library :fragments))) :holes)) :width) 8)))
            (when (memq control '(stale hole))
              (setq bytes (concat (nelisp-native-template--print library) "\n")
                    nelisp-native-template-library-sha256 (secure-hash 'sha256 bytes)))
            (let ((coding-system-for-write 'no-conversion)) (write-region bytes nil path nil 'silent))
            (set-file-modes path #o600)
            (should-error (nelisp-native-template-open-library))
            (should (= copies nelisp-native-template--copy-count))
            (should (= maps nelisp-native-load--trusted-map-count))))
      (delete-file path))))
(ert-deftest nelisp-native-template-library-mode-gate ()
  "A group-writable checkout opens; a world-writable library is refused."
  (let* ((snapshot (with-temp-buffer (set-buffer-multibyte nil)
                     (insert-file-contents-literally nelisp-native-template--library-path)
                     (buffer-string)))
         (path (make-temp-file "stencils-mode-")))
    (unwind-protect
        (let ((coding-system-for-write 'no-conversion))
          (write-region snapshot nil path nil 'silent)
          (dolist (case '((#o664 . t) (#o666 . nil)))
            (let ((nelisp-native-template--snapshot nil)
                  (nelisp-native-template--library-path path))
              (set-file-modes path (car case))
              (if (cdr case)
                  (should (nelisp-native-template-open-library))
                (should-error (nelisp-native-template-open-library))))))
      (delete-file path))))
(ert-deftest nelisp-native-template-immutable-snapshot ()
  (let* ((library (nelisp-native-template-open-library))
         (fragment (cdr (assq 'copy (plist-get library :fragments)))))
    (aset (plist-get fragment :bytes) 0 255)
    (should-not (= (aref (plist-get (cdr (assq 'copy (plist-get (nelisp-native-template-open-library) :fragments))) :bytes) 0) 255))))
(ert-deftest nelisp-native-template-validator-refuses-malformed-input ()
  (dolist (recipe (list (nelisp-native-template-test--recipe '(136 135))
                       (nelisp-native-template-test--recipe '(129 0))
                       (nelisp-native-template-test--recipe '(193 135))
                       (nelisp-native-template-test--recipe '(192 192 135) nil nil 1)
                       (nelisp-native-template-test--recipe '(192))
                       (nelisp-native-template-test--recipe '(192 135 192))
                       (nelisp-native-template-test--recipe '(130 1 0 135))
                       (nelisp-native-template-test--recipe '(192 135) nil 129)))
    (should-error (nelisp-native-template-validate recipe))))
(ert-deftest nelisp-native-template-assembler-composes-labelled-fragments ()
  (let* ((recipe (nelisp-native-template-test--recipe '(192 137 66 135)))
         (cert (nelisp-native-template-validate recipe))
         (assembled (nelisp-native-template-assemble cert (nelisp-native-template-open-library)))
         (text (plist-get assembled :text)) (ranges (plist-get assembled :pc-ranges)))
    (should (= 4 (length ranges)))
    (should (= 195 (aref text (1- (length text)))))
    (should (equal '("nl_native_funcall_v2" "nl_native_poll_v2" "nl_root_pin_slot_v2")
                   (sort (delete-dups (mapcar (lambda (r) (plist-get r :symbol)) (plist-get assembled :relocs))) #'string<)))
    (dolist (range ranges) (should (<= (nth 1 range) (nth 2 range))))))
(ert-deftest nelisp-native-template-public-proof-checks-all-emission ()
  (cl-letf (((symbol-function 'nelisp-native-load-running-binary-sha256) (lambda () (make-string 64 ?a))))
    (let* ((recipe (nelisp-native-template-test--recipe '(192 137 66 135)))
           (certificate (nelisp-native-template-validate recipe))
           (assembled (nelisp-native-template-assemble certificate (nelisp-native-template-open-library)))
           (manifest (nelisp-native-template-manifest recipe certificate assembled)))
      (should-not (nelisp-native-template-check manifest))
      (dolist (field '(:root-count :result :staging :arity :exit-root-base))
        (let* ((broken (copy-tree manifest)) (cert (plist-get (plist-get broken :native-template-proof) :certificate)))
          (setf (plist-get cert field) (1+ (plist-get cert field)))
          (should (nelisp-native-template-check broken))))
      (let* ((broken (copy-tree manifest)) (native (plist-get broken :native))
             (bytes (base64-decode-string (plist-get native :text-base64))))
        (aset bytes 0 (logxor 1 (aref bytes 0)))
        (setf (plist-get native :text-base64) (base64-encode-string bytes t)
              (plist-get native :object-sha256) (secure-hash 'sha256 bytes))
        (setq broken (nelisp-native-load--raw-plist-without broken :artifact-sha256))
        (setq broken (append broken (list :artifact-sha256 (nelisp-native-template--hash broken))))
        (should (nelisp-native-template-check broken))))))
(ert-deftest nelisp-native-template-public-proof-refuses-cycles ()
  (let ((cycle (list 1))) (setcdr cycle cycle)
    (should-not (nelisp-native-template-bounded-data-p cycle))))

(ert-deftest nelisp-native-template-public-dispatch-refuses-cyclic-spine ()
  (let ((cycle (list :native-template-proof-version nelisp-native-template-proof-version)))
    (setcdr (cdr cycle) cycle)
    (should-error (nelisp-native-load-raw-v2-check cycle))))
(ert-deftest nelisp-native-template-validator-refuses-oversized-constants ()
  (should-error (nelisp-native-template-validate
                 (nelisp-native-template-test--recipe '(192 135) (vector (make-string 1048577 97))))))

(ert-deftest nelisp-native-template-ordinary-worklist-and-asymmetric-edges ()
  (dolist (code '((192 133 6 0 193 135 194 135)
                  (192 134 6 0 193 135 194 135)
                  (192 136 130 0 0)
                  (192 137 178 1 135)
                  (192 193 182 129 135)))
    (let ((before nelisp-native-template--validation-count))
      (should (nelisp-native-template-validate
               (nelisp-native-template-test--recipe code [nil t 42])))
      (should (= 1 (- nelisp-native-template--validation-count before)))))
  (dolist (code '((192 131 8 0 193 130 8 0 135)
                  (192 130 2 0 135)
                  (192 178 1 135)
                  (192 182 129 135)))
    (should-error (nelisp-native-template-validate
                   (nelisp-native-template-test--recipe code [nil t 42])))))

(ert-deftest nelisp-native-template-ordinary-switch-landing-domain ()
  (let* ((recipe (nelisp-native-template-test--recipe '(192 193 183 194 135 195 135) [7 nil 42 99]))
         (certificate (nelisp-native-template-validate recipe))
         (info (car (plist-get certificate :switch-targets)))
         (assembled (nelisp-native-template-assemble certificate (nelisp-native-template-open-library))))
    (should (equal (nth 2 info) '(0 3 5)))
    (should (= 7 (length (plist-get assembled :pc-ranges))))
    (setf (plist-get recipe :switch-targets) '(4))
    (should-error (nelisp-native-template-validate recipe))
    (setf (plist-get recipe :switch-targets) '(5))
    (should (nelisp-native-template-validate recipe))))

(ert-deftest nelisp-native-template-every-instruction-polls-and-root-bank ()
  (let* ((certificate (nelisp-native-template-validate
                       (nelisp-native-template-test--recipe '(192 136 130 0 0))))
         (assembled (nelisp-native-template-assemble certificate (nelisp-native-template-open-library)))
         (calls (cl-count "nl_native_poll_v2" (plist-get assembled :relocs)
                          :key (lambda (r) (plist-get r :symbol)) :test #'equal)))
    (should (= calls 3))
    (should (> (plist-get certificate :result) (+ (plist-get certificate :staging) 2)))
    (should (= (plist-get certificate :exit-root-base) (1+ (plist-get certificate :result))))))

(ert-deftest nelisp-native-template-interactive-p-keeps-gnu-dynamic-provider ()
  (let* ((certificate (nelisp-native-template-validate
                       (nelisp-native-template-test--recipe '(116 135))))
         (root (cdr (assq 'interactive-p (plist-get certificate :provider-roots))))
         (initializer (cl-find root (plist-get certificate :initializers)
                               :key (lambda (init) (plist-get init :root)))))
    (should (eq (plist-get initializer :value) 'interactive-p))
    (should-not (plist-get initializer :primitive))))

(ert-deftest nelisp-native-template-refuses-gnu-reserved-stack-ref-base ()
  (should-error (nelisp-native-template-validate
                 (nelisp-native-template-test--recipe '(0 135) [] 257)))
  (should-error (funcall (make-byte-code 257 (unibyte-string 0 135) [] 2) 42)))

(ert-deftest nelisp-native-template-full-frame-actions ()
  (dolist (recipe (list
                  (nelisp-native-template-test--recipe '(193 24 8 41 135) [template-dynamic 42])
                  (nelisp-native-template-test--recipe '(97 192 135))
                  (nelisp-native-template-test--recipe '(192 142 193 135) [(lambda () nil) 42])))
    (let* ((cert (nelisp-native-template-validate recipe))
           (assembly (nelisp-native-template-assemble cert (nelisp-native-template-open-library))))
      (should (plist-get cert :frame-p))
      (should (plist-get cert :frame-analysis))
      (should (cl-find "nl_native_frame_v2" (plist-get assembly :relocs)
                       :key (lambda (r) (plist-get r :symbol)) :test #'equal)))))

(ert-deftest nelisp-native-template-handler-only-cycle-poll-states ()
  ;; A callback may throw back into PC 1 twice before returning. There are
  ;; no ordinary branches; the exceptional transfer itself creates the cycle.
  (let* ((recipe (nelisp-native-template-test--recipe '(192 50 1 0 193 32 48 135) [tag callback]))
         (cert (nelisp-native-template-validate recipe))
         (assembly (nelisp-native-template-assemble cert (nelisp-native-template-open-library)))
         (calls (cl-count "nl_native_poll_v2" (plist-get assembly :relocs)
                          :key (lambda (r) (plist-get r :symbol)) :test #'equal)))
    (should (plist-get cert :handler-p))
    (should (equal (plist-get (plist-get cert :frame-analysis) :targets) '(1)))
    (should (= calls (length (plist-get cert :rows))))
    (should (= 1 (plist-get (plist-get cert :frame-analysis) :max-handlers)))))

(ert-deftest nelisp-native-template-poll-checks-pre-pop-handler-state ()
  ;; POP-HANDLER itself has an exceptional poll edge. Its target has a
  ;; different depth from the ordinary predecessor, so admission must refuse.
  (should-error (nelisp-native-template-validate
                 (nelisp-native-template-test--recipe '(192 50 4 0 48 193 135) [tag 42]))))

(ert-deftest nelisp-native-template-typed-frame-negative-controls ()
  (dolist (code '((48 192 135) (41 192 135) (192 50 2 0 193 135)
                  (193 24 130 0 0)))
    (should-error (nelisp-native-template-validate
                   (nelisp-native-template-test--recipe code [template-dynamic 42])))))

(ert-deftest nelisp-native-template-serialization-roundtrip-refuses-counterfeit-printer ()
  (let ((source (locate-library "nelisp-native-template-stencils.el" t))
        (value '(:v [1 nil t "a\"b\\c"] :p -4)))
    (unwind-protect
        (cl-letf (((symbol-function 'nelisp--repr) (lambda (_value) "(:v [1])")))
          (load source nil t t)
          (should (equal value (car (read-from-string (nelisp-native-template--print value)))))
          (should-error (let ((cycle (list 1))) (setcdr cycle cycle)
                          (nelisp-native-template--print cycle))))
      (load source nil t t))))
