;;; nelisp-native-buffer-u4b-test.el --- U4b lowering -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'ert)
(require 'nelisp-bytecode-native-rooted-cfg-contract)
(require 'nelisp-bytecode-native-rooted-cfg-constructor-contract)
(require 'nelisp-bytecode-native-rooted-cfg-safe-contract)
(require 'nelisp-native-load)
(load "support/native-buffer-u4b-fixtures.el" nil t t)
(ert-deftest u4b/exact-nine-opcodes-both-contracts-and-dynamic-exception ()
  (dolist (row native-buffer-u4b-family)
    (should (equal row (nelisp-native-funcall-v2-primitive (car row))))
    (let* ((input (nelisp-bytecode-compiler-input-build (native-buffer-u4b-function row)))
           (plan (nelisp-bytecode-native-rooted-cfg-plan input))
           (op (car (plist-get (car (plist-get plan :blocks)) :operations))))
      (should (eq (plist-get input :status) 'complete))
      (should (eq (plist-get plan :status) 'complete))
      (should (eq (plist-get op :opcode) (if (= (car row) 116) 'funcall 'primitive-call)))
      (should (= (plist-get op :argument-count) (nth 2 row)))
      (should (equal (plist-get op :argument-roots) (number-sequence 1 (nth 2 row))))
      (should (equal (plist-get plan :gateway-imports) '("nl_native_funcall_v2")))
      (when (= (car row) 116)
        (should (member (list :root (plist-get op :function-root) :value 'interactive-p)
                        (plist-get plan :immediate-initializers)))
        (should-not (cl-find 'interactive-p (plist-get plan :primitive-initializers)
                             :key (lambda (x) (plist-get x :primitive)))))
      (let* ((emitted (nelisp-bytecode-native-rooted-cfg-shared-emit-build
                       plan nelisp-bytecode-native-rooted-cfg-contract-shared-entry))
             (contract (nelisp-bytecode-native-rooted-cfg-contract-create-shared-v2 input plan emitted)))
        (should (eq (plist-get emitted :status) 'complete))
        (should (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract))
        (should (nelisp-bytecode-native-rooted-cfg-contract-f1-p contract)))
      (let* ((safe (nelisp-bytecode-native-rooted-cfg-plan input 'safe-primitives-v3))
             (emitted (nelisp-bytecode-native-rooted-cfg-emit safe nelisp-bytecode-native-rooted-cfg-safe-contract-entry)))
        (should (nelisp-bytecode-native-rooted-cfg-safe-contract-valid-p
                 (nelisp-bytecode-native-rooted-cfg-safe-contract-create input safe emitted)))))))
(ert-deftest u4b/frozen-values-and-defensive-table ()
  (let ((native-comp-enable-subr-trampolines nil))
    (dolist (row native-buffer-u4b-family)
      (unless (= (car row) 116)
        (let* ((name (cadr row)) (value (nelisp-native-funcall-v2-initializer name))
               (old (symbol-function name)) (restore (symbol-function 'fset)))
          (should (functionp value))
          (unwind-protect
              (progn (funcall restore name (lambda (&rest _) 'poison))
                     (should (eq value (nelisp-native-funcall-v2-initializer name))))
            (funcall restore name old))))
      (let ((copy (nelisp-native-funcall-v2-primitive (car row))))
        (setcar (cdr copy) 'poison)
        (should (equal row (nelisp-native-funcall-v2-primitive (car row))))))))
(ert-deftest u4b/gnu-results-errors-multibyte-narrowing-point-and-markers ()
  (dolist (row native-buffer-u4b-family)
    (unless (= (car row) 116)
      (let ((vm (native-buffer-u4b-function row))
            (value (nelisp-native-funcall-v2-initializer (cadr row))))
        (dolist (narrow '(nil t))
          (dolist (p (if narrow '(2 3 4 5 6) '(1 2 3 4 5 6 7)))
            (dolist (args (native-buffer-u4b-cases (car row)))
              (should (equal (native-buffer-u4b-observe vm args p narrow)
                             (native-buffer-u4b-observe value args p narrow))))))))))
(ert-deftest u4b/interactive-p-follows-current-cell-and-exact-errors ()
  (let ((vm (native-buffer-u4b-function '(116 interactive-p 0))))
    (dolist (value '(nil t rebound))
      (cl-letf (((symbol-function 'interactive-p) (lambda () value)))
        (should (eq (funcall vm) value))))
    (cl-letf (((symbol-function 'interactive-p) (lambda () (signal 'args-out-of-range '(1 2)))))
      (should (equal (condition-case e (funcall vm) (error e)) '(args-out-of-range 1 2))))))
(ert-deftest u4b/error-stops-later-effect-with-exact-data ()
  (let ((seen (native-buffer-u4b-observe (native-buffer-u4b-effect-function) '(bad) 3 nil)))
    (should (equal (car seen) '(wrong-type-argument fixnump bad)))
    (should (equal (nth 2 seen) "aé先中\n\tb"))))
(ert-deftest u4b/underflow-and-neighbors-refused ()
  (dolist (op '(113 117 118))
    (should-not (eq (plist-get (nelisp-bytecode-compiler-input-build
                               (make-byte-code 0 (unibyte-string op 135) [] 1)) :status) 'complete)))
  (dolist (op '(107 114 115)) (should-not (nelisp-native-funcall-v2-primitive op))))
;; Evaluate the actual standalone provider body on GNU buffers as an
;; independent oracle; the host initializer alone would test GNU against GNU.
(defvar nelisp--current-buffer)
(ert-deftest u4b/standalone-word-provider-agrees-with-gnu ()
  (let* ((source (expand-file-name "../scripts/nelisp-stdlib-prelude.el"
                                  (file-name-directory (or load-file-name
                                                          (locate-library "nelisp-native-buffer-u4b-test")))))
         (form (with-temp-buffer
                 (insert-file-contents source)
                 (goto-char (point-min))
                 (search-forward "(unless (fboundp 'forward-word)")
                 (goto-char (match-beginning 0))
                 (caddr (read (current-buffer)))))
         (provider (eval (cons 'lambda (cddr form)) t))
         (nelisp--current-buffer nil))
    (cl-letf (((symbol-function 'nelisp-point) (lambda (_) (point)))
              ((symbol-function 'nelisp-point-min) (lambda (_) (point-min)))
              ((symbol-function 'nelisp-point-max) (lambda (_) (point-max)))
              ((symbol-function 'nelisp-buffer-string)
               (lambda (_) (save-restriction (widen) (buffer-string))))
              ((symbol-function 'nelisp-goto-char) (lambda (p _) (goto-char p))))
      (dolist (narrow '(nil t))
        (dolist (p (if narrow '(2 3 4 5 6) '(1 2 3 4 5 6 7)))
          (dolist (args (native-buffer-u4b-cases 118))
            (should (equal (native-buffer-u4b-observe #'forward-word args p narrow)
                           (native-buffer-u4b-observe provider args p narrow)))))))))

(ert-deftest u4b/driver-and-fixtures-have-complete-forms ()
  (let ((root (expand-file-name ".." (file-name-directory
                                     (locate-library "nelisp-native-buffer-u4b-test")))))
    (dolist (file '("test/standalone-native-buffer-u4b-driver.el"
                    "test/support/native-buffer-u4b-fixtures.el"))
      (with-temp-buffer
        (insert-file-contents (expand-file-name file root))
        (emacs-lisp-mode) (check-parens)))))

(provide 'nelisp-native-buffer-u4b-test)
