;;; nelisp-native-funcall-v2-test.el --- Generic evaluator bridge tests -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'ert)
(require 'nelisp-bytecode-native-rooted-cfg-contract)
(require 'nelisp-bytecode-native-rooted-cfg-constructor-contract)
(require 'nelisp-native-load)
(defconst f1-test-root (expand-file-name ".." (file-name-directory (or load-file-name buffer-file-name))))
(defun f1-test-compile (form &optional emitter)
  (let* ((input (nelisp-bytecode-compiler-input-build (byte-compile form)))
         (plan (nelisp-bytecode-native-rooted-cfg-plan input))
         (emitted (if emitter
                      (nelisp-bytecode-native-rooted-cfg-emit plan "nl_native_rooted_cfg_probe_v1")
                    (nelisp-bytecode-native-rooted-cfg-shared-emit-build plan nelisp-bytecode-native-rooted-cfg-contract-shared-entry)))
         (contract (if emitter (nelisp-bytecode-native-rooted-cfg-contract-create input plan emitted)
                     (nelisp-bytecode-native-rooted-cfg-contract-create-shared-v2 input plan emitted))))
    (list input plan emitted contract)))
(ert-deftest f1/vertical-slice-one-import-and-sealed-contract ()
  (pcase-let* ((`(,_ ,plan ,emitted ,contract)
                (f1-test-compile '(lambda (x) (f1-user (cons (car x) (cdr x))))))
               (operations (plist-get (car (plist-get plan :blocks)) :operations)))
    (should (equal (plist-get plan :gateway-imports) '("nl_native_funcall_v2")))
    (should (= 4 (cl-count-if (lambda (op) (memq (plist-get op :opcode) '(primitive-call funcall))) operations)))
    (should (equal (plist-get contract :imports) '("nl_native_funcall_v2" "nl_root_pin_slot_v2")))
    (should (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract))
    (should (nelisp-bytecode-native-rooted-cfg-contract-f1-p contract))
    (should-not (nelisp-bytecode-native-rooted-cfg-contract-constructor-p contract))
    (should-not (plist-get emitted :additional-source))
    (let ((mutant (copy-tree contract)))
      (plist-put mutant :funcall-hash (make-string 64 ?0))
      (should-not (nelisp-bytecode-native-rooted-cfg-contract-valid-p mutant)))))
(ert-deftest f1/both-emitters-and-generic-argc ()
  (dolist (form '((lambda (f) (funcall f))
                  (lambda (f x) (funcall f x x x x x x))
                  (lambda (f x) (funcall f (if x x nil) x))))
    (dolist (mode '(nil tree))
      (let* ((parts (f1-test-compile form mode)) (contract (nth 3 parts)))
        (should (eq (plist-get (nth 1 parts) :status) 'complete))
        (should (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract))))))
(ert-deftest f1/primitive-is-frozen-and-descriptor-is-copied ()
  (let ((original (nelisp-native-funcall-v2-initializer 'car))
        (digest (nelisp-native-funcall-v2-hash))
        (descriptor (nelisp-native-funcall-v2-descriptor)))
    (cl-letf (((symbol-function 'car) (lambda (_) 'rebound)))
      (should (eq original (nelisp-native-funcall-v2-initializer 'car))))
    (plist-put descriptor :root-limit 5)
    (should (equal digest (nelisp-native-funcall-v2-hash)))
    (should-error (nelisp-native-funcall-v2-initializer 'f1-user))))
(defun f1-test-provider ()
  (let (provider)
    (cl-labels ((walk (node)
                  (when (consp node)
                    (if (and (eq (car node) 'defun) (eq (cadr node) 'nl_native_funcall_v2))
                        (setq provider node)
                      (walk (car node)) (walk (cdr node))))))
      (with-temp-buffer
        (insert-file-contents (expand-file-name "scripts/nelisp-standalone-build.el" f1-test-root))
        (goto-char (point-min))
        (condition-case nil (while t (walk (read (current-buffer)))) (end-of-file nil))))
    (should provider)
    (cl-labels ((host-form (node)
                  (cond ((and (consp node) (eq (car node) 'data-addr))
                         (list 'data-addr (list 'quote (cadr node))))
                        ((consp node) (cons (host-form (car node)) (host-form (cdr node))))
                        (t node))))
      (eval (host-form provider) t))))
(defun f1-test-provider-run (function arguments &optional request lose-owner)
  (let ((roots (make-hash-table)) (count 20) (calls 0) (live t)
        (stash 0) (words (make-hash-table)))
    (puthash (+ 4096 32) function roots)
    (cl-loop for argument in arguments for index from 2 do (puthash (+ 4096 (* index 32)) argument roots))
    (cl-letf (((symbol-function 'data-addr) (lambda (name) (pcase name ('nl_arena_base 8192) (_ 16384))))
              ((symbol-function 'atomic-fetch-add) (lambda (&rest _) (+ 4096 (* count 32))))
              ((symbol-function 'nl_root_pin_slot_v2)
               (lambda (env ticket index) (if (and live (= env 1) (= ticket 7) (<= 0 index) (< index count)) (+ 4096 (* index 32)) 0)))
              ((symbol-function 'wf_write_nil) (lambda (slot) (puthash slot nil roots)))
              ((symbol-function 'wf_write_int) (lambda (slot value) (puthash slot value roots)))
              ((symbol-function 'wf_bytecode_copy) (lambda (to from) (puthash to (gethash from roots) roots)))
              ((symbol-function 'ptr-read-u64)
               (lambda (address offset)
                 (if (and (= address 8192) (= offset 0)) 8192
                   (if (= offset 16) stash (gethash offset words 0)))))
              ((symbol-function 'ptr-write-u64) (lambda (_ offset value) (when (= offset 16) (setq stash value))))
              ((symbol-function 'seq) (lambda (&rest values) (car (last values))))
              ((symbol-function 'wf_bytecode_call_gateway)
               (lambda (_ function marker first argc out)
                 (setq calls (1+ calls))
                 (condition-case err
                     (progn (puthash out (apply (gethash function roots)
                                              (cl-loop for i below argc collect (gethash (+ marker (* (+ first i) 32)) roots))) roots)
                            (when lose-owner (setq live nil)) 0)
                   (error (setq stash 1) (puthash (+ 8192 24) (car err) roots)
                          (puthash (+ 8192 56) (cdr err) roots) 1)))))
      (f1-test-provider)
      (let ((rc (apply #'nl_native_funcall_v2 (or request (list 1 7 1 2 (length arguments) 12)))))
        (list rc calls (gethash (+ 4096 (* 12 32)) roots)
              (gethash (+ 4096 (* 13 32)) roots)
              (gethash (+ 4096 (* 14 32)) roots) stash)))))
(ert-deftest f1/provider-zero-six-lambda-and-closure ()
  (should (equal (cl-subseq (f1-test-provider-run (lambda () 'zero) nil) 0 3) '(0 1 zero)))
  (let ((state (list 'mutable)))
    (should (eq (nth 2 (f1-test-provider-run (lambda (&rest _) state) '(1 2 3 4 5 6))) state)))
  (should (equal (cl-subseq (f1-test-provider-run #'+ '(1 2 3 4 5 6)) 0 3) '(0 1 21))))
(ert-deftest f1/provider-redefinition-and-exit-publication ()
  (fset 'f1-test-user (lambda (x) x))
  (should (= (nth 2 (f1-test-provider-run 'f1-test-user '(17))) 17))
  (fset 'f1-test-user (lambda (_) 'new))
  (should (eq (nth 2 (f1-test-provider-run 'f1-test-user '(17))) 'new))
  (let ((result (f1-test-provider-run (lambda () (signal 'wrong-type-argument '(listp 17))) nil)))
    (should (= (nth 0 result) 1037)) (should (= (nth 3 result) 1))
    (should (eq (nth 4 result) 'wrong-type-argument)) (should (= (nth 5 result) 0))))
(ert-deftest f1/provider-malformed-ticket-bounds-overlap-and-ownership ()
  (dolist (request '((1 8 1 2 1 12) (1 7 0 2 1 12) (1 7 1 0 1 12)
                     (1 7 1 2 -1 12) (1 7 1 2 256 12) (1 7 1 2 19 12)
                     (1 7 1 2 1 17) (1 7 12 2 1 12) (1 7 1 1 1 12)
                     (1 7 1 11 2 12)))
    (should (equal (cl-subseq (f1-test-provider-run #'identity '(3) request) 0 2) '(2 0))))
  (should (= 2 (car (f1-test-provider-run #'identity '(3) nil t)))))
(ert-deftest f1/safe-contract-reconstructs-call-layout ()
  (let* ((input (nelisp-bytecode-compiler-input-build
                 (byte-compile '(lambda (x) (f1-user (cons (car x) (cdr x)))))))
         (plan (nelisp-bytecode-native-rooted-cfg-plan input 'safe-primitives-v3))
         (emitted (nelisp-bytecode-native-rooted-cfg-emit plan nelisp-bytecode-native-rooted-cfg-safe-contract-entry))
         (contract (nelisp-bytecode-native-rooted-cfg-safe-contract-create input plan emitted)))
    (should (equal (plist-get contract :version) nelisp-bytecode-native-rooted-cfg-safe-contract-f1-version))
    (should (nelisp-bytecode-native-rooted-cfg-safe-contract-valid-p contract))
    (should (nelisp-bytecode-native-rooted-cfg-contract-f1-p contract))
    (let ((mutant (copy-tree contract)))
      (plist-put mutant :exit-root-base 1)
      (should-not (nelisp-bytecode-native-rooted-cfg-safe-contract-valid-p mutant)))))
(ert-deftest f1/dynamic-elf-preserves-loads-and-defines-proof-symbols ()
  (require 'nelisp-static-linker)
  (let* ((unit (nelisp-link-unit-make
                "f1-proof" (list (cons 'text (unibyte-string #xc3)) (cons 'bss 16))
                (list (nelisp-link-symbol "_start" 0 :section 'text :type 'func :bind 'global :size 1)
                      (nelisp-link-symbol "f1-bss" 0 :section 'bss :type 'object :bind 'global)) nil))
         (path (make-temp-file "f1-elf-")))
    (unwind-protect
        (progn
          (nelisp-link-units-dynamic path (list unit) nil)
          (let ((record (nelisp-elf-read-symbol path "_start")))
            (should (equal (plist-get record :section-name) ".text"))
            (should (= (plist-get record :value)
                       (plist-get (nelisp-elf--dynamic-layout 1 nil nil 0 0 16) :text-vaddr))))
          (let* ((bytes (nelisp-elf-read-file-bytes path))
                 (record (nelisp-elf-read-symbol path "_start"))
                 (plain (nelisp-elf-build-dynamic-binary
                         (list :text (unibyte-string #xc3) :bss-size 16))))
            (should (= (aref bytes (plist-get record :section-offset)) #xc3))
            (should (equal (substring bytes 64 (length plain)) (substring plain 64))))
          (should (equal (plist-get (nelisp-elf-read-symbol path "f1-bss") :section-name) ".bss")))
      (delete-file path))))
(provide 'nelisp-native-funcall-v2-test)
