;;; nelisp-native-cleanup-u7b-test.el --- Cleanup frame admission -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'ert)
(require 'nelisp-bytecode-native-rooted-cfg-contract)
(require 'nelisp-native-frame-v2)
(load "support/native-cleanup-u7b-fixtures.el" nil t t)
(ert-deftest u7b/five-opcodes-use-shared-frame-bridge ()
  (dolist (kind '(97 114 138 140 ordered forms implicit))
    (let* ((input (nelisp-bytecode-compiler-input-build (native-cleanup-u7b-function kind)))
           (plan (nelisp-bytecode-native-rooted-cfg-plan input))
           (emitted (nelisp-bytecode-native-rooted-cfg-shared-emit-build
                     plan nelisp-bytecode-native-rooted-cfg-contract-shared-entry)))
      (should (eq (plist-get plan :status) 'complete))
      (should (eq (plist-get emitted :status) 'complete))
      (should (member "nl_native_frame_v2" (plist-get emitted :gateway-imports)))
      (should (nelisp-bytecode-native-rooted-cfg-contract-valid-p
               (nelisp-bytecode-native-rooted-cfg-contract-create-shared-v2 input plan emitted))))))
(ert-deftest u7b/gnu-ordered-gc-and-replacement-oracles ()
  (let ((fn (native-cleanup-u7b-function 'ordered)))
    (let ((result (native-cleanup-u7b-observe fn 'ordered nil)))
      (should (equal (nth 1 result) '((body inside) (two inside) (one outside))))
      (should (nth 5 result)))
    (dolist (mode '(cleanup-error cleanup-throw last-error last-throw))
      (let ((result (native-cleanup-u7b-observe fn 'ordered mode)))
        (should (equal (nth 1 result) '((body inside) (two inside) (one outside))))
        (should (equal (car result)
                       (pcase mode ('cleanup-error '(signal (error "cleanup")))
                         ('cleanup-throw 'cleanup) ('last-error '(signal (error "last cleanup")))
                         ('last-throw 'last))))))))
(ert-deftest u7b/gnu-markers-restriction-and-killed-buffer ()
  (dolist (kind '(97 114 138 140))
    (let* ((fn (native-cleanup-u7b-function kind))
           (result (native-cleanup-u7b-observe fn kind nil)))
      (should (nth 5 result))
      (should (eq (nth 3 result) (if (= kind 140) 'other 'original)))
      (should (equal (nth 4 result)
                     (pcase kind (138 '(6 1 13)) (140 '(5 5 9)) (_ '(4 1 11))))))
    (when (memq kind '(97 114))
      (let ((result (native-cleanup-u7b-observe (native-cleanup-u7b-function kind) kind 'kill)))
        (should (eq (nth 3 result) 'other)) (should-not (nth 4 result))))))
(ert-deftest u7b/underflow-remains-refused ()
  (should-not (eq (plist-get (nelisp-bytecode-native-rooted-cfg-plan
                            (nelisp-bytecode-compiler-input-build
                             (make-byte-code 0 (unibyte-string 114 42 192 135) [nil] 1))) :status)
                  'complete)))
(ert-deftest u7b/forms-payload-is-evaluated ()
  (should (equal (nth 1 (native-cleanup-u7b-observe
                        (native-cleanup-u7b-function 'forms) 'forms nil))
                 '((body outside) (one outside)))))
(ert-deftest u7b/identity-and-policy-share-one-frozen-source ()
  (let ((hash (copy-sequence (nelisp-native-frame-v2-hash)))
        (provider (nelisp-native-frame-v2-initializer)))
    (let ((copy (nelisp-native-frame-v2-hash)))
      (aset copy 0 (if (= (aref copy 0) ?0) ?1 ?0))
      (should (equal hash (nelisp-native-frame-v2-hash))))
    (cl-letf (((symbol-function 'nelisp-native-frame-v2-source)
               (lambda () (error "mutable public policy query")))
              ((symbol-function 'nelisp-bytecode-cleanup-source)
               (lambda () (error "mutable public cleanup query"))))
      (should (equal hash (nelisp-native-frame-v2-hash)))
      (should (eq provider (nelisp-native-frame-v2-initializer))))))
