;;; nelisp-native-compiler-constructor-loader-test.el --- Fail-closed startup gates -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'nelisp-native-compiler-runtime-capability)
(require 'nelisp-native-load)

(ert-deftest nelisp-native-compiler-constructor-loader-absent-startup-refused ()
  (should-error (nelisp-native-load-compiler-capability-bind))
  (should-not (nelisp-native-load--compiler-constructor-runtime-p nil))
  (should-not (nelisp-native-load--compiler-constructor-runtime-p
               '(:native-rooted-cfg-contract-version "forged"))))

(ert-deftest nelisp-native-compiler-constructor-loader-counterfeit-bind-refused ()
  (cl-letf (((symbol-function 'nelisp-native-compiler-runtime-capability-p)
             (lambda (&rest _) t))
            ((symbol-function 'nelisp-bytecode-native-rooted-cfg-contract-constructor-p)
             (lambda (&rest _) t)))
    (dotimes (_ 2)
      (let ((condition (should-error (nelisp-native-load-compiler-capability-bind))))
        (should (string-match-p "no runtime authority"
                                (error-message-string condition)))))
    (should-not (nelisp-native-load--compiler-constructor-runtime-p
                 '(:native-rooted-cfg-contract-version "forged")))))

(ert-deftest nelisp-native-compiler-constructor-loader-triple-counterfeit-refused ()
  (cl-letf (((symbol-function 'nelisp-native-compiler-runtime-capability-p)
             (lambda (&rest _) t))
            ((symbol-function 'nelisp-native-compiler-runtime-capability-owner-p)
             (lambda (&rest _) t))
            ((symbol-function 'nelisp-bytecode-native-rooted-cfg-contract-constructor-p)
             (lambda (&rest _) t)))
    (dotimes (_ 2)
      (let ((condition (should-error (nelisp-native-load-compiler-capability-bind))))
        (should (string-match-p "no runtime authority" (error-message-string condition)))))
    (should-not (nelisp-native-load-compiler-constructor-contract-p nil))
    (should-not (nelisp-native-load--compiler-constructor-runtime-p
                 '(:native-rooted-cfg-contract-version "forged")))))

(ert-deftest nelisp-native-compiler-constructor-loader-core-owners-preserved ()
  (let ((layout (symbol-function 'nelisp-native-load-rooted-production-contract))
        (hash (symbol-function 'nelisp-native-load-running-binary-sha256))
        (sha-context (symbol-function 'nelisp-native-load-sha256-dependency-context)))
    (load (symbol-file 'nelisp-native-load-compiler-constructor-contract-p 'defun) nil t t)
    (should (eq layout (symbol-function 'nelisp-native-load-rooted-production-contract)))
    (should (eq hash (symbol-function 'nelisp-native-load-running-binary-sha256)))
    (should (eq sha-context (symbol-function 'nelisp-native-load-sha256-dependency-context)))))

(ert-deftest nelisp-native-compiler-constructor-loader-private-inspector-pinned ()
  (cl-letf (((symbol-function 'nelisp-runtime-reload-contract-matches-p)
             (lambda () nil))
            ((symbol-function 'nelisp-native-load--compiler-constructor-runtime-p)
             (lambda (&rest _) t))
            ((symbol-function 'nelisp-native-load--raw-supported-p)
             (lambda () t))
            ((symbol-function 'nelisp--native-env) (lambda () 4096))
            ((symbol-function 'nelisp--native-pin-copy-v2)
             (lambda (&rest _) (ert-fail "Forged capability reached native copy"))))
    (should-error (nelisp-native-load-root-v2-addresses))
    (should-error (nelisp-native-load-root-v2-copy 4096 1 1 'value))))

(ert-deftest nelisp-native-compiler-constructor-loader-old-runtime-path-preserved ()
  (cl-letf (((symbol-function 'nelisp-runtime-reload-contract-matches-p)
             (lambda () t))
            ((symbol-function 'nelisp-native-load--raw-supported-p) (lambda () t))
            ((symbol-function 'nelisp--native-env) (lambda () 4096))
            ((symbol-function 'nelisp-native-load--symbol-addr) (lambda (_) 8192))
            ((symbol-function 'nelisp--native-pin-copy-v2) (lambda (&rest _) 12288)))
    (let ((addresses (nelisp-native-load-root-v2-addresses)))
      (should (= (plist-get addresses :environment) 4096))
      (dolist (key '(:begin :reserve :end :slot))
        (should (= (plist-get addresses key) 8192))))
    (should (= (nelisp-native-load-root-v2-copy 4096 1 1 'value) 12288))))
