;;; nelisp-native-unit-development-test.el --- native REPL rebuild contracts -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'nelisp-native-unit-development)

(ert-deftest nelisp-native-unit-development/failed-or-changed-source-never-stages ()
  (dolist (mode '(compiler-error source-edit))
    (let ((source (make-temp-file "native-unit-source-" nil ".el"))
          (stages 0))
      (unwind-protect
          (progn
            (with-temp-file source (insert "(defun score (x) (+ x 1))\n"))
            (cl-letf (((symbol-function 'nelisp-native-load--running-binary-sha256)
                       (lambda () (make-string 64 ?a)))
                      ((symbol-function 'call-process)
                       (lambda (&rest _)
                         (if (eq mode 'compiler-error) 1
                           (with-temp-file source (insert "(defun score (x) (+ x 2))\n"))
                           0)))
                      ((symbol-function 'nelisp-native-unit-stage)
                       (lambda (&rest _) (setq stages (1+ stages)))))
              (let ((result (nelisp-native-unit-rebuild-and-reload source)))
                (should (eq 'rejected (plist-get result :status)))
                (should (= 0 stages)))))
        (delete-file source)))))

(ert-deftest nelisp-native-unit-development/publishes-only-explicit-stage-candidate ()
  (let ((source (make-temp-file "native-unit-source-" nil ".el"))
        (published nil) (staged-unit nil))
    (unwind-protect
        (progn
          (with-temp-file source (insert "(defun score (x) (+ x 1))\n"))
          (cl-letf (((symbol-function 'nelisp-native-load--running-binary-sha256)
                     (lambda () (make-string 64 ?a)))
                    ((symbol-function 'call-process) (lambda (&rest _) 0))
                    ((symbol-function 'nelisp-native-unit-stage)
                     (lambda (_path unit _exports)
                       (setq staged-unit unit)
                       '(:status staged :candidate-id "candidate")))
                    ((symbol-function 'nelisp-native-unit-publish)
                     (lambda (candidate)
                       (setq published candidate)
                       '(:status published :unit-id "unit" :generation 2))))
            (let ((result (nelisp-native-unit-rebuild-and-reload source "unit")))
              (should (eq 'published (plist-get result :status)))
              (should (equal staged-unit "unit"))
              (should (equal published "candidate"))
              (should (equal (plist-get result :source-sha256)
                             (secure-hash 'sha256 "(defun score (x) (+ x 1))\n"))))))
      (delete-file source))))

(ert-deftest nelisp-native-unit-development/source-edited-during-stage-revokes-candidate ()
  (let ((source (make-temp-file "native-unit-source-" nil ".el"))
        discarded published)
    (unwind-protect
        (progn
          (with-temp-file source (insert "(defun score (x) (+ x 1))\n"))
          (cl-letf (((symbol-function 'nelisp-native-load--running-binary-sha256)
                     (lambda () (make-string 64 ?a)))
                    ((symbol-function 'call-process) (lambda (&rest _) 0))
                    ((symbol-function 'nelisp-native-unit-stage)
                     (lambda (&rest _)
                       (with-temp-file source (insert "(defun score (x) (+ x 2))\n"))
                       '(:status staged :candidate-id "candidate")))
                    ((symbol-function 'nelisp-native-unit-discard)
                     (lambda (id) (setq discarded id)))
                    ((symbol-function 'nelisp-native-unit-publish)
                     (lambda (&rest _) (setq published t))))
            (let ((result (nelisp-native-unit-rebuild-and-reload source "unit")))
              (should (eq (plist-get result :status) 'rejected))
              (should (eq (plist-get result :phase) :publish))
              (should (equal discarded "candidate"))
              (should-not published))))
      (delete-file source))))

(provide 'nelisp-native-unit-development-test)
