(defun p35-vm-frame0 (f) (funcall f))
(defun p35-vm-frame1 (f a) (funcall f a))
(defun p35-vm-frame2 (f a b) (funcall f a b))
(defun p35-vm-frame3 (f a b c) (funcall f a b c))
(defun p35-vm-frame6 (f a b c d e g) (funcall f a b c d e g))
(defun p35-vm-frame-fixed0 () 'zero)
(defun p35-vm-frame-fixed1 (a) a)
(defun p35-vm-frame-fixed2 (a b) (list a b))
(defun p35-vm-frame-optional (a &optional b c) (list a b c))
(defun p35-vm-frame-rest (a &optional b &rest c) (list a b c))
(defun p35-vm-frame-allrest (&rest a) a)
(defun p35-vm-frame-gc (a b) (garbage-collect) (list a b))
(defun p35-vm-frame-error (a &optional b &rest c) (unwind-protect (error "inner-error") (setq p35-vm-frame-cleanup (list a b c)) (garbage-collect)))
(defun p35-vm-frame-loop (f n a b) (let ((i 0) (v nil)) (while (< i n) (setq v (funcall f a b) i (1+ i))) v))
(defun p35-vm-frame-dynamic (p35-vm-frame-x &optional p35-vm-frame-y &rest p35-vm-frame-r) (garbage-collect) (list p35-vm-frame-x p35-vm-frame-y p35-vm-frame-r))
