;;; nelisp-native-handlers-u8-test.el --- U8 handler contracts -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'ert)
(require 'bytecomp)
(require 'nelisp-bytecode-handlers-u8)
(require 'nelisp-bytecode-native-rooted-cfg-plan)
(require 'nelisp-bytecode-native-rooted-cfg-contract)

(defun u8-compile (form)
  "Compile FORM using GNU's lexical operand cells."
  (let ((byte-compile-warnings nil))
    (with-temp-buffer
      (setq-local lexical-binding t)
      (byte-compile form))))

(defun u8-frame (function &optional depth)
  "Analyze FUNCTION at argument stack DEPTH."
  (nelisp-bytecode-handlers-u8-build (aref function 1) (aref function 2) depth))

(defun u8-stackset-function ()
  "Literal GNU fixture: mutate a saved cell before throwing through a call."
  (make-byte-code 0 (unibyte-string 192 193 50 13 0 194 178 1 195 32 136 48 135 66 135)
                  (vector 'old 'u8-tag 'changed (lambda () (throw 'u8-tag 'caught))) 2))

(ert-deftest u8/ir-stackset-exceptional-phis-read-bank ()
  (let* ((frame (u8-frame (u8-stackset-function)))
         (phis (plist-get frame :exceptional-phis))
         (block (cl-find 6 (plist-get frame :blocks) :key (lambda (b) (plist-get b :start)))))
    (should (eq (plist-get frame :status) 'complete))
    (should (= (plist-get (plist-get frame :operand-bank) :count) 2))
    (should (equal (plist-get (aref (plist-get block :instructions) 0) :bank-writes)
                   '((:slot 0 :source (:value 6 0)))))
    (should (= (length phis) 2))
    (should (cl-some (lambda (phi)
                      (and (= (plist-get phi :block) 13) (= (plist-get phi :slot) 0)
                           (cl-every (lambda (incoming) (equal (plist-get incoming :source) '(:bank 0)))
                                     (append (plist-get phi :incoming) nil))))
                    (append phis nil)))
    ;; The callback's normal output is a write on the normal edge only.
    (let ((call (cl-find 9 (plist-get frame :blocks) :key (lambda (b) (plist-get b :start)))))
      (should (equal (plist-get (aref (plist-get call :instructions) 0) :bank-writes)
                     '((:slot 1 :source (:value 9 0)))))
      (should (equal (plist-get (aref (plist-get call :exceptional-successors) 0) :slots)
                     [(:bank 0) (:caught 9 2)])))))

(ert-deftest u8/ir-loop-handler-state-reaches-fixed-point ()
  (let* ((fn (u8-compile '(lambda (n)
                           (while (> n 0)
                             (catch 'u8-tag (setq n (1- n)) (funcall 'u8-step n)))
                           n)))
         (frame (u8-frame fn 1)))
    (should (eq (plist-get frame :status) 'complete))
    (should (= (plist-get frame :max-handler-depth) 1))
    (should (< (plist-get frame :analysis-states) 100))
    (should (cl-some (lambda (edge) (< (plist-get edge :target) (plist-get edge :from-pc)))
                    (append (plist-get frame :edges) nil)))
    (should (> (length (plist-get frame :exceptional-phis)) 0))))

(ert-deftest u8/ir-nested-types-and-unwind-watermarks ()
  (let* ((fn (u8-compile '(lambda ()
                           (catch 'u8-outer
                             (condition-case nil
                                 (unwind-protect (funcall 'u8-step) (funcall 'u8-cleanup))
                               (error (funcall 'u8-handler)))))))
         (frame (u8-frame fn))
         (pushes (append (plist-get frame :pushes) nil)))
    (should (eq (plist-get frame :status) 'complete))
    (should (= (plist-get frame :max-handler-depth) 2))
    (should (memq 'catch (mapcar (lambda (h) (plist-get h :kind)) pushes)))
    (should (memq 'condition (mapcar (lambda (h) (plist-get h :kind)) pushes)))
    (should (> (plist-get frame :max-binding-depth) 0))
    (dolist (edge (append (plist-get frame :edges) nil))
      (when (eq (plist-get edge :kind) 'exceptional)
        (let ((selected (plist-get edge :handler)))
          (should-not (member selected (plist-get edge :handler-state)))
          (should (equal (plist-get edge :unwind-state) (plist-get selected :unwind-state))))))))

(ert-deftest u8/ir-loop-poll-can-land-in-local-quit-handler ()
  (let* ((fn (u8-compile '(lambda () (condition-case nil (while t) (quit 'caught)))))
         (frame (u8-frame fn))
         (push (aref (plist-get frame :pushes) 0))
         (landing (plist-get push :target)))
    (should (eq (plist-get frame :status) 'complete))
    (should (cl-find landing (plist-get frame :blocks) :key (lambda (b) (plist-get b :start))))
    (should (> (length (plist-get frame :exceptional-phis)) 0))
    (should (cl-some (lambda (edge)
                      (and (eq (plist-get edge :kind) 'exceptional)
                           (= (plist-get edge :from-pc) 4)
                           (= (plist-get edge :target) landing)))
                    (append (plist-get frame :edges) nil)))))

(ert-deftest u8/ir-normal-and-exceptional-predecessors-share-phi ()
  (let* ((fn (u8-compile '(lambda () (catch 'u8-tag (funcall 'u8-step)))))
         (frame (u8-frame fn)))
    (should (eq (plist-get frame :status) 'complete))
    (should (cl-some
             (lambda (phi)
               (let ((kinds (mapcar (lambda (e) (plist-get e :kind))
                                    (append (plist-get phi :incoming) nil))))
                 (and (memq 'exceptional kinds) (memq 'fallthrough kinds))))
             (append (plist-get frame :exceptional-phis) nil)))))

(ert-deftest u8/ir-forward-feedback-edge-has-poll-predecessor ()
  ;; Entry jumps to 13; DFS follows 13->7->10->13. Feedback 10->13
  ;; points forward in the byte stream, so a PC comparison is insufficient.
  (let ((frame (nelisp-bytecode-handlers-u8-build
                (unibyte-string 192 49 16 0 130 13 0 130 10 0 130 13 0 130 7 0 193 135)
                [(quit) caught])))
    (should (eq (plist-get frame :status) 'complete))
    (should (cl-some (lambda (edge)
                      (and (= (plist-get edge :from-pc) 10)
                           (= (plist-get edge :target) 16)
                           (eq (plist-get edge :kind) 'exceptional)))
                    (append (plist-get frame :edges) nil)))))

(ert-deftest u8/ir-path-dependent-finite-unwind-states ()
  ;; A branch-dependent cleanup chain is legal and remains runtime state.
  (let* ((fn (make-byte-code 0
                            (unibyte-string 192 131 8 0 193 142 130 8 0 194 135)
                            [t (lambda () nil) result] 1))
         ;; Correct the target to the common constant instruction.
         (code (copy-sequence (aref fn 1))))
    (aset code 2 9) (aset code 7 9)
    (let* ((frame (nelisp-bytecode-handlers-u8-build code (aref fn 2)))
           (join (cl-find 9 (plist-get frame :blocks) :key (lambda (b) (plist-get b :start)))))
      (should (eq (plist-get frame :status) 'complete))
      (should (= (length (plist-get join :handler-entry-states)) 2)))))

(ert-deftest u8/ir-malformed-and-admission-controls ()
  (dolist (code (list (unibyte-string 48 192 135)
                     (unibyte-string 192 50 2 0 48 135)
                     (unibyte-string 49 3 0 135)))
    (should (eq (plist-get (nelisp-bytecode-handlers-u8-build code [tag]) :status) 'malformed)))
  (let ((nelisp-bytecode-handlers-u8-state-limit 16))
    (let ((frame (nelisp-bytecode-handlers-u8-build
                  (unibyte-string 192 50 7 0 130 0 0 135) [tag])))
      (should (eq (plist-get frame :status) 'unsupported))
      (should (string-match-p "admission limit" (plist-get frame :reason)))))
  (should (eq (plist-get (nelisp-bytecode-handlers-u8-build
                         (unibyte-string 192 193 183 194 135) [nil nil nil]) :status)
              'unsupported)))

(ert-deftest u8/ir-native-admission-requires-handler-plan ()
  (let* ((fn (u8-stackset-function)) (frame (u8-frame fn))
         (input (nelisp-bytecode-compiler-input-build
                 (make-byte-code 0 (aref fn 1) [old u8-tag changed u8-callback] 2))))
    (should (eq (plist-get frame :status) 'complete))
    (should (eq (plist-get frame :native-status) 'runtime-op-pending))
    (should (equal (plist-get frame :exit-transport)
                   '(:signal 1 :throw 2 :type-error-base 256 :return-base 512 :exit-base 1024 :root-count 3)))
    (let* ((plan (nelisp-bytecode-native-rooted-cfg-plan input))
           (emit (nelisp-bytecode-native-rooted-cfg-shared-emit-build plan nelisp-bytecode-native-rooted-cfg-contract-shared-entry)))
      (should (eq (plist-get plan :status) 'complete))
      (should (plist-get plan :handler-bank))
      ;; Handler tag/spec roots retain the caller's live constants after loading.
      (should (cl-every (lambda (init) (integerp (plist-get init :constant-index)))
                       (plist-get plan :constant-initializers)))
      (should (eq (plist-get emit :status) 'complete))
      (should (nelisp-bytecode-native-rooted-cfg-contract-valid-p
               (nelisp-bytecode-native-rooted-cfg-contract-create-shared-v2 input plan emit)))))
  ;; A single-pass reconstruction must preserve DAG sharing, copy mutable
  ;; cells/strings, retain opaque owners, and reject active ancestors.
  (let* ((text (copy-sequence "mutable")) (shared (vector text text))
         (owner (lambda () 'owner)) (data (vector shared shared (copy-sequence shared) owner))
         (copy (cl-letf (((symbol-function 'sxhash-eq) (lambda (_) 0)))
                 ;; Every bucket collides; sharing must still use actual eq.
                 (nelisp-bytecode-native-rooted-cfg-contract--snapshot-data data 0))))
    (should (equal data copy))
    (should (eq (aref copy 0) (aref copy 1)))
    (should-not (eq shared (aref copy 0)))
    (should-not (eq (aref copy 0) (aref copy 2)))
    (should (eq owner (aref copy 3)))
    (should (eq (aref (aref copy 0) 0) (aref (aref copy 0) 1)))
    (aset (aref (aref copy 0) 0) 0 ?M)
    (should (equal text "mutable")))
  (let ((cycle (vector nil)))
    (aset cycle 0 cycle)
    (should-error (nelisp-bytecode-native-rooted-cfg-contract--snapshot-data cycle 0)))
  (let ((cycle (list 1)))
    (setcdr cycle cycle)
    (should-error (nelisp-bytecode-native-rooted-cfg-contract--snapshot-data cycle 0)))
  (should (= (length (nelisp-bytecode-native-rooted-cfg-contract--snapshot-data
                     (make-list 4000 1) 0)) 4000)))

(ert-deftest u8/bank-stackset-before-exit-keeps-current-cells ()
  (let* ((bank (nelisp-bytecode-handlers-u8-bank '(old u8-tag) 4))
         (handler (nelisp-bytecode-handlers-u8-bank-register bank 'catch 'u8-tag 13 0)))
    (nelisp-bytecode-handlers-u8-bank-push bank 'changed)
    (nelisp-bytecode-handlers-u8-bank-stack-set bank 1)
    (nelisp-bytecode-handlers-u8-bank-push bank 'callback)
    ;; Failed callback leaves its normal output uncommitted.
    (should (equal (nelisp-bytecode-handlers-u8-bank-land bank handler 'caught '(13))
                   '(:target 13 :stack (changed caught))))
    (should-not (aref bank 2))))

(ert-deftest u8/bank-popped-cells-remain-available-to-landing ()
  (let* ((bank (nelisp-bytecode-handlers-u8-bank '(a b tag) 4))
         (handler (nelisp-bytecode-handlers-u8-bank-register bank 'catch 'tag 42 0)))
    (nelisp-bytecode-handlers-u8-bank-pop bank)
    (nelisp-bytecode-handlers-u8-bank-pop bank)
    (should (equal (nelisp-bytecode-handlers-u8-bank-land bank handler 'caught '(42))
                   '(:target 42 :stack (a b caught))))))

(ert-deftest u8/bank-loop-handler-state-and-gc ()
  (let ((bank (nelisp-bytecode-handlers-u8-bank '(3) 4)) (landings nil))
    (while (> (aref (aref bank 0) 0) 0)
      (nelisp-bytecode-handlers-u8-bank-push bank 'tag)
      (let ((handler (nelisp-bytecode-handlers-u8-bank-register bank 'catch 'tag 7 0)))
        (nelisp-bytecode-handlers-u8-bank-push bank (1- (aref (aref bank 0) 0)))
        (nelisp-bytecode-handlers-u8-bank-stack-set bank 1)
        (garbage-collect)
        (push (plist-get (nelisp-bytecode-handlers-u8-bank-land bank handler 'caught '(7)) :stack) landings)
        (nelisp-bytecode-handlers-u8-bank-pop bank)))
    (should (equal (reverse landings) '((2 caught) (1 caught) (0 caught))))
    (should-not (aref bank 2))))

(ert-deftest u8/bank-invalid-landing-is-atomic-and-nested-crossing ()
  (let* ((bank (nelisp-bytecode-handlers-u8-bank '(cell outer) 5))
         (outer (nelisp-bytecode-handlers-u8-bank-register bank 'catch 'outer 7 0)))
    (nelisp-bytecode-handlers-u8-bank-push bank 'inner)
    (nelisp-bytecode-handlers-u8-bank-register bank 'condition '(error) 8 1)
    (let ((before (prin1-to-string bank)))
      (should-error (nelisp-bytecode-handlers-u8-bank-land bank outer 'caught '(8)))
      (should (equal before (prin1-to-string bank))))
    (should (equal (nelisp-bytecode-handlers-u8-bank-land bank outer 'caught '(7 8))
                   '(:target 7 :stack (cell caught))))
    (should-not (aref bank 2))
    (should-error (nelisp-bytecode-handlers-u8-bank-land bank outer 'twice '(7)))))

(ert-deftest u8/bank-offset-zero-and-large-offset ()
  (let ((bank (nelisp-bytecode-handlers-u8-bank '(a b) 2)))
    (nelisp-bytecode-handlers-u8-bank-stack-set bank 0)
    (should (= (aref bank 1) 1))
    (should (eq (aref (aref bank 0) 0) 'a))
    (should-error (nelisp-bytecode-handlers-u8-bank-stack-set bank 1)))
  (let ((bank (nelisp-bytecode-handlers-u8-bank (append (make-list 256 'old) '(new)) 257)))
    (nelisp-bytecode-handlers-u8-bank-stack-set bank 256)
    (should (= (aref bank 1) 256))
    (should (eq (aref (aref bank 0) 0) 'new))))

(ert-deftest u8/reference-literal-stackset-agrees-with-gnu ()
  (should (equal (funcall (u8-stackset-function)) '(changed . caught))))

(defvar u8-reference-seen nil)
(defun u8-step (n)
  "Record N, collect and throw through the interpreted callback."
  (push n u8-reference-seen)
  (garbage-collect)
  (throw 'u8-tag n))

(ert-deftest u8/reference-loop-callback-and-gc ()
  (let* ((u8-reference-seen nil)
         (fn (u8-compile '(lambda (n)
                           (while (> n 0)
                             (catch 'u8-tag (setq n (1- n)) (funcall 'u8-step n)))
                           n))))
    (should (= (funcall fn 3) 0))
    (should (equal (reverse u8-reference-seen) '(2 1 0)))
    (should (eq (plist-get (u8-frame fn 1) :status) 'complete))))

(ert-deftest u8/reference-nil-tag-and-local-no-catch ()
  (let ((fn (u8-compile '(lambda ()
                          (condition-case e (catch nil (throw nil 'value))
                            (no-catch (car e)))))))
    (should (eq (funcall fn) 'no-catch))
    (should (eq (plist-get (u8-frame fn) :status) 'complete))))

(ert-deftest u8/reference-inherited-and-quit-conditions ()
  (define-error 'u8-child "U8 child" 'arith-error)
  (let ((fn (u8-compile '(lambda (kind)
                          (condition-case e (signal kind '(payload))
                            (arith-error (car e)) (quit (car e)))))))
    (should (eq (funcall fn 'u8-child) 'u8-child))
    (should (eq (funcall fn 'quit) 'quit))
    (should (eq (plist-get (u8-frame fn 1) :status) 'complete))))

(ert-deftest u8/reference-cleanup-rethrow-and-handler-removal ()
  (let ((fn (u8-compile '(lambda ()
                          (catch 'outer
                            (catch 'inner
                              (unwind-protect (throw 'inner 'discarded)
                                (throw 'outer 'replacement))))))))
    (should (eq (funcall fn) 'replacement))
    (should (eq (plist-get (u8-frame fn) :status) 'complete))))

(provide 'nelisp-native-handlers-u8-test)
;;; nelisp-native-handlers-u8-test.el ends here
