;;; arithmetic-provider-test.el --- Source ownership controls -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(load (expand-file-name "../lisp/nelisp-native-arithmetic-v2.el"
                        (file-name-directory load-file-name)) nil t)

(ert-deftest nelisp-arithmetic-provider-independent-source ()
  (let* ((first (nelisp-native-arithmetic-v2-source))
         (second (nelisp-native-arithmetic-v2-source)))
    (should (equal first second))
    (setcar (cdr first) 'mutated)
    (should-not (equal first (nelisp-native-arithmetic-v2-source)))
    (should (equal second (nelisp-native-arithmetic-v2-source)))))

(ert-deftest nelisp-arithmetic-provider-bounds-and-owner-mutation ()
  (let ((cycle (list 'seq)))
    (setcdr cycle cycle)
    (let ((nelisp-native-arithmetic-v2--source cycle))
      (should-error (nelisp-native-arithmetic-v2-source))))
  (let ((nelisp-native-arithmetic-v2--source (make-list 5000 0)))
    (should-error (nelisp-native-arithmetic-v2-source)))
  (let* ((shared (list 1 2))
         (nelisp-native-arithmetic-v2--source (list shared shared)))
    (should (equal (nelisp-native-arithmetic-v2-source) '((1 2) (1 2)))))
  (let ((before (nelisp-native-arithmetic-v2-dependency-context)))
    (cl-letf (((symbol-function 'nelisp-native-arithmetic-v2--snapshot)
               (lambda (value) value)))
      (should-error (nelisp-native-arithmetic-v2-dependency-context)))))

(ert-deftest nelisp-arithmetic-provider-no-runtime-macro-expansion ()
  (let ((before (nelisp-native-arithmetic-v2-source))
        (context (nelisp-native-arithmetic-v2-dependency-context))
        (forbidden (lambda (&rest _) (error "unexpected runtime macro expansion"))))
    (cl-letf (((symbol-function 'cl-labels) (cons 'macro forbidden))
              ((symbol-function 'when) (cons 'macro forbidden))
              ((symbol-function 'unless) (cons 'macro forbidden)))
      (should (equal before (nelisp-native-arithmetic-v2-source))))
    (cl-letf (((symbol-function 'nelisp-native-arithmetic-v2--copy-node)
               (lambda (&rest _) '(mutated))))
      (should-error (nelisp-native-arithmetic-v2-dependency-context)))))

(ert-run-tests-batch-and-exit (or (getenv "NELISP_ARITHMETIC_TEST_SELECTOR") t))
