;;; nelisp-native-switch-u6-test.el --- General Bswitch -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'ert)
(require 'nelisp-bytecode-native-rooted-cfg-contract)
(require 'nelisp-aot-compiler)
(ert-deftest u6/dynamic-table-is-shared-native ()
  (skip-unless (equal emacs-version "31.1"))
  (let* ((fn (make-byte-code 514 (unibyte-string 183 192 135 193 135) [miss hit] 2))
         (input (nelisp-bytecode-compiler-input-build fn))
         (plan (nelisp-bytecode-native-rooted-cfg-plan input)))
    (should (eq (plist-get plan :status) 'complete))
    (should (eq (plist-get (nelisp-bytecode-native-rooted-cfg-shared-emit-build
                           plan nelisp-bytecode-native-rooted-cfg-contract-shared-entry) :status) 'complete))))
(load (expand-file-name "support/native-switch-u6-fixtures.el"
                        (file-name-directory (or load-file-name buffer-file-name))) nil t)
(ert-deftest u6/gnu-oracle-and-shared-artifacts ()
  (skip-unless (equal emacs-version "31.1"))
  (dolist (name '(eq eql equal custom dynamic backedge))
    (let* ((fixture (native-switch-u6-fixture name)) (fn (car fixture))
           (table (cadr fixture)) (keys (nth 2 fixture))
           (input (nelisp-bytecode-compiler-input-build fn))
           (plan (nelisp-bytecode-native-rooted-cfg-plan input))
           (emitted (nelisp-bytecode-native-rooted-cfg-shared-emit-build
                     plan nelisp-bytecode-native-rooted-cfg-contract-shared-entry))
           (contract (nelisp-bytecode-native-rooted-cfg-contract-create-shared-v2 input plan emitted)))
      (should (eq (plist-get plan :status) 'complete))
      (should (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract))
      (should (plist-get (nelisp-aot-compile-to-link-unit (plist-get emitted :form)) :text))
      (should (eq (plist-get (plist-get input :frame-result) :runtime-switch-lowering) 'runtime-gethash))
      (if (eq name 'backedge)
          (progn (setq u6-left 3 u6-effects nil) (should (eq (funcall fn) 'done))
                 (should (equal u6-effects '(0 1 2 3))))
        (cl-labels ((args (key) (if (eq name 'dynamic) (list key table) (list key))))
          (should (eq (apply fn (args (car keys))) 'first))
          (should (eq (apply fn (args (cadr keys))) 'second))
          (should (eq (apply fn (args (nth 2 keys))) 'miss))
          (puthash (car keys) (if (eq name 'dynamic) 5 6) table)
          (should (eq (apply fn (args (car keys))) 'second))
          (puthash (nth 2 keys) (if (eq name 'dynamic) 5 6) table)
          (should (eq (apply fn (args (nth 2 keys))) 'second))
          (remhash (car keys) table)
          (should (eq (apply fn (args (car keys))) 'miss)))))))
(ert-deftest u6/boundary-depth-and-nil-table-refusals ()
  (let ((table (make-hash-table :test 'eq)))
    (dolist (target '(nil bad 1 3 99 -1))
      (puthash 'a target table)
      (should-not (eq (plist-get (nelisp-bytecode-frame-ir-build
                                  (unibyte-string 192 183 193 135 194 135)
                                  (vector table 'miss 'hit) 1) :status) 'complete)))
    (clrhash table)
    (puthash 'a 4 table)
    (should (eq (plist-get (nelisp-bytecode-frame-ir-build
                            (unibyte-string 192 183 193 135 194 135)
                            (vector table 'miss 'hit) 1) :status) 'complete)))
  (should (eq (plist-get (nelisp-bytecode-frame-ir-build (unibyte-string 192 183 135) [nil] 32) :status) 'unsupported)))
(ert-deftest u6/runtime-sentinel-and-frozen-function ()
  (let ((table (make-hash-table :test 'equal))
        (function (nelisp-bytecode-native-switch-function)))
    (should (= (funcall function 'absent table '(0 4)) -1))
    (puthash "a" 0 table)
    (cl-letf (((symbol-function 'gethash) (lambda (&rest _) (error "poisoned"))))
      (should (= (funcall function (copy-sequence "a") table '(0 4)) 0)))
    (dolist (value '(nil t -1 1 99))
      (puthash 'bad value table)
      (should-error (funcall function 'bad table '(0 4)) :type 'error))))
(ert-deftest u6/cache-recipe-does-not-freeze-table ()
  (skip-unless (equal emacs-version "31.1"))
  (let* ((fixture (native-switch-u6-fixture 'eq)) (fn (car fixture)) (table (cadr fixture))
         (recipe (nelisp-bytecode-native-rooted-cfg-contract-input-recipe
                  (nelisp-bytecode-compiler-input-build fn))))
    (puthash 'one 6 table)
    (should (equal recipe (nelisp-bytecode-native-rooted-cfg-contract-input-recipe
                          (nelisp-bytecode-compiler-input-build fn))))
    (should (equal (plist-get recipe :live-hash-constants) '(0)))
    (should (null (aref (plist-get recipe :constants) 0)))))
(ert-deftest u6/audit-valid-switch-proved-diagnostic-stays-pending ()
  (skip-unless (equal emacs-version "31.1"))
  (add-to-list 'load-path (expand-file-name "tools/ai" default-directory))
  (require 'nelisp-bytecode-coverage-audit)
  (let* ((report (nelisp-bytecode-coverage-audit-run)) (row (aref (plist-get report :opcodes) 183)))
    (should (eq (plist-get row :status) 'runtime-op-pending))
    (should (eq (plist-get (plist-get row :valid-fixture) :shared-form-status) 'proved))
    (should-not (plist-get (cdr (assq 'gccjit (plist-get row :backend-execution))) :executed-native))))
(provide 'nelisp-native-switch-u6-test)
(ert-deftest u6/live-contract-reconstruction-does-not-admit-different-code ()
  (skip-unless (equal emacs-version "31.1"))
  (let* ((fixture (native-switch-u6-fixture 'eq)) (fn (car fixture))
         (input (nelisp-bytecode-compiler-input-build fn))
         (plan (nelisp-bytecode-native-rooted-cfg-plan input))
         (emitted (nelisp-bytecode-native-rooted-cfg-shared-emit-build plan nelisp-bytecode-native-rooted-cfg-contract-shared-entry))
         (contract (nelisp-bytecode-native-rooted-cfg-contract-create-shared-v2 input plan emitted)))
    (should (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract :reconstruction input))
    (let ((different (make-byte-code (aref fn 0) (unibyte-string 192 183 194 135 193 135 195 135)
                                     (aref fn 2) (aref fn 3))))
      (should-not (nelisp-bytecode-native-rooted-cfg-contract-valid-p
                   contract :reconstruction (nelisp-bytecode-compiler-input-build different))))
    (let ((forged (copy-tree contract)))
      (setf (plist-get (plist-get forged :input-recipe) :live-hash-constants) '(99))
      (should-not (nelisp-bytecode-native-rooted-cfg-contract-valid-p forged)))))

(ert-deftest u6/residual-stack-and-default-successor-target ()
  (skip-unless (equal emacs-version "31.1"))
  (let* ((table (make-hash-table :test 'equal))
         (fn (make-byte-code 514 (unibyte-string 192 183 135 135) (vector table) 3))
         (payload (list 'rooted)))
    (puthash "one" 3 table)
    (should (eq (funcall fn payload "one") payload))
    (let* ((input (nelisp-bytecode-compiler-input-build fn))
           (plan (nelisp-bytecode-native-rooted-cfg-plan input))
           (targets (cl-find-if (lambda (init) (equal (sort (copy-sequence (plist-get init :value)) #'<) '(2 3)))
                               (cl-remove-if-not (lambda (init) (listp (plist-get init :value)))
                                                 (plist-get plan :immediate-initializers)))))
      (should (eq (plist-get plan :status) 'complete))
      (should targets))
    (puthash "one" 2 table)
    (should (eq (funcall fn payload "one") payload))
    (should (eq (plist-get (nelisp-bytecode-frame-ir-build (aref fn 1) (aref fn 2) 2) :status) 'complete))
    (puthash "one" 0 table)
    (should-not (eq (plist-get (nelisp-bytecode-frame-ir-build (aref fn 1) (aref fn 2) 2) :status) 'complete))))
