;;; arithmetic-gateway-model-test.el --- Executed DSL protocol model -*- lexical-binding: t; -*-
;; This executes the source AST with a host memory/root model, not native code.
(require 'ert)
(require 'cl-lib)
(load (expand-file-name "../lisp/nelisp-native-arithmetic-v2.el"
                        (file-name-directory load-file-name)) nil t)
(defun nelisp-arithmetic-test--lower (form)
  (cond ((atom form) form)
        ((and (getenv "NELISP_ARITHMETIC_LEAK_MUTANT")
              (eq (car form) 'nl_root_pin_end_v2)) 0)
        ((and (getenv "NELISP_ARITHMETIC_SWAP_MUTANT")
              (equal form '(nelisp_cons_construct second nil-slot tail)))
         '(nelisp_cons_construct first nil-slot tail))
        ((and (getenv "NELISP_ARITHMETIC_GUARD_MUTANT")
              (equal form '(= args 0))) nil)
        ((and (getenv "NELISP_ARITHMETIC_PENDING_MUTANT")
              (equal form '(ptr-write-u64 (+ base 16) 0 0))) 0)
        ((eq (car form) 'seq)
         (cons 'progn (mapcar #'nelisp-arithmetic-test--lower (cdr form))))
        ((eq (car form) 'data-addr) 900)
        (t (mapcar #'nelisp-arithmetic-test--lower form))))
(eval (nelisp-arithmetic-test--lower (nelisp-native-arithmetic-v2-direct-source)) t)
(when (getenv "NELISP_ARITHMETIC_COPY_MUTANT")
  (fset 'nl_native_add_v2_copy (lambda (_to _from) 0)))

(ert-deftest nelisp-arithmetic-gateway-executed-source-protocol ()
  (let ((memory (make-hash-table :test 'eql)) (reserved 0) (ended 0)
        (calls 0) (allocations 0) (refuse nil) (exit-kind nil) (exit-tag nil) (exit-value nil))
    (cl-labels ((write-object (address object)
                  (puthash address object memory)
                  (dolist (offset '(8 16 24)) (puthash (+ address offset) 0 memory)))
                (parent (index) (+ 1000 (* index 32)))
                (nested (index) (+ 10000 (* index 32)))
                (fold (args result)
                  (setq calls (1+ calls))
                  (should (= reserved 6))
                  (should (equal (gethash args memory)
                                 (list (gethash (parent 1) memory)
                                       (gethash (parent 2) memory))))
                  (garbage-collect)
                  (if exit-kind
                      (progn (puthash 20016 exit-kind memory)
                             (write-object 20024 exit-tag)
                             (write-object 20056 exit-value))
                    (condition-case err
                        (write-object result (apply #'+ (gethash args memory)))
                      (error (puthash 20016 1 memory)
                             (write-object 20024 (car err))
                             (write-object 20056 (cdr err)))))))
      (puthash 900 20000 memory)
      (cl-letf (((symbol-function 'ptr-read-u64)
                 (lambda (address offset) (gethash (+ address offset) memory 0)))
                ((symbol-function 'ptr-write-u64)
                 (lambda (address offset value) (puthash (+ address offset) value memory)))
                ((symbol-function 'wf_write_int) #'write-object)
                ((symbol-function 'alloc-bytes)
                 (lambda (&rest _) (setq allocations (1+ allocations)) 30000))
                ((symbol-function 'dealloc-bytes)
                 (lambda (address bytes alignment)
                   (should (= address 30000)) (should (= bytes 8))
                   (should (= alignment 1)) (setq allocations (1- allocations))))
                ((symbol-function 'nl_alloc_symbol)
                 (lambda (_name length output)
                   (write-object output (if (= length 7) 'builtin '+))))
                ((symbol-function 'nelisp_cons_construct)
                 (lambda (head tail output)
                   (should (= reserved 6))
                   (write-object output (cons (gethash head memory) (gethash tail memory)))))
                ((symbol-function 'nl_root_pin_slot_v2)
                 (lambda (env ticket index)
                   (if (and (= env 10) (= ticket 20) (< index 12) (> index 0))
                       (parent index) 0)))
                ((symbol-function 'nl_root_pin_begin_v2)
                 (lambda (_env) (setq reserved 0) 21))
                ((symbol-function 'nl_root_pin_reserve_v2)
                 (lambda (_env _ticket)
                   (prog1 (if (or (eq refuse t) (eq refuse reserved)) 0 (nested reserved))
                     (write-object (nested reserved) nil)
                     (setq reserved (1+ reserved)))))
                ((symbol-function 'nl_root_pin_end_v2)
                 (lambda (_env _ticket) (setq ended (1+ ended)) 1))
                ((symbol-function 'wf_bytecode_call_gateway)
                 (lambda (&rest _) (error "indirect gateway forbidden")))
                ((symbol-function 'wf_any_float_arith)
                 (lambda (args)
                   (let ((values (gethash args memory)))
                     (cond ((not (cl-every #'numberp values)) 2)
                           ((cl-some #'floatp values) 1) (t 0)))))
                ((symbol-function 'wf_first_non_number_or_bignum) #'identity)
                ((symbol-function 'wf_sum) (lambda (args _acc out) (fold args out)))
                ((symbol-function 'wf_fsum) (lambda (args _acc out) (fold args out)))
                ((symbol-function 'wf_copy32) #'nl_native_add_v2_copy)
                ((symbol-function 'bf_wrong_type_number_or_marker)
                 (lambda (args) (fold args 0))))
        (dolist (pair (list '(1 2) '(1.25 2) (list most-positive-fixnum 1)
                           (list most-negative-fixnum -1) '("bad" 1)))
          (write-object (parent 1) (car pair))
          (write-object (parent 2) (cadr pair))
          (write-object (parent 3) 'unchanged)
          (let* ((oracle (condition-case err (list 'ok (+ (car pair) (cadr pair)))
                           (error (list 'error err))))
                 (status (nl_native_add_v2 10 20 1 2 3 4)))
            (if (eq (car oracle) 'ok)
                (progn (should (= status 0))
                       (should (equal (gethash (parent 3) memory) (cadr oracle))))
              (should (= status 1))
              (should (eq (gethash (parent 3) memory) 'unchanged))
              ;; KIND is a tagged Sexp::Int, not the unboxed signal number.
              (should (= (gethash (parent 4) memory) 2))
              (should (= (gethash (+ (parent 4) 8) memory) 1))
              (should (equal (cons (gethash (parent 5) memory)
                                  (gethash (parent 6) memory)) (cadr oracle))))
            (should (= (gethash 20016 memory 0) 0))))
        (setq exit-kind 2 exit-tag (make-symbol "tag") exit-value (list 'opaque))
        (should (= (nl_native_add_v2 10 20 1 2 3 4) 1))
        (should (eq (gethash (parent 5) memory) exit-tag))
        (should (eq (gethash (parent 6) memory) exit-value))
        (should (= (gethash 20016 memory) 0))
        (let ((before calls))
          (should (= (nl_native_add_v2 10 99 1 2 3 4) 2))
          (should (= (nl_native_add_v2 10 20 4 2 3 4) 2))
          (setq refuse 4)
          (should (= (nl_native_add_v2 10 20 1 2 3 4) 2))
          (should (= calls before)))
        ;; The unchanged builtin float arm owns one 32-byte scratch allocation.
        ;; The direct adapter itself allocates only the two rooted cons cells.
        (should (= allocations 1))
        (should (= ended 7))))))

(ert-run-tests-batch-and-exit)
