;;; nelisp-n3-unwind-reference.el --- Additional GNU unwind/GC references -*- lexical-binding: t; -*-
(defvar n3unwind-x 1)
(defvar n3unwind-y 2)
(defvar n3unwind-events nil)
(defun n3unwind-watch (s v op _where)
  (push (list s v op (and (boundp s) (symbol-value s))) n3unwind-events))
(defmacro n3unwind-row (name form)
  `(progn (princ ,name) (princ "|") (prin1 (condition-case e ,form (error (list 'ERR (car e))))) (terpri)))
(n3unwind-row "eval-gc-sharing" (let* ((env (list (cons 'n3unwind-lex '(a b)))) (fn (eval '(lambda () (setq n3unwind-lex (cons 'c n3unwind-lex))) env))) (garbage-collect) (setcdr (car env) '(z)) (list (funcall fn) env)))
(n3unwind-row "watch-let-star-init-error" (progn (setq n3unwind-events nil) (add-variable-watcher 'n3unwind-x #'n3unwind-watch) (unwind-protect (list (condition-case e (let* ((n3unwind-x 9) (n3unwind-z (error "initializer"))) nil) (error (car e))) n3unwind-x (reverse n3unwind-events)) (remove-variable-watcher 'n3unwind-x #'n3unwind-watch))))
(n3unwind-row "watch-let-multiple" (progn (setq n3unwind-events nil) (add-variable-watcher 'n3unwind-x #'n3unwind-watch) (add-variable-watcher 'n3unwind-y #'n3unwind-watch) (unwind-protect (list (condition-case e (let ((n3unwind-x 8) (n3unwind-y 7)) (error "body")) (error (car e))) (reverse n3unwind-events)) (remove-variable-watcher 'n3unwind-x #'n3unwind-watch) (remove-variable-watcher 'n3unwind-y #'n3unwind-watch))))
(defun n3unwind-argument-function (n3unwind-x) n3unwind-x)
(n3unwind-row "watch-function-argument" (progn (setq n3unwind-events nil) (add-variable-watcher 'n3unwind-x #'n3unwind-watch) (unwind-protect (list (n3unwind-argument-function 6) (reverse n3unwind-events)) (remove-variable-watcher 'n3unwind-x #'n3unwind-watch))))
(n3unwind-row "watch-declaration" (progn (setq n3unwind-events nil) (add-variable-watcher 'n3unwind-new #'n3unwind-watch) (unwind-protect (progn (defvar n3unwind-new 2) (defconst n3unwind-new 3) (reverse n3unwind-events)) (remove-variable-watcher 'n3unwind-new #'n3unwind-watch))))
(defun n3unwind-gc-watch (s v op _where)
  (garbage-collect)
  (push (list s v op) n3unwind-events))
(n3unwind-row "watch-parallel-gc" (progn (setq n3unwind-events nil) (add-variable-watcher 'n3unwind-x #'n3unwind-gc-watch) (add-variable-watcher 'n3unwind-y #'n3unwind-gc-watch) (unwind-protect (list (let ((n3unwind-x '(a b)) (n3unwind-y '(c d))) (list n3unwind-x n3unwind-y)) (reverse n3unwind-events)) (remove-variable-watcher 'n3unwind-x #'n3unwind-gc-watch) (remove-variable-watcher 'n3unwind-y #'n3unwind-gc-watch))))
(n3unwind-row "watch-initializer-activation" (progn (setq n3unwind-events nil) (unwind-protect (list (let ((n3unwind-x (progn (add-variable-watcher 'n3unwind-x #'n3unwind-watch) 11)) (n3unwind-y 12)) (list n3unwind-x n3unwind-y)) (reverse n3unwind-events)) (remove-variable-watcher 'n3unwind-x #'n3unwind-watch))))
(n3unwind-row "watch-initializer-deactivation" (progn (setq n3unwind-events nil) (add-variable-watcher 'n3unwind-x #'n3unwind-watch) (unwind-protect (list (let ((n3unwind-x '(earlier)) (n3unwind-y (progn (remove-variable-watcher 'n3unwind-x #'n3unwind-watch) '(later)))) (list n3unwind-x n3unwind-y)) (reverse n3unwind-events)) (remove-variable-watcher 'n3unwind-x #'n3unwind-watch))))
(n3unwind-row "watch-collection-error-after-activation" (progn (setq n3unwind-events nil) (unwind-protect (list (condition-case e (let ((n3unwind-x (progn (add-variable-watcher 'n3unwind-x #'n3unwind-watch) '(earlier))) (n3unwind-y (error "initializer"))) nil) (error (car e))) n3unwind-x n3unwind-y (reverse n3unwind-events)) (remove-variable-watcher 'n3unwind-x #'n3unwind-watch))))
(n3unwind-row "watch-unlet-write-error" (let ((f (lambda (s _v op _where) (when (eq op 'unlet) (set s 99) (error "unlet"))))) (setq n3unwind-x 1) (add-variable-watcher 'n3unwind-x f) (unwind-protect (list (condition-case e (let ((n3unwind-x 2)) nil) (error (car e))) n3unwind-x) (remove-variable-watcher 'n3unwind-x f))))
(n3unwind-row "watch-unlet-void-error" (let ((f (lambda (s _v op _where) (when (eq op 'unlet) (makunbound s) (error "unlet"))))) (setq n3unwind-x 1) (add-variable-watcher 'n3unwind-x f) (unwind-protect (list (condition-case e (let ((n3unwind-x 2)) nil) (error (car e))) (boundp 'n3unwind-x)) (remove-variable-watcher 'n3unwind-x f))))
(n3unwind-row "watch-unlet-write-gc-error" (let ((f (lambda (s _v op _where) (when (eq op 'unlet) (set s '(after callback)) (garbage-collect) (error "unlet"))))) (setq n3unwind-x '(before)) (add-variable-watcher 'n3unwind-x f) (unwind-protect (list (condition-case e (let ((n3unwind-x '(during))) nil) (error (car e))) n3unwind-x) (remove-variable-watcher 'n3unwind-x f))))
(princ "N3-UNWIND-DONE\n")
nil
