;;; nelisp-bytecode-native-rooted-stack-call-test.el --- checked stack caller -*- lexical-binding: t; -*-
(require 'ert)
(require 'nelisp-bytecode-native-rooted-stack-call)

(defun nelisp-bytecode-native-rooted-stack-call-test--result ()
  (list :status 'complete :entry-name "nl_native_stack_probe_v1"
        :artifact-path "test-artifact.nelr" :artifact-sha256 "artifact-sha"
        :runtime-binary-sha256 "binary-sha" :gateway-imports '("nl_native_car_v2")
        :argument-count 1 :constants [] :input '(:constants [])
        :plan '(:status complete :initial-roots (1) :constant-roots nil
                :operations ((:operation car :inputs (1) :outputs (1)))
                :final-root 1 :required-root-count 2)))

(ert-deftest nelisp-bytecode-native-rooted-stack-call-accepts-only-attested-gateway-mode ()
  (let* ((names '("nl_native_car_v2" "nl_native_cdr_v2" "nl_native_cons_v2"))
         (descriptors
          (mapcar (lambda (name)
                    (list :name name :kind 'func
                          :abi nelisp-native-load-raw-runtime-abi-v2
                          :index 0 :address-mode 'native-bridgeable-v1))
                  names)))
    (should (equal (nelisp-bytecode-native-rooted-stack-call--manifest-import-names
                    `(:native (:imports ,descriptors)))
                   names))
    (dolist (mode '(resolver call1-typed-v1 unknown))
      (should-error
       (nelisp-bytecode-native-rooted-stack-call--manifest-import-names
        `(:native (:imports ((:name "nl_native_car_v2" :kind func
                              :abi ,nelisp-native-load-raw-runtime-abi-v2
                              :index 0 :address-mode ,mode)))))))))

(ert-deftest nelisp-bytecode-native-rooted-stack-call-public-resolver-is-fixed-and-attested ()
  (let (resolved)
    (cl-letf (((symbol-function 'nelisp-native-load--raw-v2-contract)
               (lambda () '((runtime . 1))))
              ((symbol-function 'nelisp-native-load--raw-supported-p) (lambda () t))
              ((symbol-function 'nelisp-runtime-reload-contract-matches-p) (lambda () t))
              ((symbol-function 'nelisp--native-env) (lambda () 77))
              ((symbol-function 'nelisp-native-load--symbol-addr)
               (lambda (name)
                 (push name resolved)
                 (1+ (length resolved)))) )
      (should (equal (nelisp-native-load-root-v2-addresses)
                     '(:environment 77 :begin 2 :reserve 3 :end 4 :slot 5)))
      (should (equal (nreverse resolved)
                     '("nl_root_pin_begin_v2" "nl_root_pin_reserve_v2"
                       "nl_root_pin_end_v2" "nl_root_pin_slot_v2"))))))

(ert-deftest nelisp-bytecode-native-rooted-stack-call-rejects-unauthenticated-before-map ()
  (let ((maps 0) (result (nelisp-bytecode-native-rooted-stack-call-test--result)))
    (cl-letf (((symbol-function 'nelisp-bytecode-native-rooted-stack-authenticated-result-p)
               (lambda (_) nil))
              ((symbol-function 'nelisp-native-load-raw-v2-artifact)
               (lambda (&rest _) (setq maps (1+ maps)))) )
      (should-error (nelisp-bytecode-native-rooted-stack-call result 'x))
      (should (= maps 0)))))

(ert-deftest nelisp-bytecode-native-rooted-stack-call-refuses-mutated-arity-before-map ()
  (let ((result (nelisp-bytecode-native-rooted-stack-call-test--result))
        (maps 0) (auth-count 0))
    (setf (plist-get result :argument-count) 2)
    (cl-letf (((symbol-function 'nelisp-bytecode-native-rooted-stack-authenticated-result-p)
               (lambda (_) (setq auth-count (1+ auth-count)) t))
              ((symbol-function 'nelisp-native-load-raw-v2-artifact)
               (lambda (&rest _) (setq maps (1+ maps)))) )
      (should-error (nelisp-bytecode-native-rooted-stack-call result 'x))
      (should (= auth-count 0))
      (should (= maps 0)))))

(ert-deftest nelisp-bytecode-native-rooted-stack-call-refuses-final-root-out-of-range ()
  (let ((result (nelisp-bytecode-native-rooted-stack-call-test--result)) (maps 0))
    (setf (plist-get (plist-get result :plan) :final-root) 2)
    (cl-letf (((symbol-function 'nelisp-bytecode-native-rooted-stack-authenticated-result-p)
               (lambda (_) t))
              ((symbol-function 'nelisp-native-load-raw-v2-artifact)
               (lambda (&rest _) (setq maps (1+ maps)))) )
      (should-error (nelisp-bytecode-native-rooted-stack-call result 'x))
      (should (= maps 0)))))

(ert-deftest nelisp-bytecode-native-rooted-stack-call-refuses-bad-operation-root ()
  (let ((result (nelisp-bytecode-native-rooted-stack-call-test--result)) (maps 0))
    (setf (plist-get (plist-get result :plan) :operations)
          '((:operation car :inputs (9) :outputs (1))))
    (cl-letf (((symbol-function 'nelisp-bytecode-native-rooted-stack-authenticated-result-p)
               (lambda (_) t))
              ((symbol-function 'nelisp-native-load-raw-v2-artifact)
               (lambda (&rest _) (setq maps (1+ maps)))) )
      (should-error (nelisp-bytecode-native-rooted-stack-call result 'x))
      (should (= maps 0)))))

(ert-deftest nelisp-bytecode-native-rooted-stack-call-refuses-malformed-import-before-entry ()
  (let ((result (nelisp-bytecode-native-rooted-stack-call-test--result))
        (ptrcalls 0) (maps 0))
    (cl-letf (((symbol-function 'nelisp-bytecode-native-rooted-stack-authenticated-result-p)
               (lambda (_) t))
              ((symbol-function 'nelisp-native-load-running-binary-sha256)
               (lambda () "binary-sha"))
              ((symbol-function 'nelisp-native-load-root-v2-addresses)
               (lambda () '(:environment 50 :begin 11 :reserve 12 :end 13 :slot 14)))
              ((symbol-function 'nelisp-native-load-manifest)
               (lambda (_) '(:native (:imports ((:name "nl_native_unknown_v2" :kind func
                                                   :abi raw-v2 :index 1 :address-mode resolver))))))
              ((symbol-function 'ptr-call) (lambda (&rest _) (setq ptrcalls (1+ ptrcalls))))
              ((symbol-function 'nelisp-native-load-raw-v2-artifact)
               (lambda (&rest _) (setq maps (1+ maps)))) )
      (should-error (nelisp-bytecode-native-rooted-stack-call result 'x))
      (should (= ptrcalls 0))
      (should (= maps 0)))))

(ert-deftest nelisp-bytecode-native-rooted-stack-call-decodes-and-cleans-on-wrong-type ()
  (let* ((result (nelisp-bytecode-native-rooted-stack-call-test--result))
         (mapping (list :kind 'raw-runtime-v2 :entry-name "nl_native_stack_probe_v1"
                        :arity 4 :runtime-abi nelisp-native-load-raw-runtime-abi-v2
                        :raw-abi nelisp-native-load-raw-runtime-abi-v2))
         (nelisp-native-load-raw-mappings nil)
         (slots 0) (end-count 0) (unload-count 0) (unbox-count 0)
         (gc-count 0) (auth-count 0) (copies nil))
    (setf (plist-get result :constants) [42]
          (plist-get result :input) '(:constants [42])
          (plist-get (plist-get result :plan) :constant-roots) '((0 . 2))
          (plist-get (plist-get result :plan) :final-root) 2
          (plist-get (plist-get result :plan) :required-root-count) 3)
    (cl-letf (((symbol-function 'nelisp-bytecode-native-rooted-stack-authenticated-result-p)
               (lambda (_) (setq auth-count (1+ auth-count)) t))
              ((symbol-function 'nelisp-native-load-running-binary-sha256)
               (lambda () "binary-sha"))
              ((symbol-function 'nelisp-native-load-root-v2-addresses)
               (lambda () '(:environment 50 :begin 11 :reserve 12 :end 13 :slot 14)))
              ((symbol-function 'nelisp-native-load-root-v2-copy)
               (lambda (_env _ticket index value)
                 (push (cons index value) copies) (+ 201 index)))
              ((symbol-function 'nelisp-native-load--raw-supported-p) (lambda () t))
              ((symbol-function 'nelisp-runtime-reload-contract-matches-p) (lambda () t))
              ((symbol-function 'nelisp--native-pin-copy-v2)
               (lambda (_env _ticket index value)
                 (push (cons index value) copies) (+ 201 index)))
              ((symbol-function 'garbage-collect)
               (lambda () (setq gc-count (1+ gc-count))))
              ((symbol-function 'nelisp-native-load-manifest)
               (lambda (_) `(:native (:imports
                                      ((:name "nl_native_car_v2" :kind func
                                        :abi ,nelisp-native-load-raw-runtime-abi-v2
                                        :index 0 :address-mode native-bridgeable-v1))))))
              ((symbol-function 'nelisp-native-load-raw-v2-artifact)
               (lambda (&rest _) (setq nelisp-native-load-raw-mappings
                                       (cons mapping nelisp-native-load-raw-mappings))
                 mapping))
              ((symbol-function 'nelisp-native-load-raw-export-address) (lambda (&rest _) 90))
              ((symbol-function 'nelisp-native-load-unload)
               (lambda (_) (setq unload-count (1+ unload-count))))
              ((symbol-function 'nelisp-native-load-box) (lambda (&rest _) t))
              ((symbol-function 'nelisp-native-load-unbox)
               (lambda (&rest _) (setq unbox-count (1+ unbox-count)) :offender))
              ((symbol-function 'ptr-call)
               (lambda (address _env _ticket a _b _c _d)
                 (cond ((= address 11) 7)
                       ((= address 12) (setq slots (1+ slots)) (+ 200 slots))
                       ((= address 14) (+ 201 a))
                       ((= address 13) (setq end-count (1+ end-count)) 1)
                       ((= address 90) 257)
                       (t (error "unexpected ptr-call address"))))))
      (should-error (nelisp-bytecode-native-rooted-stack-call result 'bad)
                    :type 'wrong-type-argument)
      (should (member '(2 . 42) copies))
      (should (= gc-count 1))
      (should (= auth-count 1))
      (should (= unbox-count 1))
      (should (= end-count 1))
      (should (= unload-count 1)))))

(provide 'nelisp-bytecode-native-rooted-stack-call-test)
