(defun p35-vm-read (v i) (aref v i))
(defun p35-vm-write (v i x) (aset v i x))
(defun p35-vm-gc-read (v i callback) (funcall callback) (aref v i))
(defun p35-vm-gc-write (v i x callback) (funcall callback) (aset v i x))
(defun p35-vm-read-loop (v count) (let ((i 0) (value nil)) (while (< i count) (setq value (aref v 0) i (1+ i))) value))
(defun p35-vm-write-loop (v x count) (let ((i 0) (value nil)) (while (< i count) (setq value (aset v 0 x) i (1+ i))) value))
(defun p35-vm-read-epoch (v i address) (let ((before (ptr-read-u64 address 0))) (aref v i) (- (ptr-read-u64 address 0) before)))
(defun p35-vm-write-epoch (v i x address) (let ((before (ptr-read-u64 address 0))) (aset v i x) (- (ptr-read-u64 address 0) before)))
(defun p35-vm-increment (v) (1+ (aref v 0)))
(defun p35-vm-decrement (v) (1- (aref v 0)))
(defun p35-vm-add (v) (+ (aref v 0) (aref v 1)))
(defun p35-vm-multiply (v) (* (aref v 0) (aref v 1)))
(defun p35-vm-subtract (v) (- (aref v 0) (aref v 1)))
(defun p35-vm-num-equal (v) (= (aref v 0) (aref v 1)))
(defun p35-vm-less (v) (< (aref v 0) (aref v 1)))
(defun p35-vm-greater (v) (> (aref v 0) (aref v 1)))
(defun p35-vm-less-equal (v) (<= (aref v 0) (aref v 1)))
(defun p35-vm-greater-equal (v) (>= (aref v 0) (aref v 1)))
