;;; -*- lexical-binding: t; -*-
(require 'cl-lib)
(require 'nelisp-aot-compiler)
(require 'nelisp-standalone-build)
(require 'nelisp-cc-val-load)
(require 'nelisp-cc-sexp-clone-into)
(require 'nelisp-cc-nlvector-slot-ptr)
(require 'nelisp-cc-nlvector-set-slot)
(defun av-def (name forms)
 (or (cl-find-if (lambda (f) (eq (cadr f) name)) forms) (error "Missing %S" name)))
(let* ((variant (or (getenv "AV_VARIANT") "positive"))
       (output (getenv "AV_OUTPUT")) (base #x37000000)
       (slots (+ base 256)) (box (+ base 512)) (data (+ base 1024))
       (boxed (+ base 2048)) (marker (+ base 2112)) (text (+ base 2200))
       (pools (append nelisp-standalone--applyfn-bytecode-helpers nelisp-standalone--applyfn-core-helpers nelisp-standalone--applyfn-bf-helpers))
       (helper (copy-tree (av-def 'wf_bytecode_vector_primitive pools)))
       (decode (copy-tree (av-def 'nl_sci_store_imm (cdr nelisp-cc-sexp-clone-into--source))))
       (cases nil) (checks nil) (count 0))
 (cl-labels ((check (predicate) (push `(if ,predicate 0 (when (= failure 0) (setq failure ,(cl-incf count)))) checks))
             (emit (form) (push form checks))
             (slot (addr tag p8 p16 p24)
                (emit `(ptr-write-u64 ,addr 0 ,tag)) (emit `(ptr-write-u64 ,addr 8 ,p8))
                (emit `(ptr-write-u64 ,addr 16 ,p16)) (emit `(ptr-write-u64 ,addr 24 ,p24)))
             (setup (tag index len word)
                (slot slots tag box 77 99) (slot (+ slots 32) 2 index 0 0)
                (emit `(ptr-write-u64 ,box 16 ,len)) (emit `(ptr-write-u64 ,box 8 ,data))
                (emit `(ptr-write-u64 ,data -8 3))
                (emit `(ptr-write-u64 ,data 8 3))
                (emit `(ptr-write-u64 ,data 0 ,word))
                (emit `(ptr-write-u64 ,base 0 0)) (emit `(ptr-write-u64 ,base 8 0))))
  (pcase variant
   ("bad-bounds" (setq helper (cl-subst t '(and (>= i 0) (< i (vector-len arr))) helper :test #'equal)))
   ("bad-bridge" (setq helper (cl-subst t '(= (bf_nemacs_char_table_vector_p arr) 0) helper :test #'equal)))
   ("bad-shift" (setq decode (cl-subst 'shr 'sar decode)))
   ("bad-copy" (setq helper (cl-subst '(ptr-write-u64 arr 0 (ptr-read-u64 (nl_val_load word arr) 0)) '(wf_bytecode_copy arr (nl_val_load word arr)) helper :test #'equal)))
   ("old-view" (setq helper (cl-subst '(wf_bytecode_copy arr (vector-ref-ptr arr i)) '(wf_bytecode_copy arr (nl_val_load word arr)) helper :test #'equal))))
  (slot boxed 7 (+ base 3000) 123 456)
  (slot marker 4 19 text 19)
  (dotimes (i 19) (emit `(ptr-write-u8 ,text ,i ,(aref "--nemacs-char-table" i))))
  ;; Read every complete output word, then enforce no temporary allocation.
  (dolist (row (append (list (list 3 0 0 0 0) (list 7 1 0 0 0) (list 11 1 0 0 0))
                       (mapcar (lambda (n) (list (+ (* n 4) 1) 2 n 0 0)) (list -2305843009213693952 -2 -1 0 1 2305843009213693951))
                       (list (list boxed 7 (+ base 3000) 123 456))))
   (setup 8 0 1 (car row))
   (check `(= (wf_bytecode_vector_primitive ,slots 2 72) 0))
   (dotimes (i 4) (check `(= (ptr-read-u64 ,slots ,(* i 8)) ,(nth (1+ i) row))))
   (check `(= (ptr-read-u64 ,base 0) 0)))
  ;; Rejections must neither mutate the array/result slot nor the epoch.
  (dolist (row '((8 -1 1 2) (8 1 1 2) (8 0 0 2) (5 0 1 2) (8 0 1 1)))
   (dolist (op '(72 73))
    (setup (nth 0 row) (nth 1 row) (nth 2 row) 3)
    (emit `(ptr-write-u64 ,(+ slots 32) 0 ,(nth 3 row)))
    (slot (+ slots 64) 2 9 0 0)
    (check `(= (wf_bytecode_vector_primitive ,slots ,(if (= op 73) 3 2) ,op) 2))
    (check `(= (ptr-read-u64 ,slots 0) ,(nth 0 row)))
    (check `(= (ptr-read-u64 ,data 0) 3))
    (check `(= (ptr-read-u64 ,base 8) 0))))
  (dolist (op '(72 73))
   (setup 8 0 7 marker) (slot (+ slots 64) 2 9 0 0)
   (check `(= (wf_bytecode_vector_primitive ,slots ,(if (= op 73) 3 2) ,op) 2))
   (check `(= (ptr-read-u64 ,data 0) ,marker))
   (check `(= (ptr-read-u64 ,base 8) 0)))
  ;; Actual vector setter and canonical immediate conversion, not a setter stub.
  (dolist (row '((0 0 3) (1 0 7) (2 -2 -7) (2 2305843009213693951 9223372036854775805)))
   (setup 8 0 1 3) (slot (+ slots 64) (nth 0 row) (nth 1 row) 0 0)
   (check `(= (wf_bytecode_vector_primitive ,slots 3 73) 0))
   (check `(= (ptr-read-u64 ,data 0) ,(nth 2 row)))
   (check `(= (ptr-read-u64 ,slots 0) ,(nth 0 row)))
   (check `(= (ptr-read-u64 ,slots 8) ,(nth 1 row)))
   (check `(= (ptr-read-u64 ,base 8) 1))
   (check `(= (ptr-read-u64 ,base 0) 0)))
  (let ((source `(seq
    ,@(mapcar (lambda (n) (av-def n pools)) '(wf_bytecode_slot wf_bytecode_copy wf_copy32 bf_nemacs_char_table_vector_p))
    (defun wf_dirty () (atomic-fetch-add ,(+ base 8) 1))
    (defun nl_alloc_bytes (size align) (let ((p (ptr-read-u64 ,base 16))) (seq (ptr-write-u64 ,base 16 (+ p size)) (ptr-write-u64 ,base 0 (+ (ptr-read-u64 ,base 0) 1)) (ptr-write-u64 ,base 40 (+ (ptr-read-u64 ,base 40) 1)) p)))
    ;; Unused boxed-write branches link to explicit failure stubs; native cold corpus tests their real GC behavior.
    (defun nl_bind_clone_force_flag () 0) (defun nl_gc_in_arena (p) 0) (defun nl_gc_is_boot (p) 0)
    (defun nl_sexp_clone_into (src dst) (syscall-direct 60 199 0 0 0 0 0))
    ,decode ,@(cdr nelisp-cc-val-load--source) ,@(cdr nelisp-cc-nlvector-slot-ptr--source) ,@(cdr nelisp-cc-nlvector-set-slot--source)
    ,helper
    (defun audit_run () (let ((failure 0)) (seq
       (syscall-direct 9 ,base 16777216 3 50 -1 0)
       (ptr-write-u64 ,base 16 ,(+ base 65536))
       ,@(nreverse checks)
       (ptr-write-u64 ,base 0 (ptr-read-u64 ,base 40))
       (ptr-write-u64 ,base 24 failure)
       (syscall-direct 1 1 ,base 32 0 0 0) failure)))
    (defun _start () (syscall-direct 60 (audit_run) 0 0 0 0 0)))))
   (nelisp-link-units output (list (nelisp-standalone--compile-to-unit "array-audit.o" source)) "_start")
   (with-temp-file (concat output ".source.el") (prin1 source (current-buffer)))
   (princ (format "ARRAY-UNIT-COMPILED variant=%s checks=%d\n" variant count)))))

