;;; nelisp-native-prims-u2c-test.el --- U2c frozen primitive lowering -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'ert)
(require 'nelisp-bytecode-native-rooted-cfg-contract)
(require 'nelisp-bytecode-native-rooted-cfg-constructor-contract)
(require 'nelisp-bytecode-native-rooted-cfg-safe-contract)
(require 'nelisp-native-load)
(load "support/native-prims-u2c-fixtures.el" nil t t)
(ert-deftest u2c/eq-symbols-use-runtime-identity ()
  ;; An interned symbol's offset 8 is not its identity.  Distinct names
  ;; can have the same word there, so the generated form must delegate.
  (let ((calls 0) (writes 0))
    (cl-letf (((symbol-function 'extern-call)
               (lambda (_name _env _ticket index &rest _) (+ 4096 (* 32 index))))
              ((symbol-function 'ptr-read-u64)
               (lambda (_address offset) (if (= offset 0) 4 0)))
              ((symbol-function 'ptr-write-u64)
               (lambda (&rest _) (setq writes (1+ writes))))
              ((symbol-function 'u2c-test-runtime-eq)
               (lambda () (setq calls (1+ calls)) 19)))
      (should (= 19 (eval (nelisp-native-funcall-v2-value-form
                          61 '(1 2) 3 0
                          '(u2c-test-runtime-eq))
                         '((env . 1) (ticket . 7) (nl_root_pin_slot_v2 . slot)))))
      (should (= calls 1))
      (should (= writes 0)))))
(ert-deftest u2c/exact-family-ordered-roots-and-shared-contract ()
  (skip-unless (equal emacs-version "31.1"))
  (dolist (row native-prims-u2c-family)
    (let* ((input (nelisp-bytecode-compiler-input-build (native-prims-u2c-function row)))
           (plan (nelisp-bytecode-native-rooted-cfg-plan input))
           (op (car (plist-get (car (plist-get plan :blocks)) :operations))))
      (should (eq (plist-get input :status) 'complete))
      (should (eq (plist-get plan :status) 'complete))
      (should (eq (plist-get op :opcode) 'primitive-call))
      (should (equal (plist-get op :argument-roots) (number-sequence 1 (nth 2 row))))
      (should (= (plist-get op :argument-count) (nth 2 row)))
      (should (equal (plist-get plan :gateway-imports) '("nl_native_funcall_v2")))
      (let* ((emitted (nelisp-bytecode-native-rooted-cfg-shared-emit-build
                       plan nelisp-bytecode-native-rooted-cfg-contract-shared-entry))
             (contract (nelisp-bytecode-native-rooted-cfg-contract-create-shared-v2 input plan emitted)))
        (should (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract))
        (should (nelisp-bytecode-native-rooted-cfg-contract-f1-p contract))))))
(ert-deftest u2c/frozen-values-and-defensive-family-copy ()
  (dolist (row native-prims-u2c-family)
    (let* ((name (nth 1 row)) (original (nelisp-native-funcall-v2-initializer name))
           (cell (symbol-function name)) (restore (symbol-function 'fset)) actual)
      (unwind-protect
          (progn (funcall restore name (lambda (&rest _) 'poison))
                 (setq actual (nelisp-native-funcall-v2-initializer name)))
        (funcall restore name cell))
      (should (eq actual original))
      (let ((copy (nelisp-native-funcall-v2-primitive (car row))))
        (setcar (cdr copy) 'poison)
        (should (equal (nelisp-native-funcall-v2-primitive (car row)) row))))))
(ert-deftest u2c/underflow-and-unrelated-pending-opcode-refused ()
  (dolist (row native-prims-u2c-family)
    (let ((fn (make-byte-code 0 (unibyte-string (car row) 135) [] 0)))
      (should-not (eq (plist-get (nelisp-bytecode-compiler-input-build fn) :status) 'complete))))
  (should-not (nelisp-native-funcall-v2-primitive 114)))
(ert-deftest u2c/safe-contract-and-exit-layout-reconstruct ()
  (skip-unless (equal emacs-version "31.1"))
  (dolist (row native-prims-u2c-family)
    (let* ((input (nelisp-bytecode-compiler-input-build (native-prims-u2c-function row)))
           (plan (nelisp-bytecode-native-rooted-cfg-plan input 'safe-primitives-v3))
           (emitted (nelisp-bytecode-native-rooted-cfg-emit plan nelisp-bytecode-native-rooted-cfg-safe-contract-entry))
           (contract (nelisp-bytecode-native-rooted-cfg-safe-contract-create input plan emitted)))
      (should (nelisp-bytecode-native-rooted-cfg-safe-contract-valid-p contract))
      (let ((mutant (copy-tree contract)))
        (plist-put mutant :exit-root-base 1)
        (should-not (nelisp-bytecode-native-rooted-cfg-safe-contract-valid-p mutant))))))

(defun u2c-test-lisp-provider (name)
  "Execute the source provider with canonical GNU builtin values."
  (let (binding)
    (with-temp-buffer
      (insert-file-contents (locate-library "nelisp-native-funcall-v2.el" t))
      (goto-char (point-min))
      (condition-case nil
          (while t
            (let ((form (read (current-buffer))))
              (when (and (eq (car-safe form) 'let) (assq name (cadr form)))
                (setq binding (cadr (assq name (cadr form)))))))
        (end-of-file nil)))
    (should binding)
    (cl-labels ((host (form)
                 (cond ((and (eq (car-safe form) 'quote)
                             (eq (car-safe (cadr form)) 'builtin))
                        (list 'quote (symbol-function (cadr (cadr form)))))
                       ((consp form) (cons (host (car form)) (host (cdr form))))
                       (t form))))
      (eval (host binding) t))))
(ert-deftest u2c/source-provider-nconc-error-data-and-dotted-mutation ()
  (let ((provider (u2c-test-lisp-provider 'nconc-provider))
        (vm (native-prims-u2c-function '(164 nconc 2)))
        (actual-cases (native-prims-u2c-cases 164)))
    (dolist (args (native-prims-u2c-cases 164))
      (should (equal (native-prims-u2c-observe vm args)
                     (native-prims-u2c-observe provider (pop actual-cases)))))))

(ert-deftest u2c/safe-list-providers-match-gnu-and-retain-identity ()
  (dolist (row '((car-safe car-safe-provider) (cdr-safe cdr-safe-provider)))
    (let* ((provider (u2c-test-lisp-provider (cadr row)))
           (pair (cons 'a 'b))
           (objects (list pair nil 42 "text" [a b]))
           (expected (mapcar (symbol-function (car row)) objects)))
      (should (equal (mapcar provider objects) expected))
      (should (eq (funcall provider pair) (if (eq (car row) 'car-safe) (car pair) (cdr pair)))))))
(ert-deftest u2c/runtime-initializers-freeze-tokens-and-provider-dependencies ()
  (cl-letf (((symbol-function 'nelisp--eval-source-string) (lambda (&rest _) nil)))
    (dolist (name '(symbolp consp stringp listp eq not 1- 1+ = > < <= >= - + * / numberp integerp))
      (let ((original (symbol-function name)) (restore (symbol-function 'fset)) actual)
        (unwind-protect
            (progn (funcall restore name (lambda (&rest _) 'poison))
                   (setq actual (nelisp-native-funcall-v2-initializer name)))
          (funcall restore name original))
        (should (equal actual (list 'builtin name)))))
    (dolist (name '(max min nconc %))
      (let ((expected (nelisp-native-funcall-v2-initializer name))
            (original (symbol-function name)) (restore (symbol-function 'fset)) actual)
        (unwind-protect
            (progn (funcall restore name (lambda (&rest _) 'poison))
                   (setq actual (nelisp-native-funcall-v2-initializer name)))
          (funcall restore name original))
        (should (eq actual expected))))))
(ert-deftest u2c/cyclic-second-operand-retains-identity ()
  (let ((provider (u2c-test-lisp-provider 'nconc-provider))
        (vm (native-prims-u2c-function '(164 nconc 2))))
    (dolist (empty-first '(nil t))
      (should (equal (native-prims-u2c-observe-cyclic-tail vm empty-first)
                     (native-prims-u2c-observe-cyclic-tail provider empty-first))))))
(provide 'nelisp-native-prims-u2c-test)
