;;; nelisp-reader-uninterned-symbol-smoke.el --- Reader #:-identity smoke -*- lexical-binding: t; -*-

(let* ((name "nelisp-p5-reader-uninterned-probe-9f7a")
       (before (intern-soft name))
       (source (concat "[#" ":" name " #" ":" name "]"))
       (forms (car (read-from-string source)))
       (native-forms (read source))
       (labelled (car (read-from-string "[#1=#:reader-label #1#]")))
       (native-labelled (read "[#1=#:reader-label #1#]"))
       (empty (car (read-from-string "#:")))
       (native-empty (read "#:"))
       (escaped-source (concat "#:foo" (string 92) " bar"))
       (escaped (car (read-from-string escaped-source)))
       (native-escaped (read escaped-source))
       (fallback (car (nelisp--rd-read-one escaped-source 0 (length escaped-source))))
       (marker (copy-sequence "reader-load-marker"))
       (mixed (let ((load-file-name marker))
                (car (read-from-string "[#$ #:reader-mixed]"))))
       (native-mixed (let ((load-file-name marker))
                       (read "[#$ #:reader-mixed]"))))
  (unless (and (null before)
               (not (eq (aref forms 0) (aref forms 1)))
               (not (eq (aref native-forms 0) (aref native-forms 1)))
               (null (intern-soft name))
               (eq (aref labelled 0) (aref labelled 1))
               (eq (aref native-labelled 0) (aref native-labelled 1))
               (equal (symbol-name empty) "")
               (not (eq empty (intern "")))
               (equal (symbol-name native-empty) "")
               (not (eq native-empty (intern "")))
               (equal (symbol-name escaped) "foo bar")
               (equal (symbol-name native-escaped) "foo bar")
               (equal (symbol-name fallback) "foo bar")
               (eq (aref mixed 0) marker)
               (eq (aref native-mixed 0) marker)
               (not (eq (aref mixed 1) (intern "reader-mixed"))))
    (error "reader uninterned-symbol identity mismatch"))
  (princ "READER-UNINTERNED-SYMBOL-SMOKE:PASS\n"))

;;; nelisp-reader-uninterned-symbol-smoke.el ends here
