;;; nelisp-native-optimization-guard-v1-test.el --- Executed DSL guard model -*- lexical-binding: t; -*-
;; The model executes the returned DSL; it is not a native ABI certificate.
(require 'ert)
(require 'cl-lib)
(require 'bytecomp)
(require 'nelisp-native-optimization-guard-v1)
(let* ((fixture (expand-file-name "guard-oracle.el" (file-name-directory load-file-name)))
       (directory (make-temp-file "nelisp-guard-oracle-" t))
       (source (expand-file-name "guard-oracle.el" directory)))
  ;; Compile the checked-in GNU fixture without relying on a retained ELC or
  ;; changing the source tree. The fixture has no compile-time side effects.
  (unwind-protect
      (progn
        (copy-file fixture source)
        (unless (byte-compile-file source)
          (error "guard oracle: GNU byte compilation failed"))
        (load (byte-compile-dest-file source) nil t))
    (delete-directory directory t)))

(defun nelisp-guard-test--lower (form)
  (if (atom form) form
    (cond
     ((and (equal (getenv "NELISP_GUARD_MUTANT") "type")
           (equal form '(and (= (ptr-read-u64 left 0) 2) (= (ptr-read-u64 right 0) 2)))) t)
     ((and (equal (getenv "NELISP_GUARD_MUTANT") "range")
           (eq (car form) 'and) (consp (cadr form))
           (eq (caadr form) '>=) (memq (cadadr form) '(a b sum))) t)
     (t (cons (if (eq (car form) 'seq) 'progn (car form))
              (mapcar #'nelisp-guard-test--lower (cdr form)))))))

(defun nelisp-guard-test--run (mode a b &optional bad-env alias-output)
  (let* ((roots (vector nil a b 'output-marker nil nil nil))
         (words (make-hash-table :test #'equal))
         (reads 0) (writes 0) (slow 0)
         (source (car (last (nelisp-native-optimization-guard-v1-source 'on))))
         (function (eval (nelisp-guard-test--lower (cons 'lambda (cddr source))) t))
         (output (if alias-output 1 3)))
    (cl-labels ((signed (n) (let ((bits (logand n (1- (expt 2 64)))))
                             (if (>= bits (expt 2 63)) (- bits (expt 2 64)) bits))))
      (cl-letf (((symbol-function 'nl_root_pin_slot_v2)
                 (lambda (env ticket index)
                   (if (and (= env 101) (= ticket 202) (> index 0) (< index 7)) index 0)))
                ((symbol-function 'ptr-read-u64)
                 (lambda (pointer offset)
                   (setq reads (1+ reads))
                   (if (= offset 0) (if (integerp (aref roots pointer)) 2 5) 42)))
                ((symbol-function 'ptr-read-s64)
                 (lambda (pointer _offset)
                   (setq reads (1+ reads))
                   (if (integerp (aref roots pointer)) (signed (aref roots pointer)) 42)))
                ((symbol-function 'ptr-write-u64)
                 (lambda (pointer offset value)
                   (setq writes (1+ writes))
                   (puthash (cons pointer offset) value words)
                   (when (= offset 8) (aset roots pointer (signed value))) 0))
                ((symbol-function 'nl_native_add_v2)
                 (lambda (_env _ticket left right out _exit)
                   (setq slow (1+ slow))
                   (aset roots out (nelisp-guard-oracle-add (aref roots left) (aref roots right))) 0)))
        (let ((status (if (eq mode 'on)
                          (funcall function (if bad-env 999 101) 202 1 2 output 4)
                        (nl_native_add_v2 101 202 1 2 output 4))))
          (list :status status :value (aref roots output) :slow slow
                :reads reads :writes writes :words words))))))

(ert-deftest nelisp-guard/arithmetic-VM-on-off-refallback ()
  (should (byte-code-function-p (symbol-function 'nelisp-guard-oracle-add)))
  (dolist (case (list '(2 3 0) '(-2 3 0) '(1.25 2 1)
                     (list most-positive-fixnum 1 1) (list most-negative-fixnum -1 1)
                     '(9223372036854775807 1 1)))
    (let* ((a (nth 0 case)) (b (nth 1 case))
           (expected (nelisp-guard-oracle-add a b))
           (off (nelisp-guard-test--run 'off a b))
           (on (nelisp-guard-test--run 'on a b)))
      (should (equal expected (plist-get off :value)))
      (should (equal expected (plist-get on :value)))
      (should (= (nth 2 case) (plist-get on :slow)))
      (when (= (nth 2 case) 0)
        (should (= (plist-get on :writes) 4))
        (should (= (gethash '(3 . 0) (plist-get on :words)) 2))
        (should (= (gethash '(3 . 16) (plist-get on :words)) 0))
        (should (= (gethash '(3 . 24) (plist-get on :words)) 0))))))

(ert-deftest nelisp-guard/fullwidth-overflow-refallback ()
  (let ((expected (nelisp-guard-oracle-add 9223372036854775807 1)))
    (should (equal expected
                   (plist-get (nelisp-guard-test--run 'on 9223372036854775807 1) :value)))))

(ert-deftest nelisp-guard/type-refallback-root-refusal-and-alias ()
  (dolist (mode '(on off))
    (should-error (nelisp-guard-test--run mode "wrong" 2) :type 'wrong-type-argument))
  (let ((refused (nelisp-guard-test--run 'on 2 3 t)))
    (should (= (plist-get refused :status) 2))
    (should (= (plist-get refused :reads) 0))
    (should (= (plist-get refused :writes) 0))
    (should (= (plist-get refused :slow) 0))
    (should (eq (plist-get refused :value) 'output-marker)))
  (should (= (plist-get (nelisp-guard-test--run 'on 2 3 nil t) :value) 5)))

(ert-deftest nelisp-guard/call-redefinition-and-live-callee ()
  (let ((expected (symbol-function 'nelisp-guard-oracle-call-first))
        (replacement (symbol-function 'nelisp-guard-oracle-call-replacement))
        (target (make-symbol "guard-call-target")))
    (unwind-protect
        (progn
          (fset target expected)
          (let ((decision (nelisp-native-optimization-guard-v1-call-select target expected)))
            (should (eq (plist-get decision :route) 'fast))
            (should (eq (plist-get decision :callee) expected))
            (should (= (funcall (plist-get decision :callee) 10) 11)))
          (fset target replacement)
          (garbage-collect)
          (let* ((decision (if (getenv "NELISP_GUARD_CALL_MUTANT")
                               (list :route 'fast :callee expected)
                             (nelisp-native-optimization-guard-v1-call-select target expected)))
                 (actual (funcall (plist-get decision :callee) 10)))
            (should (eq (plist-get decision :route) 'slow))
            (should (eq (plist-get decision :callee) replacement))
            (should (= actual (funcall target 10)))
            (should (= actual 9))))
      (fmakunbound target))))

(ert-deftest nelisp-guard/bounded-source-and-context ()
  (should (= (length (nelisp-native-optimization-guard-v1-source 'on)) 6))
  (should (= (length (nelisp-native-optimization-guard-v1-source 'off)) 5))
  (should-error (nelisp-native-optimization-guard-v1-source 'unknown))
  (should (eq (plist-get (nelisp-native-optimization-guard-v1-descriptor 'on) :native-call-guard)
              'pending-owner-proof))
  (should (eq (plist-get (nelisp-native-optimization-guard-v1-call-select nil #'identity) :route) 'refused))
  (let ((cycle (list 'x)))
    (setcdr cycle cycle)
    (should-error (nelisp-native-optimization-guard-v1--copy cycle nil (list 2048) 0))))

(ert-deftest nelisp-guard/source-budget-and-owner-mutation ()
  (should-error (nelisp-native-optimization-guard-v1--copy '(a b) nil (list 1) 0))
  (should-error (nelisp-native-optimization-guard-v1--copy 'a nil (list 2048) 65))
  (let* ((symbol 'nelisp-native-optimization-guard-v1-source)
         (owner (symbol-function symbol))
         (before (nelisp-native-optimization-guard-v1-dependency-context)))
    (unwind-protect
        (progn
          ;; Equivalent source data must not erase a replaced helper owner.
          (fset symbol (lambda (mode) (funcall owner mode)))
          (should-error (nelisp-native-optimization-guard-v1-dependency-context)))
      (fset symbol owner))
    (should (eq (nth 1 (aref before 0))
                (nth 1 (aref (nelisp-native-optimization-guard-v1-dependency-context) 0))))))

(ert-deftest nelisp-guard/private-copy-owner-refuses-before-invocation ()
  (let ((owner (symbol-function 'nelisp-native-optimization-guard-v1--copy)) (calls 0))
    (unwind-protect
        (progn
          (fset 'nelisp-native-optimization-guard-v1--copy
                (lambda (&rest _) (setq calls (1+ calls)) nil))
          (should-error (nelisp-native-optimization-guard-v1-owner-valid-p))
          (should-error (nelisp-native-optimization-guard-v1-source 'on))
          (should-error (nelisp-native-optimization-guard-v1-dependency-context))
          (should (= calls 0)))
      (fset 'nelisp-native-optimization-guard-v1--copy owner))
    (should (nelisp-native-optimization-guard-v1-owner-valid-p))))
