;;; nelisp-float-reader-exact-test.el --- float literal parsing exactness -*- lexical-binding: t; -*-

;; Copyright (C) 2026 zawatton

;; This file is not part of GNU Emacs.

;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Commentary:

;; The float READER (`read' / `string-to-number' on a decimal float
;; literal, `nl_str_to_float' in `lisp/nelisp-cc-evalport-str-to-
;; float.el') was inexact for a measurable slice of doubles: the
;; Eisel-Lemire 128-bit fast path (`nl_lem_hi'/`nl_lem_lo', Doc 159
;; §8) signals ambiguity (`fb=1') for specific (mantissa, decimal-
;; exponent) pairs -- some of them, like "1e23", provably EXACT ties
;; needing round-to-even, not merely close calls -- and NeLisp's
;; fallback for that signal was a single, already-lossy float
;; multiply/divide (`(* (i64-to-f64 mant) (bits-to-f64 (pow10hi q)))'),
;; which double-rounds for any mantissa wider than 53 bits.  Measured
;; against a corpus built from GNU Emacs's own shortest-round-trip
;; printer output plus a broad arithmetic sweep: about 1.6% of an
;; 11,026-value corpus failed `(= (read (prin1-to-string x)) x)'
;; before this fix.
;;
;; Two separate, compounding bugs, both in
;; `lisp/nelisp-cc-evalport-str-to-float.el':
;;
;;   1. `nl_lem_hi'/`nl_lem_lo' (the 128-bit power-of-five table Doc
;;      159 §8 built) were generated by TRUNCATING (floor) the exact
;;      value instead of rounding to nearest -- confirmed by comparing
;;      every table entry, q in [-342,308], against an exact bignum
;;      reference: 299 of 651 entries need rounding up and every one
;;      of those 299 matched floor, none matched round-to-nearest.  In
;;      practice this specific bug rarely flips the final answer (128
;;      bits of precision swamps a 1-part-in-2^128 error), but it is a
;;      real, fixable defect and is fixed here regardless.
;;   2. The actual, measurable bug: when Eisel-Lemire's own ambiguity
;;      check (`fb') fires -- which happens for a bounded, specific
;;      range of decimal exponents (-27 <= net_exp <= 55) and is by
;;      design meant to catch exactly the rare cases needing more care
;;      -- NeLisp fell back to ONE float op on a mantissa that, for
;;      anything past ~53 significant bits (~16 decimal digits), was
;;      already rounded (hence already wrong) before that op ever ran.
;;
;; Fix (`nlf_exact_fallback' and its helpers, same file): when Eisel-
;; Lemire signals ambiguity within its own bounded exponent range,
;; resolve it EXACTLY instead of falling back to a lossy float op:
;;
;;   - net_exp >= 0: MANT * 10^net_exp is an EXACT integer (no
;;     rounding at all going in) -- computed as a 4-limb (256-bit)
;;     schoolbook product (`nlf_exact_pos', reusing the file's own
;;     `nl_u128_hi' 64x64->128 multiply), then rounded to the nearest
;;     double with correct round-to-even (`nlf_extract53'/
;;     `nlf_round53', which locate the top nonzero limb, extract a
;;     64-bit window plus an exact sticky bit from everything below
;;     it, and round on that).
;;   - net_exp < 0: split into the RARE case where MANT is an exact
;;     multiple of 5^|net_exp| (`nlf_exact_neg' -- native `mod'/`/' on
;;     plain i64s, since both fit comfortably within 64 bits for
;;     |net_exp| <= 27) -- then MANT/10^|net_exp| reduces to
;;     (MANT/5^|net_exp|) * 2^(-|net_exp|), an EXACT dyadic value, no
;;     approximation anywhere -- and the general case, multiplying by
;;     a correctly-rounded 256-bit reciprocal of 5^|net_exp| (baked
;;     table, `nlf_rca'/`nlf_rcb'/`nlf_rcc'/`nlf_rcd') and rounding the
;;     5-limb product the same way.
;;
;; Verified against 470,000+ (mantissa, decimal-exponent) pairs spanning
;; every digit length NeLisp's reader ever produces (1 to 18 -- the
;; digit-accumulation cap in `nl_str_to_float' itself) and the full
;; net_exp range Eisel-Lemire's own ambiguity check can ever fire in
;; (-27..55), using an independent, exact-bignum reference implemented
;; in host Elisp (not this fix's own code): zero mismatches.  `string-
;; to-number' is fixed separately, in `scripts/nelisp-stdlib-
;; prelude.el': its float branch used to run its OWN interpreted
;; digit-by-digit walk (`nelisp--scale10', repeated multiplication by
;; at-most-22-exact powers of ten -- the same double-rounding shape as
;; bug 2 above, independently) instead of sharing the fixed reader; it
;; now re-synthesizes the "<mant>e<exp>" form its own digit walk
;; already computed and calls `read' on it, both closing the same class
;; of bug there and dropping its ~25x-slower-than-`read' interpreted
;; scaling loop.
;;
;; This file follows test/nelisp-float-exp-range-test.el's pattern:
;; run target/nelisp itself (a host-only comparison would stay green
;; whether or not the standalone fix is present, since the defect
;; lives in the AOT-compiled reader, not anything host Emacs shares),
;; and re-derive every expectation from a live host Emacs so a copied-
;; in constant cannot go stale.

;;; Code:

(require 'ert)
(require 'subr-x)

(defconst nelisp-float-reader-exact-test--repo-root
  (file-name-as-directory
   (expand-file-name ".." (file-name-directory
                           (or load-file-name buffer-file-name))))
  "Absolute root of the checkout holding this test.")

;; Every one of these previously misread under the OLD fallback
;; (measured directly against a pre-fix target/nelisp build); each is
;; re-verified against a live host Emacs by
;; `nelisp-float-reader-exact/host-emacs-pins-the-oracle' below, so a
;; stale or mistyped expectation cannot sit here quietly.
(defconst nelisp-float-reader-exact-test--strings
  '("9e24" "-9e24" "5e24" "-5e24" "99e23" "-99e23"
    "1e23" "-1e23"
    "17976931348623157e1" "-17976931348623157e1"
    "17976931348623157e2" "-17976931348623157e2"
    "17976931348623157e3" "-17976931348623157e3"
    "123456789012345e4" "-123456789012345e4"
    "438857990509934742e1" "-438857990509934742e1"
    "80430433116792665e-1" "-80430433116792665e-1"
    "69820765572332365e-1" "-69820765572332365e-1"
    "75599031617898775e-1" "-75599031617898775e-1"
    "2.0041683600089728e-308" "-2.0041683600089728e-308")
  "Decimal float literals the pre-fix reader misread by exactly 1 ULP
(the first twelve pairs, all <= 18 significant digits -- the widest a
GNU-Emacs-printed round-trip string is ever needs and the widest
`nl_str_to_float' itself ever keeps; 19-digit literals hit a separate,
pre-existing, documented truncation-not-rounding limit in that
function's own digit cap and are deliberately not exercised here), plus
one deep-subnormal case that a first, differently-shaped regeneration
of the corrected `nl_lem_hi'/`nl_lem_lo' tables mis-compiled -- the
interpreted (host-Elisp) simulation of that regenerated tree read it
correctly, but the AOT-compiled machine code did not, even though the
case (q=-324) never reaches any of this fix's new code at all, only
the table + the unmodified `nl_lem_compute'.  Fixed by regenerating the
tables as a MINIMAL, structure-preserving patch -- walking the
ORIGINAL if-tree and replacing only the individual leaf literals that
were actually wrong, keeping every `(if (< q N) ...)' branch byte-
identical to the shipped tree -- rather than a freshly bisected one of
a different shape.")

(defun nelisp-float-reader-exact-test--host-value (s)
  "GNU Emacs's own, correctly-rounded reading of S."
  (read s))

(defun nelisp-float-reader-exact-test--binary ()
  "Return the standalone binary path, or skip the test when it is absent."
  (let ((binary (expand-file-name "target/nelisp"
                                  nelisp-float-reader-exact-test--repo-root)))
    (unless (file-executable-p binary)
      (ert-skip "target/nelisp is not built; standalone-reader-test owns it"))
    binary))

(defun nelisp-float-reader-exact-test--eval (expression)
  "Return `target/nelisp''s trimmed stdout for EXPRESSION."
  (let ((binary (nelisp-float-reader-exact-test--binary)))
    (with-temp-buffer
      (let ((rc (call-process binary nil t nil "--eval" expression)))
        (unless (= rc 0)
          (ert-fail (format "standalone %s failed: rc=%S out=%S"
                            expression rc (buffer-string))))
        (string-trim (buffer-string))))))

(ert-deftest nelisp-float-reader-exact/host-emacs-pins-the-oracle ()
  "Every string in the fixed list must have a well-defined, non-NaN
host reading -- guards the list itself against a typo turning a real
case into something `read' silently errors or NaNs on instead."
  (dolist (s nelisp-float-reader-exact-test--strings)
    (let ((v (nelisp-float-reader-exact-test--host-value s)))
      (should (floatp v))
      (should (not (isnan v))))))

(ert-deftest nelisp-float-reader-exact/standalone-read-matches-host ()
  "`(read S)' under target/nelisp equals GNU Emacs's reading of S, for
every previously-misread string -- checked via `=' on the value
(evaluated by the standalone binary itself), not by comparing printed
strings, so this cannot be fooled by a coincidentally-matching printer
bug."
  (dolist (s nelisp-float-reader-exact-test--strings)
    (let* ((host-val (nelisp-float-reader-exact-test--host-value s))
           (expr (format "(= (read %S) %s)" s (prin1-to-string host-val))))
      (should (equal "t" (nelisp-float-reader-exact-test--eval expr))))))

(ert-deftest nelisp-float-reader-exact/standalone-string-to-number-matches-host ()
  "`string-to-number' shares the same fix (routes its float branch
through `read' instead of its own lossy `nelisp--scale10' walk)."
  (dolist (s nelisp-float-reader-exact-test--strings)
    (let* ((host-val (nelisp-float-reader-exact-test--host-value s))
           (expr (format "(= (string-to-number %S) %s)" s (prin1-to-string host-val))))
      (should (equal "t" (nelisp-float-reader-exact-test--eval expr))))))

(defun nelisp-float-reader-exact-test--mkmant (n seed)
  "The Nth deterministic N-digit mantissa string from SEED (host-side;
NeLisp's own elisp layer has no bignums, so the exact 'expected' value
below is computed here, under host Emacs, not inside target/nelisp)."
  (let ((s (make-string n ?0)) (x (mod seed 2147483647)))
    (aset s 0 (+ ?1 (mod (abs x) 9)))
    (dotimes (i (1- n))
      (setq x (mod (+ (* x 48271) 12345) 2147483647))
      (aset s (1+ i) (+ ?0 (mod (abs x) 10))))
    s))

(defun nelisp-float-reader-exact-test--expected (mant k)
  "The correctly-rounded double for MANT * 10^K, via exact host bignum
rational arithmetic (round-to-nearest-even) -- the same algorithm
CLAUDE-REPORT.md section 3 validated against 473,112 cases, used here
as this test's oracle instead of routing through NeLisp's own printer
(which has a separate, pre-existing, out-of-scope limitation for
fixed-point strings with several leading zeros -- see section 5.2)."
  (let* ((num (if (>= k 0) (* mant (expt 10 k)) mant))
         (den (if (>= k 0) 1 (expt 10 (- k))))
         (bl (- (nelisp-float-reader-exact-test--bitlen num)
                (nelisp-float-reader-exact-test--bitlen den))))
    ;; floor(log2(num/den)), found by comparing num against den*2^bl --
    ;; NEVER via (ash 1 bl) directly (bl can be very negative here, and
    ;; (ash 1 NEGATIVE) silently underflows to 0, which is exactly the
    ;; bug this comment is warning off): shift whichever side needs a
    ;; NON-negative shift instead.
    (while (not (if (>= bl 0) (>= num (* den (ash 1 bl))) (>= (ash num (- bl)) den)))
      (setq bl (1- bl)))
    (while (if (>= (1+ bl) 0) (>= num (* den (ash 1 (1+ bl)))) (>= (ash num (- (1+ bl))) den))
      (setq bl (1+ bl)))
    (let* ((shift (- bl 52))
           (scaled-num (if (>= shift 0) num (ash num (- shift))))
           (scaled-den (if (>= shift 0) (* den (ash 1 shift)) den))
           (cand (/ scaled-num scaled-den))
           (rem (- scaled-num (* cand scaled-den)))
           (twice (* 2 rem))
           (rounded (cond ((> twice scaled-den) (1+ cand))
                          ((< twice scaled-den) cand)
                          (t (if (= (logand cand 1) 0) cand (1+ cand)))))
           (ov (if (>= rounded (ash 1 53)) 1 0))
           (m3 (if (= ov 1) (ash 1 52) rounded))
           (finalbl (if (= ov 1) (1+ bl) bl)))
      (* (float m3) (expt 2.0 (- finalbl 52))))))

(defun nelisp-float-reader-exact-test--bitlen (n)
  (if (= n 0) 0 (let ((b 0) (x n)) (while (> x 0) (setq b (1+ b) x (ash x -1))) b)))

(ert-deftest nelisp-float-reader-exact/round-trip-property-sweep ()
  "A deterministic pseudo-random sweep: for a set of (mantissa-digit-
string, decimal-exponent) pairs spanning every digit length the reader
ever produces (1..18) and the full ambiguity-triggering exponent range
Eisel-Lemire's own check can ever fire in (-27..55), `(= (read S) X)'
must hold under target/nelisp, where S is `<digits>e<k>' (a plain
integer-mantissa scientific literal -- never fixed-point notation, so
a leading-zero count never enters into it) and X is computed
independently, host-side, by
`nelisp-float-reader-exact-test--expected' (exact bignum rational
arithmetic -- NeLisp's own elisp layer has no bignums, so this cannot
run inside target/nelisp itself; only the `read' being tested does).
All cases are checked in one `target/nelisp' invocation."
  (let ((cases nil))
    (dotimes (leni 18)
      (let ((len (1+ leni)))
        (dotimes (rep 2)
          (let* ((digits (nelisp-float-reader-exact-test--mkmant
                          len (+ (* len 97) (* rep 131) 1)))
                 (mant (string-to-number digits)))
            (dotimes (ki 21)
              (let ((k (- (* ki 4) 27)))
                (push (cons (format "%se%d" digits k)
                            (nelisp-float-reader-exact-test--expected mant k))
                      cases)))))))
    (setq cases (nreverse cases))
    (let* ((checks (mapconcat
                    ;; The expected value is embedded as a literal via
                    ;; "%.17e" (always scientific notation, exactly 18
                    ;; significant digits, never any leading zeros in
                    ;; the mantissa), not `prin1-to-string': the latter
                    ;; can choose FIXED-point notation for this
                    ;; magnitude, and reading THAT back here would
                    ;; round-trip through the same separate,
                    ;; pre-existing, out-of-scope leading-zero digit-
                    ;; cap bug documented in section 5.2 -- a bug in
                    ;; this harness's own embedding, not in the case
                    ;; under test.
                    (lambda (c)
                      (format "(unless (= (read %S) %s) (setq bad (1+ bad)) (when (< (length firsts) 20) (setq firsts (cons %S firsts))))"
                              (car c) (format "%.17e" (cdr c)) (car c)))
                    cases "\n"))
           (script (format "(let ((bad 0) (firsts nil)) %s (princ (format \"TOTAL=%d BAD=%%d FIRSTS=%%S\" bad (reverse firsts))))"
                           checks (length cases)))
           (out (with-temp-buffer
                  (let* ((binary (nelisp-float-reader-exact-test--binary))
                         (tmp (make-temp-file "nlf-round-trip-" nil ".el" script))
                         (rc (call-process binary nil t nil "--load" tmp)))
                    (delete-file tmp)
                    (unless (= rc 0)
                      (ert-fail (format "standalone round-trip sweep crashed: rc=%S out=%S"
                                        rc (buffer-string))))
                    (buffer-string)))))
      (should (string-match "TOTAL=\\([0-9]+\\) BAD=\\([0-9]+\\) FIRSTS=\\(.*\\)" out))
      (let ((total (string-to-number (match-string 1 out)))
            (bad (string-to-number (match-string 2 out)))
            (firsts (match-string 3 out)))
        (should (> total 0))
        (unless (= bad 0)
          (ert-fail (format "%d/%d round-trip failures, first: %s" bad total firsts)))))))

(provide 'nelisp-float-reader-exact-test)

;;; nelisp-float-reader-exact-test.el ends here
