;;; nelisp-eln-symbol-base-lease-test.el --- Symbol-base lease tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'nelisp-eln-objects)

(ert-deftest nelisp-eln-symbol-base-lease-pins-through-unit-symbol-cleanup ()
  (let* ((mapping 'mapping)
         (base (vector mapping 4096 'name-owner 'open))
         (nelisp-eln-objects--symbol-base base)
         (nelisp-eln-objects--symbol-base-leases nil)
         (nelisp-eln-objects--identity-records nil)
         (nelisp-eln-objects--registry-state 'open)
         (token nil)
         (released 0))
    (cl-letf (((symbol-function 'nelisp-eln-objects--ensure-symbol-base)
               (lambda () base))
              ((symbol-function 'nl-ffi-memory-release) (lambda (_owner) t))
              ((symbol-function 'nelisp-eln-string-release) (lambda (_owner) t))
              ((symbol-function 'nelisp-eln-objects--release-symbol-base)
               (lambda () (setq released (1+ released)
                                nelisp-eln-objects--symbol-base nil) t)))
      (setq token (nelisp-eln-objects-symbol-base-acquire))
      (let* ((symbol (make-symbol "lease-test"))
             (record (vector symbol 'symbol 8192 'symbol-owner nil 0 0 'open)))
        (push (cons symbol record) nelisp-eln-objects--identity-records)
        (nelisp-eln-objects--finish-global-release record)
        (should (eq nelisp-eln-objects--symbol-base base))
        (should (= released 0))
        (should (eq nelisp-eln-objects--registry-state 'open)))
      (nelisp-eln-objects-symbol-base-release token)
      (should (= released 1))
      (should-not nelisp-eln-objects--symbol-base)
      (should-error (nelisp-eln-objects-symbol-base-release token)
                    :type 'nelisp-eln-objects-error))))

(ert-deftest nelisp-eln-symbol-base-lease-invalid-token-does-not-release-base ()
  (let* ((base (vector 'mapping 4096 'name-owner 'open))
         (nelisp-eln-objects--symbol-base base)
         (nelisp-eln-objects--symbol-base-leases nil)
         (nelisp-eln-objects--identity-records nil)
         (nelisp-eln-objects--registry-state 'open))
    (should-error (nelisp-eln-objects-symbol-base-release
                   (vector nelisp-eln-objects--symbol-base-lease-marker base 'open))
                  :type 'nelisp-eln-objects-error)
    (should (eq nelisp-eln-objects--symbol-base base))))

(ert-deftest nelisp-eln-symbol-base-lease-blocks-direct-base-release ()
  (let* ((base (vector 'mapping 4096 'name-owner 'open))
         (nelisp-eln-objects--symbol-base base)
         (nelisp-eln-objects--symbol-base-leases nil)
         (nelisp-eln-objects--identity-records nil)
         (nelisp-eln-objects--registry-state 'open))
    (cl-letf (((symbol-function 'nelisp-eln-objects--ensure-symbol-base)
               (lambda () base)))
      (let ((token (nelisp-eln-objects-symbol-base-acquire)))
        (should-error (nelisp-eln-objects--release-symbol-base)
                      :type 'nelisp-eln-objects-error)
        (should (eq nelisp-eln-objects--symbol-base base))
        ;; Keep the test's synthetic base from entering the real cleanup path.
        (cl-letf (((symbol-function 'nelisp-eln-objects--release-symbol-base)
                   (lambda () (setq nelisp-eln-objects--symbol-base nil) t)))
          (nelisp-eln-objects-symbol-base-release token))))))

(provide 'nelisp-eln-symbol-base-lease-test)
;;; nelisp-eln-symbol-base-lease-test.el ends here
