;;; nelisp-bytecode-jit-test.el --- P5 narrow lowering tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'nelisp-bytecode-jit)

(defun nelisp-bytecode-jit-test--dispatch-prepared (function &rest arguments)
  "Prepare eligible FUNCTION explicitly, then exercise the VM dispatch hook."
  (let ((ir (nelisp-bytecode-jit--decode-ir function)))
    (when (and ir (nelisp-bytecode-jit--safe-ir-p ir arguments))
      (nelisp-bytecode-jit-prepare function)))
  (apply #'nelisp-bytecode-jit--runtime-dispatch function arguments))

(defun nelisp-bytecode-jit-test--install-ready-handle (function ir handle)
  "Install an explicitly marked test fixture for FUNCTION, IR, and HANDLE."
  (puthash function
           (list :state 'ready
                 :identity (nelisp-bytecode-jit--cache-identity function)
                 :ir ir :handle handle)
           nelisp-bytecode-jit--handles))

(defun nelisp-bytecode-jit-test--candidate-handle (ir &optional entry)
  "Return a metadata-complete mock candidate compatible with IR."
  (cond
   ((nelisp-bytecode-jit--boxed-integerp-ir-p ir)
    (list :entry (or entry 4096) :arity (plist-get ir :arity)
          :abi 'integer :param-repr 'sexp-ptr :return-repr 'raw-bool))
   ((nelisp-bytecode-jit--boxed-result-ir-p ir)
    (list :entry (or entry 4096) :arity (plist-get ir :arity)
          :abi 'boxed :param-repr 'sexp-ptr
          :return-repr (if (nelisp-bytecode-jit--boxed-object-boolean-ir-p ir)
                           'raw-bool 'sexp-ptr)))
   (t (list :entry (or entry 4096) :arity (plist-get ir :arity)
            :abi 'integer :param-repr 'raw-i64 :return-repr 'raw-i64))))

(ert-deftest nelisp-bytecode-jit/runtime-dispatch-queues-once-and-drains-outside-vm ()
  (let* ((function (byte-compile '(lambda (x) (1+ x))))
         (nelisp-bytecode-jit-threshold 1)
         (nelisp-bytecode-jit--deferred-preparation-enabled t)
         (nelisp-bytecode-jit--runtime-identity-cache :unset)
         (nelisp-bytecode-jit--handles (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--pending-identities (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--compile-failures (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--pending-queue nil)
         (nelisp-bytecode-jit--dispatch-active nil)
         (compile-calls 0)
         (identity-calls 0))
    (cl-letf (((symbol-function 'nelisp-native-load--running-binary-sha256)
               (lambda () (setq identity-calls (1+ identity-calls)) "image-a"))
              ((symbol-function 'nelisp-bytecode-jit--compile-ir)
               (lambda (_function _ir)
                 (setq compile-calls (1+ compile-calls))
                 (should (= (nelisp-bytecode-jit-drain-pending) 0))
                 '(:entry 4096 :arity 1 :abi integer
                   :param-repr raw-i64 :return-repr raw-i64)))
              ((symbol-function 'nelisp-native-load-raw-call)
               (lambda (_handle arguments) (1+ (car arguments)))))
      (should-not (nelisp-bytecode-jit--runtime-dispatch function 8))
      (should-not (nelisp-bytecode-jit--runtime-dispatch function 8))
      (should (= compile-calls 0))
      (should (= (length nelisp-bytecode-jit--pending-queue) 1))
      (let ((nelisp-bytecode-jit--dispatch-active t))
        (should (= (nelisp-bytecode-jit-drain-pending) 0)))
      (should (= (nelisp-bytecode-jit-drain-pending) 1))
      (should (= compile-calls 1))
      (should (= identity-calls 1))
      (should (= (length nelisp-bytecode-jit--pending-queue) 0))
      (should (equal (nelisp-bytecode-jit--runtime-dispatch function 8) [t 9]))
      (should (= identity-calls 1)))))

(ert-deftest nelisp-bytecode-jit/preparation-failure-is-terminal-until-identity-changes ()
  (let* ((function (byte-compile '(lambda (x) (1+ x))))
         (nelisp-bytecode-jit-threshold 1)
         (nelisp-bytecode-jit--deferred-preparation-enabled t)
         (nelisp-bytecode-jit--runtime-identity-cache :unset)
         (nelisp-bytecode-jit--handles (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--pending-identities (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--compile-failures (make-hash-table :test 'eq))
         (nelisp-native-load-raw-runtime-abi-v2 "abi-a")
         (nelisp-bytecode-jit--pending-queue nil)
         (compile-calls 0)
         (image "image-a"))
    (cl-letf (((symbol-function 'nelisp-native-load--running-binary-sha256)
               (lambda () image))
              ((symbol-function 'nelisp-bytecode-jit--compile-ir)
               (lambda (&rest _)
                 (setq compile-calls (1+ compile-calls))
                 (error "terminal compile failure"))))
      (should-not (nelisp-bytecode-jit--runtime-dispatch function 4))
      (should-not (nelisp-bytecode-jit--runtime-dispatch function 4))
      (should (= (length nelisp-bytecode-jit--pending-queue) 1))
      (should (= (nelisp-bytecode-jit-drain-pending) 1))
      (should (= compile-calls 1))
      (should (= (hash-table-count nelisp-bytecode-jit--compile-failures) 1))
      (should-not (nelisp-bytecode-jit--runtime-dispatch function 4))
      (should (= compile-calls 1))
      (should (= (length nelisp-bytecode-jit--pending-queue) 0))
      (setq image "image-b"
            nelisp-bytecode-jit--runtime-identity-cache :unset)
      (should-not (nelisp-bytecode-jit--runtime-dispatch function 4))
      (should (= (length nelisp-bytecode-jit--pending-queue) 1))
      (should (= (nelisp-bytecode-jit-drain-pending) 1))
      (should (= compile-calls 2))
      (should (= (hash-table-count nelisp-bytecode-jit--compile-failures) 1))
      (setq nelisp-native-load-raw-runtime-abi-v2 "abi-b")
      (should-not (nelisp-bytecode-jit--runtime-dispatch function 4))
      (should (= (length nelisp-bytecode-jit--pending-queue) 1))
      (should (= (nelisp-bytecode-jit-drain-pending) 1))
      (should (= compile-calls 3))
      (should (= (hash-table-count nelisp-bytecode-jit--compile-failures) 1)))))

(ert-deftest nelisp-bytecode-jit/bytecode-payload-change-invalidates-ready-handle ()
  (let* ((function (byte-compile '(lambda (x) (1+ x))))
         (nelisp-bytecode-jit-threshold 1)
         (nelisp-bytecode-jit--deferred-preparation-enabled t)
         (nelisp-bytecode-jit--runtime-identity-cache :unset)
         (nelisp-bytecode-jit--handles (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--pending-identities (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--compile-failures (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--hot-counts (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--pending-queue nil)
         (compile-calls 0))
    (cl-letf (((symbol-function 'nelisp-native-load--running-binary-sha256)
               (lambda () "stable-image"))
              ((symbol-function 'nelisp-bytecode-jit--compile-ir)
               (lambda (_function _ir)
                 (setq compile-calls (1+ compile-calls))
                 (list :entry compile-calls :arity 1 :abi 'integer
                       :param-repr 'raw-i64 :return-repr 'raw-i64)))
              ((symbol-function 'nelisp-bytecode-jit--execute-ir)
               (lambda (_ir handle arguments)
                 (list (plist-get handle :entry) (car arguments)))))
      (should-not (nelisp-bytecode-jit--runtime-dispatch function 10))
      (should (nelisp-bytecode-jit--validated-handle-p
               (nelisp-bytecode-jit--decode-ir function)
               (nelisp-bytecode-jit--cache-identity function)
               '(:entry 4096 :arity 1 :abi integer
                 :param-repr raw-i64 :return-repr raw-i64)))
      (should (= (nelisp-bytecode-jit-drain-pending) 1))
      (should (nelisp-bytecode-jit--ready-handle
               function (nelisp-bytecode-jit--decode-ir function)
               (nelisp-bytecode-jit--cache-identity function)))
      (should (equal (nelisp-bytecode-jit--runtime-dispatch function 11)
                     [t (1 11)]))
      (let ((bytecode (aref function 1)))
        (aset bytecode 0 83))
      (should-not (nelisp-bytecode-jit--runtime-dispatch function 12))
      (should (= (nelisp-bytecode-jit-drain-pending) 1))
      (should (= compile-calls 2))
      (should (equal (nelisp-bytecode-jit--runtime-dispatch function 13)
                     [t (2 13)])))))

(ert-deftest nelisp-bytecode-jit/preflight-rejection-does-not-hash-or-queue ()
  (let* ((function (make-byte-code 257 (unibyte-string 85 135) [] 2))
         (nelisp-bytecode-jit--runtime-identity-cache :unset)
         (nelisp-bytecode-jit--pending-identities (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--pending-queue nil)
         (identity-calls 0))
    (cl-letf (((symbol-function 'nelisp-native-load--running-binary-sha256)
               (lambda () (setq identity-calls (1+ identity-calls)) "image")))
      (should-not (nelisp-bytecode-jit--runtime-dispatch function 3))
      (should (= identity-calls 0))
      (should-not nelisp-bytecode-jit--pending-queue))))

(ert-deftest nelisp-bytecode-jit/prepare-rejects-missing-identity-and-memoizes-bad-handle ()
  (let* ((function (byte-compile '(lambda (x) (1+ x))))
         (nelisp-bytecode-jit--runtime-identity-cache :unset)
         (nelisp-bytecode-jit--handles (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--compile-failures (make-hash-table :test 'eq))
         (compile-calls 0))
    (cl-letf (((symbol-function 'nelisp-bytecode-jit--function-payload-fingerprint)
               (lambda (_function) nil))
              ((symbol-function 'nelisp-bytecode-jit--compile-ir)
               (lambda (&rest _) (setq compile-calls (1+ compile-calls))))
              ((symbol-function 'nelisp-native-load--running-binary-sha256)
               (lambda () "identity")))
      (should-not (nelisp-bytecode-jit-prepare function))
      (should (= compile-calls 0)))
    (cl-letf (((symbol-function 'nelisp-native-load--running-binary-sha256)
               (lambda () "identity"))
              ((symbol-function 'nelisp-bytecode-jit--compile-ir)
               (lambda (&rest _)
                 (setq compile-calls (1+ compile-calls))
                 '(:entry 4096 :arity 99 :abi integer
                   :param-repr raw-i64 :return-repr raw-i64))))
      (should-error (nelisp-bytecode-jit-prepare function))
      (should (= (hash-table-count nelisp-bytecode-jit--compile-failures) 1))
      (should-error (nelisp-bytecode-jit-prepare function))
      (should (= compile-calls 1)))))

(ert-deftest nelisp-bytecode-jit/generic-native-entry-error-does-not-replay-and-recovers ()
  (let* ((function (byte-compile '(lambda (x) (+ x 1))))
         (nelisp-bytecode-jit-threshold 1)
         (nelisp-bytecode-jit--hot-counts (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--pending-queue nil)
         (nelisp-bytecode-jit--pending-identities (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--compile-failures (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--dispatch-active nil)
         (nelisp-bytecode-jit--interpreter-fallback-count 0)
         (nelisp-bytecode-jit--native-call-count 0)
         (native-calls 0)
         (replays 0))
         (cl-letf (((symbol-function 'nelisp-bytecode-jit--compile-ir)
               (lambda (_function ir)
                 (nelisp-bytecode-jit-test--candidate-handle ir)))
              ((symbol-function 'nelisp-native-load-raw-call)
               (lambda (_handle _arguments)
                 (setq native-calls (1+ native-calls))
                 (if (= native-calls 1)
                     (signal 'file-error '("mock native entry failed"))
                   9))))
      (let ((failure
             (should-error
              (if (nelisp-bytecode-jit-test--dispatch-prepared function 8)
                  'native-result
                (setq replays (1+ replays)))
              :type 'file-error)))
        (should (equal failure '(file-error "mock native entry failed"))))
      (should (= native-calls 1))
      (should (= replays 0))
      (should (= nelisp-bytecode-jit--interpreter-fallback-count 0))
      (should-not nelisp-bytecode-jit--dispatch-active)
      (should (equal (nelisp-bytecode-jit-test--dispatch-prepared function 8) [t 9]))
      (should (= native-calls 2)))))

(ert-deftest nelisp-bytecode-jit/prepared-predicate-native-entry-error-does-not-replay-and-recovers ()
  (let* ((function (byte-compile '(lambda (x) (stringp x))))
         (ir (nelisp-bytecode-jit--decode-boxed-predicate function))
         (handle 'mock-boxed-handle)
         (nelisp-bytecode-jit-threshold 1)
         (nelisp-bytecode-jit--handles (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--hot-counts (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--pending-queue nil)
         (nelisp-bytecode-jit--pending-identities (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--compile-failures (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--dispatch-active nil)
         (nelisp-bytecode-jit--interpreter-fallback-count 0)
         (nelisp-bytecode-jit--native-call-count 0)
         (native-calls 0)
         (replays 0))
    (nelisp-bytecode-jit-test--install-ready-handle
     function (nelisp-bytecode-jit--decode-ir function) handle)
    (cl-letf (((symbol-function 'nelisp-native-load-call)
               (lambda (_handle _arguments)
                 (setq native-calls (1+ native-calls))
                 (if (= native-calls 1)
                     (signal 'file-error '("mock boxed entry failed"))
                   t))))
      (let ((failure
             (should-error
              (if (nelisp-bytecode-jit-test--dispatch-prepared function "text")
                  'native-result
                (setq replays (1+ replays)))
              :type 'file-error)))
        (should (equal failure '(file-error "mock boxed entry failed"))))
      (should (= native-calls 1))
      (should (= replays 0))
      (should (= nelisp-bytecode-jit--interpreter-fallback-count 0))
      (should-not nelisp-bytecode-jit--dispatch-active)
      (should (equal (nelisp-bytecode-jit-test--dispatch-prepared function "text")
                     [t t]))
      (should (= native-calls 2)))))

(defvar nelisp-bytecode-jit-test-global-bound nil)

(ert-deftest nelisp-bytecode-jit/frame-configuration-p-generic-ir-uses-boxed-symbol-literal ()
  (let* ((function
          (make-byte-code
           257 (unibyte-string 137 58 133 9 0 137 64 192 61 135)
           [frame-configuration] 3))
         (ir (nelisp-bytecode-jit--decode-ir function)))
    (should (equal (plist-get ir :expression)
                   '(if (consp x0)
                        (eq (car x0) (quote frame-configuration))
                      (consp x0))))
    (should (nelisp-bytecode-jit--boxed-object-boolean-ir-p ir))
    (should (nelisp-bytecode-jit--safe-ir-p
             ir '((frame-configuration state))))
    (should-not (nelisp-bytecode-jit--safe-ir-p ir '((frame-configuration . state))))
    (should-not (nelisp-bytecode-jit--safe-ir-p ir (list (make-symbol "loose"))))))

(ert-deftest nelisp-bytecode-jit/object-boolean-unknown-return-requires-boxed-abi ()
  (let* ((function
          (make-byte-code
           257 (unibyte-string 137 58 133 9 0 137 64 192 61 135)
           [frame-configuration] 3))
         (ir (nelisp-bytecode-jit--decode-ir function))
         (nelisp-bytecode-jit--handles (make-hash-table :test 'eq))
         (handle '(:entry 4096 :arity 1 :abi boxed
                   :param-repr sexp-ptr :return-repr unknown)))
    (cl-letf (((symbol-function 'nelisp-artifact-compile-file)
               (lambda (&rest _args) nil))
              ((symbol-function 'nelisp-native-load-artifact)
               (lambda (&rest _args) handle)))
      (should (eq (nelisp-bytecode-jit--compile-ir function ir) handle))
      (clrhash nelisp-bytecode-jit--handles)
      (setq handle (plist-put handle :abi 'integer))
      (should-error (nelisp-bytecode-jit--compile-ir function ir)))))

(ert-deftest nelisp-bytecode-jit/frame-configuration-p-dispatch-keeps-boxed-fallback-guard ()
  (let* ((function
          (make-byte-code
           257 (unibyte-string 137 58 133 9 0 137 64 192 61 135)
           [frame-configuration] 3))
         (nelisp-bytecode-jit-threshold 1)
         (nelisp-bytecode-jit--handles (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--hot-counts (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--native-call-count 0)
         (handle '(:entry 4096 :arity 1 :abi boxed :param-repr sexp-ptr
                   :return-repr sexp-ptr)))
    (cl-letf (((symbol-function 'nelisp-bytecode-jit--compile-ir)
               (lambda (_function _ir) handle))
              ((symbol-function 'nelisp-native-load-call)
               (lambda (actual arguments)
                 (should (eq actual handle))
                 (should (equal arguments '((frame-configuration state))))
                 t)))
      (should (equal (nelisp-bytecode-jit-test--dispatch-prepared
                      function '(frame-configuration state))
                     [t t]))
      (should (= nelisp-bytecode-jit--native-call-count 1))
      (should-not (nelisp-bytecode-jit-test--dispatch-prepared
                   function '(frame-configuration . state)))
      (should (= nelisp-bytecode-jit--native-call-count 1)))))

(ert-deftest nelisp-bytecode-jit/generic-variable-ref-ir-lowering ()
  (let* ((symbol 'nelisp-bytecode-jit-test-global-bound)
         (function (make-byte-code 0 (unibyte-string 8 135) (vector symbol) 1))
         (nelisp-bytecode-jit-test-global-bound 41)
         (ir (nelisp-bytecode-jit--decode-ir function)))
    (should (equal (plist-get ir :expression) symbol))
    (should (nelisp-bytecode-jit--safe-ir-p ir nil))))

(ert-deftest nelisp-bytecode-jit/vendor-fixnump-opcode-168-ir-and-safe-fallback ()
  (let* ((function
          (make-byte-code
           257 (unibyte-string 137 168 133 14 0 8 1 88 133 14 0
                               137 9 88 135)
           [most-negative-fixnum most-positive-fixnum] 3))
         (code (aref function 1))
         (constants (aref function 2))
         (ir (nelisp-bytecode-jit--decode-ir function))
         (rows (nelisp-bytecode-jit--decode-instructions code constants))
         (nelisp-bytecode-jit-threshold 1)
         (nelisp-bytecode-jit--hot-counts (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--native-call-count 0))
    (should
     (equal (secure-hash 'sha256
                         (prin1-to-string
                          (list (aref function 0) code constants
                                (aref function 3))))
            "102e639e742351efbc457d8517db951ead880750dbc9eb1b96409f5fe063762d"))
    (should (equal (mapcar (lambda (row) (aref row 1)) rows)
                   '(137 168 133 8 1 88 133 137 9 88 135)))
    (should (equal (plist-get ir :expression)
                   '(if (integerp x0)
                        (if (<= most-negative-fixnum x0)
                            (<= x0 most-positive-fixnum)
                          (<= most-negative-fixnum x0))
                      (integerp x0))))
    (dolist (case '((17 . t) (-17 . t) ("text" . nil) (symbol . nil)
                    (nil . nil) ((1+ most-positive-fixnum) . nil)))
      (should (eq (funcall function (car case)) (cdr case))))
    (should (nelisp-bytecode-jit--safe-ir-p ir '(17)))
    (should (nelisp-bytecode-jit--safe-ir-p ir '("text")))
    (should-not (nelisp-bytecode-jit--safe-ir-p ir '(1.5)))
    (should-not (nelisp-bytecode-jit--safe-ir-p
                 ir (list (1+ most-positive-fixnum))))
    (should-not
     (nelisp-bytecode-jit-test--dispatch-prepared
      function (1+ most-positive-fixnum)))
    (should (= nelisp-bytecode-jit--native-call-count 0))))

(ert-deftest nelisp-bytecode-jit/gnu-emacs-31-nil-constant-enters-generic-ir ()
  (let* ((function (byte-compile '(lambda () nil)))
         (code (aref function 1))
         (ir (nelisp-bytecode-jit--decode-ir function)))
    (should (= (aref function 0) 0))
    (should (equal (string-to-list code) '(192 135)))
    (should (equal (aref function 2) [nil]))
    (should (= (aref function 3) 1))
    (should-not (funcall function))
    (should ir)
    (should (null (plist-get ir :expression)))
    (should (nelisp-bytecode-jit--safe-ir-p ir nil))))

(ert-deftest nelisp-bytecode-jit/comparison-ir-decodes-only-boolean-words ()
  (let* ((function (byte-compile '(lambda (x) (= x 0))))
         (ir (nelisp-bytecode-jit--decode-ir function)))
    (should (equal (plist-get ir :expression) '(= x0 0)))
    (should (nelisp-bytecode-jit--boolean-result-ir-p ir))
    (cl-letf (((symbol-function 'nelisp-bytecode-jit--compile-ir)
               (lambda (&rest _) 'fake-handle))
              ((symbol-function 'nelisp-native-load-raw-call)
               (lambda (&rest _) 1)))
      (should (nelisp-bytecode-jit--call-ir function ir '(0))))
    (cl-letf (((symbol-function 'nelisp-bytecode-jit--compile-ir)
               (lambda (&rest _) 'fake-handle))
              ((symbol-function 'nelisp-native-load-raw-call)
               (lambda (&rest _) 0)))
      (should-not (nelisp-bytecode-jit--call-ir function ir '(1))))
    (cl-letf (((symbol-function 'nelisp-bytecode-jit--compile-ir)
               (lambda (&rest _) 'fake-handle))
              ((symbol-function 'nelisp-native-load-raw-call)
               (lambda (&rest _) 2)))
      (should-error (nelisp-bytecode-jit--call-ir function ir '(0))))))

(ert-deftest nelisp-bytecode-jit/numeric-and-conditional-ir-stay-raw ()
  (let* ((numeric (nelisp-bytecode-jit--decode-ir
                   (byte-compile '(lambda (x) (1+ x)))))
         (conditional (nelisp-bytecode-jit--decode-ir
                       (byte-compile '(lambda (x) (if (= x 0) 1 2))))))
    (should-not (nelisp-bytecode-jit--boolean-result-ir-p numeric))
    (should-not (nelisp-bytecode-jit--boolean-result-ir-p conditional))
    (cl-letf (((symbol-function 'nelisp-bytecode-jit--compile-ir)
               (lambda (&rest _) 'fake-handle))
              ((symbol-function 'nelisp-native-load-raw-call)
               (lambda (&rest _) 1)))
      (should (= 1 (nelisp-bytecode-jit--call-ir nil numeric '(0))))
      (should (= 1 (nelisp-bytecode-jit--call-ir nil conditional '(0)))))))

(ert-deftest nelisp-bytecode-jit/nil-constant-dispatches-with-boxed-abi ()
  (let* ((function (byte-compile '(lambda () nil)))
         (nelisp-bytecode-jit-threshold 1)
         (nelisp-bytecode-jit--hot-counts (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--handles (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--native-call-count 0)
         (nelisp-bytecode-jit--interpreter-fallback-count 0)
         (observed nil))
    (cl-letf (((symbol-function 'nelisp-bytecode-jit--compile-ir)
               (lambda (_function ir)
                 (nelisp-bytecode-jit-test--candidate-handle ir)))
              ((symbol-function 'nelisp-native-load-call)
               (lambda (handle arguments)
                 (setq observed (list handle arguments))
                 nil))
              ((symbol-function 'nelisp-native-load-raw-call)
               (lambda (&rest _args) (ert-fail "nil IR used raw ABI"))))
      (should (equal (nelisp-bytecode-jit-test--dispatch-prepared function) [t nil]))
      (should (equal (cadr observed) nil))
      (should (equal (plist-get (car observed) :abi) 'boxed))
      (should (= nelisp-bytecode-jit--native-call-count 1))
      (should (= nelisp-bytecode-jit--interpreter-fallback-count 0)))))

(ert-deftest nelisp-bytecode-jit/decodes-only-complete-unary-return-streams ()
  (let ((add1 (make-byte-code 257 (unibyte-string 84 135) [] 2))
        (sub1 (make-byte-code 257 (unibyte-string 83 135) [] 2))
        (unknown (make-byte-code 257 (unibyte-string 85 135) [] 2))
        (after-return (make-byte-code 257 (unibyte-string 135 84) [] 2))
        (wrong-depth (make-byte-code 257 (unibyte-string 84 135) [] 3)))
    (should (eq (nelisp-bytecode-jit--decode-unary add1) 'add1))
    (should (eq (nelisp-bytecode-jit--decode-unary sub1) 'sub1))
    (should-not (nelisp-bytecode-jit--decode-unary unknown))
    (should-not (nelisp-bytecode-jit--decode-unary after-return))
    (should-not (nelisp-bytecode-jit--decode-unary wrong-depth))))

(ert-deftest nelisp-bytecode-jit/host-bytecode-fixture-has-emacs-semantics ()
  (let ((add1 (byte-compile '(lambda (x) (1+ x))))
        (sub1 (byte-compile '(lambda (x) (1- x)))))
    (should (eq (nelisp-bytecode-jit--decode-unary add1) 'add1))
    (should (eq (nelisp-bytecode-jit--decode-unary sub1) 'sub1))
    (should (= (funcall add1 41) 42))
    (should (= (funcall sub1 -41) -42))
    (should (= (funcall add1 (ash 1 100)) (1+ (ash 1 100))))
    (should (= (funcall sub1 (- (ash 1 100)))
               (1- (- (ash 1 100)))))))

(ert-deftest nelisp-bytecode-jit/rejects-extended-stack-ref-opcodes-6-and-7 ()
  (dolist (code (list (unibyte-string 6 1 135)
                      (unibyte-string 7 1 2 135)))
    (let ((function (make-byte-code 257 code [] 4)))
      (should-not (nelisp-bytecode-jit--decode-instructions code []))
      (should-not (nelisp-bytecode-jit--decode-ir function)))))

(ert-deftest nelisp-bytecode-jit/rejects-branch-into-fetch2-operand-before-native-path ()
  ;; Opcode 15 is compact varref7: its FETCH2 bytes are operands, not ops.
  (let* ((code (unibyte-string 130 4 0 15 0 0 135))
         (function (make-byte-code 257 code [] 2))
         (nelisp-bytecode-jit--native-call-count 0)
         (nelisp-bytecode-jit--hot-counts (make-hash-table :test 'eq)))
    (should (eq (plist-get (nelisp-bytecode-ir-validate code [] 1) :status)
                'malformed))
    (should-not (nelisp-bytecode-jit--decode-instructions code []))
    (should-not (nelisp-bytecode-jit--decode-ir function))
    (should-not (nelisp-bytecode-jit-test--dispatch-prepared function 1))
    (should (= nelisp-bytecode-jit--native-call-count 0))))

(ert-deftest nelisp-bytecode-jit/gnu-emacs-31-binary-add-stream-is-exact ()
  (let* ((function (byte-compile '(lambda (x y) (+ x y))))
         (code (aref function 1)))
    (should (= (aref function 0) 514))
    (should (equal (string-to-list code) '(1 1 92 135)))
    (should (equal (aref function 2) []))
    (should (= (aref function 3) 4))
    (should (eq (nelisp-bytecode-jit--decode-binary-add function) 'add))
    (should (= (funcall function 19 23) 42))
    (should-not
     (nelisp-bytecode-jit--decode-binary-add
      (make-byte-code 514 (unibyte-string 1 1 92 134) [] 4)))
    (should-not
     (nelisp-bytecode-jit--decode-binary-add
      (make-byte-code 514 (unibyte-string 1 1 93 135) [] 4)))
    (should (eq (nelisp-bytecode-jit--decode-binary-add
                 (make-byte-code 514 (unibyte-string 1 1 92 135) [0] 4))
                'add))
    (should-not
     (nelisp-bytecode-jit--decode-binary-add
      (make-byte-code 514 (unibyte-string 1 1 92 135) [] 5)))))

(ert-deftest nelisp-bytecode-jit/bytecode-add-ignores-function-cell-overrides ()
  (let* ((function (byte-compile '(lambda (x y) (+ x y))))
         (original (symbol-function '+)))
    (unwind-protect
        (progn
          (fset '+ (lambda (&rest _args) 999))
          (should (= (funcall function 19 23) 42)))
      (fset '+ original))))

(ert-deftest nelisp-bytecode-jit/binary-hotness-requires-interior-fixnums ()
  (let* ((function (byte-compile '(lambda (x y) (+ x y))))
         (nelisp-bytecode-jit-threshold 2)
         (nelisp-bytecode-jit--hot-counts (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--native-call-count 0)
         (nelisp-bytecode-jit--interpreter-fallback-count 0)
         (seen nil))
    (cl-letf (((symbol-function 'nelisp-native-load-raw-call)
               (lambda (_handle arguments)
                 (setq seen arguments)
                 (+ (car arguments) (cadr arguments))))
              ((symbol-function 'nelisp-bytecode-jit--compile-ir)
               (lambda (_function ir)
                 (nelisp-bytecode-jit-test--candidate-handle ir))))
      (should-not (nelisp-bytecode-jit-test--dispatch-prepared function 20 22))
      (should (equal (nelisp-bytecode-jit-test--dispatch-prepared function 19 23)
                     [t 42]))
      (should (equal seen '(19 23)))
      (should (= nelisp-bytecode-jit--interpreter-fallback-count 1))
      (should (= nelisp-bytecode-jit--native-call-count 1))
      (should-not
       (nelisp-bytecode-jit-test--dispatch-prepared function 1.5 2))
      (should-not
       (nelisp-bytecode-jit-test--dispatch-prepared function (ash 1 100) 1))
      (should-not
       (nelisp-bytecode-jit-test--dispatch-prepared
        function most-positive-fixnum 1))
      (let ((near-miss (byte-compile '(lambda (x y) (+ x (1+ y))))))
        (should-not (nelisp-bytecode-jit--decode-binary-add near-miss))
        (should-not (nelisp-bytecode-jit-test--dispatch-prepared near-miss 20 22))))))

(ert-deftest nelisp-bytecode-jit/gnu-emacs-31-branch-stream-is-exact-and-safe ()
  (let* ((function (byte-compile '(lambda (x) (if (= x 0) 17 23))))
         (code (aref function 1)))
    (should (equal (string-to-list code)
                   '(137 192 85 131 8 0 193 135 194 135)))
    (should (equal (aref function 2) [0 17 23]))
    (should (equal (nelisp-bytecode-jit--decode-branch function)
                   '(branch-eq-zero 17 23)))
    (should (= (funcall function 0) 17))
    (should (= (funcall function 1) 23))
    (should (= (funcall function -9) 23))))

(ert-deftest nelisp-bytecode-jit/branch-decoder-rejects-near-misses ()
  (let ((function (byte-compile '(lambda (x) (if (= x 0) 17 23)))))
    (should-not
     (nelisp-bytecode-jit--decode-branch
      (make-byte-code 257 (copy-sequence (aref function 1))
                      [0 17 (ash 1 100)] 3)))
    (should-not
     (nelisp-bytecode-jit--decode-branch
      (make-byte-code 257 (unibyte-string 137 192 85 131 8 0 193 135 194 134)
                      [0 17 23] 3)))
    (should-not
     (nelisp-bytecode-jit--decode-branch
      (make-byte-code 257
                      (concat (aref function 1) (unibyte-string 84))
                      [0 17 23] 3)))))

(ert-deftest nelisp-bytecode-jit/branch-lowering-is-hot-and-side-effect-free ()
  (let* ((function (byte-compile '(lambda (x) (if (= x 0) 17 23))))
         (nelisp-bytecode-jit-threshold 2)
         (nelisp-bytecode-jit--hot-counts (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--native-call-count 0)
         (nelisp-bytecode-jit--interpreter-fallback-count 0)
         (seen nil))
    (cl-letf (((symbol-function 'nelisp-bytecode-jit--compile-ir)
               (lambda (_function ir)
                 (setq seen ir)
                 (nelisp-bytecode-jit-test--candidate-handle ir)))
              ((symbol-function 'nelisp-native-load-raw-call)
               (lambda (_handle arguments)
                 (if (= (car arguments) 0) 17 23))))
      (should-not (nelisp-bytecode-jit-test--dispatch-prepared function 0))
      (should (equal (nelisp-bytecode-jit-test--dispatch-prepared function 5) [t 23]))
      (should (equal (plist-get seen :expression) '(if (= x0 0) 17 23)))
      (should (= nelisp-bytecode-jit--interpreter-fallback-count 1))
      (should (= nelisp-bytecode-jit--native-call-count 1)))))

(ert-deftest nelisp-bytecode-jit/threshold-keeps-cold-calls-in-fallback ()
  (let* ((function (make-byte-code 257 (unibyte-string 83 135) [] 2))
         (nelisp-bytecode-jit-threshold 2)
         (nelisp-bytecode-jit--hot-counts (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--native-call-count 0)
         (nelisp-bytecode-jit--interpreter-fallback-count 0))
    (cl-letf (((symbol-function 'nelisp-bytecode-jit--compile-ir)
               (lambda (_function ir)
                 (nelisp-bytecode-jit-test--candidate-handle ir)))
              ((symbol-function 'nelisp-native-load-raw-call)
               (lambda (_handle arguments) (1+ (car arguments)))))
      (should-not (nelisp-bytecode-jit-test--dispatch-prepared function 4))
      (should (equal (nelisp-bytecode-jit-test--dispatch-prepared function 8)
                     [t 9]))
      (should (= nelisp-bytecode-jit--interpreter-fallback-count 1))
      (should (= nelisp-bytecode-jit--native-call-count 1)))))

(ert-deftest nelisp-bytecode-jit/fixnum-boundaries-stay-in-the-vm ()
  (let ((nelisp-bytecode-jit--hot-counts (make-hash-table :test 'eq)))
    (should-not
     (nelisp-bytecode-jit-test--dispatch-prepared
      (make-byte-code 257 (unibyte-string 84 135) [] 2)
      most-positive-fixnum))
    (should-not
     (nelisp-bytecode-jit-test--dispatch-prepared
      (make-byte-code 257 (unibyte-string 83 135) [] 2)
      most-negative-fixnum))))

(ert-deftest nelisp-bytecode-jit/caches-by-function-and-decoded-operation ()
  (let* ((function (byte-compile '(lambda (x) (1+ x))))
        (nelisp-bytecode-jit--handles (make-hash-table :test 'eq))
        (nelisp-bytecode-jit--compile-count 0)
        (next-entry 4096))
    (cl-letf (((symbol-function 'nelisp-native-load-raw-compile-file)
               (lambda (&rest _args) t))
              ((symbol-function 'nelisp-native-load-raw-artifact)
               (lambda (&rest _args)
                 (setq next-entry (1+ next-entry))
                 (list :entry next-entry :arity 1 :abi 'integer
                       :param-repr 'raw-i64 :return-repr 'raw-i64))))
      (let ((first (nelisp-bytecode-jit--compile-unary function 'add1))
            (again (nelisp-bytecode-jit--compile-unary function 'add1)))
        (should (eq first again))
        (aset (aref function 1) 0 83)
        (should (eq (nelisp-bytecode-jit--decode-unary function) 'sub1))
        (should-not (eq first
                        (nelisp-bytecode-jit--compile-unary function 'sub1)))
        (should (= nelisp-bytecode-jit--compile-count 2))
        (should (= (hash-table-count nelisp-bytecode-jit--handles) 1))))))

(ert-deftest nelisp-bytecode-jit/generic-ir-retains-offsets-and-rejects-invalid-cfg ()
  (let* ((function (byte-compile '(lambda (x y) (- x y))))
         (ir (nelisp-bytecode-jit--decode-ir function)))
    (should (equal (plist-get ir :expression) '(- x0 x1)))
    (should (equal (mapcar (lambda (instruction) (aref instruction 0))
                           (plist-get ir :instructions))
                   '(0 1 2 3)))
    (should-not
     (nelisp-bytecode-jit--decode-ir
      (make-byte-code 514 (unibyte-string 1 1 90 131 0 0 135) [] 4)))
    (should-not
     (nelisp-bytecode-jit--decode-ir
      (make-byte-code 514 (unibyte-string 1 1 50 135) [] 4)))
    (should-not
     (nelisp-bytecode-jit--decode-ir
      (make-byte-code 514 (unibyte-string 1 1 90 135 84) [] 4))))
  )

(ert-deftest nelisp-bytecode-jit/gnu-emacs-31-object-predicate-family-decodes-to-boxed-ir ()
  (let ((nelisp-bytecode-jit--deferred-preparation-enabled t)
        (nelisp-bytecode-jit--native-call-count 0)
        (cases '((symbolp 57 symbol 42)
                 (consp 58 (a) nil)
                 (stringp 59 "text" symbol)
                 (listp 60 (a) 42))))
    (dolist (case cases)
      (let* ((operator (nth 0 case))
             (opcode (nth 1 case))
             (accepted (nth 2 case))
             (function (byte-compile `(lambda (x) (,operator x))))
             (ir (nelisp-bytecode-jit--decode-ir function)))
        (should (equal (string-to-list (aref function 1))
                       (list opcode 135)))
        (should (equal (plist-get ir :expression)
                       (list operator 'x0)))
        (should (nelisp-bytecode-jit--safe-ir-p ir (list accepted)))
        (should (eq (funcall function accepted) t))
        (should (null (funcall function (nth 3 case))))
        (should-not
         (nelisp-bytecode-jit--runtime-dispatch function accepted))
        (should (= nelisp-bytecode-jit--native-call-count 0))))))

(ert-deftest nelisp-bytecode-jit/predicate-ir-rejects-underflow-and-trailing-code ()
  (dolist (code (list (unibyte-string 90 58 135)
                      (unibyte-string 1 58 135 84)))
    (should-not (nelisp-bytecode-jit--decode-ir
                 (make-byte-code 257 code [] 2)))))

(ert-deftest nelisp-bytecode-jit/boxed-predicate-ir-is-an-exact-structural-subset ()
  (dolist (case '((symbolp 57) (consp 58) (stringp 59) (listp 60)))
    (let* ((predicate (car case))
           (opcode (cadr case))
           (function (byte-compile `(lambda (x) (,predicate x))))
           (ir (nelisp-bytecode-jit--decode-boxed-predicate function)))
      (should (eq (plist-get ir :predicate) predicate))
      (should (= (plist-get ir :opcode) opcode))
      (should (= (plist-get ir :arity) 1))))
  (dolist (function
           (list (byte-compile '(lambda (x) (atom x)))
                 (byte-compile '(lambda (x) (if x (consp x) nil)))
                 (make-byte-code 513 (unibyte-string 58 135) [] 2)
                 (make-byte-code 257 (unibyte-string 58 135 84) [] 2)
                 (make-byte-code 257 (unibyte-string 90 58 135) [] 2)
                 (make-byte-code 257 (unibyte-string 58 135) [1] 2)))
    (should-not (nelisp-bytecode-jit--decode-boxed-predicate function))))

(ert-deftest nelisp-bytecode-jit/boxed-predicate-prepare-caches-safe-handle-only ()
  (let* ((function (byte-compile '(lambda (x) (stringp x))))
         (unsupported (byte-compile '(lambda (x) (atom x))))
         (nelisp-bytecode-jit-threshold 1)
         (nelisp-bytecode-jit--deferred-preparation-enabled t)
         (nelisp-bytecode-jit--handles (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--hot-counts (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--compile-count 0)
         (nelisp-bytecode-jit--native-call-count 0)
         (compile-calls 0)
         (boxed-calls 0)
         (handle '(:entry 4096 :arity 1 :abi boxed
                   :param-repr sexp-ptr :return-repr raw-bool)))
    (cl-letf (((symbol-function 'nelisp-artifact-compile-file)
               (lambda (source artifact &rest args)
                 (setq compile-calls (1+ compile-calls))
                 (should (string-suffix-p ".neln" artifact))
                 (should (eq (car (last args)) 'neln))
                 (with-temp-buffer
                   (insert-file-contents source)
                   (should (equal (buffer-string)
                                  ";;; -*- lexical-binding: t; -*-\n(defun nl_bc_jit_entry (x0) (stringp x0))\n")))))
              ((symbol-function 'nelisp-native-load-artifact)
               (lambda (_artifact name)
                 (should (equal name "nl_bc_jit_entry"))
                 handle))
              ((symbol-function 'nelisp-native-load-call)
               (lambda (actual args)
                 (setq boxed-calls (1+ boxed-calls))
                 (should (eq actual handle))
                 (if (stringp (car args)) t nil))))
      ;; Before preparation, real Lisp behavior remains in the VM.
      (should (eq (funcall function "a") t))
      (should (null (funcall function 17)))
      (should-not (nelisp-bytecode-jit--runtime-dispatch function "a"))
      (should (= compile-calls 0))
      (should-not (nelisp-bytecode-jit-prepare unsupported))
      (should-not (nelisp-bytecode-jit-test--dispatch-prepared unsupported '(a)))
      (should (eq (nelisp-bytecode-jit-prepare function) handle))
      (should (eq (nelisp-bytecode-jit-prepare function) handle))
      (should (= compile-calls 1))
      (should (= nelisp-bytecode-jit--compile-count 1))
      (should (equal (nelisp-bytecode-jit-test--dispatch-prepared function "a")
                     [t t]))
      (should (equal (nelisp-bytecode-jit-test--dispatch-prepared function 17)
                     [t nil]))
      (should (= boxed-calls 2))
      (should (= nelisp-bytecode-jit--native-call-count 2)))))

(ert-deftest nelisp-bytecode-jit/unboxable-object-predicates-fall-back-before-native-call ()
  (let* ((consp-function (byte-compile '(lambda (x) (consp x))))
         (listp-function (byte-compile '(lambda (x) (listp x))))
         (symbolp-function (byte-compile '(lambda (x) (symbolp x))))
         (functions (list consp-function listp-function symbolp-function))
         (nelisp-bytecode-jit--handles (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--hot-counts (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--compile-count 0)
         (nelisp-bytecode-jit--native-call-count 0)
         (native-calls 0)
         (handle '(:entry 4096 :arity 1 :abi boxed
                   :param-repr sexp-ptr :return-repr raw-bool))
         (cycle (list 'a)))
    (setcdr cycle cycle)
    (cl-letf (((symbol-function 'nelisp-artifact-compile-file)
               (lambda (&rest _args) nil))
              ((symbol-function 'nelisp-native-load-artifact)
               (lambda (&rest _args) handle))
              ((symbol-function 'nelisp-native-load-call)
               (lambda (&rest _args)
                 (setq native-calls (1+ native-calls))
                 (error "unsupported values must never enter the native loader"))))
      (dolist (function functions)
        (should (nelisp-bytecode-jit-prepare function)))
      (dolist (case `((,symbolp-function ,(make-symbol "jit-uninterned"))
                      (,consp-function (a . b))
                      (,listp-function (a . b))
                      (,consp-function ,cycle)
                      (,listp-function ,cycle)
                      (,symbolp-function [a])))
        (should-not (nelisp-bytecode-jit-test--dispatch-prepared
                     (car case) (cadr case)))
        ;; The caller's ordinary VM execution remains authoritative.
        (funcall (car case) (cadr case)))
      (should (= native-calls 0))
      (should (= nelisp-bytecode-jit--native-call-count 0)))))

(ert-deftest nelisp-bytecode-jit/boxed-predicates-dispatch-safe-symbols-and-lists ()
  (let* ((cases (list (cons 'symbolp
                            (byte-compile '(lambda (x) (symbolp x))))
                      (cons 'consp
                            (byte-compile '(lambda (x) (consp x))))
                      (cons 'listp
                            (byte-compile '(lambda (x) (listp x))))))
         (nelisp-bytecode-jit-threshold 1)
         (nelisp-bytecode-jit--handles (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--hot-counts (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--compile-count 0)
         (nelisp-bytecode-jit--native-call-count 0)
         (native-calls 0)
         current-predicate)
    (cl-letf (((symbol-function 'nelisp-artifact-compile-file)
               (lambda (source _artifact &rest _args)
                 (with-temp-buffer
                   (insert-file-contents source)
                   (goto-char (point-min))
                   (when (re-search-forward "(\\(symbolp\\|consp\\|listp\\) x0)" nil t)
                     (setq current-predicate (intern (match-string 1)))))))
              ((symbol-function 'nelisp-native-load-artifact)
               (lambda (&rest _args)
                 (list :entry 4096 :arity 1 :abi 'boxed
                       :param-repr 'sexp-ptr :return-repr 'raw-bool
                       :predicate current-predicate)))
              ((symbol-function 'nelisp-native-load-call)
               (lambda (handle arguments)
                 (setq native-calls (1+ native-calls))
                 (funcall (plist-get handle :predicate) (car arguments)))))
      (dolist (case cases)
        (let* ((predicate (car case))
               (function (cdr case))
               (argument (if (eq predicate 'symbolp) 'jit-interned '(a b)))
               (vm-value (funcall function argument)))
          (should (nelisp-bytecode-jit-prepare function))
          (should (equal (nelisp-bytecode-jit-test--dispatch-prepared
                          function argument)
                         (vector t vm-value)))
          (should (equal vm-value (funcall function argument)))))
      (should (= native-calls 3))
      (should (= nelisp-bytecode-jit--native-call-count 3))
      (let* ((nested '(a (b c)))
             (consp-nested
              (nelisp-bytecode-jit-test--dispatch-prepared
               (cdr (assq 'consp cases)) nested))
             (listp-nested
              (nelisp-bytecode-jit-test--dispatch-prepared
               (cdr (assq 'listp cases)) nested)))
        (should-not consp-nested)
        (should-not listp-nested)
        (should (= native-calls 3))
        (should (= nelisp-bytecode-jit--native-call-count 3))
        (should (funcall (cdr (assq 'consp cases)) nested))
        (should (funcall (cdr (assq 'listp cases)) nested))
        (should (= native-calls 3))))))

(ert-deftest nelisp-bytecode-jit/boxed-list-dispatch-budget-is-bounded ()
  (should (nelisp-bytecode-jit--boxed-argument-supported-p
           (make-list 256 'item)))
  (should-not (nelisp-bytecode-jit--boxed-argument-supported-p
               (make-list 257 'item))))

(ert-deftest nelisp-bytecode-jit/prepare-failure-cleans-artifacts-by-default ()
  (let ((process-environment (copy-sequence process-environment))
        source artifact manifest
        (function (byte-compile '(lambda (x) (consp x)))))
    (setenv "NELISP_JIT_DIAGNOSTIC_DIR" nil)
    (cl-letf (((symbol-function 'nelisp-artifact-compile-file)
               (lambda (src out &rest _args)
                 (setq source src artifact out manifest (concat out ".manifest.el"))
                 (with-temp-file out (insert "artifact"))
                 (with-temp-file manifest (insert "(:body-offset 8)"))))
              ((symbol-function 'nelisp-native-load-artifact)
               (lambda (&rest _args) (error ":no-body-offset mocked load failure"))))
      (should-error (nelisp-bytecode-jit-prepare function)))
    (should source)
    (should-not (file-exists-p source))
    (should-not (file-exists-p artifact))
    (should-not (file-exists-p manifest))))

(ert-deftest nelisp-bytecode-jit/prepare-failure-captures-opt-in-diagnostics ()
  (let* ((diagnostic-dir (make-temp-file "nelisp-jit-diagnostic-test-" t))
         (process-environment (copy-sequence process-environment))
         source artifact manifest)
    (unwind-protect
        (let ((function (byte-compile '(lambda (x) (consp x)))))
          (setenv "NELISP_JIT_DIAGNOSTIC_DIR" diagnostic-dir)
          (cl-letf (((symbol-function 'nelisp-artifact-compile-file)
                     (lambda (src out &rest _args)
                       (setq source src artifact out manifest (concat out ".manifest.el"))
                       (with-temp-file out (insert "artifact"))
                       (with-temp-file manifest
                         (prin1 '( :body-offset 8 :param-repr sexp-ptr
                                   :return-repr raw-bool)
                                (current-buffer)))))
                    ((symbol-function 'nelisp-native-load-artifact)
                     (lambda (&rest _args)
                       (error ":no-body-offset mocked load failure"))))
            (should-error (nelisp-bytecode-jit-prepare function)))
          (should (file-exists-p source))
          (should (file-exists-p artifact))
          (should (file-exists-p manifest))
          (let* ((records (directory-files diagnostic-dir t "^failure-.*\\.el$"))
                 (record (with-temp-buffer
                           (insert-file-contents (car records))
                           (read (current-buffer)))))
            (should (= (length records) 1))
            (should (eq (plist-get record :ir-status) 'valid))
            (should (plist-get record :ir-eligible))
            (should (equal (plist-get record :opcode-bytes) '(58 135)))
            (should (string-match-p ":no-body-offset"
                                    (plist-get record :error)))
            (should (= (plist-get record :manifest-body-offset) 8))
            (should (eq (plist-get record :manifest-param-repr) 'sexp-ptr))
            (should (eq (plist-get record :manifest-return-repr) 'raw-bool))))
      (setenv "NELISP_JIT_DIAGNOSTIC_DIR" nil)
      (delete-directory diagnostic-dir t))))

(ert-deftest nelisp-bytecode-jit/runtime-dispatch-failure-captures-opt-in-diagnostics ()
  (let* ((diagnostic-dir (make-temp-file "nelisp-jit-runtime-diagnostic-" t))
         (process-environment (copy-sequence process-environment))
         (function (byte-compile '(lambda (x) (+ x 1))))
         (nelisp-bytecode-jit-threshold 1)
         (nelisp-bytecode-jit--deferred-preparation-enabled t)
         (nelisp-bytecode-jit--hot-counts (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--pending-queue nil)
         (nelisp-bytecode-jit--pending-identities (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--compile-failures (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--dispatch-active nil)
         (nelisp-bytecode-jit--interpreter-fallback-count 0))
    (unwind-protect
        (progn
          (setenv "NELISP_JIT_DIAGNOSTIC_DIR" diagnostic-dir)
          (cl-letf (((symbol-function 'nelisp-native-load-raw-compile-file)
                     (lambda (&rest _)
                       (error "mock raw compiler failure")))
                    ((symbol-function 'nelisp-native-load-raw-artifact)
                     (lambda (&rest _)
                       (error "raw artifact load should not be reached"))))
            (should-not (nelisp-bytecode-jit--runtime-dispatch function 4))
            (should (= (nelisp-bytecode-jit-drain-pending) 1)))
          (should (= nelisp-bytecode-jit--interpreter-fallback-count 1))
          (let* ((records (directory-files diagnostic-dir t "^failure-.*\\.el$"))
                 (record (with-temp-buffer
                           (insert-file-contents (car records))
                           (read (current-buffer)))))
            (should (= (length records) 1))
            (should (eq (plist-get record :kind)
                        'nelisp-bytecode-jit-prepare-failure))
            (should (equal (plist-get record :function-fingerprint)
                           (nelisp-bytecode-jit--function-payload-fingerprint
                            function)))
            (should (plist-get record :ir-expression))
            (should (eq (plist-get record :compile-phase) 'artifact-compile))
            (should (file-exists-p (plist-get record :source-path)))
            (should (file-exists-p (plist-get record :artifact-path)))
            (should (string-match-p "mock raw compiler failure"
                                    (plist-get record :error)))
            (should (integerp
                     (plist-get (plist-get record :stage-timings)
                                :artifact-compile-us)))
            (should (= (plist-get (plist-get record :stage-timings)
                                  :artifact-load-us)
                       0))
            (should (equal (plist-get record :expression-fingerprint)
                           (plist-get record :function-fingerprint)))))
      (setenv "NELISP_JIT_DIAGNOSTIC_DIR" nil)
      (delete-directory diagnostic-dir t))))

(ert-deftest nelisp-bytecode-jit/generic-stage-timings-cover-aot-pipeline ()
  (let* ((diagnostic-dir (make-temp-file "nelisp-jit-stage-timing-" t))
         (process-environment (copy-sequence process-environment))
         (function (byte-compile '(lambda (x) (1+ x))))
         (nelisp-bytecode-jit-threshold 1)
         (nelisp-bytecode-jit--deferred-preparation-enabled t)
         (nelisp-bytecode-jit--hot-counts (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--pending-queue nil)
         (nelisp-bytecode-jit--pending-identities (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--compile-failures (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--dispatch-active nil)
         (nelisp-bytecode-jit--native-call-count 0)
         (nelisp-bytecode-jit--compile-count 0))
    (unwind-protect
        (progn
          (setenv "NELISP_JIT_DIAGNOSTIC_DIR" diagnostic-dir)
          (cl-letf (((symbol-function 'nelisp-native-load-raw-compile-file)
                     (lambda (_source artifact &rest _args)
                       (with-temp-file artifact (insert "artifact"))))
                    ((symbol-function 'nelisp-native-load-raw-artifact)
                     (lambda (&rest _args)
                       (nelisp-bytecode-jit-test--candidate-handle
                        (nelisp-bytecode-jit--decode-ir function))))
                    ((symbol-function 'nelisp-native-load-raw-call)
                     (lambda (_handle _arguments) 42)))
            (should (equal (nelisp-bytecode-jit-test--dispatch-prepared function 41)
                           [t 42])))
          (let* ((status (nelisp-bytecode-jit-status))
                 (timings (plist-get status :last-stage-timings)))
            (should (equal (plist-get status :last-expression-fingerprint)
                           (secure-hash 'sha256
                                        (prin1-to-string
                                         (list (aref function 0) (aref function 1)
                                               (aref function 2) (aref function 3))))))
            (dolist (stage '(:decode-ir-us :source-generation-us
                             :artifact-compile-us :artifact-load-us
                             :native-call-us))
              (should (integerp (plist-get timings stage)))
              (should (>= (plist-get timings stage) 0))))
          (should (= nelisp-bytecode-jit--native-call-count 1)))
      (setenv "NELISP_JIT_DIAGNOSTIC_DIR" nil)
      (delete-directory diagnostic-dir t))))

(ert-deftest nelisp-bytecode-jit/timing-disabled-does-not-read-clock ()
  (let* ((process-environment (copy-sequence process-environment))
         (function (byte-compile '(lambda (x) (1+ x))))
         (nelisp-bytecode-jit-threshold 1)
         (nelisp-bytecode-jit--hot-counts (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--dispatch-active nil))
    (setenv "NELISP_JIT_DIAGNOSTIC_DIR" nil)
    (cl-letf (((symbol-function 'float-time)
               (lambda (&rest _) (error "clock sampled with timing disabled")))
              ((symbol-function 'nelisp-native-load-raw-compile-file)
               (lambda (_source artifact &rest _args)
                 (with-temp-file artifact (insert "artifact"))))
              ((symbol-function 'nelisp-native-load-raw-artifact)
               (lambda (&rest _args)
                 (nelisp-bytecode-jit-test--candidate-handle
                  (nelisp-bytecode-jit--decode-ir function))))
              ((symbol-function 'nelisp-native-load-raw-call)
               (lambda (_handle _arguments) 42)))
      (should (equal (nelisp-bytecode-jit-test--dispatch-prepared function 41)
                     [t 42])))))

(ert-deftest nelisp-bytecode-jit/lowers-backward-loop-from-cfg-stack-state ()
  (let* ((function
          (byte-compile
           '(lambda (n) (let ((i 0)) (while (< i n) (setq i (1+ i))) i))))
         (ir (nelisp-bytecode-jit--decode-ir function)))
    (should ir)
    (should (equal (plist-get (plist-get ir :loop) :header) 1))
    (should (equal (plist-get (plist-get ir :loop) :backedge) 8))
    (should (equal (plist-get ir :expression)
                   '(let ((nelisp-bc-loop-s0 0) (nelisp-bc-loop-s1 x0))
                      (while (< nelisp-bc-loop-s0 nelisp-bc-loop-s1)
                        (let ((nelisp-bc-loop-next0
                               (1+ nelisp-bc-loop-s0)))
                          (setq nelisp-bc-loop-s0 nelisp-bc-loop-next0)))
                      nelisp-bc-loop-s0)))
    (let* ((aot-form (nelisp-bytecode-jit--aot-form
                      (plist-get ir :expression)))
           (body (nth 2 (nth 2 aot-form))))
      (should (equal (cadar (cadr body))
                     '(+ nelisp-bc-loop-s0 1))))
    (dolist (case '((-4 . 0) (0 . 0) (1 . 1) (9 . 9)))
      (should (= (funcall function (car case)) (cdr case)))
      (should (nelisp-bytecode-jit--safe-ir-p ir (list (car case)))))
    (should-not
     (nelisp-bytecode-jit--safe-ir-p ir (list most-positive-fixnum)))))

(ert-deftest nelisp-bytecode-jit/loop-compare-generalizes-without-byte-offset-patterns ()
  (let* ((function
          (byte-compile
           '(lambda (n) (let ((i 0)) (while (<= i n) (setq i (1+ i))) i))))
         (ir (nelisp-bytecode-jit--decode-ir function)))
    (should ir)
    (should (eq (car (nth 1 (nth 2 (plist-get ir :expression)))) '<=))
    (dolist (case '((-4 . 0) (0 . 1) (1 . 2) (9 . 10)))
      (should (= (funcall function (car case)) (cdr case)))
      (should (nelisp-bytecode-jit--safe-ir-p ir (list (car case)))))))

(ert-deftest nelisp-bytecode-jit/rejects-stack-changing-backedge-and-falls-back ()
  (let* ((function
          (byte-compile
           '(lambda (n) (let ((i 0)) (while (< i n) (setq i (1+ i))) i))))
         (code (copy-sequence (aref function 1)))
         (broken (progn (aset code 7 137)
                        (make-byte-code (aref function 0) code
                                        (aref function 2) (aref function 3))))
         (nelisp-bytecode-jit-threshold 1)
         (nelisp-bytecode-jit--native-call-count 0)
         (nelisp-bytecode-jit--hot-counts (make-hash-table :test 'eq)))
    (should-not (nelisp-bytecode-jit--decode-ir broken))
    (should-not (nelisp-bytecode-jit-test--dispatch-prepared broken 9))
    (should (= nelisp-bytecode-jit--native-call-count 0))))

(ert-deftest nelisp-bytecode-jit/backward-loop-dispatch-counts-native-entry ()
  (let* ((function
          (byte-compile
           '(lambda (n) (let ((i 0)) (while (< i n) (setq i (1+ i))) i))))
         (nelisp-bytecode-jit-threshold 1)
         (nelisp-bytecode-jit--hot-counts (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--native-call-count 0)
         (seen-ir nil))
    (cl-letf (((symbol-function 'nelisp-bytecode-jit--compile-ir)
               (lambda (_function ir)
                 (setq seen-ir ir)
                 (nelisp-bytecode-jit-test--candidate-handle ir)))
              ((symbol-function 'nelisp-native-load-raw-call)
               (lambda (handle arguments)
                 (should (equal (plist-get handle :abi) 'integer))
                 (funcall function (car arguments)))))
      (should (equal (nelisp-bytecode-jit-test--dispatch-prepared function 9)
                     [t 9]))
      (should (plist-get seen-ir :loop))
      (should (= nelisp-bytecode-jit--native-call-count 1)))))

(ert-deftest nelisp-bytecode-jit/eq-ir-admits-tested-boxed-identity-classes ()
  (let* ((function (byte-compile '(lambda (x y) (eq x y))))
         (ir (nelisp-bytecode-jit--decode-ir function)))
    (should (equal (string-to-list (aref function 1)) '(1 1 61 135)))
    (should (equal (plist-get ir :expression) '(eq x0 x1)))
    (should (nelisp-bytecode-jit--boxed-eq-ir-p ir))
    (dolist (arguments '((nil nil) (t t) (19 19)
                         (same-symbol same-symbol) ((a) (a))
                         ("text" "text")))
      (should (nelisp-bytecode-jit--safe-ir-p ir arguments)))
    (should (nelisp-bytecode-jit--safe-ir-p
             ir (list (1- most-positive-fixnum) 1)))
    (should-not (nelisp-bytecode-jit--safe-ir-p
                 ir (list (make-symbol "loose") 'loose)))
    (should-not (nelisp-bytecode-jit--safe-ir-p ir '(same-symbol 1.5)))
    (should-not (nelisp-bytecode-jit--safe-ir-p ir (list [a] [a])))))

(ert-deftest nelisp-bytecode-jit/host-eq-parity-cases-pin-opcode-and-identity-results ()
  (let* ((function (byte-compile '(lambda (x y) (eq x y))))
         (same-cons (list 'a)))
    (should (equal (aref function 0) 514))
    (should (equal (string-to-list (aref function 1)) '(1 1 61 135)))
    (should (equal
             (list (funcall function 'foo 'foo)
                   (funcall function 'foo 'bar)
                   (funcall function nil nil)
                   (funcall function 19 19)
                   (funcall function 19 20)
                   (funcall function same-cons same-cons)
                   (funcall function (list 'a) (list 'a))
                   (funcall function 'a same-cons))
             '(t nil t t nil t nil nil)))))

(ert-deftest nelisp-bytecode-jit/eq-dispatch-preserves-tested-identity-classes ()
  (let* ((function (byte-compile '(lambda (x y) (eq x y))))
         (nelisp-bytecode-jit-threshold 1)
         (nelisp-bytecode-jit--handles (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--hot-counts (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--native-call-count 0)
         (native-arguments nil)
         (same-cons (list 'alpha))
         (other-cons (list 'alpha))
         (same-string (copy-sequence "text"))
         (other-string (copy-sequence "text")))
    (cl-letf (((symbol-function 'nelisp-bytecode-jit--compile-ir)
               (lambda (_function ir)
                 (should (nelisp-bytecode-jit--boxed-eq-ir-p ir))
                 (nelisp-bytecode-jit-test--candidate-handle ir)))
              ((symbol-function 'nelisp-native-load-call)
               (lambda (handle arguments)
                 (should (equal (plist-get handle :abi) 'boxed))
                 (setq native-arguments (cons arguments native-arguments))
                 (apply #'eq arguments))))
      (should (equal (nelisp-bytecode-jit-test--dispatch-prepared function 'alpha 'alpha)
                     [t t]))
      (should (equal (nelisp-bytecode-jit-test--dispatch-prepared function nil nil)
                     [t t]))
      (should (equal (nelisp-bytecode-jit-test--dispatch-prepared function 19 20)
                     [t nil]))
      (should (equal (nelisp-bytecode-jit-test--dispatch-prepared
                      function same-cons same-cons)
                     [t t]))
      (should (equal (nelisp-bytecode-jit-test--dispatch-prepared
                      function same-cons other-cons)
                     [t nil]))
      (should (equal (nelisp-bytecode-jit-test--dispatch-prepared
                      function same-string same-string)
                     [t t]))
      (should (equal (nelisp-bytecode-jit-test--dispatch-prepared
                      function same-string other-string)
                     [t nil]))
      (should-not
       (nelisp-bytecode-jit-test--dispatch-prepared
        function (make-symbol "loose") 'loose))
      (should (= nelisp-bytecode-jit--native-call-count 7))
      (should (= (length native-arguments) 7)))))

(ert-deftest nelisp-bytecode-jit/eq-native-error-propagates-after-entry ()
  (let* ((function (byte-compile '(lambda (x y) (eq x y))))
         (nelisp-bytecode-jit-threshold 1)
         (nelisp-bytecode-jit--handles (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--hot-counts (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--native-call-count 0)
         (nelisp-bytecode-jit--interpreter-fallback-count 0))
    (cl-letf (((symbol-function 'nelisp-bytecode-jit--compile-ir)
               (lambda (_function ir)
                 (nelisp-bytecode-jit-test--candidate-handle ir)))
              ((symbol-function 'nelisp-native-load-call)
               (lambda (&rest _)
                 (error "simulated boxed-call failure"))))
      (should-error (nelisp-bytecode-jit-test--dispatch-prepared function 'x 'x)
                    :type 'error)
      (should (= nelisp-bytecode-jit--native-call-count 0))
      (should (= nelisp-bytecode-jit--interpreter-fallback-count 0))
      (should-not nelisp-bytecode-jit--dispatch-active))))

(ert-deftest nelisp-bytecode-jit/gnu31-caar-bytecode-lowers-to-boxed-car-chain ()
  (require 'bytecomp)
  (let* ((function (byte-compile '(lambda (x) (car (car x)))))
         (ir (nelisp-bytecode-jit--decode-ir function)))
    (should (= (aref function 0) 257))
    (should (equal (string-to-list (aref function 1)) '(137 64 64 135)))
    (should (equal (secure-hash 'sha256 (aref function 1))
                   "e501504fc7f12b116f506b2370646e43aff5447d1912303c4208341c62e09229"))
    (should
     (equal (secure-hash
             'sha256
             (prin1-to-string
              (list (aref function 0) (aref function 1)
                    (aref function 2) (aref function 3))))
            "54657f49c4d902c5a7c19d4a30e977cb6c49f11c8add17ae6ab0166f845f2643"))
    (should (equal (aref function 2) []))
    (should (= (aref function 3) 2))
    (should (equal (plist-get ir :expression) '(car (car x0))))
    (should (= (nelisp-bytecode-jit--boxed-car-chain-depth ir) 2))
    (should (nelisp-bytecode-jit--boxed-result-ir-p ir))
    (should (nelisp-bytecode-jit--boxed-car-call-supported-p
             ir '(((nelisp-caar-marker)))))
    (should (nelisp-bytecode-jit--boxed-car-call-supported-p ir '((("text")))))
    (should (nelisp-bytecode-jit--boxed-car-call-supported-p ir '(nil)))
    (should-not (nelisp-bytecode-jit--boxed-car-call-supported-p ir '(1)))
    (should-not (nelisp-bytecode-jit--boxed-car-call-supported-p ir '((7))))
    (should (nelisp-bytecode-jit--boxed-car-call-supported-p
             ir '((((nelisp-caar-marker))))))
    (should (nelisp-bytecode-jit--boxed-car-call-supported-p
             ir '(((((nelisp-caar-marker)))))))))

(ert-deftest nelisp-bytecode-jit/caught-runtime-failure-is-queryable-without-io ()
  (let* ((process-environment (copy-sequence process-environment))
         (function (byte-compile '(lambda (x) (+ x 1))))
         (nelisp-bytecode-jit-threshold 1)
         (nelisp-bytecode-jit--deferred-preparation-enabled t)
         (nelisp-bytecode-jit--hot-counts (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--pending-queue nil)
         (nelisp-bytecode-jit--pending-identities (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--compile-failures (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--dispatch-active nil)
         (nelisp-bytecode-jit--interpreter-fallback-count 0)
         (nelisp-bytecode-jit--last-runtime-failure nil))
    (setenv "NELISP_JIT_DIAGNOSTIC_DIR" nil)
    (cl-letf (((symbol-function 'nelisp-native-load-raw-compile-file)
               (lambda (&rest _) (error "mock compile fault"))))
      (should-not (nelisp-bytecode-jit--runtime-dispatch function 4))
      (should (= (nelisp-bytecode-jit-drain-pending) 1)))
    (let* ((status (nelisp-bytecode-jit-status))
           (failure (gethash function nelisp-bytecode-jit--compile-failures))
           (condition (plist-get failure :condition)))
      (should (= (plist-get status :interpreter-fallbacks) 1))
      (should (equal (error-message-string condition) "mock compile fault"))
      (should (eq (plist-get failure :phase) 'artifact-compile))
      (should (stringp (car (plist-get failure :identity)))))))

(ert-deftest nelisp-bytecode-jit/bind-trace-is-written-only-after-caught-failure ()
  (let* ((process-environment (copy-sequence process-environment))
         (directory (make-temp-file "nelisp-jit-bind-trace-" t))
         (trace-file (expand-file-name "binder-arity-trace.el" directory))
         (function (byte-compile '(lambda (x) (+ x 1))))
         (nelisp-bytecode-jit-threshold 1)
         (nelisp-bytecode-jit--deferred-preparation-enabled t)
         (nelisp-bytecode-jit--hot-counts (make-hash-table :test 'eq))
         (nelisp-bytecode-jit--dispatch-active nil)
         (nelisp-bytecode-jit--last-runtime-failure nil)
         (nelisp--last-jit-bind-arity-trace nil))
    (unwind-protect
        (progn
          (setenv "NELISP_JIT_DIAGNOSTIC_DIR" nil)
          (setenv "NELISP_JIT_BIND_TRACE_DIR" directory)
          (cl-letf (((symbol-function 'nelisp-bytecode-jit--compile-ir)
                     (lambda (&rest _)
                       (setq nelisp-bytecode-jit--failure-phase 'artifact-compile)
                       (setq nelisp-bytecode-jit--failure-source "/tmp/jit-probe.el")
                       (setq nelisp--last-jit-bind-arity-trace '(0 1))
                       (signal 'wrong-number-of-arguments '(lambda 1)))))
            (should-not (nelisp-bytecode-jit--runtime-dispatch function 4))
            (should (= (nelisp-bytecode-jit-drain-pending) 1)))
          (should (file-exists-p trace-file))
          (with-temp-buffer
            (insert-file-contents trace-file)
            (let ((record (read (current-buffer))))
              (should (equal (plist-get record :condition)
                             '(wrong-number-of-arguments lambda 1)))
              (should (stringp (plist-get record :fingerprint)))
              (should (eq (plist-get record :phase) 'artifact-compile))
              (should (equal (plist-get record :source) "/tmp/jit-probe.el"))
              (should (equal (plist-get record :required-got) '(0 1)))))
          (should-not (getenv "NELISP_JIT_DIAGNOSTIC_DIR")))
      (delete-directory directory t))))

(provide 'nelisp-bytecode-jit-test)
;;; nelisp-bytecode-jit-test.el ends here
