;;; nelisp-nadvice-parity-smoke.el --- host/VM parity probe for nadvice/oclosure  -*- lexical-binding: t; -*-
;; Evaluated by both GNU Emacs 31 and the standalone binary; the printed
;; transcripts must be identical (see the .sh wrapper).  JIT ledger S6.14.
(require 'cl-lib)
(defmacro np--t (form)
  `(princ (format "%S => %S\n" ',form (condition-case e ,form (error e)))))

;; advice-add / advice-remove / advice-member-p on a named function
(defvar np--log nil)
(defun np--f (x) (push (list 'f x) np--log) (* x 2))
(np--t (np--f 3))
(defun np--around (orig x) (push 'around np--log) (1+ (funcall orig x)))
(np--t (progn (advice-add 'np--f :around #'np--around) (setq np--log nil) (list (np--f 3) (reverse np--log))))
(np--t (and (advice-member-p #'np--around 'np--f) t))
(np--t (advice-member-p #'car 'np--f))
(np--t (progn (advice-remove 'np--f #'np--around) (list (np--f 3) (and (advice-member-p #'np--around 'np--f) t))))
(defun np--before (x) (push (list 'before x) np--log))
(np--t (progn (advice-add 'np--f :before #'np--before) (setq np--log nil) (list (np--f 4) (reverse np--log))))
(np--t (progn (advice-remove 'np--f #'np--before) (np--f 4)))
(defun np--after (x) (push (list 'after x) np--log))
(np--t (progn (advice-add 'np--f :after #'np--after) (setq np--log nil) (list (np--f 5) (reverse np--log))))
(np--t (progn (advice-remove 'np--f #'np--after) (np--f 5)))
(defun np--filter-ret (r) (list 'ret r))
(np--t (progn (advice-add 'np--f :filter-return #'np--filter-ret) (prog1 (np--f 6) (advice-remove 'np--f #'np--filter-ret))))
(defun np--filter-args (args) (list (1+ (car args))))
(np--t (progn (advice-add 'np--f :filter-args #'np--filter-args) (prog1 (np--f 6) (advice-remove 'np--f #'np--filter-args))))
(np--t (progn (advice-add 'np--f :override #'1+) (prog1 (np--f 6) (advice-remove 'np--f #'1+))))
(np--t (progn (advice-add 'np--f :before-while #'cl-evenp) (prog1 (list (np--f 6) (np--f 7)) (advice-remove 'np--f #'cl-evenp))))
;; several pieces of advice, name property, advice-mapc
(np--t (progn
         (advice-add 'np--f :around (lambda (o x) (funcall o (+ x 100))) '((name . np-one)))
         (advice-add 'np--f :filter-return #'list)
         (let ((seen nil))
           (advice-mapc (lambda (f props) (push (list (functionp f) props) seen)) 'np--f)
           (prog1 (list (np--f 1) (and (advice-member-p 'np-one 'np--f) t) (nreverse seen))
             (advice-remove 'np--f 'np-one)
             (advice-remove 'np--f #'list)))))
(np--t (np--f 8))
;; adding the same advice twice keeps one copy
(np--t (progn (advice-add 'np--f :filter-return #'list) (advice-add 'np--f :filter-return #'list)
              (prog1 (np--f 2) (advice-remove 'np--f #'list))))
;; advice on a macro and on an undefined function
(defmacro np--m (x) `(list ,x))
(np--t (progn (advice-add 'np--m :filter-return (lambda (form) `(cons 'adv ,form)))
              (prog1 (macroexpand '(np--m 1)) (advice-remove 'np--m (lambda (form) `(cons 'adv ,form))))))
(np--t (progn (advice-add 'np--undefined :around #'np--around) (prog1 (fboundp 'np--undefined)
                                                                  (advice-remove 'np--undefined #'np--around))))
;; define-advice
(np--t (progn (define-advice np--f (:around (o x) np-da) (* 10 (funcall o x)))
              (prog1 (np--f 2) (advice-remove 'np--f 'np--f@np-da))))
;; add-function on a variable, a (var SYM) place, and remove-function
(defvar np--hook (lambda (x) (list 'orig x)))
(np--t (progn (add-function :around (var np--hook) (lambda (o x) (list 'wrapped (funcall o x))))
              (funcall np--hook 1)))
(np--t (progn (add-function :filter-return (var np--hook) #'reverse) (funcall np--hook 2)))
(defvar np--var-fn (lambda (x) (* x 3)))
(np--t (progn (add-function :around np--var-fn (lambda (o x) (1+ (funcall o x))) '((name . plus1)))
              (list (funcall np--var-fn 2) (advice--p np--var-fn)
                    (and (advice-function-member-p 'plus1 np--var-fn) t))))
(np--t (progn (remove-function np--var-fn 'plus1)
              (list (funcall np--var-fn 2) (advice--p np--var-fn))))
(np--t (let ((fn (lambda (x) (* x 2))))
         (add-function :before-while (var fn) #'cl-evenp)
         (list (funcall fn 4) (funcall fn 3))))
(np--t (advice--p (symbol-function 'car)))
(np--t (advice--p 5))
(np--t (advice--cd*r #'car))
(np--t (let ((fn (lambda (x) x)))
         (add-function :around (var fn) (lambda (o x) (funcall o x)))
         (functionp (advice--cd*r fn))))

;; oclosure-define / oclosure-lambda / accessors / copier
(oclosure-define (np--ocl (:predicate np--ocl-p) (:copier np--ocl-copy (a))) "Doc." a b)
(np--t (let ((o (oclosure-lambda (np--ocl (a 1) (b 2)) (x) (+ x a b))))
         (list (funcall o 10) (np--ocl--a o) (np--ocl--b o) (np--ocl-p o) (np--ocl-p #'car)
               (oclosure-type o) (oclosure-type #'car) (oclosure-type 5)
               (funcall (np--ocl-copy o 100) 10) (np--ocl--a (np--ocl-copy o 100)) (np--ocl--b (np--ocl-copy o 100)))))
(np--t (let ((o (oclosure-lambda (np--ocl (a 1) (b 2)) (x) x)))
         (list (closurep o) (interpreted-function-p o) (functionp o) (aref o 4))))
(oclosure-define (np--child (:parent np--ocl)) c)
(np--t (let ((o (oclosure-lambda (np--child (a 1) (b 2) (c 3)) () (list a b c))))
         (list (funcall o) (np--child--c o) (np--ocl--a o) (np--ocl-p o) (oclosure-type o))))
(np--t (np--ocl--a (lambda (x) x)))
(np--t (oclosure--slot-value (oclosure-lambda (np--ocl (a 7) (b 8)) () a) 'b))
(np--t (accessor--type (symbol-function 'np--ocl--a)))
(np--t (accessor--slot (symbol-function 'np--ocl--b)))
(np--t (funcall (symbol-function 'np--ocl--a) (oclosure-lambda (np--ocl (a 5) (b 6)) () a)))

;;; nelisp-nadvice-parity-smoke.el ends here
