;;; nelisp-eln-metadata-arena-test.el --- metadata arena tests -*- lexical-binding: t; -*-

(require 'ert)
(let* ((overlay (file-name-directory
                 (directory-file-name
                  (file-name-directory (or load-file-name buffer-file-name)))))
       (root (getenv "NELISP_ROOT")))
  (add-to-list 'load-path (expand-file-name "lisp" overlay))
  (when root
    (add-to-list 'load-path (expand-file-name "lisp" root))
    (add-to-list 'load-path (expand-file-name "packages/nl-ffi/src" root))))
(require 'nelisp-eln-metadata-arena)

(defmacro nelisp-eln-metadata-arena-test--mock (&rest body)
  `(let ((nelisp-eln-metadata-arena--pool nil)
         (nelisp-eln-metadata-arena--live nil)
         (nelisp-eln-metadata-arena--base-lease nil)
         (next-address 1048584)
         (allocation-fails nil))
     (cl-letf (((symbol-function 'nelisp-eln-objects-symbol-base-acquire)
                (lambda () (vector 'lease (vector nil 2097152))))
               ((symbol-function 'nl-ffi-memory-allocate)
                (lambda (size)
                  (when allocation-fails (error "mock allocation failure"))
                  (prog1 (vector size next-address)
                    (setq next-address (+ next-address size)))))
               ((symbol-function 'nl-ffi-memory-address)
                (lambda (owner) (aref owner 1)))
               ((symbol-function 'nl-ffi-memory-release) (lambda (_) t)))
       ,@body)))

(ert-deftest nelisp-eln-metadata-arena-concurrent-and-reuse ()
  (nelisp-eln-metadata-arena-test--mock
   (let* ((one (nelisp-eln-metadata-arena-acquire))
          (two (nelisp-eln-metadata-arena-acquire))
          (a (aref one 1)) (b (aref two 1)))
     (should-not (eq a b))
     (nelisp-eln-metadata-arena-retain one 'source-root)
     (nelisp-eln-metadata-arena-release one)
     (should-not (aref one 1))
     (should-not (aref one 4))
     (should-error (nelisp-eln-metadata-arena-release one)
                   :type 'nelisp-eln-metadata-arena-error)
     (let ((three (nelisp-eln-metadata-arena-acquire)))
       (should-not (eq one three))
       (should (eq a (aref three 1)))
       (should-error (nelisp-eln-metadata-arena-reserve one 8)
                     :type 'nelisp-eln-metadata-arena-error)
       (nelisp-eln-metadata-arena-release two)
       (nelisp-eln-metadata-arena-release three)))))

(ert-deftest nelisp-eln-metadata-arena-pool-stays-at-peak-demand ()
  (nelisp-eln-metadata-arena-test--mock
   (dotimes (_ 20)
     (let ((token (nelisp-eln-metadata-arena-acquire)))
       (nelisp-eln-metadata-arena-reserve token 8)
       (nelisp-eln-metadata-arena-release token)))
   (should (= (length nelisp-eln-metadata-arena--pool) 1))))

(ert-deftest nelisp-eln-metadata-arena-reserve-checks-before-mutation ()
  (nelisp-eln-metadata-arena-test--mock
   (let* ((token (nelisp-eln-metadata-arena-acquire))
          (arena (aref token 1)))
     (let ((aligned (nelisp-eln-metadata-arena-reserve token 9 4096)))
       (should (= (mod aligned 4096) 0)))
     (let ((cursor (aref arena 5)))
       (should-error (nelisp-eln-metadata-arena-reserve token 65536)
                     :type 'nelisp-eln-metadata-arena-exhausted)
       (should (= cursor (aref arena 5)))
       (dolist (bad '(-1 0 1.5))
         (should-error (nelisp-eln-metadata-arena-reserve token bad)
                       :type 'nelisp-eln-metadata-arena-error))
       (dolist (bad '(0 4 12 8192 1.0))
         (should-error (nelisp-eln-metadata-arena-reserve token 8 bad)
                       :type 'nelisp-eln-metadata-arena-error))
       (should (= cursor (aref arena 5))))
     (nelisp-eln-metadata-arena-release token))))

(ert-deftest nelisp-eln-metadata-arena-projected-word-range ()
  (nelisp-eln-metadata-arena-test--mock
   (let* ((token (nelisp-eln-metadata-arena-acquire))
          (arena (aref token 1))
          (address (aref arena 2))
          (delta (- address 2097152)))
     (dolist (tag '(1 3 4 5 7))
       (should (nelisp-eln-metadata-arena-projected-word-p (+ address tag))))
     (should-not (nelisp-eln-metadata-arena-projected-word-p
                  (+ (- address 8) 3)))
     (should (nelisp-eln-metadata-arena-projected-word-p delta))
     (should (nelisp-eln-metadata-arena-projected-word-p
              (nelisp-eln-abi-normalize-word delta)))
     (should-not (nelisp-eln-metadata-arena-projected-word-p 0))
     (should-not (nelisp-eln-metadata-arena-projected-word-p 10))
     (nelisp-eln-metadata-arena-release token)
     (should (nelisp-eln-metadata-arena-projected-word-p (+ address 3)))
     (should (nelisp-eln-metadata-arena-projected-word-p delta))
     (should (nelisp-eln-metadata-arena-projected-word-p
              (nelisp-eln-abi-normalize-word delta)))
     (let ((reused (nelisp-eln-metadata-arena-acquire)))
       (should (= address (nelisp-eln-metadata-arena-reserve reused 8)))
       (should (nelisp-eln-metadata-arena-projected-word-p (+ address 5)))
       (should (nelisp-eln-metadata-arena-projected-word-p delta))
       (nelisp-eln-metadata-arena-release reused)))))

(ert-deftest nelisp-eln-metadata-arena-allocation-failure-keeps-pool ()
  (nelisp-eln-metadata-arena-test--mock
   (setq allocation-fails t)
   (should-error (nelisp-eln-metadata-arena-acquire))
   (should-not nelisp-eln-metadata-arena--pool)
   (should nelisp-eln-metadata-arena--base-lease)))

(when (getenv "NELISP_METADATA_ARENA_STANDALONE")
  (let* ((one (nelisp-eln-metadata-arena-acquire))
         (start (nelisp-eln-metadata-arena-reserve one 32 16))
         (word (+ start 5))
         (base (aref (aref nelisp-eln-metadata-arena--base-lease 1) 1))
         (signed-delta (- start base))
         (unsigned-delta (nelisp-eln-abi-normalize-word signed-delta)))
    (unless (and (= (mod start 16) 0)
                 (nelisp-eln-metadata-arena-projected-word-p word)
                 (nelisp-eln-metadata-arena-projected-word-p signed-delta)
                 (nelisp-eln-metadata-arena-projected-word-p unsigned-delta))
      (error "actual mapped arena range check failed"))
    (nelisp-eln-metadata-arena-release one)
    (unless (and (nelisp-eln-metadata-arena-projected-word-p word)
                 (nelisp-eln-metadata-arena-projected-word-p signed-delta)
                 (nelisp-eln-metadata-arena-projected-word-p unsigned-delta))
      (error "retired actual arena pointer stopped being forbidden"))
    (unless (condition-case nil
                (progn (nelisp-eln-metadata-arena-reserve one 8) nil)
              (nelisp-eln-metadata-arena-error t))
      (error "stale token reserve was accepted"))
    (let ((two (nelisp-eln-metadata-arena-acquire)))
      (unless (and (not (eq one two))
                   (= start (nelisp-eln-metadata-arena-reserve two 32 16))
                   (nelisp-eln-metadata-arena-projected-word-p word)
                   (nelisp-eln-metadata-arena-projected-word-p signed-delta)
                   (nelisp-eln-metadata-arena-projected-word-p unsigned-delta))
        (error "actual arena mapping was not safely reused"))
      (nelisp-eln-metadata-arena-release two))
    (princ "metadata-arena-standalone: PASS\n")))

(provide 'nelisp-eln-metadata-arena-test)
;;; nelisp-eln-metadata-arena-test.el ends here
