;;; nelisp-variable-alias-core-test.el --- VM variable alias core tests -*- lexical-binding: t; -*-

;; Copyright (C) 2026 zawatton
;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Code:

(require 'ert)
(require 'nelisp-eval)
(require 'nelisp-bytecode)

(defun nelisp-variable-alias-core--bc-eval (form)
  "Compile and run FORM through the source bytecode VM."
  (nelisp-bc-run (nelisp-bc-compile form)))

(ert-deftest nelisp-variable-alias-core-resolves-and-routes-values ()
  (let ((nelisp--variable-aliases (make-hash-table :test 'eq))
        (nelisp--globals (make-hash-table :test 'eq)))
    (puthash 'va-a 'va-b nelisp--variable-aliases)
    (puthash 'va-b 'va-c nelisp--variable-aliases)
    (puthash 'va-c 37 nelisp--globals)
    (should (eq (nelisp-variable-canonical-symbol 'va-a) 'va-c))
    (should (= (nelisp-variable-get 'va-a nelisp--unbound) 37))
    (should (= (nelisp-variable-put 'va-a 42) 42))
    (should (= (gethash 'va-c nelisp--globals) 42))
    (should (eq (gethash 'va-a nelisp--globals nelisp--unbound)
                nelisp--unbound))))

(ert-deftest nelisp-variable-alias-core-distinguishes-unbound-from-nil ()
  (let ((nelisp--variable-aliases (make-hash-table :test 'eq))
        (nelisp--globals (make-hash-table :test 'eq)))
    (puthash 'va-nil nil nelisp--globals)
    (should (null (nelisp-variable-get 'va-nil nelisp--unbound)))
    (should (eq (nelisp-variable-get 'va-missing nelisp--unbound)
                nelisp--unbound))))

(ert-deftest nelisp-variable-alias-core-rejects-cycles-and-malformed-targets ()
  (let ((nelisp--variable-aliases (make-hash-table :test 'eq))
        (nelisp--globals (make-hash-table :test 'eq)))
    (puthash 'va-a 'va-b nelisp--variable-aliases)
    (puthash 'va-b 'va-a nelisp--variable-aliases)
    (should-error (nelisp-variable-get 'va-a nelisp--unbound)
                  :type 'cyclic-variable-indirection)
    (clrhash nelisp--variable-aliases)
    (puthash 'va-a "not-a-symbol" nelisp--variable-aliases)
    (should-error (nelisp-variable-put 'va-a 99)
                  :type 'nelisp-variable-alias-error)
    (should (eq (gethash 'va-a nelisp--globals nelisp--unbound)
                nelisp--unbound))))

(ert-deftest nelisp-variable-alias-core-installs-retargets-and-detaches ()
  (let ((nelisp--variable-aliases (make-hash-table :test 'eq))
        (nelisp--globals (make-hash-table :test 'eq))
        (nelisp--specials (make-hash-table :test 'eq))
        (nelisp--functions (make-hash-table :test 'eq)))
    (puthash 'va-a 'old nelisp--globals)
    (should (eq (nelisp-variable-install-alias 'va-a 'va-b) 'va-b))
    (should (eq (nelisp-variable-get 'va-a nelisp--unbound) 'old))
    (should (gethash 'va-a nelisp--specials))
    (should (gethash 'va-b nelisp--specials))
    (puthash 'va-c 'target-value nelisp--globals)
    (puthash 'va-a 'prior-alias-value nelisp--globals)
    (nelisp-variable-install-alias 'va-a 'va-c)
    (should (eq (nelisp-variable-get 'va-a nelisp--unbound) 'target-value))
    (should (eq (gethash 'va-b nelisp--globals) 'old))
    (puthash 'va-d 'value-d nelisp--globals)
    (nelisp-variable-install-alias 'va-c 'va-d)
    (should (eq (nelisp-variable-get 'va-a nelisp--unbound) 'value-d))
    (nelisp-variable-makunbound 'va-a)
    (should-not (nelisp-variable-boundp 'va-a))
    (should (nelisp-variable-boundp 'va-c))
    (should (eq (nelisp-variable-get 'va-c nelisp--unbound) 'value-d))))

(ert-deftest nelisp-variable-alias-core-retarget-cycle-is-atomic ()
  (let ((nelisp--variable-aliases (make-hash-table :test 'eq))
        (nelisp--globals (make-hash-table :test 'eq))
        (nelisp--specials (make-hash-table :test 'eq)))
    (puthash 'va-base 11 nelisp--globals)
    (nelisp-variable-install-alias 'va-a 'va-base)
    (puthash 'va-a 'function-cell nelisp--functions)
    (puthash 'va-b 'va-a nelisp--variable-aliases)
    (should (equal
             (condition-case err
                 (progn (nelisp-variable-install-alias 'va-a 'va-b) nil)
               (cyclic-variable-indirection err))
             '(cyclic-variable-indirection va-b)))
    (should (eq (gethash 'va-a nelisp--variable-aliases) 'va-base))
    (should (eq (nelisp-variable-get 'va-a nelisp--unbound) 11))
    (should (eq (gethash 'va-a nelisp--functions) 'function-cell))))

(ert-deftest nelisp-variable-alias-core-cycle-payload-is-target-and-atomic ()
  (let ((nelisp--variable-aliases (make-hash-table :test 'eq))
        (nelisp--globals (make-hash-table :test 'eq))
        (nelisp--specials (make-hash-table :test 'eq))
        (nelisp--functions (make-hash-table :test 'eq))
        (nelisp--plists (make-hash-table :test 'eq)))
    (puthash 'va-base 41 nelisp--globals)
    (nelisp-variable-install-alias 'va-a 'va-base)
    (nelisp-variable-install-alias 'va-b 'va-a)
    (nelisp-variable-install-alias 'va-c 'va-b)
    (puthash 'va-a 'function-a nelisp--functions)
    (puthash 'va-b 'function-b nelisp--functions)
    (puthash 'va-a '(property-a value-a) nelisp--plists)
    (puthash 'va-b '(property-b value-b) nelisp--plists)
    (should (equal
             (condition-case err
                 (progn (nelisp-variable-install-alias 'va-self 'va-self) nil)
               (cyclic-variable-indirection err))
             '(cyclic-variable-indirection va-self)))
    (should (equal
             (condition-case err
                 (progn (nelisp-variable-install-alias 'va-a 'va-b) nil)
               (cyclic-variable-indirection err))
             '(cyclic-variable-indirection va-b)))
    (should (equal
             (condition-case err
                 (progn (nelisp-variable-install-alias 'va-a 'va-c) nil)
               (cyclic-variable-indirection err))
             '(cyclic-variable-indirection va-c)))
    (should (eq (gethash 'va-self nelisp--variable-aliases nelisp--unbound)
                nelisp--unbound))
    (should (eq (gethash 'va-a nelisp--variable-aliases) 'va-base))
    (should (eq (gethash 'va-b nelisp--variable-aliases) 'va-a))
    (should (eq (gethash 'va-c nelisp--variable-aliases) 'va-b))
    (should (= (nelisp-variable-get 'va-c nelisp--unbound) 41))
    (should (eq (gethash 'va-a nelisp--functions) 'function-a))
    (should (eq (gethash 'va-b nelisp--functions) 'function-b))
    (should (equal (gethash 'va-a nelisp--plists) '(property-a value-a)))
    (should (equal (gethash 'va-b nelisp--plists) '(property-b value-b)))))

(ert-deftest nelisp-variable-alias-core-routes-evaluator-and-bytecode-globals ()
  (let ((nelisp--variable-aliases (make-hash-table :test 'eq))
        (nelisp--globals (make-hash-table :test 'eq))
        (nelisp--specials (make-hash-table :test 'eq)))
    (puthash 'va-base 17 nelisp--globals)
    (should (eq (nelisp-eval
                 '(nelisp-variable-install-alias 'va-alias 'va-base))
                'va-base))
    (should (= (nelisp-eval 'va-alias) 17))
    (should (= (nelisp-eval '(setq va-alias 21)) 21))
    (should (= (gethash 'va-base nelisp--globals) 21))
    (should (= (nelisp-variable-alias-core--bc-eval 'va-alias) 21))
    (should (= (nelisp-variable-alias-core--bc-eval
                '(setq va-alias 33)) 33))
    (should (= (gethash 'va-base nelisp--globals) 33))
    (should (equal (nelisp-eval
                    '(let ((va-alias 7)) (list va-alias va-base)))
                   '(7 7)))
    (should (= (gethash 'va-base nelisp--globals) 33))
    (should (equal (nelisp-variable-alias-core--bc-eval
                    '(let ((va-alias 9)) (list va-alias va-base)))
                   '(9 9)))
    (should (= (gethash 'va-base nelisp--globals) 33))))

(ert-deftest nelisp-variable-alias-core-preserves-self-valued-constants ()
  (let ((nelisp--variable-aliases (make-hash-table :test 'eq))
        (nelisp--globals (make-hash-table :test 'eq))
        (nelisp--specials (make-hash-table :test 'eq)))
    (dolist (constant '(nil t :va-constant))
      (let ((alias (make-symbol "va-constant-alias")))
        (should (eq (nelisp-variable-install-alias alias constant) constant))
        (should (eq (nelisp-variable-canonical-symbol alias) constant))
        (should (eq (nelisp-variable-get alias 'missing) constant))
        (should (nelisp-variable-boundp alias))
        (should-error (nelisp-variable-put alias 'bad)
                      :type 'setting-constant)
        (should-error (nelisp-variable-makunbound constant)
                      :type 'setting-constant)
        (nelisp-variable-makunbound alias)
        (should-not (nelisp-variable-boundp alias))))
    (dolist (constant '(nil t :va-constant))
      (should-error (nelisp-variable-install-alias constant 'va-target)
                    :type 'error))))

(ert-deftest nelisp-variable-alias-core-unaliased-resolution-does-not-allocate ()
  (let ((nelisp--variable-aliases (make-hash-table :test 'eq)))
    (cl-letf (((symbol-function 'make-hash-table)
               (lambda (&rest _)
                 (error "unexpected allocation for unaliased variable"))))
      (should (eq (nelisp-variable-canonical-symbol 'va-plain)
                  'va-plain)))))

(provide 'nelisp-variable-alias-core-test)
;;; nelisp-variable-alias-core-test.el ends here
