;;; n4-backtrace-reference.el --- Activation API GNU references -*- lexical-binding: t; -*-
;; Run unchanged on GNU 31.1 and the N4b standalone (with the normal bundle).
(defmacro n4-row (name form)
  `(progn (princ ,name) (princ "|")
          (prin1 (condition-case err ,form (error err))) (terpri)))
(defun n4-frame (x &optional y) (backtrace-frame 0 'n4-frame))
(defun n4-frame-alias (x) (backtrace-frame 0 'n4-frame-alias))
(defun n4-special () (let ((x 3)) (backtrace-frame 0 'let)))
(defun n4-locals (x) (backtrace--locals 1 'backtrace--locals))
(defun n4-eval-helper (expression) (backtrace-eval expression 0 'n4-eval-helper))
(defun n4-live () (let ((n4-x 7)) (list (n4-eval-helper '(setq n4-x 8)) n4-x)))
(defun n4-live-error ()
  (let ((n4-x 7))
    (list (condition-case nil (n4-eval-helper '(progn (setq n4-x 8) (error "expected")))
            (error 'caught)) n4-x)))
(defun n4-live-throw ()
  (let ((n4-x 7))
    (list (catch 'n4-tag (n4-eval-helper '(progn (setq n4-x 8) (throw 'n4-tag 9)))) n4-x)))
(defvar n4-dynamic 1)
(defun n4-dynamic-helper () (backtrace-eval '(setq n4-dynamic 8) 0 'n4-dynamic-helper))
(defun n4-dynamic-live () (let ((n4-dynamic 7)) (list (n4-dynamic-helper) n4-dynamic)))
(n4-row "frame-direct" (n4-frame 7 8))
(n4-row "frame-funcall" (funcall 'n4-frame 7 8))
(n4-row "frame-apply" (apply 'n4-frame '(7 8)))
(n4-row "frame-special" (n4-special))
(n4-row "frame-callback" (backtrace-frame--internal (lambda (e f _a flags) (list e f flags)) 0 nil))
(n4-row "frame-missing" (backtrace-frame--internal #'list 99999 nil))
(n4-row "frame-negative" (backtrace-frame--internal #'list -1 nil))
(n4-row "frame-offset" (n4-frame-alias 7))
(n4-row "frame-base-missing" (backtrace-frame 0 'n4-absent))
(n4-row "locals-parameter" (n4-locals 7))
(n4-row "locals-zero" (backtrace--locals 0))
(n4-row "locals-negative" (backtrace--locals -1))
(n4-row "locals-missing" (backtrace--locals 99999))
(n4-row "eval-literal" (backtrace-eval '(+ 2 3) 0))
(n4-row "eval-missing" (backtrace-eval 'ignored 99999))
(n4-row "eval-live" (n4-live))
(n4-row "eval-signal" (n4-live-error))
(n4-row "eval-throw" (n4-live-throw))
(n4-row "eval-dynamic" (n4-dynamic-live))
(n4-row "debug-return" (backtrace-debug 99999 t))
(n4-row "debug-negative" (backtrace-debug -1 nil))
(n4-row "map-self" (let (seen) (mapbacktrace (lambda (_e f _a _flags) (when (eq f 'mapbacktrace) (setq seen t)))) seen))
(n4-row "map-missing-base" (mapbacktrace (lambda (&rest _args) (error "unexpected")) 'n4-absent))
(n4-row "thread-nonempty" (consp (backtrace--frames-from-thread (current-thread))))
(n4-row "thread-type" (backtrace--frames-from-thread nil))
;; Debugger return value becomes the flagged activation's return value.
(defun n4-debug-target () (backtrace-debug 0 t 'n4-debug-target) 7)
(n4-row "debug-on-exit" (let ((debugger (lambda (reason value) (list reason value)))) (n4-debug-target)))
(n4-row "unwind-stack" (progn (condition-case nil (error "expected") (error nil)) (consp (backtrace-frames))))
(defun n4-map-flags ()
  (let (seen)
    (mapbacktrace
     (lambda (_e function _args flags)
       (when (eq function 'mapbacktrace) (backtrace-debug 0 t 'n4-map-flags))
       (when (eq function 'n4-map-flags) (setq seen (plist-get flags :debug-on-exit)))))
    (backtrace-debug 0 nil 'n4-map-flags)
    seen))
(n4-row "map-live-flags" (n4-map-flags))
(defun n4-args-copy (x)
  (let* ((frame (backtrace-frame 0 'n4-args-copy))
         (_ignored (setcar (cddr frame) 99)))
    (list x (backtrace-frame 0 'n4-args-copy))))
(n4-row "evaluated-args-spine" (n4-args-copy 7))
(n4-row "base-offset" (backtrace-frame--internal
                       (lambda (_e f _a _flags) f) 0 '(1 . backtrace-frame--internal)))
(defalias 'n4-alias #'n4-frame)
(n4-row "indirect-base" (n4-alias 7 8))
(defun n4-rest (&rest args) (backtrace-frame 0 'n4-rest))
(n4-row "rest-args" (n4-rest 1 2 3))
(n4-row "backtrace-print" (string-match-p "backtrace()" (with-output-to-string (backtrace))))
(defvar n4-repeat 1)
(defun n4-repeat-helper () (backtrace--locals 1 'n4-repeat-helper))
(defun n4-repeat-outer () (let ((n4-repeat 2) (n4-repeat 3)) (n4-repeat-helper)))
(n4-row "locals-repeated-dynamic" (n4-repeat-outer))
(n4-row "locals-captured-unused"
        (let ((unused 8))
          (funcall (lambda (y) (backtrace--locals 1 'backtrace--locals)) 7)))
(n4-row "frame-bignum" (backtrace-frame--internal #'list 1180591620717411303424 nil))
(n4-row "base-offset-nil" (backtrace-frame--internal #'list 0 '(0)))
(n4-row "base-offset-one-nil" (backtrace-frame--internal #'list 0 '(1)))
(princ "N4-BACKTRACE-REFERENCE-DONE\n")
nil
