;;; Extract genuine prelude functions without loading the prelude on GNU. -*- lexical-binding: t; -*-
(require 'bytecomp)
(require 'cl-lib)
(require 'nelisp-prelude-bytecode)
(defvar fp-names '(p34-arith3 p34-optional p34-rest p34-values expand-file-name file-exists-p file-directory-p file-name-directory file-name-nondirectory directory-files locate-file))
(defvar fp-forms nil)
(defun fp-walk (form line)
  (when (consp form)
    (cond
     ((and (eq (car form) 'defun) (memq (cadr form) fp-names))
      (push (list (cadr form) (cons 'lambda (cddr form)) line) fp-forms))
     ((and (eq (car form) 'fset) (consp (cadr form))
           (memq (cadadr form) fp-names) (eq (car-safe (caddr form)) 'lambda))
      (push (list (cadadr form) (caddr form) line) fp-forms))
     (t (let ((tail form))
          (while (consp tail) (fp-walk (car tail) line) (setq tail (cdr tail))))))))
(with-temp-buffer
  (insert-file-contents (expand-file-name "scripts/nelisp-stdlib-prelude.el" (getenv "FP_ROOT")))
  (goto-char (point-min))
  (condition-case nil
      (while t
        (forward-comment (point-max))
        (let ((line (line-number-at-pos))) (fp-walk (read (current-buffer)) line)))
    (end-of-file nil)))
(dolist (form '((defun p34-arith3 (a b c) (+ a (* b c)))
                (defun p34-optional (a &optional b c) (list a b c))
                (defun p34-rest (a &optional b &rest c) (list a b c))
                (defun p34-values (a b)
                  (list (symbolp a) (consp a) (stringp a) (listp a)
                        (eq a b) (not a) (numberp a) (integerp a)))))
  (fp-walk form 0))
(when (getenv "FP_GUI_SOURCE")
  (setq fp-names (append fp-names '(emacs-redisplay--ml-spans)))
  (let (helpers)
    (with-temp-buffer
      (insert-file-contents (getenv "FP_GUI_SOURCE"))
      (goto-char (point-min))
      (condition-case nil
          (while t
            (let ((form (read (current-buffer))))
              (when (and (memq (car-safe form) '(defun defvar defconst))
                         (symbolp (cadr form))
                         (string-prefix-p "emacs-redisplay--" (symbol-name (cadr form))))
                (fp-walk form 0)
                (push form helpers))))
        (end-of-file nil)))
    (with-temp-file (expand-file-name "gui-helpers.el" (getenv "FP_OUT"))
      (insert ";;; -*- lexical-binding: t; -*-\n")
      (dolist (form (nreverse helpers))
        (prin1 form (current-buffer)) (insert "\n")))))
(setq fp-forms (nreverse fp-forms))
(dolist (name fp-names)
  ;; The later fallback directory-files is inactive; the earlier fset is live.
  (let* ((entry (assq name fp-forms)) (source (cadr entry))
         (function (byte-compile source))
         (output (expand-file-name (concat "input-" (symbol-name name) ".elc") (getenv "FP_OUT"))))
    (unless (byte-code-function-p function) (error "No bytecode: %s" name))
    (with-temp-file output
      (insert ";ELC\037\000\000\000\n;;; -*- lexical-binding: t; -*-\n")
      (let ((print-escape-nonascii t) (print-length nil) (print-level nil))
        (prin1 (list 'defalias (list 'quote name) function) (current-buffer)))
      (insert "\n"))
    (with-temp-file (expand-file-name (concat "source-" (symbol-name name) ".el") (getenv "FP_OUT"))
      (prin1 (list 'fset (list 'quote name) (list 'quote source)) (current-buffer)))
    (princ (format "FP-HOST|%s|line=%s|bytes=%d|constants=%S|\n" name (caddr entry) (length (aref function 1)) (aref function 2)))))
(princ "FP-HOST-DONE\n")

;; The caller remains interpreted GNU bytecode on both sides.  Keeping its
;; loop in bytecode separates dispatch cost from the source evaluator's
;; allocation-heavy DOTIMES expansion; neither caller is natively compiled.
(dolist (pair '((file-exists-p "/tmp") (file-name-directory "/tmp/a")
                (p34-arith3 2 3 4)))
  (let* ((name (car pair)) (caller (intern (concat "p34-caller-" (symbol-name name))))
         (function (byte-compile
                    (if (eq name 'p34-arith3)
                        `(lambda (n) (let (result) (dotimes (_ n result)
                                                   (setq result (,name ,@(cdr pair))))))
                      `(lambda (n path) (let (result) (dotimes (_ n result)
                                                     (setq result (,name path)))))))))
    ;; Literal pure calls can be folded by GNU before the loop runs. Keep the
    ;; pathname dynamic and the result observable, and require a live target.
    (unless (cl-find name (aref function 2) :test #'eq)
      (error "Benchmark caller eliminated its target: %s" name))
    (with-temp-file (expand-file-name (concat "caller-" (symbol-name name) ".elc") (getenv "FP_OUT"))
      (insert ";ELC\037\000\000\000\n;;; -*- lexical-binding: t; -*-\n")
      (let ((print-escape-nonascii t) (print-length nil) (print-level nil))
        (prin1 (list 'defalias (list 'quote caller) function) (current-buffer)))
      (insert "\n"))))

;; Genuine GNU VM instructions exercise the private vector path without
;; native-compiling these callers. Reject any unsupported or absent opcode.
(let ((forms nil) (count 0))
  (with-temp-buffer
    (insert-file-contents
     (expand-file-name "test/nelisp-native-vm-vector-callers.el" (getenv "FP_ROOT")))
    (goto-char (point-min))
    (condition-case nil
        (while t (push (read (current-buffer)) forms))
      (end-of-file nil)))
  (with-temp-file (expand-file-name "vm-vector-helpers.el" (getenv "FP_OUT"))
    (insert ";;; Genuine GNU vector callers -*- lexical-binding: t; -*-\n")
    (dolist (form (nreverse forms))
      (let* ((name (cadr form))
             (compiled (let ((lexical-binding t)) (byte-compile (cons 'lambda (cddr form)))))
             (ops (and (byte-code-function-p compiled)
                       (nelisp-prelude-bytecode--decode-opcodes (aref compiled 1))))
             (expected (cond ((eq name 'p35-vm-increment) 84)
                             ((eq name 'p35-vm-decrement) 83)
                             ((eq name 'p35-vm-add) 92)
                             ((eq name 'p35-vm-multiply) 95)
                             ((eq name 'p35-vm-subtract) 90)
                             ((eq name 'p35-vm-num-equal) 85)
                             ((eq name 'p35-vm-less) 87)
                             ((eq name 'p35-vm-greater) 86)
                             ((eq name 'p35-vm-less-equal) 88)
                             ((eq name 'p35-vm-greater-equal) 89)
                             ((string-match-p "write" (symbol-name name)) 73)
                             (t 72))))
        (unless (and ops (memq expected ops)
                     (not (cl-set-difference ops nelisp-prelude-bytecode--opcodes))
                     (not (nelisp-prelude-bytecode--nested-unsupported compiled)))
          (error "Vector caller lacks supported opcode %d: %S" expected name))
        (let ((print-length nil) (print-level nil) (print-escape-nonascii t)
              (print-escape-newlines t))
          (prin1 `(fset ',name ,compiled) (current-buffer)) (insert "\n"))
        (setq count (1+ count)))))
  (unless (= count 18) (error "Expected eighteen VM callers"))
  (princ "FP-VECTOR-CALLERS-CHECKED count=18\n"))

;; Preserve ordinary CALL semantics, rather than GNU's dedicated subtraction.
(let ((forms nil) (count 0) (saved-minus (get '- 'byte-compile)))
  (unwind-protect
      (progn
        (put '- 'byte-compile nil)
        (with-temp-buffer
          (insert-file-contents
           (expand-file-name "test/nelisp-native-vm-call-difference-callers.el" (getenv "FP_ROOT")))
          (goto-char (point-min))
          (condition-case nil
              (while t (push (read (current-buffer)) forms))
            (end-of-file nil)))
        (with-temp-file (expand-file-name "vm-call-difference-helpers.el" (getenv "FP_OUT"))
          (insert ";;; Genuine GNU ordinary CALL helpers -*- lexical-binding: t; -*-\n")
          (dolist (form (nreverse forms))
            (unless (eq (car-safe form) 'defun) (error "Unexpected CALL fixture form"))
            (let* ((name (cadr form))
                   (compiled (let ((lexical-binding t)) (byte-compile (cons 'lambda (cddr form)))))
                   (ops (and (byte-code-function-p compiled)
                             (nelisp-prelude-bytecode--decode-opcodes (aref compiled 1)))))
              (unless (and ops (memq 32 ops) (not (memq 90 ops)) (not (memq 91 ops))
                           (or (not (eq name 'p35-vm-call-difference))
                               (memq '- (append (aref compiled 2) nil)))
                           (not (cl-set-difference ops nelisp-prelude-bytecode--opcodes))
                           (not (nelisp-prelude-bytecode--nested-unsupported compiled)))
                (error "Ordinary CALL fixture lacks supported CALL: %S" name))
              (let ((print-length nil) (print-level nil) (print-escape-nonascii t)
                    (print-escape-newlines t) (print-gensym t))
                (prin1 `(fset ',name ,compiled) (current-buffer)) (insert "\n"))
              (setq count (1+ count)))))
        (unless (= count 5) (error "Expected five ordinary CALL helpers"))
        (princ "FP-CALL-DIFFERENCE-CALLERS-CHECKED count=5\n"))
    (put '- 'byte-compile saved-minus)))

;;; Append to the existing GNU fixture generator. -*- lexical-binding: t; -*-
(let ((saved-minus (get '- 'byte-compile)))
 (unwind-protect
  (progn
   (put '- 'byte-compile nil)
   (dolist (spec '((frame 15) (dynamic-frame 19)))
    (let ((forms nil) (count 0) (kind (car spec)))
     (with-temp-buffer
      (insert-file-contents (expand-file-name (format "test/nelisp-native-vm-%s-callers.el" kind) (getenv "FP_ROOT")))
      (goto-char (point-min))
      (condition-case nil (while t (push (read (current-buffer)) forms)) (end-of-file nil)))
     (with-temp-file (expand-file-name (format "vm-%s-helpers.el" kind) (getenv "FP_OUT"))
      (insert ";;; Genuine checked GNU bytecode. -*- lexical-binding: t; -*-\n")
      (dolist (form (nreverse forms))
       (unless (eq (car-safe form) 'defun) (error "Unexpected VM frame fixture form"))
       (let* ((name (cadr form))
              (dynamic (or (eq name 'p35-vm-frame-dynamic) (eq name 'p35-vm-jit-dynamic)
                           (string-prefix-p "p35-vm-dynamic-" (symbol-name name))))
              (compiled (let ((lexical-binding (not dynamic))) (byte-compile (cons 'lambda (cddr form)))))
              (ops (and (byte-code-function-p compiled) (nelisp-prelude-bytecode--decode-opcodes (aref compiled 1)))))
        (unless (and ops (if dynamic (listp (aref compiled 0)) (integerp (aref compiled 0)))
                     (not (cl-set-difference ops nelisp-prelude-bytecode--opcodes))
                     (not (nelisp-prelude-bytecode--nested-unsupported compiled)))
         (error "Unsupported VM frame fixture bytecode: %S" name))
        (let ((print-length nil) (print-level nil) (print-circle t) (print-gensym t) (print-escape-newlines t) (print-escape-nonascii t))
         (prin1 `(fset ',name ,compiled) (current-buffer)) (insert "\n"))
        (setq count (1+ count)))))
     (unless (= count (cadr spec)) (error "Wrong VM frame caller count: %S %d" kind count))
     (princ (format "FP-VM-%s-CALLERS-CHECKED count=%d\n" (upcase (symbol-name kind)) count)))))
  (put '- 'byte-compile saved-minus)))
