;;; nelisp-native-tier-test.el --- Async tier publication controls -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'ert)
(require 'nelisp-native-tier)
(require 'nelisp-native-cache-test)
(defmacro nelisp-native-tier-test--state (&rest body)
  (declare (indent 0))
  `(let ((nelisp-native-tier--entries nil) (nelisp-native-tier--queue nil)
         (nelisp-native-tier--pending nil) (nelisp-native-tier--serial 0)
         (nelisp-native-tier--reaped 0)
         (nelisp-native-tier--tier0 (make-hash-table :test 'equal))
         (nelisp-native-tier--refusals (make-hash-table :test 'equal))
         (nelisp-native-tier--accepted (make-hash-table :test 'equal))
         (nelisp-native-tier-threshold 2)
         (nelisp-native-budget--handles 0) (nelisp-native-budget--bytes 0)
         (fn (make-byte-code 257 (unibyte-string 0 135) [old] 1))
         (loads 0))
     (cl-letf (((symbol-function 'nelisp-native-tier--identity)
                (lambda (function backend)
                  (list :backend backend :abi "abi" :input
                        (nelisp-native-cache--hash (list (aref function 1) (aref function 2))))))
               ((symbol-function 'nelisp-native-cache-load)
                (lambda (_fn) (setq loads (1+ loads))
                  (let* ((generation loads)
                         (factory (lambda (_constants) (lambda (x) (list generation x)))))
                    (when nelisp-native-cache--unit-observer
                      (funcall nelisp-native-cache--unit-observer factory))
                    (funcall factory nil)))))
       (unwind-protect (progn ,@body) (fmakunbound 'tier-test-target)))))
(defun nelisp-native-tier-test--completed-job (entry)
  (let* ((dir (make-temp-file "tier-host-" t))
         (job (list :entry entry :key (plist-get entry :key) :serial 1 :directory dir
                    :cache dir :process 'fake :started (float-time)
                    :cell (plist-get entry :cell) :generation (car (plist-get entry :cell)) :released nil)))
    (setf (plist-get entry :job) job)
    (nelisp-native-tier--write (expand-file-name "reply" dir)
                             (list :status 'ok :serial 1 :identity (plist-get entry :identity)))
    job))
(ert-deftest nelisp-native-tier-hotness-saturates-no-validation ()
  (nelisp-native-tier-test--state
    (let ((nelisp-native-tier-threshold nil)
          (entry (nelisp-native-tier-install 'tier-test-target fn)))
      (cl-letf (((symbol-function 'nelisp-native-tier--identity)
                 (lambda (&rest _) (ert-fail "entry validated"))))
        (dotimes (_ 3) (tier-test-target 42))
        (should (= 3 (plist-get entry :count)))
        (setf (plist-get entry :count) most-positive-fixnum)
        (tier-test-target 42)
        (should (= most-positive-fixnum (plist-get entry :count)))))))
(ert-deftest nelisp-native-tier-forced-hotness-requests-once ()
  (nelisp-native-tier-test--state
    (let ((requests 0) (entry (nelisp-native-tier-install 'tier-test-target fn)))
      (cl-letf (((symbol-function 'nelisp-native-tier--launch-next) #'ignore))
        (tier-test-target 42) (should-not nelisp-native-tier--queue)
        (tier-test-target 42) (setq requests (length nelisp-native-tier--queue))
        (tier-test-target 42)
        (should (= requests 1))
        (should (= 1 (length nelisp-native-tier--queue)))
        (should (plist-get entry :job))))))
(ert-deftest nelisp-native-tier-complete-generation-snapshot-under-gc ()
  (nelisp-native-tier-test--state
    (let* ((nelisp-native-tier-threshold nil)
           (entry (nelisp-native-tier-install 'tier-test-target fn))
           (job (nelisp-native-tier-test--completed-job entry))
           (cell (plist-get entry :cell))
           (old (lambda (x)
                  (nelisp-native-tier--finish job)
                  (garbage-collect)
                  (list 'old x))))
      (unwind-protect
          (progn (setcar cell old) (setf (plist-get job :generation) old)
                 (should (equal (tier-test-target 42) '(old 42)))
                 (should-not (eq (car cell) old))
                 (should (= 1 (plist-get entry :tier)))
                 (should (equal (tier-test-target 42) '(2 42))))
        (delete-directory (plist-get job :directory) t)))))
(ert-deftest nelisp-native-tier-redefinition-before-load-stays-current ()
  (nelisp-native-tier-test--state
    (let* ((entry (nelisp-native-tier-install 'tier-test-target fn))
           (job (nelisp-native-tier-test--completed-job entry))
           (current (lambda (_) 'user)))
      (unwind-protect
          (progn (fset 'tier-test-target current)
                 (should-error (nelisp-native-tier--finish job))
                 (should (eq current (symbol-function 'tier-test-target)))
                 (should (= loads 1)))
        (delete-directory (plist-get job :directory) t)))))
(ert-deftest nelisp-native-tier-stale-input-and-abi-refuse ()
  (nelisp-native-tier-test--state
    (let* ((entry (nelisp-native-tier-install 'tier-test-target fn))
           (job (nelisp-native-tier-test--completed-job entry))
           (old (car (plist-get entry :cell))))
      (unwind-protect
          (progn (aset (aref fn 2) 0 'changed)
                 (should-error (nelisp-native-tier--finish job))
                 (should (eq old (car (plist-get entry :cell))))
                 (aset (aref fn 2) 0 'old)
                 (cl-letf (((symbol-function 'nelisp-native-tier--identity)
                            (lambda (&rest _) '(:abi changed))))
                   (should-error (nelisp-native-tier--finish job))))
        (delete-directory (plist-get job :directory) t)))))
(ert-deftest nelisp-native-tier-rechecks-after-mapping-callback ()
  (nelisp-native-tier-test--state
    (let* ((entry (nelisp-native-tier-install 'tier-test-target fn))
           (job (nelisp-native-tier-test--completed-job entry))
           (old (car (plist-get entry :cell)))
           (current (lambda (_) 'user)))
      (unwind-protect
          (cl-letf (((symbol-function 'nelisp-native-cache-load)
                     (lambda (_) (fset 'tier-test-target current)
                       (funcall nelisp-native-cache--unit-observer (lambda (_) #'identity)) #'identity)))
            (should-error (nelisp-native-tier--finish job))
            (should (eq current (symbol-function 'tier-test-target)))
            (should (eq old (car (plist-get entry :cell)))))
        (delete-directory (plist-get job :directory) t)))))
(ert-deftest nelisp-native-tier-refusal-retained-and-backed-off ()
  (nelisp-native-tier-test--state
    (let ((entry (nelisp-native-tier-install 'tier-test-target fn)))
      (cl-letf (((symbol-function 'nelisp-native-tier--launch-next) #'ignore))
        (nelisp-native-tier--refuse entry 'temporarily-busy)
        (nelisp-native-tier-request entry) (should-not nelisp-native-tier--queue)
        (nelisp-native-tier-request entry t) (should nelisp-native-tier--queue)
        (nelisp-native-tier-cancel entry)
        (nelisp-native-tier--refuse entry 'unsupported t)
        (nelisp-native-tier-request entry t) (should-not nelisp-native-tier--queue)
        (should (eq 'unsupported (plist-get (plist-get entry :refusal) :reason)))))))
(ert-deftest nelisp-native-tier-deduplicates-and-limits-generations ()
  (nelisp-native-tier-test--state
    (let ((a (nelisp-native-tier-install 'tier-test-target fn))
          (b (nelisp-native-tier-install 'tier-test-target fn)))
      (cl-letf (((symbol-function 'nelisp-native-tier--launch-next) #'ignore))
        (nelisp-native-tier-request a) (nelisp-native-tier-request b)
        (should (= 1 (length nelisp-native-tier--queue)))
        (should (eq 'duplicate-pending (plist-get (plist-get b :refusal) :reason)))
        (nelisp-native-tier-cancel a)
        (puthash (plist-get a :key) (lambda (_) #'identity) nelisp-native-tier--accepted)
        (nelisp-native-tier-request a t) (should-not nelisp-native-tier--queue)))))
(ert-deftest nelisp-native-tier-no-sync-fallback ()
  (nelisp-native-tier-test--state
    (let ((entry (nelisp-native-tier-install 'tier-test-target fn)))
      (cl-letf (((symbol-function 'nelisp-native-tier--native-process-p) (lambda () nil))
                ((symbol-function 'nelisp-native-cache-compile)
                 (lambda (_) (ert-fail "synchronous optimizer"))))
        (nelisp-native-tier-request entry)
        (should-not nelisp-native-tier--pending)
        (should (plist-get (plist-get entry :refusal) :permanent))
        (should (= 0 (plist-get entry :tier)))))))
(ert-deftest nelisp-native-tier-finished-child-cleanup-even-corrupt-reply ()
  (nelisp-native-tier-test--state
    (let* ((entry (nelisp-native-tier-install 'tier-test-target fn))
           (job (nelisp-native-tier-test--completed-job entry)) (deleted 0))
      (setq nelisp-native-tier--pending job)
      (nelisp-native-tier--write (expand-file-name "reply" (plist-get job :directory)) '(corrupt))
      (cl-letf (((symbol-function 'nelisp-process-status) (lambda (_) 1))
                ((symbol-function 'nelisp-process-exit-status) (lambda (_) 0))
                ((symbol-function 'nelisp-process-delete) (lambda (_) (setq deleted (1+ deleted)))))
        (nelisp-native-tier-poll)
        (should (= deleted 1)) (should (= nelisp-native-tier--reaped 1))
        (should-not (file-exists-p (plist-get job :directory)))
        (should-not nelisp-native-tier--pending) (should-not (plist-get entry :job))
        (should (= 0 (plist-get entry :tier)))))))
(ert-deftest nelisp-native-tier-timeout-and-cancel-reap ()
  (nelisp-native-tier-test--state
    (let* ((entry (nelisp-native-tier-install 'tier-test-target fn))
           (job (nelisp-native-tier-test--completed-job entry)) (deleted 0)
           (nelisp-native-tier-timeout 1))
      (setq nelisp-native-tier--pending job)
      (setf (plist-get job :started) (- (float-time) 2))
      (cl-letf (((symbol-function 'nelisp-process-status) (lambda (_) 0))
                ((symbol-function 'nelisp-process-delete) (lambda (_) (setq deleted (1+ deleted)))))
        (nelisp-native-tier-poll) (should (= deleted 1))
        (setq job (nelisp-native-tier-test--completed-job entry)
              nelisp-native-tier--pending job)
        (nelisp-native-tier-cancel entry)
        (should (= deleted 2)) (should (= nelisp-native-tier--reaped 2))))))
(ert-deftest nelisp-native-tier-worker-executable-and-static-gccjit-fences ()
  (let ((binary (make-temp-file "tier-binary-")))
    (unwind-protect
        (cl-letf (((symbol-function 'nelisp-native-load-running-binary-sha256)
                   (lambda () (nelisp-native-cache--file-hash binary))))
          (should (null (nelisp-native-tier--check-worker binary 'in-house)))
          (cl-letf (((symbol-function 'nelisp-native-load-running-binary-sha256) (lambda () "foreign")))
            (should-error (nelisp-native-tier--check-worker binary 'in-house)))
          (let ((features (cons 'nl-ffi features)))
          (cl-letf (((symbol-function 'nl-ffi--dlopen) (lambda (_) (error "Static reader"))))
            (should-error (nelisp-native-tier--check-worker binary 'gccjit)))))
      (delete-file binary))))
(ert-deftest nelisp-native-tier-worker-uses-raw-executable-identity ()
  (cl-letf (((symbol-function 'nelisp-native-load--sha256-file-external) (lambda (_) "complete-raw-elf"))
            ((symbol-function 'nelisp-native-cache--file-hash) (lambda (_) (ert-fail "encoded buffer hash used")))
            ((symbol-function 'nelisp-native-load-running-binary-sha256) (lambda () "complete-raw-elf")))
    (should-not (nelisp-native-tier--check-worker "reader" 'in-house))))
(ert-deftest nelisp-native-tier-worker-raw-hash-fallback ()
  (let ((binary (make-temp-file "tier-binary-")) (bytes (unibyte-string 0 128 255)))
    (unwind-protect
        (let ((coding-system-for-write 'no-conversion))
          (write-region bytes nil binary nil 'silent)
          (cl-letf (((symbol-function 'nelisp-native-load--sha256-file-external) (lambda (_) nil))
                    ((symbol-function 'nelisp-native-load-running-binary-sha256)
                     (lambda () (secure-hash 'sha256 bytes))))
            (should-not (nelisp-native-tier--check-worker binary 'in-house))))
      (delete-file binary))))
(ert-deftest nelisp-native-tier-launch-file-error-backs-off ()
  (nelisp-native-tier-test--state
    (let ((entry (nelisp-native-tier-install 'tier-test-target fn)))
      (cl-letf (((symbol-function 'nelisp-native-tier--native-process-p) (lambda () t))
                ((symbol-function 'nelisp-native-tier--check-worker)
                 (lambda (&rest _) (signal 'file-error '("No space left")))))
        (nelisp-native-tier-request entry)
        (should-not (plist-get (plist-get entry :refusal) :permanent))
        (should (> (plist-get (plist-get entry :refusal) :retry-after) (float-time)))
        (should-not nelisp-native-tier--pending)
        (nelisp-native-tier-request entry)
        (should (= 1 nelisp-native-tier--serial))))))
(ert-deftest nelisp-native-tier-worker-refuses-missing-requested-image ()
  (let ((request (make-temp-file "tier-request-")) (reply (make-temp-file "tier-reply-"))
        (nelisp-native-cache--cold-source-check nil))
    (unwind-protect
        (progn
          (nelisp-native-tier--write request '(:version 1 :image-required t :identity (:backend in-house)))
          (cl-letf (((symbol-function 'nelisp-native-cache-compile) (lambda (_) (ert-fail "source fallback compiled"))))
            (nelisp-native-tier-worker request reply))
          (let ((record (nelisp-native-tier--read reply)))
            (should (eq (plist-get record :status) 'refused))
            (should (plist-get record :permanent))
            (should (equal (plist-get record :reason)
                           '(nelisp-native-tier-permanent optimizer-image-not-loaded)))))
      (delete-file request) (delete-file reply))))
(ert-deftest nelisp-native-tier-budget-is-lifetime-and-refuses-before-map ()
  (let ((nelisp-native-budget--handles 0) (nelisp-native-budget--bytes 0)
        (nelisp-native-budget-handle-limit 2) (nelisp-native-budget-byte-limit 8192))
    (nelisp-native-budget-reserve 4096) (nelisp-native-budget-reserve 4096)
    (should-error (nelisp-native-budget-reserve 1))
    (should (= nelisp-native-budget--handles 2))
    (should (= nelisp-native-budget--bytes 8192))))
(ert-deftest nelisp-native-tier-protocol-refuses-trailing-data ()
  (let ((path (make-temp-file "tier-record-")))
    (unwind-protect
        (progn (write-region "(:version 1)\n(:status ok)" nil path nil 'silent)
               (should-error (nelisp-native-tier--read path)))
      (delete-file path))))
(ert-deftest nelisp-native-tier-final-identity-callback-cannot-clobber-user ()
  (nelisp-native-tier-test--state
    (let* ((entry (nelisp-native-tier-install 'tier-test-target fn))
           (job (nelisp-native-tier-test--completed-job entry))
           (current (lambda (_) 'user)) (calls 0)
           (identity (plist-get entry :identity)))
      (unwind-protect
          (cl-letf (((symbol-function 'nelisp-native-tier--identity)
                     (lambda (&rest _)
                       (setq calls (1+ calls))
                       (when (= calls 2) (fset 'tier-test-target current))
                       identity)))
            (should-error (nelisp-native-tier--finish job))
            (should (= calls 2))
            (should (eq current (symbol-function 'tier-test-target)))
            (should (= 0 (plist-get entry :tier))))
        (delete-directory (plist-get job :directory) t)))))
(ert-deftest nelisp-native-tier-tier0-owner-reused-with-distinct-live-constants ()
  (nelisp-native-tier-test--state
    (let ((second (make-byte-code 257 (unibyte-string 0 135) [old] 1)) (maps 0))
      (cl-letf (((symbol-function 'nelisp-native-cache-load)
                 (lambda (input-fn)
                   (setq maps (1+ maps))
                   (let ((factory (lambda (constants) (lambda (_) (aref constants 0)))))
                     (funcall nelisp-native-cache--unit-observer factory)
                     (funcall factory (nelisp-native-cache--constants input-fn))))))
        (let* ((a (nelisp-native-tier-install 'tier-test-target fn))
               (b (nelisp-native-tier-install 'tier-test-target second)))
          (should (= maps 1))
          (aset (aref fn 2) 0 'first)
          (aset (aref second 2) 0 'second)
          (should (eq 'first (funcall (car (plist-get a :cell)) nil)))
          (should (eq 'second (funcall (car (plist-get b :cell)) nil))))))))
(ert-deftest nelisp-native-tier-exhausted-budget-never-launches-compiler ()
  (nelisp-native-tier-test--state
    (let ((entry (nelisp-native-tier-install 'tier-test-target fn))
          (nelisp-native-budget--handles 512))
      (cl-letf (((symbol-function 'nelisp-native-tier--native-process-p) (lambda () t))
                ((symbol-function 'nelisp-native-tier--check-worker)
                 (lambda (&rest _) (ert-fail "exhausted budget reached worker launch"))))
        (nelisp-native-tier-request entry)
        (should-not nelisp-native-tier--pending)
        (should (plist-get (plist-get entry :refusal) :permanent))
        (should (equal (funcall (car (plist-get entry :cell)) 42) '(1 42)))))))
(ert-deftest nelisp-native-tier-exhausted-budget-refuses-actual-trusted-mapper ()
  (nelisp-native-cache-test--runtime
    (nelisp-native-cache-test--directory
      (pcase-let* ((`(,fn ,manifest ,header) (nelisp-native-cache-test--fixture))
                   (file (nelisp-native-cache-file fn))
                   (nelisp-native-budget--handles 0) (nelisp-native-budget--bytes 0))
        (nelisp-native-cache-test--write file header manifest)
        (let ((callable (nelisp-native-cache-load fn))
              (nelisp-native-budget-handle-limit 1))
          (cl-letf (((symbol-function 'nelisp-native-load--mmap)
                     (lambda (&rest _) (ert-fail "exhausted budget reached mmap"))))
            (should-error (nelisp-native-cache-load fn) :type 'nelisp-native-budget-exhausted)
            (should (= 12 (funcall callable 12 34)))))))))
(ert-deftest nelisp-native-tier-cancel-during-load-keeps-new-worker-ownership ()
  (nelisp-native-tier-test--state
    (let* ((entry (nelisp-native-tier-install 'tier-test-target fn))
           (job (nelisp-native-tier-test--completed-job entry))
           (next (list :entry (list :job nil) :process 'next :directory nil :released nil))
           (deleted 0) (old (car (plist-get entry :cell))))
      (setq nelisp-native-tier--pending job nelisp-native-tier--queue (list next))
      (cl-letf (((symbol-function 'nelisp-process-status) (lambda (_) 1))
                ((symbol-function 'nelisp-process-exit-status) (lambda (_) 0))
                ((symbol-function 'nelisp-process-delete) (lambda (_) (setq deleted (1+ deleted))))
                ((symbol-function 'nelisp-native-tier--launch-next)
                 (lambda ()
                   (unless nelisp-native-tier--pending
                     (setq nelisp-native-tier--pending (pop nelisp-native-tier--queue)))))
                ((symbol-function 'nelisp-native-cache-load)
                 (lambda (_) (nelisp-native-tier-cancel entry)
                       (funcall nelisp-native-cache--unit-observer (lambda (_) #'identity)) #'identity)))
        (nelisp-native-tier-poll)
        (should (eq next nelisp-native-tier--pending))
        (should (= deleted 1)) (should (= nelisp-native-tier--reaped 1))
        (should-not (plist-get entry :job))
        (should (eq old (car (plist-get entry :cell))))
        (should (= 0 (plist-get entry :tier)))))))
(ert-deftest nelisp-native-tier-worker-file-refusal-is-transient ()
  (nelisp-native-tier-test--state
    (let* ((entry (nelisp-native-tier-install 'tier-test-target fn))
           (job (nelisp-native-tier-test--completed-job entry)))
      (unwind-protect
          (progn
            (nelisp-native-tier--write (expand-file-name "reply" (plist-get job :directory))
                                      (list :status 'refused :reason '(file-error "No space left")
                                            :identity (plist-get entry :identity) :serial 1 :permanent nil))
            (should-error (nelisp-native-tier--finish job))
            (should-not (plist-get (plist-get entry :refusal) :permanent))
            (should (> (plist-get (plist-get entry :refusal) :retry-after) (float-time))))
        (delete-directory (plist-get job :directory) t)))))
(ert-deftest nelisp-native-tier-accepted-owner-reused-by-another-symbol ()
  (nelisp-native-tier-test--state
    (let* ((entry (nelisp-native-tier-install 'tier-test-target fn))
           (job (nelisp-native-tier-test--completed-job entry)))
      (unwind-protect
          (progn
            (nelisp-native-tier--finish job)
            (let ((second (nelisp-native-tier-install 'tier-test-target fn)))
              (nelisp-native-tier-request second)
              (should (= 1 (plist-get second :tier)))
              (should (equal (tier-test-target 42) '(2 42)))
              (should-not nelisp-native-tier--pending)))
        (delete-directory (plist-get job :directory) t)))))
(ert-deftest nelisp-native-tier-accepted-adoption-refusal-keeps-tier0-and-backs-off ()
  (nelisp-native-tier-test--state
    (let* ((entry (nelisp-native-tier-install 'tier-test-target fn)) (attempts 0))
      (puthash (plist-get entry :key)
               (lambda (_) (setq attempts (1+ attempts)) (error "Transient binding failure"))
               nelisp-native-tier--accepted)
      (dotimes (_ 4) (should (equal (tier-test-target 42) '(1 42))))
      (should (= attempts 1))
      (should (plist-get entry :refusal))
      (should (= 0 (plist-get entry :tier))))))
(ert-deftest nelisp-native-tier-restores-native-cache-environment ()
  ;; A standalone setenv updates the OS environment, independently of the
  ;; dynamically bound process-environment list. Model that on the host.
  (dolist (failure '(nil t))
    (nelisp-native-tier-test--state
      (let* ((entry (nelisp-native-tier-install 'tier-test-target fn))
             (job (nelisp-native-tier-test--completed-job entry))
             (external "parent-cache")
             (loader (symbol-function 'nelisp-native-cache-load)))
        (unwind-protect
            (cl-letf (((symbol-function 'getenv) (lambda (&rest _) external))
                      ((symbol-function 'setenv)
                       (lambda (_name value &rest _) (setq external value)))
                      ((symbol-function 'nelisp-native-cache-load)
                       (lambda (input)
                         (should (equal external (plist-get job :cache)))
                         (if failure (error "Artifact refused") (funcall loader input)))))
              (if failure (should-error (nelisp-native-tier--finish job))
                (nelisp-native-tier--finish job))
              (should (equal external "parent-cache")))
          (delete-directory (plist-get job :directory) t))))))
(provide 'nelisp-native-tier-test)
;;; nelisp-native-tier-test.el ends here
