;;; exit-decoder-test.el --- Rooted exit decoder controls -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(let ((source (expand-file-name "../lisp/nelisp-native-load.el"
                                (file-name-directory load-file-name))))
  (with-temp-buffer
    (insert-file-contents source)
    (goto-char (point-min))
    (let (form)
      (condition-case nil
          (while t
            (setq form (read (current-buffer)))
            (when (and (eq (car-safe form) 'defun)
                       (eq (cadr form) 'nelisp-native-load-root-v2-resume-exit))
              (eval form t)))
        (end-of-file nil)))))

(ert-deftest nelisp-arithmetic-exit-scalar-refusal-before-access ()
  (let ((accesses 0))
    (cl-letf (((symbol-function 'nelisp-native-load-root-v2-addresses)
               (lambda (&rest _) (setq accesses (1+ accesses)))))
      (dolist (input '((nil 2 3) (1 nil 3) (1 2 nil) (1 0 3)
                       (1 2 0) (1 2 16382) (1 2 "3")))
        (should-error (apply #'nelisp-native-load-root-v2-resume-exit input)))
      (should (= accesses 0)))))

(ert-deftest nelisp-arithmetic-exit-exact-signal-and-throw ()
  (let ((kind 1) (tag 'wrong-type-argument) (payload (list 'numberp "bad")))
    (cl-letf (((symbol-function 'nelisp-native-load-root-v2-addresses)
               (lambda (&rest _) '(:environment 10 :slot 20)))
              ((symbol-function 'ptr-call)
               (lambda (_slot _env _ticket index &rest _) (+ 100 index)))
              ((symbol-function 'nelisp-native-load-unbox)
               (lambda (slot &rest _)
                 (cond ((= slot 103) kind) ((= slot 104) tag)
                       ((= slot 105) payload)))))
      (let ((observed (condition-case err
                          (nelisp-native-load-root-v2-resume-exit 10 2 3)
                        (wrong-type-argument err))))
        (should (eq (car observed) tag))
        (should (eq (cdr observed) payload)))
      (setq kind 2 tag (make-symbol "exit-tag"))
      (should (eq (catch tag (nelisp-native-load-root-v2-resume-exit 10 2 3)) payload))
      (setq kind "bad")
      (should-error (nelisp-native-load-root-v2-resume-exit 10 2 3)))))

(ert-deftest nelisp-arithmetic-exit-authenticated-address-refusal ()
  (let ((accesses 0) (environment 10) (slot 20) (returned nil))
    (cl-letf (((symbol-function 'nelisp-native-load-root-v2-addresses)
               (lambda (&rest _) (list :environment environment :slot slot)))
              ((symbol-function 'ptr-call)
               (lambda (&rest _) (setq accesses (1+ accesses)) returned)))
      (should-error (nelisp-native-load-root-v2-resume-exit 11 2 3))
      (should (= accesses 0))
      (dolist (invalid '(nil "20" 0 -1))
        (setq slot invalid)
        (should-error (nelisp-native-load-root-v2-resume-exit 10 2 3)))
      (should (= accesses 0))
      (setq slot 20)
      (should-error (nelisp-native-load-root-v2-resume-exit 10 2 3)
                    :type 'error))))

(ert-run-tests-batch-and-exit (or (getenv "NELISP_EXIT_TEST_SELECTOR") t))
