;;; nelisp-bytecode-ir-test.el --- Tests for bytecode structural decoder -*- lexical-binding: t; -*-

;; Copyright (C) 2026
;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Code:

(require 'ert)
(require 'bytecomp)
(require 'nelisp-bytecode-ir)

(defun nelisp-bytecode-ir-test--compiled-parts (form)
  (let ((function (byte-compile form)))
    (list (aref function 1) (aref function 2))))

(ert-deftest nelisp-bytecode-ir/decodes-cons-effect-without-general-lowering-credit ()
  (let* ((result (nelisp-bytecode-ir-validate
                  (unibyte-string 1 1 66 135) [] 2))
         (rows (plist-get result :instructions))
         (cons-row (aref rows 2)))
    (should (eq (plist-get result :status) 'unsupported))
    (should (equal (aref cons-row 1) 66))
    (should (equal (plist-get (aref cons-row 4) :stack-delta) -1))
    (should (eq (plist-get (plist-get result :stack-analysis) :status)
                'complete))))

(ert-deftest nelisp-bytecode-ir-emacs31-object-predicates-have-fixed-neutral-width ()
  (dolist (case '((symbolp 57) (consp 58) (stringp 59) (listp 60)))
    (let* ((operator (car case)) (opcode (cadr case))
           (function (byte-compile (list 'lambda '(x) (list operator 'x))))
           (code (aref function 1)) (constants (aref function 2))
           (result (nelisp-bytecode-ir-validate code constants 1))
           (rows (plist-get result :instructions)))
      (should (equal (string-to-list code) (list opcode 135)))
      (should (eq (plist-get result :status) 'valid))
      (should (= (length rows) 2))
      (should (equal (append (aref rows 0) nil)
                     (list 0 opcode 1 nil
                           '(:kind predicate :stack-delta 0 :lowerable t
                             :width 1))))
      (should (= (aref (aref rows 1) 0) 1))
      (should (= (aref (aref rows 1) 1) 135))
      (should (eq (plist-get (plist-get result :stack-analysis) :status)
                  'complete)))))

(ert-deftest nelisp-bytecode-ir-bytecomp-object-opcode-table-is-width-one ()
  ;; Names and stack effects mirror GNU Emacs 31.1 bytecomp.el byte-defop.
  (dolist (case '((56 nth -1) (61 eq -1) (62 memq -1) (63 not 0)
                  (64 car 0) (65 cdr 0) (66 cons -1) (67 list1 0)
                  (68 list2 -1) (69 list3 -2) (70 list4 -3) (71 length 0)
                  (72 aref -1) (73 aset -2) (74 symbol-value 0)
                  (75 symbol-function 0) (76 set -1) (77 fset -1)
                  (78 get -1) (79 substring -2) (80 concat2 -1)
                  (81 concat3 -2) (82 concat4 -3)))
    (let* ((opcode (nth 0 case)) (kind (nth 1 case)) (delta (nth 2 case))
           (result (nelisp-bytecode-ir-decode-result
                    (unibyte-string opcode 135) []))
           (rows (plist-get result :instructions))
           (metadata (aref (aref rows 0) 4)))
      (should (eq (plist-get result :status)
                  (if (memq kind '(eq car cdr)) 'valid 'unsupported)))
      (should (= (aref (aref rows 0) 2) 1))
      (should (eq (plist-get metadata :kind) kind))
      (should (= (plist-get metadata :stack-delta) delta))
      (should (eq (plist-get metadata :width) 1))
      (should (eq (plist-get metadata :lowerable)
                  (and (memq kind '(eq car cdr)) t))))))

(ert-deftest nelisp-bytecode-ir-symbol-value-set-get-have-structural-stack-contracts ()
  ;; Hand-authored streams avoid source compilation and never execute opcodes.
  (dolist (case '((74 [symbol] 1 0 symbol-value)
                  (76 [symbol value] 2 -1 set)
                  (78 [symbol property] 2 -1 get)))
    (let* ((opcode (nth 0 case)) (constants (nth 1 case))
           (minimum (nth 2 case)) (delta (nth 3 case)) (kind (nth 4 case))
           (code (cond ((= opcode 74) (unibyte-string 192 74 135))
                       ((= opcode 76) (unibyte-string 192 193 76 135))
                       (t (unibyte-string 192 193 78 135))))
           (result (nelisp-bytecode-ir-validate code constants 0))
           (row (aref (plist-get result :instructions)
                      (if (= opcode 74) 1 2)))
           (metadata (aref row 4)))
      (should (eq (plist-get result :status) 'unsupported))
      (should (eq (plist-get (plist-get result :stack-analysis) :status)
                  'complete))
      (should (= (aref row 1) opcode))
      (should (= (plist-get metadata :minimum-inputs) minimum))
      (should (= (plist-get metadata :stack-delta) delta))
      (should (eq (plist-get metadata :kind) kind))
      (should (eq (plist-get metadata :runtime-op) kind))
      (should (eq (plist-get metadata :may-signal) t))
      (should-not (plist-get metadata :lowerable))))
  (should (eq (plist-get (nelisp-bytecode-ir-decode-result
                          (unibyte-string 192 74 135) []) :status)
              'malformed)))

(ert-deftest nelisp-bytecode-ir-symbol-value-set-get-reject-stack-underflow-at-opcode ()
  (dolist (case '((74 0) (76 1) (78 1)))
    (let* ((opcode (car case)) (depth (cadr case))
           (result (nelisp-bytecode-ir-validate
                    (unibyte-string opcode 135) [] depth))
           (stack (plist-get result :stack-analysis)))
      (should (eq (plist-get result :status) 'malformed))
      (should (eq (plist-get stack :status) 'invalid))
      (should (string-match-p "minimum input" (plist-get stack :reason)))
      (should (string-match-p "at 0" (plist-get stack :reason))))))

(ert-deftest nelisp-bytecode-ir-host-car-cons-and-eq-use-mapped-object-opcodes ()
  (dolist (case '(((lambda (x) (car x)) 64 car 0 1)
                  ((lambda (x y) (cons x y)) 66 cons -1 2)
                  ((lambda (x y) (eq x y)) 61 eq -1 2)))
    (let* ((function (byte-compile (car case)))
           (opcode (nth 1 case)) (kind (nth 2 case)) (delta (nth 3 case))
           (arity (nth 4 case))
           (result (nelisp-bytecode-ir-validate
                    (aref function 1) (aref function 2) arity))
           (rows (plist-get result :instructions))
           (row (cl-find-if (lambda (item) (= (aref item 1) opcode)) rows))
           (metadata (and row (aref row 4))))
      (should (byte-code-function-p function))
      (should row)
      (should (eq (plist-get metadata :kind) kind))
      (should (= (plist-get metadata :stack-delta) delta))
      (should (eq (plist-get metadata :lowerable)
                  (and (memq kind '(eq car cdr)) t)))
      (should (eq (plist-get (plist-get result :stack-analysis) :status)
                  'complete)))))

(ert-deftest nelisp-bytecode-ir-host-eq-is-the-generic-object-opcode-61 ()
  (let* ((function (byte-compile '(lambda (x y) (eq x y))))
         (code (aref function 1))
         (result (nelisp-bytecode-ir-validate code (aref function 2) 2))
         (rows (plist-get result :instructions))
         (row (cl-find-if (lambda (instruction) (= (aref instruction 1) 61))
                          rows)))
    (should (equal (string-to-list code) '(1 1 61 135)))
    (should (eq (plist-get result :status) 'valid))
    (should row)
    (should (eq (plist-get (aref row 4) :kind) 'eq))
    (should (= (plist-get (aref row 4) :stack-delta) -1))
    (should (plist-get (aref row 4) :lowerable))
    (should (= (plist-get (plist-get result :stack-analysis) :max-depth) 4))))

(ert-deftest nelisp-bytecode-ir-object-opcode-stream-rejects-stack-underflow ()
  (let ((result (nelisp-bytecode-ir-validate (unibyte-string 64 135) [] 0)))
    (should (eq (plist-get result :status) 'malformed))
    (should (string-match-p "underflow" (plist-get result :reason)))))

(ert-deftest nelisp-bytecode-ir-bytecomp-opcodes-147-through-168-have-fixed-metadata ()
  ;; Names and stack effects mirror GNU Emacs 31.1 bytecomp.el byte-defop.
  (dolist (case '((147 set-marker -2) (148 match-beginning 0)
                  (149 match-end 0) (150 upcase 0) (151 downcase 0)
                  (152 string= -1) (153 string< -1) (154 equal -1)
                  (155 nthcdr -1) (156 elt -1) (157 member -1)
                  (158 assq -1) (159 nreverse 0) (160 setcar -1)
                  (161 setcdr -1) (162 car-safe 0) (163 cdr-safe 0)
                  (164 nconc -1) (165 quo -1) (166 rem -1)
                  (167 numberp 0) (168 integerp 0)))
    (let* ((opcode (nth 0 case)) (kind (nth 1 case)) (delta (nth 2 case))
           (result (nelisp-bytecode-ir-decode-result
                    (unibyte-string opcode 135) []))
           (row (aref (plist-get result :instructions) 0))
           (metadata (aref row 4)))
      (should (eq (plist-get result :status)
                  (if (= opcode 168) 'valid 'unsupported)))
      (should (= (aref row 2) 1))
      (should (eq (plist-get metadata :kind) kind))
      (should (= (plist-get metadata :stack-delta) delta))
      (should (= (plist-get metadata :width) 1))
      (should (eq (plist-get metadata :lowerable) (= opcode 168))))))

(ert-deftest nelisp-bytecode-ir-buffer-and-control-opcodes-have-fixed-metadata ()
  (dolist (case '((96 point 1) (97 save-current-buffer 0 obsolete)
                  (98 goto-char 0) (99 insert 0) (100 point-max 1)
                  (101 point-min 1) (102 char-after 0) (103 following-char 1)
                  (104 preceding-char 1) (105 current-column 1) (106 indent-to 0)
                  (107 scan-buffer 0 obsolete) (108 eolp 1) (109 eobp 1)
                  (110 bolp 1) (111 bobp 1) (112 current-buffer 1)
                  (113 set-buffer 0) (114 save-current-buffer 0)
                  (115 set-mark 0 obsolete) (116 interactive-p 1 obsolete)
                  (117 forward-char 0) (118 forward-word 0)
                  (119 skip-chars-forward -1) (120 skip-chars-backward -1)
                  (121 forward-line 0) (122 char-syntax 0)
                  (123 buffer-substring -1) (124 delete-region -1)
                  (125 narrow-to-region -1) (126 widen 1) (127 end-of-line 0)
                  (136 discard -1)
                  (138 save-excursion 0) (139 save-window-excursion 0 obsolete)
                  (140 save-restriction 0) (141 catch -1 obsolete)
                  (142 unwind-protect -1) (143 condition-case -2 obsolete)
                  (144 temp-output-buffer-setup 0 obsolete)
                  (145 temp-output-buffer-show -1 obsolete)))
    (let* ((op (nth 0 case)) (kind (nth 1 case)) (delta (nth 2 case))
           (result (nelisp-bytecode-ir-decode-result
                    (unibyte-string op 135) []))
           (row (aref (plist-get result :instructions) 0))
           (meta (aref row 4)))
      (should (eq (plist-get result :status) 'unsupported))
      (should (= (aref row 2) 1))
      (should (eq (plist-get meta :kind) kind))
      (should (= (plist-get meta :stack-delta) delta))
      (should-not (plist-get meta :lowerable))
      (should (eq (not (null (plist-get meta :obsolete)))
                  (and (nth 3 case) t))))))

(ert-deftest nelisp-bytecode-ir-counted-and-switch-opcodes-are-structural-only ()
  (dolist (op '(175 176 177))
    (let* ((code (unibyte-string op 4 135))
           (result (nelisp-bytecode-ir-decode-result code []))
           (row (aref (plist-get result :instructions) 0))
           (meta (aref row 4)))
      (should (eq (plist-get result :status) 'unsupported))
      (should (= (aref row 2) 2))
      (should (= (aref row 3) 4))
      (should (= (plist-get meta :stack-delta) -3))
      (should (= (plist-get meta :count) 4))
      (should (= (plist-get meta :operand-width) 1))
      (should-not (plist-get meta :lowerable))))
  (let* ((discard (nelisp-bytecode-ir-decode-result
                   (unibyte-string 182 #x83 135) []))
         (discard-row (aref (plist-get discard :instructions) 0))
         (switch (nelisp-bytecode-ir-validate (unibyte-string 183 135) [] 2))
         (switch-row (aref (plist-get switch :instructions) 0)))
    (should (= (aref discard-row 2) 2))
    (should (= (plist-get (aref discard-row 4) :stack-delta) -3))
    (should (plist-get (aref discard-row 4) :preserve-top))
    (should (eq (plist-get (aref switch-row 4) :control-flow) 'table-driven))
    (should (= (plist-get (aref switch-row 4) :stack-delta) -2))
    (should-not (plist-get (aref switch-row 4) :lowerable))
    (should (eq (plist-get switch :status) 'unsupported))
    (should (eq (plist-get (plist-get switch :stack-analysis) :status) 'unknown))
    (should (equal (plist-get (plist-get switch :stack-analysis) :reason)
                   "handler or table-driven transfer has dynamic control flow"))
    (should-not (nelisp-bytecode-ir-cfg-valid-p
                 (append (plist-get switch :instructions) nil) 2)))
  (dolist (code (list (unibyte-string 175) (unibyte-string 176)
                      (unibyte-string 177) (unibyte-string 182)))
    (should (eq (plist-get (nelisp-bytecode-ir-decode-result code []) :status)
                'malformed)))
  (dolist (code (list (unibyte-string 130 4 0 175 2 135)
                      (unibyte-string 130 4 0 176 2 135)
                      (unibyte-string 130 4 0 177 2 135)
                      (unibyte-string 130 4 0 182 2 135)))
    (should (string-match-p
             "not an instruction boundary"
             (plist-get (nelisp-bytecode-ir-validate code [] 2) :reason)))))

(ert-deftest nelisp-bytecode-ir-host-compiled-fixtures-cover-listn-concatn-insertn-point ()
  (dolist (fixture '(((lambda () (point)) 96)
                     ((lambda (a b c d e f) (list a b c d e f)) 175)
                     ((lambda (a b c d e f) (concat a b c d e f)) 176)
                     ((lambda (a b c d e f) (insert a b c d e f)) 177)))
    (let* ((function (byte-compile (car fixture)))
           (result (nelisp-bytecode-ir-decode-result
                    (aref function 1) (aref function 2)))
           (opcode (cadr fixture))
           (row (cl-find-if (lambda (insn) (= (aref insn 1) opcode))
                            (plist-get result :instructions))))
      (should (byte-code-function-p function))
      (should row)
      (should-not (plist-get (aref row 4) :lowerable)))))

(ert-deftest nelisp-bytecode-ir-host-assq-and-stack-set-bytecode-match-widths ()
  (let* ((assq-function (byte-compile '(lambda (key alist) (assq key alist))))
         (assq-result (nelisp-bytecode-ir-decode-result
                       (aref assq-function 1) (aref assq-function 2)))
         (assq-row (cl-find-if (lambda (row) (= (aref row 1) 158))
                               (plist-get assq-result :instructions)))
         (stack-set-function
          (byte-compile '(lambda (x)
                           (let ((a x) (b x) (c x)) (setq a c) a))))
         (code (aref stack-set-function 1))
         (result (nelisp-bytecode-ir-decode-result code
                                                   (aref stack-set-function 2)))
         (row (cl-find-if (lambda (item) (= (aref item 1) 178))
                          (plist-get result :instructions))))
    (should assq-row)
    (should (eq (plist-get (aref assq-row 4) :kind) 'assq))
    (should-not (plist-get (aref assq-row 4) :lowerable))
    (should row)
    (should (= (aref row 2) (+ (aref row 0) 2)))
    (should (= (aref row 3) (aref code (1+ (aref row 0)))))
    (should (= (plist-get (aref row 4) :stack-offset) (aref row 3)))
    (should (= (plist-get (aref row 4) :operand-width) 1))
    (should (= (plist-get (aref row 4) :stack-delta) -1))
    (should-not (plist-get (aref row 4) :lowerable))))

(ert-deftest nelisp-bytecode-ir-stack-set-width-endian-and-truncation ()
  (let* ((code (unibyte-string 178 9 179 2 1 135))
         (result (nelisp-bytecode-ir-decode-result code []))
         (rows (plist-get result :instructions)))
    (should (eq (plist-get result :status) 'unsupported))
    (should (equal (list (aref (aref rows 0) 2) (aref (aref rows 0) 3))
                   '(2 9)))
    (should (equal (list (aref (aref rows 1) 2) (aref (aref rows 1) 3))
                   '(5 258)))
    (should (eq (plist-get (aref (aref rows 0) 4) :kind) 'stack-set))
    (should (= (plist-get (aref (aref rows 0) 4) :width) 2))
    (should (= (plist-get (aref (aref rows 0) 4) :stack-offset) 9))
    (should-not (plist-get (aref (aref rows 0) 4) :lowerable))
    (should (= (plist-get (aref (aref rows 1) 4) :operand-width) 2))
    (should (eq (plist-get (aref (aref rows 1) 4) :kind) 'stack-set))
    (should (= (plist-get (aref (aref rows 1) 4) :width) 3))
    (should (= (plist-get (aref (aref rows 1) 4) :stack-offset) 258))
    (should (= (plist-get (aref (aref rows 1) 4) :stack-delta) -1))
    (should-not (plist-get (aref (aref rows 1) 4) :lowerable)))
  (dolist (code (list (unibyte-string 178) (unibyte-string 179 1)))
    (let ((result (nelisp-bytecode-ir-decode-result code [])))
      (should (eq (plist-get result :status) 'malformed))
      (should (string-match-p "truncated" (plist-get result :reason))))))

(ert-deftest nelisp-bytecode-ir-branches-cannot-target-stack-set-operands ()
  (dolist (code (list (unibyte-string 130 4 0 178 0 135)
                      (unibyte-string 130 4 0 179 1 0 135)))
    (let ((result (nelisp-bytecode-ir-validate code [] 2)))
      (should (eq (plist-get result :status) 'malformed))
      (should (string-match-p "not an instruction boundary"
                              (plist-get result :reason))))))

(ert-deftest nelisp-bytecode-ir-compiled-arithmetic-has-known-stack-depth ()
  (let* ((parts (nelisp-bytecode-ir-test--compiled-parts '(lambda (x) (+ x 1))))
         (result (nelisp-bytecode-ir-decode-result (car parts) (cadr parts)))
         (instructions (plist-get result :instructions))
         (stack (nelisp-bytecode-ir-analyze-stack instructions 1)))
    (should (eq (plist-get result :status) 'valid))
    (should (equal (mapcar (lambda (row) (list (aref row 0) (aref row 1)
                                                (aref row 2)))
                           (append instructions nil))
                   '((0 84 1) (1 135 2))))
    (should (eq (plist-get stack :status) 'complete))
    (should (= (plist-get stack :max-depth) 1))))

(ert-deftest nelisp-bytecode-ir-compiled-branch-validates-targets-and-depths ()
  (let* ((parts (nelisp-bytecode-ir-test--compiled-parts '(lambda (x) (if x 1 2))))
         (result (nelisp-bytecode-ir-decode-result (car parts) (cadr parts)))
         (instructions (plist-get result :instructions))
         (stack (nelisp-bytecode-ir-analyze-stack instructions 1)))
    (should (eq (plist-get result :status) 'valid))
    (should-not (nelisp-bytecode-ir-validate-targets instructions (length (car parts))))
    (should (eq (plist-get stack :status) 'complete))
    (should (= (plist-get stack :max-depth) 2))
    (should (nelisp-bytecode-ir-cfg-valid-p (append instructions nil)
                                             (length (car parts))))))

(ert-deftest nelisp-bytecode-ir-compiled-catch-is-structural-but-not-lowerable ()
  (let* ((parts (nelisp-bytecode-ir-test--compiled-parts '(lambda () (catch 'k 17))))
         (result (nelisp-bytecode-ir-decode-result (car parts) (cadr parts)))
         (instructions (plist-get result :instructions))
         (stack (nelisp-bytecode-ir-analyze-stack instructions 0)))
    (should (eq (plist-get result :status) 'unsupported))
    (should-not (plist-get (aref (aref instructions 1) 4) :lowerable))
    (should-not (nelisp-bytecode-ir-validate-targets instructions (length (car parts))))
    (should (eq (plist-get stack :status) 'unknown))
    (should (equal (plist-get stack :reason)
                   "handler or table-driven transfer has dynamic control flow"))))

(ert-deftest nelisp-bytecode-ir-compiled-condition-case-recognizes-handler-width ()
  (let* ((parts (nelisp-bytecode-ir-test--compiled-parts
                 '(lambda () (condition-case nil (error "x") (error 17)))))
         (result (nelisp-bytecode-ir-decode-result (car parts) (cadr parts)))
         (instructions (plist-get result :instructions))
         (stack (nelisp-bytecode-ir-analyze-stack instructions 0)))
    (should (eq (plist-get result :status) 'unsupported))
    (should (eq (aref (aref instructions 1) 1) 49))
    (should (eq (aref (aref instructions 5) 1) 48))
    (should-not (nelisp-bytecode-ir-validate-targets instructions (length (car parts))))
    (should (eq (plist-get stack :status) 'unknown))
    (should (nelisp-bytecode-ir-cfg-valid-p (append instructions nil)
                                             (length (car parts))))))

(ert-deftest nelisp-bytecode-ir-stack-ref-6-and-7-have-upstream-widths ()
  (let* ((code (string-as-unibyte (unibyte-string 6 4 7 1 1 135)))
         (result (nelisp-bytecode-ir-decode-result code []))
         (rows (plist-get result :instructions)))
    (should (eq (plist-get result :status) 'unsupported))
    (should (= (length rows) 3))
    (should (equal (append (aref rows 0) nil) '(0 6 2 4 (:kind stack-ref :stack-delta 1 :lowerable nil :stack-offset 4))))
    (should (equal (append (aref rows 1) nil) '(2 7 5 257 (:kind stack-ref :stack-delta 1 :lowerable nil :stack-offset 257))))
    (should (equal (append (aref rows 2) nil) '(5 135 6 nil (:kind return :stack-delta -1 :lowerable t))))))

(ert-deftest nelisp-bytecode-ir-compact-families-decode-fetch-fetch2-operands ()
  (dolist (case '((14 4 2 6 1 unsupported) (15 257 3 7 1 unsupported)
                  (22 4 2 6 -1 unsupported) (23 257 3 7 -1 unsupported)
                  (30 4 2 6 -1 unsupported) (31 257 3 7 -1 unsupported)
                  (38 4 2 6 -4 unsupported) (39 257 3 7 -257 unsupported)
                  (46 4 2 6 0 unsupported) (47 257 3 7 0 unsupported)))
    (let* ((opcode (nth 0 case)) (operand (nth 1 case))
           (width (nth 2 case)) (immediate (nth 3 case))
           (delta (nth 4 case)) (expected-status (nth 5 case))
           (bytes (if (= immediate 6)
                      (list opcode operand 135)
                    (list opcode (logand operand 255)
                          (ash operand -8) 135)))
           (result (nelisp-bytecode-ir-decode-result
                    (apply #'unibyte-string bytes)
                    (if (memq opcode '(30 31))
                        (make-vector (1+ operand) 'frame-ir-variable)
                      [])))
           (insn (aref (plist-get result :instructions) 0)))
      (should (eq (plist-get result :status) expected-status))
      (should (= (aref insn 2) width))
      (should (= (aref insn 3) operand))
      (should (= (plist-get (aref insn 4) :compact-index) immediate))
      (should (= (plist-get (aref insn 4) :stack-delta) delta))))
  (should (eq (plist-get (nelisp-bytecode-ir-decode-result
                          (unibyte-string 14) []) :status) 'malformed))
  (should (eq (plist-get (nelisp-bytecode-ir-decode-result
                          (unibyte-string 15 1) []) :status) 'malformed)))

(ert-deftest nelisp-bytecode-ir-truncated-extended-stack-ref-is-malformed ()
  (should (eq (plist-get (nelisp-bytecode-ir-decode-result
                          (unibyte-string 6) []) :status) 'malformed))
  (should (eq (plist-get (nelisp-bytecode-ir-decode-result
                          (unibyte-string 7 1) []) :status) 'malformed)))

(ert-deftest nelisp-bytecode-ir-constant2-is-little-endian-and-bounded ()
  (let* ((code (unibyte-string 129 1 0 135))
         (result (nelisp-bytecode-ir-decode-result code [10 11])))
    (should (eq (plist-get result :status) 'valid))
    (should (= (aref (aref (plist-get result :instructions) 0) 3) 11))
    (should (eq (plist-get (nelisp-bytecode-ir-decode-result
                            (unibyte-string 129 2 0 135) [10 11]) :status)
                'malformed))))

(ert-deftest nelisp-bytecode-ir-rejects-branch-into-operand ()
  (let* ((code (unibyte-string 131 2 0 192 135))
         (rows (nelisp-bytecode-ir-decode-instructions code [x])))
    (should rows)
    (should (string-match-p "not an instruction boundary"
                            (nelisp-bytecode-ir-validate-targets rows (length code))))
    (should (eq (plist-get (nelisp-bytecode-ir-validate code [x] 0) :status)
                'malformed))
    (should-not (nelisp-bytecode-ir-cfg-valid-p rows (length code)))))

(ert-deftest nelisp-bytecode-ir-rejects-branch-into-compact-fetch-operand ()
  (let* ((code (unibyte-string 130 4 0 14 135 135))
         (result (nelisp-bytecode-ir-decode-result code []))
         (instructions (plist-get result :instructions)))
    (should (eq (plist-get result :status) 'unsupported))
    (should (= (aref (aref instructions 1) 2) 5))
    (should (string-match-p "not an instruction boundary"
                            (nelisp-bytecode-ir-validate-targets
                             instructions (length code))))))

(ert-deftest nelisp-bytecode-ir-rejects-reserved-opcodes-and-stack-underflow ()
  (should (eq (plist-get (nelisp-bytecode-ir-decode-result
                          (unibyte-string 184) []) :status) 'malformed))
  (let* ((decoded (nelisp-bytecode-ir-decode-result (unibyte-string 83 135) []))
         (stack (nelisp-bytecode-ir-analyze-stack
                 (plist-get decoded :instructions) 0)))
    (should (eq (plist-get stack :status) 'invalid))
    (should (string-match-p "underflow" (plist-get stack :reason)))))

(ert-deftest nelisp-bytecode-ir-gnu31-and-decoder-reject-opcode-zero-as-malformed ()
  (skip-unless (string-match-p "\\`31\\.1\\(?:\\'\\|[.-]\\)" emacs-version))
  (let* ((code (unibyte-string 0))
         (gnu-error (should-error (byte-code code [] 1) :type 'error))
         (decoded (nelisp-bytecode-ir-decode-result code [])))
    (should (string-match-p "Invalid byte opcode: op=0"
                            (error-message-string gnu-error)))
    (should (eq (plist-get decoded :status) 'malformed))
    (should (equal (plist-get decoded :reason) "reserved opcode 0"))
    (should (= (length (plist-get decoded :instructions)) 0))))

(ert-deftest nelisp-bytecode-ir-proves-single-backedge-loop-stack-depth ()
  (let* ((function
          (byte-compile
           '(lambda (n) (let ((i 0)) (while (< i n) (setq i (1+ i))) i))))
         (code (aref function 1))
         (decoded (nelisp-bytecode-ir-validate code (aref function 2) 1))
         (loop (nelisp-bytecode-ir-single-backedge-loop
                (plist-get decoded :instructions) (length code) 1)))
    (should (eq (plist-get (plist-get decoded :stack-analysis) :status)
                'complete))
    (should (= (plist-get loop :header) 1))
    (should (= (plist-get loop :backedge) 8))
    (should (= (plist-get loop :stack-depth) 2))
    (should (plist-get loop :continue-on-true))))

(provide 'nelisp-bytecode-ir-test)
;;; nelisp-bytecode-ir-test.el ends here
