;;; nelisp-cl-loop-all-any-parity-smoke.el --- host/VM parity probe  -*- lexical-binding: t; -*-
;; Evaluated by both GNU Emacs and the standalone binary; the printed
;; transcripts must be identical (see the .sh wrapper).
(defmacro np--t (form)
  `(princ (format "%S => %S\n" ',form (condition-case e ,form (error e)))))
;; all / any
(np--t (all #'identity '(1 2 3)))
(np--t (all #'identity nil))
(np--t (all #'identity '(1 nil 3)))
(np--t (all #'null '(nil nil)))
(np--t (all #'ignore '(1)))
(np--t (all #'identity '(1 . 2)))
(np--t (all #'identity [1 2]))
(np--t (all #'identity 5))
(np--t (all #'identity "ab"))
(np--t (all 1 nil))
(np--t (let ((n 0)) (list (all (lambda (x) (setq n (1+ n)) (> x 1)) '(2 3 0 4 5)) n)))
(np--t (any #'identity '(nil 3 4)))
(np--t (any #'identity nil))
(np--t (any #'ignore '(1 2)))
(np--t (any #'identity '(1 2 . 3)))
(np--t (any #'ignore '(1 2 . 3)))
(np--t (any #'identity [1 2]))
(np--t (any #'identity "ab"))
(np--t (any (lambda (x) (and (> x 1) (* x 10))) '(1 2 3)))
;; cl-loop for VAR in-ref LIST
(np--t (let ((l (list 1 2 3))) (cl-loop for x in-ref l do (setf x (* x 10))) l))
(np--t (let ((l (list 1 2 3))) (cl-loop for x in-ref l do (cl-incf x 5)) l))
(np--t (let ((l (list 1 2 3))) (cl-loop for x in-ref l collect x)))
(np--t (let ((l (list 1 2 3))) (cl-loop for x in-ref l when (= x 2) do (setf x 'two)) l))
(np--t (let ((l (list (list 1 2 3) 'a (list 4 5 6))))
         (cl-loop for el in-ref l
                  when (and (listp el) (eq (nth 1 el) 2))
                  do (setf (nth 2 el) 'hit) and return nil)
         l))
(np--t (let ((l (list (list 1 2 3) (list 1 2 3))))
         (cl-loop for el in-ref l
                  when (eq (nth 1 el) 2)
                  do (setf (nth 2 el) 'hit) and return nil)
         l))
(np--t (let ((l (list 1 2 3 4))) (cl-loop for x in-ref l by #'cddr do (setf x 0)) l))
(np--t (let ((l nil)) (cl-loop for x in-ref l do (setf x 1)) l))
(np--t (let ((l (list 1 2)) (m (list 10 20 30))) (cl-loop for x in-ref l for y in m do (setf x (+ x y))) l))
;; finally / return
(np--t (cl-loop for table in '(1 2 3) when (memq table '(9)) return nil finally return t))
(np--t (cl-loop for table in '(1 2 3) when (eq table 2) return nil finally return t))
(np--t (cl-loop for x in '(1 2 3) finally return 'done))
(np--t (cl-loop for x in '(1 2 3) collect x finally return 'done))
(np--t (let ((n 0)) (cl-loop for x in '(1 2 3) do (setq n (+ n x)) finally return n)))
(np--t (let ((n 0)) (list (cl-loop for x in '(1 2 3) do (setq n (+ n x)) finally do (setq n (* n 10))) n)))
(np--t (let ((n 0)) (list (cl-loop for x in '(1 2 3) do (setq n (+ n x)) finally (setq n (* n 10))) n)))
(np--t (let ((n 0)) (list (cl-loop for x in '(1 2 3) when (= x 2) return 'early finally (setq n 99)) n)))
(np--t (cl-loop for x in '(1 2 3) sum x finally return 'v))
(np--t (cl-loop for x in '(1 2 3) sum x))
(np--t (cl-loop for x across [1 2 3] when (> x 5) return 'big finally return 'small))
(np--t (cl-loop for x in '(a b) for i from 0 collect (cons i x) finally return 'x))
;; printing of byte-code objects (docstring newlines raw, code string octal)
(np--t (make-byte-code 257 "\207" [] 2 "\n\n(fn X)"))
(np--t (list (make-byte-code 257 "\207" [] 2) (make-byte-code 0 "\300\207" [x] 1 nil '(interactive))))
(np--t (advice--cd*r #'car))
;;; nelisp-cl-loop-all-any-parity-smoke.el ends here
