;;; nelisp-native-windows-test.el --- Host Win64 native prerequisites -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'ert)
(require 'bytecomp)
(require 'nelisp-aot-compiler)
(require 'nelisp-bytecode-native-rooted-cfg-contract)
(require 'nelisp-native-load)

(defun nelisp-native-windows-test--contains (text bytes)
  (string-match-p (regexp-quote (apply #'unibyte-string bytes)) text))

(defun nelisp-native-windows-test--bridge (format)
  (nelisp-aot-compile-to-link-unit
   '(defun probe (a b c d e f)
      (extern-call nl_native_funcall_v2 a b c d e f))
   :arch 'x86_64 :format format))

(ert-deftest nelisp-native-windows-six-word-bridge-reference-bytes ()
  "Win64 receives four registers, spills two stack arguments and reserves shadow."
  (let ((text (plist-get (nelisp-native-windows-test--bridge 'coff) :text)))
    (should (equal (substring text 0 4) (unibyte-string #x55 #x48 #x89 #xe5)))
    ;; Incoming word 1 is RCX, not RDI; word 5 is at rbp+48 after push rbp.
    (should (nelisp-native-windows-test--contains text '(#x48 #x89 #x4d #xf8)))
    (should (nelisp-native-windows-test--contains text '(#x48 #x8b #x45 #x30)))
    (should (nelisp-native-windows-test--contains text '(#x48 #x8b #x45 #x38)))
    ;; Six GP words need 32 shadow bytes plus two stack words.
    (should (nelisp-native-windows-test--contains text '(#x48 #x81 #xec #x30 0 0 0)))
    (should (nelisp-native-windows-test--contains text '(#x48 #x81 #xc4 #x30 0 0 0)))
    (should (equal (substring text -5) (unibyte-string #x48 #x89 #xec #x5d #xc3)))))

(ert-deftest nelisp-native-windows-abi-negative-control ()
  "The same reference check must reject a SysV unit and corrupted bytes."
  (let* ((windows (plist-get (nelisp-native-windows-test--bridge 'coff) :text))
         (linux (plist-get (nelisp-native-windows-test--bridge 'elf) :text))
         (reference '(#x48 #x89 #x4d #xf8)))
    (should-not (equal windows linux))
    (should (nelisp-native-windows-test--contains windows reference))
    (should-not (nelisp-native-windows-test--contains linux reference))
    (let ((offset (string-match (regexp-quote (apply #'unibyte-string reference)) windows)))
      (aset windows offset #x90)
      (should-not (nelisp-native-windows-test--contains windows reference)))))

(ert-deftest nelisp-native-windows-f1-canonical-emitter ()
  "Compile the actual rooted F1 form to a pre-writer Win64 unit on Linux."
  (should (equal emacs-version "31.1"))
  (let* ((byte-compile-warnings nil)
         (function (byte-compile '(lambda (x) (f1-user (cons (car x) (cdr x))))))
         (input (nelisp-bytecode-compiler-input-build function))
         (plan (nelisp-bytecode-native-rooted-cfg-plan input))
         (emitted (nelisp-bytecode-native-rooted-cfg-shared-emit-build
                   plan nelisp-bytecode-native-rooted-cfg-contract-shared-entry))
         (source (plist-get emitted :form))
         (unit (nelisp-aot-compile-to-link-unit source :arch 'x86_64 :format 'coff))
         (text (plist-get unit :text))
         (relocs (plist-get unit :relocs)))
    (should (eq (plist-get plan :status) 'complete))
    (should (eq (plist-get emitted :status) 'complete))
    (should-not (plist-get emitted :additional-source))
    (should (= 4 (cl-count "nl_native_funcall_v2" relocs
                          :key (lambda (r) (plist-get r :symbol)) :test #'equal)))
    (should (member "nl_root_pin_slot_v2" (plist-get unit :extern-symbols)))
    (should (nelisp-native-windows-test--contains text '(#x48 #x89 #x4d #xf8)))
    (should (nelisp-native-windows-test--contains text '(#x48 #x81 #xec #x30 0 0 0)))
    (should (equal (substring text -5) (unibyte-string #x48 #x89 #xec #x5d #xc3)))))

(provide 'nelisp-native-windows-test)
;;; nelisp-native-windows-test.el ends here

(require 'nelisp-native-windows)
(require 'nelisp-native-pe-symbols)

(ert-deftest nelisp-native-windows-cache-acl-negative-controls ()
  (let* ((user "S-1-5-21-1")
         (ace (list :type 0 :flags 0 :mask #x1f01ff :sid user)))
    (should (nelisp-native-windows-security-trusted-p user user #x1004 (list ace) #x10))
    (should-not (nelisp-native-windows-security-trusted-p "S-1-5-21-2" user #x1004 (list ace) #x10))
    (should-not (nelisp-native-windows-security-trusted-p user user #x1004
                 (list ace (list :type 0 :flags 0 :mask 2 :sid "S-1-1-0")) #x10))
    (should-not (nelisp-native-windows-security-trusted-p user user #x1004 (list ace) #x410))
    (should-not (nelisp-native-windows-security-trusted-p user user 4 (list ace) #x10))
    (should-not (nelisp-native-windows-security-trusted-p user user #x1004
                  (list (plist-put (copy-sequence ace) :flags 16)) #x10))
    (should-not (nelisp-native-windows-security-trusted-p user user #x1004 nil #x10))))

(defun nelisp-native-windows-test--trusted-fixture ()
  "A structurally valid decode fixture; it is never executed."
  (let* ((abi (nelisp-native-load--runtime-abi-v2))
         (manifest (list :format nelisp-native-load-raw-artifact-format-v2 :runtime-abi abi
                         :target (nelisp-native-load--target-v2)
                         :gc-table-magic nelisp-native-load-raw-gc-table-magic :gc-table-count 1
                         :gc-entries '((:name "gc-entry" :arity 0 :index 0))
                         :native (list :raw-abi abi :text-base64 (base64-encode-string (make-string 16 0) t)
                                       :text-size 16 :object-size 16
                                       :imports '((:name "bridge" :kind func))
                                       :relocs '((:offset 4 :type pc32 :symbol "bridge" :addend -4))
                                       :exports '((:name "probe" :value 0 :size 1 :arity 0)
                                                  (:name "gc-entry" :value 1 :size 1 :arity 0))))))
    (plist-put manifest :artifact-sha256 (secure-hash 'sha256 (prin1-to-string manifest)))))

(ert-deftest nelisp-native-windows-target-and-relocation-refuse-before-map ()
  (let ((system-type 'windows-nt) (allocations 0))
    (cl-letf (((symbol-function 'nelisp-native-load--mmap)
               (lambda (&rest _) (setq allocations (1+ allocations)) (error "unexpected map")))
              ((symbol-function 'nelisp-native-load--raw-v2-contract) (lambda () '(("gc-entry" . 0)))))
      (let ((manifest (nelisp-native-windows-test--trusted-fixture)))
        ;; A valid baseline proves the refusal is not another malformed-field error.
        (should (= 16 (length (nelisp-native-load--raw-v2-trusted-decode manifest "probe"))))
        (setf (plist-get manifest :runtime-abi) nelisp-native-load-raw-runtime-abi-v2)
        (should (equal (cadr (should-error (nelisp-native-load-raw-v2-artifact-trusted manifest "probe" nil)))
                       "nelisp-native-load: trusted target/ABI refused")))
      (let* ((manifest (nelisp-native-windows-test--trusted-fixture))
             (relocation (car (plist-get (plist-get manifest :native) :relocs))))
        (setf (plist-get relocation :addend) 2147483647)
        (setf (plist-get manifest :artifact-sha256)
              (secure-hash 'sha256 (prin1-to-string (nelisp-native-load--raw-plist-without manifest :artifact-sha256))))
        (should (equal (cadr (should-error (nelisp-native-load-raw-v2-artifact-trusted manifest "probe" nil)))
                       "nelisp-native-load: trusted relocation refused")))
      (should (= allocations 0)))))

(ert-deftest nelisp-native-windows-map-publication-and-release ()
  "Host simulation verifies API order, R/RX and original reservation release."
  (let ((calls nil) (protection 0))
    (cl-letf (((symbol-function 'nelisp-native-windows-buffer) (lambda (_) 4096))
              ((symbol-function 'nelisp-native-windows-free) (lambda (a) (push (list "free" a) calls)))
              ((symbol-function 'ptr-read-u32) (lambda (_a _off) protection))
              ((symbol-function 'nelisp-native-windows-call)
               (lambda (name &rest args)
                 (push (cons name args) calls)
                 (cond ((equal name "VirtualAlloc") 65536)
                       ((equal name "VirtualProtect") (setq protection (nth 2 args)) 1)
                       ((equal name "VirtualQuery") 48)
                       ((equal name "GetCurrentProcess") -1)
                       (t 1)))))
      (should (= 65536 (nelisp-native-windows-map 4096)))
      (should (= 0 (nelisp-native-windows-protect 65536 4096 1)))
      (should (= 0 (nelisp-native-windows-protect 65536 4096 5)))
      (should-error (nelisp-native-windows-protect 65536 4096 7))
      (should (= 0 (nelisp-native-windows-unmap 65536 4096)))
      (should (member '("VirtualAlloc" 0 4096 12288 4) calls))
      (should (member '("VirtualProtect" 65536 4096 2 4096) calls))
      (should (member '("VirtualProtect" 65536 4096 32 4096) calls))
      (should (member '("FlushInstructionCache" -1 65536 4096) calls))
      (should (equal (car calls) '("free" 65536))))))

(ert-deftest nelisp-native-windows-module-path-truncation-and-surrogates ()
  (let ((allocated 0) (freed 0) (count 32768))
    (cl-letf (((symbol-function 'nelisp-native-windows-buffer) (lambda (_) (setq allocated (1+ allocated)) 1))
              ((symbol-function 'nelisp-native-windows-free) (lambda (_) (setq freed (1+ freed))))
              ((symbol-function 'nelisp-native-windows-call) (lambda (&rest _) count))
              ((symbol-function 'ptr-read-u8) (lambda (_a off) (if (= off 1) #xd8 0))))
      (should-error (nelisp-native-windows-module-path))
      (setq count 1)
      (should-error (nelisp-native-windows-module-path))
      (should (= allocated freed)))))

(ert-deftest nelisp-native-windows-final-pe-symbols-and-mutation ()
  "Generate a PE, decode actual COFF ownership and refuse mutated section/symbol bounds."
  (require 'nelisp-static-linker)
  (let* ((file (make-temp-file "windows-symbols-" nil ".exe"))
         (unit (nelisp-aot-compile-to-link-unit '(defun _start () 42) :arch 'x86_64 :format 'coff)))
    (unwind-protect
        (progn
          (nelisp-link-units-pe32 file
            (list (nelisp-link-unit-make "probe.obj" (list (cons 'text (plist-get unit :text)))
                                        (plist-get unit :symbols) (plist-get unit :relocs))) "_start")
          (let* ((bytes (with-temp-buffer (set-buffer-multibyte nil)
                                         (insert-file-contents-literally file) (buffer-string)))
                 (reader (lambda (offset size) (substring bytes offset (+ offset size))))
                 (decoded (nelisp-native-pe-symbols-read reader))
                 (symbol (gethash "_start" (cadr decoded)))
                 (nt (nelisp-native-pe-symbols-u bytes 60 4)))
            (should symbol)
            (should (= (plist-get symbol :type) 2))
            (should (= (plist-get symbol :address) #x140001000))
            (nelisp-native-pe-symbols-put bytes (+ nt 16) 4 20001)
            (should-error (nelisp-native-pe-symbols-read reader))))
      (delete-file file))))

(ert-deftest nelisp-native-windows-linux-f1-text-remains-identical ()
  "Use the same source and emitter on HEAD as the byte baseline, not a SysV relabel."
  (let* ((unit (nelisp-native-windows-test--bridge 'elf))
         (text (plist-get unit :text)))
    (should (equal (secure-hash 'sha256 text)
                   "927a197339366790e6a8d14339bb7d170fbe8be988a42cd1eb89720a94e13c4b"))))

(ert-deftest nelisp-native-windows-stale-binary-and-ticket-before-map ()
  "Exercise public loader/root boundaries under simulated windows-nt."
  (let ((system-type 'windows-nt) (allocations 0) (calls 0))
    (cl-letf (((symbol-function 'nelisp-native-load--mmap) (lambda (&rest _) (setq allocations (1+ allocations)) (error "map reached")))
              ((symbol-function 'nelisp-native-load-raw-v2-check) (lambda (&rest _) nil))
              ((symbol-function 'nelisp-native-load--running-binary-sha256) (lambda () (make-string 64 ?a)))
              ((symbol-function 'nelisp-runtime-reload-contract-matches-p) (lambda () t))
              ((symbol-function 'nelisp-native-load--raw-supported-p) (lambda () t))
              ((symbol-function 'nelisp--native-pin-copy-v2) (lambda (&rest _) (setq calls (1+ calls)) 0)))
      (let ((manifest (nelisp-native-windows-test--trusted-fixture)))
        (setf (plist-get manifest :binary-sha256) (make-string 64 ?a))
        (should (equal (cadr (should-error (nelisp-native-load-raw-v2-artifact
                                          manifest "probe" (make-string 64 ?a)))) "map reached"))
        (should (= allocations 1))
        (setq allocations 0)
        (setf (plist-get manifest :binary-sha256) (make-string 64 ?b))
        (should (equal (cadr (should-error (nelisp-native-load-raw-v2-artifact
                                          manifest "probe" (make-string 64 ?b))))
                       "nelisp-native-load: v2 running binary identity unavailable or mismatched")))
      (should-error (nelisp-native-load-root-v2-copy 8192 123 0 'value))
      (should-error (nelisp-native-load-root-v2-copy 8192 0 0 'value))
      (should (= calls 1))
      (should (= allocations 0)))))

(ert-deftest nelisp-native-windows-register-sentinel-generation ()
  (load (expand-file-name "test/support/windows-native-sentinel.el" default-directory) nil t)
  (should (nelisp-native-windows-test--contains windows-native-sentinel--code
                                             '(#x48 #x81 #xec #xd8 0 0 0)))
  (should (nelisp-native-windows-test--contains windows-native-sentinel--code
                                             '(#x48 #x8b #x45 #x30 #x48 #x89 #x44 #x24 #x20)))
  (should (nelisp-native-windows-test--contains windows-native-sentinel--code
                                             '(#x48 #x8b #x45 #x38 #x48 #x89 #x44 #x24 #x28)))
  (should (equal (substring windows-native-sentinel--code windows-native-sentinel--hole
                            (+ windows-native-sentinel--hole 8)) (make-string 8 0)))
  (should (= (aref windows-native-sentinel--code (1- windows-native-sentinel--text-end)) #xc3)))

(ert-deftest nelisp-native-windows-seven-word-ffi-stack ()
  "CreateFileW and SetSecurityInfo both require a genuine seventh Win64 word."
  (let* ((unit (nelisp-aot-compile-to-link-unit
                '(defun ffi-seven (a b c d e f g)
                   (extern-call SetSecurityInfo a b c d e f g))
                :arch 'x86_64 :format 'coff))
         (text (plist-get unit :text)))
    (should (nelisp-native-windows-test--contains text '(#x48 #x8b #x45 #x40)))
    (should (nelisp-native-windows-test--contains text '(#x48 #x89 #x44 #x24 #x30)))
    (should (nelisp-native-windows-test--contains text '(#x48 #x81 #xec #x40 0 0 0)))
    (should (member "SetSecurityInfo" (plist-get unit :extern-symbols)))))

(ert-deftest nelisp-native-windows-executable-cache-is-private ()
  "Use only the in-memory stamp, despite forged cache, paths and string mutation."
  (let ((system-type 'windows-nt)
        (nelisp-native-load--running-binary-sha256-cache (make-string 64 ?a))
        (expected (make-string 64 ?b)) (reads 0))
    (cl-letf (((symbol-function 'nelisp--build-digest)
               (lambda () (setq reads (1+ reads)) (copy-sequence expected)))
              ((symbol-function 'nelisp-native-windows-module-path)
               (lambda () (ert-fail "Executable path must not be consulted")))
              ((symbol-function 'nelisp-native-windows-file-bytes)
               (lambda (&rest _) (ert-fail "Executable must not be read")))
              ((symbol-function 'nelisp-native-load--sha256)
               (lambda (&rest _) (ert-fail "Executable must not be hashed"))))
      (let ((digest (nelisp-native-load--running-binary-sha256)))
        (should (equal digest expected))
        (aset digest 0 ?c)
        (should (equal (nelisp-native-load--running-binary-sha256) expected))
        (should (= reads 2))))))

(ert-deftest nelisp-native-windows-executable-stamp-fails-closed ()
  "Absent, unstamped, malformed and failed accessors cannot authorize a PE."
  (let ((system-type 'windows-nt))
    (cl-letf (((symbol-function 'nelisp-native-windows-file-bytes)
               (lambda (&rest _) (ert-fail "No whole-file identity fallback"))))
      (dolist (value (list nil "" "short" (make-string 64 ?z) (make-string 64 ?0)))
        (cl-letf (((symbol-function 'nelisp--build-digest) (lambda () value)))
          (should-not (nelisp-native-load--running-binary-sha256))))
      (cl-letf (((symbol-function 'nelisp--build-digest) (lambda () (error "absent"))))
        (should-not (nelisp-native-load--running-binary-sha256))))))

(ert-deftest nelisp-native-windows-temporary-private-from-creation ()
  (let (events)
    (cl-letf (((symbol-function 'make-temp-name) (lambda (_) "private-temp"))
              ((symbol-function 'nelisp-native-windows-security)
               (lambda (thunk) (funcall thunk 99 100)))
              ((symbol-function 'nelisp-native-windows-open)
               (lambda (file access disposition flags security)
                 (push (list file access disposition flags security) events) 7))
              ((symbol-function 'nelisp-native-windows-check-security)
               (lambda (handle) (push (list 'check handle) events)))
              ((symbol-function 'nelisp-native-windows-close)
               (lambda (handle) (push (list 'close handle) events))))
      (should (equal (nelisp-native-windows-temporary "prefix") "private-temp"))
      (should (equal (nreverse events) '(("private-temp" #xc00e0000 1 0 99) (check 7) (close 7)))))))

(ert-deftest nelisp-native-windows-genuine-f1-code-encoding ()
  "Compile GNU F1 bytecode through the real shared planner/emitter to Win64.
The complete Linux text digest was independently reproduced from HEAD 7a140f8ae."
  (require 'nelisp-bytecode-native-rooted-cfg-shared-emit)
  (let* ((byte-compile-warnings nil)
         (fixture (byte-compile '(lambda (x) (f1-user (cons (car x) (cdr x))))))
         (input (nelisp-bytecode-compiler-input-build fixture))
         (plan (nelisp-bytecode-native-rooted-cfg-plan input nil 'off))
         (emitted (nelisp-bytecode-native-rooted-cfg-shared-emit-build plan "win_f1_fixture")))
    (should (byte-code-function-p fixture))
    (should (eq (plist-get plan :status) 'complete))
    (should (eq (plist-get emitted :status) 'complete))
    (let* ((form (plist-get emitted :form))
           (windows (nelisp-aot-compile-to-link-unit form :arch 'x86_64 :format 'coff))
           (linux (nelisp-aot-compile-to-link-unit form :arch 'x86_64 :format 'elf))
           (text (plist-get windows :text)))
      (should (equal (plist-get windows :extern-symbols)
                     '("nl_native_funcall_v2" "nl_root_pin_slot_v2")))
      (should (nelisp-native-windows-test--contains text '(#x48 #x89 #x4d #xf8)))
      (should (nelisp-native-windows-test--contains text '(#x48 #x89 #x44 #x24 #x20)))
      (should-not (equal text (plist-get linux :text)))
      (should (equal (secure-hash 'sha256 (plist-get linux :text))
                     "1c93f13bb929b2e50c50303d5ef572fc604cd31b640e613041e8d7c3c6621ad5")))))

(ert-deftest nelisp-native-windows-worker-refuses-before-whole-file-hash ()
  "The unsupported async worker cannot fall back to hashing another PE."
  (require 'nelisp-native-tier)
  (let ((system-type 'windows-nt))
    (cl-letf (((symbol-function 'nelisp-native-load--sha256-file-external)
               (lambda (&rest _) (ert-fail "No worker PE hashing on Windows")))
              ((symbol-function 'nelisp-native-load--read-file)
               (lambda (&rest _) (ert-fail "No worker PE reads on Windows"))))
      (should (equal (cdr (should-error
                          (nelisp-native-tier--check-worker "chosen.exe" 'in-house)
                          :type 'nelisp-native-tier-permanent))
                     '(windows-worker-unsupported))))))
