;;; nelisp-native-legacy-u9-test.el --- Legacy wrapper admission -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'ert)
(require 'nelisp-bytecode-native-rooted-cfg-contract)
(load "support/native-legacy-u9-fixtures.el" nil t t)
(ert-deftest u9/all-five-use-frozen-evaluator-through-shared-form ()
  (dolist (opcode '(139 141 143 144 145))
    (let* ((input (nelisp-bytecode-compiler-input-build (native-legacy-u9-function opcode)))
           (plan (nelisp-bytecode-native-rooted-cfg-plan input))
           (emitted (nelisp-bytecode-native-rooted-cfg-shared-emit-build
                     plan nelisp-bytecode-native-rooted-cfg-contract-shared-entry)))
      (should (eq (plist-get plan :status) 'complete))
      (should (eq (plist-get emitted :status) 'complete))
      (should (member "nl_native_funcall_v2" (plist-get emitted :gateway-imports)))
      (when (memq opcode '(144 145))
        (should (member "nl_native_frame_v2" (plist-get emitted :gateway-imports)))))))
(ert-deftest u9/forms-are-evaluated-and-dynamic-binding-is-restored ()
  (dolist (opcode '(139 141 143))
    (dolist (mode (native-legacy-u9-modes opcode))
      (let ((actual (native-legacy-u9-observe (native-legacy-u9-function opcode) opcode mode))
            (provider (nelisp-native-funcall-v2-initializer
                       (nth 1 (nelisp-native-funcall-v2-primitive opcode)))))
        (should (equal actual
                       (native-legacy-u9-observe
                        (lambda () (apply provider (append (aref (native-legacy-u9-function opcode) 2) nil)))
                        opcode mode)))
        (should (eq (nth 4 actual) 'outside))
        (should (eq (nth 5 actual) 'outside))))))
(ert-deftest u9/setup-show-order-and-batch-oracle ()
  (dolist (mode '(nil error throw setup-error batch show-error show-throw))
    (let ((result (native-legacy-u9-observe (native-legacy-u9-function 145) 145 mode)))
      (should (eq (nth 2 result) 'original))
      (should (nth 3 result))
      (should (equal (car (nth 1 result)) '(setup t t)))
      (when (eq mode nil)
        (should (equal (nth 1 result) '((setup t t) (body t t) (show t t t)))))
      (if (eq mode 'batch)
          (should (memq 'unexpected-show-hook (nth 1 result)))
        (should-not (memq 'unexpected-show-hook (nth 1 result)))))))
(ert-deftest u9/stack-and-binding-underflow-remain-refused ()
  (dolist (code (list (unibyte-string 139 135) (unibyte-string 192 141 135)
                     (unibyte-string 192 193 143 135) (unibyte-string 192 193 145 135)))
    (should-not (eq (plist-get (nelisp-bytecode-native-rooted-cfg-plan
                              (nelisp-bytecode-compiler-input-build (make-byte-code 0 code [nil nil] 4)))
                             :status) 'complete))))
