;;; -*- lexical-binding: t; -*-
(require 'cl-lib) (require 'nelisp-aot-compiler) (if (getenv "OD_SOURCE") (load (getenv "OD_SOURCE") nil t t) (require 'nelisp-standalone-build))
(dolist (f '(val-load sexp-clone-into cons-construct nlconsbox-alloc nlconsbox-set-car nlconsbox-set-cdr nlconsbox-clone nlvector-clone nlstr-clone nlchartable-clone nlboolvector-clone nlcell-clone nlrecord-clone nlrecord-slot-ptr jit-cons-car-ptr jit-cons-cdr-ptr)) (require (intern (format "nelisp-cc-%s" f))))
(defun od-def (name) (with-temp-buffer (insert-file-contents (or (getenv "OD_SOURCE") "scripts/nelisp-standalone-build.el")) (goto-char (point-min)) (search-forward (format "(defun %s " name)) (goto-char (match-beginning 0)) (read (current-buffer))))
(let* ((variant (or (getenv "OD_VARIANT") "positive")) (output (getenv "OD_OUTPUT")) (base #x3d000000)
       (frame (+ base 512)) (args (+ base 768)) (formals (+ base 800)) (func (+ base 1024)) (box (+ base 1088)) (data (+ base 1184))
       (code (+ base 1248)) (constants (+ base 1280)) (out (+ base 1344)) (records (+ base 4096)) (names (+ base 2048))
       (binder (od-def 'wf_bytecode_bind_argframe)) (dispatcher (od-def 'wf_bytecode_dynamic_function_frame))
       (legacy (od-def 'wf_bytecode_bind_arglist)) (legacy-dispatch (od-def 'wf_bytecode_dynamic_function))
       (static-next (+ base 16384)) (count 0) checks symbols)
 (pcase variant
  ("bad-epoch" (setq binder (cl-subst 0 '(wf_dirty) binder :test #'equal)))
  ("bad-index" (setq binder (cl-subst '(+ frame (* 0 32)) '(+ frame (* index 32)) binder :test #'equal)))
  ("bad-rest-start" (setq binder (cl-subst '(wf_bytecode_build_args frame 0 (- argc index) value) '(wf_bytecode_build_args frame index (- argc index) value) binder :test #'equal)))
  ("bad-optional" (setq binder (cl-subst 0 '(wf_write_nil value) binder :test #'equal)))
  ("bad-unbind" (setq dispatcher (cl-subst 0 '(wf_bytecode_unbind (+ env 32) bound) dispatcher :test #'equal)))
  ("bad-arity" (setq dispatcher (cl-subst nil '(< argc required) dispatcher :test #'equal)))
  ("bad-exhaustion" (setq dispatcher (cl-subst '(wf_bytecode_execute code constants depth env out 0 0 0 0) '(if (< bound 0) 1 (wf_bytecode_execute code constants depth env out 0 0 0 0)) dispatcher :test #'equal))))
 (cl-labels ((emit (x) (push x checks))
             (check (x) (emit `(if ,x 0 (seq (ptr-write-u64 ,base 24 ,(cl-incf count)) (syscall-direct 1 1 ,base 32 0 0 0) (syscall-direct 60 2 0 0 0 0 0)))))
             (slot (p tag a b c) (cl-loop for v in (list tag a b c) for k from 0 do (emit `(ptr-write-u64 ,p ,(* k 8) ,v))))
             (reserve (n) (prog1 static-next (setq static-next (+ static-next n))))
             (symbol-slot (s)
              (or (cdr (assq s symbols))
               (let* ((p (reserve 32)) (name (symbol-name s)) (buf (reserve (* 8 (1+ (/ (length name) 8))))))
                (slot p 4 (length name) buf (length name)) (cl-loop for c across name for i from 0 do (emit `(ptr-write-u8 ,buf ,i ,c)))
                (push (cons s p) symbols) p)))
             (word (x)
              (cond ((null x) 3) ((integerp x) (+ (* x 4) 1)) ((symbolp x) (symbol-slot x))
               ((consp x) (let* ((p (reserve 32)) (b (reserve 24)) (a (word (car x))) (d (word (cdr x))))
                 (slot p 7 b 0 0) (emit `(ptr-write-u64 ,b 0 ,a)) (emit `(ptr-write-u64 ,b 8 ,d)) (emit `(ptr-write-u64 ,b 16 1)) p))
               (t (error "Unsupported fixture literal %S" x))))
             (reset (spec argc)
              (emit `(wf_bytecode_copy ,formals (nl_val_load ,(word spec) ,formals)))
              (emit `(wf_write_nil ,args)) (emit `(wf_bytecode_build_args ,frame 0 ,argc ,args))
              (slot func 17 box 0 0) (emit `(ptr-write-u64 ,box 32 ,data)) (emit `(ptr-write-u64 ,box 48 4))
              (emit `(ptr-write-u64 ,data 0 ,formals)) (emit `(ptr-write-u64 ,data 8 ,code)) (emit `(ptr-write-u64 ,data 16 ,constants)) (emit `(ptr-write-u64 ,data 24 33))
              (dolist (offset '(0 8 48 56 64 72 80 88 96 104)) (emit `(ptr-write-u64 ,base ,offset 0)))
              (dotimes (i 8) (slot (+ records (* i 32)) 99 88 77 66)) (slot out 99 88 77 66)))
  (dotimes (i 6) (slot (+ frame (* i 32)) 2 (+ 10 i) 0 0))
  (slot code 14 0 0 0) (slot constants 8 0 0 0)
  (dolist (row '((nil 0 nil 0)
                 ((a b) 2 (a b) 0)
                 ((a a) 2 (a a) 0)
                 ((a &optional b c) 1 (a b c) 0)
                 ((a &optional b c) 2 (a b c) 0)
                 ((&rest r) 0 (r) 1)
                 ((&rest r) 1 (r) 1)
                 ((&rest r) 2 (r) 1)
                 ((&rest r) 6 (r) 1)
                 ((a &optional b &rest r) 1 (a b r) 1)
                 ((a &optional b &rest r) 2 (a b r) 1)
                 ((a &optional b &rest r) 3 (a b r) 1)
                 ((a &optional b &rest r) 6 (a b r) 1)
                 ((a &rest a) 3 (a a) 1)))
   (pcase-let ((`(,spec ,argc ,bound-names ,rest) row))
    (dolist (kind '(old new))
     (reset spec argc)
     (check `(= (,(if (eq kind 'old) 'wf_bytecode_bind_arglist 'wf_bytecode_bind_argframe) 77 ,formals ,(if (eq kind 'old) args frame) ,argc) ,(length bound-names)))
     (check `(= (ptr-read-u64 ,base 0) ,(length bound-names))) (check `(= (ptr-read-u64 ,base 48) 0))
     (let* ((fixed (- (length bound-names) rest)) (extra (max 0 (- argc fixed))) (epochs (if (= rest 1) (max 0 (1- extra)) 0)))
      (check `(= (ptr-read-u64 ,base 8) ,epochs))
      (cl-loop for n in bound-names for i from 0 do
       (check `(= (ptr-read-u64 ,names ,(* i 8)) ,(symbol-slot n)))
       (if (< i fixed)
        (cl-loop for x in (if (< i argc) (list 2 (+ 10 i) 0 0) '(0 0 0 0)) for k from 0 do (check `(= (ptr-read-u64 ,(+ records (* i 32)) ,(* k 8)) ,x)))
        (if (= extra 0) (dotimes (k 4) (check `(= (ptr-read-u64 ,(+ records (* i 32)) ,(* k 8)) 0)))
         (progn
          (emit `(setq cursor ,(+ records (* i 32))))
          (dotimes (j extra)
           (check '(= (ptr-read-u64 cursor 0) 7)) (check '(= (ptr-read-u64 cursor 16) 0)) (check '(= (ptr-read-u64 cursor 24) 0))
           (check `(= (ptr-read-u64 (ptr-read-u64 cursor 8) 0) ,(+ (* (+ 10 fixed j) 4) 1)))
           (if (= j (1- extra)) (check '(= (ptr-read-u64 (ptr-read-u64 cursor 8) 8) 3))
            (emit '(setq cursor (ptr-read-u64 (ptr-read-u64 cursor 8) 8)))))))))))))
  ;; Both full dynamic dispatchers preserve shape/arity errors, all bound-cell
  ;; cleanup, and the original code/constant/depth snapshots across binding.
  (dolist (kind '(old new))
   (dolist (row '(((a b) 1 4) ((a) 2 4) ((a &rest) 2 5) ((a &optional &optional) 2 5) ((3) 1 5) ((a . tail) 1 5)))
    (reset (nth 0 row) (nth 1 row))
    (check `(= (,(if (eq kind 'old) 'wf_bytecode_dynamic_function 'wf_bytecode_dynamic_function_frame) ,func ,formals ,(if (eq kind 'old) args frame) ,(nth 1 row) 77 ,out) 1))
    (check `(= (ptr-read-u64 ,out 0) ,(nth 2 row))) (check `(= (ptr-read-u64 ,base 64) 0)) (check `(= (ptr-read-u64 ,base 72) 0)))
   (dolist (status '(0 1))
    (reset '(a &optional b &rest r) 6) (emit `(ptr-write-u64 ,base 80 ,status)) (emit `(ptr-write-u64 ,base 96 1))
    (check `(= (,(if (eq kind 'old) 'wf_bytecode_dynamic_function 'wf_bytecode_dynamic_function_frame) ,func ,formals ,(if (eq kind 'old) args frame) 6 77 ,out) ,status))
    (check `(= (ptr-read-u64 ,base 64) 1)) (check `(= (ptr-read-u64 ,base 72) 3)) (check `(= (ptr-read-u64 ,base 88) ,code)) (check `(= (ptr-read-u64 ,base 8) 3)) (check `(= (ptr-read-u64 ,base 48) 0))))
  ;; New checked scratch-root failure must not execute or unbind nonexistent cells.
  (reset '(a) 1) (emit `(ptr-write-u64 ,base 56 1))
  (check `(= (wf_bytecode_dynamic_function_frame ,func ,formals ,frame 1 77 ,out) 1))
  (check `(= (ptr-read-u64 ,base 0) 0)) (check `(= (ptr-read-u64 ,base 64) 0)) (check `(= (ptr-read-u64 ,base 72) 0)) (check `(= (ptr-read-u64 ,base 104) 1)) (check `(= (ptr-read-u64 ,base 48) 0))
  (let* ((common (cl-loop for f in '(val-load sexp-clone-into nlconsbox-alloc nlconsbox-set-car nlconsbox-set-cdr nlconsbox-clone nlvector-clone nlstr-clone nlchartable-clone nlboolvector-clone nlcell-clone nlrecord-clone nlrecord-slot-ptr jit-cons-car-ptr jit-cons-cdr-ptr) append (let ((x (symbol-value (intern (format "nelisp-cc-%s--source" f))))) (if (eq (car x) 'seq) (cdr x) (list x)))))
         (source `(seq ,binder ,dispatcher ,legacy ,legacy-dispatch ,nelisp-cc-cons-construct--source ,@common
           ,@(mapcar #'od-def '(wf_bytecode_slot wf_bytecode_copy wf_copy32 wf_write_nil wf_bytecode_build_args wf_bytecode_arglist_shape wf_bytecode_optional_marker_p wf_bytecode_rest_marker_p wf_bytecode_copy_arg_tail))
           (defun nl_bind_clone_force_flag () 0) (defun nl_gc_in_arena (p) 0) (defun nl_gc_is_boot (p) 0)
           (defun nl_alloc_str (a b c) (syscall-direct 60 199 0 0 0 0 0)) (defun nl_alloc_symbol (a b c) (syscall-direct 60 199 0 0 0 0 0))
           (defun wf_dirty () (ptr-write-u64 ,base 8 (+ (ptr-read-u64 ,base 8) 1)))
           (defun nl_root_mark (env) (ptr-read-u64 ,base 48))
           (defun nl_root_reserve (env) (let ((i (ptr-read-u64 ,base 48))) (seq (ptr-write-u64 ,base 48 (+ i 1)) (+ ,(+ base 8192) (* i 32)))))
           (defun nl_root_reserve_checked (env) (if (= (ptr-read-u64 ,base 56) 1) 0 (nl_root_reserve env)))
           (defun nl_root_release (env mark) (ptr-write-u64 ,base 48 mark))
           (defun wf_bytecode_root_exhausted () (seq (ptr-write-u64 ,base 104 1) 1))
           (defun wf_bytecode_varbind (env name value)
            (let ((i (ptr-read-u64 ,base 0)))
             (seq (ptr-write-u64 ,names (* i 8) name) (wf_copy32 (+ ,records (* i 32)) value) (ptr-write-u64 ,base 0 (+ i 1))
              (if (= (ptr-read-u64 ,base 96) 1) (ptr-write-u64 ,data 8 ,out) 0) 0)))
           (defun wf_bytecode_unbind (frames bound) (seq (ptr-write-u64 ,base 72 bound) 0))
           (defun bf_wrong_number_of_args (func argc) (seq (ptr-write-u64 ,out 0 4) 1))
           (defun nl_apply_stash_invalid_function (env func) (seq (ptr-write-u64 ,out 0 5) 1))
           (defun wf_bytecode_execute (code constants depth env out args argc maxargs rest)
            (seq (ptr-write-u64 ,base 64 (+ (ptr-read-u64 ,base 64) 1)) (ptr-write-u64 ,base 88 code) (ptr-read-u64 ,base 80)))
           (defun nl_alloc_bytes (size align) (let ((p (ptr-read-u64 ,base 16))) (seq (ptr-write-u64 ,base 16 (+ p size)) p)))
           (defun audit_run () (let ((cursor 0)) (seq (syscall-direct 9 ,base 16777216 3 50 -1 0) (ptr-write-u64 (data-addr nl_arena_base) 0 ,base) (ptr-write-u64 ,base 192 1) (ptr-write-u64 ,base 16 ,(+ base 1048576)) ,@(nreverse checks) (ptr-write-u64 ,base 24 0) (syscall-direct 1 1 ,base 32 0 0 0) 0)))
           (defun _start () (syscall-direct 60 (audit_run) 0 0 0 0 0)))))
   (nelisp-link-units output (list (nelisp-standalone--compile-to-unit "dynamic-frame-audit.o" source) (nelisp-standalone--arena-base-slot-unit)) "_start")
   (with-temp-file (concat output ".source.el") (prin1 source (current-buffer)))
   (princ (format "DYNAMIC-NATIVE-COMPILED variant=%s checks=%d\n" variant count)))))
