;;; Ordinary VM CALL preserves live callable semantics. -*- lexical-binding: t; -*-
;; p35-vm-condition is shared with the preceding vector fixture.  The numeric
;; oracle uses ordinary APPLY in this process; this is not a claim that every
;; existing mixed bignum/float result matches GNU Emacs.
(load (expand-file-name "vm-call-difference-helpers.el" fp-out) nil t t)
(unless (fboundp 'p35-vm-condition) (error "Missing shared VM condition oracle"))
(dolist (name '(p35-vm-call-difference p35-vm-call-zero p35-vm-call-one
               p35-vm-call-two p35-vm-call-three))
  (unless (byte-code-function-p (symbol-function name))
    (error "Ordinary CALL helper is not genuine bytecode: %S" name)))
(let ((checked 0)
      (values (list -2305843009213693953 -2305843009213693952 -2 -1 0 1 2
                    2305843009213693951 2305843009213693952
                    9223372036854775807 9223372036854775808
                    1.5 -2.5 nil t 'wrong "bad" [3])))
  (dolist (a values)
    (dolist (b values)
      (let ((args (list a b)))
        (unless (equal (p35-vm-condition #'p35-vm-call-difference args)
                       (p35-vm-condition '- args))
          (error "Ordinary CALL numeric/condition mismatch: %S" args))
        (setq checked (1+ checked)))))
  (let* ((saved (symbol-function '-))
         (alias-bound (fboundp 'p35-vm-call-difference-alias))
         (alias-owner (and alias-bound (symbol-function 'p35-vm-call-difference-alias))))
    (unless (and (consp saved) (consp (cdr saved)) (null (cddr saved))
                 (eq (car saved) 'builtin) (eq (cadr saved) '-))
      (error "Expected ordinary subtraction builtin token"))
    (let* ((saved-head (car saved)) (saved-cdr (cdr saved))
           (saved-name (car saved-cdr)) (saved-tail (cdr saved-cdr)))
      (unwind-protect
          (progn
            (dolist (row (list (list 'zero #'p35-vm-call-zero (list '-) '(value 0))
                               (list 'one #'p35-vm-call-one (list '- 7) '(value -7))
                               (list 'three #'p35-vm-call-three (list '- 10 2 3) '(value 5))
                               (list 'direct #'p35-vm-call-two (list saved 7 2) '(value 5))))
              (unless (equal (p35-vm-condition (nth 1 row) (nth 2 row)) (nth 3 row))
                (error "Ordinary CALL arity/direct mismatch: %S" (car row)))
              (setq checked (1+ checked)))
            (fset '- (lambda (a b) (garbage-collect) (list 'changed a b)))
            (unless (equal (p35-vm-condition #'p35-vm-call-difference '(7 2))
                           '(value (changed 7 2)))
              (error "Ordinary CALL ignored live replacement or callback GC"))
            (setq checked (1+ checked))
            (fset 'p35-vm-call-difference-alias (lambda (a b) (list 'alias a b)))
            (fset '- 'p35-vm-call-difference-alias)
            (unless (equal (p35-vm-condition #'p35-vm-call-difference '(7 2))
                           '(value (alias 7 2)))
              (error "Ordinary CALL alias mismatch"))
            (setq checked (1+ checked))
            (fset '- (lambda (a b) (error "rebound-difference")))
            (unless (equal (p35-vm-condition #'p35-vm-call-difference '(7 2))
                           '(error error ("rebound-difference")))
              (error "Ordinary CALL replacement error mismatch"))
            (setq checked (1+ checked))
            (fset '- saved)
            (setcar saved-cdr '+)
            (unless (equal (p35-vm-condition #'p35-vm-call-difference '(7 2)) '(value 9))
              (error "Ordinary CALL cached a mutable token name"))
            (setq checked (1+ checked))
            (unless (equal (p35-vm-condition #'p35-vm-call-two (list saved 7 2)) '(value 9))
              (error "Direct CALL cached a mutable token name"))
            (setq checked (1+ checked))
            (setcar saved-cdr saved-name)
            (setcdr saved-cdr '(extra))
            (unless (equal (p35-vm-condition #'p35-vm-call-difference '(7 2)) '(value 5))
              (error "Ordinary CALL extra-tail fallback mismatch"))
            (setq checked (1+ checked))
            (setcdr saved-cdr 'tail)
            (unless (equal (p35-vm-condition #'p35-vm-call-difference '(7 2)) '(value 5))
              (error "Ordinary CALL dotted-tail fallback mismatch"))
            (setq checked (1+ checked))
            (setcdr saved-cdr saved-tail)
            (setcar saved 'unknown)
            (unless (equal (p35-vm-condition #'p35-vm-call-difference '(7 2))
                           '(error invalid-function ((unknown -))))
              (error "Ordinary CALL invalid-head fallback mismatch"))
            (setq checked (1+ checked)))
        ;; Restore the exact cons identities and both function cells, even if a
        ;; value assertion or callback signals while the token is malformed.
        (setcar saved saved-head)
        (setcdr saved saved-cdr)
        (setcar saved-cdr saved-name)
        (setcdr saved-cdr saved-tail)
        (fset '- saved)
        (if alias-bound
            (fset 'p35-vm-call-difference-alias alias-owner)
          (fmakunbound 'p35-vm-call-difference-alias)))
      (unless (and (eq (symbol-function '-) saved) (eq (car saved) saved-head)
                   (eq (cdr saved) saved-cdr) (eq (car saved-cdr) saved-name)
                   (eq (cdr saved-cdr) saved-tail)
                   (equal (p35-vm-condition #'p35-vm-call-difference '(7 2)) '(value 5)))
        (error "Ordinary CALL restoration mismatch"))
      (setq checked (1+ checked))))
  (unless (= checked 337) (error "Ordinary CALL fixture count: %S" checked))
  (princ (format "P35-CALL-DIFFERENCE-VM-PASS controls=%d\n" checked)))
