;;; nelisp-eln-float-test.el --- focused float-view tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'nelisp-eln-float)

(defvar nelisp-eln-float-test--memory nil)
(defvar nelisp-eln-float-test--next-base #x400000)
(defvar nelisp-eln-float-test--alloc-count 0)
(defvar nelisp-eln-float-test--release-count 0)
(defvar nelisp-eln-float-test--limbs nil)

(defun nelisp-eln-float-test--allocate (size)
  (unless (= size 8) (error "bad allocation size: %S" size))
  (setq nelisp-eln-float-test--alloc-count
        (1+ nelisp-eln-float-test--alloc-count))
  (let ((owner (vector 'fake-float-mmap nelisp-eln-float-test--next-base t)))
    (setq nelisp-eln-float-test--next-base
          (+ nelisp-eln-float-test--next-base #x1000))
    owner))

(defun nelisp-eln-float-test--address (owner)
  (unless (and (vectorp owner) (eq (aref owner 0) 'fake-float-mmap)
               (aref owner 2))
    (error "closed fake mapping"))
  (aref owner 1))

(defun nelisp-eln-float-test--release (owner)
  (nelisp-eln-float-test--address owner)
  (aset owner 2 nil)
  (setq nelisp-eln-float-test--release-count
        (1+ nelisp-eln-float-test--release-count)))

(defun nelisp-eln-float-test--write-u32 (address offset value)
  (puthash (+ address offset) value nelisp-eln-float-test--memory))

(defun nelisp-eln-float-test--read-u32 (address offset)
  (gethash (+ address offset) nelisp-eln-float-test--memory 0))

(defun nelisp-eln-float-test--half (_value half)
  (aref nelisp-eln-float-test--limbs half))

(defmacro nelisp-eln-float-test--with-fakes (&rest body)
  `(let ((nelisp-eln-float-test--memory (make-hash-table :test 'eql))
         (nelisp-eln-float-test--next-base #x400000)
         (nelisp-eln-float-test--alloc-count 0)
         (nelisp-eln-float-test--release-count 0))
     (cl-letf (((symbol-function 'nl-ffi-memory-allocate)
                #'nelisp-eln-float-test--allocate)
               ((symbol-function 'nl-ffi-memory-address)
                #'nelisp-eln-float-test--address)
               ((symbol-function 'nl-ffi-memory-release)
                #'nelisp-eln-float-test--release)
               ((symbol-function 'ptr-write-u32)
                #'nelisp-eln-float-test--write-u32)
               ((symbol-function 'ptr-read-u32)
                #'nelisp-eln-float-test--read-u32)
               ((symbol-function 'nelisp--float-word-half)
                #'nelisp-eln-float-test--half))
       ,@body)))

(ert-deftest nelisp-eln-float-raw-payload-lifetimes ()
  (nelisp-eln-float-test--with-fakes
   (let ((cases `((0.0 #x00000000 #x00000000)
                  (-0.0 #x00000000 #x80000000)
                  (1.0 #x00000000 #x3ff00000)
                  (0.5 #x00000000 #x3fe00000)
                  (,(car (read-from-string "4.9406564584124654e-324"))
                   #x00000001 #x00000000)
                  (,(car (read-from-string "1.0e+INF"))
                   #x00000000 #x7ff00000)
                  (,(car (read-from-string "0.0e+NaN"))
                   #x00001234 #x7ff80000))))
     (dolist (case cases)
       (let* ((source (nth 0 case))
              (nelisp-eln-float-test--limbs (vector (nth 1 case) (nth 2 case)))
              (owner (nelisp-eln-float-allocate source))
              (address (nelisp-eln-float-address owner)))
         (should (eq (nelisp-eln-float-source owner) source))
         (should (eq (nelisp-eln-abi-classify-word
                      (nelisp-eln-float-word owner)) 'float))
         (should (= (nelisp-eln-float-word owner) (+ address 7)))
         (should (= (nelisp-eln-float-test--read-u32 address 0) (nth 1 case)))
         (should (= (nelisp-eln-float-test--read-u32 address 4) (nth 2 case)))
         (should (nelisp-eln-float-release owner))
         (should (nelisp-eln-float-release owner))
         (should-error (nelisp-eln-float-word owner))
         (should-error (nelisp-eln-float-source owner))))
     (should (= nelisp-eln-float-test--alloc-count
                nelisp-eln-float-test--release-count)))))

(ert-deftest nelisp-eln-float-rejects-before-allocation ()
  (nelisp-eln-float-test--with-fakes
   (should-error (nelisp-eln-float-allocate "not-float")
                 :type 'nelisp-eln-float-error)
   (should (= nelisp-eln-float-test--alloc-count 0))
   (let ((nelisp-eln-float-test--limbs (vector -1 0)))
     (should-error (nelisp-eln-float-allocate 1.0)
                   :type 'nelisp-eln-float-error))
   (should (= nelisp-eln-float-test--alloc-count 0))))

(when (getenv "NELISP_ELN_FLOAT_STANDALONE")
  (let ((cases `((0.0 #x00000000 #x00000000)
                 (-0.0 #x00000000 #x80000000)
                 (1.0 #x00000000 #x3ff00000)
                 (0.5 #x00000000 #x3fe00000)
                 (,(car (read-from-string "4.9406564584124654e-324"))
                  #x00000001 #x00000000)
                 (,(car (read-from-string "1.0e+INF"))
                  #x00000000 #x7ff00000))))
    (dolist (case cases)
      (let* ((source (nth 0 case))
             (owner (nelisp-eln-float-allocate source))
             (address (nelisp-eln-float-address owner)))
        (unless (and (= (ptr-read-u32 address 0) (nth 1 case))
                     (= (ptr-read-u32 address 4) (nth 2 case)))
          (error "standalone raw float payload mismatch: %S" source))
        (nelisp-eln-float-release owner)))
    (princ "NELISP_ELN_FLOAT_RAW_BITS_PASS\n")))

;;; nelisp-eln-float-test.el ends here
