;;; nelisp-native-compiler-runtime-capability-test.el --- Scoped metadata gates -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'nelisp-native-compiler-runtime-capability)

(defun nelisp-native-compiler-runtime-capability-test--metadata ()
  (list :version 1 :domain 'compiler-runtime-v1 :operation-eligibility '(constructor)
        :abi-sha256 (make-string 64 ?a) :binary-sha256 (make-string 64 ?b)
        :active-manifest-sha256 (make-string 64 ?c)
        :exports
        (mapcar (lambda (entry)
                  (append (list :name (car entry) :kind (nth 1 entry) :address 4096)
                          (if (eq (nth 1 entry) 'data)
                              (list :size (nth 2 entry))
                            (list :arity (nth 2 entry) :size 32))))
                nelisp-native-compiler-runtime-capability--constructor-exports)))

(ert-deftest nelisp-native-compiler-runtime-capability-schema-controls ()
  (let ((record (nelisp-native-compiler-runtime-capability-test--metadata)))
    (should (nelisp-native-compiler-runtime-capability--metadata-p record))
    (dolist (mutation '((:version 2) (:domain ticket-gc-memory-v1)
                        (:operation-eligibility (constructor numeric call))
                        (:abi-sha256 "bad") (:binary-sha256 "bad")
                        (:active-manifest-sha256 "bad")))
      (should-not (nelisp-native-compiler-runtime-capability--metadata-p
                   (plist-put (copy-tree record) (car mutation) (cadr mutation)))))
    (let ((changed (copy-tree record)))
      (setcdr (plist-get changed :exports) nil)
      (should-not (nelisp-native-compiler-runtime-capability--metadata-p changed)))
    (let* ((changed (copy-tree record))
           (entry (car (plist-get changed :exports))))
      (plist-put entry :size 16)
      (should-not (nelisp-native-compiler-runtime-capability--metadata-p changed)))
    (dolist (change '(("nl_native_cons_v2" :arity 6)
                      ("nl_arena_base" :kind func)
                      ("nl_native_cons_v2" :name "nl_native_car_v2")))
      (let* ((changed (copy-tree record))
             (entry (cl-find (car change) (plist-get changed :exports)
                             :key (lambda (item) (plist-get item :name)) :test #'equal)))
        (plist-put entry (nth 1 change) (nth 2 change))
        (should-not (nelisp-native-compiler-runtime-capability--metadata-p changed))))
    (let* ((changed (copy-tree record))
           (exports (plist-get changed :exports)))
      (setcar (cdr exports) (copy-tree (car exports)))
      (should-not (nelisp-native-compiler-runtime-capability--metadata-p changed)))))

(ert-deftest nelisp-native-compiler-runtime-capability-late-provider-refused ()
  (should-not (nelisp-native-compiler-runtime-capability-p '(constructor)))
  (cl-letf (((symbol-function 'nelisp-native-compiler-runtime-proof-create)
             (lambda () 'forged))
            ((symbol-function 'nelisp-native-compiler-runtime-proof-valid-p)
             (lambda (_) t))
            ((symbol-function 'nelisp-native-compiler-runtime-proof-metadata)
             (lambda (_) (nelisp-native-compiler-runtime-capability-test--metadata))))
    (should-not (nelisp-native-compiler-runtime-capability-p '(constructor)))
    (should-not (nelisp-native-compiler-runtime-capability-p '(numeric)))
    (should-not (nelisp-native-compiler-runtime-capability-p '(call)))
    (should-not (nelisp-native-compiler-runtime-capability-p))))
