;;; nelisp-bytecode-native-arithmetic-lowering-test.el --- ABI boundary controls -*- lexical-binding: t; -*-
(require 'ert)
(require 'nelisp-bytecode-native-arithmetic-lowering)
(defun nelisp-arithmetic-lowering-test--operation ()
  (list :opcode 'add :bytecode-opcode 92 :input-roots (list 1 2)
        :output-root 3 :exit-root-base 4))
(ert-deftest nelisp-arithmetic-lowering-gateway ()
  (let ((result (nelisp-bytecode-native-arithmetic-lowering-build
                 (nelisp-arithmetic-lowering-test--operation) 7 'env 'ticket)))
    (should (eq (plist-get result :status) 'complete))
    (should (equal (plist-get result :call) '(nl_native_add_v2 env ticket 1 2 3 4)))
    (should (equal (plist-get result :import) (nelisp-native-arithmetic-v2-descriptor)))
    (setcar (plist-get result :source) 'mutant)
    (should (eq (car (nelisp-native-arithmetic-v2-source)) 'seq))))
(ert-deftest nelisp-arithmetic-lowering-refuses-malformed ()
  (dolist (case '((:output-root 4) (:exit-root-base 5) (:input-roots (0 2))
                  (:input-roots (1 4)) (:input-roots (1 2 3))
                  (:output-root "3") (:bytecode-opcode 91) (:opcode cons)))
    (let ((operation (nelisp-arithmetic-lowering-test--operation)))
      (setq operation (plist-put operation (car case) (cadr case)))
      (should (eq (plist-get (nelisp-bytecode-native-arithmetic-lowering-build operation 7 'env 'ticket)
                             :status) 'refused))))
  (dolist (variable '(nil t :constant))
    (should (eq (plist-get (nelisp-bytecode-native-arithmetic-lowering-build
                           (nelisp-arithmetic-lowering-test--operation) 7 variable 'ticket)
                          :status) 'refused)))
  (let* ((operation (nelisp-arithmetic-lowering-test--operation))
         (cycle (copy-sequence operation)))
    (setcdr (last cycle) cycle)
    (should (eq (plist-get (nelisp-bytecode-native-arithmetic-lowering-build cycle 7 'env 'ticket)
                          :status) 'refused)))
  (should (eq (plist-get (nelisp-bytecode-native-arithmetic-lowering-build
                         (append (nelisp-arithmetic-lowering-test--operation) '(:opcode add))
                         7 'env 'ticket) :status) 'refused)))
(ert-deftest nelisp-arithmetic-lowering-provider-owner-mutation ()
  (let ((before (nelisp-bytecode-native-arithmetic-lowering-dependency-context))
        (owner (symbol-function 'nelisp-native-arithmetic-v2-source)))
    (unwind-protect
        (progn
          (fset 'nelisp-native-arithmetic-v2-source (lambda () '(seq mutant)))
          (should-error (nelisp-bytecode-native-arithmetic-lowering-dependency-context)))
      (fset 'nelisp-native-arithmetic-v2-source owner))))
(ert-deftest nelisp-arithmetic-lowering-supported-aliases ()
  ;; The provider copies both operands into nested precise roots before output.
  (dolist (output '(1 2))
    (let ((operation (nelisp-arithmetic-lowering-test--operation)))
      (setq operation (plist-put operation :output-root output))
      (should (eq (plist-get (nelisp-bytecode-native-arithmetic-lowering-build operation 7 'env 'ticket)
                            :status) 'complete))))
  (let ((operation (nelisp-arithmetic-lowering-test--operation)))
    (setq operation (plist-put operation :input-roots '(1 1)))
    (should (equal (plist-get (nelisp-bytecode-native-arithmetic-lowering-build operation 7 'env 'ticket)
                             :call) '(nl_native_add_v2 env ticket 1 1 3 4)))))
(provide 'nelisp-bytecode-native-arithmetic-lowering-test)
