;;; nelisp-native-concat-u3b-test.el --- U3b sequence lowering -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'ert)
(require 'nelisp-bytecode-native-rooted-cfg-contract)
(require 'nelisp-bytecode-native-rooted-cfg-constructor-contract)
(require 'nelisp-bytecode-native-rooted-cfg-safe-contract)
(require 'nelisp-native-load)
(load "support/native-concat-u3b-fixtures.el" nil t t)
(ert-deftest u3b/ordered-operands-and-shared-contracts ()
  (dolist (row (native-concat-u3b-fixtures))
    (let* ((fn (apply #'native-concat-u3b-function row))
           (input (nelisp-bytecode-compiler-input-build fn))
           (plan (nelisp-bytecode-native-rooted-cfg-plan input))
           (op (car (last (plist-get (car (plist-get plan :blocks)) :operations) 2))))
      (should (eq (plist-get input :status) 'complete))
      (should (eq (plist-get plan :status) 'complete))
      (should (< (plist-get plan :required-root-count) 256))
      (should (= (plist-get op :argument-count) (cadr row)))
      (should (equal (plist-get op :argument-roots)
                     (if (> (cadr row) 4) (cons 1 (make-list (1- (cadr row)) 2))
                       (number-sequence 1 (cadr row)))))
      (should (eq (plist-get op :opcode) (if (> (cadr row) 32) 'list-build 'primitive-call)))
      (when (> (cadr row) 32)
        (should (integerp (plist-get op :apply-function-root)))
        (should (integerp (plist-get op :target-function-root))))
      (let* ((emitted (nelisp-bytecode-native-rooted-cfg-shared-emit-build
                       plan nelisp-bytecode-native-rooted-cfg-contract-shared-entry))
             (contract (nelisp-bytecode-native-rooted-cfg-contract-create-shared-v2 input plan emitted)))
        (should (eq (plist-get emitted :status) 'complete))
        (should (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract))
        (should (nelisp-bytecode-native-rooted-cfg-contract-f1-p contract)))
      ;; Packed-call targets and argument order are authenticated plan facts.
      (when (> (cadr row) 32)
        (let* ((mutant (copy-tree plan))
               (mutant-op (car (last (plist-get (car (plist-get mutant :blocks)) :operations) 2))))
          (plist-put mutant-op :target-function-root (plist-get mutant-op :function-root))
          (should-not (eq (plist-get (nelisp-bytecode-native-rooted-cfg-shared-emit-build
                                     mutant nelisp-bytecode-native-rooted-cfg-contract-shared-entry) :status)
                          'complete)))))))
(ert-deftest u3b/gnu-count-order-and-buffer-point ()
  (dolist (row (native-concat-u3b-fixtures))
    (let* ((opcode (car row)) (count (cadr row))
           (args (native-concat-u3b-args opcode count))
           (fn (apply #'native-concat-u3b-function row))
           (reference (if (= opcode 177) #'insert #'concat)))
      (should (equal (native-concat-u3b-observe fn args opcode)
                     (native-concat-u3b-observe reference (native-concat-u3b-values args count) opcode)))))
  (dolist (opcode '(176 177))
    (dolist (count '(-1 256 65535)) (should-error (native-concat-u3b-function opcode count)))))
(ert-deftest u3b/sequence-types-and-byte-modes ()
  (dolist (args (list (list (unibyte-string 65 255) (unibyte-string 66))
                     (list "λ" "尾") (list [65 955] '(66 23614))
                     (list (make-bool-vector 0 nil) nil)
                     (list (make-bool-vector 2 t) "x") (list "x" 'bad)))
    (should (equal (native-concat-u3b-observe (native-concat-u3b-function 80 2) args 80)
                   (native-concat-u3b-observe #'concat args 80)))))
(ert-deftest u3b/underflow-truncation-and-storage-refused ()
  (dolist (op '(80 81 82))
    (should-not (eq (plist-get (nelisp-bytecode-compiler-input-build
                               (make-byte-code 0 (unibyte-string op 135) [] 1)) :status) 'complete)))
  (dolist (op '(176 177))
    (dolist (code (list (unibyte-string op) (unibyte-string op 1 135)))
      (should-not (eq (plist-get (nelisp-bytecode-compiler-input-build
                                 (make-byte-code 0 code [] 1)) :status) 'complete)))
    (let* ((valid (native-concat-u3b-function op 255))
           (fn (make-byte-code (aref valid 0) (aref valid 1) (aref valid 2) 254)))
      (should-not (eq (plist-get (nelisp-bytecode-native-rooted-cfg-plan
                                 (nelisp-bytecode-compiler-input-build fn)) :status) 'complete)))))
(ert-deftest u3b/frozen-values-and-defensive-family-copy ()
  (let ((native-comp-enable-subr-trampolines nil))
    (dolist (name '(concat insert apply))
      (let ((value (nelisp-native-funcall-v2-initializer name))
            (old (symbol-function name)) (restore (symbol-function 'fset)) actual)
        (unwind-protect
            (progn (funcall restore name (lambda (&rest _) 'poison))
                   (setq actual (nelisp-native-funcall-v2-initializer name)))
          (funcall restore name old))
        (should (eq value actual)))))
  (dolist (op '(80 81 82 176 177))
    (let* ((row (nelisp-native-funcall-v2-primitive op)) (expected (if (= op 177) 'insert 'concat)))
      (should (eq (cadr row) expected)) (setcar (cdr row) 'poison)
      (should (eq (cadr (nelisp-native-funcall-v2-primitive op)) expected)))))
(ert-deftest u3b/error-retains-mutation-and-partial-insert ()
  (dolist (op '(80 177))
    (let ((cell (cons 'before 'tail)))
      (with-temp-buffer
        (should (eq (car (condition-case err (funcall (native-concat-u3b-mutation-error op) cell)
                           (error err))) 'wrong-type-argument))
        (should (equal (buffer-string) (if (= op 177) "first" "")))
        (should (equal cell '(changed . tail)))))))
(provide 'nelisp-native-concat-u3b-test)
