;;; nelisp-dev-source-test.el --- nonexecuting source contracts -*- lexical-binding: t; -*-
(require 'ert)
(require 'nelisp-dev-source)

(ert-deftest nelisp-dev-source-function-quotes-preserve-function-namespace ()
  (let* ((text "(defun f\\ name () 1)\n#'f\\ name\n(function f\\ name)\n'(function f\\ name)\n")
         (offset (string-match "#'" text))
         (lookup (nelisp-dev-source-lookup text (+ offset 2)))
         (refs (nelisp-dev-source-references text (+ offset 2))))
    (should (equal (cdr (assoc "symbol" lookup)) "f name"))
    (should (equal (cdr (assoc "namespace" lookup)) "function"))
    (should (= (length refs) 3))
    (should (= (length (nelisp-dev-source-occurrences text "f name" "function")) 3))
    (let ((uninterned "(defun target () 1)\n#'#:target"))
      (should-not (nelisp-dev-source-lookup uninterned (+ (string-match "#'" uninterned) 2))))
    (should-not (nelisp-dev-source-lookup "(cl-flet ((f () 1)) #'f)" 21 nil t))))

(ert-deftest nelisp-dev-source-function-quote-does-not-hide-parameter-names ()
  (let ((text "(defun f (function target) function)"))
    (should (= (length (nelisp-dev-source-references text 10)) 2))))

(ert-deftest nelisp-dev-source-function-quote-reuses-reader-record ()
  (with-temp-buffer
    (insert "#'f\\ name")
    (goto-char (point-min))
    (let* ((form (read (current-buffer)))
           (record (list :form form :start 0 :end (1- (point))))
           (original (symbol-function 'read)) (calls 0) argument)
      (cl-letf (((symbol-function 'read) (lambda (&rest args) (setq calls (1+ calls)) (apply original args))))
        (setq argument (nelisp-dev-source--function-argument record)))
      (should (eq (plist-get argument :form) (cadr form)))
      (should (= (plist-get argument :start) 2))
      (should (= (plist-get argument :end) 9))
      (should (= calls 0)))))

(ert-deftest nelisp-dev-source-global-occurrences-exclude-local-bindings ()
  (let* ((text "(defun caller (target) (progn target (target 1)))\n'(target)\n; target\n\"target\"")
         (calls (nelisp-dev-source-occurrences text "target" "function")))
    (should (= (length calls) 1))
    (should (eq (cdr (assoc "declaration" (aref calls 0))) :false))
    (should (= (length (nelisp-dev-source-occurrences text "target" "variable")) 0)))
  (should (= (length (nelisp-dev-source-occurrences "(defvar world 0)\nworld\n(let ((world 1)) world)" "world" "variable")) 2)))

(ert-deftest nelisp-dev-source-unresolved-tokens-retain-context-boundaries ()
  (should-not (nelisp-dev-source-lookup "(external 1)" 2))
  (let ((token (nelisp-dev-source-lookup "(external 1)" 2 nil t)))
    (should (equal (cdr (assoc "namespace" token)) "function"))
    (should (equal (cdr (assoc "symbol" token)) "external"))
    (should (= (length (cdr (assoc "definitions" token))) 0)))
  (should-not (nelisp-dev-source-lookup "'(external)" 3 nil t))
  (should-not (nelisp-dev-source-lookup "(opaque (external))" 10 nil t))
  (let ((source "(cl-defun f (&key x) x)"))
    (should-not (nelisp-dev-source-lookup source (- (length source) 2) nil t))))

(ert-deftest nelisp-dev-source-local-completion-scope ()
  (cl-labels ((names (text)
               (mapcar (lambda (item) (cdr (assoc "symbol" item)))
                       (append (nelisp-dev-source-local-completions text (length text)) nil))))
    (should (equal (names "(defun f (argument &optional extra) (let ((local 1)) ")
                   '("local" "extra" "argument")))
    (should (equal (names "(let ((outer 1)) (let ((inner 2) (next ") '("outer")))
    (should (equal (names "(let ((outer 1)) (let* ((inner 2) (next ") '("inner" "outer")))
    (should (equal (names "(let ((same 1)) (let ((same 2)) sa") '("same")))
    (dolist (text '("(let ((x 1)) '(" "(let ((x 1)) \"" "(let ((x 1)) ; comment"
                    "(let ((x 1)) (opaque " "(cl-flet ((f () 1)) " "(defun f (&key x) "))
      (should-not (names text)))))

(ert-deftest nelisp-dev-source-builtin-context-is-only-a-fallback ()
  (let* ((builtin '(("symbol" . "+") ("kind" . "builtin")))
         (macro '(("symbol" . "+") ("kind" . "defmacro")))
         (function '(("symbol" . "+") ("kind" . "defun")))
         (text "(let ((local 1)) (+ local))"))
    (should (= (length (nelisp-dev-source-references text (- (length text) 3) nil (list builtin))) 2))
    (should (= (length (nelisp-dev-source-references text (- (length text) 3) nil (list builtin macro))) 0))
    (should (= (length (nelisp-dev-source-references text (- (length text) 3) nil (list builtin function function))) 0))
    (let ((source (concat "(defun + (value) value)\n" text)))
      (should (= (length (nelisp-dev-source-references source (- (length source) 3) nil (list builtin macro))) 2)))
    (should-not (nelisp-dev-source-signature "(+ " 3 (list builtin)))))

(ert-deftest nelisp-dev-source-reader-catalog-is-literal-data ()
  (defvar nelisp-dev-source-test--catalog-side-effect nil)
  (let ((nelisp-dev-source-test--catalog-side-effect nil)
        (text "(defconst nelisp-standalone--reader-builtins (append '(\"+\" \"car\") (progn (setq nelisp-dev-source-test--catalog-side-effect t) '(\"conditional\"))))"))
    (should (equal (mapcar (lambda (item) (cdr (assoc "symbol" item)))
                          (append (nelisp-dev-source-reader-builtins text) nil)) '("+" "car")))
    (should-not nelisp-dev-source-test--catalog-side-effect)
    (eval '(setq nelisp-dev-source-test--catalog-side-effect t))
    (should nelisp-dev-source-test--catalog-side-effect)
    (should-error (nelisp-dev-source-reader-builtins (concat text text)))
    (should-error (nelisp-dev-source-reader-builtins
                   "(defconst nelisp-standalone--reader-builtins (append (list \"computed\") nil))"))
    (should-error (nelisp-dev-source-reader-builtins
                   "(defconst nelisp-standalone--reader-builtins (append '(\"duplicate\" \"duplicate\") nil))"))))

(ert-deftest nelisp-dev-source-occurrences-share-declaration-classification ()
  (let ((original (symbol-function 'nelisp-dev-source--declarations)) (calls 0)
        (text "(defvar global 1)\n(progn global global global global)"))
    (cl-letf (((symbol-function 'nelisp-dev-source--declarations)
               (lambda (records source) (setq calls (1+ calls)) (funcall original records source))))
      (should (= (length (nelisp-dev-source-occurrences text "global" "variable")) 5))
      (should (= calls 1))
      (setq calls 0)
      (should (= (length (nelisp-dev-source-occurrences text "absent" "variable")) 0))
      (should (= calls 0)))))

(ert-deftest nelisp-dev-source-shared-classification-keeps-context-boundaries ()
  (let* ((text "(defvar global 1)\n(external global)")
         (parsed (nelisp-dev-source--parse text))
         (function '((("symbol" . "external") ("kind" . "defun"))))
         (macro '((("symbol" . "external") ("kind" . "defmacro"))))
         (nelisp-dev-source--lookup-context
          (nelisp-dev-source--prepare-lookup-context (plist-get parsed :forms) text function)))
    (should (nelisp-dev-source-lookup text (- (length text) 3) parsed t function))
    (should-not (nelisp-dev-source-lookup text (- (length text) 3) parsed t macro))))

(ert-deftest nelisp-dev-source-external-reference-contexts ()
  (let ((text "(defvar global 1)\n(let ((local global)) (external global local))")
        (external '((("symbol" . "external") ("kind" . "defun")))))
    (should (= (length (nelisp-dev-source-occurrences text "global" "variable" external)) 3))
    (should (= (length (nelisp-dev-source-occurrences text "local" "variable" external)) 0))
    (should (= (length (nelisp-dev-source-references text (- (length text) 3) nil external)) 2))
    (setcdr (assoc "kind" (car external)) "defmacro")
    (should (= (length (nelisp-dev-source-occurrences text "global" "variable" external)) 2))
    (should (= (length (nelisp-dev-source-references text (- (length text) 3) nil external)) 0))))

(ert-deftest nelisp-dev-source-external-call-contexts ()
  (let ((function '(("symbol" . "external") ("kind" . "defun")
                    ("signature" . "(x)") ("documentation" . "External")))
        (macro '(("symbol" . "external") ("kind" . "defmacro")))
        (text "(let ((local 1)) (external "))
    (should (equal (cdr (assoc "symbol" (aref (nelisp-dev-source-local-completions text (length text) (list function)) 0)))
                   "local"))
    (should (= (length (nelisp-dev-source-local-completions text (length text) (list macro))) 0))
    (should (= (length (nelisp-dev-source-local-completions text (length text) (list function function))) 0))
    (let ((source (concat "(defmacro external (x) x)\n" text)))
      (should (= (length (nelisp-dev-source-local-completions source (length source) (list function))) 0)))
    (let ((source "(external (external "))
      (should (equal (cdr (assoc "label" (nelisp-dev-source-signature source (length source) (list function))))
                     "external (x)")))))

(ert-deftest nelisp-dev-source-local-completion-shares-one-parse ()
  (let ((original (symbol-function 'nelisp-dev-source--parse)) (calls 0)
        (text "(defun f (one two three four) (let ((five 5)) "))
    (cl-letf (((symbol-function 'nelisp-dev-source--parse)
               (lambda (source) (setq calls (1+ calls)) (funcall original source))))
      (should (= (length (nelisp-dev-source-local-completions text (length text))) 5))
      (should (= calls 1)))))

(ert-deftest nelisp-dev-source-signature-external-context-boundaries ()
  (let ((external '((("symbol" . "f") ("kind" . "defun")
                     ("signature" . "(x)") ("documentation" . "External docs")))))
    (dolist (text '("(f " "(let ((f 1)) (f "))
      (should (equal (cdr (assoc "label" (nelisp-dev-source-signature text (length text) external))) "f (x)")))
    (dolist (text '("'(f " "(opaque (f " "(cl-flet ((f () 1)) (f " "\"(f " "; (f "))
      (should-not (nelisp-dev-source-signature text (length text) external)))
    (let* ((text "(defun f (local) local)\n(f ")
           (result (nelisp-dev-source-signature text (length text) external)))
      (should (equal (cdr (assoc "label" result)) "f (local)")))
    (should-not (nelisp-dev-source-signature "(f " 3 (append external external)))))

(ert-deftest nelisp-dev-source-signature-handles-incomplete-call-context ()
  (let* ((definition "(defun f (x &optional y &rest more) \"Literal docs\" x)\n")
         (text (concat definition "(f 1 "))
         (result (nelisp-dev-source-signature text (length text))))
    (should (equal (cdr (assoc "label" result)) "f (x &optional y &rest more)"))
    (should (= (cdr (assoc "active_parameter" result)) 1))
    (should (= (length (cdr (assoc "parameters" result))) 3))
    (dolist (tail '("'(f " "(opaque (f " "\"(f " "; (f "))
      (let ((source (concat definition tail)))
        (should-not (nelisp-dev-source-signature source (length source)))))
    (let ((source (concat definition "(f 1 2 3 4 ")))
      (should (= (cdr (assoc "active_parameter" (nelisp-dev-source-signature source (length source)))) 2)))))

(ert-deftest nelisp-dev-source-rename-shares-one-reader-snapshot ()
  (let ((original (symbol-function 'nelisp-dev-source--parse)) (calls 0)
        (text ";;; -*- lexical-binding: t; -*-\n(defun f (x) x)"))
    (cl-letf (((symbol-function 'nelisp-dev-source--parse)
               (lambda (input) (setq calls (1+ calls)) (funcall original input))))
      (should (= (length (cdr (assoc "edits" (nelisp-dev-source-rename text (- (length text) 2) "renamed")))) 2))
      (should (= calls 1)))))

(ert-deftest nelisp-dev-source-rename-local-validates-entire-owner ()
  (let* ((header ";;; -*- lexical-binding: t; -*-\n")
         (text (concat header "(defun f (x) (let ((y x)) x))"))
         (offset (+ (length header) 10))
         (plan (nelisp-dev-source-rename text offset "名前")))
    (should (= (length (cdr (assoc "edits" plan))) 3))
    (should (equal (cdr (assoc "newText" (aref (cdr (assoc "edits" plan)) 0))) "名前"))
    (should-error (nelisp-dev-source-rename text offset "y"))
    (should-error (nelisp-dev-source-rename text offset "nil"))
    (should-error (nelisp-dev-source-rename (concat text "(") offset "z"))
    (should-error (nelisp-dev-source-rename (concat header "(defun f (x) (opaque x))") offset "z"))
    (should-error (nelisp-dev-source-rename (concat header "(defun f (x) (when t x))\n(defmacro when (&rest body) body)") offset "z"))
    (should-error (nelisp-dev-source-rename "\"lexical-binding: t;\"\n(defun f (x) x)" 31 "z"))
    (should-error (nelisp-dev-source-rename "(defun f (x) x)" 10 "z"))
    (should-error (nelisp-dev-source-rename (concat header "(defvar x 0)\n(defun f (x) x)")
                                           (+ (length header) 23) "z"))
    (should (= (length (cdr (assoc "edits" (nelisp-dev-source-rename text offset "x")))) 0))))

(ert-deftest nelisp-dev-source-references-respect-bindings-and-reader-data ()
  (let* ((text "(defun f (x) x)\n(f 1)\n'(f 2)\n\"f\" ; f\n(let ((f 3)) f)")
         (refs (nelisp-dev-source-references text 7)))
    (should (= (length refs) 2))
    (should (eq (cdr (assoc "declaration" (aref refs 0))) t))
    (should (eq (cdr (assoc "declaration" (aref refs 1))) :false))
    (should (= (length (nelisp-dev-source-references text 10)) 2))
    (should (= (length (nelisp-dev-source-references
                       "(defvar x 0)\n(let ((x 1)) (let ((x x)) x))" 20)) 2))
    (should (= (length (nelisp-dev-source-references "(defun f () 1)\n(defun f () 2)\n(f)" 7)) 0))))

(ert-deftest nelisp-dev-source-lookup-preserves-nested-variable-scopes ()
  (let* ((text "(defvar item 0)\n(let ((item 1))\n  (let ((item item)) item))")
         (initializer (string-match "item))" text))
         (body (string-match "item))$" text))
         (outer (aref (cdr (assoc "definitions" (nelisp-dev-source-lookup text initializer))) 0))
         (inner (aref (cdr (assoc "definitions" (nelisp-dev-source-lookup text body))) 0)))
    (should (equal (cdr (assoc "kind" outer)) "binding"))
    (should (= (cdr (assoc "line" (cdr (assoc "start" outer)))) 2))
    (should (= (cdr (assoc "line" (cdr (assoc "start" inner)))) 3))
    (should-not (nelisp-dev-source-lookup
                 "(defvar item 0)\n(cl-defun f (&key item) item)" 39))))

(ert-deftest nelisp-dev-source-lookup-recognizes-reader-contexts ()
  (let* ((text "(defun f\\ name (x) \"Literal\" x)\n(defun caller () (f\\ name 1))")
         (offset (string-match "f\\\\ name 1" text))
         (result (nelisp-dev-source-lookup text offset)))
    (should (equal (cdr (assoc "symbol" result)) "f name"))
    (should (= (length (cdr (assoc "definitions" result))) 1))
    (should-not (nelisp-dev-source-lookup "(defun f () 1)\n'(f)" 17))
    (should-error (nelisp-dev-source-lookup text -1))))

(ert-deftest nelisp-dev-source-completion-preserves-strict-symbol-contract ()
  (let* ((text "(error \"do not run\")\n(defun complete (x) \"Literal docs\" x)\n(incomplete")
         (symbols (nelisp-dev-source-completion-symbols text)))
    (should (= (length symbols) 1))
    (should (equal (cdr (assoc "symbol" (aref symbols 0))) "complete"))
    (should (equal (cdr (assoc "insert_text" (aref symbols 0))) "complete"))
    (should-error (nelisp-dev-source-symbols text))
    ;; Declarations after a reader error are not guessed or recovered by regex.
    (should (= (length (nelisp-dev-source-completion-symbols ") (defun later () 1)")) 0))))

(ert-deftest nelisp-dev-source-symbol-docs-are-nonexecuting ()
  (let* ((text "(error \"must not run\")\n(defun 文 (x) \"日本語 <script>\" x)\n(defvar setting 1 \"Setting docs\")\n")
         (symbols (nelisp-dev-source-symbols text)))
    (should (= (length symbols) 2))
    (should (equal (cdr (assoc "documentation" (aref symbols 0))) "日本語 <script>"))
    (should (equal (cdr (assoc "kind" (aref symbols 1))) "defvar"))
    (should (= (cdr (assoc "line" (cdr (assoc "start" (aref symbols 0))))) 2))
    (should-error (nelisp-dev-source-symbols "(defun broken ("))))

(ert-deftest nelisp-dev-source-arity-scope-and-stable-occurrences ()
  (let* ((text "(defun f (x) x)\n(defun caller () (f) (f) 42)\n")
         (first (nelisp-dev-source-test--run text "check"))
         (second (nelisp-dev-source-test--run text "check"))
         (rows (cdr (assoc "diagnostics" first))))
    (should (= 2 (length rows)))
    (should (equal rows (cdr (assoc "diagnostics" second))))
    (should-not (equal (cdr (assoc "id" (aref rows 0)))
                       (cdr (assoc "id" (aref rows 1)))))
    (should (equal "definition" (cdr (assoc "precision" (aref rows 0)))))
    (should (= 0 (length (cdr (assoc "diagnostics"
      (nelisp-dev-source-test--run text "describe" "f"))))))))

(ert-deftest nelisp-dev-source-arity-rejects-unsupported-lambda-lists ()
  (dolist (args '((x &rest rest tail) (x &rest nil) (x &optional &optional y)
                  (&rest r &optional x) (&unknown x) (nil) (t) (x x)
                  ((x)) (x . rest)))
    (should-not (nelisp-dev-source--plain-arity args)))
  (dolist (text '("(defun f (x) x) (defmacro f () nil) (defun caller () (f))"
                  "(defun f (x) x) (cl-defun f () nil) (defun caller () (f))"
                  "(defun f (x) x) (defmacro when (&rest x) nil) (defun caller () (when (f)))"))
    (should (= 0 (length (cdr (assoc "diagnostics"
                                   (nelisp-dev-source-test--run text "check"))))))))

(defun nelisp-dev-source-test--run (text op &optional symbol)
  (let ((root (make-temp-file "nelisp-source-test-" t)))
    (unwind-protect
        (progn
          (let ((coding-system-for-write 'utf-8-unix))
            (with-temp-file (expand-file-name "fixture.el" root)
              (insert text)))
          (nelisp-dev-source-dispatch
           (list (cons "operation" op) (cons "request_id" "test")
                 (cons "arguments" (list (cons "path" "fixture.el") (cons "symbol" symbol))))
           (list :root root :target "host-emacs")))
      (delete-directory root t))))

(defun nelisp-dev-source-test--diagnostics (result)
  (cdr (assoc "diagnostics" result)))

(ert-deftest nelisp-dev-source-check-proves-plain-defun-arities ()
  (let* ((text (concat
                "(defun required (a b) nil)\n"
                "(defun optional (a &optional b) nil)\n"
                "(defun variadic (a &rest rest) nil)\n"
                "(defun caller ()\n"
                "  (required 1)\n"
                "  (required 1 2 3)\n"
                "  (optional)\n"
                "  (optional 1 2 3)\n"
                "  (variadic))\n"))
         (result (nelisp-dev-source-test--run text "check"))
         (diagnostics (nelisp-dev-source-test--diagnostics result)))
    (should (equal "failed" (cdr (assoc "status" result))))
    (should (= 5 (length diagnostics)))
    (should (cl-every (lambda (diagnostic)
                        (equal "NELISP-CHECK-ARITY"
                               (cdr (assoc "code" diagnostic))))
                      diagnostics))))

(ert-deftest nelisp-dev-source-check-keeps-uncertain-calls-inconclusive ()
  (let* ((text (concat
                "(defun target (a b) nil)\n"
                "(defun target (x) nil)\n"
                "(cl-defun destructuring ((a b)) nil)\n"
                "(defmacro known-macro (&rest body) body)\n"
                "(defun caller ()\n"
                "  '(target 1)\n"
                "  (unknown-macro (target 1))\n"
                "  (known-macro (target 1))\n"
                "  (flet ((target (x y) x)) (target 1))\n"
                "  (cl-labels ((target (x y) x)) (target 1))\n"
                "  (destructuring 1))\n"))
         (result (nelisp-dev-source-test--run text "check")))
    (should (equal "inconclusive" (cdr (assoc "status" result))))
    (should (= 0 (length (nelisp-dev-source-test--diagnostics result))))))

(ert-deftest nelisp-dev-source-reader-distinguishes-boundary-eof ()
  (dolist (text '("(defun bad (x)" "(defun bad (x) (list x)" "\"" "(a . )" ")"))
    (let ((result (nelisp-dev-source-test--run text "check")))
      (should (equal "failed" (cdr (assoc "status" result))))
      (should (equal "NELISP-CHECK-SYNTAX"
                     (cdr (assoc "code" (aref (cdr (assoc "diagnostics" result)) 0)))))))
  (dolist (text '("" "; comment (\n" "42 ; trailing (\n"
                  "(defun f () \"(\") ; )\n" "(list ?\\()"))
    (should (equal "inconclusive"
                   (cdr (assoc "status" (nelisp-dev-source-test--run text "check")))))))

(ert-deftest nelisp-dev-source-exact-unicode-span-and-raw-hash ()
  (let* ((text "\"界\" (defun  α (x) x)\n(defun other () nil)\n")
         (result (nelisp-dev-source-test--run text "describe" "α"))
         (definition (aref (cdr (assoc "definitions" (cdr (assoc "data" result)))) 0))
         (start (cdr (assoc "start" definition))) (end (cdr (assoc "end" definition))))
    (should (equal "ok" (cdr (assoc "status" result))))
    (should (= 1 (cdr (assoc "line" start))))
    (should (= 5 (cdr (assoc "column" start))))
    (should (= 6 (cdr (assoc "byte_offset" start))))
    (should (= 1 (cdr (assoc "line" end))))
    (should (= 21 (cdr (assoc "column" end))))
    (should (equal (concat "sha256:" (secure-hash 'sha256 (encode-coding-string text 'utf-8-unix)))
                   (cdr (assoc "source_content_hash" (cdr (assoc "identity" result))))))))

(ert-deftest nelisp-dev-source-duplicates-are-not-a-loaded-definition ()
  (let* ((result (nelisp-dev-source-test--run "(defun f () 1)\n(defun f () 2)" "describe" "f"))
         (definitions (cdr (assoc "definitions" (cdr (assoc "data" result))))))
    (should (equal "inconclusive" (cdr (assoc "status" result))))
    (should (= 2 (length definitions)))
    (should (= 2 (cdr (assoc "line" (cdr (assoc "start" (aref definitions 1)))))))))

(ert-deftest nelisp-dev-source-never-executes-application-or-macro ()
  (let ((symbol (intern (make-temp-name "nelisp-source-test-effect-"))))
    (set symbol 0)
    (dolist (op '("check" "describe" "impact"))
      (let* ((text (format "(setq %s 9)\n(defmacro evil () (error \"executed\"))\n(evil)\n(defun f () (funcall callback))"
                           (symbol-name symbol)))
             (result (nelisp-dev-source-test--run text op "f")))
        (should-not (equal "failed" (cdr (assoc "status" result))))))
    (unwind-protect (should (= 0 (symbol-value symbol)))
      (unintern symbol obarray))))

(ert-deftest nelisp-dev-source-impact-ignores-quoted-and-variable-references ()
  (let* ((text "(defun quoted () '(callee x))\n(defun variable (callee) (list callee))\n(defun caller (x) (callee x))")
         (result (nelisp-dev-source-test--run text "impact" "callee"))
         (edges (cdr (assoc "callers" (cdr (assoc "data" result))))))
    (should (equal "inconclusive" (cdr (assoc "status" result))))
    (should (= 1 (length edges)))
    (should (equal "caller" (cdr (assoc "caller" (aref edges 0)))))
    (should (equal "syntactic-call-candidate" (cdr (assoc "kind" (aref edges 0)))))))

(ert-deftest nelisp-dev-source-stable-diagnostic-id-and-input-limits ()
  (let* ((a (nelisp-dev-source-test--run "(defun broken (" "check"))
         (b (nelisp-dev-source-test--run "(defun broken (" "check")))
    (should (equal (cdr (assoc "id" (aref (cdr (assoc "diagnostics" a)) 0)))
                   (cdr (assoc "id" (aref (cdr (assoc "diagnostics" b)) 0))))))
  (let ((root (make-temp-file "nelisp-source-limit-" t)))
    (unwind-protect
        (dolist (path '(nil "../outside.el" "missing.el"))
          (let ((result (nelisp-dev-source-dispatch
                         (list (cons "operation" "check") (cons "request_id" "test")
                               (cons "arguments" (list (cons "path" path))))
                         (list :root root))))
            (should (equal "failed" (cdr (assoc "status" result))))))
      (delete-directory root t))))
