;;; nelisp-native-frame-u7a-test.el --- Frame bridge admission -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'ert)
(require 'nelisp-bytecode-native-rooted-cfg-contract)
(require 'nelisp-native-frame-v2)
(require 'nelisp-native-gccjit)
(load "support/native-frame-u7a-fixtures.el" nil t t)
(defvar u7a-buffer nil)
(unless (fboundp 'nelisp--make-record)
  (defun nelisp--make-record (tag &rest slots) (apply #'record tag slots))
  (defun nelisp--record-ref (rec i) (aref rec (1+ i)))
  (defun nelisp--record-set (rec i value) (aset rec (1+ i) value))
  (defun nelisp--record-type (rec) (aref rec 0)))
(defun u7a-function (n)
  (make-byte-code 0 (apply #'unibyte-string
                          (append (apply #'append (make-list n '(192 24)))
                                  (list (+ 40 n) 193 135))) [u7a-special result] 1))
(ert-deftest u7a/valid-structural-unbind-fixtures-shared-contract ()
  (skip-unless (equal emacs-version "31.1"))
  (dotimes (i 5)
    (let* ((fn (u7a-function (1+ i)))
           (input (nelisp-bytecode-compiler-input-build fn))
           (plan (nelisp-bytecode-native-rooted-cfg-plan input))
           (emitted (nelisp-bytecode-native-rooted-cfg-shared-emit-build
                     plan nelisp-bytecode-native-rooted-cfg-contract-shared-entry)))
      (should (eq (plist-get plan :status) 'complete))
      (should (member "nl_native_frame_v2" (plist-get emitted :gateway-imports)))
      (should (nelisp-bytecode-native-rooted-cfg-contract-valid-p
               (nelisp-bytecode-native-rooted-cfg-contract-create-shared-v2 input plan emitted))))))
(ert-deftest u7a/invalid-unbind-remains-refused ()
  (dotimes (i 5)
    (should-not (eq (plist-get (nelisp-bytecode-native-rooted-cfg-plan
                               (nelisp-bytecode-compiler-input-build
                                (make-byte-code 0 (unibyte-string (+ 41 i) 192 135) [nil] 1)))
                              :status) 'complete))))
(ert-deftest u7a/descriptor-copy-and-source-policy ()
  (let ((d (nelisp-native-frame-v2-descriptor)))
    (setcar (plist-get d :params) 'poison)
    (should (equal (plist-get (nelisp-native-frame-v2-descriptor) :params)
                   '(u64 u64 u64 u64 u64 u64))))
  (let* ((provider (nelisp-native-frame-v2-initializer))
         (mirror (nelisp-env-make))
         (state (funcall provider provider nil 0 '(1 2) mirror 10 nil)))
    (should-error (funcall provider provider state 2 '(1) mirror 10 nil))
    (dolist (name '(nil t :u7a-constant))
      (should-error (funcall provider provider state 1 (list name 42) mirror 10 42)
                    :type 'setting-constant))
    (let ((frame (funcall provider provider state 1 '(u7a-special 42) mirror 10 42)))
      (should (nelisp-lexframe-dynamic-p frame 'u7a-special))
      (should (= (nelisp-lexframe-lookup frame 'u7a-special) 42)))
    (should-error (funcall provider provider state 3 nil mirror 10 nil))
    (should (= (funcall provider provider state 3 nil mirror 11 nil) 1))
    ;; Validation leaves entries attached until the adapter pops each one.
    (should (aref state 1))
    (should (= (length (aref state 3)) 1))))

(ert-deftest u7a/variable-access-and-all-exits-admitted ()
  (skip-unless (equal emacs-version "31.1"))
  (dolist (name '(callback nested implicit set zero))
    (let* ((input (nelisp-bytecode-compiler-input-build (native-frame-u7a-function name)))
           (plan (nelisp-bytecode-native-rooted-cfg-plan input)))
      (should (eq (plist-get plan :status) 'complete))
      (let ((emitted (nelisp-bytecode-native-rooted-cfg-shared-emit-build
                      plan nelisp-bytecode-native-rooted-cfg-contract-shared-entry)))
        (should (eq (plist-get emitted :status) 'complete))
        ;; Banked entry phis already have physical roots: no CFG is needed.
        (should-not
         (cl-labels ((cfg-p (node)
                       (and (consp node)
                            (or (eq (car node) 'cfg) (cfg-p (car node))
                                (cfg-p (cdr node))))))
           (cfg-p (plist-get emitted :form))))))))

(ert-deftest u7a/bare-variable-access-admitted-without-unbind-prefix ()
  (skip-unless (equal emacs-version "31.1"))
  (dolist (bytes '((8 135) (192 16 192 135)))
    (let* ((fn (make-byte-code 0 (apply #'unibyte-string bytes) [u7a-special] 16))
           (plan (nelisp-bytecode-native-rooted-cfg-plan
                  (nelisp-bytecode-compiler-input-build fn))))
      (should (eq (plist-get plan :status) 'complete))
      (should (plist-get plan :frame-descriptor)))))

(ert-deftest u7a/safe-list-access-admitted-through-shared-funcall-bridge ()
  (skip-unless (equal emacs-version "31.1"))
  (dolist (opcode '(162 163))
    (let* ((fn (make-byte-code 0 (unibyte-string 192 opcode 193 32 136 135)
                               [42 garbage-collect] 16))
           (input (nelisp-bytecode-compiler-input-build fn))
           (plan (nelisp-bytecode-native-rooted-cfg-plan input))
           (emitted (nelisp-bytecode-native-rooted-cfg-shared-emit-build
                     plan nelisp-bytecode-native-rooted-cfg-contract-shared-entry)))
      (should (eq (plist-get plan :status) 'complete))
      (should (eq (plist-get emitted :status) 'complete))
      (should (nelisp-bytecode-native-rooted-cfg-contract-valid-p
               (nelisp-bytecode-native-rooted-cfg-contract-create-shared-v2
                input plan emitted))))))

(ert-deftest u7a/alias-target-cell-and-void-target ()
  (let* ((provider (nelisp-native-frame-v2-initializer))
         (mirror (nelisp-env-make))
         (alias (nelisp-env--ensure-entry mirror "u7a-alias"))
         (state (funcall provider provider nil 0 '(1 0) mirror 7 nil)))
    (nelisp-env--symbol-entry-set-alias-target alias 'u7a-target)
    (let ((frame (funcall provider provider state 1 '(u7a-alias 42) mirror 7 42)))
      (should (= (nelisp-lexframe-lookup frame 'u7a-target) 42))
      (should (nelisp-lexframe-dynamic-p frame 'u7a-target))
      (should-not (nelisp-env-is-bound mirror "u7a-target")))))
(ert-deftest u7a/gnu-buffer-local-and-watcher-oracles ()
  ;; Qualify the semantic oracle; these are not standalone execution receipts.
  (let* ((fn (native-frame-u7a-function 'callback)) (events nil)
        (watcher (lambda (symbol new operation where)
                   (push (list symbol new operation where) events))))
    (with-temp-buffer
      (setq-local u7a-special 'local)
      (let ((u7a-mode 'throw))
        (should (equal (car (native-frame-u7a-observe fn '(inside))) 'inside)))
      (should (eq u7a-special 'local)))
    (unwind-protect
        (progn
          (add-variable-watcher 'u7a-special watcher)
          (let ((u7a-mode 'throw))
            (native-frame-u7a-observe fn '(inside)))
          (should (equal (mapcar (lambda (e) (nth 2 e)) (reverse events)) '(let set))))
      (remove-variable-watcher 'u7a-special watcher))))
(ert-deftest u7a/gnu31-watcher-ordered-values-and-locality ()
  (skip-unless (equal emacs-version "31.1"))
  ;; The standalone interpreter lacks watchers. GNU 31.1 is the reference,
  ;; not evidence that the standalone API or callbacks have been implemented.
  (should (string-prefix-p "31.1" emacs-version))
  (let ((fn (native-frame-u7a-function 'callback)) (events nil))
    (let ((watcher (lambda (symbol new operation where)
                     (push (list symbol new operation where) events))))
      (unwind-protect
          (progn
            (add-variable-watcher 'u7a-special watcher)
            (dolist (mode '(nil throw signal))
              (setq events nil)
              (let ((u7a-mode mode)) (native-frame-u7a-observe fn '(inside)))
              (should (equal (reverse events)
                             '((u7a-special inside let nil) (u7a-special outside set nil)))))
            (with-temp-buffer
              (setq-local u7a-special 'local)
              (let ((buffer (current-buffer)))
                (setq events nil)
                (let ((u7a-mode 'throw)) (native-frame-u7a-observe fn '(inside)))
                (should (equal (reverse events)
                               (list (list 'u7a-special 'inside 'let buffer)
                                     (list 'u7a-special 'local 'unlet buffer)))))
              (should (eq (default-value 'u7a-special) 'outside))))
        (remove-variable-watcher 'u7a-special watcher)))))
(ert-deftest u7a/buffer-local-redirect-selected-before-specbind ()
  (let* ((provider (nelisp-native-frame-v2-initializer))
         (mirror (nelisp-env-make))
         (buffer (vector 'buffer))
         (table (nelisp--record-ref mirror 0))
         (entry (nelisp--make-record 'symbol-entry 'outside nil nil nil nil
                                     (vector 'u7a-buffer (list (cons buffer 'u7a-local-cell)))))
         (state (funcall provider provider nil 0 '(1 0) mirror 7 nil)))
    (nelisp--fast-hash-put table "u7a-special" entry)
    (let ((u7a-buffer buffer))
      (let ((frame (cl-letf (((symbol-function 'symbol-value)
                              (lambda (&rest _) (vector 'poisoned-buffer))))
                     (funcall provider provider state 1 '(u7a-special 42) mirror 7 42))))
        (should (nelisp-lexframe-dynamic-p frame 'u7a-local-cell))
        (should (= (nelisp-lexframe-lookup frame 'u7a-local-cell) 42))
        (should-not (nelisp-lexframe-dynamic-p frame 'u7a-special))))))
(ert-deftest u7a/gccjit-api-addresses-scoped-by-owner ()
  (let ((nelisp-native-gccjit--symbol-cache (make-hash-table :test #'equal))
        (calls 0))
    (cl-letf (((symbol-function 'nl-ffi--dlsym) (lambda (handle _name)
                                               (setq calls (1+ calls)) (+ 1000 handle))))
      (should (= (nelisp-native-gccjit--symbol 1 "api") 1001))
      (should (= (nelisp-native-gccjit--symbol 1 "api") 1001))
      (should (= (nelisp-native-gccjit--symbol 2 "api") 1002))
      (should (= calls 2)))))
(ert-deftest u7a/gnu31-local-wins-over-default-binding-in-other-buffer ()
  (let ((other (generate-new-buffer " u7a-host-other"))
        (fn (native-frame-u7a-function 'buffer-local)))
    (unwind-protect
        (progn
          (with-current-buffer other (setq-local u7a-special 'other-local))
          (let ((u7a-mode 'switch-read) (u7a-other-buffer other))
            (should (equal (native-frame-u7a-observe fn '(inside))
                           '((returned inside) (inside other-local other-changed) outside))))
          (with-current-buffer other (should (eq u7a-special 'other-changed)))
          (should (eq u7a-special 'outside)))
      (kill-buffer other))))
(ert-deftest u7a/gccjit-constants-are-owned-by-one-context ()
  (let ((serial 4096) (calls nil))
    (cl-letf (((symbol-function 'nelisp-native-gccjit--call)
               (lambda (name &rest args) (push (cons name args) calls) (setq serial (1+ serial))))
              ((symbol-function 'nelisp-native-gccjit--cstring) #'identity)
              ((symbol-function 'nelisp-native-gccjit--array) #'identity))
      (dotimes (_ 2)
        (nelisp-native-gccjit-lower
         '(defun probe (env ticket argument-count root-count) (progn 42 42 42)) nil))
      (let ((integers (cl-remove-if-not (lambda (c) (equal (car c) "gcc_jit_context_new_rvalue_from_long")) calls)))
        (should (= (cl-count 42 integers :key (lambda (c) (nth 3 c))) 2))))))
(ert-deftest u7a/frame-schema-tampering-rejected ()
  (skip-unless (equal emacs-version "31.1"))
  (let* ((input (nelisp-bytecode-compiler-input-build (u7a-function 1)))
         (plan (nelisp-bytecode-native-rooted-cfg-plan input))
         (emitted (nelisp-bytecode-native-rooted-cfg-shared-emit-build
                   plan nelisp-bytecode-native-rooted-cfg-contract-shared-entry))
         (contract (nelisp-bytecode-native-rooted-cfg-contract-create-shared-v2 input plan emitted)))
    (should (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract))
    (plist-put contract :frame-hash (make-string 64 ?0))
    (should-not (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract))))
