;;; nelisp-eln-objects-empty-symbols-test.el --- empty lease regression -*- lexical-binding: t; -*-

(require 'ert)
(require 'nelisp-eln-objects)

(ert-deftest nelisp-eln-add-empty-symbols-preserves-pinned-base ()
  (let* ((base (vector nil 100 nil 'open))
         (lease (vector nelisp-eln-objects--symbol-base-lease-marker base 'open))
         (unit (make-vector 7 nil)))
    (let ((nelisp-eln-objects--registry-state 'open)
          (nelisp-eln-objects--identity-records nil)
          (nelisp-eln-objects--symbol-base base)
          (nelisp-eln-objects--symbol-base-leases (list lease)))
      (should-not (nelisp-eln-objects--add-symbols unit nil))
      (should (eq nelisp-eln-objects--registry-state 'open))
      (should (eq nelisp-eln-objects--symbol-base base))
      (should (eq (car nelisp-eln-objects--symbol-base-leases) lease))
      (should-not (aref unit 6)))))

(ert-deftest nelisp-eln-add-symbols-failure-keeps-explicit-base-lease ()
  (let* ((base (vector nil 100 nil 'open))
         (lease (vector nelisp-eln-objects--symbol-base-lease-marker base 'open))
         (unit (make-vector 7 nil))
         (nelisp-eln-objects--registry-state 'open)
         (nelisp-eln-objects--identity-records nil)
         (nelisp-eln-objects--symbol-base base)
         (nelisp-eln-objects--symbol-base-leases (list lease)))
    (cl-letf (((symbol-function 'nelisp-eln-objects--symbol-record)
               (lambda (&rest _) nil))
              ((symbol-function 'nelisp-eln-objects--fresh-symbol-p)
               (lambda (&rest _) nil)))
      (should-error (nelisp-eln-objects--add-symbols unit '(uninterned-probe)))
      (should (eq nelisp-eln-objects--registry-state 'open))
      (should (eq nelisp-eln-objects--symbol-base base))
      (should (eq (car nelisp-eln-objects--symbol-base-leases) lease)))))

(ert-deftest nelisp-eln-add-symbols-release-failure-quarantines-registry ()
  (let* ((base (vector 'base-memory 100 nil 'open))
         (unit (make-vector 7 nil))
         (nelisp-eln-objects--registry-state 'open)
         (nelisp-eln-objects--identity-records nil)
         (nelisp-eln-objects--symbol-base base)
         (nelisp-eln-objects--symbol-base-leases nil))
    (cl-letf (((symbol-function 'nelisp-eln-objects--symbol-record)
               (lambda (&rest _) nil))
              ((symbol-function 'nelisp-eln-objects--fresh-symbol-p)
               (lambda (&rest _) nil))
              ((symbol-function 'nl-ffi-memory-release)
               (lambda (&rest _) (error "injected release failure"))))
      (should-error (nelisp-eln-objects--add-symbols unit '(uninterned-probe)))
      (should (eq nelisp-eln-objects--registry-state 'poisoned))
      (should (eq (aref base 3) 'releasing)))))

(provide 'nelisp-eln-objects-empty-symbols-test)
;;; nelisp-eln-objects-empty-symbols-test.el ends here
