(defun p35-vm-dyn0 (f) (funcall f))
(defun p35-vm-dyn1 (f a) (funcall f a))
(defun p35-vm-dyn2 (f a b) (funcall f a b))
(defun p35-vm-dyn3 (f a b c) (funcall f a b c))
(defun p35-vm-dyn6 (f a b c d e g) (funcall f a b c d e g))
(defun p35-vm-dynamic-required (p35-vm-dynamic-x p35-vm-dynamic-y) (list p35-vm-dynamic-x p35-vm-dynamic-y))
(defun p35-vm-dynamic-optional (p35-vm-dynamic-x &optional p35-vm-dynamic-y p35-vm-dynamic-z) (list p35-vm-dynamic-x p35-vm-dynamic-y p35-vm-dynamic-z))
(defun p35-vm-dynamic-rest (p35-vm-dynamic-x &optional p35-vm-dynamic-y &rest p35-vm-dynamic-r) (list p35-vm-dynamic-x p35-vm-dynamic-y p35-vm-dynamic-r))
(defun p35-vm-dynamic-allrest (&rest p35-vm-dynamic-r) p35-vm-dynamic-r)
(defun p35-vm-dynamic-duplicate (p35-vm-dynamic-x p35-vm-dynamic-x) p35-vm-dynamic-x)
(defun p35-vm-dynamic-scope (p35-vm-dynamic-x &optional p35-vm-dynamic-y &rest p35-vm-dynamic-r) (funcall p35-vm-dynamic-callback))
(defun p35-vm-dynamic-error (p35-vm-dynamic-x &optional p35-vm-dynamic-y &rest p35-vm-dynamic-r) (unwind-protect (error "dynamic-error") (setq p35-vm-dynamic-cleanup (list p35-vm-dynamic-x p35-vm-dynamic-y p35-vm-dynamic-r)) (garbage-collect)))
(defun p35-vm-dynamic-epoch (&rest p35-vm-dynamic-r) (ptr-read-u64 p35-vm-dynamic-epoch-address 0))
(defun p35-vm-dynamic-epoch-optional (p35-vm-dynamic-x &optional p35-vm-dynamic-y &rest p35-vm-dynamic-r) (ptr-read-u64 p35-vm-dynamic-epoch-address 0))
(defun p35-vm-dyn-epoch0 (f address) (let ((before (ptr-read-u64 address 0))) (let ((value (funcall f))) (list (- value before) (- (ptr-read-u64 address 0) before)))))
(defun p35-vm-dyn-epoch1 (f address a) (let ((before (ptr-read-u64 address 0))) (let ((value (funcall f a))) (list (- value before) (- (ptr-read-u64 address 0) before)))))
(defun p35-vm-dyn-epoch2 (f address a b) (let ((before (ptr-read-u64 address 0))) (let ((value (funcall f a b))) (list (- value before) (- (ptr-read-u64 address 0) before)))))
(defun p35-vm-dyn-epoch3 (f address a b c) (let ((before (ptr-read-u64 address 0))) (let ((value (funcall f a b c))) (list (- value before) (- (ptr-read-u64 address 0) before)))))
(defun p35-vm-dyn-epoch6 (f address a b c d e g) (let ((before (ptr-read-u64 address 0))) (let ((value (funcall f a b c d e g))) (list (- value before) (- (ptr-read-u64 address 0) before)))))
