;;; nelisp-primspeed-parity-smoke.el --- host-vs-standalone probe forms  -*- lexical-binding: t; -*-
;; Evaluated by both GNU Emacs and the standalone binary; the driver script
;; (nelisp-primspeed-parity-smoke.sh) diffs the printed lines.  Every probe
;; is wrapped so an error is printed as data instead of aborting the run.
(setq default-directory "/tmp/ps-base/")
(setenv "HOME" "/home/tester")
(defmacro ps--p (form)
  `(princ (format "%S => %S\n" ',form
                  (condition-case e ,form (error (list 'ERR (car e)))))))
;; expand-file-name: fast-path and general-path edge cases.
(ps--p (expand-file-name "/usr/share/emacs/foo.el"))
(ps--p (expand-file-name "/"))
(ps--p (expand-file-name "/usr/"))
(ps--p (expand-file-name "/usr//share"))
(ps--p (expand-file-name "/usr/./share"))
(ps--p (expand-file-name "/usr/share/.."))
(ps--p (expand-file-name "/usr/share/."))
(ps--p (expand-file-name "/usr/../../etc"))
(ps--p (expand-file-name "/.."))
(ps--p (expand-file-name "/../etc"))
(ps--p (expand-file-name "/../../etc"))
(ps--p (expand-file-name "/../../../etc"))
(ps--p (expand-file-name "/../"))
(ps--p (expand-file-name "/../x/"))
(ps--p (expand-file-name "/../a/../.."))
(ps--p (expand-file-name "/a/../../.."))
(ps--p (expand-file-name "../../../x"))
(ps--p (expand-file-name "foo/../../.."))
(ps--p (expand-file-name "/usr/share/../lib/x.el"))
(ps--p (expand-file-name "/.hidden/.f"))
(ps--p (expand-file-name "/a/...b/c"))
(ps--p (expand-file-name "foo.el"))
(ps--p (expand-file-name "foo/bar.el"))
(ps--p (expand-file-name "foo/"))
(ps--p (expand-file-name ".hidden"))
(ps--p (expand-file-name "./foo"))
(ps--p (expand-file-name "../foo"))
(ps--p (expand-file-name "foo/../bar"))
(ps--p (expand-file-name "foo//bar"))
(ps--p (expand-file-name "foo/."))
(ps--p (expand-file-name ".."))
(ps--p (expand-file-name "."))
(ps--p (expand-file-name ""))
(ps--p (expand-file-name "~"))
(ps--p (expand-file-name "~/x"))
(ps--p (expand-file-name "~/x/../y"))
(ps--p (expand-file-name "foo.el" "/usr/share/"))
(ps--p (expand-file-name "foo.el" "/usr/share"))
(ps--p (expand-file-name "foo.el" "/"))
(ps--p (expand-file-name "foo/bar" "/usr//share/"))
(ps--p (expand-file-name "foo" "/usr/share/.."))
(ps--p (expand-file-name "foo" "/usr/./share"))
(ps--p (expand-file-name "foo" "rel/dir"))
(ps--p (expand-file-name "foo" "~/d"))
(ps--p (expand-file-name "/abs/x" "/ignored/base"))
(ps--p (expand-file-name "foo" "/tmp/日本"))
(ps--p (expand-file-name "日本/x" "/tmp/"))
(ps--p (expand-file-name 'foo))
(ps--p (expand-file-name 5))
;; string-match compiled-pattern cache: mutation of the pattern string, case-fold
;; changes, match-data and backrefs must never see a stale compiled form.
(ps--p (let ((p (copy-sequence "a+")) r) (push (string-match p "xaa") r) (aset p 0 ?b) (push (string-match p "xbb") r) (push (string-match p "xaa") r) (nreverse r)))
(ps--p (let ((case-fold-search t) r) (push (string-match "abc" "xABC") r) (setq case-fold-search nil) (push (string-match "abc" "xABC") r) (setq case-fold-search t) (push (string-match "abc" "xABC") r) (nreverse r)))
(ps--p (let ((case-fold-search t)) (list (string-match "[a-c]+" "xABCd") (match-data))))
(ps--p (let ((case-fold-search nil)) (list (string-match "[a-c]+" "xABCd") (match-data))))
(ps--p (progn (string-match "\\(a\\)\\(b\\)?\\(c\\)" "zac") (match-data)))
(ps--p (list (string-match "\\(a+\\)\\1" "xaaaa") (match-data)))
(ps--p (list (string-match "\\w+\\s-+\\w+" "  foo   bar ") (match-data)))
(ps--p (list (string-match "\\_<foo-bar\\_>" "a foo-bar b") (match-data)))
(ps--p (list (string-match "^b" "a\nb") (string-match "\\`b" "a\nb") (string-match "a$" "a\nb")))
(ps--p (list (string-match "b" "abcb" 2) (string-match "b" "abcb" 4) (string-match-p "c" "abc")))
(ps--p (list (string-match "é+" "caféé") (match-end 0)))
(ps--p (let ((case-fold-search t)) (string-match "É" "café")))
(ps--p (progn (string-match "z" "abc") (string-match "\\(b\\)" "abc") (string-match "q" "abc") (match-data)))
;; string-search
(ps--p (string-search "//" "a//b"))
(ps--p (string-search "b" "abcabc" 2))
(ps--p (string-search "b" "abcabc" 6))
(ps--p (string-search "b" "abcabc" 7))
(ps--p (string-search "" "abc" 2))
(ps--p (string-search "abcd" "abc"))
(ps--p (string-search "é" "caféé"))
(ps--p (string-search "é" "caféé" 4))
(ps--p (string-search "日本" "これは日本語"))
(ps--p (string-search "x" "abc" -1))
(ps--p (string-search 1 "abc"))
;; equal / string-equal / string=
(ps--p (equal "abc" "abc"))
(ps--p (equal "abc" "abd"))
(ps--p (equal "abc" 'abc))
(ps--p (equal 'a 'a))
(ps--p (equal 'a "a"))
(ps--p (equal nil nil))
(ps--p (equal 1 1))
(ps--p (equal 1 1.0))
(ps--p (equal '(1 "a" b) '(1 "a" b)))
(ps--p (equal [1 "a"] [1 "a"]))
(ps--p (equal "a" '("a")))
(ps--p (equal 1.5 1.5))
(ps--p (string= "abc" "abc"))
(ps--p (string= 'abc "abc"))
(ps--p (string= "abc" 'abd))
(ps--p (string= nil "nil"))
(ps--p (string-equal "é" "é"))
(ps--p (string= 1 "1"))
(ps--p (string= "1" 1))
;; mapconcat
(ps--p (mapconcat #'identity '("a" "b" "c") "/"))
(ps--p (mapconcat #'identity nil "/"))
(ps--p (mapconcat #'identity '("a") "/"))
(ps--p (mapconcat #'identity '("a" "b") nil))
(ps--p (mapconcat #'symbol-name '(a b c) ", "))
(ps--p (mapconcat #'identity ["x" "y"] "-"))
(ps--p (mapconcat #'identity '("日" "本") "・"))
(ps--p (mapconcat #'string '(?a ?b) ""))
(ps--p (mapconcat (lambda (x) (list x)) '(?a ?b) ""))
(ps--p (mapconcat #'identity '(1 2) ","))
(ps--p (length (mapconcat (lambda (_) "abcde") (make-list 500 nil) ",")))
;; file-name-directory / nondirectory
(ps--p (file-name-directory "/a/b/c.el"))
(ps--p (file-name-directory "c.el"))
(ps--p (file-name-directory "/"))
(ps--p (file-name-directory "a/b/"))
(ps--p (file-name-directory ""))
(ps--p (file-name-nondirectory "/a/b/c.el"))
(ps--p (file-name-nondirectory "c.el"))
(ps--p (file-name-nondirectory "a/b/"))
(ps--p (file-name-nondirectory "/"))
(ps--p (file-name-nondirectory "日本/語.el"))
;; secure-hash
(ps--p (secure-hash 'sha256 ""))
(ps--p (secure-hash 'sha256 "abc"))
(ps--p (secure-hash 'sha256 "日本語テスト"))
(ps--p (secure-hash 'sha256 "é"))
(ps--p (secure-hash 'sha256 "abcdef" 1 4))
(ps--p (secure-hash 'sha256 "abcdef" 2))
(ps--p (secure-hash 'sha256 (unibyte-string 65 200 66)))
(ps--p (secure-hash 'sha256 (make-string 5000 ?x)))
(ps--p (length (secure-hash 'sha256 "abc" nil nil t)))
(ps--p (append (secure-hash 'sha256 "abc" nil nil t) nil))
(ps--p (secure-hash 'sha256 "abcdef" 4 2))
;; func-arity on byte-code function objects and others
(ps--p (func-arity (make-byte-code 257 "\300\207" [1] 2)))
(ps--p (func-arity (make-byte-code 385 "\300\207" [1] 2)))
(ps--p (func-arity (make-byte-code 0 "\300\207" [1] 2)))
(ps--p (func-arity (make-byte-code 514 "\300\207" [1] 3)))
(ps--p (func-arity (make-byte-code 769 "\300\207" [1] 4)))
(ps--p (func-arity (make-byte-code 641 "\300\207" [1] 4)))
(ps--p (func-arity (make-byte-code '(a &optional b) "\300\207" [1] 2)))
(ps--p (func-arity (make-byte-code '(a &rest b) "\300\207" [1] 2)))
(ps--p (func-arity (make-byte-code nil "\300\207" [1] 2)))
(ps--p (func-arity (lambda (a &optional b) a)))
(ps--p (func-arity 'car))
(ps--p (func-arity 5))
(ps--p (list (string-match "\\(a\\)\\1" "xaa") (string-match "\\(a*\\)b\\1" "aabaa") (match-data) (string-match "\\(a\\)\\1" "aA")))
(ps--p (let ((case-fold-search t)) (list (string-match "\\(a\\)\\1" "aA") (string-match "\\(é\\)\\1" "éÉ"))))
(ps--p (string-match "\\(a\\)?b\\1" "b"))
(ps--p (string-match "\\(a\\)\\2" "aa"))
(ps--p (let ((case-fold-search t)) (list (string-match "[é]" "É") (string-match "[а-я]+" "ПРИВЕТ") (string-match "éa" "xÉA"))))
(ps--p (list (regexp-quote "a.b*c+d?e[f]g^h$i\\j") (regexp-quote "") (regexp-quote "(a|b){1}") (regexp-quote "日本.語")))
(ps--p (list (file-name-as-directory "a") (file-name-as-directory "a/") (file-name-as-directory "") (file-name-as-directory "/")))
(ps--p (list (directory-file-name "a/") (directory-file-name "a//") (directory-file-name "/") (directory-file-name "///") (directory-file-name "a") (directory-file-name "")))
(ps--p (list (file-name-as-directory 5)))
(ps--p (list (regexp-quote 5)))
;; logb: integer and float exponents, subnormal/large values, non-finites,
;; signed zero, and GNU's numberp type error.
(ps--p (mapcar #'logb (list 0 1 -1 2 -2 3 most-positive-fixnum
                           (1+ most-positive-fixnum))))
(ps--p (mapcar #'logb (list 0.0 -0.0 0.5 1.0 2.0 3.0 8.0 0.1
                           5.0e-324 1.7976931348623157e+308)))
(ps--p (list (logb (/ 1.0 0.0)) (logb (/ -1.0 0.0))
             (logb (/ 0.0 0.0))))
(ps--p (logb "not a number"))
(ignore)
;;; nelisp-primspeed-parity-smoke.el ends here
