;;; nelisp-native-buffer-u4a-test.el --- Frozen buffer lowering -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'ert)
(require 'nelisp-bytecode-native-rooted-cfg-contract)
(require 'nelisp-bytecode-native-rooted-cfg-constructor-contract)
(require 'nelisp-bytecode-native-rooted-cfg-safe-contract)
(require 'nelisp-native-load)
(load "support/native-buffer-u4a-fixtures.el" nil t t)
(ert-deftest u4a/exact-ten-opcodes-and-both-contracts ()
  (skip-unless (equal emacs-version "31.1"))
  (dolist (row native-buffer-u4a-family)
    (should (equal row (nelisp-native-funcall-v2-primitive (car row))))
    (let* ((input (nelisp-bytecode-compiler-input-build (native-buffer-u4a-function row)))
           (plan (nelisp-bytecode-native-rooted-cfg-plan input))
           (op (car (plist-get (car (plist-get plan :blocks)) :operations)))
           (args (plist-get op :argument-roots)))
      (should (eq (plist-get input :status) 'complete))
      (should (eq (plist-get plan :status) 'complete))
      (should (eq (plist-get op :opcode) 'primitive-call))
      (should (equal (plist-get plan :gateway-imports) '("nl_native_funcall_v2")))
      (should (= (plist-get op :argument-count) (if (= (car row) 106) 2 (nth 2 row))))
      (if (= (car row) 106)
          (progn (should (= (car args) 1))
                 (should (member (list :root (cadr args) :value nil)
                                 (plist-get plan :immediate-initializers))))
        (should (equal args (number-sequence 1 (nth 2 row)))))
      (let* ((emitted (nelisp-bytecode-native-rooted-cfg-shared-emit-build
                       plan nelisp-bytecode-native-rooted-cfg-contract-shared-entry))
             (contract (nelisp-bytecode-native-rooted-cfg-contract-create-shared-v2 input plan emitted)))
        (should (eq (plist-get emitted :status) 'complete))
        (should (nelisp-bytecode-native-rooted-cfg-contract-valid-p contract))
        (should (nelisp-bytecode-native-rooted-cfg-contract-f1-p contract)))
      (let* ((safe (nelisp-bytecode-native-rooted-cfg-plan input 'safe-primitives-v3))
             (emitted (nelisp-bytecode-native-rooted-cfg-emit safe nelisp-bytecode-native-rooted-cfg-safe-contract-entry)))
        (should (nelisp-bytecode-native-rooted-cfg-safe-contract-valid-p
                 (nelisp-bytecode-native-rooted-cfg-safe-contract-create input safe emitted)))))))
(ert-deftest u4a/frozen-values-and-defensive-table ()
  (let ((native-comp-enable-subr-trampolines nil))
    (dolist (row native-buffer-u4a-family)
      (let* ((name (cadr row)) (value (nelisp-native-funcall-v2-initializer name))
             (old (symbol-function name)) (restore (symbol-function 'fset)))
        (should (functionp value))
        (unwind-protect
            (progn (funcall restore name (lambda (&rest _) 'poison))
                   (should (eq value (nelisp-native-funcall-v2-initializer name))))
          (funcall restore name old)))
      (let ((copy (nelisp-native-funcall-v2-primitive (car row))))
        (setcar (cdr copy) 'poison)
        (should (equal row (nelisp-native-funcall-v2-primitive (car row))))))))
(ert-deftest u4a/gnu-results-errors-text-and-markers ()
  (dolist (row native-buffer-u4a-family)
    (let ((vm (native-buffer-u4a-function row))
          (value (nelisp-native-funcall-v2-initializer (cadr row))))
      (dolist (narrow '(nil t))
        (dolist (position (if narrow '(2 4 6) '(1 3 5 7)))
          (dolist (args (native-buffer-u4a-cases (car row)))
            (should (equal (native-buffer-u4a-observe vm args position narrow)
                           (native-buffer-u4a-observe value args position narrow)))))))))
(ert-deftest u4a/underflow-and-neighbor-slots-refused ()
  (dolist (opcode '(98 99 102 106))
    (should-not (eq (plist-get (nelisp-bytecode-compiler-input-build
                               (make-byte-code 0 (unibyte-string opcode 135) [] 1)) :status) 'complete)))
  (dolist (opcode '(97 107 114 115)) (should-not (nelisp-native-funcall-v2-primitive opcode))))
(ert-deftest u4a/error-stops-later-effect-with-exact-data ()
  (let ((observed (native-buffer-u4a-observe (native-buffer-u4a-mutation-error) '("先" bad) 3 nil)))
    (should (equal (car observed) '(wrong-type-argument integer-or-marker-p bad)))
    (should (equal (cadr observed) "aé先中\n\tb")))
  (let ((observed (native-buffer-u4a-observe (native-buffer-u4a-range-error) '("先") 3 nil)))
    (should (equal (car observed) '(args-out-of-range "a" 0 9)))
    (should (equal (cadr observed) "aé先中\n\tb"))))
(provide 'nelisp-native-buffer-u4a-test)
