;;; p1c-test.el --- Private cache compilation redundancy controls -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'ert)
(require 'cl-lib)
(require 'bytecomp)
(require 'nelisp-native-cache)
(require 'nelisp-bytecode-native-rooted-cfg-native)
(require 'nelisp-aot-compiler)

(defun p1c-test--fixture (check)
  "Run CHECK with a real compiler and a private disposable cache directory."
  (let* ((directory (make-temp-file "p1c-host-" t))
         (file (expand-file-name "cache.nelr" directory))
         (function (byte-compile '(lambda (a b) (cons a b))))
         (nelisp-native-cache-backend 'in-house)
         (nelisp-native-cache-mode 'shared-v2)
         (nelisp-native-cache-guard-mode 'off)
         (native-comp-enable-subr-trampolines nil)
         (nelisp-bytecode-native-rooted-cfg-contract--validation-count 0)
         (nelisp-native-load--raw-v2-check-count 0)
         (nelisp-bytecode-native-rooted-cfg-native--registry nil))
    (unwind-protect
        (cl-letf (((symbol-function 'nelisp-native-cache-file) (lambda (_) file))
                  ((symbol-function 'nelisp-native-cache-abi-hash) (lambda () "host-abi"))
                  ((symbol-function 'nelisp-native-cache--input-hash) (lambda (_) "host-input"))
                  ((symbol-function 'nelisp-native-load-running-binary-sha256)
                   (lambda () (make-string 64 ?a)))
                  ((symbol-function 'nelisp-runtime-reload-contract-matches-p) (lambda () t))
                  ((symbol-function 'nelisp-native-cache--publish)
                   (lambda (temporary final) (rename-file temporary final))))
          (funcall check function file directory))
      (delete-directory directory t))))

(defun p1c-test--read (file)
  (with-temp-buffer
    (insert-file-contents file)
    (goto-char (point-min))
    (list (read (current-buffer)) (read (current-buffer)))))

(ert-deftest p1c/cache-validates-once-without-producer-structural-check ()
  (p1c-test--fixture
   (lambda (function file _directory)
     (cl-letf (((symbol-function 'nelisp-native-load--raw-v2-check-after-compile)
                (lambda (&rest _) (ert-fail "cache repeated producer structural check"))))
       (should (equal (nelisp-native-cache-compile function) file)))
     (should (= nelisp-bytecode-native-rooted-cfg-contract--validation-count 1))
     (should (= nelisp-native-load--raw-v2-check-count 0))
     (should-not nelisp-bytecode-native-rooted-cfg-native--registry))))

(ert-deftest p1c/cache-does-not-build-an-unused-admission-receipt ()
  (p1c-test--fixture
   (lambda (function file _directory)
     (cl-letf (((symbol-function 'nelisp-native-load--raw-v2-compile-file-with-validation)
                (lambda (&rest _) (ert-fail "cache constructed an unused admission receipt"))))
       (should (equal (nelisp-native-cache-compile function) file))))))

(ert-deftest p1c/cache-writes-and-publishes-only-the-final-cache ()
  (p1c-test--fixture
   (lambda (function file directory)
     (let ((writer (symbol-function 'write-region))
           (maker (symbol-function 'make-temp-file))
           (writes 0) (temps 0) (publications 0))
       (cl-letf (((symbol-function 'write-region)
                  (lambda (start end filename &rest options)
                    (should (string-prefix-p ".publish-" (file-name-nondirectory filename)))
                    (setq writes (1+ writes))
                    (apply writer start end filename options)))
                 ((symbol-function 'make-temp-file)
                  (lambda (prefix &rest options)
                    (should (string-prefix-p ".publish-" (file-name-nondirectory prefix)))
                    (setq temps (1+ temps))
                    (apply maker prefix options)))
                 ((symbol-function 'nelisp-native-cache--publish)
                  (lambda (temporary final)
                    (setq publications (1+ publications))
                    (rename-file temporary final))))
         (nelisp-native-cache-compile function))
       (should (= writes 1)) (should (= temps 1)) (should (= publications 1))
       (should (equal (directory-files directory nil "^[^.]" t) '("cache.nelr")))
       (should (eq (plist-get (car (p1c-test--read file)) :backend) 'in-house))))))

(ert-deftest p1c/snapshot-encoding-and-file-manifest-stay-identical ()
  (p1c-test--fixture
   (lambda (function file _directory)
     (let ((compiler (symbol-function 'nelisp-native-load-raw-v2-compile-file))
           (parser (symbol-function 'nelisp-native-load--raw-source-forms))
           (last-coding-system-used 'utf-16)
           captured)
       (cl-letf (((symbol-function 'nelisp-native-load-raw-v2-compile-file)
                  (lambda (&rest args)
                    (setq captured args)
                    (apply compiler args))))
         (nelisp-native-cache-compile function))
       (let* ((snapshot (nth 12 captured))
              (manifest (cadr (p1c-test--read file)))
              (source (car captured))
              (calls 0))
         (should (nth 13 captured))
         (should-not (file-exists-p source))
         (should (equal (plist-get manifest :source-sha256)
                        (nelisp-native-load--sha256 (cdr snapshot))))
         (let ((bytes (with-temp-buffer
                        (let ((print-length nil) (print-level nil))
                          (dolist (form (car snapshot)) (prin1 form (current-buffer)) (insert "\n")))
                        (encode-coding-string (buffer-string) 'utf-8-unix))))
           (should (equal bytes (cdr snapshot)))
           (let ((coding-system-for-write 'no-conversion))
             (write-region bytes nil source nil 'silent)))
         ;; Explicitly remove the snapshot, rather than depending on optional
         ;; argument order.  This control must actually parse the source file.
         (setf (nth 12 captured) nil (nth 13 captured) nil (nth 11 captured) nil)
         (cl-letf (((symbol-function 'nelisp-native-load--raw-source-forms)
                    (lambda (&rest args) (setq calls (1+ calls)) (apply parser args))))
           (should (equal manifest (apply compiler captured))))
         (should (= calls 1)))))))

(ert-deftest p1c/trusted-decoder-keeps-memory-safety-refusals ()
  (p1c-test--fixture
   (lambda (function file _directory)
     (nelisp-native-cache-compile function)
     (let* ((data (p1c-test--read file)) (header (car data)) (manifest (cadr data))
            (entry (plist-get header :entry)))
       (should (stringp (nelisp-native-load--raw-v2-trusted-decode manifest entry)))
       (dolist (mutate (list (lambda (m) (plist-put (plist-get m :native) :text-size 0))
                            (lambda (m) (plist-put (car (plist-get (plist-get m :native) :exports)) :value -1))
                            (lambda (m) (plist-put (car (plist-get m :gc-entries)) :index -1))))
         (let ((bad (copy-tree manifest)))
           (funcall mutate bad)
           (should-error (nelisp-native-load--raw-v2-trusted-decode bad entry))))))))

(ert-deftest p1c/trusted-decoder-authenticates-artifact-once-before-mapping ()
  (p1c-test--fixture
   (lambda (function file _directory)
     (nelisp-native-cache-compile function)
     (let* ((data (p1c-test--read file)) (manifest (cadr data))
            (entry (plist-get (car data) :entry))
            (hash (symbol-function 'nelisp-native-load--sha256)) (hashes 0)
            (checks nelisp-native-load--raw-v2-check-count))
       (cl-letf (((symbol-function 'nelisp-native-load--sha256)
                  (lambda (value) (setq hashes (1+ hashes)) (funcall hash value))))
         (should (stringp (nelisp-native-load--raw-v2-trusted-decode manifest entry))))
       (should (= hashes 1))
       (should (= checks nelisp-native-load--raw-v2-check-count))
       (dolist (limits '((1 nil) (nil 1) (1 1)))
         (let ((print-length (car limits)) (print-level (cadr limits)))
           (should (stringp (nelisp-native-load--raw-v2-trusted-decode manifest entry)))))
       (dolist (control '(body digest missing))
         (let* ((bad (copy-tree manifest)) (native (plist-get bad :native))
                (maps nelisp-native-load--trusted-map-count))
           (pcase control
             ('body
              (let ((bytes (base64-decode-string (plist-get native :text-base64))))
                (aset bytes 0 (logxor (aref bytes 0) 1))
                (plist-put native :text-base64 (base64-encode-string bytes t))))
             ('digest (plist-put bad :artifact-sha256 (make-string 64 ?0)))
             ('missing (plist-put bad :artifact-sha256 nil)))
           (should-error (nelisp-native-load-raw-v2-artifact-trusted bad entry "u10-control"))
           (should (= maps nelisp-native-load--trusted-map-count))))))))

(ert-deftest p1c/failed-validation-does-not-publish-and-hit-does-not-recompile ()
  (p1c-test--fixture
   (lambda (function file directory)
     (let ((publications 0))
     (cl-letf (((symbol-function 'nelisp-bytecode-native-rooted-cfg-contract-valid-p)
                (lambda (&rest _) (ert-fail "unexpected replaced validator invocation")))
               ((symbol-function 'nelisp-native-cache--publish)
                (lambda (&rest _) (setq publications (1+ publications)))))
       (should-error (nelisp-native-cache-compile function)))
     (should (= publications 0)))
     (should-not (file-exists-p file))
     (should-not (directory-files directory nil "^[^.]" t))
     (nelisp-native-cache-compile function)
     (let ((before (with-temp-buffer (insert-file-contents-literally file) (buffer-string))))
       (cl-letf (((symbol-function 'nelisp-bytecode-native-rooted-cfg-native--build)
                  (lambda (&rest _) (ert-fail "cache hit recompiled"))))
         (should (equal (nelisp-native-cache-compile function) file)))
       (should (equal before (with-temp-buffer (insert-file-contents-literally file) (buffer-string))))))))

(ert-deftest p1c/public-build-still-checks-publishes-and-seals ()
  (p1c-test--fixture
   (lambda (function _file directory)
     (let* ((artifact (expand-file-name "public.nelr" directory))
            (input (nelisp-bytecode-compiler-input-build function))
            (result (nelisp-bytecode-native-rooted-cfg-native-build-shared-v2 input artifact 'off)))
       (should (= nelisp-native-load--raw-v2-check-count 1))
       (should (= nelisp-bytecode-native-rooted-cfg-contract--validation-count 1))
       (should (equal (nelisp-native-load-manifest artifact) (plist-get result :manifest)))
       (should (nelisp-bytecode-native-rooted-cfg-native-authenticated-result-p result))))))

(ert-deftest p1c/rewrite-loads-its-module-without-loading-the-build-driver ()
  (p1c-test--fixture
   (lambda (_function _file directory)
     (require 'nelisp-standalone-arena-rewrite)
     (let ((original (symbol-function 'nelisp-standalone--chunk-arena-rewrite))
           (require-function (symbol-function 'require))
           (features (remq 'nelisp-standalone-arena-rewrite features))
           (source (expand-file-name "runtime.el" directory))
           (calls 0))
       (with-temp-file source
         (dolist (entry (nelisp-native-load-raw-v2-contract))
           (prin1 (list 'defun (intern (car entry))
                        (cl-loop for index below (cdr entry)
                                 collect (intern (format "arg%d" index))) 0)
                  (current-buffer))
           (insert "\n")))
       (unwind-protect
           (progn
             (fmakunbound 'nelisp-standalone--chunk-arena-rewrite)
             (cl-letf (((symbol-function 'require)
                        (lambda (feature &rest args)
                          (when (eq feature 'nelisp-standalone-build)
                            (ert-fail "compiler loaded the entire build driver"))
                          (when (eq feature 'nelisp-standalone-arena-rewrite)
                            (setq calls (1+ calls)))
                          (apply require-function feature args)))
                       ((symbol-function 'nelisp-aot-compile-to-link-unit)
                        (lambda (&rest _) (throw 'p1c-ready 'prepared))))
               (should (eq (catch 'p1c-ready
                             (nelisp-native-load-raw-v2-compile-file
                              source (expand-file-name "runtime.nelr" directory)
                              "host" (make-string 64 ?a)))
                           'prepared)))
             (should (= calls 1)))
         (fset 'nelisp-standalone--chunk-arena-rewrite original))))))

(ert-deftest p1c/compiler-hash-excludes-driver-and-keeps-arena-source ()
  (let ((locator (symbol-function 'locate-library))
        (reader (symbol-function 'insert-file-contents-literally))
        (native-comp-enable-subr-trampolines nil)
        (nelisp-native-cache--compiler-revision :unset)
        seen)
    (cl-letf (((symbol-function 'locate-library)
               (lambda (name &rest args)
                 (when (equal name "nelisp-standalone-build.el")
                   (ert-fail "cache hashed the unused build driver"))
                 (push name seen)
                 (apply locator name args))))
      (let ((before (nelisp-native-cache-compiler-revision-hash)))
        (should (stringp before))
        (should (member "nelisp-standalone-arena-rewrite.el" seen))
        (setq nelisp-native-cache--compiler-revision :unset)
        (cl-letf (((symbol-function 'insert-file-contents-literally)
                   (lambda (file &rest args)
                     (prog1 (apply reader file args)
                       (when (equal (file-name-nondirectory file)
                                    "nelisp-standalone-arena-rewrite.el")
                         (goto-char (point-max))
                         (insert "\n;; source identity mutation\n"))))))
          (should-not (equal before (nelisp-native-cache-compiler-revision-hash))))))))

(ert-deftest p1c/cache-only-requires-a-source-snapshot-and-exclusive-cfg-spec ()
  (dolist (snapshot '(nil t (nil . 1)))
    (should-error (nelisp-native-load-raw-v2-compile-file
                   "missing.el" "unit.nelr" nil nil nil nil nil nil nil
                   '(:contract t) nil nil snapshot t)))
  (should-error (nelisp-native-load-raw-v2-compile-file
                 "missing.el" "unit.nelr" nil nil t nil nil nil nil
                 '(:contract t) nil nil '((nil) . "source") t)))

(defun p1c-test--compile-without-driver ()
  "Check both producers with the build driver absent from the library path."
  (p1c-test--fixture
   (lambda (function _file directory)
     (let ((load-path (cl-remove-if
                      (lambda (path) (equal (file-name-nondirectory
                                            (directory-file-name path)) "scripts"))
                      load-path)))
       (should-not (featurep 'nelisp-standalone-build))
       (should-not (locate-library "nelisp-standalone-build"))
         (should (eq (plist-get (nelisp-bytecode-native-rooted-cfg-native-build-shared-v2
                                (nelisp-bytecode-compiler-input-build function)
                                (expand-file-name "public.nelr" directory) 'off)
                               :status) 'complete))
         (should (file-exists-p (nelisp-native-cache-compile function)))
       (should-not (featurep 'nelisp-standalone-build)))))
  (princ "P1C-DRIVER-ABSENT-PASS\n"))

(ert-deftest p1c/public-and-cache-compile-without-the-build-driver ()
  ;; Other test files may deliberately load the driver.  Use a fresh host in
  ;; that case rather than treating their setup as a compiler regression.
  (if (not (featurep 'nelisp-standalone-build))
      (p1c-test--compile-without-driver)
    (let* ((source (symbol-file 'p1c-test--fixture 'defun))
           (root (file-name-directory (directory-file-name (file-name-directory source)))))
      (with-temp-buffer
        (should (= 0 (call-process
                      (expand-file-name invocation-name invocation-directory)
                      nil t nil "-Q" "--batch"
                      "-L" (expand-file-name "lisp" root)
                      "-L" (expand-file-name "src" root)
                      "-L" (expand-file-name "test" root)
                      "-L" (expand-file-name "packages/nl-ffi/src" root)
                      "-l" source "-f" "p1c-test--compile-without-driver")))
        (should (string-match-p "P1C-DRIVER-ABSENT-PASS" (buffer-string)))))))

(ert-deftest p1c/stage-tracing-does-not-expand-compiler-bodies ()
  (let ((macro (cdr (symbol-function 'cl-labels)))
        (stage-expansions 0))
    (dolist (name '(nelisp-bytecode-native-rooted-cfg-native--build
                   nelisp-native-load-raw-v2-compile-file))
      (let (definition)
        (letrec ((find-definition
                  (lambda (form)
                    (when (consp form)
                      (if (and (eq (car form) 'defun) (eq (cadr form) name))
                          (setq definition form)
                        (funcall find-definition (car form))
                        (funcall find-definition (cdr form)))))))
          (with-temp-buffer
            (insert-file-contents (symbol-file name 'defun))
            (goto-char (point-min))
            (condition-case nil
                (while (not definition) (funcall find-definition (read (current-buffer))))
              (end-of-file nil))))
        (should definition)
        (cl-letf (((symbol-function 'cl-labels)
                   (cons 'macro
                         (lambda (bindings &rest body)
                           (when (assq 'stage bindings)
                             (setq stage-expansions (1+ stage-expansions)))
                           (apply macro bindings body)))))
          (macroexpand-all definition))))
    (should (= stage-expansions 0))))

(ert-deftest p1c/cache-keeps-the-aot-contract-mutation-check ()
  (p1c-test--fixture
   (lambda (function file _directory)
     (let ((compiler (symbol-function 'nelisp-native-load-raw-v2-compile-file))
           (aot (symbol-function 'nelisp-aot-compile-to-link-unit))
           contract)
       (cl-letf (((symbol-function 'nelisp-native-load-raw-v2-compile-file)
                  (lambda (&rest args)
                    (setq contract (plist-get (nth 9 args) :contract))
                    (apply compiler args)))
                 ((symbol-function 'nelisp-aot-compile-to-link-unit)
                  (lambda (&rest args)
                    (prog1 (apply aot args)
                      (plist-put contract :status-base 513)))))
         (should-error (nelisp-native-cache-compile function)))
       (should-not (file-exists-p file))
       (should (= nelisp-bytecode-native-rooted-cfg-contract--validation-count 2))))))

(provide 'p1c-test)
