;;; p2-fixed-test.el --- Fixed-cost trust controls -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'ert)
(require 'nelisp-native-cache)

(ert-deftest p2-fixed/prebuilt-manifest-preserves-authenticated-bytes ()
  (dolist (value (list "plain" "quote\" and slash\\" "line\nnext" "日本語"
                      (unibyte-string 0 127 128 255)))
    (let* ((manifest (list :format 'example :native (list :text-base64 "YWJj")
                           :metadata (vector value '(quote example))))
           (unsigned (prin1-to-string manifest))
           (digest (secure-hash 'sha256 unsigned))
           (signed (append manifest (list :artifact-sha256 digest)))
           (wire (nelisp-native-load--signed-manifest unsigned digest))
           (snapshot (concat "(:header t)\n" wire "\n"))
           (first (read-from-string snapshot))
           (second (read-from-string snapshot (cdr first))))
      (should (equal wire (prin1-to-string signed)))
      (should (equal signed (car second)))
      (should (equal unsigned
                     (nelisp-native-cache--unsigned-snapshot
                      snapshot (cdr first) (cdr second) (car second)))))))

(ert-deftest p2-fixed/snapshot-mutation-keeps-a-stale-digest ()
  (let* ((manifest '(:native (:text-base64 "YWJj")))
         (unsigned (prin1-to-string manifest))
         (digest (secure-hash 'sha256 unsigned))
         (wire (nelisp-native-load--signed-manifest unsigned digest))
         (position (string-search "YWJj" wire)))
    (aset wire position ?Z)
    (let* ((read (read-from-string wire))
           (actual (nelisp-native-cache--unsigned-snapshot wire 0 (cdr read) (car read))))
      (should actual)
      (should-not (equal (secure-hash 'sha256 actual) digest)))))

(ert-deftest p2-fixed/build-identities-skip-source-and-component-hashes ()
  (let* ((revision (make-string 64 ?b))
         (nelisp-native-cache--build-source-identity revision)
         (nelisp-native-cache--build-identities
          (list "abi" revision "in-house-identity" "gccjit-identity"))
         (nelisp-native-cache--compiler-revision :unset)
         (nelisp-native-cache--cold-source-check nil)
         (nelisp-native-cache--abi :unset)
         (nelisp-native-cache--addresses nil)
         (nelisp-native-cache--disabled-reason nil)
         (nelisp-native-cache-backend 'in-house)
         (addresses 0))
    (cl-letf (((symbol-function 'nelisp-native-load-root-v2-addresses)
               (lambda () (setq addresses (1+ addresses)) '(:environment 1)))
              ((symbol-function 'nelisp--native-pin-copy-v2) #'ignore)
              ((symbol-function 'nelisp-native-cache--abi-components)
               (lambda () (ert-fail "Per-process ABI rehash")))
              ((symbol-function 'locate-library)
               (lambda (&rest _) (ert-fail "Per-process source scan"))))
      (should (equal (nelisp-native-cache-abi-hash) "in-house-identity"))
      (setq nelisp-native-cache-backend 'gccjit)
      (should (equal (nelisp-native-cache-abi-hash) "gccjit-identity"))
      (should (= addresses 1))
      (let ((nelisp-native-cache--abi "changed-abi"))
        (should-not (equal (nelisp-native-cache-abi-hash) "gccjit-identity"))))))

(ert-deftest p2-fixed/build-identity-strings-remain-private ()
  (let* ((base (make-string 64 ?a)) (revision (make-string 64 ?r))
         (nelisp-native-cache--build-source-identity revision)
         (nelisp-native-cache--build-identities
          (list base revision (make-string 64 ?b) (make-string 64 ?c)))
         (nelisp-native-cache--compiler-revision :unset)
         (nelisp-native-cache--cold-source-check nil)
         (nelisp-native-cache--abi :unset)
         (nelisp-native-cache--addresses nil)
         (nelisp-native-cache-backend 'in-house))
    (cl-letf (((symbol-function 'nelisp-native-load-root-v2-addresses)
               (lambda () '(:environment 1)))
              ((symbol-function 'nelisp--native-pin-copy-v2) #'ignore))
      (let ((key (nelisp-native-cache-abi-hash)))
        (aset key 0 ?x)
        (should (equal (nelisp-native-cache-abi-hash) (make-string 64 ?b))))
      (aset nelisp-native-cache--abi 0 ?z)
      (should (equal base (make-string 64 ?a)))
      (should-not (equal (nelisp-native-cache-abi-hash) (make-string 64 ?b))))))
