;;; standalone-native-stackset-u5-driver.el --- Native stack transfer parity -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'nelisp-native-cache)
(load "test/support/native-entry-observer.el" nil t t)
(load "test/support/native-stackset-u5-fixtures.el" nil t t)
(defun u5-assert (value label) (unless value (error "U5: %s" label)))
(let* ((nelisp-native-cache-backend (if (equal (getenv "U5_BACKEND") "gccjit") 'gccjit 'in-house))
       (names (split-string (getenv "U5_CASES")))
       (entries 0) (cases 0) (compiles 0) (cold-bodies 0)
       (compile-function (symbol-function 'nelisp-native-cache-compile)))
  ;; Each body is compiled once; instrument the actual raw-v2 entry so an
  ;; interpreter fallback cannot satisfy value-only assertions.
  (dolist (name names)
    (let* ((fixture (assq (intern name) (native-stackset-u5-fixtures)))
           (fn (nth 1 fixture))
           (arity 2) (roots nil))
      (princ (format "U5-FIXTURE-START backend=%S fixture=%s\n" nelisp-native-cache-backend name))
      (u5-assert fixture "fixture exists")
      (let ((file (nelisp-native-cache-file fn)))
        (unless (and (file-exists-p file)
                     (or (eq nelisp-native-cache-backend 'in-house)
                         (file-exists-p (concat file ".nelh"))))
          (setq cold-bodies (1+ cold-bodies))))
      (cl-letf (((symbol-function 'nelisp-native-cache-compile)
                 (lambda (&rest args) (setq compiles (1+ compiles)) (apply compile-function args))))
        (nelisp-native-cache-install 'u5-native fn))
      (u5-assert (file-exists-p (nelisp-native-cache-file fn)) "native artifact exists")
      (let* ((file (nelisp-native-cache-file fn))
             (metadata (if (eq nelisp-native-cache-backend 'gccjit) (concat file ".nelh") file))
             (header (with-temp-buffer (insert-file-contents metadata) (goto-char (point-min)) (read (current-buffer)))))
        (setq roots (plist-get header :root-count))
        (u5-assert (= arity (plist-get header :arity)) "fixture arity"))
      (dolist (args (nth 2 fixture))
        (setq u5-remaining 3 u5-history nil)
        (let* ((expected (native-stackset-u5-reference fn args))
               (history (copy-sequence u5-history)) actual)
          ;; stack-set2 has no NeLisp VM provider in U2a. Its reference is
          ;; qualified against the identical bytecode in the GNU host suite.
          (unless (memq (car fixture) '(set2zero set2one set256 swap2))
            (setq u5-remaining 3 u5-history nil)
            (u5-assert (equal expected (apply fn args)) "direct NeLisp VM parity")
            (u5-assert (equal history u5-history) "VM ordered loop effects"))
          (setq u5-remaining 3 u5-history nil)
          (garbage-collect)
          (nelisp-test-with-native-entry-observer
	      (lambda (address env ticket argc count x y)
		(when (and (= argc arity) (= count roots) (= x 0) (= y 0))
		  (setq entries (1+ entries))))
	    (setq actual (apply #'u5-native args)))
          (u5-assert (equal expected actual) (format "%s interpreter=%S native=%S" name expected actual))
          (u5-assert (equal history u5-history) "native ordered loop effects")
          (if (memq (car fixture) '(swap swap2))
              (progn (u5-assert (eq (car actual) (cadr args)) "swapped Y identity")
                     (u5-assert (eq (cdr actual) (car args)) "swapped X identity")
                     (u5-assert (= u5-remaining 0) "three backedges"))
            (u5-assert (eq expected actual) "complete boxed identity")))
        (setq cases (1+ cases)))
      ;; A second load must be a cache hit, with no compilation or fallback.
      (cl-letf (((symbol-function 'nelisp-native-cache-compile)
                 (lambda (&rest _) (error "U5 warm load recompiled"))))
        (nelisp-native-cache-install 'u5-native fn))
      (princ (format "U5-FIXTURE-PASS backend=%S fixture=%s\n" nelisp-native-cache-backend name))))
  (u5-assert (= entries cases) "one native machine entry per case")
  (u5-assert (= compiles cold-bodies) "one compile per cache miss; no warm recompilation")
  (princ (format "U5-NATIVE-PASS backend=%S fixtures=%d cases=%d native-entries=%d compiles=%d cache-hits=%d\n"
                 nelisp-native-cache-backend (length names) cases entries compiles (- (length names) cold-bodies))))
