;;; standalone-native-cleanup-u7b-driver.el --- Native cleanup parity -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'nelisp-native-cache)
(load "test/support/native-entry-observer.el" nil t t)
(load "test/support/native-cleanup-u7b-fixtures.el" nil t t)
(defun u7b-assert (value label) (unless value (error "U7b: %s" label)))
(let ((nelisp-native-cache-backend (intern (getenv "U7B_BACKEND")))
      (phase (getenv "U7B_PHASE")) (cases 0) (entries 0))
  (dolist (name (split-string (getenv "U7B_CASES")))
    (let* ((kind (if (string-match-p "^[0-9]+$" name) (string-to-number name) (intern name)))
           (fn (native-cleanup-u7b-function kind)))
      (princ (format "U7B-START backend=%S fixture=%S phase=%s\n" nelisp-native-cache-backend kind phase))
      (if (equal phase "load")
          (cl-letf (((symbol-function 'nelisp-native-cache-compile)
                     (lambda (&rest _) (error "U7b warm recompiled"))))
            (nelisp-native-cache-install 'u7b-native fn))
        (nelisp-native-cache-install 'u7b-native fn))
      (let* ((native (symbol-function 'u7b-native))
             (file (nelisp-native-cache-file fn))
             (header (with-temp-buffer
                       (insert-file-contents (if (eq nelisp-native-cache-backend 'gccjit) (concat file ".nelh") file))
                       (goto-char (point-min)) (read (current-buffer))))
             (roots (plist-get header :root-count)))
        (cl-labels ((compare (mode)
                     (let* ((entry-before entries) (u7b-inner fn)
                            (expected (native-cleanup-u7b-observe fn kind mode))
                            (u7b-inner native)
                            (actual
                             (nelisp-test-with-native-entry-observer
				 (lambda (address env ticket argc count x y)
				   (when (and (= argc 0) (= count roots) (= x 0) (= y 0))
				     (setq entries (1+ entries))))
			       (native-cleanup-u7b-observe native kind mode))))
                       (u7b-assert (equal expected actual)
                                   (format "%S/%S expected=%S actual=%S" kind mode expected actual))
                       (u7b-assert (= (- entries entry-before) (if (eq mode 'reenter) 2 1))
                                   "one machine entry per invocation; no fallback")
                       (setq cases (1+ cases))
                       (princ (format "U7B-PARITY fixture=%S mode=%S case=%d\n" kind mode cases)))))
          (let* ((all (append '(normal body-error body-throw caller-normal caller-throw)
                              (when (memq kind '(97 114)) '(kill))
                              (when (memq kind '(ordered implicit))
                                '(cleanup-error cleanup-throw last-error last-throw reenter))))
                 (selected (if (getenv "U7B_MODES")
                               (mapcar #'intern (split-string (getenv "U7B_MODES"))) all)))
            (u7b-assert (and selected (= (length selected) (length (delete-dups (copy-sequence selected))))
                            (cl-every (lambda (mode) (memq mode all)) selected)) "mode selection")
            (dolist (mode selected)
              (cond ((eq mode 'normal) (compare nil))
                    ((memq mode '(caller-normal caller-throw))
                     (let ((u7b-special 'caller))
                       (compare (if (eq mode 'caller-normal) nil 'body-throw))
                       (u7b-assert (eq u7b-special 'caller) "caller watermark")))
                    (t (compare mode)))))
          (u7b-assert (eq u7b-special 'outside) "outside binding")
          ;; Measure a matched body without forced GC: each call's result
          ;; remains a boxed object rooted across the native cleanup bridge.
          (when (eq kind 'forms)
            (let ((restore (symbol-function 'garbage-collect)) (iterations 20) start before after)
              (unwind-protect
                  (progn
                    (fset 'garbage-collect (lambda () nil))
                    (setq start (float-time))
                    (dotimes (_ iterations) (funcall fn))
                    (setq before (/ (* 1e9 (- (float-time) start)) iterations) start (float-time))
                    (dotimes (_ iterations) (funcall native))
                    (setq after (/ (* 1e9 (- (float-time) start)) iterations))
                    (princ (format "U7B-TIMING iterations=%d interpreter-ns=%.0f native-ns=%.0f\n" iterations before after)))
                (fset 'garbage-collect restore))))))))
  (u7b-assert (>= entries cases) "actual machine entry per parity case")
  (princ (format "U7B-NATIVE-PASS backend=%S cases=%d native-entries=%d phase=%s\n"
                 nelisp-native-cache-backend cases entries phase)))
