;;; standalone-native-template-driver.el --- Cons trust and composition -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'nelisp-native-cache)
(require 'nelisp-bytecode-native-consumer)
(defun template-assert (value label) (unless value (error "Template assertion: %s" label)))
(let* ((nelisp-native-cache-backend (intern (or (getenv "TEMPLATE_BACKEND") "template")))
       (phase (getenv "TEMPLATE_PHASE"))
       (functions (nelisp-bytecode-native-consumer-read-elc-functions (getenv "TEMPLATE_FIXTURE")))
       (function (cdr (assq 'compiler-r3-cons functions)))
       (start (float-time)) (validations nelisp-native-template--validation-count)
       (maps nelisp-native-load--trusted-map-count)
       file compile-seconds native end-seconds)
  (template-assert function "genuine compiler-r3-cons input")
  (if (equal phase "compile")
      (progn
        (setq file (nelisp-native-cache-compile function) compile-seconds (- (float-time) start))
        (setq native (nelisp-native-cache-load function))
        (template-assert (equal (funcall native 40 2) '(40 . 2)) "exact first Cons call")
        (setq end-seconds (- (float-time) start))
        (when (and (eq system-type 'windows-nt) (eq nelisp-native-cache-backend 'template))
          (load (expand-file-name "test/support/windows-native-sentinel.el") nil t)
          (let ((entry (plist-get (car nelisp-native-load-raw-mappings) :codepage)))
            (windows-native-sentinel-with-entry
             entry (lambda () (template-assert (equal (funcall native 40 2) '(40 . 2))
                                               "Win64 template register sentinel"))))
          (princ "TEMPLATE-WIN64-REGISTER-SENTINEL-PASS GP=8 XMM=10\n"))
        (template-assert (= (if (eq nelisp-native-cache-backend 'gccjit) 0 1)
                            (- nelisp-native-load--trusted-map-count maps)) "selected mapper")
        (when (eq nelisp-native-cache-backend 'template)
          (template-assert (= 1 (- nelisp-native-template--validation-count validations)) "one compile validator")
          (template-assert (= 1 nelisp-native-template--compile-count) "template compiler entered")
          (template-assert (= (if (eq system-type 'windows-nt) 2 1) nelisp-native-template--entry-count) "machine entry")
          (template-assert (= 0 nelisp-native-template--fallback-count) "no fallback"))
        (princ (format "TEMPLATE-TIMING compile=%.9f end-to-end=%.9f\n" compile-seconds end-seconds)))
    (setq native (nelisp-native-cache-load function))
    (let ((first-page (plist-get (car nelisp-native-load-raw-mappings) :codepage)))
    (let ((second (nelisp-native-cache-load function)))
      (unless (eq nelisp-native-cache-backend 'gccjit)
        (template-assert (/= first-page (plist-get (car nelisp-native-load-raw-mappings) :codepage)) "distinct code mappings"))
      (dotimes (i 1000)
        (template-assert (equal (funcall native i (* i 10)) (cons i (* i 10))) "first mapping")
        (template-assert (equal (funcall second i (* i 10)) (cons i (* i 10))) "independent mapping"))))
    (template-assert (= (if (eq nelisp-native-cache-backend 'gccjit) 0 2)
                        (- nelisp-native-load--trusted-map-count maps)) "selected fresh mappings")
    (template-assert (= validations nelisp-native-template--validation-count) "zero load validation")
    ;; Typed patches compose with live constant initializers, independently of
    ;; immutable machine text or address layout. Both callables see mutation.
    (when (eq nelisp-native-cache-backend 'template)
      (let* ((constant (cdr (assq 'template-constant functions)))
             (_file (nelisp-native-cache-compile constant))
             (first (nelisp-native-cache-load constant))
             (second (nelisp-native-cache-load constant))
             (vector (vector 'shared)))
        (template-assert (equal (funcall first 'tail) '(tag . tail)) "constant stencil")
        (aset (aref constant 2) 0 vector)
        (garbage-collect)
        (template-assert (eq (car (funcall first nil)) vector) "live constant alias first")
        (template-assert (eq (car (funcall second nil)) vector) "live constant alias second")
        (aset vector 0 'changed)
        (template-assert (eq (aref (car (funcall second nil)) 0) 'changed) "constant mutation")
        ;; Checked path must retain complete provenance, never accept changed
        ;; machine text merely because the producer copied a proof object.
        (let* ((file _file)
               (snapshot (with-temp-buffer (insert-file-contents file) (buffer-string)))
               (first-record (read-from-string snapshot))
               (header (car first-record))
               (manifest (car (read-from-string snapshot (cdr first-record))))
               (before nelisp-native-template--validation-count)
               (handle (nelisp-native-load-raw-v2-artifact manifest (plist-get header :entry)
                                                         (nelisp-native-load-running-binary-sha256) file)))
          (nelisp-native-load-unload handle)
          (template-assert (> nelisp-native-template--validation-count before) "checked proof validator")
          (let* ((broken (copy-tree manifest)) (section (plist-get broken :native))
                 (bytes (base64-decode-string (plist-get section :text-base64))))
            (aset bytes 0 (logxor 1 (aref bytes 0)))
            (setf (plist-get section :text-base64) (base64-encode-string bytes t))
            (template-assert (nelisp-native-load-raw-v2-check broken (plist-get header :entry)) "checked corruption refused"))))))
  (princ (format "TEMPLATE-TRUST-PASS backend=%S phase=%s compiles=%d entries=%d fallback=%d\n"
                 nelisp-native-cache-backend phase nelisp-native-template--compile-count
                 nelisp-native-template--entry-count nelisp-native-template--fallback-count)))
