;;; standalone-bytecode-native-funcall-driver.el --- F1 cache corpus -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'nelisp-native-cache)
(require 'nelisp-bytecode-native-consumer)
(defun f1-user (x)
  (when (equal (getenv "F1_FORCE_GC") "1") (garbage-collect))
  x)
(defun f1-assert (value label) (unless value (error "F1 assertion: %s" label)))
(defun f1-check-runtime-gc-table (function)
  "Check both raw mappers against the linked GC addresses across collection."
  (when (memq nelisp-native-cache-backend '(in-house template))
    (let* ((file (nelisp-native-cache-file function)) header manifest)
      (with-temp-buffer
        (insert-file-contents file)
        (goto-char (point-min))
        (setq header (read (current-buffer)) manifest (read (current-buffer))))
      (dolist (mapper '(checked trusted))
        (let* ((before nelisp-bytecode-native-rooted-cfg-contract--validation-count)
               (start (float-time))
               (handle
               (if (eq mapper 'checked)
                   (nelisp-native-load-raw-v2-artifact
                    manifest (plist-get header :entry)
                    (nelisp-native-load-running-binary-sha256) file)
                 (nelisp-native-load-raw-v2-artifact-trusted
                  manifest (plist-get header :entry) file))))
          (unwind-protect
              (progn
                (f1-assert (= (length (plist-get handle :exports)) 1) "one user export")
                (garbage-collect)
                (dolist (entry (plist-get manifest :gc-entries))
                  (f1-assert
                   (= (ptr-read-u64 (plist-get handle :gc-table)
                                    (+ 16 (* 8 (plist-get entry :index))))
                      (nelisp-native-load--symbol-addr (plist-get entry :name)))
                   "GC table uses runtime addresses after collection")))
            (nelisp-native-load-unload handle))
          (let ((validations (- nelisp-bytecode-native-rooted-cfg-contract--validation-count before)))
            (f1-assert (= validations (if (eq mapper 'checked) 1 0))
                       "checked GC control validates once; trusted control never validates")
            (princ (format "F1-GC-MAPPER-PASS mapper=%S seconds=%.3f validations=%d\n"
                           mapper (- (float-time) start) validations))))))))
(let* ((function (cdr (assq 'f1-fixture (nelisp-bytecode-native-consumer-read-elc-functions (getenv "F1_FIXTURE")))))
       (phase (getenv "F1_PHASE"))
       (nelisp-native-cache-backend (intern (or (getenv "F1_BACKEND") "in-house"))))
  (f1-assert function "genuine GNU fixture")
  (unless (memq nelisp-native-cache-backend '(in-house gccjit template)) (error "Unknown backend"))
  (if (equal phase "compile")
      (let* ((start (float-time)) (before nelisp-bytecode-native-rooted-cfg-contract--validation-count)
             (file (nelisp-native-cache-install 'f1-native function)))
        (f1-assert (functionp (symbol-function 'f1-native)) "installed callable")
        (f1-assert (equal (f1-native '(1 . 2)) '(1 . 2)) "first native call")
        (princ (format "F1-COMPILE-PASS backend=%S seconds=%.3f validations=%d file=%S\n"
                       nelisp-native-cache-backend (- (float-time) start)
                       (- nelisp-bytecode-native-rooted-cfg-contract--validation-count before)
                       (nelisp-native-cache-file function))))
    (let* ((before nelisp-bytecode-native-rooted-cfg-contract--validation-count)
           (start (float-time))
           (native (nelisp-native-cache-load function))
           (shared (vector 11))
           (tail (list 'tail shared))
           (corpus (list nil '(1 2 3) '(a . b) (cons shared tail) (cons shared shared)))
           (count 0) (observations nil))
      (f1-assert native "fresh-process cache hit")
      (let* ((file (nelisp-native-cache-file function))
             (names (with-temp-buffer
                      (insert-file-contents (if (eq nelisp-native-cache-backend 'gccjit) (concat file ".nelh") file))
                      (goto-char (point-min))
                      (let ((header (read (current-buffer))))
                        (if (eq nelisp-native-cache-backend 'gccjit) (plist-get header :imports)
                          (mapcar #'nelisp-native-load--raw-import-name
                                  (plist-get (plist-get (read (current-buffer)) :native) :imports)))))))
        (f1-assert
         (equal (sort (copy-sequence names) #'string<)
                (if (eq nelisp-native-cache-backend 'template)
                    '("nl_native_funcall_v2" "nl_native_poll_v2" "nl_root_pin_slot_v2")
                  '("nl_native_funcall_v2" "nl_root_pin_slot_v2")))
         "one generic evaluator import plus template poll gate"))
      (f1-assert (= before nelisp-bytecode-native-rooted-cfg-contract--validation-count) "zero cache validations")
      (dolist (input corpus)
        (when (equal (getenv "F1_FORCE_GC") "1") (garbage-collect))
        (let ((expected (funcall function input)) (actual (funcall native input)))
          (when (equal (getenv "F1_FORCE_GC") "1") (garbage-collect))
          (f1-assert (equal expected actual) "native/interpreter equality")
          (f1-assert (eq (car actual) (car expected)) "car identity")
          (f1-assert (eq (cdr actual) (cdr expected)) "cdr identity")
          (push (format "%S" actual) observations)
          (setq count (1+ count))))
      (when (and (member phase '("load" "measure"))
                 (not (equal (getenv "F1_FORCE_GC") "1")))
        (let ((rounds 5) (calls 0) (vm-start (float-time)) vm-seconds native-start)
          (dotimes (_ rounds)
            (dolist (input corpus) (funcall function input) (setq calls (1+ calls))))
          (setq vm-seconds (- (float-time) vm-start) native-start (float-time))
          (dotimes (_ rounds) (dolist (input corpus) (funcall native input)))
          (princ (format "F1-CENSUS calls=%d operations-per-call=4 interpreter-ns=%.0f native-ns=%.0f\n"
                         calls (/ (* vm-seconds 1000000000) calls)
                         (/ (* (- (float-time) native-start) 1000000000) calls)))))
      (let ((result (funcall native (cons shared shared))))
        (aset shared 0 19)
        (f1-assert (= (aref (car result) 0) 19) "mutation through alias")
        (f1-assert (eq (car result) (cdr result)) "repeated aliases")
        (push (format "%S" (list (aref (car result) 0) (eq (car result) (cdr result)))) observations))
      (fset 'f1-user (lambda (x) (cons 'redefined x)))
      (f1-assert (equal (funcall native '(7 . 8)) '(redefined 7 . 8)) "function redefinition")
      (push (format "%S" (funcall native '(7 . 8))) observations)
      (princ (format "F1-CORPUS-DIGEST=%s\n" (secure-hash 'sha256 (prin1-to-string (nreverse observations)))))
      ;; Include every cache/corpus operation, but not the independent checked
      ;; mapper below: that positive control deliberately revalidates semantics.
      (f1-assert (= before nelisp-bytecode-native-rooted-cfg-contract--validation-count)
                 "zero cache validations after corpus")
      (princ (format "F1-CACHE-PASS backend=%S corpus=%d seconds=%.3f validations=%d\n"
                     nelisp-native-cache-backend count (- (float-time) start)
                     (- nelisp-bytecode-native-rooted-cfg-contract--validation-count before)))
      (when (equal (getenv "F1_FORCE_GC") "1")
        (f1-check-runtime-gc-table function)
        (princ (format "F1-FORCED-GC-PASS backend=%S\n" nelisp-native-cache-backend))))))
(when (equal (getenv "F1_BACKEND") "template")
  (f1-assert (> nelisp-native-template--entry-count 0) "template native entry")
  (f1-assert (= nelisp-native-template--fallback-count 0) "no template fallback")
  (f1-assert (= nelisp-native-template--compile-count (if (equal (getenv "F1_PHASE") "compile") 1 0)) "actual template compiler")
  (princ (format "F1-TEMPLATE-COUNTERS compiles=%d entries=%d fallback=%d\n"
                 nelisp-native-template--compile-count nelisp-native-template--entry-count nelisp-native-template--fallback-count)))
