;;; standalone-native-funcall-v2-exits-driver.el --- F1 exit/GC corpus -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'nelisp-native-cache)
(require 'nelisp-bytecode-native-consumer)
(defvar f1b-binding 'outside)
(defvar f1b-cleanups 0)
(defun f1b-tick () nil)
(put 'f1b-signal 'error-conditions '(f1b-signal error))
(defun f1b-assert (value label) (unless value (error "F1B: %s" label)))
(defun f1b-observe (thunk)
  (condition-case err (list 'value (funcall thunk))
    (error (list 'condition err))))
(defun f1b-arity (a b) (list a b))
(defun f1b-redefined (x) x)
(defvar f1b-control nil)
(defun f1b-import-controls (function)
  (let* ((input (nelisp-bytecode-compiler-input-build function))
         (plan (nelisp-bytecode-native-rooted-cfg-plan input))
         (emitted (nelisp-bytecode-native-rooted-cfg-shared-emit-build
                   plan nelisp-bytecode-native-rooted-cfg-contract-shared-entry))
         (contract (nelisp-bytecode-native-rooted-cfg-contract-create-shared-v2 input plan emitted))
         (imports (mapcar (lambda (name)
                            (list :name name :kind 'func :abi (nelisp-native-load--runtime-abi-v2)
                                  :address-mode (if (equal name "nl_root_pin_slot_v2")
                                                    'conditional-root-slot-v1 'native-bridgeable-v1)
                                  :index (cl-position name nelisp-native-load-bridgeable-symbols :test #'equal)
                                  :arity 6 :params '(u64 u64 u64 u64 u64 u64) :return 'u64))
                          (plist-get contract :imports)))
         (manifest (list :native-rooted-cfg-contract-version (plist-get contract :version)
                         :native-rooted-cfg-contract contract :native-rooted-cfg-import-descriptors imports
                         :native (list :imports imports :exports
                                       (list (list :name (plist-get contract :entry) :type 'func
                                                   :abi (nelisp-native-load--runtime-abi-v2)
                                                   :arity 4 :params '(u64 u64 u64 u64) :return 'u64))))))
    (f1b-assert (nelisp-native-load--raw-v2-rooted-cfg-contract-valid-slow-p manifest) "genuine typed manifest")
    (dolist (pair (list (cons :index (1- (cl-position "nl_native_funcall_v2"
                                                     nelisp-native-load-bridgeable-symbols :test #'equal)))
                       (cons :arity 5) (cons :abi "wrong-ABI")))
      (let ((bad (copy-tree manifest)))
        ;; Mutate both parallel records so mere inequality cannot be the oracle.
        (dolist (records (list (plist-get bad :native-rooted-cfg-import-descriptors)
                               (plist-get (plist-get bad :native) :imports)))
          (dolist (entry records)
            (when (equal (plist-get entry :name) "nl_native_funcall_v2")
              (plist-put entry (car pair) (cdr pair)))))
        (f1b-assert (not (nelisp-native-load--raw-v2-rooted-cfg-contract-valid-slow-p bad))
                    "bridge index/six-word ABI mutation refused")))
    (princ "F1B-IMPORT-CONTROLS-PASS index arity ABI\n")))
(defun f1b-root-state ()
  ;; Pin control is restored by the public cache wrapper, independently of
  ;; any Lisp success/error normalization. Ignore the monotonic ticket nonce.
  (mapcar (lambda (offset) (ptr-read-u64 f1b-control offset)) '(0 8 16 24 48)))
(let* ((fixtures (nelisp-bytecode-native-consumer-read-elc-functions (getenv "F1B_FIXTURE")))
       (functions (mapcar (lambda (name) (cdr (assq name fixtures))) '(f1b-one f1b-zero f1b-six)))
       (compile-unit (getenv "F1B_COMPILE_UNIT"))
       (nelisp-native-cache-backend (intern (or (getenv "F1B_BACKEND") "in-house"))))
  (f1b-assert (not (memq nil functions)) "GNU bytecode fixtures")
  (when compile-unit
    (f1b-assert (and (equal (getenv "F1B_PHASE") "compile")
                     (member compile-unit '("f1b-one" "f1b-zero" "f1b-six"))) "compile selection")
    (setq functions (list (nth (cl-position (intern compile-unit) '(f1b-one f1b-zero f1b-six)) functions))))
  (dolist (function functions)
    (let ((plan (nelisp-bytecode-native-rooted-cfg-plan (nelisp-bytecode-compiler-input-build function))))
      (f1b-assert (plist-get plan :funcall-version) "generic F1 plan, including unary corpus")
      (f1b-assert (equal (plist-get plan :gateway-imports) '("nl_native_funcall_v2"))
                  "one generic bridge on every fixture")))
  (if (equal (getenv "F1B_PHASE") "compile")
      (progn
        (dolist (function functions) (nelisp-native-cache-compile function))
        (princ (format "F1B-COMPILE-PASS units=%d unit=%s\n" (length functions) (or compile-unit "all"))))
    (load "test/standalone-native-funcall-v2-controls-driver.el" nil t)
    (load "test/standalone-native-funcall-v2-domain-driver.el" nil t)
    (setq f1b-control (plist-get (gethash "nl_root_pin_control"
                                        (plist-get (nelisp-native-compiler-f1-runtime-proof--verify) :symbols)) :address))
    (let* ((native (mapcar #'nelisp-native-cache-load functions))
           (one (nth 0 native)) (zero (nth 1 native)) (six (nth 2 native))
           (state (list (vector 'mutable))) (observations nil)
           (baseline (f1b-root-state)))
      (f1b-assert (not (memq nil native)) "fresh-process native cache hits")
      (f1b-assert (nelisp-native-load-compiler-f1-runtime-p) "genuine F1 import table")
      (f1b-import-controls (car functions))
      (let* ((file (nelisp-native-cache-file (car functions)))
             (sidecar (if (eq nelisp-native-cache-backend 'gccjit) (concat file ".nelh") file))
             (original (with-temp-buffer (insert-file-contents sidecar) (buffer-string)))
             (first (read-from-string original)) (header (car first)))
        (unwind-protect
            (progn
              (plist-put header :abi (make-string 64 ?0))
              (write-region (concat (prin1-to-string header) (substring original (cdr first))) nil sidecar nil 'silent)
              (f1b-assert (equal (condition-case err (progn (nelisp-native-cache-load (car functions)) nil)
                                  (error (cadr err))) "Native cache header identity or structure mismatch")
                          "ABI mutation refused"))
          (write-region original nil sidecar nil 'silent)))
      (f1b-assert (eq (funcall zero (lambda () state)) state) "N=0 closure root")
      (push '(zero identity) observations)
      (f1b-assert (funcall six (lambda (&rest args) (cl-every (lambda (x) (eq x state)) args)) state)
                  "N>5 argument aliases")
      (push '(six aliases) observations)
      (f1b-assert (eq (funcall one 'f1b-redefined state) state) "symbol root")
      (fset 'f1b-redefined (lambda (_) 'redefined))
      (f1b-assert (eq (funcall one 'f1b-redefined state) 'redefined) "redefinition")
      (push 'redefined observations)
      (let ((gc-callee (lambda (x)
                         (garbage-collect)
                         (aset (car x) 0 'collected)
                         x)))
        (f1b-assert (eq (funcall one gc-callee state) state) "callee GC preserves argument/result")
        (f1b-assert (eq (aref (car state) 0) 'collected) "callee GC mutation"))
      (push '(gc identity mutation) observations)
      (f1b-assert
       (eq (funcall one (lambda (x) (funcall one (lambda (y) (garbage-collect) y) x)) state) state)
       "native Lisp native GC nesting")
      (push '(nested gc identity) observations)
      ;; Two consecutive failures then a success, repeated in one process.
      ;; Each callee owns a dynamic binding and unwind-protect cleanup.
      (dotimes (_ 2)
        (dolist (target (list (lambda (_) (signal 'f1b-signal (list state)))
                             (lambda (x) (car 17)) 'f1b-arity 'f1b-void))
          (let* ((callee (lambda (x)
                           (let ((f1b-binding 'inside))
                             (unwind-protect (funcall target x)
                               (setq f1b-cleanups (1+ f1b-cleanups))))))
                 (expected (f1b-observe (lambda () (funcall (car functions) callee state))))
                 (actual (f1b-observe (lambda () (funcall one callee state)))))
            (f1b-assert (equal expected actual) "callee condition parity")
            (f1b-assert (equal actual (f1b-observe (lambda () (funcall one callee state))))
                        "successive failures")
            (f1b-assert (eq f1b-binding 'outside) "binding restored")
            (f1b-assert (eq (funcall one #'identity state) state) "success after error")
            (f1b-assert (equal baseline (f1b-root-state)) "pin cleanup after error/success")
            ;; Compare full data above; freeze only stable condition names.
            (push (list 'condition (car (cadr actual))) observations))))
      (f1b-assert (= f1b-cleanups 24) "exactly one cleanup per callee")
      (let (caught)
        (condition-case err
            (funcall one (lambda (x) (signal 'f1b-signal (list x))) state)
          (f1b-signal (setq caught t)
                      (f1b-assert (eq (cadr err) state) "signal payload identity")))
        (f1b-assert caught "signal handler reached"))
      (let* ((tag (list 'unique-tag))
             (callee (lambda (x) (garbage-collect) (throw tag x)))
             (actual (catch tag (funcall one callee state))))
        (f1b-assert (eq actual state) "throw tag/value identity through native exit")
        (f1b-assert (eq (funcall one #'identity state) state) "success after throw")
        (f1b-assert (equal baseline (f1b-root-state)) "pin cleanup after throw")
        (push '(throw identity) observations))
      (princ (format "F1B-CORPUS-DIGEST=%s\n"
                     (secure-hash 'sha256 (prin1-to-string (nreverse observations)))))
      (princ (format "F1B-LOAD-PASS backend=%S cleanup=%d\n" nelisp-native-cache-backend f1b-cleanups)))))
