;;; standalone-native-entry-observer-driver.el --- Recorder controls -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'nelisp-native-cache)
(let* ((constructor (symbol-function 'nelisp--native-subr-create))
       (page (nelisp-native-load-map-anonymous 4096 nil))
       ;; Lisp reference: (lambda (_argument) 42). Return initialized root 0.
       (descriptor (vector page 1 1 1 2 (vector (vector 0 0 42)) nil -1 nil)))
  (nelisp-native-load--poke-string page 0 (unibyte-string #xb8 0 2 0 0 #xc3))
  (nelisp-native-load--poke-string page 16 (unibyte-string #xb8 1 2 0 0 #xc3))
  (nelisp-native-load--mprotect-rx page 4096)
  (let ((plain (funcall constructor descriptor 'observer-plain 0 t)))
    (load "test/support/native-entry-observer.el" nil t t)
    (let* ((native (nelisp--native-subr-create descriptor 'observer-native 0 t))
           (events nil) (before (nelisp-test-native-entry-snapshot)))
      (unless (= (funcall native 'live) 42) (error "Observer changed return value"))
      (setq events (nelisp-test-native-entry-events before))
      (unless (and (= (length events) 1)
                   (= (caar events) page) (> (nth 1 (car events)) 0)
                   (> (nth 2 (car events)) 0)
                   (equal (nthcdr 3 (car events)) '(1 2 0 0)))
        (error "Observer ABI or exact count failed"))
      (princ "ENTRY-OBSERVER-PASS native=1 ABI=1 value=42\n")
      (let* ((nelisp-test-native-entry-gc-once t)
             (gc-descriptor (vector (+ page 16) 1 1 1 2 [] nil -1 nil))
             (gc-native (nelisp--native-subr-create gc-descriptor 'observer-gc 0 t))
             (payload (vector 'live (cons 'nested 'identity))))
        (unless (and (eq (funcall gc-native payload) payload)
                     (= (nelisp-test-native-entry-collections) 1))
          (error "Staged-entry GC changed a rooted argument"))
        (unless (and (eq (funcall gc-native payload) payload)
                     (= (nelisp-test-native-entry-collections) 1))
          (error "Staged-entry collection was not once per descriptor"))
        (princ "ENTRY-OBSERVER-PASS staged-GC=1 rooted-argument-identity=1\n"))
      (dolist (control '(fallback unobserved duplicate ABI))
        (setq before (nelisp-test-native-entry-snapshot))
        (cond ((eq control 'fallback) (funcall (lambda (_) 42) 'live))
              ((eq control 'unobserved) (funcall plain 'live))
              ((eq control 'duplicate) (funcall native 'live) (funcall native 'live))
              (t (funcall native 'live)))
        (setq events (nelisp-test-native-entry-events before))
        (when (and (= (length events) 1)
                   (= (nth 3 (car events)) (if (eq control 'ABI) 0 1)))
          (error "Observer accepted broken %S control" control))
        (princ (format "ENTRY-OBSERVER-REJECT control=%S entries=%d\n" control (length events))))
      (setq before (nelisp-test-native-entry-snapshot))
      (dotimes (_ 257) (funcall native 'live))
      (let (refused)
        (condition-case err
            (nelisp-test-native-entry-events before)
          (error (setq refused (equal (error-message-string err) "Native entry observation overflow"))))
        (unless refused (error "Observer silently lost entries"))
        (princ "ENTRY-OBSERVER-REJECT control=overflow entries=257\n"))
      ;; Matched dispatch only; data recording adds no Lisp allocations.
      (let ((iterations 1000) (start (float-time)) before-ns after-ns)
        (dotimes (_ iterations) (funcall plain 'live))
        (setq before-ns (/ (* 1e9 (- (float-time) start)) iterations) start (float-time))
        (dotimes (_ iterations) (funcall native 'live))
        (setq after-ns (/ (* 1e9 (- (float-time) start)) iterations))
        (princ (format "ENTRY-OBSERVER-TIMING calls=%d plain-ns=%.0f observed-ns=%.0f\n"
                       iterations before-ns after-ns))))))
(princ "ENTRY-OBSERVER-DONE\n")
