;;; standalone-native-tier-driver.el --- Genuine static async tier controls -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(defvar tier-parent-image-marker nil)
(unless (and tier-parent-image-marker
             (equal tier-parent-image-marker (getenv "TIER_PARENT_MARKER")))
  (error "Tier parent cold image was not restored"))
(defvar tier-parent-aot-before (featurep 'nelisp-aot-compiler))
(defvar tier0-backend (intern (or (getenv "TIER0_BACKEND") "in-house")))
(defvar tier-parent-cache (getenv "NELISP_NATIVE_CACHE"))
(require 'nelisp-native-tier)
(require 'nelisp-bytecode-native-consumer)
(defun tier-assert (condition label) (unless condition (error "Tier assertion: %s" label)))
(defun tier-ready (entry)
  (let ((start (float-time)) (job (plist-get entry :job)) (delay (alloc-bytes 16 8)))
    (ptr-write-u64 delay 0 0)
    (ptr-write-u64 delay 8 50000000)
    (tier-assert job "genuine queued job")
    (while (and (= 0 (nelisp-process-status (plist-get job :process)))
                (< (- (float-time) start) 270))
      (nl-nanosleep delay))
    (tier-assert (/= 0 (nelisp-process-status (plist-get job :process))) "worker completed before deadline")
    (tier-assert (= 0 (nelisp-process-exit-status (plist-get job :process))) "worker exited successfully")
    job))
(let* ((functions (nelisp-bytecode-native-consumer-read-elc-functions (getenv "TIER_FIXTURE")))
       (function (cdr (assq 'tier-fixture functions)))
       (cons-function (cdr (assq 'tier-cons functions)))
       (nelisp-native-tier-threshold 2)
       (nelisp-native-tier-worker-binary (getenv "TIER_BINARY"))
       (nelisp-native-tier-worker-image (getenv "TIER_FULL_IMAGE"))
       (entry (nelisp-native-tier-install 'tier-live function tier0-backend))
       (old (car (plist-get entry :cell)))
       (old-handle (car nelisp-native-load-raw-mappings))
       (value (vector 'kept))
       (identity-callback (lambda (x) (cons 'exact (car x)))))
  (princ (format "TIER-PARENT-IMAGE optimizer-before=%S optimizer-after=%S\n"
                 tier-parent-aot-before (featurep 'nelisp-aot-compiler)))
  (tier-assert (equal (tier-live identity-callback value) (cons 'exact value)) "pre-swap exact behavior")
  (tier-live identity-callback value)
  (tier-assert nelisp-native-tier--pending
               (format "hotness launched asynchronous child; count=%S refusal=%S"
                       (plist-get entry :count) (plist-get entry :refusal)))
  (let* ((job nelisp-native-tier--pending) (process (plist-get job :process))
         (pid (nelisp-process-pid process)))
    (tier-assert (> pid 0) "real child PID")
    (tier-assert (= 0 (nelisp-process-status process)) "launch did not wait for compiler")
    (tier-assert (eq old (car (plist-get entry :cell))) "Tier 0 continues while compiling")
    (tier-assert (equal (tier-live identity-callback value) (cons 'exact value)) "caller continues")
    (tier-ready entry)
    (tier-assert (plist-get (nelisp-native-tier--read
                            (expand-file-name "reply" (plist-get job :directory))) :compiler-cold)
                 "different compiler image really loaded")
    ;; The native Tier 0 frame is active while its callback publishes Tier 1.
    (let ((result (tier-live
                   (lambda (x)
                     (tier-assert (eq old (car (plist-get entry :cell))) "old generation active before publication")
                     (nelisp-native-tier-poll)
                     (tier-assert (= 1 (plist-get entry :tier)) "complete generation published")
                     (tier-assert (equal tier-parent-cache (getenv "NELISP_NATIVE_CACHE"))
                                  "parent cache environment restored after publication")
                     (garbage-collect)
                     (tier-assert (memq old-handle nelisp-native-load-raw-mappings) "old mapping lifetime retained")
                     (cons 'exact (car x))) value)))
      (tier-assert (equal result (cons 'exact value)) "active old generation returned after swap and GC"))
    (tier-assert (not (eq old (car (plist-get entry :cell)))) "callable changed")
    (tier-assert (equal (tier-live identity-callback value) (cons 'exact value)) "post-swap exact behavior")
    (tier-assert (= nelisp-native-tier--reaped 1) "finished child reaped")
    (tier-assert (not (file-exists-p (format "/proc/%d" pid))) "no zombie child")
    (tier-assert (not (file-exists-p (plist-get job :directory))) "job files removed"))
  (let* ((nelisp-native-tier-threshold 1)
         (stale (nelisp-native-tier-install 'tier-stale cons-function tier0-backend))
         (current (lambda (_a _b) 'user-definition)))
    (tier-stale 'a 'b)
    (tier-ready stale)
    (fset 'tier-stale current)
    (nelisp-native-tier-poll)
    (tier-assert (equal tier-parent-cache (getenv "NELISP_NATIVE_CACHE"))
                 "parent cache environment preserved after stale refusal")
    (tier-assert (eq current (symbol-function 'tier-stale)) "stale job keeps current user definition")
    (tier-assert (plist-get stale :refusal) "stale refusal retained")
    (tier-assert (= 0 (plist-get stale :tier)) "stale job not published")
    (tier-assert (not (plist-get stale :job)) "stale child reaped"))
  (let* ((nelisp-native-tier-backend 'gccjit) (nelisp-native-tier-threshold 1)
         (refused (nelisp-native-tier-install 'tier-refused function tier0-backend))
         (serial nelisp-native-tier--serial))
    (tier-assert (equal (tier-refused identity-callback value) (cons 'exact value)) "static gccjit preserves Tier 0")
    (tier-assert (plist-get (plist-get refused :refusal) :permanent) "static refusal memoized")
    (dotimes (_ 3) (tier-refused identity-callback value))
    (tier-assert (= nelisp-native-tier--serial (1+ serial)) "permanent refusal backed off")
    (tier-assert (not nelisp-native-tier--pending) "static gccjit created no worker"))
  (let* ((nelisp-native-tier-worker-binary (getenv "TIER_FOREIGN_BINARY"))
         (nelisp-native-tier-threshold 1)
         (refused (nelisp-native-tier-install 'tier-foreign (cdr (assq 'tier-foreign functions)) tier0-backend)))
    (tier-foreign 'a 'b)
    (tier-assert (plist-get refused :refusal) "different executable refused")
    (tier-assert (not nelisp-native-tier--pending) "foreign executable never launched"))
  ;; Cancel an actual compiler child and check that waitpid closes its lifetime.
  (let* ((nelisp-native-tier-threshold 1)
         (cancelled (nelisp-native-tier-install 'tier-cancel (cdr (assq 'tier-cancellation functions)) tier0-backend)))
    (nelisp-native-tier-request cancelled t)
    (let* ((job (plist-get cancelled :job)) (process (plist-get job :process))
           (pid (nelisp-process-pid process)))
      (tier-assert (= 0 (nelisp-process-status process)) "cancel target was a running child")
      (nelisp-native-tier-cancel cancelled)
      (tier-assert (not (file-exists-p (format "/proc/%d" pid))) "cancelled child reaped")
      (tier-assert (not (file-exists-p (plist-get job :directory))) "cancel job files removed")
      (tier-assert (equal (tier-cancel 'a 'b) '(b . a)) "cancel preserves current behavior")
      (tier-assert (not nelisp-native-tier--pending) "cancel cooldown prevents immediate retry")))
  (princ (format "TIER-PASS cases=9 reaped=%d handles=%d bytes=%d\n"
                 nelisp-native-tier--reaped nelisp-native-budget--handles nelisp-native-budget--bytes)))

(when (eq tier0-backend 'template)
  (tier-assert (> nelisp-native-template--entry-count 0) "template Tier 0 entries")
  (tier-assert (= nelisp-native-template--fallback-count 0) "no Tier 0 fallback")
  (princ (format "TIER-TEMPLATE-PASS entries=%d fallback=%d optimizer-after=%S\n"
                 nelisp-native-template--entry-count nelisp-native-template--fallback-count
                 (featurep 'nelisp-aot-compiler))))
