;;; standalone-native-corpus-u10-driver.el --- Native corpus receipts -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(when (file-exists-p (getenv "U10_STOP"))
  (princ "U10-ABORT known qualification blocker; no native claim\n")
  (exit 2))
(require 'nelisp-native-cache)
(load (expand-file-name "test/support/native-corpus-u10-fixtures.el") nil t t)
(load (expand-file-name "test/support/native-corpus-u10-state.el") nil t t)
(defvar u10-protected-function nil)
(defvar u10-protected-oracle nil)
(load (getenv "U10_FIXTURE") nil t t)
(let* ((cases (split-string (getenv "U10_CASES")))
       (protected (member "protected" cases))
       (opcodes (mapcar #'string-to-number (cl-remove "protected" cases :test #'equal))))
  (u10-assert (equal opcodes (mapcar (lambda (row) (plist-get row :opcode)) u10-fixtures))
              "exact projected opcode sequence")
  (u10-assert (if protected
                 (and (byte-code-function-p u10-protected-function) (= (length u10-protected-oracle) 4))
               (and (null u10-protected-function) (null u10-protected-oracle)))
              "exact projected protected presence")
  (when protected
    (setq u10-protected-function (u10-protected-cache-function u10-protected-function))))
(defun u10-load (fn phase)
  "Retain the exact public path and mapped header without duplicating their reads."
  (let ((cache-file (symbol-function 'nelisp-native-cache-file))
        seen-file file hit native entry loaded-header)
    (cl-letf (((symbol-function 'nelisp-native-cache-file)
               (lambda (function)
                 (let ((path (funcall cache-file function)))
                   (unless seen-file
                     (setq seen-file t file path hit (file-exists-p path)))
                   path))))
      (when (equal phase "compile") (nelisp-native-cache-compile fn))
      (let ((constructor (symbol-function 'nelisp-native-cache--callable-from-entry))
            (checks (list nelisp-native-load--raw-v2-check-count
                          nelisp-native-load--rooted-cfg-outer-validation-count
                          nelisp-bytecode-native-rooted-cfg-contract--validation-count))
            (maps 0))
        (cl-letf (((symbol-function 'nelisp-native-cache-compile)
                   (lambda (&rest _) (error "U10 warm load attempted compilation")))
                  ((symbol-function 'nelisp-native-cache--callable-from-entry)
                   (lambda (address header addresses &optional constants)
                     (setq maps (1+ maps) entry address loaded-header header)
                     (funcall constructor address header addresses constants))))
          (setq native (nelisp-native-cache-load fn)))
        (u10-assert (and native entry (= maps 1)) "one mapped native entry")
        (u10-assert (equal checks (list nelisp-native-load--raw-v2-check-count
                                      nelisp-native-load--rooted-cfg-outer-validation-count
                                      nelisp-bytecode-native-rooted-cfg-contract--validation-count))
                    "zero full validations on cache load")))
    (list native entry loaded-header file hit)))
(defun u10-copy-bytes (source destination)
  (with-temp-buffer
    (let ((coding-system-for-read 'no-conversion) (coding-system-for-write 'no-conversion))
      (insert-file-contents-literally source)
      (write-region (point-min) (point-max) destination nil 'silent))))
(defun u10-stale-controls (fn)
  "Misroute stale files deliberately; refusal must precede either mapper."
  (let* ((file (nelisp-native-cache-file fn))
         (changed (make-byte-code 0 (aref fn 1) (vconcat (aref fn 2)) (aref fn 3)))
         (directory (make-temp-file "u10-corrupt-" t))
         (corrupt (expand-file-name (file-name-nondirectory file) directory))
         (trusted (symbol-function 'nelisp-native-load-raw-v2-artifact-trusted))
         (dynamic (symbol-function 'nelisp-native-cache--load-gccjit)))
    (aset (aref changed 2) 0 43)
    (u10-assert (not (equal file (nelisp-native-cache-file changed))) "input changes key")
    (let ((nelisp-native-cache--abi (make-string 64 ?0))
          (nelisp-native-template--abi (make-string 64 ?0)))
      (u10-assert (not (equal file (nelisp-native-cache-file fn))) "ABI changes key"))
    (unwind-protect
        (progn
          (u10-copy-bytes file corrupt)
          (if (eq nelisp-native-cache-backend 'gccjit)
              (progn (u10-copy-bytes (concat file ".nelh") (concat corrupt ".nelh"))
                     (let ((coding-system-for-write 'no-conversion))
                       (write-region "corruption" nil corrupt t 'silent)))
            (with-temp-buffer
              (insert-file-contents corrupt) (goto-char (point-min))
              (let ((header (read (current-buffer))) (manifest (read (current-buffer))))
                (let* ((native (plist-get manifest :native))
                       (bytes (base64-decode-string (plist-get native :text-base64))))
                  ;; Same length, valid base64, stale hashes: authenticate bytes,
                  ;; not just envelope syntax. Never invoke this candidate.
                  (aset bytes 0 (logxor (aref bytes 0) 1))
                  (setq native (plist-put native :text-base64 (base64-encode-string bytes t)))
                  (setq manifest (plist-put manifest :native native)))
                (erase-buffer) (prin1 header (current-buffer)) (insert "\n")
                (prin1 manifest (current-buffer)) (insert "\n")
                (write-region (point-min) (point-max) corrupt nil 'silent))))
          (dolist (control '(input abi artifact))
            (let ((maps 0) refused
                  (nelisp-native-cache--abi (if (eq control 'abi) (make-string 64 ?0)
                                             nelisp-native-cache--abi))
                  (nelisp-native-template--abi (if (eq control 'abi) (make-string 64 ?0)
                                                 nelisp-native-template--abi)))
              (cl-letf (((symbol-function 'nelisp-native-cache-file)
                         (lambda (_) (if (eq control 'artifact) corrupt file)))
                        ((symbol-function 'nelisp-native-load-raw-v2-artifact-trusted)
                         (lambda (&rest args) (setq maps (1+ maps)) (apply trusted args)))
                        ((symbol-function 'nelisp-native-cache--load-gccjit)
                         (lambda (&rest args) (setq maps (1+ maps)) (apply dynamic args))))
                (condition-case condition
                    (nelisp-native-cache-load (if (eq control 'input) changed fn))
                  (error (setq refused condition))))
              ;; Static artifact authentication occurs inside the trusted API,
              ;; before its actual mmap counter changes.
              (unless refused
                (princ (format "U10-STALE-ACCEPTED control=%s backend=%s mapper-calls=%d\n"
                               control nelisp-native-cache-backend maps)))
              (u10-assert refused (format "stale %s refused" control))
              (u10-assert (or (= maps 0) (and (eq control 'artifact)
                                              (memq nelisp-native-cache-backend '(in-house template)) (= maps 1)))
                          "stale input/ABI did not reach mapper")
              (princ (format "U10-STALE-PASS control=%s\n" control)))))
      (delete-directory directory t))))
(let ((nelisp-native-cache-backend (intern (getenv "U10_BACKEND")))
      (phase (getenv "U10_PHASE")) (passed 0) (entries 0) (pointer (symbol-function 'ptr-call)))
  (dolist (name (split-string (getenv "U10_CASES")))
    (let* ((row (cl-find (string-to-number name) u10-fixtures
                         :key (lambda (item) (plist-get item :opcode))))
           (cache (expand-file-name (or (plist-get row :unit) name) (getenv "U10_CACHE_BASE"))))
      ;; On Windows the reader creates every component itself with the
      ;; owner's protected DACL and pins it; POSIX modes do not apply there.
      (unless (eq system-type 'windows-nt)
        (unless (file-directory-p cache) (make-directory cache t))
        (set-file-modes cache #o700))
      (setenv "NELISP_NATIVE_CACHE" cache))
    (if (equal name "protected")
        (let* ((pair (u10-load u10-protected-function phase)) (count 0))
          (dolist (test u10-protected-oracle)
            (let (actual)
              (cl-letf (((symbol-function 'ptr-call)
                         (lambda (address env ticket argc roots x y)
                           (when (= address (cadr pair)) (setq count (1+ count)))
                           (funcall pointer address env ticket argc roots x y))))
                (setq actual (u10-protected-observe (car pair) (car test) (cadr test))))
              (u10-assert (equal actual (nth 2 test))
                          (format "GNU raise-time hook/debugger/cleanup ordering mode=%S debugger=%S GNU=%S actual=%S"
                                  (car test) (cadr test) (nth 2 test) actual))))
          (u10-assert (= count 4) "protected native entries")
          (princ "U10-ORDER-PASS cases=4 entries=4\n"))
      (let* ((opcode (string-to-number name))
             (row (cl-find opcode u10-fixtures :key (lambda (item) (plist-get item :opcode))))
             (fn (plist-get row :function))
             ;; Populate live switch tables before public admission.
             (vm (u10-observe row fn nil))
             (state (u10-function-state fn))
             (count 0))
        (u10-assert (eq (plist-get row :frame-status) 'complete) "only audited complete fixtures run")
        (when (plist-get row :relocation-refusal)
          (let* ((fixture (plist-get row :fixture))
                 (original (make-byte-code
                            0 (apply #'unibyte-string (append (alist-get 'bytecode fixture) nil))
                            (u10-materialize fixture) (alist-get 'declared_stack_depth fixture)))
                 (code (aref original 1)) (constants (aref original 2)) refused)
            (condition-case condition
                (nelisp-native-cache-compile original)
              (error (setq refused
                           (string-match-p (if (eq nelisp-native-cache-backend 'template)
                                               "\\`Template relocation refused:"
                                             "Cache relocation refused")
                                           (error-message-string condition)))))
            (u10-assert (and refused (byte-code-function-p original)
                             (eq code (aref original 1)) (eq constants (aref original 2)))
                        "unreadable relocation refused; original byte code retained")
            (u10-assert (equal (plist-get row :gnu) (u10-observe row original t))
                        "refused original still runs as byte code")
            (u10-assert (and (eq code (aref original 1)) (eq constants (aref original 2)))
                        "same refused byte-code object after execution")
            (princ (format "U10-RELOCATION-REFUSED backend=%s opcode=%d reason=unreadable-live-constant\n"
                           nelisp-native-cache-backend opcode))))
        (u10-assert (equal (plist-get row :gnu) vm) (format "GNU/VM fixture %d" opcode))
        (let* ((pair (u10-load fn phase)) (header (nth 2 pair))
               (expected (plist-get row :gnu))
               actual
               (before nelisp-native-load--trusted-map-count))
          (princ (format "U10-START backend=%s opcode=%d phase=%s cache=%s\n"
                         nelisp-native-cache-backend opcode phase (if (nth 4 pair) "hit" "miss")))
          (u10-function-state-check fn state)
          (cl-letf (((symbol-function 'ptr-call)
                     (lambda (address env ticket argc roots x y)
                       (when (= address (cadr pair))
                         (u10-assert (and (= argc 0) (= roots (plist-get header :root-count))
                                          (= x 0) (= y 0) (> ticket 0)) "native entry ABI")
                         (setq count (1+ count)))
                       (funcall pointer address env ticket argc roots x y))))
            (setq actual (u10-observe row (car pair) nil)))
          (u10-assert (equal expected actual) (format "GNU/native fixture %d GNU=%S actual=%S" opcode expected actual))
          (u10-assert (= count 1) "exact native entry, no fallback")
          (when (= opcode 192)
            (u10-stale-controls fn)
            (u10-assert (= before nelisp-native-load--trusted-map-count) "corruption refused before mmap"))
          (setq passed (1+ passed) entries (+ entries count))
          (princ (format "U10-FIXTURE-PASS backend=%s opcode=%d phase=%s entries=1 gc=1\n"
                         nelisp-native-cache-backend opcode phase))))))
  (princ (format "U10-BATCH-DONE backend=%s phase=%s fixtures=%d entries=%d\n"
                 nelisp-native-cache-backend phase passed entries)))
