;;; standalone-root-pin-v2-slot-index-driver.el --- Slot index smoke -*- lexical-binding: t; -*-

(require 'nelisp-native-load)

(defun nelisp-test-root-pin-v2-slot-index-smoke ()
  (let* ((env (nelisp--native-env))
         (slot-addr (nelisp-native-load--symbol-addr "nl_root_pin_slot_v2"))
         (begin-addr (nelisp-native-load--symbol-addr "nl_root_pin_begin_v2"))
         (reserve-addr (nelisp-native-load--symbol-addr "nl_root_pin_reserve_v2"))
         (end-addr (nelisp-native-load--symbol-addr "nl_root_pin_end_v2"))
         (ticket (ptr-call begin-addr env 0 0 0 0 0))
         (slot0 (ptr-call reserve-addr env ticket 0 0 0 0))
         (slot1 (ptr-call reserve-addr env ticket 0 0 0 0))
         (before-gc (list (ptr-call slot-addr env ticket 0 0 0 0)
                          (ptr-call slot-addr env ticket 1 0 0 0)))
         (gc (garbage-collect))
         (after-gc (list (ptr-call slot-addr env ticket 0 0 0 0)
                         (ptr-call slot-addr env ticket 1 0 0 0)))
         (refusals (list (ptr-call slot-addr env ticket -1 0 0 0)
                         (ptr-call slot-addr env ticket 2 0 0 0)
                         (ptr-call slot-addr env ticket 16384 0 0 0)
                         (ptr-call slot-addr env ticket most-positive-fixnum 0 0 0)
                         (ptr-call slot-addr (1+ env) ticket 0 0 0 0)))
         (end (ptr-call end-addr env ticket 0 0 0 0))
         (stale (ptr-call slot-addr env ticket 0 0 0 0))
         (next (ptr-call begin-addr env 0 0 0 0 0))
         (next-slot (ptr-call reserve-addr env next 0 0 0 0))
         (reused (ptr-call slot-addr env next 0 0 0 0))
         (next-stale (ptr-call slot-addr env ticket 0 0 0 0))
         (next-end (ptr-call end-addr env next 0 0 0 0))
         (outer (ptr-call begin-addr env 0 0 0 0 0))
         (outer-slot (ptr-call reserve-addr env outer 0 0 0 0))
         (inner (ptr-call begin-addr env 0 0 0 0 0))
         (outer-during-inner (ptr-call slot-addr env outer 0 0 0 0))
         (inner-before-reserve (ptr-call slot-addr env inner 0 0 0 0))
         (inner-slot (ptr-call reserve-addr env inner 0 0 0 0))
         (inner-access (ptr-call slot-addr env inner 0 0 0 0))
         (inner-end (ptr-call end-addr env inner 0 0 0 0))
         (inner-stale (ptr-call slot-addr env inner 0 0 0 0))
         (outer-again (ptr-call slot-addr env outer 0 0 0 0))
         (outer-end (ptr-call end-addr env outer 0 0 0 0))
         (legacy (nelisp-native-load--pin-begin env))
         (legacy-mode-refusal (ptr-call slot-addr env legacy 0 0 0 0))
         (legacy-end (nelisp-native-load--pin-end env legacy))
         (ok (and (> ticket 0) (> slot0 0) (> slot1 slot0)
                  (equal before-gc (list slot0 slot1))
                  (equal after-gc (list slot0 slot1))
                  (equal refusals '(0 0 0 0 0))
                  (= end 1) (= stale 0)
                  (> next 0) (/= ticket next) (> next-slot 0)
                  (= reused slot0) (= next-stale 0) (= next-end 1)
                  (> outer 0) (> outer-slot 0) (> inner 0) (/= outer inner)
                  (= outer-during-inner 0) (= inner-before-reserve 0)
                  (> inner-slot 0) (= inner-access inner-slot)
                  (= inner-end 1) (= inner-stale 0)
                  (= outer-again outer-slot) (= outer-end 1)
                  (> legacy 0) (= legacy-mode-refusal 0) (null legacy-end)))
         (observed (list before-gc after-gc refusals end stale next next-slot
                         reused next-stale next-end outer outer-slot inner
                         outer-during-inner inner-before-reserve inner-slot
                         inner-access inner-end inner-stale outer-again
                         outer-end legacy legacy-mode-refusal legacy-end)))
    (if ok t (progn (princ (format "observed=%S" observed)) nil))))

(provide 'standalone-root-pin-v2-slot-index-driver)

;;; standalone-root-pin-v2-slot-index-driver.el ends here
