;;; standalone-native-switch-u6-driver.el --- U6 native entries -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'nelisp-native-cache)
(load "test/support/native-entry-observer.el" nil t t)
(load "test/support/native-switch-u6-fixtures.el" nil t t)
(defun u6-assert (value label) (unless value (error "U6: %s" label)))
(let* ((nelisp-native-cache-backend (intern (getenv "U6_BACKEND")))
       (name (intern (getenv "U6_CASE")))
       (fixture (native-switch-u6-fixture name))
       (fn (car fixture)) (table (cadr fixture)) (keys (nth 2 fixture))
       (entries 0) (cases 0) (compiles 0)
       (compiler (symbol-function 'nelisp-native-cache-compile))
       (before (float-time)))
  (princ (format "U6-START %S %S\n" nelisp-native-cache-backend name))
  (cl-letf (((symbol-function 'nelisp-native-cache-compile)
             (lambda (&rest arguments) (setq compiles (1+ compiles)) (apply compiler arguments))))
    (nelisp-native-cache-install 'u6-native fn))
  (let* ((file (nelisp-native-cache-file fn))
         (header (with-temp-buffer
                   (insert-file-contents (if (eq nelisp-native-cache-backend 'gccjit) (concat file ".nelh") file))
                   (goto-char (point-min)) (read (current-buffer))))
         (roots (plist-get header :root-count))
         (arity (plist-get header :arity))
         (native (symbol-function 'u6-native)))
    (cl-labels ((run (args expected)
                 (garbage-collect)
                 (nelisp-test-with-native-entry-observer
		     (lambda (address env ticket argc count x y)
		       (when (and (= argc arity) (= count roots) (= x 0) (= y 0))
			 (setq entries (1+ entries))))
		   (u6-assert (eq (apply native args) expected) "native value/identity"))
                 (setq cases (1+ cases)))
               (args (key) (if (eq name 'dynamic) (list key table) (list key))))
      (if (eq name 'backedge)
          (progn (setq u6-left 3 u6-effects nil)
                 (u6-assert (eq (funcall fn) 'done) "VM loop oracle")
                 (u6-assert (equal u6-effects '(0 1 2 3)) "VM loop effects")
                 (setq u6-left 3 u6-effects nil) (run nil 'done)
                 (u6-assert (equal u6-effects '(0 1 2 3)) "native backedge effects"))
        ;; GNU host suite qualifies custom equality against identical bytecode;
        ;; the stock NeLisp VM lacks custom table-test dispatch.
        (unless (eq name 'custom)
          (u6-assert (eq (apply fn (args (car keys))) 'first) "VM hit")
          (u6-assert (eq (apply fn (args (nth 2 keys))) 'miss) "VM miss"))
        (setq u6-gc (eq name 'custom) u6-effects nil)
        (run (args (car keys)) 'first) (run (args (cadr keys)) 'second)
        (run (args (nth 2 keys)) 'miss)
        (when (eq name 'custom) (u6-assert u6-effects "custom comparator executed"))
        (setq u6-gc nil)
        (when (eq name 'custom)
          (setq u6-custom-mode 'throw)
          (u6-assert (eq (catch 'u6-custom (funcall native (car keys))) 'custom-exit)
                     "custom comparison throw propagated")
          (setq u6-custom-mode 'signal)
          (let ((condition nil))
            (condition-case err (funcall native (car keys)) (error (setq condition err)))
            (u6-assert (equal condition '(error "u6 custom equality")) "custom comparison signal/data"))
          (setq u6-custom-mode nil))
        ;; Mutation to a previously absent target, shared target, and removal.
        (puthash (car keys) (if (eq name 'dynamic) 5 6) table)
        (run (args (car keys)) 'second)
        (puthash (nth 2 keys) (if (eq name 'dynamic) 5 6) table)
        (run (args (nth 2 keys)) 'second)
        (remhash (car keys) table) (run (args (car keys)) 'miss)
        (puthash (car keys) 999 table)
        (let ((failed nil))
          (condition-case err (apply native (args (car keys))) (error (setq failed err)))
          (u6-assert (and failed (string-match-p "Invalid native switch target" (cadr failed))) "invalid runtime target refused"))
        (remhash (car keys) table)
        ;; Frozen lookup callable survives poisoning of the public cell.
        (cl-letf (((symbol-function 'gethash) (lambda (&rest _) (error "poisoned gethash"))))
          (run (args (cadr keys)) 'second))
        ;; Reusing a table-bearing cache must bind the current caller's object.
        (cl-letf (((symbol-function 'nelisp-native-cache-compile) (lambda (&rest _) (error "warm U6 recompiled"))))
          (nelisp-native-cache-install 'u6-native fn))
        (let* ((other (native-switch-u6-fixture name)) (other-fn (car other)) (other-table (cadr other)))
          (puthash (car keys) (if (eq name 'dynamic) 5 6) other-table)
          (cl-letf (((symbol-function 'nelisp-native-cache-compile) (lambda (&rest _) (error "equivalent body recompiled"))))
            (nelisp-native-cache-install 'u6-other other-fn))
          (u6-assert (eq (if (eq name 'dynamic) (funcall 'u6-other (car keys) other-table)
                          (funcall 'u6-other (car keys))) 'second) "cache bound the second caller's table"))))
    (u6-assert (= entries cases) "one raw native entry per successful case")
    (princ (format "U6-NATIVE-PASS backend=%S fixture=%S cases=%d native-entries=%d compiles=%d seconds=%.3f\n"
                   nelisp-native-cache-backend name cases entries compiles (- (float-time) before)))))
