;;; standalone-native-legacy-u9-driver.el --- Independent native wrapper parity -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'nelisp-native-cache)
(load "test/support/native-entry-observer.el" nil t t)
(load "test/support/native-legacy-u9-fixtures.el" nil t t)
(defun u9-assert (value message) (unless value (error "U9: %s" message)))
(let ((nelisp-native-cache-backend (intern (getenv "U9_BACKEND")))
      (phase (getenv "U9_PHASE")) (cases 0) (entries 0)
      (oracle (with-temp-buffer (insert-file-contents (getenv "U9_ORACLE"))
                                (goto-char (point-min)) (read (current-buffer)))))
  (dolist (name (split-string (getenv "U9_CASES")))
    (let* ((opcode (string-to-number name)) (fn (native-legacy-u9-function opcode)))
      (princ (format "U9-START backend=%S opcode=%d phase=%s\n" nelisp-native-cache-backend opcode phase))
      (if (equal phase "load")
          (cl-letf (((symbol-function 'nelisp-native-cache-compile)
                     (lambda (&rest _) (error "U9 warm recompiled"))))
            (nelisp-native-cache-install 'u9-native fn))
        (nelisp-native-cache-install 'u9-native fn))
      (let* ((native (symbol-function 'u9-native))
             (file (nelisp-native-cache-file fn))
             (header (with-temp-buffer
                       (insert-file-contents (if (eq nelisp-native-cache-backend 'gccjit)
                                                 (concat file ".nelh") file))
                       (goto-char (point-min)) (read (current-buffer))))
             (roots (plist-get header :root-count))
             (provider-name (nth 1 (nelisp-native-funcall-v2-primitive opcode))))
        (dolist (mode (native-legacy-u9-modes opcode))
          (let* ((expected (cdr (assq mode (cdr (assq opcode oracle)))))
                 (interpreted (native-legacy-u9-observe fn opcode mode))
                 (before entries)
                 (actual
                  (cl-letf (((symbol-function provider-name) (lambda (&rest _) (error "public provider rebound"))))
                    (nelisp-test-with-native-entry-observer
			(lambda (address env ticket argc count x y)
			  (when (and (= argc 0) (= count roots) (= x 0) (= y 0))
			    (setq entries (1+ entries))))
		      (native-legacy-u9-observe native opcode mode)))))
            (u9-assert (equal expected interpreted)
                       (format "VM %d/%S GNU=%S VM=%S" opcode mode expected interpreted))
            (u9-assert (equal expected actual)
                       (format "native %d/%S GNU=%S actual=%S" opcode mode expected actual))
            (u9-assert (= (- entries before) 1) "one native entry, no fallback")
            (setq cases (1+ cases))
            (princ (format "U9-PARITY opcode=%d mode=%S\n" opcode mode)))))))
  (u9-assert (and (> cases 0) (= cases entries)) "executed count")
  (princ (format "U9-NATIVE-PASS backend=%S cases=%d entries=%d phase=%s\n"
                 nelisp-native-cache-backend cases entries phase)))
