;;; standalone-native-handlers-u8-bridge-driver.el --- Focused native landing -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'nelisp-native-cache)
(define-error 'u8-bridge-child "U8 bridge" 'arith-error)
(let* ((addresses (nelisp-native-load-root-v2-addresses))
       (env (plist-get addresses :environment))
       (gateway (nelisp-native-load--raw-v2-symbol-addr-trusted "nl_native_frame_v2"))
       (call (nelisp-native-load--raw-v2-symbol-addr-trusted "nl_native_funcall_v2"))
       (ticket (ptr-call (plist-get addresses :begin) env 0 0 0 0 0))
       (slots nil))
  (unwind-protect
      (progn
        (dotimes (_ 40) (push (ptr-call (plist-get addresses :reserve) env ticket 0 0 0 0) slots))
        (setq slots (vconcat (nreverse slots)))
        (cl-labels ((put (i value) (nelisp--native-pin-copy-v2 env ticket i value))
                    (get (i) (nelisp-native-load-unbox (aref slots i) env (aref slots 0)))
                    (frame (action a r) (ptr-call gateway env ticket 1 action a r))
                    (check (value) (unless value (error "U8 bridge assertion result=%S exit=%S" (get 4) (list (get 18) (get 19) (get 20)))))
                    (enter () (put 1 (nelisp-native-frame-v2-initializer)) (put 2 1) (put 3 0) (check (= (frame 0 2 4) 0)))
                    (register (kind selector target depth)
                      (put 2 selector) (put 3 (vector kind target depth 14 2 10))
                      (check (= (frame 8 2 4) 0)))
                    (raise (function)
                      (put 21 function)
                      (check (= (ptr-call call env ticket 21 22 0 23) 1048))
                      (dotimes (i 3) (check (= (frame 12 (+ 24 i) (+ 18 i)) 0))))
                    (cleanup (payload)
                      (put 2 payload) (check (= (frame 4 2 4) 0)))
                    (land (target value depth)
                      (check (= (frame 11 18 4) 0))
                      (check (= (get 4) target))
                      (check (equal (get (+ 10 depth)) value))
                      (check (= (frame 3 2 4) 0))))
          (enter)
          (register 2 'u8-bridge-tag 100 1)
          (put 10 'old) (put 11 'changed)
          (check (= (frame 12 11 10) 0))
          (check (= (frame 12 11 1) 2))
          (raise (lambda () (garbage-collect) (throw 'u8-bridge-tag 'caught)))
          (land 100 'caught 1)
          (check (eq (get 10) 'changed))
          (princ "U8-BRIDGE-PASS catch-bank-gc\n")
          (enter)
          (register 1 '(no-catch) 101 0)
          (register 2 nil 102 0)
          (raise (lambda () (throw nil 'value)))
          (land 101 '(no-catch nil value) 0)
          (princ "U8-BRIDGE-PASS nil-no-catch\n")
          (enter)
          (register 1 '(arith-error quit) 103 0)
          (raise (lambda () (signal 'u8-bridge-child '(payload))))
          (land 103 '(u8-bridge-child payload) 0)
          (princ "U8-BRIDGE-PASS inherited-condition\n")
          (enter)
          (register 2 'outer 104 0)
          (register 2 'inner 105 0)
          (cleanup (lambda () (garbage-collect) (throw 'outer 'replacement)))
          (raise (lambda () (throw 'inner 'discarded)))
          (land 104 'replacement 0)
          (princ "U8-BRIDGE-PASS cleanup-rethrow\n")
          (princ "U8-BRIDGE-COMPLETE cases=4\n")))
    (ptr-call (plist-get addresses :end) env ticket 0 0 0 0)))
