;;; standalone-native-template-ordinary-driver.el --- P2.3 timing and controls -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'nelisp-native-cache)
(require 'nelisp-bytecode-native-consumer)
(load (expand-file-name "test/support/native-real-corpus-inputs.el") nil t t)
(load (expand-file-name "test/support/native-real-corpus-fixtures.el") nil t t)
(defun p23-assert (value label) (unless value (error "Template ordinary: %s" label)))
(let* ((nelisp-native-cache-backend 'template)
       (name (intern (getenv "TEMPLATE_NAME")))
       (row (cl-find name f3-real-corpus :key (lambda (item) (plist-get item :name))))
       (function (if row (plist-get row :function)
                   (cdr (assq name (nelisp-bytecode-native-consumer-read-elc-functions (getenv "TEMPLATE_FIXTURE"))))))
       (arguments (if row (plist-get (car (plist-get row :cases)) :args) '(40 2)))
       (expected (if row (plist-get (car (plist-get row :cases)) :gnu) '(:value (40 . 2))))
       (before nelisp-native-template--validation-count)
       (maps nelisp-native-load--trusted-map-count)
       (entries nelisp-native-template--entry-count)
       (start (float-time))
       (_file (nelisp-native-cache-compile function))
       (compiled (- (float-time) start))
       (native (nelisp-native-cache-load function))
       (loaded (- (float-time) start))
       (actual (f3-real-corpus-observe native arguments))
       (elapsed (- (float-time) start)))
  (p23-assert (equal actual expected) "exact GNU result")
  (p23-assert (= 1 (- nelisp-native-template--validation-count before)) "one validation")
  (p23-assert (= 1 (- nelisp-native-load--trusted-map-count maps)) "one trusted map")
  (p23-assert (= 1 (- nelisp-native-template--entry-count entries)) "one native entry")
  (p23-assert (= 0 nelisp-native-template--fallback-count) "no fallback")
  (princ (format "P23-TIMING name=%s compile=%.9f load=%.9f call=%.9f total=%.9f validations=1 maps=1 entries=1\n"
                 name compiled (- loaded compiled) (- elapsed loaded) elapsed)))
(when (equal (getenv "TEMPLATE_CONTROLS") "1")
  (let* ((nelisp-native-cache-backend 'template)
         (table (make-hash-table :test 'eql))
         (function (make-byte-code 257 (unibyte-string 192 183 193 135 194 135) (vector table 42 99) 3)))
    (puthash 7 2 table)
    (nelisp-native-cache-compile function)
    (let ((native (nelisp-native-cache-load function)))
      (p23-assert (= 42 (funcall native 7)) "switch hit")
      (p23-assert (= 42 (funcall native 8)) "switch miss")
      (puthash 7 4 table)
      (p23-assert (= 99 (funcall native 7)) "valid live switch mutation")
      (dolist (target '(3 -1 6 nope))
        (puthash 7 target table)
        (let ((refused nil))
          (condition-case e (funcall native 7) (error (setq refused e)))
          (p23-assert refused "invalid live switch mutation refused")))
      (puthash 7 2 table))
    (princ "P23-SWITCH-PASS valid=3 invalid=4\n"))
  ;; No topology pass is allowed. This ordinary cycle is polled at all four
  ;; entries; its callback collects and requests quit after three iterations.
  (setq p23-cycle-count 0)
  (defun p23-cycle-step ()
    (setq p23-cycle-count (1+ p23-cycle-count))
    (garbage-collect)
    (when (= p23-cycle-count 3) (setq quit-flag t)) nil)
  (let* ((nelisp-native-cache-backend 'template)
         (function (make-byte-code 0 (unibyte-string 192 32 136 130 0 0) [p23-cycle-step] 1))
         (_file (nelisp-native-cache-compile function))
         (native (nelisp-native-cache-load function)) (stopped nil))
    (condition-case nil (funcall native) (quit (setq stopped t)))
    (p23-assert (and stopped (= p23-cycle-count 3)) "cyclic GC/quit")
    (princ "P23-CYCLE-PASS callbacks=3 quit=1 gc=3\n")))
