;;; standalone-cl-type-lambda.el --- Live GNU source provider regression -*- lexical-binding: t; -*-
(require 'nelisp-stdlib-cl-type-lambda)
(defvar nelisp-test-cl-type-lambda--installed nil)
(let ((before-type (symbol-function 'cl-typep))
      (before-function (symbol-function 'cl-function))
      (before-compiler-macro (get 'cl-typep 'compiler-macro))
      (before-help (featurep 'help)))
  (let ((result (nelisp-stdlib-cl-type-lambda-install)))
    (setq nelisp-test-cl-type-lambda--installed (eq result 'installed))
    (unless (memq result '(installed preserved))
      (error "Unexpected CL source installer result"))
    (when (eq result 'preserved)
      (unless (and (eq before-type (symbol-function 'cl-typep))
                   (eq before-function (symbol-function 'cl-function))
                   (eq before-compiler-macro (get 'cl-typep 'compiler-macro)))
        (error "GNU host cells changed")))
    (unless (eq before-help (featurep 'help))
      (error "Installer changed whole help feature availability"))))
(unless (eq (funcall (cl-function (lambda (&cl-defs ('*)) 'normalized)))
            'normalized)
  (error "CL lambda normalization failed"))
(unless (and (= (funcall (cl-function (lambda (&optional (x 9)) x))) 9)
             (= (funcall (cl-function (lambda (&optional (x 9)) x)) 4) 4)
             (equal (funcall (cl-function (lambda (x &rest rest) (cons x rest)))
                             1 2 3) '(1 2 3))
             (= (funcall (cl-function (lambda (&key (x 8)) x))) 8)
             (= (funcall (cl-function (lambda (&key (x 8)) x)) :x 5) 5)
             (= (funcall (cl-function (lambda (x &aux (y (+ x 2))) y)) 3) 5)
             (= (funcall (cl-function (lambda ((x y)) (+ x y))) '(3 4)) 7))
  (error "General CL lambda-list normalization failed"))
(let (refused)
  (condition-case nil
      (funcall (cl-function (lambda (required) required)))
    (wrong-number-of-arguments (setq refused t)))
  (unless refused (error "Missing required argument was accepted")))
(princ "GENERAL-CL-LAMBDA-LISTS-PASS\n")
(cl-deftype nelisp-source-test-integer () '(satisfies integerp))
(unless (and (cl-typep 3 '(or nelisp-source-test-integer string))
             (not (cl-typep nil '(or nelisp-source-test-integer string))))
  (error "Derived composite type dispatch failed"))
(princ "DERIVED-COMPOSITE-TYPE-PASS\n")
(let* ((expression '(progn (setq calls (1+ calls)) 3))
       (expansion (funcall (get 'cl-typep 'compiler-macro)
                           (list 'cl-typep expression ''(or integer string))
                           expression ''(or integer string))))
  (unless (equal (eval (list 'let '((calls 0))
                            (list 'list expansion 'calls)) t)
                 '(t 1))
    (error "Genuine cl-typep compiler macro value/evaluation mismatch")))
(when nelisp-test-cl-type-lambda--installed
  (let ((old (symbol-function 'help--docstring-quote)) refused)
    (unwind-protect
        (progn
          (fset 'help--docstring-quote (lambda (text) text))
          (condition-case nil
              (macroexpand '(cl-function (lambda (&key (x 8)) x)))
            (error (setq refused t)))
          (unless refused (error "Changed CL doc helper was accepted")))
      (fset 'help--docstring-quote old))))
(let ((old nelisp-stdlib-cl-type-lambda--forms) refused)
  (unwind-protect
      (progn
        (setq nelisp-stdlib-cl-type-lambda--forms '(progn (error "Changed payload")))
        (condition-case nil (nelisp-stdlib-cl-type-lambda-install)
          (error (setq refused t)))
        (unless refused (error "Changed source payload was accepted")))
    (setq nelisp-stdlib-cl-type-lambda--forms old)))
(let ((old (symbol-function 'nelisp-bytecode-compiler-input-dialect)) refused)
  (unwind-protect
      (progn
        (fset 'nelisp-bytecode-compiler-input-dialect (lambda () '(:status unknown)))
        (condition-case nil (nelisp-stdlib-cl-type-lambda-install)
          (error (setq refused t)))
        (unless refused (error "Changed evidence owner was accepted")))
    (fset 'nelisp-bytecode-compiler-input-dialect old)))
(princ "GNU-CL-TYPE-LAMBDA-PROVIDER-PASS\n")
