;;; standalone-keymapp-symbol.el --- Genuine prefix/autoload classification -*- lexical-binding: t; -*-
(let ((map (make-sparse-keymap))
      (command (make-symbol "keymapp-prefix-probe"))
      (alias (make-symbol "keymapp-alias-probe"))
      (unbound (make-symbol "keymapp-unbound-probe"))
      (ordinary (make-symbol "keymapp-function-probe"))
      (variable (make-symbol "keymapp-variable-probe"))
      (autoload-map (make-symbol "keymapp-autoload-probe"))
      (autoload-function (make-symbol "keymapp-autoload-function-probe")))
  (fset command map)
  (fset alias command)
  (fset ordinary (lambda () nil))
  (set variable map)
  (fset autoload-map '(autoload "missing-keymap-probe" nil nil keymap))
  (fset autoload-function '(autoload "missing-function-probe" nil nil nil))
  (dolist (object (list map command alias autoload-map))
    (unless (eq (keymapp object) t) (error "Genuine keymap form rejected: %S" object)))
  (dolist (object (list nil 1 [97] '(lambda () nil) ordinary variable unbound autoload-function
                       '(autoload "missing-keymap-probe" nil nil keymap)))
    (when (keymapp object) (error "Non-keymap object accepted: %S" object)))
  (unless (and (equal (symbol-function autoload-map)
                     '(autoload "missing-keymap-probe" nil nil keymap))
               (not (featurep 'missing-keymap-probe)))
    (error "Keymap classification loaded an autoload"))
  (define-key map [98 99] 'keymapp-probe-action)
  (unless (eq (lookup-key alias [98 99]) 'keymapp-probe-action)
    (error "Alias keymap lookup differs")))
(when (eq (plist-get (nelisp-bytecode-compiler-input-dialect) :runtime-evidence)
          'standalone-build-verified)
 (dolist (reader '(symbol-function fboundp))
  (let ((saved (symbol-function reader)) (refused nil))
    (unwind-protect
        (progn
          (fset reader (lambda (&rest _args) nil))
          (condition-case nil (keymapp '(keymap))
            (error (setq refused t)))
          (unless refused (error "Changed function-cell reader admitted")))
      (fset reader saved)))))
(let ((one (make-symbol "keymapp-cycle-one"))
      (two (make-symbol "keymapp-cycle-two")))
  (dolist (edge (list (cons one one)))
    (unless (eq (condition-case condition
                    (progn (fset (car edge) (cdr edge)) (keymapp (car edge)) nil)
                  (cyclic-function-indirection (car condition)))
                'cyclic-function-indirection)
      (error "Self function cycle was not rejected")))
  (fset one two)
  (unless (eq (condition-case condition (progn (fset two one) (keymapp two) nil)
                (cyclic-function-indirection (car condition)))
              'cyclic-function-indirection)
    (error "Two-symbol function cycle was not rejected")))
(princ "KEYMAPP-SYMBOL-PASS\n")
