;;; standalone-prefix-command.el --- GNU prefix command cell semantics -*- lexical-binding: t; -*-
(let ((command (make-symbol "prefix-command-probe"))
      (mapvar (make-symbol "prefix-map-probe")))
  (unless (eq (define-prefix-command command) command)
    (error "Prefix command return differs"))
  (unless (and (keymapp (symbol-function command))
               (eq (symbol-value command) (symbol-function command)))
    (error "Prefix command function/value cells differ"))
  (let ((original (symbol-value command)))
    (unless (eq (define-prefix-command command mapvar "Prefix Probe") command)
      (error "Named prefix command return differs"))
    (unless (and (eq original (symbol-value command))
                 (eq (symbol-value mapvar) (symbol-function command))
                 (equal (keymap-prompt (symbol-value mapvar)) "Prefix Probe"))
      (error "Optional map variable/prompt semantics differ")))
  (define-key (symbol-value mapvar) [97] 'probe-action)
  (unless (eq (lookup-key (symbol-function command) [97]) 'probe-action)
    (error "Prefix command keymap binding differs")))
(let ((refused nil))
  (condition-case nil (define-prefix-command 1)
    (wrong-type-argument (setq refused t)))
  (unless refused (error "Nonsymbol prefix command admitted")))
(when (eq (plist-get (nelisp-bytecode-compiler-input-dialect) :runtime-evidence)
          'standalone-build-verified)
  (let ((saved (symbol-function 'define-prefix-command)) (refused nil))
    (unwind-protect
        (progn
          (fset 'define-prefix-command (lambda (&rest _args) nil))
          (condition-case nil
              (nelisp-stdlib-derived-parent-install (getenv "NELISP_GNU_BUILD_SOURCE_ROOT"))
            (error (setq refused t)))
          (unless refused (error "Changed prefix command owner admitted")))
      (fset 'define-prefix-command saved))))
(princ "PREFIX-COMMAND-PASS\n")
