;;; standalone-native-template-handler-cycle.el --- Poll-only exceptional cycles -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'cl-lib)
(defvar template-cycle-calls 0)
(defvar template-cycle-mode nil)
(defun template-cycle-callback ()
  (setq template-cycle-calls (1+ template-cycle-calls))
  (garbage-collect)
  (cond ((and (eq template-cycle-mode 'throw) (< template-cycle-calls 3))
         (throw 'tag 'tag))
        ((and (eq template-cycle-mode 'quit) (= template-cycle-calls 1))
         (setq quit-flag t) 'first)
        (t 'done)))
(if (getenv "TEMPLATE_CYCLE_HOST")
    (let ((template-cycle-mode 'throw) (template-cycle-calls 0))
      (unless (and (eq (funcall (make-byte-code 0 (unibyte-string 192 50 1 0 193 32 48 135)
                                               [tag template-cycle-callback] 2)) 'done)
                   (= template-cycle-calls 3))
        (error "GNU exceptional cycle control failed"))
      (princ "TEMPLATE-HANDLER-CYCLE-GNU-PASS calls=3\n"))
  (require 'nelisp-native-cache)
  (let* ((nelisp-native-cache-backend 'template)
         (factory (symbol-function 'nelisp-bytecode-native-rooted-cfg-poll-function))
         (frozen (funcall factory)) (polls 0) (requests 0))
    (unwind-protect
        (progn
          ;; Instrumentation delegates to the ORIGINAL frozen quit/GC poll.
          (fset 'nelisp-bytecode-native-rooted-cfg-poll-function
                (lambda () (lambda () (setq polls (1+ polls))
                             (let ((request (funcall frozen)))
                               (when request (setq requests (1+ requests))) request))))
          (dolist (mode '(throw quit))
            (let* ((template-cycle-mode mode) (template-cycle-calls 0)
                   (polls-before polls) (requests-before requests)
                   (entries-before nelisp-native-template--entry-count)
                   (function (make-byte-code 0 (unibyte-string 192 (if (eq mode 'throw) 50 49)
                                                             1 0 193 32 48 135)
                                              (vector (if (eq mode 'throw) 'tag t) 'template-cycle-callback) 2))
                   (_file (nelisp-native-cache-compile function))
                   (validations nelisp-native-template--validation-count)
                   (native (nelisp-native-cache-load function)) (result (funcall native)))
              (unless (and (eq result 'done) (= (- nelisp-native-template--entry-count entries-before) 1)
                           (= validations nelisp-native-template--validation-count)
                           (= template-cycle-calls (if (eq mode 'throw) 3 2))
                           (> (- polls polls-before) template-cycle-calls)
                           (or (eq mode 'throw) (= (- requests requests-before) 1)))
                (error "Exceptional poll cycle failed mode=%S calls=%d polls=%d requests=%d result=%S"
                       mode template-cycle-calls (- polls polls-before) (- requests requests-before) result))
              (princ (format "TEMPLATE-HANDLER-CYCLE-PASS mode=%S calls=%d polls=%d requests=%d entries=1 gc=forced\n"
                             mode template-cycle-calls (- polls polls-before) (- requests requests-before))))))
      (fset 'nelisp-bytecode-native-rooted-cfg-poll-function factory))))
