;;; standalone-native-real-corpus-driver.el --- Real GNU .elc parity -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'nelisp-native-cache)
(load "test/support/native-entry-observer.el" nil t t)
(load (expand-file-name "test/support/native-real-corpus-inputs.el") nil t t)
(load (expand-file-name (or (getenv "F3_FIXTURE") "test/support/native-real-corpus-fixtures.el")) nil t t)
(defun f3-assert (value label) (unless value (error "F3: %s" label)))
(defun f3-observe (function arguments)
  (f3-real-corpus-observe function arguments))
(let ((nelisp-native-cache-backend (intern (getenv "F3_BACKEND")))
      (phase (getenv "F3_PHASE")) (count 0) (failed 0))
  (dolist (name (mapcar #'intern (split-string (getenv "F3_NAMES"))))
    (let* ((row (cl-find name f3-real-corpus :key (lambda (item) (plist-get item :name))))
           (function (plist-get row :function)) (stage "identity") (cases 0) (entries 0)
           (start (float-time)))
      (princ (format "F3-START backend=%s name=%s phase=%s\n" nelisp-native-cache-backend name phase))
      (condition-case condition
          (progn
            (f3-assert (and row function (or (equal (getenv "F3_REPRODUCE") "1") (not (plist-get row :excluded)))) "admitted fixture")
            (f3-assert (equal (secure-hash 'sha256 (nelisp-native-cache--print function))
                              (plist-get row :bytecode-sha256)) "byte-code pin")
            ;; Test the standalone GNU VM first; its definition is never replaced.
            (setq stage "interpreter")
            (dolist (test (plist-get row :cases))
              (let ((actual (f3-observe function (plist-get test :args))))
                (f3-assert (equal actual (plist-get test :gnu))
                           (format "%s input=%S GNU=%S VM=%S" name (plist-get test :args) (plist-get test :gnu) actual))))
            (setq stage phase)
            (when (equal phase "compile")
              (let* ((file (nelisp-native-cache-file function))
                     (hit (and (file-exists-p file)
                               (or (not (eq nelisp-native-cache-backend 'gccjit))
                                   (file-exists-p (concat file ".nelh"))))))
                (when (equal (getenv "F3_FRESH") "1")
                  (f3-assert (not hit) "fresh compilation"))
                (princ (format "F3-CACHE backend=%s name=%s status=%s\n"
                               nelisp-native-cache-backend name (if hit "hit" "miss"))))
              (nelisp-native-cache-compile function)
              (princ (format "F3-CACHE-FILE name=%s file=%s\n" name (nelisp-native-cache-file function))))
            (let* ((before nelisp-bytecode-native-rooted-cfg-contract--validation-count)
                   (outer nelisp-native-load--rooted-cfg-outer-validation-count)
                   (maps 0)
                   (trusted (symbol-function 'nelisp-native-load-raw-v2-artifact-trusted))
                   (dynamic (symbol-function 'nelisp-native-cache--load-gccjit))
                   (native
                    (cl-letf (((symbol-function 'nelisp-native-cache-compile)
                               (lambda (&rest _) (error "F3 cache load attempted compilation")))
                              ((symbol-function 'nelisp-native-load-raw-v2-artifact-trusted)
                               (lambda (&rest args) (setq maps (1+ maps)) (apply trusted args)))
                              ((symbol-function 'nelisp-native-cache--load-gccjit)
                               (lambda (&rest args) (setq maps (1+ maps)) (apply dynamic args))))
                      (nelisp-native-cache-load function)))
                   (file (nelisp-native-cache-file function))
                   (header (with-temp-buffer
                             (insert-file-contents (if (eq nelisp-native-cache-backend 'gccjit) (concat file ".nelh") file))
                             (goto-char (point-min)) (read (current-buffer))))
                   (roots (plist-get header :root-count))
                   (arity (plist-get header :arity)))
              (f3-assert native "fresh-process cache hit")
              (f3-assert (= maps 1) "one trusted mapper")
              (f3-assert (and (= before nelisp-bytecode-native-rooted-cfg-contract--validation-count)
                              (= outer nelisp-native-load--rooted-cfg-outer-validation-count)) "zero load validations")
              (setq stage "native")
              (dolist (test (plist-get row :cases))
                (let* ((arguments (plist-get test :args))
                       (expected (f3-observe function arguments))
                       (entry-before entries)
                       (actual
                        (nelisp-test-with-native-entry-observer
			    (lambda (address env ticket argc count x y)
			      (when (and (= argc arity) (= count roots) (= x 0) (= y 0))
				(setq entries (1+ entries))))
			  (f3-observe native arguments))))
                  (f3-assert (equal expected actual)
                             (format "%s input=%S VM=%S native=%S" name arguments expected actual))
                  (f3-assert (equal actual (plist-get test :gnu)) "recorded GNU result")
                  (f3-assert (= (- entries entry-before) 1) "one machine entry per call; no fallback")
                  (setq cases (1+ cases))))
              (setq count (1+ count))
              (princ (format "F3-FUNCTION-PASS backend=%s name=%s phase=%s cases=%d native-entries=%d validations=0 seconds=%.3f\n"
                             nelisp-native-cache-backend name phase cases entries (- (float-time) start)))))
        (error (setq failed (1+ failed))
               (princ (format "F3-FUNCTION-FAIL backend=%s name=%s phase=%s stage=%s reason=%S\n"
                              nelisp-native-cache-backend name phase stage condition))))))
  (princ (format "F3-BATCH-DONE backend=%s phase=%s functions=%d failed=%d\n" nelisp-native-cache-backend phase count failed)))
