;;; standalone-native-frame-u7a-driver.el --- U7a native parity -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'nelisp-native-cache)
(load "test/support/native-entry-observer.el" nil t t)
(defvar u7a-origin (float-time))
(defun u7a-phase (name)
  (princ (format "U7A-PHASE %s seconds=%.3f\n" name (- (float-time) u7a-origin))))
(load "test/support/native-frame-u7a-fixtures.el" nil t t)
(defun u7a-assert (value label) (unless value (error "U7a: %s" label)))
(let* ((nelisp-native-cache-backend (intern (getenv "U7A_BACKEND")))
       (phase (or (getenv "U7A_PHASE") "compile"))
       (case-name (getenv "U7A_CASE"))
       (name (if (string-match-p "^[1-5]$" case-name) (string-to-number case-name) (intern case-name)))
       (fn (native-frame-u7a-function name))
       (cases 0) (entries 0)
       (args (cond ((eq name 'nested) '(outer inner))
                   ((or (integerp name) (eq name 'zero)) nil) (t '(inside)))))
  (princ (format "U7A-START backend=%S fixture=%S\n" nelisp-native-cache-backend name))
  (u7a-phase "before-install")
  (u7a-assert (member phase '("compile" "load")) "phase")
  (if (equal phase "load")
      (cl-letf (((symbol-function 'nelisp-native-cache-compile)
                 (lambda (&rest _) (error "U7a warm recompiled"))))
        (nelisp-native-cache-install 'u7a-native fn))
    (nelisp-native-cache-install 'u7a-native fn))
  (princ (format "U7A-COMPILED fixture=%S\n" name))
  (u7a-phase "after-install")
  (let* ((file (nelisp-native-cache-file fn))
         (header (with-temp-buffer
                   (insert-file-contents (if (eq nelisp-native-cache-backend 'gccjit) (concat file ".nelh") file))
                   (goto-char (point-min)) (read (current-buffer))))
         (count (plist-get header :root-count)) (arity (plist-get header :arity))
         (native (symbol-function 'u7a-native)))
    (cl-labels ((run ()
                  (nelisp-test-with-native-entry-observer
		      (lambda (address env ticket argc roots x y)
			(when (and (= argc arity) (= roots count) (= x 0) (= y 0))
			  (setq entries (1+ entries))))
		    (native-frame-u7a-observe native args)))
               (compare ()
                 (let ((expected (let ((u7a-inner (if (eq u7a-mode 'reenter) fn u7a-inner)))
                                   (native-frame-u7a-observe fn args))))
                   (u7a-assert (equal expected (run)) (format "parity expected=%S" expected)))
                 (setq cases (1+ cases))
                 (princ (format "U7A-PARITY fixture=%S case=%d\n" name cases))))
      (setq u7a-special 'outside u7a-mode nil)
      (when (eq name 'alias) (defvaralias 'u7a-alias 'u7a-target))
      (compare)
      ;; A caller's dynamic binding is never popped by the native epilogue.
      (let ((u7a-special 'caller)) (compare) (u7a-assert (eq u7a-special 'caller) "caller watermark"))
      (when (eq name 'callback)
        (dolist (mode '(throw signal)) (setq u7a-mode mode) (compare))
        (setq u7a-mode nil)
        (makunbound 'u7a-special) (compare)
        (u7a-assert (not (boundp 'u7a-special)) "void state restored")
        (setq u7a-special 'outside)
        (setq u7a-inner native u7a-mode 'reenter) (compare)
        (setq u7a-mode nil)
        (princ (format "U7A-CAPABILITIES watchers=%S\n" (fboundp 'add-variable-watcher))))
      (when (eq name 'buffer-local)
        (let ((other (generate-new-buffer " u7a-other")))
          (unwind-protect
              (progn
                (with-current-buffer other
                  (set (make-local-variable 'u7a-special) 'other-local))
                (let ((u7a-other-buffer other) (u7a-mode 'switch-read))
                  ;; Each run mutates the other local; reset both oracle and
                  ;; candidate to the same initial state before invoking them.
                  (let ((expected (native-frame-u7a-observe fn args)))
                    (u7a-assert (equal expected '((returned inside) (inside other-local other-changed) outside))
                                "GNU31 local cell wins over dynamic default in another buffer")
                    (with-current-buffer other (set 'u7a-special 'other-local))
                    (u7a-assert (equal expected (run)) "buffer-switch native parity")
                    (setq cases (1+ cases))))
                (with-current-buffer other (kill-local-variable 'u7a-special))
                (with-temp-buffer
                (set (make-local-variable 'u7a-special) 'local)
                (u7a-assert (local-variable-p 'u7a-special) "real local cell")
                (u7a-assert (eq (default-value 'u7a-special) 'outside) "default distinct from local")
                (dolist (mode '(nil throw signal))
                  (setq u7a-mode mode) (compare)
                  (u7a-assert (eq u7a-special 'local) "local restored after normal/throw/signal")
                  (u7a-assert (eq (default-value 'u7a-special) 'outside) "default preserved on exit"))
                (let ((u7a-special 'local-caller))
                  (compare)
                  (u7a-assert (eq u7a-special 'local-caller) "local caller binding preserved"))
                (with-current-buffer other
                  (u7a-assert (not (local-variable-p 'u7a-special)) "other buffer not local")
                  (u7a-assert (eq u7a-special 'outside) "other buffer default"))
                ;; A void local must remain local and void after a throw.
                (makunbound 'u7a-special)
                (setq u7a-mode 'throw) (compare)
                (u7a-assert (and (local-variable-p 'u7a-special) (not (boundp 'u7a-special)))
                            "void local restored")
                (set 'u7a-special 'local)
                (kill-local-variable 'u7a-special)
                (u7a-assert (and (not (local-variable-p 'u7a-special)) (eq u7a-special 'outside))
                            "local removal reveals default")))
            (kill-buffer other)))
        (setq u7a-mode nil))
      (when (eq name 'watcher)
        ;; GNU 31.1's ordered oracle is asserted in host ERT. This interpreter
        ;; has no add-variable-watcher, so qualify that limitation explicitly
        ;; and compare native behavior with the actual interpreter, not GNU.
        (u7a-assert (not (fboundp 'add-variable-watcher)) "watcher limitation changed; extend parity")
        (dolist (mode '(throw signal)) (setq u7a-mode mode) (compare))
        (setq u7a-mode nil)
        (princ "U7A-WATCHER unsupported-interpreter GNU31.1-normal-and-throw=(let set)\n"))
      (when (eq name 'alias)
        (u7a-assert (eq u7a-target 'outside) "canonical alias target restored")
        (defvaralias 'u7a-middle 'u7a-target)
        (defvaralias 'u7a-alias 'u7a-middle)
        (compare)
        (u7a-assert (eq u7a-target 'outside) "alias chain restored")
        (makunbound 'u7a-target)
        (compare)
        (u7a-assert (not (boundp 'u7a-target)) "void alias target restored"))
      (when (memq name '(implicit set))
        (cl-labels ((poisoned ()
          (let ((set-cell (symbol-function 'set)) (value-cell (symbol-function 'symbol-value))
              (restore (symbol-function 'fset))
              (expected (native-frame-u7a-observe fn args)))
          (u7a-assert
           (equal expected
                  (native-frame-u7a-observe
                   (lambda (&rest arguments)
                     (unwind-protect
                         (progn
                           (funcall restore 'set (lambda (&rest _) (error "poisoned set")))
                           (funcall restore 'symbol-value (lambda (&rest _) (error "poisoned symbol-value")))
                           (apply native arguments))
                       (funcall restore 'set set-cell)
                       (funcall restore 'symbol-value value-cell))) args))
           "frozen varref/varset providers"))))
          (poisoned)
          (when (eq name 'implicit)
            (with-temp-buffer
              (set (make-local-variable 'u7a-special) 'local)
              (poisoned)
              (u7a-assert (eq u7a-special 'local) "poisoned local specbind restored")))))
      (u7a-assert (= entries (+ cases (if (eq name 'callback) 1 0))) "actual native entry per case and reentrant call")
      (u7a-assert (eq u7a-special 'outside) "outside value restored")
      ;; The separate load process forbids compilation on its first install.
      (when (eq name 'implicit)
        ;; Matched census body: one varbind, varref and implicit leave.
        ;; Measure the same arguments on the VM and the machine entry.
        (let ((iterations 200) before after start)
          (setq start (float-time))
          (dotimes (_ iterations) (funcall fn 'inside))
          (setq before (/ (* 1000000000.0 (- (float-time) start)) iterations)
                start (float-time))
          (dotimes (_ iterations) (funcall native 'inside))
          (setq after (/ (* 1000000000.0 (- (float-time) start)) iterations))
          (u7a-assert (eq u7a-special 'outside) "timed calls restore binding")
          (princ (format "U7A-TIMING iterations=%d interpreter-ns=%.0f native-ns=%.0f\n"
                         iterations before after))))
      (princ (format "U7A-NATIVE-PASS backend=%S fixture=%S cases=%d native-entries=%d phase=%s\n"
                     nelisp-native-cache-backend name cases entries phase)))))
(when (equal (getenv "U7A_CASE") "callback")
  (let* ((addresses (nelisp-native-load-root-v2-addresses))
         (env (plist-get addresses :environment))
         (bridge (nelisp-native-load--symbol-addr "nl_native_frame_v2"))
         (ticket (ptr-call (plist-get addresses :begin) env 0 0 0 0 0)))
    (unwind-protect
        (progn
          (dotimes (_ 8) (ptr-call (plist-get addresses :reserve) env ticket 0 0 0 0))
          (nelisp--native-pin-copy-v2 env ticket 1 (nelisp-native-frame-v2-initializer))
          (nelisp--native-pin-copy-v2 env ticket 2 1)
          (nelisp--native-pin-copy-v2 env ticket 3 0)
          (u7a-assert (= (ptr-call bridge env (1+ ticket) 1 0 2 4) 2) "stale ticket refused")
          (u7a-assert (= (ptr-call bridge env ticket 1 0 1 4) 2) "state/operand overlap refused")
          (u7a-assert (= (ptr-call bridge env ticket 1 99 2 4) 2) "unknown action refused")
          (u7a-assert (= (ptr-call bridge env ticket 1 0 2 4) 0) "direct enter")
          (u7a-assert (= (ptr-call bridge env ticket 1 2 2 4) 1029) "unbind underflow publishes signal")
          (u7a-assert (= (ptr-call bridge env ticket 1 3 2 4) 0) "underflow did not consume caller state")
          (u7a-assert (= (ptr-call bridge env ticket 1 3 2 4) 1029) "double leave publishes ownership error")
          (princ "U7A-AUTH-PASS stale=1 overlap=1 unknown=1 underflow=1 double-leave=1\n"))
      (u7a-assert (= (ptr-call (plist-get addresses :end) env ticket 0 0 0 0) 1) "probe ticket restored"))))
