;;; standalone-native-cdr-v2-driver.el --- Authenticated CDR smoke -*- lexical-binding: t; -*-

(require 'nelisp-native-load)

(defun nelisp-test-native-cdr-v2-smoke ()
  (let* ((env (nelisp--native-env))
         (begin-addr (nelisp-native-load--symbol-addr "nl_root_pin_begin_v2"))
         (reserve-addr (nelisp-native-load--symbol-addr "nl_root_pin_reserve_v2"))
         (end-addr (nelisp-native-load--symbol-addr "nl_root_pin_end_v2"))
         (cons-addr (nelisp-native-load--symbol-addr "nl_native_cons_v2"))
         (cdr-addr (nelisp-native-load--symbol-addr "nl_native_cdr_v2"))
         (ticket (ptr-call begin-addr env 0 0 0 0 0))
         (leaf (ptr-call reserve-addr env ticket 0 0 0 0))
         (tail (ptr-call reserve-addr env ticket 0 0 0 0))
         (head (ptr-call reserve-addr env ticket 0 0 0 0))
         (inner (ptr-call reserve-addr env ticket 0 0 0 0))
         (outer (ptr-call reserve-addr env ticket 0 0 0 0))
         (result (ptr-call reserve-addr env ticket 0 0 0 0))
         (nil-input (ptr-call reserve-addr env ticket 0 0 0 0))
         (wrong-input (ptr-call reserve-addr env ticket 0 0 0 0))
         (status nil) (nil-status nil) (wrong-status nil)
         (identity-before nil) (gc nil) (identity-after nil)
         (nil-result-tag nil)
         (bad-input nil) (bad-output nil) (unchanged nil)
         (stale-ticket ticket) (ended nil) (next-ticket nil)
         (next-output nil) (stale-status nil) (stale-unchanged nil)
         (next-end nil))
    (nelisp-native-load-box leaf "tail leaf")
    (nelisp-native-load-box tail nil)
    (nelisp-native-load-box head 17)
    (setq status (ptr-call cons-addr env ticket 0 1 3 0))
    (setq status (and (= status 0)
                      (= (ptr-call cons-addr env ticket 2 3 4 0) 0)))
    (nelisp-native-load-box nil-input nil)
    (nelisp-native-load-box wrong-input "not a cons")
    (setq status (and status (= (ptr-call cdr-addr env ticket 4 5 0 0) 0)))
    (setq identity-before
          (and (= (ptr-read-u64 result 0) 7)
               (= (ptr-read-u64 result 8) (ptr-read-u64 inner 8))))
    (setq gc (garbage-collect))
    (setq identity-after
          (and (= (ptr-read-u64 result 0) 7)
               (= (ptr-read-u64 result 8) (ptr-read-u64 inner 8))))
    (setq nil-status (ptr-call cdr-addr env ticket 6 5 0 0))
    (setq nil-result-tag (ptr-read-u64 result 0))
    (nelisp-native-load-box result 777)
    (setq wrong-status (ptr-call cdr-addr env ticket 7 5 0 0))
    (setq unchanged (and (= (ptr-read-u64 result 0) 2)
                         (= (ptr-read-u64 result 8) 777)))
    (setq bad-input (ptr-call cdr-addr env ticket -1 5 0 0))
    (setq bad-output (ptr-call cdr-addr env ticket 3 16384 0 0))
    (setq unchanged (and unchanged (= (ptr-read-u64 result 0) 2)
                         (= (ptr-read-u64 result 8) 777)))
    (setq ended (ptr-call end-addr env ticket 0 0 0 0))
    (setq next-ticket (ptr-call begin-addr env 0 0 0 0 0))
    (setq next-output (ptr-call reserve-addr env next-ticket 0 0 0 0))
    (nelisp-native-load-box next-output 888)
    (setq stale-status (ptr-call cdr-addr env stale-ticket 4 0 0 0))
    (setq stale-unchanged (and (= (ptr-read-u64 next-output 0) 2)
                               (= (ptr-read-u64 next-output 8) 888)))
    (setq next-end (ptr-call end-addr env next-ticket 0 0 0 0))
    (and (> ticket 0) status identity-before gc identity-after
         (= nil-status 0) (= nil-result-tag 0)
         (= wrong-status 1) unchanged (= bad-input 2) (= bad-output 2)
         (= ended 1) (= stale-status 2) stale-unchanged (= next-end 1))))

(provide 'standalone-native-cdr-v2-driver)

;;; standalone-native-cdr-v2-driver.el ends here
