;;; standalone-match-state.el --- Genuine public setter and restoration regression -*- lexical-binding: t; -*-
(require 'nelisp-stdlib-match-state)
(let ((old-set (and (fboundp 'set-match-data) (symbol-function 'set-match-data)))
      (old-get (symbol-function 'match-data)))
  (when (eq (nelisp-stdlib-match-state-install) 'preserved)
    (unless (and (eq old-set (symbol-function 'set-match-data))
                 (eq old-get (symbol-function 'match-data)))
      (error "GNU match-state cells changed"))))
(dolist (case '((nil nil) ((1 3) (1 3)) ((1) nil)
                ((nil 3) nil) ((-1 3) nil) ((3 1) (3 1))
                ((1 2 3) (1 2)) ((1 2 nil nil) (1 2))
                ((1 -1) (1 -1)) ((nil anything) nil)))
  (unless (and (null (set-match-data (car case)))
               (equal (match-data t) (cadr case)))
    (error "Match list shape differs: %S" case)))
(dolist (case '(((1 nil) integer-or-marker-p) ((a 3) integer-or-marker-p)
                ((1.2 3) integer-or-marker-p) ([1 2] listp)
                (3 listp) ((1 2 . tail) listp)))
  (let (condition)
    (condition-case error (set-match-data (car case))
      (wrong-type-argument (setq condition error)))
    (unless (and condition (eq (cadr condition) (cadr case)))
      (error "Match setter type condition differs: %S => %S" case condition))))
(let ((dead (make-marker)))
  (set-match-data (list dead dead))
  (unless (equal (match-data t) '(0 0)) (error "Dead marker conversion differs")))
(with-temp-buffer
  (insert "abcdef")
  (let ((begin (copy-marker 2)) (end (copy-marker 4))
        (buffer (current-buffer)))
    (set-match-data (list begin end) t)
    (unless (and (equal (match-data t) (list 2 4 buffer))
                 (null (marker-position begin)) (null (marker-position end))
                 (= (match-beginning 0) 2) (= (match-end 0) 4))
      (error "Marker-origin state or RESEAT differs"))
    (let ((reuse (list nil nil nil nil)))
      (unless (and (eq (match-data nil reuse) reuse)
                   (= (marker-position (car reuse)) 2)
                   (= (marker-position (cadr reuse)) 4)
                   (equal (cddr reuse) '(nil nil)))
        (error "Actual marker reuse differs")))
    (set-match-data '(1 3))
    (unless (equal (save-match-data (string-match "b" "abc") 'normal) 'normal)
      (error "Save match normal body value differs"))
    (unless (equal (match-data t) '(1 3)) (error "Normal unwind lost match state"))
    (condition-case nil
        (save-match-data (string-match "c" "abc") (error "Expected"))
      (error nil))
    (unless (equal (match-data t) '(1 3)) (error "Error unwind lost match state"))
    (catch 'expected (save-match-data (string-match "a" "abc") (throw 'expected t)))
    (unless (equal (match-data t) '(1 3)) (error "Throw unwind lost match state"))))
(princ "PUBLIC-MATCH-STATE-PASS\n")
