#!/usr/bin/env bash
set -euo pipefail

binary_arg=${1:-target/nelisp}
minimal_runs=${2:-2}
stress_runs=${3:-2}
root=$(cd "$(dirname "$0")/.." && pwd)
cd "$root"

if [[ ! -x "$binary_arg" ]]; then
  echo "standalone-bytecode-jit-zeroarg-stress: binary is not executable: $binary_arg" >&2
  exit 2
fi
for count in "$minimal_runs" "$stress_runs"; do
  if [[ ! "$count" =~ ^[1-9][0-9]*$ ]]; then
    echo "standalone-bytecode-jit-zeroarg-stress: run counts must be positive integers" >&2
    exit 2
  fi
done
direct_runs=${NELISP_JIT_STRESS_DIRECT_RUNS:-0}
if [[ ! "$direct_runs" =~ ^(0|[1-9][0-9]*)$ ]]; then
  echo "standalone-bytecode-jit-zeroarg-stress: direct run count must be zero or a positive integer" >&2
  exit 2
fi
timeout_seconds=${NELISP_JIT_STRESS_TIMEOUT_SECONDS:-90}
if [[ ! "$timeout_seconds" =~ ^[1-9][0-9]*$ ]]; then
  echo "standalone-bytecode-jit-zeroarg-stress: timeout must be a positive integer" >&2
  exit 2
fi

artifact_dir=${NELISP_JIT_STRESS_ARTIFACT_DIR:-"$root/target/zeroarg-jit-stress-$(date -u +%Y%m%dT%H%M%SZ)-$$"}
if [[ -e "$artifact_dir/nelisp.snapshot" ]]; then
  echo "standalone-bytecode-jit-zeroarg-stress: artifact directory already contains a binary snapshot: $artifact_dir" >&2
  exit 2
fi
mkdir -p "$artifact_dir/cores"
artifact_dir=$(cd "$artifact_dir" && pwd)
binary="$artifact_dir/nelisp.snapshot"
cp -- "$binary_arg" "$binary"
chmod 0555 "$binary"
binary_sha=$(sha256sum "$binary" | awk '{print $1}')

nelisp_root_value=${NELISP_ROOT:-<unset>}
if [[ -n "${NELISP_ROOT:-}" ]]; then
  source_root_kind=NELISP_ROOT
  source_root_input=$NELISP_ROOT
else
  source_root_kind=harness-root-default
  source_root_input=$root
fi
if [[ -d "$source_root_input" ]]; then
  source_root_candidate=$(cd -- "$source_root_input" && pwd -P)
else
  source_root_candidate="<unresolved:$source_root_input>"
fi
hash_source_file() {
  local path=$1
  if [[ -f "$path" ]]; then
    sha256sum "$path" | awk '{print $1}'
  else
    printf 'missing\n'
  fi
}
source_sha_aot_compiler=$(hash_source_file "$source_root_candidate/lisp/nelisp-aot-compiler.el")
source_sha_artifact=$(hash_source_file "$source_root_candidate/lisp/nelisp-artifact.el")
source_sha_bytecode_jit=$(hash_source_file "$source_root_candidate/lisp/nelisp-bytecode-jit.el")
source_sha_stdlib_prelude=$(hash_source_file "$source_root_candidate/scripts/nelisp-stdlib-prelude.el")

minimal_expr='(let* ((function (make-byte-code 0 (unibyte-string 192 135) [nil] 1)))
  (require (quote nelisp-bytecode-jit))
  (setq nelisp-bytecode-jit-threshold 3)
  (let* ((a (funcall function)) (b (funcall function)) (c (funcall function)))
    (let ((status (nelisp-bytecode-jit-status)))
      (let ((result
             (list (null a) (null b) (null c)
                   (= (plist-get status :native-calls) 1)
                   (= (plist-get status :interpreter-fallbacks) 2))))
        (unless (equal result (quote (t t t t t)))
          (princ (format "jit-status=%S\n" status)))
        result))))'
stress_expr='(progn
    (require (quote nelisp-bytecode-jit))
    (require (quote cl-lib))
    (setq nelisp-bytecode-jit-threshold 3)
    (let* ((function (make-byte-code 0 (unibyte-string 192 135) [nil] 1))
           (first (nelisp-bytecode-jit--runtime-dispatch function))
           (first-fallbacks (plist-get (nelisp-bytecode-jit-status) :interpreter-fallbacks)))
      (garbage-collect)
      (let* ((recursive-depth 0)
             (recursive-result (quote unobserved))
             (recursive-counts-clean nil)
             (original-decode-ir
              (symbol-function (quote nelisp-bytecode-jit--decode-ir)))
             (error-caught
             (condition-case nil
                 (progn
                   (cl-letf (((symbol-function (quote nelisp-bytecode-jit--decode-ir))
                              (lambda (candidate)
                                (setq recursive-depth (1+ recursive-depth))
                                (when (> recursive-depth 4)
                                  (error "bounded guarded recursion"))
                                (let ((attempts nelisp-bytecode-jit--dispatch-attempt-count)
                                      (native-calls nelisp-bytecode-jit--native-call-count))
                                  (setq recursive-result
                                        (nelisp-bytecode-jit--runtime-dispatch function))
                                  (setq recursive-counts-clean
                                        (and (= attempts nelisp-bytecode-jit--dispatch-attempt-count)
                                             (= native-calls nelisp-bytecode-jit--native-call-count))))
                                (error "injected dispatcher failure"))))
                     (nelisp-bytecode-jit--runtime-dispatch function))
                   nil)
               (error t))))
      ;; cl-letf-generated bytecode helpers may be JIT-eligible; anchor reentry checks
      ;; after the injected-error setup instead of assuming absolute counters.
      (let* ((error-attempts nelisp-bytecode-jit--dispatch-attempt-count)
             (error-fallbacks nelisp-bytecode-jit--interpreter-fallback-count)
             (guard-clean (null nelisp-bytecode-jit--dispatch-active))
             (reentrant (let ((nelisp-bytecode-jit--dispatch-active t))
                          (nelisp-bytecode-jit--runtime-dispatch function)))
             (reentrant-attempts nelisp-bytecode-jit--dispatch-attempt-count)
             (reentrant-fallbacks nelisp-bytecode-jit--interpreter-fallback-count)
             (cold (funcall function))
             (cold-native-calls nelisp-bytecode-jit--native-call-count)
             (cold-fallbacks nelisp-bytecode-jit--interpreter-fallback-count))
        (garbage-collect)
        (let* ((hot (funcall function))
               (status (nelisp-bytecode-jit-status)))
          (let ((result
                 (list (null first) (= first-fallbacks 1) error-caught
                       (null recursive-result) (= recursive-depth 1)
                       recursive-counts-clean guard-clean
                       (null reentrant) (= reentrant-attempts error-attempts)
                       (= reentrant-fallbacks error-fallbacks)
                       (null cold) (= cold-native-calls 0)
                       (= cold-fallbacks (1+ error-fallbacks)) (null hot)
                       (= (plist-get status :native-calls) 1)
                       (= (plist-get status :interpreter-fallbacks)
                          cold-fallbacks))))
            (unless (equal result (quote (t t t t t t t t t t t t t t t t)))
                (princ (format "jit-status=%S\n" status)))
              ;; Run a bounded negative control with the active guard disabled only
              ;; around recursive entry. A missing guard must reach the depth cap.
              (let* ((mutant-depth 0)
                    (mutant-caught
                     (condition-case nil
                         (progn
                           (cl-letf (((symbol-function
                                       (quote nelisp-bytecode-jit--decode-ir))
                                      (lambda (candidate)
                                        (setq mutant-depth (1+ mutant-depth))
                                        (when (> mutant-depth 4)
                                          (error "bounded recursive mutant"))
                                        (let ((nelisp-bytecode-jit--dispatch-active nil))
                                          (nelisp-bytecode-jit--runtime-dispatch function))
                                        (funcall original-decode-ir candidate))))
                             (nelisp-bytecode-jit--runtime-dispatch function))
                           nil)
                       (error t))))
                (unless (and mutant-caught (= mutant-depth 5))
                  (princ (format "recursive-negative-control depth=%S caught=%S\n"
                                 mutant-depth mutant-caught)))
                (list result mutant-caught (= mutant-depth 5)))))))))'
negative_expr='(error "zeroarg stress negative control")'
direct_expr='(progn
  (require (quote nelisp-bytecode-jit))
  (let* ((function (make-byte-code 0 (unibyte-string 192 135) [nil] 1))
         (ir (nelisp-bytecode-jit--decode-ir function))
         (handle (nelisp-bytecode-jit--compile-ir function ir)))
    (list (nelisp-native-load-call handle nil)
          (plist-get handle :arity)
          (plist-get handle :param-repr)
          (plist-get handle :return-repr))))'

core_pattern=$(cat /proc/sys/kernel/core_pattern 2>/dev/null || true)
ulimit -c unlimited 2>/dev/null || true

success_output_is_expected() {
  local label=$1 out=$2 err=$3 output
  if grep -Fq 'nelisp: uncaught error:' "$err"; then
    return 1
  fi
  output=$(tail -n 1 "$out" 2>/dev/null || true)
  case "$label:$output" in
    minimal:'(t t t t t)'|\
    guarded:'((t t t t t t t t t t t t t t t t) t t)'|\
    direct-loader:'(nil 0 sexp-ptr raw-bool)') return 0 ;;
    *) return 1 ;;
  esac
}

capture_case() {
  local label=$1 run_index=$2 expression=$3 expected=$4
  local temp_dir run_dir out err status core_file record_dir binary_sha_after candidate_core
  local bind_trace_dir diagnostic_dir remaining_files
  temp_dir=$(mktemp -d "$artifact_dir/.capture.XXXXXX")
  run_dir="$artifact_dir/cwd/$label-$run_index"
  bind_trace_dir="$temp_dir/bind-trace"
  diagnostic_dir="$temp_dir/diagnostics"
  mkdir -p "$bind_trace_dir" "$diagnostic_dir"
  mkdir -p "$run_dir"
  for entry in vendor lisp scripts src packages target; do
    if [[ -e "$root/$entry" && ! -e "$run_dir/$entry" ]]; then
      ln -s "$root/$entry" "$run_dir/$entry"
    fi
  done
  out="$temp_dir/stdout"
  err="$temp_dir/stderr"
  if [[ "$label" == signal-control ]]; then
    if (cd "$run_dir"; { timeout --foreground "${timeout_seconds}s" env \
      NELISP_JIT_BIND_TRACE_DIR="$bind_trace_dir" \
      NELISP_JIT_DIAGNOSTIC_DIR="$diagnostic_dir" \
      bash -c 'kill -SEGV "$$"'; }) > "$out" 2> "$err"; then
      status=0
    else
      status=$?
    fi
  elif [[ "$label" == negative-control ]]; then
    if (cd "$run_dir"; { timeout --foreground "${timeout_seconds}s" env \
      NELISP_JIT_BIND_TRACE_DIR="$bind_trace_dir" \
      NELISP_JIT_DIAGNOSTIC_DIR="$diagnostic_dir" \
      bash -c '
        printf "negative-control marker\\n" > "$NELISP_JIT_BIND_TRACE_DIR/retention-marker"
        printf "negative-control marker\\n" > "$NELISP_JIT_DIAGNOSTIC_DIR/retention-marker"
        exec "$1" --eval "$2"
      ' bash "$binary" "$expression"; }) > "$out" 2> "$err"; then
      status=0
    else
      status=$?
    fi
  elif [[ "$label" == stderr-control ]]; then
    if (cd "$run_dir"; { timeout --foreground "${timeout_seconds}s" bash -c \
      'printf "(t t t t t)\\n"; printf "nelisp: uncaught error: injected\\n" >&2'; }) > "$out" 2> "$err"; then
      status=0
    else
      status=$?
    fi
  elif (cd "$run_dir"; { timeout --foreground "${timeout_seconds}s" env \
    NELISP_JIT_BIND_TRACE_DIR="$bind_trace_dir" \
    NELISP_JIT_DIAGNOSTIC_DIR="$diagnostic_dir" \
    "$binary" --eval "$expression"; }) > "$out" 2> "$err"; then
    status=0
  else
    status=$?
  fi
  local returncode signal_name
  returncode=$status
  if ((status == 124)); then
    signal_name=TIMEOUT
  elif ((status >= 128)); then
    signal_name=$(kill -l "$((status - 128))" 2>/dev/null || printf 'signal-%s' "$((status - 128))")
  else
    signal_name=none
  fi
  binary_sha_after=$(sha256sum "$binary" | awk '{print $1}')

  core_file=
  for candidate_core in "$run_dir"/core*; do
    if [[ -f "$candidate_core" ]]; then
      core_file="$artifact_dir/cores/$label-$run_index.core"
      mv -- "$candidate_core" "$core_file"
      break
    fi
  done

  local passed=0
  if [[ "$expected" == rejected-control && "$returncode" == 0 ]] \
      && [[ "$(tail -n 1 "$out" 2>/dev/null || true)" == '(t t t t t)' ]] \
      && grep -Fq 'nelisp: uncaught error:' "$err" \
      && ! success_output_is_expected minimal "$out" "$err"; then
    passed=1
  elif [[ "$binary_sha_after" == "$binary_sha" && "$expected" == success && "$returncode" == 0 ]] \
      && success_output_is_expected "$label" "$out" "$err"; then
    passed=1
  elif [[ "$binary_sha_after" == "$binary_sha" && "$expected" == failure && "$returncode" == 1 && "$signal_name" == none ]] && grep -Fq 'zeroarg stress negative control' "$err"; then
    if [[ "$label" == negative-control \
          && -f "$bind_trace_dir/retention-marker" \
          && -f "$diagnostic_dir/retention-marker" ]]; then
      passed=1
    fi
  elif [[ "$binary_sha_after" == "$binary_sha" && "$label" == signal-control && "$expected" == signal && "$status" == 139 && "$signal_name" == SEGV ]]; then
    passed=1
  fi

  if [[ "$expected" == success && "$passed" == 1 ]]; then
    remaining_files=$(find "$bind_trace_dir" "$diagnostic_dir" -type f -print -quit)
    if [[ -n "$remaining_files" ]]; then
      passed=0
    fi
  fi

  if ((passed)); then
    if [[ "$expected" == failure || "$expected" == signal ]]; then
      record_dir="$artifact_dir/$label-$run_index"
    else
      rm -rf -- "$temp_dir"
      return 0
    fi
  else
    record_dir="$artifact_dir/$label-$run_index"
  fi
  mkdir -p "$record_dir"
  mv -- "$out" "$record_dir/stdout"
  mv -- "$err" "$record_dir/stderr"
  mv -- "$bind_trace_dir" "$record_dir/bind-trace"
  mv -- "$diagnostic_dir" "$record_dir/diagnostics"
  local command_kind='nelisp --eval'
  if [[ "$label" == signal-control ]]; then
    command_kind='bash -c kill -SEGV "$$"'
  fi
  cat > "$record_dir/metadata.txt" <<EOF
binary_sha256=$binary_sha
binary_snapshot=$binary
case=$label
run_index=$run_index
expected=$expected
returncode=$returncode
exit_status=$status
signal=$signal_name
binary_sha256_after=$binary_sha_after
timeout_seconds=$timeout_seconds
core_pattern=$core_pattern
command_kind=$command_kind
bind_trace_dir=$record_dir/bind-trace
diagnostic_dir=$record_dir/diagnostics
NELISP_ROOT=$nelisp_root_value
source_root_candidate_kind=$source_root_kind
source_root_candidate=$source_root_candidate
source_root_effective=unverified_harness_candidate_only
source_sha256_lisp_nelisp_aot_compiler=$source_sha_aot_compiler
source_sha256_lisp_nelisp_artifact=$source_sha_artifact
source_sha256_lisp_nelisp_bytecode_jit=$source_sha_bytecode_jit
source_sha256_scripts_nelisp_stdlib_prelude=$source_sha_stdlib_prelude
expression:
$expression
EOF
  if [[ -n "$core_file" ]]; then
    printf 'core_file=%s\n' "$core_file" >> "$record_dir/metadata.txt"
    if command -v gdb >/dev/null 2>&1; then
      local debug_binary=$binary
      if [[ "$label" == signal-control ]]; then
        debug_binary=$(command -v bash)
      fi
      gdb -q -batch "$debug_binary" "$core_file" \
        -ex 'set pagination off' \
        -ex 'bt 24' \
        -ex 'frame 0' \
        -ex 'info args' \
        -ex 'info locals' \
        -ex 'info registers' \
        -ex 'info symbol $pc' \
        -ex 'printf "candidate_root_pointer(rdi)=%p\\n", $rdi' \
        -ex 'x/8gx $rdi' \
        > "$record_dir/gdb.txt" 2>&1 || true
    else
      echo 'gdb=unavailable' > "$record_dir/gdb.txt"
    fi
  fi
  if [[ "$label" == negative-control && "$passed" == 1 ]] \
      && [[ ! -f "$record_dir/bind-trace/retention-marker" \
            || ! -f "$record_dir/diagnostics/retention-marker" ]]; then
    passed=0
  fi
  rm -rf -- "$temp_dir"
  if ((passed)); then
    return 0
  fi
  echo "standalone-bytecode-jit-zeroarg-stress: $label run $run_index failed (status=$returncode signal=$signal_name; details=$record_dir)" >&2
  return 1
}

minimal_failures=0
minimal_attempted=0
for ((run = 1; run <= minimal_runs; run++)); do
  minimal_attempted=$run
  if ! capture_case minimal "$run" "$minimal_expr" success; then
    minimal_failures=1
    break
  fi
done

stress_failures=0
for ((run = 1; run <= stress_runs; run++)); do
  capture_case guarded "$run" "$stress_expr" success || stress_failures=$((stress_failures + 1))
done

direct_failures=0
for ((run = 1; run <= direct_runs; run++)); do
  capture_case direct-loader "$run" "$direct_expr" success || direct_failures=$((direct_failures + 1))
done

negative_failures=0
if ! capture_case negative-control 1 "$negative_expr" failure; then
  negative_failures=1
fi
signal_control_failures=0
if ! capture_case signal-control 1 'kill -SEGV "$$"' signal; then
  signal_control_failures=1
fi
stderr_control_failures=0
if ! capture_case stderr-control 1 '' rejected-control; then
  stderr_control_failures=1
fi

echo "standalone-bytecode-jit-zeroarg-stress: minimal=$((minimal_attempted - minimal_failures))/$minimal_attempted guarded=$((stress_runs - stress_failures))/$stress_runs direct=$((direct_runs - direct_failures))/$direct_runs negative-control=captured signal-control=$((1 - signal_control_failures))/1 stderr-control=$((1 - stderr_control_failures))/1 sha256=$binary_sha artifacts=$artifact_dir"
((minimal_failures == 0 && stress_failures == 0 && direct_failures == 0 && negative_failures == 0 && signal_control_failures == 0 && stderr_control_failures == 0))
