;;; standalone-native-cfg-cycles-driver.el --- Cyclic native parity -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(defun cycles-stage (label)
  (write-region (concat label "\n") nil (getenv "CYCLES_STAGE") t 'silent))
(cycles-stage "require-start")
(require 'nelisp-native-cache)
(cycles-stage "require-end")
(load "test/support/native-cfg-cycles-fixtures.el" nil t t)
(defvar cycles-swap-state nil)
(defun cycles-swap-step ()
  (let ((left (nth 0 cycles-swap-state)) (right (nth 1 cycles-swap-state))
        (remaining (nth 2 cycles-swap-state)))
    (if (= remaining 0) nil
      (setq cycles-swap-state (list right left (1- remaining))) t)))
(defun cycles-assert (value label) (unless value (error "cycles: %s" label)))
(let* ((nelisp-native-cache-backend (if (equal (getenv "CYCLES_BACKEND") "gccjit") 'gccjit 'in-house))
       (name (intern (getenv "CYCLES_CASE")))
       (fixture (assq name (native-cfg-cycles-fixtures)))
       (fn (nth 1 fixture)) (cases 0))
  (cycles-assert fixture "fixture exists")
  (cycles-stage "install-start")
  (nelisp-native-cache-install 'cycles-native fn)
  (cycles-stage "install-end")
  (if (eq name 'closed)
      (progn
        (setq quit-flag t)
        (cycles-assert (eq (condition-case nil (progn (cycles-native) 'returned) (quit 'quit)) 'quit)
                       "closed loop quit poll")
        (setq cases 1))
    (dolist (args (nth 2 fixture))
      (cycles-stage (format "call-start %S" args))
      (let* ((_reset (setq cycles-swap-state '(left right 3) cycles-count-state 5 cycles-count-history nil))
             (expected (apply fn args))
             (expected-state (copy-sequence cycles-swap-state))
             (expected-history (copy-sequence cycles-count-history))
             (_reset (setq cycles-swap-state '(left right 3) cycles-count-state 5 cycles-count-history nil))
             (actual (apply #'cycles-native args)))
        (when (eq name 'counted)
          (cycles-assert (= cycles-count-state 0) "five counted iterations")
          (cycles-assert (equal cycles-count-history expected-history) "ordered count effects")
          (cycles-assert (equal cycles-count-history '(1 2 3 4 5)) "exact loop count"))
        (when (eq name 'swap)
          (cycles-assert (equal cycles-swap-state expected-state) "ordered swapped loop values")
          (cycles-assert (equal cycles-swap-state '(right left 0)) "odd swap count"))
        (cycles-assert (equal expected actual) "interpreter parity")
        (when (memq name '(ref6 ref7)) (cycles-assert (eq actual (car args)) "identity")))
      (setq cases (1+ cases))))
  (cycles-assert (file-exists-p (nelisp-native-cache-file fn)) "executed artifact")
  (princ (format "CYCLES-NATIVE-PASS backend=%S fixture=%S cases=%d\n"
                 nelisp-native-cache-backend name cases)))
