;;; standalone-terminal-output.el --- Genuine output API controls -*- lexical-binding: t; -*-
(require 'nelisp-stdlib-terminal-output)
(unless (and (fboundp 'internal-char-font) (fboundp 'terminal-coding-system))
  (let ((dialect (symbol-function 'nelisp-bytecode-compiler-input-dialect)))
    (unwind-protect
        (progn
          (fset 'nelisp-bytecode-compiler-input-dialect (lambda () '(:status unknown)))
          (unless (condition-case nil (progn (nelisp-stdlib-terminal-output-install) nil)
                    (error t))
            (error "Unverified runtime admitted")))
      (fset 'nelisp-bytecode-compiler-input-dialect dialect))))
(let* ((names '(internal-char-font terminal-coding-system coding-system-get encode-char))
       (cells (mapcar (lambda (symbol) (and (fboundp symbol) (symbol-function symbol))) names))
       (status (nelisp-stdlib-terminal-output-install)))
  (when (eq status 'preserved)
    (let ((remaining cells))
      (dolist (symbol names)
        (unless (eq (pop remaining) (symbol-function symbol))
          (error "Host function changed: %S" symbol)))))
  (with-temp-buffer
    (let ((results
           (mapcar (lambda (form) (condition-case err (eval form) (error err)))
                   '((internal-char-font nil 8593)
                     (internal-char-font nil nil)
                     (internal-char-font nil -1)
                     (internal-char-font 0 65)
                     (internal-char-font 'bad 65)
                     (terminal-coding-system)
                     (terminal-coding-system 'bad)
                     (coding-system-get 'utf-8-unix :charset-list)
                     (encode-char 8593 'unicode)
                     (encode-char 1114112 'unicode)))))
      (unless (equal results
                     '(nil (wrong-type-argument characterp nil)
                       (wrong-type-argument characterp -1)
                       (args-out-of-range 0 1 1)
                       (wrong-type-argument integer-or-marker-p bad)
                       utf-8-unix (wrong-type-argument terminal-live-p bad)
                       (unicode) 8593 nil))
        (error "Output API parity failed: %S" results)))
    (let ((dead (condition-case err (internal-char-font (make-marker)) (error err))))
      (unless (equal dead '(error "Marker does not point anywhere"))
        (error "Dead marker condition differs: %S" dead)))
    (insert "A")
    (unless (null (internal-char-font (copy-marker 1)))
      (error "Byte device reported a font")))
  (when (eq status 'installed)
    (let ((writer (symbol-function 'nelisp--write-stdout-bytes)))
      (unwind-protect
          (progn
            (fset 'nelisp--write-stdout-bytes (lambda (&rest _) nil))
            (unless (condition-case nil (progn (terminal-coding-system) nil)
                      (error t))
              (error "Changed writer admitted")))
        (fset 'nelisp--write-stdout-bytes writer)))
    (let ((state nelisp--terminal-output-device))
      (unwind-protect
          (progn
            (setq nelisp--terminal-output-device nil)
            (unless (condition-case nil (progn (internal-char-font nil 8593) nil)
                      (error t))
              (error "Unavailable device admitted")))
        (setq nelisp--terminal-output-device state)))))
(princ "STANDALONE-TERMINAL-OUTPUT-PASS\n")
