;;; standalone-match-state-cycles.el --- Finite match-state inputs -*- lexical-binding: t; -*-
(require 'nelisp-stdlib-match-state)
(when (eq (nelisp-stdlib-match-state-install) 'installed)
  (set-match-data '(1 3))
  (dolist (operation '(set reuse))
    (let ((cycle (list 4 6)) caught)
      (setcdr (cdr cycle) cycle)
      (condition-case condition
          (if (eq operation 'set) (set-match-data cycle) (match-data t cycle))
        (circular-list (setq caught (car condition))))
      (unless (eq caught 'circular-list) (error "Circular input accepted"))
      (unless (and (= (car cycle) 4) (= (cadr cycle) 6)
                   (eq (cddr cycle) cycle) (equal (match-data t) '(1 3)))
        (error "Circular refusal changed state or caller cells"))))
  (let ((reuse (cons 4 'bad)) caught)
    (condition-case nil (match-data t reuse)
      (wrong-type-argument (setq caught t)))
    (unless (and caught (equal reuse '(4 . bad)) (equal (match-data t) '(1 3)))
      (error "Improper REUSE changed state before refusal"))))
(princ "MATCH-FINITE-SPINE-PASS\n")
