;;; -*- lexical-binding: t; -*-
(load (or (getenv "POLL_CONTROL_SOURCE") "lisp/nelisp-native-poll.el") nil t t)
(let* ((stats (string-to-number (getenv "POLL_GC_STATS") 16))
       (poll (nelisp-bytecode-native-rooted-cfg-poll-function))
       (roots (list (vector 'retained) (cons 'head 'tail)))
       (pointer (symbol-function 'ptr-read-u64))
       (garbage nil))
  (garbage-collect) (garbage-collect)
  ;; Disable the evaluator's automatic while poll while constructing debt.
  ;; One outer form keeps the driver from collecting at a form boundary.
  (nelisp--debug-switch 30 4096) (nelisp--debug-switch 31 1)
  (nelisp--debug-switch 6)
  (setq garbage (make-string 8388608 65))
  (nelisp--debug-switch 5)
  (let ((before (funcall pointer stats 24)))
    (funcall poll)
    (unless (= (funcall pointer stats 24) (1+ before))
      (error "Allocator debt did not collect at native poll"))
    (setq before (funcall pointer stats 24))
    (dotimes (_ 10) (funcall poll))
    (unless (= (funcall pointer stats 24) before)
      (error "Allocator budget was not re-armed"))
    (unless (and (eq (aref (car roots) 0) 'retained) (equal (cadr roots) '(head . tail))
                 (= (length garbage) 8388608)) (error "Poll GC lost live roots"))
    (princ "POLL-ALLOCATOR-PASS debt=1 quiet-polls=10 roots=retained\n"))
  (nelisp--debug-switch 30 0) (nelisp--debug-switch 31 0)
  ;; Suppress debt so this control isolates the growth watermark. The native
  ;; make-string allocator has no evaluator while backedge of its own.
  (nelisp--debug-switch 30 1000000000000)
  (nelisp--debug-switch 5)
  (setq garbage (make-string 83886080 66))
  (let ((before (funcall pointer stats 24)))
    (funcall poll)
    (unless (= (funcall pointer stats 24) (1+ before))
      (error "Allocator growth did not collect at native poll"))
    (setq before (funcall pointer stats 24))
    (dotimes (_ 10) (funcall poll))
    (unless (= (funcall pointer stats 24) before)
      (error "Growth watermark was not re-armed"))
    (unless (= (length garbage) 83886080) (error "Growth GC lost live string"))
    (princ "POLL-ALLOCATOR-PASS growth=1 quiet-polls=10 roots=retained\n"))
  (nelisp--debug-switch 30 0))
