;;; Windows cache handle trust controls -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'nelisp-native-windows)
(require 'nelisp-native-load)
(unless (eq system-type 'windows-nt) (error "Windows trust control requires Windows"))
(let ((root (getenv "WINDOWS_TRUST_ROOT")) (mode (getenv "WINDOWS_TRUST_MODE")))
  (unless root (error "Missing isolated Windows trust directory"))
  (if (equal mode "reparse")
      (let ((maps 0) refused)
        (cl-letf (((symbol-function 'nelisp-native-load--mmap)
                   (lambda (&rest _) (setq maps (1+ maps)) (error "Unexpected code mapping"))))
          (condition-case err (nelisp-native-windows-private-directory root)
            (error (setq refused (equal (error-message-string err)
                                       "Cache ancestor is reparse or not a directory")))))
        (unless (and refused (= maps 0)) (error "Reparse path was admitted"))
        (princ "WINDOWS-REPARSE-REFUSED maps=0\n"))
    (let* ((parent (expand-file-name "pin-parent" root))
           (renamed (concat parent "-moved"))
           (cache (expand-file-name "cache" parent)))
      (make-directory parent t)
      (let ((from (nelisp-native-windows-wide parent)) (to (nelisp-native-windows-wide renamed)))
        (unwind-protect
            (progn
              ;; Calibrate the control: this exact rename works before pinning.
              (unless (= 1 (nelisp-native-windows-call "MoveFileExW" from to 0))
                (error "Unpinned rename negative-control setup failed"))
              (unless (= 1 (nelisp-native-windows-call "MoveFileExW" to from 0))
                (error "Unpinned rename restore failed"))
              (nelisp-native-windows-private-directory cache)
              (unless (= 0 (nelisp-native-windows-call "MoveFileExW" from to 0))
                (error "Pinned cache ancestor was replaced"))
              (unless (= 32 (nelisp-native-windows-call "GetLastError"))
                (error "Pinned rename failed for a reason other than sharing violation"))
              (princ "WINDOWS-ANCESTOR-PIN-PASS unpinned=1 pinned=0 sharing=32\n"))
          (nelisp-native-windows-free from) (nelisp-native-windows-free to))))))
