;;; standalone-bytecode-native-rooted-stack-driver.el --- source-free rooted stack proof -*- lexical-binding: t; -*-

(require 'nelisp-bytecode-native-rooted-stack)
(require 'nelisp-bytecode-native-rooted-stack-call)
(require 'nelisp-bytecode-compiler-input)
(require 'nelisp-bytecode-native-compiler)
(require 'nelisp-bytecode-native-package)
(require 'nelisp-native-load)

(defmacro nelisp-test-rooted-stack--timing-mark (label)
  `(let ((now (float-time)))
     (princ (format "stage-time: %s +%.3fs\n" ,label (- now last-stage-time)))
     (setq last-stage-time now)))

(defun nelisp-test-rooted-stack-source-free-smoke ()
  (let* ((source (getenv "NELISP_ROOTED_SOURCE"))
         (elc (getenv "NELISP_ROOTED_ELC"))
         (artifact-dir (getenv "NELISP_ROOTED_ARTIFACT_DIR"))
         (definitions (nelisp-bytecode-native-package-read-elc-functions elc))
         (names '(nelisp-rooted-stack-car-cdr-cons
                  nelisp-rooted-stack-constant-chain
                  nelisp-rooted-stack-nested-cons
                  nelisp-rooted-stack-duplicate-arg))
         (functions (mapcar (lambda (name) (cdr (assq name definitions))) names))
         (doc-function (cdr (assq 'nelisp-rooted-stack-documented-car definitions)))
         (doc-materialized
          (make-byte-code (aref doc-function 0) (aref doc-function 1)
                          (aref doc-function 2) (aref doc-function 3)
                          (aref doc-function 4)))
         (doc-input (nelisp-bytecode-compiler-input-build
                     doc-materialized))
         (inputs (mapcar (lambda (fn)
                           (nelisp-bytecode-compiler-input-build
                            (make-byte-code (aref fn 0) (aref fn 1)
                                            (aref fn 2) (aref fn 3))))
                         functions))
         (tags '((car cdr cons) (cdr car cons) (cdr cons cons) (car car cons)))
         (results nil) (index 0) (last-stage-time (float-time)))
    (unless (and (stringp source) (not (file-exists-p source))
                 (stringp elc) (file-exists-p elc)
                 (cl-every (lambda (input) (eq (plist-get input :status) 'complete)) inputs)
                 (eq (plist-get doc-input :status) 'complete)
                 (eq (plist-get doc-input :metadata-role) 'lazy-documentation-reference)
                 (plist-get doc-input :documentation-reference))
      (error "rooted-stack source-free GNU input admission failed"))
    (dolist (input inputs)
      (let* ((path (expand-file-name (format "unit-%d.nelr" index) artifact-dir))
             (result (nelisp-bytecode-native-rooted-stack-build input path)))
        (unless (and (eq (plist-get result :status) 'complete)
                     (= (plist-get input :argument-descriptor)
                        (if (= (plist-get input :argument-count) 1) 257 514))
                     (equal (mapcar (lambda (op) (plist-get op :operation))
                                    (plist-get (plist-get result :plan) :operations))
                            (nth index tags)))
          (error "rooted-stack plan differs from pinned GNU fixture %d" index))
        (nelisp-test-rooted-stack--timing-mark (format "unit-%d compile" index))
        (push result results)
        (setq index (1+ index))))
    (setq results (nreverse results))
    (let* ((result0 (nth 0 results)) (result1 (nth 1 results))
           (result2 (nth 2 results)) (result3 (nth 3 results))
           (a (cons 'left (list 'a-tail))) (b (cons 'b-head (list 'b-tail)))
           (middle-arg (list 'head (list 'leaf)))
           (doc-arg (list 'doc-value))
           (left (funcall (nth 0 functions) a b))
           (middle (funcall (nth 1 functions) middle-arg))
           (nested (funcall (nth 2 functions) a b))
           (duplicate (funcall (nth 3 functions) a))
           (real-loader (symbol-function 'nelisp-native-load-raw-v2-artifact))
           (real-export (symbol-function 'nelisp-native-load-raw-export-address))
           (real-ptr-call (symbol-function 'ptr-call)) (entry-addresses nil)
           (entry-calls 0) (mapping-calls 0)
           (doc-result nil) (doc-entry-start 0)
           (doc-vm (funcall doc-materialized doc-arg))
           native-left native-middle native-nested native-duplicate native-doc)
      (cl-letf (((symbol-function 'nelisp-native-load-raw-v2-artifact)
                 (lambda (&rest args)
                   (setq mapping-calls (1+ mapping-calls))
                   (apply real-loader args)))
                ((symbol-function 'nelisp-native-load-raw-export-address)
                 (lambda (mapping name)
                   (let ((address (funcall real-export mapping name)))
                     (when (equal name "nl_native_stack_probe_v1")
                       (push address entry-addresses))
                     address)))
                ((symbol-function 'ptr-call)
                 (lambda (address &rest args)
                   (when (memq address entry-addresses)
                     (setq entry-calls (1+ entry-calls)))
                   (apply real-ptr-call address args))))
        (setq doc-result
              (nelisp-bytecode-native-compiler-build
               doc-materialized (expand-file-name "public-doc.nelr" artifact-dir)
               "nl_native_stack_probe_v1"))
        (nelisp-test-rooted-stack--timing-mark "public doc compile")
        (unless (and (eq (plist-get doc-result :status) 'complete)
                     (equal (plist-get doc-result :entry-name) "nl_native_stack_probe_v1")
                     (nelisp-bytecode-native-rooted-stack-authenticated-result-p doc-result))
          (error "public compiler rejected documented GNU fixture"))
        (let* ((manifest (nelisp-native-load-manifest
                          (plist-get doc-result :artifact-path)))
               (descriptors (plist-get (plist-get manifest :native) :imports))
               (summary (mapcar (lambda (d)
                                  (list (plist-get d :name) (plist-get d :kind)
                                        (plist-get d :abi) (plist-get d :index)
                                        (plist-get d :address-mode) (plist-get d :arity)
                                        (plist-get d :params)))
                                descriptors)))
          (princ (format "rooted-stack manifest imports: %S\n" summary))
          (unless (equal (nelisp-bytecode-native-rooted-stack-call--manifest-import-names
                          manifest)
                         '("nl_native_car_v2"))
            (error "compiled fixture import descriptors differ from rooted plan"))
          (let ((bad (copy-tree manifest))
                (before (cons mapping-calls entry-calls)))
            (setf (plist-get (car (plist-get (plist-get bad :native) :imports))
                             :address-mode)
                  'resolver)
            (cl-letf (((symbol-function 'nelisp-native-load-manifest)
                       (lambda (_) bad)))
              (condition-case nil
                  (nelisp-bytecode-native-rooted-stack-call doc-result '(doc-value))
                (error nil)))
            (unless (equal before (cons mapping-calls entry-calls))
              (error "mutated manifest mode reached map or entry"))))
        (unless (and (nelisp-bytecode-native-rooted-stack-authenticated-result-p result0)
                     (not (nelisp-bytecode-native-rooted-stack-authenticated-result-p
                           (copy-sequence result0)))
                     (not (nelisp-bytecode-native-rooted-stack-authenticated-result-p
                           '(:status complete :entry-name "nl_native_stack_probe_v1"))))
          (error "producer result authenticity controls failed"))
        (let ((calls (cons mapping-calls entry-calls)))
          (condition-case nil
              (nelisp-bytecode-native-rooted-stack-call
               (plist-put (copy-sequence result0) :runtime-binary-sha256 "forged") a b)
            (error nil))
          (unless (equal calls (cons mapping-calls entry-calls))
            (error "forged result reached native effects")))
        (let ((calls (cons mapping-calls entry-calls))
              (artifact (plist-get result0 :artifact-path))
              artifact-content)
          (with-temp-buffer
            (insert-file-contents-literally artifact)
            (setq artifact-content (buffer-string)))
          (with-temp-file artifact
            (insert artifact-content)
            (insert "tamper"))
          (when (nelisp-bytecode-native-rooted-stack-authenticated-result-p result0)
            (error "tampered artifact retained producer authentication"))
          (condition-case nil
              (nelisp-bytecode-native-rooted-stack-call result0 a b)
            (error nil))
          (with-temp-file artifact (insert artifact-content))
          (unless (nelisp-bytecode-native-rooted-stack-authenticated-result-p result0)
            (error "restored artifact did not recover authentication"))
          (unless (equal calls (cons mapping-calls entry-calls))
            (error "tampered artifact reached native effects")))
        (setq native-left (nelisp-bytecode-native-rooted-stack-call result0 a b)
              native-middle (nelisp-bytecode-native-rooted-stack-call
                             result1 middle-arg)
              native-nested (nelisp-bytecode-native-rooted-stack-call result2 a b)
              native-duplicate (nelisp-bytecode-native-rooted-stack-call result3 a))
        (nelisp-test-rooted-stack--timing-mark "four composed native calls")
        (setq doc-entry-start entry-calls)
        (garbage-collect)
        (nelisp-test-rooted-stack--timing-mark "pre-doc-call GC")
        (setq native-doc (nelisp-bytecode-native-rooted-stack-call
                          doc-result doc-arg))
        (unless (and (equal native-doc doc-vm) (eq native-doc doc-vm)
                     (> entry-calls doc-entry-start))
          (error "public compiler documented function differs from GNU VM"))
        (princ (format "rooted-stack public route entry calls: %d -> %d; value=%S\n"
                       doc-entry-start entry-calls native-doc))
        (garbage-collect)
        (nelisp-test-rooted-stack--timing-mark "post-doc-call GC")
        (unless (and (equal native-left left) (eq (car native-left) (car left))
                     (eq (cdr native-left) (cdr left))
                     (equal native-middle middle) (eq (cdr native-middle) (cdr middle))
                     (equal native-nested nested) (eq (car native-nested) a)
                     (eq (car (cdr native-nested)) b)
                     (eq (car native-duplicate) (car a))
                     (eq (cdr native-duplicate) (car a))
                     (> entry-calls 0))
          (error "rooted-stack native/VM value identity mismatch"))
        (setcar (cdr b) 'mutated)
        (unless (eq (car (cdr native-left)) 'mutated)
          (error "rooted-stack mutation visibility mismatch"))
        (dolist (arg-list (list (list 9 b) (list a 9)))
          (unless (equal (condition-case err
                             (nelisp-bytecode-native-rooted-stack-call result0
                                                                        (car arg-list)
                                                                        (cadr arg-list))
                           (wrong-type-argument err))
                         (condition-case err (funcall (nth 0 functions)
                                                      (car arg-list) (cadr arg-list))
                           (wrong-type-argument err)))
            (error "wrong-type payload differs from GNU VM")))
        (let ((bad (cons 'head 9)))
          (unless (equal (condition-case err
                             (nelisp-bytecode-native-rooted-stack-call result1 bad)
                           (wrong-type-argument err))
                         (condition-case err (funcall (nth 1 functions) bad)
                           (wrong-type-argument err)))
            (error "intermediate wrong-type payload differs from GNU VM")))
        (unless (equal (condition-case err
                           (nelisp-bytecode-native-rooted-stack-call doc-result 9)
                         (wrong-type-argument err))
                       (condition-case err (funcall doc-materialized 9)
                         (wrong-type-argument err)))
          (error "documented function wrong-type payload differs from GNU VM"))
        (nelisp-test-rooted-stack--timing-mark "wrong-type parity checks")
        (garbage-collect)
        (nelisp-test-rooted-stack--timing-mark "post-error GC")
        (unless (eq (nelisp-bytecode-native-rooted-stack-call doc-result doc-arg)
                    doc-vm)
          (error "documented public route failed after error and GC"))
        (unless (equal (nelisp-bytecode-native-rooted-stack-call result0 a b) left)
          (error "caller failed to clean up after native errors"))
        (nelisp-test-rooted-stack--timing-mark "post-error recovery complete")))))

(provide 'standalone-bytecode-native-rooted-stack-driver)
;;; standalone-bytecode-native-rooted-stack-driver.el ends here
