;;; standalone-bytecode-native-rooted-branch-driver.el --- source-free branch proof -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'nelisp-bytecode-native-package)
(require 'nelisp-bytecode-compiler-input)
(require 'nelisp-bytecode-native-compiler)
(require 'nelisp-bytecode-native-rooted-branch)
(require 'nelisp-bytecode-native-rooted-branch-call)
(require 'nelisp-native-load)

(defun nelisp-test-rooted-branch-source-free-smoke ()
  (let* ((source (getenv "NELISP_BRANCH_SOURCE"))
         (elc (getenv "NELISP_BRANCH_ELC"))
         (artifact (expand-file-name "branch.nelr" (getenv "NELISP_BRANCH_ARTIFACT_DIR")))
         (definition (cdr (assq 'gnu-rooted-branch
                                (nelisp-bytecode-native-package-read-elc-functions elc))))
         (function (and definition
                        (make-byte-code (aref definition 0) (aref definition 1)
                                        (aref definition 2) (aref definition 3))))
         (input (and function (nelisp-bytecode-compiler-input-build function)))
         (frame (and input (nelisp-bytecode-frame-ir-build
                            (plist-get input :code) (plist-get input :constants)
                            (plist-get input :initial-stack-depth))))
         (blocks (and frame (plist-get frame :blocks)))
         result)
    (unless (and (stringp source) (not (file-exists-p source))
                 (stringp elc) (file-exists-p elc)
                 (eq (plist-get input :status) 'complete)
                 (eq (plist-get (nelisp-bytecode-native-rooted-branch-plan input) :status)
                     'complete))
      (princ (format "BRANCH-DIAG=%S\n"
                     (list (equal (plist-get input :code)
                                  (unibyte-string 2 131 7 0 1 64 135 65 135))
                           (vectorp (plist-get frame :blocks))
                           (mapcar (lambda (b) (plist-get b :start)) (append blocks nil))
                           (mapcar (lambda (e) (plist-get e :target))
                                   (plist-get (aref blocks 0) :successors))
                           (plist-get (aref (plist-get (aref blocks 0) :instructions) 1) :opcode)
                           (plist-get (aref (plist-get (aref blocks 0) :instructions) 1) :operand)
                           (mapcar (lambda (b) (plist-get b :successors)) (append blocks nil))
                           (list (plist-get input :argument-count)
                                 (plist-get input :initial-stack-depth)
                                 (plist-get input :required-argument-count)
                                 (plist-get input :argument-min) (plist-get input :argument-max)
                                 (plist-get input :argument-descriptor))
                           (plist-get input :rest-argument-p)
                           (plist-get input :capture-values-available)
                           (plist-get input :potential-capture-placeholder-p)
                           (plist-get input :closure-template-descriptor)
                           (vectorp (plist-get input :constants))
                           (length (plist-get input :constants)))))
      (error "rooted-branch: GNU ELC admission failed exists=%S input=%S frame=%S blocks=%S"
             (and (stringp source) (not (file-exists-p source))
                  (stringp elc) (file-exists-p elc))
             (and input (list (plist-get input :status) (plist-get input :argument-descriptor)
                              (plist-get input :argument-count) (plist-get input :code)
                              (plist-get input :closure-template-descriptor)))
             (and frame (plist-get frame :status))
             (and blocks (mapcar (lambda (block)
                                   (list (plist-get block :start)
                                         (mapcar (lambda (edge) (plist-get edge :target))
                                                 (plist-get block :successors))))
                                 (append blocks nil)))
             (and input
                  (list :code-equal (equal (plist-get input :code)
                                           (unibyte-string 2 131 7 0 1 64 135 65 135))
                        :vector-blocks (vectorp (plist-get frame :blocks))
                        :starts (mapcar (lambda (b) (plist-get b :start))
                                        (append (plist-get frame :blocks) nil))
                        :desc (plist-get input :argument-descriptor)
                        :minmax (list (plist-get input :argument-min)
                                      (plist-get input :argument-max)
                                      (plist-get input :required-argument-count))
                        :constants-vector (vectorp (plist-get input :constants))))))
    (setq result
          (nelisp-bytecode-native-compiler-build
           function artifact nelisp-bytecode-native-rooted-branch-entry))
    (unless (eq (plist-get result :status) 'complete)
      (error "rooted-branch: producer failed: %S" result))
    (let* ((condition t)
           (car-inner (cons 'car-result (list 'mutable-tail)))
           (car-value (list car-inner))
           (cdr-value (cons 'cdr-head (list 'cdr-result)))
           (car-vm (funcall function condition car-value cdr-value))
           (cdr-vm (funcall function nil car-value cdr-value))
           (real-loader (symbol-function 'nelisp-native-load-raw-v2-artifact))
           (real-export (symbol-function 'nelisp-native-load-raw-export-address))
           (real-entry-call
            (symbol-function 'nelisp-bytecode-native-rooted-branch-entry-call))
           (entry-addresses nil) (entry-count 0) (native-car nil) (native-cdr nil))
      (cl-letf (((symbol-function 'nelisp-native-load-raw-v2-artifact)
                 (lambda (&rest args) (apply real-loader args)))
                ((symbol-function 'nelisp-native-load-raw-export-address)
                 (lambda (mapping name)
                   (let ((address (funcall real-export mapping name)))
                     (when (equal name "nl_native_rooted_branch_probe_v1")
                       (push address entry-addresses))
                     address)))
                ((symbol-function 'nelisp-bytecode-native-rooted-branch-entry-call)
                 (lambda (address env ticket)
                   (unless (member address entry-addresses)
                     (error "rooted-branch: unrecognized native entry address"))
                   (setq entry-count (1+ entry-count))
                   (funcall real-entry-call address env ticket))))
        (unless (and (nelisp-bytecode-native-rooted-branch-authenticated-result-p result)
                     (not (nelisp-bytecode-native-rooted-branch-authenticated-result-p
                           (copy-sequence result)))
                     (not (nelisp-bytecode-native-rooted-branch-authenticated-result-p
                           '(:status complete :entry-name "nl_native_rooted_branch_probe_v1"))))
          (error "rooted-branch: forged producer result passed authentication"))
        (condition-case nil
            (nelisp-bytecode-native-rooted-branch-call
             (plist-put (copy-sequence result) :runtime-binary-sha256 "stale") t car-value cdr-value)
          (error nil))
        (setq native-car (nelisp-bytecode-native-rooted-branch-call
                          result condition car-value cdr-value)
              native-cdr (nelisp-bytecode-native-rooted-branch-call
                          result nil car-value cdr-value))
        (garbage-collect)
        (unless (and (eq native-car car-vm) (eq native-cdr cdr-vm)
                     (eq native-car car-inner) (> entry-count 0))
          (error "rooted-branch: native/VM branch result or entry count mismatch"))
        (setcar (cdr car-inner) 'changed)
        (unless (eq (cdr native-car) (cdr car-inner))
          (error "rooted-branch: mutable object identity lost across native GC"))
        (dolist (case '((t 9 (head . tail)) (nil (head . tail) 9)))
          (let ((native-error
                 (condition-case err
                     (nelisp-bytecode-native-rooted-branch-call result (nth 0 case)
                                                               (nth 1 case) (nth 2 case))
                   (wrong-type-argument err)))
                (vm-error
                 (condition-case err
                     (funcall function (nth 0 case) (nth 1 case) (nth 2 case))
                   (wrong-type-argument err))))
            (unless (equal native-error vm-error)
              (error "rooted-branch: wrong-type payload differs from GNU VM"))))
        (unless (eq (nelisp-bytecode-native-rooted-branch-call
                     result nil car-value cdr-value) cdr-vm)
          (error "rooted-branch: recovery after errors failed"))
        (unless (= entry-count 5)
          (error "rooted-branch: expected exactly five native entry calls, got %s"
                 entry-count))
        (princ (format "rooted-branch: authenticated fixed entry calls=%d\n" entry-count))))))

(provide 'standalone-bytecode-native-rooted-branch-driver)
;;; standalone-bytecode-native-rooted-branch-driver.el ends here
