;;; standalone-native-concat-u3b-driver.el --- Executed sequence parity -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'nelisp-native-cache)
(load "test/support/native-entry-observer.el" nil t t)
(load "test/support/native-concat-u3b-fixtures.el" nil t t)
(defun u3b-assert (value label) (unless value (error "U3b: %s" label)))
(defun u3b-header (fn)
  (let ((file (nelisp-native-cache-file fn)))
    (with-temp-buffer
      (insert-file-contents (if (eq nelisp-native-cache-backend 'gccjit) (concat file ".nelh") file))
      (goto-char (point-min)) (read (current-buffer)))))
(defun u3b-observe-native (fn native args opcode &optional poison)
  "Observe one authenticated native entry, poisoning public cells only inside it."
  (let* ((header (u3b-header fn)) (arity (plist-get header :arity))
         (roots (plist-get header :root-count)) (entries 0) (poison-calls 0)
         (restore (symbol-function 'fset))
         (saved (mapcar (lambda (name) (cons name (symbol-function name))) (if (= opcode 177) '(insert) '(concat apply cons))))
         actual)
    (nelisp-test-with-native-entry-observer
	(lambda (address env ticket argc n x y)
	  (when (and (= argc arity) (= n roots) (= x 0) (= y 0))
	    (setq entries (1+ entries))))
      (setq actual
	    (native-concat-u3b-observe
	     (nelisp-test-native-poison native
					(lambda nil
					  (when poison
					    (dolist (pair saved)
					      (funcall restore (car pair)
						       (lambda (&rest _)
							 (setq
							  poison-calls
							  (1+ poison-calls))
							 'poison)))))
					(lambda nil
					  (dolist (pair saved)
					    (funcall restore (car pair)
						     (cdr pair)))))
	     args opcode)))
    (u3b-assert (= entries 1) (format "one native entry, got %d" entries))
    (u3b-assert (= poison-calls 0) "frozen builtin and Lisp provider values")
    actual))
(let ((nelisp-native-cache-backend (intern (getenv "U3B_BACKEND"))))
(dolist (index (mapcar #'string-to-number (split-string (getenv "U3B_CASE"))))
  (princ (format "U3B-START backend=%S case=%d\n" nelisp-native-cache-backend index))
  (cond
   ((< index 13)
    (let* ((row (nth index (native-concat-u3b-fixtures))) (opcode (car row)) (count (cadr row))
           (fn (apply #'native-concat-u3b-function row)) (args (native-concat-u3b-args opcode count))
           (expected (native-concat-u3b-observe fn args opcode))
           (initializer (symbol-function 'nelisp-native-funcall-v2-initializer))
           (cons-value (nelisp-native-funcall-v2-initializer 'cons))
           (gc-value (symbol-function 'garbage-collect)) (collections 0) (allocations 0) actual)
      (u3b-assert
       (equal expected
              (native-concat-u3b-observe
               (nelisp-native-funcall-v2-initializer (if (= opcode 177) 'insert 'concat))
               (native-concat-u3b-values args count) opcode))
       "valid VM fixture matches the canonical provider before native compilation")
      (nelisp-native-cache-install 'u3b-native fn)
      (setq actual (u3b-observe-native fn (symbol-function 'u3b-native) args opcode t))
      (u3b-assert (equal expected actual) (format "interpreter/native parity expected=%S actual=%S" expected actual))
      (when (> count 32)
        (let (gc-native)
          (cl-letf (((symbol-function 'nelisp-native-funcall-v2-initializer)
                     (lambda (name)
                       (if (eq name 'cons)
                           (lambda (left right)
                             (setq allocations (1+ allocations))
                             (when (= allocations 2)
                               (funcall gc-value) (setq collections (1+ collections)))
                             (funcall cons-value left right))
                         (funcall initializer name)))))
            (setq gc-native (nelisp-native-cache-load fn)))
          (u3b-assert (equal expected (u3b-observe-native fn gc-native args opcode))
                      "GC preserves packed operands, result and buffer effects"))
        (u3b-assert (= collections 1) "forced GC between argument allocations")
        (u3b-assert (= allocations count) "all packed arguments use authenticated F1 CONS"))
      (princ (format "U3B-NATIVE-PASS backend=%S case=%d opcode=%d count=%d native=1 rebound=1 gc=%d allocations=%d\n"
                     nelisp-native-cache-backend index opcode count collections allocations))))
   ((= index 13)
    (let ((fn (native-concat-u3b-function 80 2)) (cases 0))
      (nelisp-native-cache-install 'u3b-types fn)
      (dolist (args (list (list (unibyte-string 65 255) (unibyte-string 66))
                         (list "λ" "尾") (list [65 955] '(66 23614))
                         (list (make-bool-vector 0 nil) nil)
                         (list (make-bool-vector 2 t) "x") (list "x" 'bad)))
        (u3b-assert (equal (native-concat-u3b-observe fn args 80)
                          (u3b-observe-native fn (symbol-function 'u3b-types) args 80 t))
                    "sequence types, byte modes and exact condition/data")
        (setq cases (1+ cases)))
      (princ (format "U3B-TYPES-PASS backend=%S case=13 cases=%d native=%d\n" nelisp-native-cache-backend cases cases))))
   ((= index 14)
    (let* ((selection (getenv "U3B_ERROR_OPCODE"))
           (opcodes (if selection (list (string-to-number selection)) '(80 177))))
      (unless (member opcodes '((80) (177) (80 177))) (error "Invalid U3b error opcode"))
    (dolist (opcode opcodes)
      (let* ((fn (native-concat-u3b-mutation-error opcode))
             (cell (cons 'before 'tail))
             (expected (native-concat-u3b-observe fn (list cell) opcode)) actual)
        (u3b-assert (eq (car (car expected)) 'wrong-type-argument) "expected Lisp type error")
        (nelisp-native-cache-install 'u3b-error fn)
        (setq cell (cons 'before 'tail))
        (setq actual (u3b-observe-native fn (symbol-function 'u3b-error) (list cell) opcode t))
        (u3b-assert (equal expected actual) "exact error and partial INSERT point/text parity")
        (u3b-assert (equal cell '(changed . tail)) "earlier mutation retained; later effect stopped")))
    (princ (format "U3B-ERROR-PASS backend=%S case=14 cases=%d native=%d opcodes=%S\n"
                   nelisp-native-cache-backend (length opcodes) (length opcodes) opcodes))))
   ((= index 15)
    (let* ((fn (native-concat-u3b-chain)) (args '("left" "λ"))
           (expected (native-concat-u3b-observe fn args 80))
           (initializer (symbol-function 'nelisp-native-funcall-v2-initializer))
           (concat-value (nelisp-native-funcall-v2-initializer 'concat))
           (gc-value (symbol-function 'garbage-collect)) (allocations 0) (collections 0) native)
      (nelisp-native-cache-install 'u3b-chain fn)
      (cl-letf (((symbol-function 'nelisp-native-funcall-v2-initializer)
                 (lambda (name)
                   (if (eq name 'concat)
                       (lambda (&rest values)
                         (setq allocations (1+ allocations))
                         (when (= allocations 2)
                           (funcall gc-value) (setq collections (1+ collections)))
                         (apply concat-value values))
                     (funcall initializer name)))))
        (setq native (nelisp-native-cache-load fn)))
      (u3b-assert (equal expected (u3b-observe-native fn native args 80)) "GC retains first concat result")
      (u3b-assert (and (= allocations 2) (= collections 1)) "GC occurs between two concat allocations")
      (princ (format "U3B-GC-PASS backend=%S case=15 allocations=2 gc=1 native=1\n" nelisp-native-cache-backend))))
   (t (error "Unknown U3b fixture")))))
