;;; standalone-desktop-handlers.el --- Genuine GNU autoload declaration controls -*- lexical-binding: t; -*-
(let* ((root (getenv "NELISP_GNU_BUILD_SOURCE_ROOT"))
       (names '(desktop-buffer-mode-handlers desktop-minor-mode-handlers))
       (standalone (eq (plist-get (nelisp-bytecode-compiler-input-dialect) :runtime-evidence)
                       'standalone-build-verified)))
  (if standalone
      (progn
        (dolist (name names)
          (when (boundp name) (error "Desktop declaration fixture already initialized: %S" name)))
        (dolist (invalid (list nil (concat root "missing/")))
          (let ((refused nil))
            (condition-case nil (nelisp-stdlib-desktop-handlers-install invalid)
              (error (setq refused t)))
            (unless (and refused (not (boundp 'desktop-buffer-mode-handlers))
                         (not (boundp 'desktop-minor-mode-handlers)))
              (error "Invalid desktop source published declarations"))))
        (unless (eq (nelisp-stdlib-desktop-handlers-install root) 'installed)
          (error "Desktop declaration installation differs"))
        (dolist (name names)
          (unless (and (boundp name) (null (symbol-value name))
                       (eq (get name 'risky-local-variable) t))
            (error "Genuine desktop declaration/property differs: %S" name)))
        (let ((saved nelisp-stdlib-desktop-handlers--forms) (refused nil))
          (unwind-protect
              (progn
                (setq nelisp-stdlib-desktop-handlers--forms nil)
                (condition-case nil (nelisp-stdlib-desktop-handlers-install root)
                  (error (setq refused t)))
                (unless refused (error "Changed desktop source payload admitted")))
            (setq nelisp-stdlib-desktop-handlers--forms saved)))
        (let ((saved (symbol-function 'eval)) (refused nil))
          (unwind-protect
              (progn
                (fset 'eval (lambda (&rest _args) nil))
                (condition-case nil (nelisp-stdlib-desktop-handlers-install root)
                  (error (setq refused t)))
                (unless refused (error "Changed desktop evaluator owner admitted")))
            (fset 'eval saved))))
    (let ((saved (mapcar (lambda (name) (list (boundp name)
                                            (and (boundp name) (symbol-value name))
                                            (get name 'risky-local-variable))) names)))
      (unless (and (eq (nelisp-stdlib-desktop-handlers-install nil) 'preserved)
                   (equal saved (mapcar (lambda (name) (list (boundp name)
                                                            (and (boundp name) (symbol-value name))
                                                            (get name 'risky-local-variable))) names)))
        (error "GNU desktop declaration owners changed"))))
  (when standalone
    (when (featurep 'desktop) (error "Declaration provider published desktop feature"))
    (let ((desktop-buffer-mode-handlers '((probe-mode . probe-restore))))
      (nelisp-stdlib-desktop-handlers-install root)
      (unless (equal desktop-buffer-mode-handlers '((probe-mode . probe-restore)))
        (error "Existing user desktop handlers changed")))))
(princ "DESKTOP-HANDLERS-PASS\n")
