;;; standalone-bytecode-native-rooted-stack-public-doc-driver.el --- public docref E2E -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'nelisp-bytecode-native-compiler)
(require 'nelisp-bytecode-native-rooted-stack)
(require 'nelisp-bytecode-native-rooted-stack-call)
(require 'nelisp-bytecode-native-package)
(require 'nelisp-native-load)

(defun nelisp-test-rooted-stack-public-doc-smoke ()
  (let* ((source (getenv "NELISP_ROOTED_SOURCE"))
         (elc (getenv "NELISP_ROOTED_ELC"))
         (artifact-dir (getenv "NELISP_ROOTED_ARTIFACT_DIR"))
         (definitions (nelisp-bytecode-native-package-read-elc-functions elc))
         (raw (cdr (assq 'nelisp-rooted-stack-documented-car definitions)))
         (function (make-byte-code (aref raw 0) (aref raw 1) (aref raw 2)
                                   (aref raw 3) (aref raw 4)))
         (input (nelisp-bytecode-compiler-input-build function))
         (argument (list 'doc-value)) (vm-value (funcall function argument))
         (artifact (expand-file-name "public-doc.nelr" artifact-dir))
         (real-loader (symbol-function 'nelisp-native-load-raw-v2-artifact))
         (real-export (symbol-function 'nelisp-native-load-raw-export-address))
         (real-ptr-call (symbol-function 'ptr-call))
         (entry-addresses nil) (entry-count 0) (mapping-count 0) result)
    (unless (and (not (file-exists-p source)) (file-readable-p elc)
                 (eq (plist-get input :status) 'complete)
                 (eq (plist-get input :metadata-role) 'lazy-documentation-reference)
                 (nelisp-bytecode-native-rooted-stack-plan input))
      (error "public docref GNU input preflight failed"))
    (princ "stage: input and VM oracle ready\n")
    (cl-letf (((symbol-function 'nelisp-native-load-raw-v2-artifact)
               (lambda (&rest args)
                 (setq mapping-count (1+ mapping-count))
                 (apply real-loader args)))
              ((symbol-function 'nelisp-native-load-raw-export-address)
               (lambda (mapping name)
                 (let ((address (funcall real-export mapping name)))
                   (when (equal name "nl_native_stack_probe_v1")
                     (push address entry-addresses))
                   address)))
              ((symbol-function 'ptr-call)
               (lambda (address &rest args)
                 (when (memq address entry-addresses)
                   (setq entry-count (1+ entry-count)))
                 (apply real-ptr-call address args))))
      (setq result (nelisp-bytecode-native-compiler-build
                    function artifact "nl_native_stack_probe_v1"))
      (unless (and (eq (plist-get result :status) 'complete)
                   (nelisp-bytecode-native-rooted-stack-authenticated-result-p result))
        (error "public docref compile failed: %S" result))
      (princ "stage: public compile complete\n")
      (let* ((manifest (nelisp-native-load-manifest artifact))
             (descriptors (plist-get (plist-get manifest :native) :imports)))
        (princ (format "stage: real imports %S\n"
                       (mapcar (lambda (d) (list (plist-get d :name)
                                                (plist-get d :kind) (plist-get d :abi)
                                                (plist-get d :index) (plist-get d :address-mode)))
                               descriptors)))
        (let ((bad (copy-tree manifest))
              (before (cons mapping-count entry-count)))
          (setf (plist-get (car (plist-get (plist-get bad :native) :imports))
                           :address-mode) 'resolver)
          (cl-letf (((symbol-function 'nelisp-native-load-manifest)
                     (lambda (_) bad)))
            (condition-case nil
                (nelisp-bytecode-native-rooted-stack-call result argument)
              (error nil)))
          (unless (equal before (cons mapping-count entry-count))
            (error "mutated manifest reached mapping or entry")))
        (princ "stage: mutated mode refused without native effects\n"))
      (garbage-collect)
      (princ "stage: pre-call GC complete\n")
      (let ((before entry-count)
            (native (nelisp-bytecode-native-rooted-stack-call result argument)))
        (unless (and (equal native vm-value) (eq native vm-value)
                     (= entry-count (1+ before)))
          (error "public docref value/dispatch mismatch: %S %S %d"
                 native vm-value entry-count))
        (princ (format "stage: public call returned %S; entries=%d\n" native entry-count)))
      (garbage-collect)
      (princ "stage: post-call GC complete\n")
      (let ((native-error (condition-case err
                              (nelisp-bytecode-native-rooted-stack-call result 9)
                            (wrong-type-argument err)))
            (vm-error (condition-case err (funcall function 9)
                        (wrong-type-argument err))))
        (unless (and (consp native-error)
                     (eq (car native-error) 'wrong-type-argument)
                     (equal native-error vm-error))
          (error "wrong-type payload differs: %S %S" native-error vm-error))
        (princ "stage: wrong-type payload matched GNU VM\n"))
      (garbage-collect)
      (princ "stage: post-error GC complete\n")
      (unless (eq (nelisp-bytecode-native-rooted-stack-call result argument) vm-value)
        (error "post-error public caller recovery failed"))
      (princ (format "stage: post-error call passed; entries=%d\n" entry-count)))))

(provide 'standalone-bytecode-native-rooted-stack-public-doc-driver)
;;; standalone-bytecode-native-rooted-stack-public-doc-driver.el ends here
