;;; standalone-native-funcall-v2-driver.el --- F1 root ABI controls -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'nelisp-native-load)
(defun f1-root-assert (value label) (unless value (error "F1 roots: %s" label)))
(defun f1-root-case (function arguments &optional malformed)
  (let* ((env (nelisp--native-env))
         (begin (nelisp-native-load--symbol-addr "nl_root_pin_begin_v2"))
         (reserve (nelisp-native-load--symbol-addr "nl_root_pin_reserve_v2"))
         (end (nelisp-native-load--symbol-addr "nl_root_pin_end_v2"))
         (slot (nelisp-native-load--symbol-addr "nl_root_pin_slot_v2"))
         (entry (nelisp-native-load--symbol-addr "nl_native_funcall_v2"))
         (ticket (ptr-call begin env 0 0 0 0 0))
         (marker nil) (answer nil))
    (f1-root-assert (> ticket 0) "begin")
    (unwind-protect
        (progn
          (dotimes (i 20)
            (let ((address (ptr-call reserve env ticket 0 0 0 0)))
              (when (= i 0) (setq marker address))
              (f1-root-assert (= address (+ marker (* i 32))) "contiguous frame")))
          (f1-root-assert (> (nelisp--native-pin-copy-v2 env ticket 1 function) 0) "function root")
          (cl-loop for argument in arguments for i from 2 do
                   (f1-root-assert (> (nelisp--native-pin-copy-v2 env ticket i argument) 0) "argument root"))
          (let ((status (if malformed
                            (ptr-call entry env (+ ticket 1) 1 2 (length arguments) 12)
                          (ptr-call entry env ticket 1 2 (length arguments) 12))))
            (if malformed (f1-root-assert (= status 2) "malformed ticket refused")
              (f1-root-assert (= status 0) "normal result")
              (setq answer (nelisp-native-load-unbox (ptr-call slot env ticket 12 0 0 0) env marker)))))
      (f1-root-assert (= (ptr-call end env ticket 0 0 0 0) 1) "end"))
    answer))
(defun f1-root-user (x) x)
(let ((object (vector 'mutable)) (state (list 'captured)))
  (f1-root-assert (eq (f1-root-case (lambda () 'zero) nil) 'zero) "N=0 lambda")
  (f1-root-assert (= (f1-root-case (lambda (a b c d e f) (+ a b c d e f)) '(1 2 3 4 5 6)) 21) "N>5")
  (f1-root-assert (eq (f1-root-case (lambda (&rest _) state) '(a b c d e f)) state) "closure identity")
  (f1-root-assert (eq (f1-root-case 'f1-root-user (list object)) object) "user symbol identity")
  (fset 'f1-root-user (lambda (_) 'redefined))
  (f1-root-assert (eq (f1-root-case 'f1-root-user (list object)) 'redefined) "redefinition")
  (f1-root-case 'f1-root-user (list object) t)
  (princ "F1-ROOTS-PASS cases=6\n"))
