;;; -*- lexical-binding: t; -*-
(load (expand-file-name "lisp/nelisp-native-load.el" (getenv "NELISP_REPO_ROOT")) nil nil t)
(load (expand-file-name "test/fixtures/aot-evalorder-functions.el" (getenv "NELISP_REPO_ROOT")) nil nil t)
(defun shl (a b) (ash a b))
(defun aot-order-reset (memory)
  (ptr-write-u64 memory 0 0)
  (ptr-write-u64 memory 8 7)
  (ptr-write-u64 memory 16 0)
  (ptr-write-u64 memory 24 5)
  (ptr-write-u64 memory 32 0)
  (ptr-write-u64 memory 40 3)
  (ptr-write-u64 memory 48 0))
(defun aot-order-trace (memory)
  (let ((node (ptr-read-u64 memory 0)) trace (count 0))
    (while (> node 0)
      (when (>= count 3) (error "Cyclic AOT trace"))
      (push (ptr-read-u64 node 0) trace)
      (setq node (ptr-read-u64 node 8) count (1+ count)))
    (nreverse trace)))
(let* ((artifact (getenv "AOT_ORDER_ARTIFACT"))
       (handle (nelisp-native-load-artifact artifact "aot-order-run"))
       (memory (alloc-bytes 56 8))
       (names '(aot-order-add aot-order-sub aot-order-mul aot-order-div
                aot-order-mod aot-order-or aot-order-and aot-order-xor
                aot-order-less aot-order-shift aot-order-three aot-order-call))
       (mode 0) failures)
  (unwind-protect
      (progn
        (dolist (name names)
          (let* ((args (list mode memory (+ memory 8) (+ memory 24) (+ memory 40)))
                 (_ (aot-order-reset memory))
                 (expected (apply #'aot-order-run args))
                 (trace (aot-order-trace memory)))
            (aot-order-reset memory)
            (let* ((actual (nelisp-native-load-call handle args))
                   (actual-trace (aot-order-trace memory)))
              (princ (format "%s actual=%S/%S expected=%S/%S\n" name actual actual-trace expected trace))
              (unless (and (equal actual expected) (equal actual-trace trace))
                (push name failures))))
          (setq mode (1+ mode)))
        (when failures (error "AOT argument evaluation order: %S" failures))
        (princ "AOT-EVALORDER-PASS cases=12\n"))
    (nelisp-native-load-unload handle)))
