;;; standalone-derived-parent.el --- Genuine mode parent/cache behavior -*- lexical-binding: t; -*-
(let ((root (getenv "NELISP_GNU_BUILD_SOURCE_ROOT"))
      (standalone (eq (plist-get (nelisp-bytecode-compiler-input-dialect) :runtime-evidence)
                      'standalone-build-verified)))
  (if standalone
      (progn
        (dolist (invalid (list nil (concat root "missing/")))
          (let ((refused nil))
            (condition-case nil (nelisp-stdlib-derived-parent-install invalid)
              (error (setq refused t)))
            (unless (and refused (not (fboundp 'derived-mode-set-parent)))
              (error "Invalid mode parent source admitted"))))
        (fset 'derived-mode-set-parent (lambda (&rest _args) nil))
        (unwind-protect
            (let ((refused nil))
              (condition-case nil (nelisp-stdlib-derived-parent-install root)
                (error (setq refused t)))
              (unless refused (error "Foreign standalone mode setter admitted")))
          (fmakunbound 'derived-mode-set-parent))
        (unless (eq (nelisp-stdlib-derived-parent-install root) 'installed)
          (error "Mode parent installation differs")))
    (let ((saved (symbol-function 'derived-mode-set-parent)))
      (unless (and (eq (nelisp-stdlib-derived-parent-install nil) 'preserved)
                   (eq saved (symbol-function 'derived-mode-set-parent)))
        (error "GNU mode parent owner changed"))))
  (let ((a (make-symbol "parent-probe-a"))
        (b (make-symbol "parent-probe-b"))
        (c (make-symbol "parent-probe-c")))
    (put a 'derived-mode--all-parents (list a b))
    (put b 'derived-mode--all-parents (list b c))
    (put c 'derived-mode--all-parents (list c a))
    (put a 'derived-mode--followers (list b))
    (put b 'derived-mode--followers (list c))
    (put c 'derived-mode--followers (list a))
    (derived-mode-set-parent a c)
    (unless (eq (get a 'derived-mode-parent) c)
      (error "Parent registration does not update real mode property"))
    (dolist (mode (list a b c))
      (unless (and (null (get mode 'derived-mode--all-parents))
                   (null (get mode 'derived-mode--followers)))
        (error "Cyclic follower invalidation differs")))
    (derived-mode-set-parent a nil)
    (unless (null (get a 'derived-mode-parent)) (error "Parent removal differs")))
  (let ((refused nil))
    (condition-case nil (derived-mode-set-parent 1 nil)
      (wrong-type-argument (setq refused t)))
    (unless refused (error "Nonsymbol mode accepted")))
  (when standalone
    (let ((saved (symbol-function 'put)) (refused nil))
      (unwind-protect
          (progn
            (fset 'put (lambda (&rest _args) nil))
            (condition-case nil (nelisp-stdlib-derived-parent-install root)
              (error (setq refused t)))
            (unless refused (error "Changed mode property owner admitted")))
        (fset 'put saved)))))
(princ "DERIVED-PARENT-PASS\n")
