//! `nelisp-runtime` CLI smoke binary (Phase 7.0) + Phase 7.5.1
//! FFI-bridge MVP (`exec-bytes`).
//!
//! `--syscall-smoke` exercises a representative slice of the FFI
//! surface end-to-end so the ERT smoke layer (Doc 27 §3 7.0 gate) can
//! prove the cdylib symbols actually link and run, without committing
//! Phase 7.0 to a fully working Elisp ↔ Rust FFI bridge (that lands
//! in Phase 7.5).
//!
//! `exec-bytes <path>` (Phase 7.5.1 MVP) reads a raw machine-code byte
//! stream from PATH, copies it into a freshly-mmapped JIT-capable page,
//! flips the page to PROT_READ|PROT_EXEC (with the macOS Apple Silicon
//! `pthread_jit_write_protect_np` + `__clear_cache` dance when needed),
//! calls the bytes as `extern "C" fn() -> i64`, prints
//! `RESULT: <i64>\n` to stdout, and unmaps.  This is the bridge that
//! lets Phase 7.1.X NeLisp backends test their generated bytes against
//! a real CPU, without an in-process Emacs FFI module — that lands in
//! Phase 7.5 proper.
//!
//! Exit codes:
//!   0 — all probes green
//!   1 — write probe failed (or `exec-bytes` argument missing)
//!   2 — usage / unknown subcommand
//!   3 — mmap / munmap probe failed
//!   4 — getenv probe failed (or `exec-bytes` read failed)
//!   5 — stat probe failed (or `exec-bytes` mprotect failed)
//!   6 — `exec-bytes` empty input

use std::env;
use std::ffi::CString;

fn syscall_smoke() -> i32 {
    // 1. write to stdout via the nelisp_syscall_write FFI symbol
    let msg: &[u8] = b"nelisp-runtime syscall smoke OK\n";
    unsafe {
        let n = nelisp_runtime::nelisp_syscall_write(1, msg.as_ptr(), msg.len());
        if n != msg.len() as isize {
            return 1;
        }
    }

    // 2. mmap an anonymous private 4 KiB page, touch it, munmap.  This
    //    is the path Phase 7.2 (allocator) and Phase 7.1 (native code
    //    pages via PROT_EXEC) will both inherit, so we want a hard
    //    failure here if the symbol or constants are wrong.
    unsafe {
        let prot = nelisp_runtime::NELISP_PROT_READ | nelisp_runtime::NELISP_PROT_WRITE;
        let flags = nelisp_runtime::NELISP_MAP_PRIVATE | nelisp_runtime::NELISP_MAP_ANONYMOUS;
        let p = nelisp_runtime::nelisp_syscall_mmap(
            std::ptr::null_mut(),
            4096,
            prot,
            flags,
            -1,
            0,
        );
        if p.is_null() || p as isize == -1 {
            return 3;
        }
        // Touch first byte to prove the page is actually mapped, then
        // release it.
        *p = 0x42;
        if nelisp_runtime::nelisp_syscall_munmap(p, 4096) != 0 {
            return 3;
        }
    }

    // 3. getenv("PATH") — should not be NULL on any reasonable host
    //    that runs `cargo test` or `make test-runtime`.
    unsafe {
        let name = CString::new("PATH").unwrap();
        let v = nelisp_runtime::nelisp_syscall_getenv(name.as_ptr());
        if v.is_null() {
            return 4;
        }
    }

    // 4. stat the binary itself.  argv[0] may not be an absolute path,
    //    but `/proc/self/exe` (Linux) or `current_exe` (cross-platform)
    //    reliably points at a file the kernel just executed.
    unsafe {
        if let Ok(exe) = env::current_exe() {
            let cpath = CString::new(exe.to_string_lossy().as_bytes()).unwrap();
            let mut sb = nelisp_runtime::NelispStat::default();
            let r = nelisp_runtime::nelisp_syscall_stat(cpath.as_ptr(), &mut sb);
            if r != 0 || sb.st_size <= 0 {
                return 5;
            }
        }
    }

    0
}

/// Phase 7.5.1 MVP: read a raw machine-code byte stream from PATH,
/// install it on a fresh JIT page, jump into it.
///
/// Layout:
///   1. read PATH → bytes (Vec<u8>).  Empty file = exit 6.
///   2. mmap a `page_size`-rounded RW page (with MAP_JIT on Apple Silicon).
///   3. macOS arm64: `jit_write_protect(0)` so the current thread can
///      write the JIT page.
///   4. memcpy bytes into the page.
///   5. macOS arm64: `jit_write_protect(1)` so the page is exec-only.
///      Linux / x86_64: `mprotect(PROT_READ|PROT_EXEC)`.
///   6. `clear_icache(start, end)` — no-op on x86_64, mandatory on arm64.
///   7. `transmute` page pointer to `extern "C" fn() -> i64` and call.
///   8. Print `RESULT: <i64>\n` to stdout.
///   9. munmap.
///
/// The MVP intentionally does *not* support arguments — Phase 7.1.X
/// scaffolding emits `() -> i64` ABI bytes, which is enough to verify
/// the byte stream actually executes on real hardware.  Arg passing
/// lands in Phase 7.5 proper alongside the in-process FFI bridge.
fn exec_bytes(path: &str) -> i32 {
    let bytes = match std::fs::read(path) {
        Ok(b) => b,
        Err(e) => {
            eprintln!("nelisp-runtime: read {}: {}", path, e);
            return 4;
        }
    };
    let len = bytes.len();
    if len == 0 {
        eprintln!("nelisp-runtime: exec-bytes: empty input file {}", path);
        return 6;
    }

    // Page-align upward.  Use 4 KiB as a portable lower bound; even on
    // hosts whose real page size is 16 KiB the kernel will round up
    // internally, so over-allocating per-page granularity is safe.
    let page_size: usize = 4096;
    let mapped_size = ((len + page_size - 1) / page_size) * page_size;

    unsafe {
        let map_jit = nelisp_runtime::NELISP_MAP_JIT;
        let prot_rw = nelisp_runtime::NELISP_PROT_READ | nelisp_runtime::NELISP_PROT_WRITE;
        let flags = nelisp_runtime::NELISP_MAP_PRIVATE
            | nelisp_runtime::NELISP_MAP_ANONYMOUS
            | map_jit;

        let p = nelisp_runtime::nelisp_syscall_mmap_jit(
            std::ptr::null_mut(),
            mapped_size,
            prot_rw,
            flags,
            -1,
            0,
        );
        if p.is_null() || p as isize == -1 {
            eprintln!("nelisp-runtime: exec-bytes: mmap_jit failed");
            return 3;
        }

        // macOS Apple Silicon: opt the current thread into write mode.
        // No-op on Linux / x86_64.
        nelisp_runtime::nelisp_syscall_jit_write_protect(0);

        std::ptr::copy_nonoverlapping(bytes.as_ptr(), p, len);

        // Lock the page back to exec-only on Apple Silicon, and flip
        // permissions to PROT_READ|PROT_EXEC on Linux / x86_64 where
        // MAP_JIT is a no-op and the page is still RW.
        nelisp_runtime::nelisp_syscall_jit_write_protect(1);

        let prot_rx = nelisp_runtime::NELISP_PROT_READ | nelisp_runtime::NELISP_PROT_EXEC;
        let mp = nelisp_runtime::nelisp_syscall_mprotect(p, mapped_size, prot_rx);
        if mp != 0 {
            eprintln!("nelisp-runtime: exec-bytes: mprotect(RX) failed");
            // Best-effort cleanup before we bail.
            let _ = nelisp_runtime::nelisp_syscall_munmap(p, mapped_size);
            return 5;
        }

        // arm64 demands an explicit I-cache flush across the bytes
        // we just wrote; x86_64 is a no-op.  Pass exact write extent
        // so the host's `__clear_cache` only invalidates what changed.
        let _ = nelisp_runtime::nelisp_syscall_clear_icache(p, p.add(len));

        // Hand the page off to the CPU.  We assume the bytes implement
        // the System V AMD64 / AAPCS64 ABI for `extern "C" fn() -> i64`.
        let func: extern "C" fn() -> i64 = std::mem::transmute(p);
        let result = func();

        println!("RESULT: {}", result);

        let _ = nelisp_runtime::nelisp_syscall_munmap(p, mapped_size);
    }

    0
}

fn main() {
    let args: Vec<String> = env::args().collect();
    let code = match args.get(1).map(|s| s.as_str()) {
        Some("--syscall-smoke") => syscall_smoke(),
        Some("--version") => {
            println!("nelisp-runtime {}", env!("CARGO_PKG_VERSION"));
            0
        }
        Some("exec-bytes") => match args.get(2).map(|s| s.as_str()) {
            Some(path) => exec_bytes(path),
            None => {
                eprintln!("usage: nelisp-runtime exec-bytes <bytes-file>");
                1
            }
        },
        _ => {
            eprintln!("usage: nelisp-runtime --syscall-smoke");
            eprintln!("       nelisp-runtime --version");
            eprintln!("       nelisp-runtime exec-bytes <bytes-file>");
            2
        }
    };
    std::process::exit(code);
}
