//! Doc 84 §84.2 (2026-05-10) — Syscall name → number table codegen.
//!
//! Emits `lisp/nelisp-syscall-table.el` containing the
//! `nelisp--syscall-nr-table' alist + `nelisp--syscall-nr-resolve'
//! resolver consumed by `lisp/nelisp-jit-strategy.el' (= the
//! `nelisp--syscall' wrapper's `nr-int' lookup).  Replaces the
//! pre-Doc-84 Rust `bi_syscall_nr_resolve' primitive in
//! `build-tool/src/jit/strategy.rs' (= -13 Rust LOC in `src/').
//!
//! The 1:1 source-of-truth for the syscall name → number map is the
//! `syscall_nr` helper in `build-tool/src/eval/builtins.rs' which the
//! `bi_syscall' primitive still consumes for the bare `(nelisp--
//! syscall NR &rest ARGS)' fast path.  This codegen mirrors that map
//! into elisp so the wrapper's symbol → number step is pure elisp.
//!
//! Cross-platform: on non-Linux targets the generated file emits a
//! `nelisp--syscall-nr-resolve' that signals `arith-error' (= same
//! semantics as the pre-Doc-84 `cfg(not(target_os = "linux"))'
//! variant).  Per Doc 62 Phase 5 §5.8, non-Linux nelisp routes all
//! syscall callers through `nl-ffi-call' libc instead, so the
//! resolver is a dead path there but still callable.

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=CARGO_CFG_TARGET_OS");

    let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR must be set by cargo");
    let out_path = std::path::Path::new(&manifest_dir)
        .join("..")
        .join("lisp")
        .join("nelisp-syscall-table.el");

    let body = if target_os == "linux" {
        emit_linux_table()
    } else {
        emit_unsupported_stub(&target_os)
    };

    // Only write if content differs (= avoid touching mtime + spurious
    // image rebakes on no-op rebuilds).
    let existing = std::fs::read_to_string(&out_path).unwrap_or_default();
    if existing != body {
        std::fs::write(&out_path, &body)
            .unwrap_or_else(|e| panic!("write {} failed: {}", out_path.display(), e));
    }
}

fn emit_linux_table() -> String {
    // 1:1 mirror of `syscall_nr' in `src/eval/builtins.rs'.  When that
    // map gains entries, add them here too (= sole syscall-nr source
    // of truth pair).  Each entry is `(NAME . NUMBER)' where NAME is
    // a symbol string and NUMBER is the host `libc::SYS_*' i64.
    let entries: &[(&str, i64)] = &[
        ("read",              libc::SYS_read              as i64),
        ("write",             libc::SYS_write             as i64),
        ("close",             libc::SYS_close             as i64),
        ("openat",            libc::SYS_openat            as i64),
        ("exit_group",        libc::SYS_exit_group        as i64),
        ("lseek",             libc::SYS_lseek             as i64),
        ("dup2",              libc::SYS_dup2              as i64),
        ("getpid",            libc::SYS_getpid            as i64),
        ("kill",              libc::SYS_kill              as i64),
        // Doc 54 Phase 3 — Core-12 additions.
        ("mmap",              libc::SYS_mmap              as i64),
        ("mprotect",          libc::SYS_mprotect          as i64),
        ("munmap",            libc::SYS_munmap            as i64),
        ("fcntl",             libc::SYS_fcntl             as i64),
        // Doc 55 Phase 4 — Posix-30 int-only additions.
        ("fork",              libc::SYS_fork              as i64),
        ("socket",            libc::SYS_socket            as i64),
        ("listen",            libc::SYS_listen            as i64),
        ("wait4",             libc::SYS_wait4             as i64),
        ("getppid",           libc::SYS_getppid           as i64),
        ("setpgid",           libc::SYS_setpgid           as i64),
        // Doc 57 Phase 4.3 — modern Linux event surface.
        ("pidfd_open",        libc::SYS_pidfd_open        as i64),
        ("pidfd_send_signal", libc::SYS_pidfd_send_signal as i64),
        ("inotify_init1",     libc::SYS_inotify_init1     as i64),
        ("inotify_rm_watch",  libc::SYS_inotify_rm_watch  as i64),
        ("eventfd2",          libc::SYS_eventfd2          as i64),
        // Doc 59 Phase 4.2 + 4.3.1 — timerfd_create int-only.
        ("timerfd_create",    libc::SYS_timerfd_create    as i64),
    ];

    let mut s = String::new();
    s.push_str(";;; nelisp-syscall-table.el --- Doc 84 §84.2 syscall nr table  -*- lexical-binding: t; -*-\n");
    s.push_str("\n;;; Commentary:\n\n");
    s.push_str(";; AUTO-GENERATED by `build-tool/build.rs' from `libc::SYS_*'\n");
    s.push_str(";; constants on the host target.  DO NOT EDIT BY HAND — edits\n");
    s.push_str(";; will be clobbered on the next `cargo build'.  When the Rust\n");
    s.push_str(";; `syscall_nr' helper in `build-tool/src/eval/builtins.rs'\n");
    s.push_str(";; gains a new arm, add a matching entry to `emit_linux_table'\n");
    s.push_str(";; in `build-tool/build.rs'.\n");
    s.push_str(";;\n");
    s.push_str(";; Doc 84 §84.2 (2026-05-10) replaces the Rust `bi_syscall_nr_\n");
    s.push_str(";; resolve' primitive (= `jit/strategy.rs') with this elisp\n");
    s.push_str(";; lookup; consumed by `nelisp-jit-strategy.el' for the\n");
    s.push_str(";; `nelisp--syscall' wrapper's symbol → i64 step.\n\n");
    s.push_str(";;; Code:\n\n");
    // Use bare `setq' instead of `defconst' because this file loads
    // BEFORE `nelisp-stdlib-eval-special.el' which provides the
    // `defconst' macro.  `setq' is a Tier 1 special form available
    // from the very first `eval' call.  The resulting binding is
    // mutable from elisp's perspective but conceptually a constant.
    s.push_str("(setq nelisp--syscall-nr-table\n      '(\n");
    for (name, nr) in entries {
        s.push_str(&format!("        ({} . {})\n", name, nr));
    }
    s.push_str("        ))\n\n");
    s.push_str("(fset 'nelisp--syscall-nr-resolve\n");
    s.push_str("      (lambda (name)\n");
    // Body uses only Tier 1 forms (`let' / `if') and Rust builtins
    // (`assq' / `cdr' / `signal' / `cons').  `assq' is itself defined
    // in `nelisp-stdlib-search.el' (loaded after this file), but the
    // resolver is only INVOKED at user-syscall time which is well
    // after stdlib finishes.  At LOAD time we only `fset' the lambda
    // — its body isn't evaluated.
    s.push_str("        (let ((cell (assq name nelisp--syscall-nr-table)))\n");
    s.push_str("          (if cell\n");
    s.push_str("              (cdr cell)\n");
    s.push_str("            (signal 'arith-error\n");
    s.push_str("                    (cons \"nelisp--syscall-nr-resolve: unknown syscall\"\n");
    s.push_str("                          (cons name nil)))))))\n\n");
    s.push_str(";; (provide 'nelisp-syscall-table) — omitted: this file is\n");
    s.push_str(";; loaded during bootstrap before `provide' is installed.\n");
    s.push_str(";;; nelisp-syscall-table.el ends here\n");
    s
}

fn emit_unsupported_stub(target_os: &str) -> String {
    let mut s = String::new();
    s.push_str(";;; nelisp-syscall-table.el --- Doc 84 §84.2 syscall nr table (non-Linux stub)  -*- lexical-binding: t; -*-\n");
    s.push_str("\n;;; Commentary:\n\n");
    s.push_str(&format!(";; AUTO-GENERATED by `build-tool/build.rs' for target_os = {}.\n", target_os));
    s.push_str(";; Per Doc 62 Phase 5 §5.8, non-Linux nelisp routes syscall\n");
    s.push_str(";; callers through `nl-ffi-call' libc bindings; this resolver\n");
    s.push_str(";; is a dead path and signals `arith-error' if invoked.\n\n");
    s.push_str(";;; Code:\n\n");
    // See Linux variant for the `setq'-instead-of-`defconst' rationale.
    s.push_str("(setq nelisp--syscall-nr-table nil)\n\n");
    s.push_str("(fset 'nelisp--syscall-nr-resolve\n");
    s.push_str("      (lambda (name)\n");
    s.push_str("        (let ((_ name))\n");
    s.push_str("          (signal 'arith-error\n");
    s.push_str("                  (cons \"nelisp--syscall-nr-resolve: unsupported platform\" nil)))))\n\n");
    s.push_str(";;; nelisp-syscall-table.el ends here\n");
    s
}
