;;; emacs-cc-ccl-1.el --- CCL primitive compatibility -*- lexical-binding: t; -*-

(defvar emacs-cc-ccl-1--programs nil)
(defvar emacs-cc-ccl-1--maps nil)
(defvar emacs-cc-ccl-1--next-program-index 0)
(defvar emacs-cc-ccl-1--next-map-index 0)

(defun emacs-cc-ccl-1--register (table next name value)
  (let ((entry (assq name (symbol-value table))))
    (if entry
        (progn (setcdr entry (cons (cadr entry) value)) (cadr entry))
      (let ((index (symbol-value next)))
        (set next (1+ index))
        (set table (cons (list name index value) (symbol-value table)))
        index))))

(unless (fboundp 'ccl-execute)
  (defun ccl-execute (ccl-prog reg)
    "Execute CCL-PROGRAM with registers initialized by REGISTERS.

CCL-PROGRAM is a CCL program name (symbol) or compiled code generated by
`ccl-compile'.  REGISTERS is a vector of initial register values."
    (ignore reg)
    (signal 'error '("Invalid CCL program"))))

(unless (fboundp 'ccl-execute-on-string)
  (defun ccl-execute-on-string (ccl-program status string &optional continue unibyte-p)
    "Execute CCL-PROGRAM with initial STATUS on STRING.

Return the contents of the output buffer.  STATUS is updated as the CCL
program runs; CONTINUE preserves its instruction counter on exhausted input.
UNIBYTE-P requests a unibyte result."
    (ignore status string continue unibyte-p)
    (signal 'error '("Invalid CCL program"))))

(unless (fboundp 'ccl-program-p)
  (defun ccl-program-p (object)
    "Return t if OBJECT is a CCL program name or compiled CCL program code."
    (or (vectorp object)
        (and (symbolp object) (assq object emacs-cc-ccl-1--programs) t))))

(unless (fboundp 'register-ccl-program)
  (defun register-ccl-program (name ccl-prog)
    "Register compiled CCL-PROG as NAME, or reserve NAME when it is nil.
Return the program index."
    (unless (symbolp name) (signal 'wrong-type-argument (list 'symbolp name)))
    (unless (or (null ccl-prog) (vectorp ccl-prog))
      (signal 'wrong-type-argument (list 'vectorp ccl-prog)))
    (when ccl-prog (signal 'error '("Error in CCL program")))
    (emacs-cc-ccl-1--register 'emacs-cc-ccl-1--programs
                              'emacs-cc-ccl-1--next-program-index name ccl-prog)))

(unless (fboundp 'register-code-conversion-map)
  (defun register-code-conversion-map (symbol map)
    "Register SYMBOL as code conversion map MAP and return its index."
    (unless (vectorp map) (signal 'wrong-type-argument (list 'vectorp map)))
    (unless (symbolp symbol) (signal 'wrong-type-argument (list 'symbolp symbol)))
    (emacs-cc-ccl-1--register 'emacs-cc-ccl-1--maps
                              'emacs-cc-ccl-1--next-map-index symbol map)))

(provide 'emacs-cc-ccl-1)
