;;; emacs-cc-font-1.el --- Font C-core compatibility -*- lexical-binding: t; -*-

(defun emacs-cc-font-1--font-kind (object)
  (cond ((and (vectorp object) (eq (aref object 0) 'font-spec)) 'font-spec)
        ((and (consp object) (eq (car object) 'font-spec)) 'font-spec)
        ((and (vectorp object) (eq (aref object 0) 'font-entity)) 'font-entity)
        ((and (vectorp object) (eq (aref object 0) 'font-object)) 'font-object)))

(defvar emacs-cc-font-1--cache-generation 0)

(unless (fboundp 'clear-font-cache)
  (defun clear-font-cache () "Clear font cache of each frame."
    (setq emacs-cc-font-1--cache-generation
          (1+ emacs-cc-font-1--cache-generation))
    nil))

(unless (fboundp 'close-font)
  (defun close-font (font-object &optional frame) "Close FONT-OBJECT."
    (ignore frame)
    (unless (eq (emacs-cc-font-1--font-kind font-object) 'font-object)
      (signal 'wrong-type-argument (list 'font-object font-object)))
    nil))

(unless (fboundp 'find-font)
  (defun find-font (font-spec &optional frame)
    "Return a font-entity matching with FONT-SPEC on the current frame."
    (ignore frame)
    (unless (eq (emacs-cc-font-1--font-kind font-spec) 'font-spec)
      (signal 'wrong-type-argument (list 'font-spec font-spec)))
    nil))

(unless (fboundp 'font-at)
  (defun font-at (position &optional window string)
    "Return a font-object for displaying a character at POSITION."
    (ignore window)
    (unless (or (integerp position) (markerp position))
      (signal 'wrong-type-argument (list 'integer-or-marker-p position)))
    (when (and (not string)
               (let ((b (current-buffer)))
                 (and (bufferp b)
                      (or (< position (point-min)) (> position (point-max))))))
      (signal 'args-out-of-range (list position (point-min) (point-max))))
    nil))

(unless (fboundp 'font-face-attributes)
  (defun font-face-attributes (font &optional frame)
    "Return a plist of face attributes generated by FONT."
    (ignore frame)
    (cond
     ((stringp font)
      (list :family font))
     ((eq (emacs-cc-font-1--font-kind font) 'font-spec)
      (let ((tail (if (consp font) (cdr font) nil)) result)
        (while tail
          (let ((key (pop tail)) (value (pop tail)))
            (when (memq key '(:family :height :weight :slant :width))
              (setq result (append result (list key value))))))
        result))
     (t
      (signal 'error (list "Invalid font object"))))))

(unless (fboundp 'font-family-list)
  (defun font-family-list (&optional frame)
    "List available font families on the current frame."
    (when (and frame (not (and (fboundp 'frame-live-p) (frame-live-p frame))))
      (signal 'wrong-type-argument (list 'frame-live-p frame)))))

(unless (fboundp 'font-get)
  (defun font-get (font key)
    "Return the value of FONT's property KEY."
    (unless (emacs-cc-font-1--font-kind font)
      (signal 'wrong-type-argument (list 'font font)))
    (if (and (consp font) (eq (car font) 'font-spec))
        (plist-get (cdr font) key)
      nil)))

(unless (fboundp 'font-get-glyphs)
  (defun font-get-glyphs (font-object from to &optional object)
    "Return a vector of FONT-OBJECT's glyphs for the specified characters."
    (ignore from to object)
    (unless (eq (emacs-cc-font-1--font-kind font-object) 'font-object)
      (signal 'wrong-type-argument (list 'font-object font-object)))
    []))

(unless (fboundp 'font-has-char-p)
  (defun font-has-char-p (font ch &optional frame)
    "Return non-nil if FONT on FRAME has a glyph for character CH."
    (ignore frame)
    (unless (memq (emacs-cc-font-1--font-kind font) '(font-entity font-object))
      (signal 'wrong-type-argument (list 'font font)))
    (unless (characterp ch) (signal 'wrong-type-argument (list 'characterp ch)))
    nil))

(unless (fboundp 'font-info)
  (defun font-info (name &optional frame)
    "Return information about a font named NAME on frame FRAME."
    (unless (stringp name) (signal 'wrong-type-argument (list 'stringp name)))
    (when (and frame (not (and (fboundp 'frame-live-p) (frame-live-p frame))))
      (signal 'wrong-type-argument (list 'frame-live-p frame)))
    (signal 'error (list "Window system frame should be used"))))

(unless (fboundp 'font-match-p)
  (defun font-match-p (spec font)
    "Return t if and only if font-spec SPEC matches with FONT."
    (unless (eq (emacs-cc-font-1--font-kind spec) 'font-spec)
      (signal 'wrong-type-argument (list 'font-spec spec)))
    (unless (emacs-cc-font-1--font-kind font)
      (signal 'wrong-type-argument (list 'font font)))
    (let ((props (if (consp spec) (cdr spec) nil)))
      (catch 'mismatch
        (while props
          (let ((key (pop props)) (value (pop props)))
            (when (and value (font-get font key)
                       (not (equal value (font-get font key))))
              (throw 'mismatch nil))))
        t))))

(unless (fboundp 'fontp)
  (defun fontp (object &optional extra-type)
    "Return t if OBJECT is a font-spec, font-entity, or font-object."
    (when (and extra-type (not (memq extra-type '(font-spec font-entity font-object))))
      (signal 'wrong-type-argument (list 'font-extra-type extra-type)))
    (let ((kind (emacs-cc-font-1--font-kind object)))
      (and kind (or (null extra-type) (eq kind extra-type)) t))))

(provide 'emacs-cc-font-1)
