;;; C1 shared command-loop regressions. -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'emacs-command-loop-builtins)
(require 'emacs-edit-builtins)
(require 'emacs-undo)
(require 'emacs-keymap-builtins)

(ert-deftest c1-command/public-hook-order ()
  (let ((emacs-keymap-global-map (emacs-keymap-make-sparse-keymap))
        (emacs-command-loop--unread-events nil)
        (this-command nil) (last-command nil) (real-this-command nil)
        trace)
    (cl-letf (((symbol-function 'c1-test-first)
               (lambda () (interactive) (setq this-command 'c1-test-rewritten)))
              ((symbol-function 'c1-test-second) (lambda () (interactive))))
      (emacs-keymap-define-key emacs-keymap-global-map [f21] 'c1-test-first)
      (emacs-keymap-define-key emacs-keymap-global-map [f22] 'c1-test-second)
      (let* ((hook (lambda () (push (list this-command last-command real-this-command) trace)))
             (pre-command-hook (list hook)) (post-command-hook (list hook)))
        (emacs-command-loop-feed-events 'f21 'f22)
        (emacs-command-loop-drain))
      (should (equal (nreverse trace)
                     '((c1-test-first nil c1-test-first)
                       (c1-test-rewritten nil c1-test-first)
                       (c1-test-second c1-test-rewritten c1-test-second)
                       (c1-test-second c1-test-rewritten c1-test-second)))))))

(ert-deftest c1-command/canonical-modifier-events ()
  (let ((emacs-command-loop--this-command-key-events [])
        (emacs-command-loop--this-command-keys ""))
    (emacs-command-loop-record-key 134217825)
    (emacs-command-loop-record-key 'S-left)
    (should (equal [134217825 S-left] (emacs-command-loop-this-command-keys-vector))))
  (dolist (event '(0 9 65 97 134217825 201326689 268435553 S-left M-S-left))
    (should (equal (event-modifiers event) (emacs-keymap-event-modifiers event)))
    (should (equal (event-basic-type event) (emacs-keymap-event-basic-type event)))))

(defun c1-command-test--newline ()
  "Extract the standalone newline definition so host tests exercise our body."
  (with-temp-buffer
    (insert-file-contents (locate-library "emacs-edit-builtins"))
    (goto-char (point-min))
    (search-forward "(when (emacs-edit-builtins--install-function-p 'newline)")
    (beginning-of-line)
    (let ((definition (caddr (read (current-buffer)))))
      (setcar (cdr definition) 'c1-test-newline)
      (eval definition t))))

(ert-deftest c1-command/newline-buffer-owner ()
  (c1-command-test--newline)
  (let* ((nelisp-ec--buffers nil)
         (nelisp-ec--current-buffer (nelisp-ec-generate-new-buffer "c1-pure")))
    (with-temp-buffer
      (insert "a")
      (c1-test-newline 2)
      (should (equal "a\n\n" (buffer-string)))
      (should (equal "" (nelisp-ec-buffer-string)))
      (let ((emacs-edit--pure-buffer-context t)) (c1-test-newline '(4)))
      (should (equal "\n\n\n\n" (nelisp-ec-buffer-string)))
      (should (equal "a\n\n" (buffer-string))))))

(ert-deftest c1-command/meta-escape-binding ()
  (let ((map (emacs-keymap-make-sparse-keymap)))
    (emacs-keymap-define-key map [134217825] 'c1-test-first)
    (dolist (key (list [134217825] [27 97] (unibyte-string 225)))
      (should (eq 'c1-test-first (emacs-keymap-lookup-key map key))))
    (should-not (emacs-keymap-lookup-key map [233]))))

(ert-deftest c1-command/live-context-restores-batch ()
  (let ((noninteractive t)
        (emacs-keymap-global-map (emacs-keymap-make-sparse-keymap))
        (emacs-command-loop--unread-events nil)
        (emacs-command-loop-input-poll-function #'ignore)
        (pre-command-hook nil) (post-command-hook nil)
        (this-command nil) (last-command nil) (real-this-command nil)
        seen)
    (cl-letf (((symbol-function 'nelisp--write-stdout-bytes) #'ignore)
              ((symbol-function 'c1-test-live)
               (lambda () (interactive) (setq seen noninteractive))))
      (emacs-keymap-define-key emacs-keymap-global-map [f23] 'c1-test-live)
      (emacs-command-loop-feed-events 'f23)
      (emacs-command-loop-step)
      (should-not seen)
      (should noninteractive))))

(ert-deftest c1-command/live-errors-and-quits-recover ()
  (let ((noninteractive t) (inhibit-message t)
        (emacs-keymap-global-map (emacs-keymap-make-sparse-keymap))
        (emacs-command-loop--unread-events nil)
        (emacs-command-loop-input-poll-function #'ignore)
        (pre-command-hook nil)
        (this-command nil) (last-command nil) (real-this-command nil)
        trace)
    (cl-letf (((symbol-function 'nelisp--write-stdout-bytes) #'ignore)
              ((symbol-function 'c1-test-error)
               (lambda () (interactive) (error "c1 failure")))
              ((symbol-function 'c1-test-quit)
               (lambda () (interactive) (signal 'quit nil))))
      (emacs-keymap-define-key emacs-keymap-global-map [f21] 'c1-test-error)
      (emacs-keymap-define-key emacs-keymap-global-map [f22] 'c1-test-quit)
      (let ((post-command-hook
             (list (lambda () (push (list this-command last-command) trace)))))
        (emacs-command-loop-feed-events 'f21 'f22)
        (emacs-command-loop-step)
        (should-not (emacs-command-loop-pending-p))
        (should (eq last-command 'c1-test-error))
        (emacs-command-loop-feed-events 'f22)
        (emacs-command-loop-step)
        (should (eq last-command 'c1-test-quit)))
      (should (equal (nreverse trace)
                     '((c1-test-error nil) (c1-test-quit c1-test-error))))
      (should noninteractive)
      (let ((emacs-command-loop-input-poll-function nil))
        (emacs-command-loop-feed-events 'f21)
        (should-error (emacs-command-loop-step) :type 'error)))))

(ert-deftest c1-command/adapter-without-pure-buffer-keeps-native-undo ()
  (let ((nelisp-ec--current-buffer nil)
        (pre-command-hook nil) (post-command-hook nil)
        (this-command nil) (last-command nil) (real-this-command nil)
        seen)
    (cl-letf (((symbol-function 'nelisp-buffer-p) (lambda (_buffer) t)))
      (emacs-command-loop-key-dispatch-run-plan
       '(:kind self-insert :binding self-insert-command :event 97)
       :run-self-insert
       (lambda (_event _plan)
         (setq seen (emacs-undo--native-buffer-p))))
      (should seen))))
