;;; C1 shared command semantics compared with GNU Emacs. -*- lexical-binding: t; -*-
(setq ring-bell-function #'ignore)
(defun ding (&optional _arg) nil)
(defvar c1-rows nil)
(defun c1-row (tag value) (push (format "C1|%s|%S\n" tag value) c1-rows))
(defun c1-error (fn) (condition-case err (funcall fn) (error (car err))))
(defun c1-first () (interactive) (setq this-command 'c1-rewritten))
(defun c1-second () (interactive))
(defun c1-hook () (when this-command (c1-row "hook" (list this-command last-command real-this-command))))
(let ((map (make-sparse-keymap))
      (pre-command-hook '(c1-hook)) (post-command-hook '(c1-hook))
      (this-command nil) (last-command nil) (real-this-command nil))
  (define-key map [f21] 'c1-first)
  (define-key map [f22] 'c1-second)
  (use-global-map map)
  (if (fboundp 'nelisp--write-stdout-bytes)
      (progn (emacs-command-loop-feed-events 'f21 'f22) (emacs-command-loop-drain))
    (execute-kbd-macro [f21 f22])))
(defun c1-live () (interactive) (c1-row "live-context" noninteractive))
(let ((map (make-sparse-keymap)))
  (define-key map [f23] 'c1-live)
  (use-global-map map)
  (if (fboundp 'nelisp--write-stdout-bytes)
      (let ((emacs-command-loop-input-poll-function #'ignore))
        (emacs-command-loop-feed-events 'f23)
        (emacs-command-loop-step))
    (let ((noninteractive nil)) (call-interactively 'c1-live))))
(c1-row "batch-context-restored" noninteractive)
(defun c1-advised (n) (interactive "p") (c1-row "argument" n) nil)
(defun c1-around (old &rest args) (apply old args))
(advice-add 'c1-advised :around #'c1-around)
(defun c1-before (&rest _args))
(advice-add 'c1-advised :before #'c1-before)
(c1-row "advised-command" (commandp 'c1-advised))
(c1-row "advised-spec" (interactive-form 'c1-advised))
(let ((current-prefix-arg '(4)))
  (c1-row "advised-call" (c1-error (lambda () (call-interactively 'c1-advised)))))
(defun c1-override (old &rest args) (interactive "P") (apply old args))
(advice-add 'c1-advised :around #'c1-override)
(let ((current-prefix-arg '(4)))
  (c1-row "override-call" (c1-error (lambda () (call-interactively 'c1-advised)))))
(advice-remove 'c1-advised #'c1-override)
(defun c1-filter (args) (list (* 2 (car args))))
(advice-add 'c1-advised :filter-args #'c1-filter)
(let ((current-prefix-arg '(4)))
  (c1-row "filter-call" (c1-error (lambda () (call-interactively 'c1-advised)))))
(let ((secret 17))
  (defalias 'c1-lexical
    (lambda (n) (interactive (list secret)) (c1-row "lexical-argument" n) nil)))
(advice-add 'c1-lexical :around #'c1-around)
(c1-row "lexical-call" (c1-error (lambda () (call-interactively 'c1-lexical))))
(defun c1-plain (n) n)
(advice-add 'c1-plain :around #'c1-around)
(c1-row "plain-negative" (c1-error (lambda () (call-interactively 'c1-plain))))
(dolist (e '(0 1 9 13 27 31 65 97 233 4194303 4194304 134217825 33554529 201326689 268435553 S-left M-S-left))
  (c1-row "event" (list e (characterp e) (char-or-string-p e)
                         (event-modifiers e) (event-basic-type e))))
(dolist (e '(97 233 134217825 S-left))
  (let ((unread-command-events (list e))) (c1-row "keys" (read-key-sequence nil)))
  (let ((unread-command-events (list e))) (c1-row "vector" (read-key-sequence-vector nil))))
(dolist (shared '(nil t))
  (let ((map (make-sparse-keymap)))
    (if (and shared (fboundp 'emacs-keymap-define-key))
        (emacs-keymap-define-key map [134217825] 'c1-advised)
      (define-key map [134217825] 'c1-advised))
    (use-global-map map)
    (dolist (key (list [134217825] [27 97] (unibyte-string 225) [233]))
      (c1-row "meta-binding"
              (if (fboundp 'emacs-keymap-key-binding)
                  (emacs-keymap-key-binding key)
                (key-binding key))))))
;; A frontend plan with no pure buffer must retain native undo ownership.
(let ((nelisp-ec--current-buffer nil) (inhibit-message t)
      (pre-command-hook nil) (post-command-hook nil))
  (with-temp-buffer
    (c1-row "adapter-native-undo"
            (if (fboundp 'nelisp--write-stdout-bytes)
                (plist-get
                 (emacs-command-loop-key-dispatch-run-plan
                  '(:kind self-insert :binding self-insert-command :event 97)
                  :run-self-insert (lambda (_event _plan) (emacs-undo--native-buffer-p)))
                 :point)
              t))))
;; Leave a live unrelated ec-buffer to reproduce the native/pure split.
(when (fboundp 'nelisp-ec-generate-new-buffer)
  (nelisp-ec-set-buffer (nelisp-ec-generate-new-buffer "c1-unrelated")))
(with-temp-buffer
  (c1-row "saved-size-default" (list buffer-saved-size (default-value 'buffer-saved-size)))
  (setq buffer-saved-size -1)
  (c1-row "saved-size-local" (list buffer-saved-size (default-value 'buffer-saved-size))))
(defvar c1-changes nil)
(defun c1-change (&rest args) (push args c1-changes))
(with-temp-buffer
  (insert "a")
  (buffer-enable-undo)
  (setq buffer-undo-list nil c1-changes nil)
  (let ((after-change-functions '(c1-change)))
    (newline 2))
  (c1-row "newline-hooks" (nreverse c1-changes))
  (primitive-undo 1 buffer-undo-list)
  (c1-row "newline-undo" (buffer-string)))
(dolist (n '(0 -1 (4)))
  (with-temp-buffer
    (c1-row "newline-prefix" (list n (c1-error (lambda () (newline n))) (buffer-string)))))
(with-temp-buffer
  (let ((changes nil) (after-change-functions nil)
        (post-self-insert-hook nil))
    (insert "a")
    (newline 2)
    (c1-row "newline" (list (buffer-string) (point)))
    (dolist (e '(97 134217825 S-left))
      (let ((last-command-event e)) (self-insert-command 1)))
    (c1-row "self-insert" (buffer-string))
    (c1-row "newline-type" (c1-error (lambda () (newline "bad"))))))
(c1-row "DONE" t)
(let ((transcript (apply #'concat (nreverse c1-rows))))
  (when (getenv "C1_TRANSCRIPT")
    (with-temp-file (getenv "C1_TRANSCRIPT") (insert transcript)))
  (princ transcript))
nil
