;;; emacs-buffer-swap-cache-test.el --- Switching cache regressions -*- lexical-binding: t; -*-
(require 'ert)
(require 'emacs-buffer)

(defmacro emacs-buffer-swap-cache-test--world (&rest body)
  `(let ((nelisp-ec--buffers nil)
         (nelisp-ec--current-buffer nil)
         (emacs-buffer--state (make-hash-table :test 'eq))
         (emacs-buffer--local-indexes (make-hash-table :test 'eq))
         (emacs-buffer--active-cache nil)
         (emacs-buffer--per-buffer-symbols '(declared))
         (emacs-buffer--default-values (make-hash-table :test 'eq))
         (emacs-buffer--swapped-in (make-hash-table :test 'eq)))
     ,@body))

(defun emacs-buffer-swap-cache-test--buffer (name locals)
  (let ((buffer (nelisp-ec-generate-new-buffer name)))
    (emacs-buffer--set-ext-locals (emacs-buffer--ensure-ext buffer) locals)
    buffer))

(ert-deftest emacs-buffer-swap-cache/fresh-cells-reuse-ordered-union ()
  (emacs-buffer-swap-cache-test--world
    (let* ((old (emacs-buffer-swap-cache-test--buffer "old" '((a . 1) (b . 2))))
           (one (emacs-buffer-swap-cache-test--buffer "one" '((b . 3) (c . 4))))
           (two (emacs-buffer-swap-cache-test--buffer "two" '((b . 5) (c . 6))))
           (union (emacs-buffer--swap-active-symbols old one)))
      (should (equal union '(c b a declared)))
      (should (eq union (emacs-buffer--swap-active-symbols old two))))))

(ert-deftest emacs-buffer-swap-cache/changed-order-and-declarations ()
  (emacs-buffer-swap-cache-test--world
    (let* ((old (emacs-buffer-swap-cache-test--buffer "old" '((a . 1) (b . 2))))
           (new (emacs-buffer-swap-cache-test--buffer "new" '((b . 3) (c . 4)))))
      (emacs-buffer--swap-active-symbols old new)
      (emacs-buffer--set-ext-locals (emacs-buffer--ensure-ext new) '((c . 4) (b . 3)))
      (should (equal (emacs-buffer--swap-active-symbols old new) '(b c a declared)))
      (let ((emacs-buffer--per-buffer-symbols '(other declared)))
        (should (equal (emacs-buffer--swap-active-symbols old new)
                       '(b c a other declared)))))))

(ert-deftest emacs-buffer-swap-cache/duplicate-names-keep-first-union-order ()
  (emacs-buffer-swap-cache-test--world
    (let ((old (emacs-buffer-swap-cache-test--buffer "old" '((a . 1) (a . 2) (b . 3))))
          (new (emacs-buffer-swap-cache-test--buffer "new" '((b . 4) (c . 5) (b . 6)))))
      (should (equal (emacs-buffer--swap-active-symbols old new) '(b c a declared))))))

(ert-deftest emacs-buffer-swap-cache/large-union-keeps-indexed-path ()
  (emacs-buffer-swap-cache-test--world
    (let* ((names (cl-loop repeat 300 collect (make-symbol "local")))
           (locals (mapcar (lambda (name) (cons name nil)) names))
           (old (emacs-buffer-swap-cache-test--buffer "old" locals))
           (new (emacs-buffer-swap-cache-test--buffer "new" (copy-tree locals)))
           (union (emacs-buffer--swap-active-symbols old new)))
      (should (= (length union) 301))
      (should (eq (car union) (car (last names))))
      (should (eq (car (last union)) 'declared))
      (should (= (length (delete-dups (copy-sequence union))) 301)))))

(ert-deftest emacs-buffer-swap-cache/keys-do-not-retain-local-values ()
  (emacs-buffer-swap-cache-test--world
    (let* ((value (list 'buffer-owned-value))
           (old (emacs-buffer-swap-cache-test--buffer "old" (list (cons 'a value))))
           (new (emacs-buffer-swap-cache-test--buffer "new" nil)))
      (emacs-buffer--swap-active-symbols old new)
      (emacs-buffer--forget old)
      (cl-labels ((retains (object)
                    (or (eq object value)
                        (and (consp object)
                             (or (retains (car object)) (retains (cdr object))))
                        (and (vectorp object) (cl-some #'retains (append object nil))))))
        (should-not (retains emacs-buffer--active-cache))))))

(ert-deftest emacs-buffer-swap-cache/bound-sentinel-and-unbound-default ()
  (emacs-buffer-swap-cache-test--world
    (let* ((symbol (make-symbol "local"))
           (emacs-buffer--per-buffer-symbols (list symbol))
           (old (emacs-buffer-swap-cache-test--buffer "old" nil))
           (new (emacs-buffer-swap-cache-test--buffer "new" nil)))
      (emacs-buffer-set-default symbol nil)
      (nelisp-ec-set-buffer old)
      (set symbol 'emacs-buffer--swap-unset)
      (nelisp-ec-set-buffer new)
      (should (null (symbol-value symbol)))
      (nelisp-ec-set-buffer old)
      (should (boundp symbol))
      (should (eq (symbol-value symbol) 'emacs-buffer--swap-unset))
      (makunbound symbol)
      (puthash symbol (cons nil nil) emacs-buffer--default-values)
      (emacs-buffer--set-ext-locals (emacs-buffer--ensure-ext new) nil)
      (nelisp-ec-set-buffer new)
      (should-not (boundp symbol)))))

(ert-deftest emacs-buffer-swap-cache/seeded-locals-rebuild-index ()
  (emacs-buffer-swap-cache-test--world
    (let* ((symbol (make-symbol "local"))
           (emacs-buffer--per-buffer-symbols (list symbol))
           (old (emacs-buffer-swap-cache-test--buffer "old" nil))
           (new (emacs-buffer-swap-cache-test--buffer "new" nil))
           (ext (emacs-buffer--ensure-ext old))
           (empty-index (emacs-buffer--local-index ext)))
      (set symbol 17)
      (emacs-buffer--swap-between old new (list symbol symbol))
      (let ((locals (emacs-buffer--ext-locals ext))
            (index (emacs-buffer--local-index ext)))
        (should (= (length locals) 1))
        (should (eq (gethash symbol index) (car locals)))
        (should (= (cdr (gethash symbol index)) 17))
        (should-not (eq empty-index index))))))

(ert-deftest emacs-buffer-swap-cache/shared-sidecar-sees-seeded-local ()
  (emacs-buffer-swap-cache-test--world
    (let* ((symbol (make-symbol "local"))
           (emacs-buffer--per-buffer-symbols (list symbol))
           (old (emacs-buffer-swap-cache-test--buffer "old" nil))
           (new (emacs-buffer-swap-cache-test--buffer "new" nil))
           (ext (emacs-buffer--ensure-ext old)))
      (emacs-buffer-set-default symbol 3)
      (puthash new ext emacs-buffer--state)
      (set symbol 29)
      (emacs-buffer-switch-current-buffer old new)
      (should (= (symbol-value symbol) 29))
      (should (= (cdr (gethash symbol (emacs-buffer--local-index ext))) 29)))))

;;; emacs-buffer-swap-cache-test.el ends here
