;;; -*- lexical-binding: t; -*-
(require 'ert)
(ert-deftest b76-default-filter-selects-live-buffer ()
  (let* ((caller (current-buffer))
         (buffer (generate-new-buffer " *b76-filter*"))
         (process (make-pipe-process :name "b76-filter" :buffer buffer :noquery t)))
    (unwind-protect
        (progn
          (with-current-buffer buffer (insert "state") (goto-char 2))
          (set-marker (process-mark process) 6 buffer)
          (should (null (emacs-cc-pipe-process-1--default-filter process "changed")))
          (should (eq (current-buffer) buffer))
          (should (= (point) 2))
          (should (equal (buffer-string) "statechanged"))
          (should (= (marker-position (process-mark process)) 13))
          (goto-char 13)
          (emacs-cc-pipe-process-1--default-filter process "!")
          (should (= (point) 14))
          (set-buffer caller)
          (set-process-buffer process nil)
          (emacs-cc-pipe-process-1--default-filter process "discarded")
          (should (eq (current-buffer) caller)))
      (set-buffer caller)
      (delete-process process)
      (kill-buffer buffer))))
(provide 'emacs-cc-default-process-filter-test)
