;;; emacs-buffer-insert-runs-test.el --- Inserted property run checks -*- lexical-binding: t; -*-
(require 'ert)
(require 'emacs-buffer)

(ert-deftest emacs-buffer-insert-runs/plain-string-uses-one-read ()
  (let ((calls 0) (original (symbol-function 'text-properties-at))
        (ext (emacs-buffer--ext-make)) (string (make-string 1000 ?x)))
    (cl-letf (((symbol-function 'text-properties-at)
               (lambda (&rest args) (setq calls (1+ calls)) (apply original args))))
      (emacs-buffer--insert-string-properties ext 1 (list string)))
    (should (= calls 1))
    (should-not (emacs-buffer--ext-text-props ext))))

(ert-deftest emacs-buffer-insert-runs/native-runs-and-character-offsets ()
  (let ((ext (emacs-buffer--ext-make)) (string (copy-sequence "abcdef")))
    (put-text-property 0 2 'face 'bold string)
    (put-text-property 3 6 'help-echo "help" string)
    (emacs-buffer--insert-string-properties ext 10 (list string ?x string))
    (dolist (row '((10 face bold) (11 face bold) (12 face nil)
                  (13 help-echo "help") (15 help-echo "help")
                  (16 face nil) (17 face bold) (18 face bold)
                  (19 face nil) (20 help-echo "help") (22 help-echo "help")))
      (let ((cell (emacs-buffer--tp-cell-at
                   (emacs-buffer--ext-text-props ext) (nth 0 row))))
        (should (equal (and cell (plist-get (emacs-buffer--tp-plist cell) (nth 1 row)))
                       (nth 2 row)))))))

(ert-deftest emacs-buffer-insert-runs/unsupported-string-scan-falls-back ()
  (let ((calls 0) (original (symbol-function 'text-properties-at))
        (ext (emacs-buffer--ext-make)) (string (copy-sequence "abcde")))
    (put-text-property 2 4 'face 'bold string)
    (cl-letf (((symbol-function 'emacs-buffer-builtins-next-property-change)
               (lambda (_pos _object limit) limit))
              ((symbol-function 'next-property-change)
               (symbol-function 'emacs-buffer-builtins-next-property-change))
              ((symbol-function 'text-properties-at)
               (lambda (&rest args) (setq calls (1+ calls)) (apply original args))))
      (emacs-buffer--insert-string-properties ext 1 (list string)))
    (should (= calls 5))
    (should (equal (emacs-buffer--tp-plist
                    (emacs-buffer--tp-cell-at (emacs-buffer--ext-text-props ext) 3))
                   '(face bold)))))

(ert-deftest emacs-buffer-insert-runs/empty-and-uniform-native-properties ()
  (let ((ext (emacs-buffer--ext-make)) (string (propertize "abc" 'face 'bold)))
    (emacs-buffer--insert-string-properties ext 7 (list "" string))
    (should (= (length (emacs-buffer--ext-text-props ext)) 1))
    (let ((cell (car (emacs-buffer--ext-text-props ext))))
      (should (= (emacs-buffer--tp-start cell) 7))
      (should (= (emacs-buffer--tp-end cell) 10))
      (should (equal (emacs-buffer--tp-plist cell) '(face bold))))))

(ert-deftest emacs-buffer-insert-runs/marked-bulk-stub-falls-back ()
  (let ((ext (emacs-buffer--ext-make)) (string (copy-sequence "abc"))
        (marker (get 'next-property-change 'emacs-stub-bulk)))
    (put-text-property 1 2 'face 'bold string)
    (unwind-protect
        (cl-letf (((symbol-function 'next-property-change)
                   (lambda (&rest _args) nil)))
          (put 'next-property-change 'emacs-stub-bulk t)
          (emacs-buffer--insert-string-properties ext 1 (list string)))
      (put 'next-property-change 'emacs-stub-bulk marker))
    (let ((cell (car (emacs-buffer--ext-text-props ext))))
      (should (= (emacs-buffer--tp-start cell) 2))
      (should (= (emacs-buffer--tp-end cell) 3))
      (should (equal (emacs-buffer--tp-plist cell) '(face bold))))))

(provide 'emacs-buffer-insert-runs-test)
;;; emacs-buffer-insert-runs-test.el ends here
