;;; package-correctness-smoke.el --- Synthetic GNU/native comparisons -*- lexical-binding: t; -*-
;; Covers alias initialization/writes, Custom and preserved search captures.
(defun k1-row (name fn)
  (princ (format "K1|%s|%S\n" name (condition-case err (funcall fn) (error err)))))
(k1-row 'alias-late-defvar (lambda ()
  (defvaralias 'k1-alias-a 'k1-base-a)
  (defvar k1-base-a 17)
  (list (boundp 'k1-alias-a) (symbol-value 'k1-alias-a) k1-alias-a)))
(k1-row 'alias-setq (lambda ()
  (defvar k1-base-b 3)
  (defvaralias 'k1-alias-b 'k1-base-b)
  (setq k1-base-b 4)
  (let ((first k1-alias-b))
    (setq k1-alias-b 5)
    (list first k1-base-b (symbol-value 'k1-alias-b)))))
(k1-row 'obsolete (lambda ()
  (defvar k1-base-c 6)
  (make-obsolete-variable 'k1-old-c 'k1-base-c "1.0")
  (list (get 'k1-old-c 'byte-obsolete-variable) (boundp 'k1-old-c))))
(k1-row 'obsolete-alias-custom (lambda ()
  (define-obsolete-variable-alias 'k1-old-d 'k1-new-d "1.0")
  (defcustom k1-new-d '(0 5) "probe" :type '(repeat integer))
  (list k1-old-d k1-new-d (get 'k1-old-d 'byte-obsolete-variable))))
(k1-row 'custom-set (lambda ()
  (defvar k1-set-calls nil)
  (defcustom k1-custom-e 7 "probe" :type 'integer
    :set (lambda (s v) (push (list s v) k1-set-calls) (set-default s (1+ v))))
  (list k1-custom-e k1-set-calls (eval (car (get 'k1-custom-e 'standard-value))))))
(k1-row 'nested-string (lambda ()
  (string-match "a\\(bc\\)" "zabc")
  (let ((before (match-data)))
    (save-match-data
      (string-match "x\\(y\\)" "xy")
      (save-match-data (string-match "q" "qq")))
    (list before (match-data) (match-string 1 "zabc")))))
(k1-row 'restore-error (lambda ()
  (string-match "a\\(b\\)" "ab")
  (condition-case nil (save-match-data (string-match "z" "zzz") (error "probe")) (error nil))
  (list (match-data) (match-string 1 "ab"))))
(k1-row 'set-match-data (lambda ()
  (string-match "z" "z")
  (set-match-data '(1 3 1 2))
  (list (match-data) (match-string 1 "abcd"))))
(k1-row 'line-preserves (lambda ()
  (with-temp-buffer
    (insert "abcdef\nnext\n") (goto-char 2)
    (string-match "a\\(bc\\)" "zabc")
    (let ((before (match-data)))
      (list before (line-end-position) (match-data) (match-string 1 "zabc"))))))
(k1-row 'configure-options-type (lambda () (stringp system-configuration-options)))
(k1-row 'headless-color-cells (lambda () (display-color-cells)))
(k1-row 'genuine-macro-autoload (lambda ()
  (eval '(define-short-documentation-group k1-synthetic-shortdoc
           "Synthetic" (identity :eval (identity 7))))
  (and (featurep 'shortdoc) (assq 'k1-synthetic-shortdoc shortdoc--groups) t)))
(k1-row 'alias-chain (lambda ()
  (defvar k1-base-f 10)
  (defvaralias 'k1-alias-f 'k1-base-f)
  (defvaralias 'k1-alias-ff 'k1-alias-f)
  (setq k1-base-f 11)
  (let ((before (list k1-alias-f k1-alias-ff)))
    (setq k1-alias-ff 12)
    (list before k1-base-f k1-alias-f k1-alias-ff))))
(k1-row 'alias-dynamic-base (lambda ()
  (defvar k1-base-g 10)
  (defvaralias 'k1-alias-g 'k1-base-g)
  (let ((inside (let ((k1-base-g 20)) (list k1-alias-g (symbol-value 'k1-alias-g)))))
    (list inside k1-base-g k1-alias-g))))
(k1-row 'alias-dynamic-alias (lambda ()
  (defvar k1-base-h 10)
  (defvaralias 'k1-alias-h 'k1-base-h)
  (let ((inside (let ((k1-alias-h 20)) (list k1-base-h k1-alias-h))))
    (list inside k1-base-h k1-alias-h))))
(k1-row 'alias-watcher (lambda ()
  (defvar k1-base-i 10)
  (defvaralias 'k1-alias-i 'k1-base-i)
  (defvar k1-watch-calls nil)
  (add-variable-watcher 'k1-base-i (lambda (s v op _where)
    (push (list s v op k1-base-i k1-alias-i) k1-watch-calls)))
  (setq k1-alias-i 12)
  (list k1-base-i k1-alias-i (reverse k1-watch-calls))))
(k1-row 'alias-global-custom-set (lambda ()
  (defvar k1-base-j 1)
  (defvaralias 'k1-alias-j 'k1-base-j)
  (set-default-toplevel-value 'k1-alias-j 4)
  (list k1-base-j k1-alias-j)))
(k1-row 'alias-void-unlet (lambda ()
  (defvar k1-void-base)
  (defvaralias 'k1-void-alias 'k1-void-base)
  (defvar k1-void-calls nil)
  (add-variable-watcher 'k1-void-base
    (lambda (_s v op _where) (push (list v op) k1-void-calls)))
  (let ((inside (let ((k1-void-base 8)) (list k1-void-base k1-void-alias))))
    (list inside (boundp 'k1-void-base) (boundp 'k1-void-alias)
          (reverse k1-void-calls)))))
(princ "K1-ALL-DONE\n")
