;;; -*- lexical-binding: t; -*-
(require 'cl-lib)
(defun k1-vector-row (name value) (princ (format "K1-VECTOR|%s|%S|\n" name value)))
(cl-defstruct (k1-v (:type vector)) (x 3) (y 4))
(let ((value (make-k1-v :y 9)))
  (k1-vector-row 'keyword (if (vectorp value) value 'wrong-storage)))
(k1-vector-row 'predicate (fboundp 'k1-v-p))
(cl-defstruct (k1-boa (:type vector) (:constructor k1-boa-create (x &aux (y (+ x 1))))) x y)
(let ((value (k1-boa-create 6)))
  (k1-vector-row 'boa (if (vectorp value) value 'wrong-storage)))
(cl-defstruct (k1-empty (:type vector) (:constructor k1-empty-create ())) (x 12))
(let ((value (k1-empty-create)))
  (k1-vector-row 'empty-boa
    (list (if (vectorp value) value 'wrong-storage)
          (condition-case nil (progn (k1-empty-create :x 99) 'accepted)
            (wrong-number-of-arguments 'rejected)))))
(let* ((value (make-k1-v)) (copy (copy-k1-v value)))
  (if (vectorp value)
      (progn (setf (k1-v-y copy) 20) (k1-vector-row 'copy (list value copy)))
    (k1-vector-row 'copy 'wrong-storage)))
(require 'timer)
(let ((value (run-with-timer 3600 nil #'ignore)))
  (unwind-protect (k1-vector-row 'timer (list (timerp value) (vectorp value) (length value)))
    (cancel-timer value)))
(princ "K1-VECTOR-DONE\n")
