;;; keymap-prefix.el --- GNU-compatible inherited prefix regression -*- lexical-binding: t; -*-
(let ((parent (make-sparse-keymap)) (child (make-sparse-keymap)))
  (define-key parent "g" 'undefined)
  (set-keymap-parent child parent)
  (define-key child "gd" 'forward-char)
  (unless (and (eq (lookup-key child "gd") 'forward-char)
               (eq (lookup-key parent "g") 'undefined))
    (error "Inherited non-prefix must be shadowed, parent retained"))
  (define-key child "a" 'backward-char)
  (let ((rejected nil))
    (condition-case nil (define-key child "ab" 'forward-char)
      (error (setq rejected t)))
    (unless rejected (error "Own non-prefix negative accepted")))
  (princ "KEYMAP-PREFIX-PASS|inherited-shadow/parent-intact/own-nonprefix-negative\n"))
