;;; library-pixels.el --- Reusable pixel contract and host shim boundary -*- lexical-binding: t; -*-
(require 'emacs-frame-pixels)
(let* ((host (symbol-function 'frame-char-width))
       (frame (emacs-frame-selected-frame))
       (window (emacs-window-selected-window))
       (cells (list (list window 7 30 50 20 25 3 2 "日" 3)))
       (provider (lambda (op &rest args)
                   (cond ((eq op :cells) cells)
                         ((eq op :measure) (cons (* 10 (emacs-frame-pixels-string-columns (car args))) 25))))))
  (emacs-frame-pixels-install frame 10 25 provider)
  (unless (= (emacs-frame-frame-char-width frame) 10) (error "Measured frame width lost"))
  (unless (= (emacs-frame-pixels-string-width "é 日本語") 80) (error "Combining/CJK advance"))
  (unless (= (emacs-frame-pixels-string-width "Tab:\tX") 90) (error "Tab stop advance"))
  (let ((hit (emacs-frame-pixels-hit 49 74 123))
        (miss (emacs-frame-pixels-hit 50 74 123)))
    (unless (and (= (nth 1 hit) 7) (= (nth 3 hit) 123)
                 (null (nth 4 hit)) (equal (nth 6 hit) '(3 . 2))
                 (equal (nth 8 hit) '(19 . 24)) (equal (nth 9 hit) '(20 . 25))
                 (null miss))
      (error "Canonical wide glyph position/boundary")))
  (emacs-frame-pixels-install-builtins)
  (unless (eq host (symbol-function 'frame-char-width)) (error "Host C primitive overridden"))
  (princ "LIBRARY-PIXELS-PASS|measured/combining/CJK/tab/canonical-posn/boundary/host-C-preserved\n"))
