;;; redisplay-incremental.el --- Shared row reuse and GUI damage regressions -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'emacs-redisplay)
(require 'nelisp-gui-pango)
(defvar nelisp-gui-frontend--renderer)

(defmacro gui-incremental--world (&rest body)
  `(let ((nelisp-ec--buffers nil) (nelisp-ec--current-buffer nil)
         (emacs-window--id-counter 0) (emacs-window--root nil) (emacs-window--selected nil)
         (emacs-redisplay-paint-mode-line-p nil))
     ,@body))

(ert-deftest gui-incremental/source-lines-reuse-and-lazy-positions ()
  (gui-incremental--world
   (let* ((b (nelisp-ec-generate-new-buffer "incremental"))
          (nelisp-ec--current-buffer b)
          (_ (nelisp-ec-insert "alpha\nbeta\ngamma\n"))
          (w (emacs-window-selected-window)) (h (emacs-redisplay-init)))
     (emacs-window-set-window-buffer w b)
     (emacs-window-set-window-point w 1)
     (let* ((m (emacs-redisplay-redisplay-window h w))
            (rows (emacs-redisplay-glyph-matrix-rows m))
            (beta (emacs-redisplay-glyph-row-glyphs (aref rows 1)))
            (tokens (symbol-function 'emacs-redisplay--display-tokens)) (calls 0))
       (nelisp-ec-goto-char 1) (nelisp-ec-insert "X")
       (emacs-window-set-window-point w 2)
       (cl-letf (((symbol-function 'emacs-redisplay--display-tokens)
                  (lambda (&rest args) (setq calls (1+ calls)) (apply tokens args))))
         (emacs-redisplay-redisplay-window h w))
       (should (= calls 0))
       (should (equal "Xalpha" (emacs-redisplay-glyph-row-text (aref rows 0))))
       (should (eq beta (emacs-redisplay-glyph-row-glyphs (aref rows 1))))
       (should (= 8 (emacs-redisplay--effective-buf-pos (aref rows 1) (aref beta 0))))
       (should-not (aref (emacs-redisplay-glyph-matrix-dirty-set m) 1))
       (should (equal '(0 . 1) (emacs-redisplay-glyph-matrix-cursor m)))))))

(ert-deftest gui-incremental/large-viewport-does-not-read-full-buffer ()
  (gui-incremental--world
   (let* ((b (generate-new-buffer " *incremental-native*"))
          (w (emacs-window-selected-window)) (h (emacs-redisplay-init))
          (emacs-redisplay-truncate-lines nil))
     (unwind-protect
         (progn
           (with-current-buffer b
             (insert (make-string 100000 ?a))
             (setq truncate-lines nil word-wrap nil mode-line-format nil)
             (goto-char 2))
           (emacs-window-set-window-buffer w b)
           (emacs-window-set-window-point w 2)
           (cl-letf (((symbol-function 'emacs-redisplay--buffer-string)
                      (lambda (&rest _) (ert-fail "full-buffer read"))))
             (let ((m (emacs-redisplay-redisplay-window h w)))
               (should (equal '(0 . 1) (emacs-redisplay-glyph-matrix-cursor m)))
               (should (= (emacs-window-window-height w) (length (emacs-redisplay-glyph-matrix-rows m)))))))
       (kill-buffer b)))))

(ert-deftest gui-incremental/paint-restores-cursor-and-reuses-cell-rows ()
  (gui-incremental--world
   (let* ((b (nelisp-ec-generate-new-buffer "damage"))
          (nelisp-ec--current-buffer b) (_ (nelisp-ec-insert "alpha\nbeta\n"))
          (w (emacs-window-selected-window)) (h (emacs-redisplay-init))
          (r (vector 0 0 0 0 nil 80 25 (vector 0)
                     nil nil nil (make-vector 4 nil)))
          (nelisp-gui-pango-force-paint t) (mark-active nil) (draws nil))
     (emacs-window-set-window-buffer w b)
     (emacs-window-set-window-point w 1)
     (cl-letf (((symbol-function 'nelisp-gui-xcb-check) (lambda (&rest _) t))
               ((symbol-function 'nelisp-gui-xcb-call) (lambda (&rest _) 0))
               ((symbol-function 'nelisp-gui-pango--source) (lambda (&rest _) nil))
               ((symbol-function 'nelisp-gui-pango--rect) (lambda (&rest _) nil))
               ((symbol-function 'nelisp-gui-menu-paint) (lambda (&rest _) nil))
               ((symbol-function 'nelisp-gui-pango-row)
                (lambda (_r _row _left top _width) (push top draws))))
       (nelisp-gui-pango-paint r h)
       (should (= (length draws) (emacs-window-window-height w)))
       (nelisp-gui-pango--ensure-cells r)
       (let ((cells (aref (aref (cdr (assq (emacs-window-id w) (aref r 8))) 1) 1)))
         (should cells)
         (setq draws nil)
         (nelisp-gui-pango-paint r h)
         (should (equal draws '(0)))
         (should (eq cells (aref (aref (cdr (assq (emacs-window-id w) (aref r 8))) 1) 1))))
       (setq draws nil)
       (emacs-window-set-window-point w 7)
       (nelisp-gui-pango-paint r h)
       (should (equal (sort draws #'<) '(0 1)))
       (setq draws nil nelisp-gui-pango-force-paint t)
       (nelisp-gui-pango-paint r h)
       (should (= (length draws) (emacs-window-window-height w)))))))

(ert-deftest gui-incremental/face-spans-reuse-with-shift-and-invalidate-on-change ()
  (gui-incremental--world
   (let* ((b (generate-new-buffer " *incremental-faces*"))
          (w (emacs-window-selected-window)) (h (emacs-redisplay-init)))
     (unwind-protect
         (progn
           (with-current-buffer b
             (insert "alpha\nbeta\ngamma\n")
             (put-text-property 7 11 'face '(:underline t))
             (setq mode-line-format nil)
             (goto-char 1))
           (emacs-window-set-window-buffer w b)
           (emacs-window-set-window-point w 1)
           (let* ((m (emacs-redisplay-redisplay-window h w))
                  (rows (emacs-redisplay-glyph-matrix-rows m))
                  (beta (emacs-redisplay-glyph-row-glyphs (aref rows 1)))
                  (glyph (aref beta 0)))
             (should (cdr (assq :underline (emacs-redisplay-glyph-realized-face glyph))))
             (with-current-buffer b (insert "X"))
             (emacs-window-set-window-point w 2)
             (emacs-redisplay-redisplay-window h w)
             (should (eq beta (emacs-redisplay-glyph-row-glyphs (aref rows 1))))
             (should (eq glyph (aref (emacs-redisplay-glyph-row-glyphs (aref rows 1)) 0)))
             (should (= 8 (emacs-redisplay--effective-buf-pos (aref rows 1) (aref beta 0))))
             (with-current-buffer b (remove-text-properties 8 12 '(face nil)))
             (emacs-redisplay-redisplay-window h w)
             (should-not (eq glyph (aref (emacs-redisplay-glyph-row-glyphs (aref rows 1)) 0)))
             (should-not (cdr (assq :underline
                                   (emacs-redisplay-glyph-realized-face
                                    (aref (emacs-redisplay-glyph-row-glyphs (aref rows 1)) 0)))))))
       (kill-buffer b)))))

(ert-deftest gui-incremental/region-movement-invalidates-shared-glyphs ()
  (gui-incremental--world
   (let* ((b (generate-new-buffer " *incremental-region*"))
          (w (emacs-window-selected-window)) (h (emacs-redisplay-init)))
     (unwind-protect
         (progn
           (emacs-redisplay-defface 'region '(:underline t))
           (with-current-buffer b
             (insert "alpha\nbeta\n")
             (setq mode-line-format nil transient-mark-mode t)
             (set-mark 1) (goto-char 4) (setq mark-active t))
           (emacs-window-set-window-buffer w b)
           (emacs-window-set-window-point w 4)
           (let* ((m (emacs-redisplay-redisplay-window h w))
                  (row (aref (emacs-redisplay-glyph-matrix-rows m) 0)))
             (should (cdr (assq :underline (emacs-redisplay-glyph-realized-face
                                           (aref (emacs-redisplay-glyph-row-glyphs row) 2)))))
             (with-current-buffer b (goto-char 2) (setq mark-active t))
             (emacs-window-set-window-point w 2)
             (emacs-redisplay-redisplay-window h w)
             (should-not (cdr (assq :underline (emacs-redisplay-glyph-realized-face
                                               (aref (emacs-redisplay-glyph-row-glyphs row) 2)))))))
       (kill-buffer b)))))

(ert-deftest gui-incremental/cached-propertized-mode-line-keeps-base-face ()
  (gui-incremental--world
   (let* ((b (generate-new-buffer " *incremental-mode*"))
          (w (emacs-window-selected-window)) (h (emacs-redisplay-init))
          (emacs-redisplay-paint-mode-line-p t))
     (unwind-protect
         (progn
           (emacs-redisplay-defface 'mode-line '(:inverse-video t))
           (emacs-redisplay-defface 'header-line '(:underline t))
           (emacs-redisplay-defface 'bold '(:weight bold))
           (with-current-buffer b
             (setq mode-line-format '((:propertize "mode" face bold))
                   header-line-format '((:propertize "head" face bold))))
           (emacs-window-set-window-buffer w b)
           (let* ((m (emacs-redisplay-redisplay-window h w))
                  (rows (emacs-redisplay-glyph-matrix-rows m))
                  (mode (aref (emacs-redisplay-glyph-row-glyphs
                               (aref rows (1- (length rows)))) 0))
                  (header (aref (emacs-redisplay-glyph-row-glyphs (aref rows 0)) 0)))
             (should (eq (plist-get (emacs-redisplay-glyph-face mode) :weight) 'bold))
             (should (eq (plist-get (emacs-redisplay-glyph-face header) :weight) 'bold))
             (should (cdr (assq :reverse (emacs-redisplay-glyph-realized-face mode))))
             (should (cdr (assq :underline (emacs-redisplay-glyph-realized-face header))))))
       (kill-buffer b)))))

(ert-deftest gui-incremental/tty-mode-line-custom-format-has-no-unbound-cache ()
  (gui-incremental--world
   (let* ((b (nelisp-ec-generate-new-buffer "tty-mode"))
          (w (emacs-window-selected-window)))
     (emacs-window-set-window-buffer w b)
     (emacs-buffer-set-buffer-local-value 'mode-line-format b '(" " "%b" " custom"))
     (should (equal " tty-mode custom"
                    (mapconcat #'car (emacs-redisplay-mode-line-spans w 80 1) ""))))))

(ert-deftest gui-incremental/dynamic-mode-line-evaluates-once-per-pass ()
  (gui-incremental--world
   (let* ((b (generate-new-buffer " *incremental-eval*"))
          (w (emacs-window-selected-window)) (h (emacs-redisplay-init))
          (emacs-redisplay-paint-mode-line-p t) (calls 0))
     (unwind-protect
         (progn
           (with-current-buffer b
             (insert "first\n")
             (setq mode-line-format '((:eval (gui-incremental--eval-mode-line)))))
           (emacs-window-set-window-buffer w b)
           (cl-letf (((symbol-function 'gui-incremental--eval-mode-line)
                      (lambda () (setq calls (1+ calls))
                        (format "end=%d" emacs-redisplay--mode-line-end))))
             (emacs-redisplay-redisplay-window h w)
             (should (= calls 1))
             (with-current-buffer b (goto-char (point-max)) (insert "x"))
             (emacs-redisplay-redisplay-window h w)
             (should (= calls 2))
             ;; An unchanged buffer still evaluates arbitrary :eval forms.
             (emacs-redisplay-redisplay-window h w)
             (should (= calls 3))
             (let* ((m (emacs-redisplay-glyph-matrix h w))
                    (row (aref (emacs-redisplay-glyph-matrix-rows m)
                               (1- (emacs-redisplay-glyph-matrix-height m)))))
               (should (string-prefix-p "end=8" (emacs-redisplay-glyph-row-text row))))))
       (kill-buffer b)))))

(ert-deftest gui-incremental/mode-line-literal-runs-preserve-faces-and-escapes ()
  (let* ((buffer (nelisp-ec-generate-new-buffer "literal-mode-line"))
         (text (concat (propertize "abc" 'face 'bold) "def%%!%"))
         (spans (emacs-redisplay--ml-string text buffer 'mode-line 80 nil)))
    (should (equal "abcdef%!%" (mapconcat #'car spans "")))
    (should (equal '(bold mode-line) (cdar spans)))
    (should (equal "abc" (caar spans)))
    (should (equal "def%%!%"
                   (mapconcat #'car (emacs-redisplay--ml-string
                                    "def%%!%" buffer 'mode-line 80 t) "")))))

(ert-deftest gui-incremental/lazy-hit-map-follows-an-edit-before-query ()
  (gui-incremental--world
   (let* ((b (nelisp-ec-generate-new-buffer "lazy-hits"))
          (nelisp-ec--current-buffer b) (_ (nelisp-ec-insert "alpha\nbeta\n"))
          (w (emacs-window-selected-window)) (h (emacs-redisplay-init))
          (r (vector 0 0 0 0 nil 80 25 (vector 0) nil nil nil (make-vector 4 nil)))
          (nelisp-gui-frontend--renderer r)
          (nelisp-gui-pango--cells nil) (nelisp-gui-pango--cells-dirty t)
          (nelisp-gui-pango-force-paint t) (mark-active nil))
     (emacs-window-set-window-buffer w b)
     (emacs-window-set-window-point w 1)
     (cl-letf (((symbol-function 'nelisp-gui-xcb-check) (lambda (&rest _) t))
               ((symbol-function 'nelisp-gui-xcb-call) (lambda (&rest _) 0))
               ((symbol-function 'nelisp-gui-pango--source) (lambda (&rest _) nil))
               ((symbol-function 'nelisp-gui-pango--rect) (lambda (&rest _) nil))
               ((symbol-function 'nelisp-gui-menu-paint) (lambda (&rest _) nil))
               ((symbol-function 'nelisp-gui-pango-row) (lambda (&rest _) nil)))
       (nelisp-gui-pango-paint r h)
       (should (= 7 (nth 1 (cl-find "b" (nelisp-gui-pango-provider :cells)
                                   :key (lambda (cell) (nth 8 cell)) :test #'equal))))
       (nelisp-ec-goto-char 1) (nelisp-ec-insert "X")
       (emacs-window-set-window-point w 2)
       (nelisp-gui-pango-paint r h)
       (should nelisp-gui-pango--cells-dirty)
       (should (= 8 (nth 1 (cl-find "b" (nelisp-gui-pango-provider :cells)
                                   :key (lambda (cell) (nth 8 cell)) :test #'equal))))
       (should-not nelisp-gui-pango--cells-dirty)))))

(ert-deftest gui-incremental/mode-line-parse-cache-keeps-dynamic-values-and-mutations ()
  (gui-incremental--world
   (let* ((b (nelisp-ec-generate-new-buffer "parse-cache"))
          (nelisp-ec--current-buffer b) (_ (nelisp-ec-insert "abc"))
          (emacs-redisplay--ml-plain-cache nil) (text (copy-sequence "%b %c%")))
     (should (equal "parse-cache 3%"
                    (mapconcat #'car (emacs-redisplay--ml-string text b 'mode-line 80 nil) "")))
     (nelisp-ec-goto-char 1)
     (should (equal "parse-cache 0%"
                    (mapconcat #'car (emacs-redisplay--ml-string text b 'mode-line 80 nil) "")))
     (aset text 1 ?l)
     (should (equal "1 0%"
                    (mapconcat #'car (emacs-redisplay--ml-string text b 'mode-line 80 nil) "")))
     (put-text-property 0 2 'face 'bold text)
     (should (equal '(bold mode-line)
                    (cdar (emacs-redisplay--ml-string text b 'mode-line 80 nil)))))))

(require 'nelisp-gui-frontend)

(ert-deftest g4-adapters/nested-insertion-retains-outer-event ()
  (let ((nelisp-gui-frontend--self-insert-event ?z) seen)
    (cl-letf (((symbol-function 'nelisp-gui-frontend--pure-buffer-p) (lambda () t))
              ((symbol-function 'nelisp-gui-frontend--point) (lambda () 1))
              ((symbol-function 'emacs-edit-self-insert-direct)
               (lambda (event)
                 (when (= event ?a) (nelisp-gui-frontend--run-self-insert ?b nil))
                 (push event seen))))
      (nelisp-gui-frontend--run-self-insert ?a nil)
      (should (equal seen '(97 98)))
      (should (= nelisp-gui-frontend--self-insert-event ?z)))))

(defun gui-incremental--reference-row-hash (row-vec)
  "Return a stable hash for ROW-VEC (vector of glyphs).
The hash mixes char + the *realized* face alist (Phase 3.B.1) so a
text-property face change that resolves to a different SGR triggers
diff redraw even if the raw spec stayed identical (= e.g. registry
mutation under the same face name)."
  (let ((h 0)
        (i 0)
        (len (length row-vec)))
    (while (< i len)
      (let* ((g (aref row-vec i))
             (c (if g (emacs-redisplay-glyph-char g) 0))
             (f (if g (or (emacs-redisplay-glyph-realized-face g)
                          (emacs-redisplay-glyph-face g))
                  nil)))
        ;; Mix char + sxhash of face into a 32-bit mask.
        (setq h (logand #xFFFFFFFF
                        (+ (* h 31)
                           (logxor c (sxhash-equal f))))))
      (setq i (1+ i)))
    h))


(ert-deftest gui-incremental/empty-padding-keeps-the-original-row-hash ()
  (let ((emacs-redisplay--nil-padding-cache nil))
    (dolist (width '(1 12 80 132))
      (dotimes (used (1+ width))
        (let ((vec (make-vector width nil)))
          (dotimes (i used)
            (aset vec i (emacs-redisplay--make-glyph
                         :char (+ 32 (% i 90)) :width 1
                         :face (and (= (% i 3) 0) 'mode-line)
                         :realized-face (and (= (% i 5) 0) '((:bold . t))))))
          (should (= (gui-incremental--reference-row-hash vec)
                     (emacs-redisplay--row-hash vec used))))))))

(ert-deftest gui-incremental/service-retains-real-timers-and-skips-empty-lists ()
  (let ((timer-list nil) (timer-idle-list nil)
        (nelisp-gui-frontend--paint-needed nil) calls)
    (cl-letf (((symbol-function 'emacs-process-dispatch-pending) (lambda () nil))
              ((symbol-function 'emacs-timer-run-pending)
               (lambda () (push 'regular calls) 1))
              ((symbol-function 'emacs-timer-idle-seconds) (lambda () 0))
              ((symbol-function 'emacs-timer-run-idle)
               (lambda (_) (push 'idle calls) 1)))
      (nelisp-gui-frontend--service)
      (should-not calls)
      (setq timer-list '(timer) timer-idle-list '(idle-timer))
      (nelisp-gui-frontend--service)
      (should (equal calls '(idle regular)))
      (should nelisp-gui-frontend--paint-needed))))

(ert-deftest gui-incremental/pango-scratch-owners-reuse-grow-and-close ()
  (let ((r (vector 0 0 0 0 nil 80 25 nil nil nil nil (make-vector 4 nil) nil nil))
        (next 100) allocated released text-addresses
        (bytes (make-hash-table :test 'equal)))
    (cl-letf (((symbol-function 'nl-ffi-memory-allocate)
               (lambda (size)
                 (setq next (+ next 100)) (push next allocated)
                 (vector 'nl-ffi-memory-owner next size size)))
              ((symbol-function 'nl-ffi-memory-address) (lambda (owner) (aref owner 1)))
              ((symbol-function 'nl-ffi-memory-release)
               (lambda (owner) (push (aref owner 1) released)))
              ((symbol-function 'ptr-write-u8)
               (lambda (p offset value) (puthash (cons p offset) value bytes)))
              ((symbol-function 'nl-ffi-libffi-u32)
               (lambda (_p offset) (if (= offset 0) 7 11)))
              ((symbol-function 'nelisp-gui-xcb-call)
               (lambda (name _signature &rest args)
                 (when (equal name "pango_layout_set_text")
                   (push (nth 1 args) text-addresses)) 0)))
      (nelisp-gui-pango--text 42 "a" r)
      (nelisp-gui-pango--text 42 "日本" r)
      (should (equal text-addresses '(200 200)))
      (should (= 0 (gethash '(200 . 6) bytes)))
      (nelisp-gui-pango--text 42 (make-string 300 ?x) r)
      (should (equal released '(200)))
      (should (= 300 (car text-addresses)))
      (should (= 0 (gethash '(300 . 300) bytes)))
      (should (equal (nelisp-gui-pango--size 42 r) '(7 . 11)))
      (should (equal (nelisp-gui-pango--size 42 r) '(7 . 11)))
      (should (= 3 (length allocated)))
      (nelisp-gui-pango-close r)
      (should (equal (sort released #'<) '(200 300 400)))
      (should-not (aref r 12)) (should-not (aref r 13)))))

(ert-deftest gui-incremental/os-wait-honors-outgoing-selection-deadline ()
  (let ((nelisp-gui-selection--sends nil))
    (cl-letf (((symbol-function 'emacs-process-wait-source-p) (lambda () nil))
              ((symbol-function 'emacs-timer-next-delay) (lambda (maximum) maximum)))
      (should (= (nelisp-gui-frontend--wait-ms) 1000.0))
      (let ((now (float-time)))
        (setq nelisp-gui-selection--sends
              (list (vector nil nil nil nil nil nil (+ now 2.0) (+ now 15.0))
                    (vector nil nil nil nil nil nil (+ now 0.5) (+ now 15.0)))))
      (let ((delay (nelisp-gui-frontend--wait-ms)))
        (should (<= delay 500.0))
        (should (> delay 400.0)))
      (should (= (nelisp-gui-selection-next-delay 0.05) 0.05))
      (aset (car nelisp-gui-selection--sends) 6 (- (float-time) 1.0))
      (should (= (nelisp-gui-frontend--wait-ms) 0.0)))))

(ert-deftest g4-scalar-cache/unsupported-signatures-remain-with-provider ()
  (dolist (signature '([:uint32 :pointer :pointer :pointer :pointer :pointer :pointer :pointer]
                       [:uint32 :pointer :pointer :pointer :pointer :double]
                       [:double :pointer] [:float :pointer] [:uint32 :float]
                       [(:struct :uint32) :pointer] [:uint32 :void]))
    (let ((nelisp-gui-xcb--calls (make-hash-table :test 'eq))
          (provider 0) (prepared 0) (direct 0)
          (args (make-list (1- (length signature)) 1)))
      (cl-letf (((symbol-function 'nl-ffi-libffi-scalar)
                 (lambda (&rest _) (setq provider (1+ provider)) 7))
                ((symbol-function 'nl-ffi-libffi-prepare)
                 (lambda (&rest _) (setq prepared (1+ prepared)) [0 42]))
                ((symbol-function 'ptr-call)
                 (lambda (&rest _) (setq direct (1+ direct)) 7))
                ((symbol-function 'ptr-call-typed)
                 (lambda (&rest _) (setq direct (1+ direct)) 7)))
        (should (= 7 (apply #'nelisp-gui-xcb-call "cache_test" signature args)))
        (should (= 7 (apply #'nelisp-gui-xcb-call "cache_test" signature args)))
        (should (= provider 2))
        (should (= prepared 0))
        (should (= direct 0))
        (should (= (hash-table-count nelisp-gui-xcb--calls) 0))))))

(ert-deftest g4-scalar-cache/supported-signature-caches-and-validates ()
  (let ((nelisp-gui-xcb--calls (make-hash-table :test 'eq))
        (provider 0) (prepared 0) (direct 0))
    (cl-letf (((symbol-function 'nl-ffi-libffi-scalar)
               (lambda (&rest _) (setq provider (1+ provider)) 7))
              ((symbol-function 'nl-ffi-libffi-prepare)
               (lambda (&rest _) (setq prepared (1+ prepared)) [0 42]))
              ((symbol-function 'ptr-call-typed)
               (lambda (address mask &rest args)
                 (should (= address 42)) (should (= mask 2))
                 (should (equal args '(1 2.0 3 4 5 6)))
                 (setq direct (1+ direct)) 7)))
      (dotimes (_ 2)
        (should (= 7 (nelisp-gui-xcb-call "cache_test"
                                        [:uint32 :pointer :double :uint8 :sint32 :uint64 :pointer]
                                        1 2 3 4 5 6))))
      (should (= provider 1)) (should (= prepared 1)) (should (= direct 1))
      (should-error (nelisp-gui-xcb-call "cache_test"
                                       [:uint32 :pointer :double :uint8 :sint32 :uint64 :pointer]
                                       1 2 3) :type 'nl-ffi-wrong-arity)
      (should-error (nelisp-gui-xcb-call "cache_test"
                                       [:uint32 :pointer :double :uint8 :sint32 :uint64 :pointer]
                                       "bad" 2 3 4 5 6) :type 'wrong-type-argument))))

(ert-deftest g4-scalar-cache/mutated-signature-rechecks-provider ()
  (let ((nelisp-gui-xcb--calls (make-hash-table :test 'eq))
        (signature (vector :uint32 :pointer)) (provider 0) (direct 0))
    (cl-letf (((symbol-function 'nl-ffi-libffi-scalar)
               (lambda (&rest _) (setq provider (1+ provider)) 7))
              ((symbol-function 'nl-ffi-libffi-prepare) (lambda (&rest _) [0 42]))
              ((symbol-function 'ptr-call) (lambda (&rest _) (setq direct (1+ direct)) 7)))
      (should (= 7 (nelisp-gui-xcb-call "cache_test" signature 1)))
      (aset signature 0 :double)
      (should (= 7 (nelisp-gui-xcb-call "cache_test" signature 1)))
      (should (= provider 2)) (should (= direct 0)))))
