;;; selection-policy.el --- Shared select.el policy tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'emacs-select)

(defmacro selection-test-with-backend (&rest body)
  `(let* ((values nil) (owned nil) (clock 1)
          (emacs-select--last nil)
          (gui-last-cut-in-clipboard nil) (gui-last-cut-in-primary nil)
          (select-enable-clipboard t) (select-enable-primary nil)
          (emacs-select-backend
           (list :set (lambda (type text)
                        (setq values (cons (cons type text) (assq-delete-all type values)))
                        (setq owned (if text (cons type owned) (delq type owned))))
                 :get (lambda (type target)
                        (if (eq target 'TIMESTAMP) clock (cdr (assq type values))))
                 :owner (lambda (type) (memq type owned))
                 :exists (lambda (type) (cdr (assq type values))))))
     ,@body))

(ert-deftest selection-policy/host-safe-install ()
  (let ((getter (symbol-function 'gui-get-selection))
        (interprogram-cut-function 'ignore) (emacs-select-backend nil))
    (emacs-select-install '(:get ignore))
    (should (eq getter (symbol-function 'gui-get-selection)))
    (should (eq interprogram-cut-function 'ignore))))
(ert-deftest selection-policy/type-and-disown ()
  (selection-test-with-backend
   (should (equal (emacs-select-set nil "primary") "primary"))
   (should (equal (emacs-select-get) "primary"))
   (emacs-select-set t "secondary")
   (should (equal (emacs-select-get 'SECONDARY) "secondary"))
   (should (emacs-select-owner-p))
   (emacs-select-set nil nil)
   (should-not (emacs-select-owner-p))
   (should-not (emacs-select-exists-p))
   (should-error (emacs-select-set 'PRIMARY 1) :type 'wrong-type-argument)))
(ert-deftest selection-policy/flags-and-cut-hook ()
  (selection-test-with-backend
   (emacs-select-text "clipboard")
   (should (equal (emacs-select-get 'CLIPBOARD) "clipboard"))
   (should-not (emacs-select-get 'PRIMARY))
   (should-not (emacs-select-value))
   (setq select-enable-clipboard nil select-enable-primary t)
   (emacs-select-text "primary")
   (should (equal (emacs-select-get 'PRIMARY) "primary"))
   (should (equal (emacs-select-get 'CLIPBOARD) "clipboard"))
   (should gui-last-cut-in-primary)
   (should-not gui-last-cut-in-clipboard)))
(ert-deftest selection-policy/external-newness-and-preference ()
  (selection-test-with-backend
   (setq select-enable-primary t)
   (emacs-select-text "old")
   (setq owned nil values '((PRIMARY . "primary") (CLIPBOARD . "clipboard")) clock 2)
   (should (equal (emacs-select-value) "clipboard"))
   (should-not (emacs-select-value))
   (setq clock 3)
   (should (equal (emacs-select-value) "clipboard"))
   (setq values '((PRIMARY . "new-primary") (CLIPBOARD . "clipboard")))
   (should (equal (emacs-select-value) "new-primary"))))
(ert-deftest selection-policy/string-fallback ()
  (let* ((calls nil)
        (emacs-select-backend (list :get (lambda (_type target)
                                          (push target calls)
                                          (when (eq target 'STRING) "café")))))
    (should (equal (emacs-select-primary) "café"))
    (should (equal (reverse calls) '(UTF8_STRING STRING)))))
(ert-deftest selection-policy/owned-primary-can-change-independently ()
  (selection-test-with-backend
   (setq select-enable-primary t select-enable-clipboard nil)
   (emacs-select-text "old")
   (emacs-select-set 'PRIMARY "new")
   (setq clock 2)
   (should (equal (emacs-select-value) "new"))
   (should-not (emacs-select-value))))
(ert-run-tests-batch-and-exit)
