;;; selection-receive.el --- Receive cap and deadline ordering -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'nelisp-gui-selection)

(ert-deftest selection-receive/running-cap-before-copy-and-expired-reply ()
  ;; An INCR owner lies in its announcement, sends one byte, then supplies
  ;; a property that fits the direct cap but exceeds the cumulative cap.
  ;; Simulate descheduling past both deadlines with the reply already ready.
  (let ((nelisp-gui-selection--state [1 2])
        (nelisp-gui-selection--receive [2 3 4 incr nil 1 10 20 nil 5])
        (nelisp-gui-selection-max-bytes 4194304)
        (copies 0) (polls 0) (discards 0) (freed nil) (released nil))
    (cl-letf (((symbol-function 'float-time) (lambda (&rest _) 100.0))
              ((symbol-function 'nl-ffi-memory-allocate) (lambda (_) 'storage))
              ((symbol-function 'nl-ffi-memory-address) (lambda (_) 1000))
              ((symbol-function 'nl-ffi-memory-release) (lambda (_) (setq released t)))
              ((symbol-function 'nelisp-gui-selection--flush) #'ignore)
              ((symbol-function 'nelisp-gui-selection--request) (lambda (&rest _) 42))
              ((symbol-function 'nelisp-gui-xcb-check) (lambda (_) t))
              ((symbol-function 'nelisp-gui-xcb-call)
               (lambda (name _signature &rest args)
                 (cond ((equal name "xcb_poll_for_reply") (cl-incf polls) 1)
                       ((equal name "xcb_discard_reply") (cl-incf discards))
                       ((equal name "free") (push (car args) freed)))))
              ((symbol-function 'ptr-read-u64) (lambda (_ offset) (if (= offset 0) 2000 0)))
              ((symbol-function 'ptr-read-u8) (lambda (&rest _) 8))
              ((symbol-function 'nl-ffi-libffi-u32)
               (lambda (_ offset) (pcase offset (16 4194304) (12 0) (4 1048576) (8 4))))
              ((symbol-function 'ptr-read-bytes) (lambda (&rest _) (cl-incf copies))))
      (let ((err (should-error (nelisp-gui-selection--read-property 2 3))))
        (should (equal err '(error "Selection INCR transfer cap"))))
      (should (= polls 1))
      (should (= discards 0))
      (should (= copies 0))
      (should (equal freed '(2000)))
      (should released))))

(ert-deftest selection-receive/exact-running-cap-is-allowed ()
  (let ((nelisp-gui-selection--receive [2 3 4 incr nil 1 10 20 nil 5])
        (nelisp-gui-selection-max-bytes 8) (freed nil))
    (cl-letf (((symbol-function 'nelisp-gui-selection--reply) (lambda (_) 2000))
              ((symbol-function 'nelisp-gui-selection--request) (lambda (&rest _) 42))
              ((symbol-function 'ptr-read-u8) (lambda (&rest _) 8))
              ((symbol-function 'nl-ffi-libffi-u32)
               (lambda (_ offset) (pcase offset (16 7) (12 0) (4 2) (8 4))))
              ((symbol-function 'ptr-read-bytes) (lambda (_ size) (make-string size ?x)))
              ((symbol-function 'nelisp-gui-xcb-call) (lambda (&rest _) (setq freed t))))
      (should (equal (nelisp-gui-selection--read-property 2 3) '(4 8 "xxxxxxx")))
      (should freed))))

(ert-deftest selection-receive/expired-missing-reply-still-times-out ()
  (let ((nelisp-gui-selection--state [1 2])
        (nelisp-gui-selection--receive [2 3 4 incr nil 1 10 20 nil 5])
        (polls 0) (discards 0) (released nil))
    (cl-letf (((symbol-function 'float-time) (lambda (&rest _) 100.0))
              ((symbol-function 'nl-ffi-memory-allocate) (lambda (_) 'storage))
              ((symbol-function 'nl-ffi-memory-address) (lambda (_) 1000))
              ((symbol-function 'nl-ffi-memory-release) (lambda (_) (setq released t)))
              ((symbol-function 'nelisp-gui-selection--flush) #'ignore)
              ((symbol-function 'nelisp-gui-xcb-check) (lambda (_) t))
              ((symbol-function 'sleep-for) (lambda (&rest _) (ert-fail "slept past deadline")))
              ((symbol-function 'nelisp-gui-xcb-call)
               (lambda (name &rest _)
                 (cond ((equal name "xcb_poll_for_reply") (cl-incf polls) 0)
                       ((equal name "xcb_discard_reply") (cl-incf discards))))))
      (should (equal (should-error (nelisp-gui-selection--reply 42))
                     '(error "Selection reply timeout")))
      (should (= polls 1))
      (should (= discards 1))
      (should released))))

(ert-deftest selection-receive/queued-cap-wins-after-scheduling-pause ()
  (let ((nelisp-gui-selection--state [1 2])
        (nelisp-gui-selection--events nil) (events 0))
    (cl-letf (((symbol-function 'float-time) (lambda (&rest _) 100.0))
              ((symbol-function 'sleep-for) (lambda (&rest _) (ert-fail "slept past deadline")))
              ((symbol-function 'nelisp-gui-xcb-poll)
               (lambda (_)
                 (cl-incf events)
                 (if (= events 1) '(:ignored t)
                   (error "Selection INCR transfer cap")))))
      ;; The queue can contain an earlier PropertyDelete or timestamp event.
      ;; Its presence must not cause the next ready cap violation to time out.
      (should (nelisp-gui-selection--wait-ready 10))
      (should (equal (should-error (nelisp-gui-selection--wait-ready 10))
                     '(error "Selection INCR transfer cap")))
      (should (= events 2))
      (should-not nelisp-gui-selection--events))))

(ert-deftest selection-receive/empty-queue-expires-after-scheduling-pause ()
  (let ((nelisp-gui-selection--state [1 2]) (polls 0))
    (cl-letf (((symbol-function 'float-time) (lambda (&rest _) 100.0))
              ((symbol-function 'sleep-for) (lambda (&rest _) (ert-fail "slept past deadline")))
              ((symbol-function 'nelisp-gui-xcb-poll) (lambda (_) (cl-incf polls) nil)))
      (should-not (nelisp-gui-selection--wait-ready 10))
      (should (= polls 1)))))
