(next-char-property-change
 (with-temp-buffer
   (insert "abcdef")
   (list (next-char-property-change 1) (next-char-property-change 7)
         (next-char-property-change 2 4) (next-char-property-change 2 1)))
 (with-temp-buffer
   (insert "abcdef")
   (put-text-property 2 4 'face 'bold)
   (mapcar #'next-char-property-change '(1 2 3 4)))
 (with-temp-buffer
   (insert "abcdef")
   (make-overlay 3 5)
   (mapcar #'next-char-property-change '(1 3 4 5)))
 (with-temp-buffer
   (insert "abcdef")
   (put-text-property 2 4 'face 'bold)
   (make-overlay 3 5)
   (mapcar #'next-char-property-change '(1 2 3 4 5)))
 (with-temp-buffer (insert "abc")
   (next-char-property-change (copy-marker 2)))
 (with-temp-buffer (condition-case err (next-char-property-change 0) (error err)))
 (condition-case err (next-char-property-change "x") (error err))
 (with-temp-buffer (insert "abcdef")
   (narrow-to-region 2 5)
   (next-char-property-change 2))
 (condition-case err (next-char-property-change) (error err)))

(previous-char-property-change
 (with-temp-buffer
   (insert "abcdef")
   (list (previous-char-property-change 7) (previous-char-property-change 1)
         (previous-char-property-change 5 3) (previous-char-property-change 2 4)))
 (with-temp-buffer
   (insert "abcdef")
   (put-text-property 2 4 'face 'bold)
   (mapcar #'previous-char-property-change '(7 4 3 2)))
 (with-temp-buffer
   (insert "abcdef")
   (make-overlay 3 5)
   (mapcar #'previous-char-property-change '(7 5 4 3)))
 (with-temp-buffer
   (insert "abcdef")
   (put-text-property 2 4 'face 'bold)
   (make-overlay 3 5)
   (mapcar #'previous-char-property-change '(7 5 4 3 2)))
 (with-temp-buffer (insert "abc")
   (previous-char-property-change (copy-marker 2)))
 (condition-case err (previous-char-property-change "x") (error err))
 (with-temp-buffer (insert "abcdef")
   (narrow-to-region 2 5)
   (previous-char-property-change 5))
 (condition-case err (previous-char-property-change) (error err)))

(get-char-property-and-overlay
 (with-temp-buffer (insert "abc")
   (get-char-property-and-overlay 1 'face))
 (with-temp-buffer (insert "abc")
   (put-text-property 1 3 'face 'text-face)
   (get-char-property-and-overlay 2 'face))
 (with-temp-buffer (insert "abcdef")
   (let ((overlay (make-overlay 2 5)))
     (overlay-put overlay 'face 'overlay-face)
     (let ((value (get-char-property-and-overlay 3 'face)))
       (list (car value) (eq (cdr value) overlay)
             (eq (overlay-buffer overlay) (current-buffer))))))
 (with-temp-buffer (insert "abcdef")
   (let ((outer (make-overlay 1 7)) (inner (make-overlay 2 5)))
     (overlay-put outer 'face 'outer-face)
     (overlay-put inner 'face 'inner-face)
     (car (get-char-property-and-overlay 3 'face))))
 (with-temp-buffer (insert "abcdef")
   (let ((outer (make-overlay 1 7)) (inner (make-overlay 2 5)))
     (overlay-put outer 'face 'outer-face)
     (overlay-put outer 'priority 10)
     (overlay-put inner 'face 'inner-face)
     (car (get-char-property-and-overlay 3 'face))))
 (with-temp-buffer (insert "abc")
   (put-text-property 1 3 'face 'text-face)
   (let ((overlay (make-overlay 1 3)))
     (overlay-put overlay 'face nil)
     (get-char-property-and-overlay 2 'face)))
 (let ((string (propertize "abc" 'face 'string-face)))
   (get-char-property-and-overlay 1 'face string))
 (get-char-property-and-overlay 3 'face "abc")
 (with-temp-buffer (insert "abcdef")
   (narrow-to-region 2 5)
   (list (get-char-property-and-overlay 2 'face)
         (condition-case err (get-char-property-and-overlay 1 'face)
           (error err))))
 (condition-case err (get-char-property-and-overlay 1 'face 17) (error err))
 (condition-case err (get-char-property-and-overlay 4 'face "abc") (error err)))

(make-overlay
 (with-temp-buffer (insert "abcdef")
   (let* ((original (make-overlay 2 5))
          (copy (copy-overlay original)))
     (overlay-put original 'face 'original-face)
     (list (eq (overlay-buffer copy) (current-buffer))
           (overlay-start copy) (overlay-end copy)
           (length (overlays-at 3)))))
 (with-temp-buffer (insert "abcdef")
   (let ((overlay (make-overlay 2 5)))
     (delete-overlay overlay)
     (list (overlay-buffer overlay) (length (overlays-at 3)))))
 (with-temp-buffer (insert "abcdef")
   (make-overlay 2 5)
   (let ((outer (current-buffer)))
     (with-temp-buffer (insert "xyz")
       (list (length (overlays-at 3))
             (with-current-buffer outer (length (overlays-at 3))))))))
