(eq
 (eq 'symbol 'symbol)
 (let ((object (cons 'a 'b))) (eq object object))
 (eq (cons 'a 'b) (cons 'a 'b))
 (let ((object "same")) (eq object object))
 (eq "same" (copy-sequence "same"))
 (condition-case err (eq) (error (list (car err) (cdr err))))
 (condition-case err (eq 'a 'a 'a) (error (list (car err) (cdr err)))))
(equal
 (equal '(a (b . c)) '(a (b . c)))
 (equal [a (b c)] [a (b c)])
 (equal "same" (copy-sequence "same"))
 (equal "a" "A")
 (let ((left (make-hash-table :test 'equal))
       (right (make-hash-table :test 'equal)))
   (puthash "key" '(value) left)
   (puthash "key" '(value) right)
   (equal left right))
 (condition-case err (equal '(a . b) '(a . c) 'extra)
   (error (list (car err)
                (and (consp (cdr err)) (symbolp (cadr err)) (cadr err)))))
 (condition-case err (equal '(a))
   (error (list (car err)
                (and (consp (cdr err)) (symbolp (cadr err)) (cadr err))))))
(memq
 (memq 'b '(a b c))
 (let* ((list '(a b c)) (tail (cdr list))) (eq (memq 'b list) tail))
 (memq 'missing '(a b c))
 (condition-case err (memq 'a '(a . b)) (error (list (car err) (cdr err))))
 (condition-case err (memq 'a "abc") (error (list (car err) (cdr err))))
 (condition-case err (memq 'a)
   (error (list (car err)
                (and (consp (cdr err)) (symbolp (cadr err)) (cadr err)))))
 (condition-case err (memq 'a '(a) 'extra)
   (error (list (car err)
                (and (consp (cdr err)) (symbolp (cadr err)) (cadr err))))))
