(ignore-errors (font-put (font-spec :family "monospace") :family "serif") t) (ignore-errors (font-put nil :family "x"))
(font-shape-gstring nil nil) (ignore-errors (font-shape-gstring '(bad) 'R2L))
(ignore-errors (and (font-spec) t)) (ignore-errors (and (font-spec :unknown 1) t))
(font-variation-glyphs nil 65) (ignore-errors (font-variation-glyphs nil -1))
(font-xlfd-name nil) (ignore-errors (font-xlfd-name "bad"))
(not (null (frame-font-cache))) (not (null (frame-font-cache (selected-frame))))
(internal-char-font 1) (with-temp-buffer (insert "x") (ignore-errors (internal-char-font (point))))
(null (list-fonts (font-spec))) (length (list-fonts (font-spec :family "monospace") nil 1))
(open-font nil) (ignore-errors (open-font "bad"))
(query-font nil) (ignore-errors (query-font "bad"))
