(frame-after-make-frame (frame-after-make-frame (selected-frame) t)
                         (frame-after-make-frame nil nil))
(frame-ancestor-p (frame-ancestor-p nil nil)
                  (condition-case e (frame-ancestor-p nil "bad") (error e)))
(frame-bottom-divider-width (frame-bottom-divider-width (selected-frame))
                            (condition-case e (frame-bottom-divider-width "bad") (error e)))
(frame-child-frame-border-width (frame-child-frame-border-width (selected-frame))
                                (condition-case e (frame-child-frame-border-width "bad") (error e)))
(frame-fringe-width (frame-fringe-width (selected-frame))
                    (condition-case e (frame-fringe-width "bad") (error e)))
(frame-id (frame-id (selected-frame))
          (condition-case e (frame-id "bad") (error e)))
(frame-internal-border-width (frame-internal-border-width (selected-frame))
                              (condition-case e (frame-internal-border-width "bad") (error e)))
(frame-native-height (frame-native-height (selected-frame))
                     (let ((w (split-window)))
                       (unwind-protect (frame-native-height (selected-frame))
                         (delete-window w))))
(frame-native-width (frame-native-width (selected-frame))
                    (let ((w (split-window)))
                      (unwind-protect (frame-native-width (selected-frame))
                        (delete-window w)))
                    (condition-case e (frame-native-width "bad") (error e)))
(frame-parent (frame-parent (selected-frame))
              (condition-case e (frame-parent "bad") (error e)))
(frame-pointer-visible-p (frame-pointer-visible-p (selected-frame))
                         (condition-case e (frame-pointer-visible-p "bad") (error e)))
(frame-position (frame-position (selected-frame))
                (let ((f (selected-frame)))
                  (unwind-protect (progn (set-frame-position f 7 9) (frame-position f))
                    (set-frame-position f 0 0)))
                (condition-case e (frame-position "bad") (error e)))
