(keymap--get-keyelt
 (keymap--get-keyelt 'plain nil)
 (keymap--get-keyelt '("Menu" . item) nil)
 (keymap--get-keyelt '("Menu" "Help" . item) nil)
 (keymap--get-keyelt '(menu-item "X" item :help "Tip") nil)
 (keymap--get-keyelt '(menu-item "X" item :filter identity) t)
 (keymap--get-keyelt '((keymap (65 . item)) . 65) nil)
 (condition-case err (keymap--get-keyelt) (error err))
 (condition-case err (keymap--get-keyelt 'plain) (error err)))

(map-keymap-internal
 (let* ((map (make-sparse-keymap))
        (seen nil))
   (define-key map [1] 'one-command)
   (define-key map [2] 'two-command)
   (list (map-keymap-internal
          (lambda (event binding) (push (cons event binding) seen)) map)
         seen))
 (let* ((parent (make-sparse-keymap))
        (map (make-sparse-keymap))
        (seen nil))
   (define-key parent [3] 'parent-command)
   (define-key map [1] 'child-command)
   (set-keymap-parent map parent)
   (list (eq (map-keymap-internal
              (lambda (event binding) (push (cons event binding) seen)) map)
             parent)
         seen))
 (condition-case err (map-keymap-internal (lambda (_event _binding)) 17)
   (error err)))

(accessible-keymaps
 (let ((map (make-sparse-keymap)))
   (mapcar #'car (accessible-keymaps map)))
 (let* ((map (make-sparse-keymap))
        (first (make-sparse-keymap))
        (second (make-sparse-keymap))
        (nested (make-sparse-keymap)))
   (define-key map [1] first)
   (define-key map [2] second)
   (define-key first [3] nested)
   (mapcar #'car (accessible-keymaps map)))
 (let* ((map (make-sparse-keymap))
        (child (make-sparse-keymap)))
   (define-key map [1] child)
   (list (mapcar #'car (accessible-keymaps map [1]))
         (mapcar #'car (accessible-keymaps map [9]))))
 (let* ((parent (make-sparse-keymap))
        (map (make-sparse-keymap))
        (child (make-sparse-keymap)))
   (define-key parent [2] child)
   (set-keymap-parent map parent)
   (mapcar #'car (accessible-keymaps map)))
 (condition-case err (accessible-keymaps 17) (error err))
 (condition-case err (accessible-keymaps (make-sparse-keymap) 17)
   (error err)))
