(list
 (list)
 (list 'alpha 'beta)
 (list nil '(x . y))
 (list 1 "text" [two] nil)
 (eq (list 'same) (list 'same)))
(nth
 (nth 0 '(alpha beta gamma))
 (nth 2 '(alpha beta gamma))
 (nth -1 '(alpha beta gamma))
 (nth 4 '(alpha beta gamma))
 (nth 1 '(alpha . omega))
 (let ((item (list 'identity))) (eq (nth 0 (list item)) item))
 (condition-case err (nth "0" '(alpha)) (error (list (car err) (cdr err))))
 (condition-case err (nth 0 17) (error (list (car err) (cdr err))))
 (condition-case err (nth) (error (list (car err) (cdr err))))
 (condition-case err (nth 1 '(alpha) 'extra) (error (list (car err) (cdr err)))))
(length
 (length nil)
 (length '(alpha beta gamma))
 (length "a雪")
 (length [alpha beta])
 (length (make-bool-vector 7 t))
 (condition-case err (length '(alpha . omega)) (error (list (car err) (cdr err))))
 (condition-case err (length 17) (error (list (car err) (cdr err))))
 (condition-case err (length) (error (list (car err) (cdr err))))
 (condition-case err (length nil 'extra) (error (list (car err) (cdr err)))))
