(car
 (car nil)
 (car '(alpha beta))
 (car '(alpha . omega))
 (condition-case err (car 17) (error (list (car err) (cdr err))))
 (condition-case err (car) (error (list (car err) (cdr err))))
 (condition-case err (car 'alpha 'beta) (error (list (car err) (cdr err)))))
(cdr
 (cdr nil)
 (cdr '(alpha beta))
 (cdr '(alpha . omega))
 (condition-case err (cdr 17) (error (list (car err) (cdr err))))
 (condition-case err (cdr) (error (list (car err) (cdr err))))
 (condition-case err (cdr 'alpha 'beta) (error (list (car err) (cdr err)))))
(cons
 (cons 'head 'tail)
 (cons 'head '(tail))
 (eq (cons 'same nil) (cons 'same nil))
 (let ((tail (list 'b)))
   (let ((cell (cons 'a tail)))
     (list (eq (cdr cell) tail) (eq cell tail) cell)))
 (let ((cell (cons 'a 'b)))
   (setcar cell 'x)
   (setcdr cell 'y)
   cell)
 (condition-case err (cons 'only-one) (error (list (car err) (cdr err))))
 (condition-case err (cons 'too 'many 'args) (error (list (car err) (cdr err)))))
