(logcount
 (list (logcount 0)
       (logcount 1)
       (logcount 15)
       (logcount 18446744073709551615))
 (list (logcount -1)
       (logcount -2)
       (logcount -3)
       (logcount -4))
 (list (logcount (ash 1 1024))
       (logcount (- (ash 1 1024)))
       (logcount (1- (ash 1 129)))
       (logcount (- (1- (ash 1 129)))))
 (condition-case error-data (logcount nil)
   (error (list (car error-data) (cdr error-data))))
 (condition-case error-data (logcount 1.5)
   (error (list (car error-data) (cdr error-data))))
 (condition-case error-data (logcount)
   (error (list (car error-data) (cdr error-data))))
 (condition-case error-data (logcount 1 2)
   (error (list (car error-data) (cdr error-data))))
)
