(call-last-kbd-macro
 (let* ((buffer (window-buffer (selected-window)))
        (text (with-current-buffer buffer (buffer-string))))
   (unwind-protect (condition-case e (call-last-kbd-macro) (error e))
     (with-current-buffer buffer (erase-buffer) (insert text))))
 (let* ((last-kbd-macro "a") (buffer (window-buffer (selected-window)))
        (text (with-current-buffer buffer (buffer-string))))
   (unwind-protect (condition-case e (call-last-kbd-macro 2) (error e))
     (with-current-buffer buffer (erase-buffer) (insert text))))
 (let* ((last-kbd-macro "a") (buffer (window-buffer (selected-window)))
        (text (with-current-buffer buffer (buffer-string))))
   (unwind-protect (call-last-kbd-macro 3)
     (with-current-buffer buffer (erase-buffer) (insert text)))))
(cancel-kbd-macro-events
 (cancel-kbd-macro-events)
 (let ((last-kbd-macro "abc")) (cancel-kbd-macro-events) last-kbd-macro))
(end-kbd-macro
 (condition-case e (end-kbd-macro) (error e))
 (progn (start-kbd-macro nil) (store-kbd-macro-event ?a) (end-kbd-macro) (stringp last-kbd-macro)))
(execute-kbd-macro
 (let* ((buffer (window-buffer (selected-window)))
        (text (with-current-buffer buffer (buffer-string))))
   (unwind-protect (condition-case e (execute-kbd-macro 1) (error e))
     (with-current-buffer buffer (erase-buffer) (insert text))))
 (let* ((buffer (window-buffer (selected-window)))
        (text (with-current-buffer buffer (buffer-string))))
   (unwind-protect (execute-kbd-macro "abc" 2)
     (with-current-buffer buffer (erase-buffer) (insert text))))
 (let* ((n 0) (buffer (window-buffer (selected-window)))
        (text (with-current-buffer buffer (buffer-string))))
   (unwind-protect (progn (execute-kbd-macro [97] 5 (lambda () (< (setq n (1+ n)) 3))) n)
     (with-current-buffer buffer (erase-buffer) (insert text))))
 (let* ((macro (make-vector 1 ?x)) (buffer (window-buffer (selected-window)))
        (text (with-current-buffer buffer (buffer-string))))
   (unwind-protect (progn (execute-kbd-macro macro) (length macro))
     (with-current-buffer buffer (erase-buffer) (insert text))))
 (progn (execute-kbd-macro [])
        (list (windowp (selected-window)) (windowp (selected-window)))))
(start-kbd-macro
 (progn (start-kbd-macro nil) (let ((v (bound-and-true-p defining-kbd-macro))) (end-kbd-macro) v))
 (let ((last-kbd-macro [?a])) (start-kbd-macro t t) (store-kbd-macro-event ?b) (end-kbd-macro) last-kbd-macro))
(store-kbd-macro-event
 (store-kbd-macro-event ?a)
 (let ((last-kbd-macro [])) (start-kbd-macro nil) (store-kbd-macro-event ?x) (store-kbd-macro-event ?y) (end-kbd-macro) last-kbd-macro))
