(menu-bar-menu-at-x-y
 (menu-bar-menu-at-x-y 0 -1)
 (condition-case e (menu-bar-menu-at-x-y -1 -1 t) (error (cons (car e) (cdr e))))
 (let ((b (get-buffer-create " *menu-probe*")))
   (with-current-buffer b (erase-buffer) (insert "changed")
     (put-text-property 1 2 'face 'bold))
   (let ((w (split-window)))
     (prog1 (list (bufferp b) (windowp w)
                  (menu-bar-menu-at-x-y 0 -1 (selected-frame)))
       (delete-window w)))))
(x-popup-menu
 (x-popup-menu nil (make-sparse-keymap))
 (condition-case e (x-popup-menu 'nonsense (make-sparse-keymap))
   (error (cons (car e) (cdr e))))
 (let ((b (get-buffer-create " *menu-popup-probe*"))
       (map (make-sparse-keymap)))
   (with-current-buffer b (erase-buffer) (insert "changed")
     (put-text-property 1 2 'face 'bold))
   (define-key map [menu-bar probe] '("Probe" . ignore))
   (let ((w (split-window)))
     (prog1 (list (bufferp b) (windowp w)
                  (x-popup-menu nil (list "Title" (list "Pane" (cons "item" 'value)))))
       (delete-window w)))))
