(current-minor-mode-maps
 (progn
   (defvar ccore-probe-minor-a nil)
   (defvar ccore-probe-minor-b nil)
   (let ((minor-mode-map-alist nil)
         (minor-mode-overriding-map-alist nil))
     (current-minor-mode-maps)))
 (let* ((a (make-sparse-keymap))
        (b (make-sparse-keymap))
        (ccore-probe-minor-a t)
        (ccore-probe-minor-b t)
        (minor-mode-map-alist
         (list (cons 'ccore-probe-minor-a a)
               (cons 'ccore-probe-minor-b b)))
        (minor-mode-overriding-map-alist nil))
   (mapcar (lambda (map) (cond ((eq map a) 'a) ((eq map b) 'b)))
           (current-minor-mode-maps)))
 (let* ((override (make-sparse-keymap))
        (ccore-probe-minor-a t)
        (minor-mode-map-alist nil)
        (minor-mode-overriding-map-alist
         (list (cons 'ccore-probe-minor-a override))))
   (mapcar (lambda (map) (eq map override))
           (current-minor-mode-maps)))
 (let* ((base (make-sparse-keymap))
        (override (make-sparse-keymap))
        (ccore-probe-minor-a t)
        (minor-mode-map-alist (list (cons 'ccore-probe-minor-a base)))
        (minor-mode-overriding-map-alist
         (list (cons 'ccore-probe-minor-a override))))
   (mapcar (lambda (map) (cond ((eq map base) 'base)
                               ((eq map override) 'override)))
           (current-minor-mode-maps)))
 (let* ((base (make-sparse-keymap))
        (ccore-probe-minor-a t)
        (minor-mode-map-alist (list (cons 'ccore-probe-minor-a base)))
        (minor-mode-overriding-map-alist
         '((ccore-probe-minor-a . nil))))
   (current-minor-mode-maps))
 (let* ((base-a (make-sparse-keymap))
        (base-b (make-sparse-keymap))
        (override-a (make-sparse-keymap))
        (override-b (make-sparse-keymap))
        (ccore-probe-minor-a t)
        (minor-mode-map-alist
         (list (cons 'ccore-probe-minor-a base-a)
               (cons 'ccore-probe-minor-a base-b)))
        (minor-mode-overriding-map-alist
         (list (cons 'ccore-probe-minor-a override-a)
               (cons 'ccore-probe-minor-a override-b))))
   (mapcar (lambda (map) (cond ((eq map base-a) 'base-a)
                               ((eq map base-b) 'base-b)
                               ((eq map override-a) 'override-a)
                               ((eq map override-b) 'override-b)))
           (current-minor-mode-maps)))
 (let* ((base (make-sparse-keymap))
        (ccore-probe-minor-a nil)
        (minor-mode-map-alist (list (cons 'ccore-probe-minor-a base)))
        (minor-mode-overriding-map-alist nil))
   (current-minor-mode-maps))
 (let* ((map (make-sparse-keymap))
        (ccore-probe-minor-a t)
        (minor-mode-map-alist
         (list (cons 'ccore-probe-minor-a 'ccore-probe-map-symbol)))
        (minor-mode-overriding-map-alist nil))
   (fset 'ccore-probe-map-symbol map)
   (unwind-protect
       (mapcar (lambda (item) (eq item map))
               (current-minor-mode-maps))
     (fmakunbound 'ccore-probe-map-symbol)))
 (let ((ccore-probe-minor-a t)
       (minor-mode-map-alist '((ccore-probe-minor-a . 17)))
       (minor-mode-overriding-map-alist nil))
   (current-minor-mode-maps))
 (let ((map (make-sparse-keymap)))
   (with-temp-buffer
     (make-local-variable 'ccore-probe-minor-a)
     (setq ccore-probe-minor-a t)
     (let ((minor-mode-map-alist
            (list (cons 'ccore-probe-minor-a map)))
           (minor-mode-overriding-map-alist nil))
       (mapcar (lambda (item) (eq item map))
               (current-minor-mode-maps)))))
 (condition-case err (current-minor-mode-maps 'extra)
   (error err)))
