(minor-mode-key-binding
 (progn
   (defvar ccore-probe-binding-a nil)
   (defvar ccore-probe-binding-b nil)
   (let ((minor-mode-map-alist nil)
         (minor-mode-overriding-map-alist nil))
     (minor-mode-key-binding [1])))
 (let* ((a (make-sparse-keymap))
        (b (make-sparse-keymap))
        (ccore-probe-binding-a t)
        (ccore-probe-binding-b t)
        (minor-mode-map-alist
         (list (cons 'ccore-probe-binding-a a)
               (cons 'ccore-probe-binding-b b)))
        (minor-mode-overriding-map-alist nil))
   (define-key a [1] 'alpha-command)
   (define-key b [1] 'beta-command)
   (minor-mode-key-binding [1]))
 (let* ((a (make-sparse-keymap))
        (b (make-sparse-keymap))
        (ccore-probe-binding-a nil)
        (ccore-probe-binding-b t)
        (minor-mode-map-alist
         (list (cons 'ccore-probe-binding-a a)
               (cons 'ccore-probe-binding-b b)))
        (minor-mode-overriding-map-alist nil))
   (define-key a [1] 'alpha-command)
   (define-key b [1] 'beta-command)
   (minor-mode-key-binding [1]))
 (let* ((a (make-sparse-keymap))
        (b (make-sparse-keymap))
        (ccore-probe-binding-a t)
        (ccore-probe-binding-b t)
        (minor-mode-map-alist
         (list (cons 'ccore-probe-binding-a a)
               (cons 'ccore-probe-binding-b b)))
        (minor-mode-overriding-map-alist nil))
   (define-key a [1] (make-sparse-keymap))
   (define-key b [1] 'beta-command)
   (mapcar (lambda (binding) (cons (car binding) (keymapp (cdr binding))))
           (minor-mode-key-binding [1])))
 (let* ((a (make-sparse-keymap))
        (b (make-sparse-keymap))
        (ccore-probe-binding-a t)
        (ccore-probe-binding-b t)
        (minor-mode-map-alist
         (list (cons 'ccore-probe-binding-a a)
               (cons 'ccore-probe-binding-b b)))
        (minor-mode-overriding-map-alist nil))
   (define-key a [1] (make-sparse-keymap))
   (define-key b [1] (make-sparse-keymap))
   (mapcar #'car (minor-mode-key-binding [1])))
 (let* ((base (make-sparse-keymap))
        (override (make-sparse-keymap))
        (ccore-probe-binding-a t)
        (minor-mode-map-alist
         (list (cons 'ccore-probe-binding-a base)))
        (minor-mode-overriding-map-alist
         (list (cons 'ccore-probe-binding-a override))))
   (define-key base [1] 'base-command)
   (define-key override [1] 'override-command)
   (minor-mode-key-binding [1]))
 (let* ((a (make-sparse-keymap))
        (ccore-probe-binding-a t)
        (minor-mode-map-alist
         (list (cons 'ccore-probe-binding-a a)))
        (minor-mode-overriding-map-alist nil))
   (define-key a [t] 'default-command)
   (list (minor-mode-key-binding [1])
         (minor-mode-key-binding [1] t)))
 (condition-case err (minor-mode-key-binding)
   (error err))
 (condition-case err (minor-mode-key-binding [1] nil 'extra)
   (error err)))
