(user-ptrp
 (user-ptrp nil)
 (user-ptrp t)
 (user-ptrp 0)
 (user-ptrp "pointer")
 (user-ptrp [user-ptr 1])
 (user-ptrp (make-record 'user-ptr 0 nil))
 (user-ptrp (make-record 'user-ptr 1 42))
 (user-ptrp (symbol-function 'cons))
 (condition-case err (user-ptrp) (error err))
 (condition-case err (user-ptrp nil nil) (error err)))

(module-function-p
 (module-function-p nil)
 (module-function-p t)
 (module-function-p 0)
 (module-function-p "function")
 (module-function-p [module-function 1])
 (module-function-p (make-record 'module-function 0 nil))
 (module-function-p (make-record 'module-function 1 42))
 (module-function-p (symbol-function 'cons))
 (module-function-p (lambda () 1))
 (condition-case err (module-function-p) (error err))
 (condition-case err (module-function-p nil nil) (error err)))
