;;; nelisp-native-boundary-cases.el --- named bare-native probes -*- lexical-binding: t; -*-
;; Each row is (NAME FORM), compatible with test/nelisp-emacs-lib/c-core-parity-driver.el.
(puthash (let ((h (make-hash-table))) (list (puthash 'key 17 h) (gethash 'key h))))
(puthash (let ((h (make-hash-table))) (puthash 'key 17 h) (list (puthash 'key 23 h) (gethash 'key h))))
(puthash (puthash 'key 17 "bad"))
(puthash (puthash 'key 17 nil))
(puthash (puthash 'key 17 'not-a-table))
(puthash (puthash 'key 17 9))
(puthash (puthash))
(puthash (puthash 'key))
(puthash (puthash 'key 17 "bad" 4))
(puthash (puthash "bad"))
(puthash (puthash "bad" "bad" "bad" 4))
(remhash (let ((h (make-hash-table))) (puthash 'key 17 h) (list (remhash 'key h) (gethash 'key h))))
(remhash (let ((h (make-hash-table))) (list (remhash 'missing h) (hash-table-count h))))
(remhash (remhash 'key "bad"))
(remhash (remhash 'key 9))
(remhash (remhash 'key 'not-a-table))
(remhash (remhash))
(remhash (remhash "bad"))
(remhash (remhash 'key "bad" 3))
(remhash (remhash 9))
(remhash (remhash 9 10 11))
(string-bytes (string-bytes "abc"))
(string-bytes (string-bytes (make-string 2048 ?x)))
(string-bytes (string-bytes (unibyte-string 65 0 255)))
(string-bytes (string-bytes "λ"))
(string-bytes (string-bytes 'not-a-string))
(string-bytes (string-bytes nil))
(string-bytes (string-bytes 9))
(string-bytes (string-bytes [1 2]))
(string-bytes (string-bytes))
(string-bytes (string-bytes "abc" "extra"))
