;;; obarray-clear-1.el --- Public obarray clear transitions -*- lexical-binding: t; -*-

(obarray-clear
 (let* ((table (obarray-make)) (symbol (intern "clear-owned" table)))
   (set symbol 42)
   (put symbol 'property 'kept)
   (list (obarray-clear table) (intern-soft "clear-owned" table)
         (symbol-value symbol) (get symbol 'property)
         (eq symbol (intern "clear-owned" table))))
 (let ((left (obarray-make)) (right (obarray-make)))
   (intern "separate" left)
   (let ((symbol (intern "separate" right)))
     (obarray-clear left)
     (list (intern-soft "separate" left)
           (eq symbol (intern-soft "separate" right)))))
 (let ((table (obarray-make)) (count 0))
   (dotimes (index 40) (intern (format "owned-%d" index) table))
   (obarray-clear table)
   (mapatoms (lambda (_symbol) (setq count (1+ count))) table)
   (list count (obarray-clear table)))
 (condition-case err (obarray-clear nil) (error err))
 (condition-case err (obarray-clear [0 0]) (error err))
 (condition-case err (obarray-clear) (error err))
 (condition-case err (obarray-clear (obarray-make) nil) (error err)))
