(x-display-save-under (x-display-save-under) (x-display-save-under nil))
(x-display-screens (x-display-screens) (x-display-screens nil))
(x-display-visual-class (x-display-visual-class) (x-display-visual-class nil))
(x-export-frames (x-export-frames) (x-export-frames nil 'png))
(x-file-dialog (x-file-dialog "Choose" "/tmp") (x-file-dialog "Choose" "/tmp" "sample.txt" t))
(x-gtk-debug (fboundp 'x-gtk-debug) (fboundp 'x-gtk-debug))
(x-gtk-launch-uri (x-gtk-launch-uri nil "https://example.com") (x-gtk-launch-uri nil "file:///tmp"))
(x-hide-tip (x-hide-tip) (let ((b (get-buffer-create " *pgtkfns-tip*"))) (unwind-protect (progn (with-current-buffer b (insert "tip")) (x-hide-tip)) (kill-buffer b))))
(x-open-connection (x-open-connection 7) (x-open-connection 7 "resource: value" t))
(x-select-font (x-select-font) (x-select-font nil t))
(x-server-max-request-size (x-server-max-request-size) (x-server-max-request-size nil))
(x-show-tip (x-show-tip "tip") (x-show-tip "changed tip" nil '((left . 10)) 1 2 3))
