(menu-or-popup-active-p
  (let ((b (get-buffer-create " *pgtkmenu-probe*")))
    (with-current-buffer b (insert "menu state probe"))
    (let ((w (split-window)))
      (prog1 (list (menu-or-popup-active-p) (windowp w)
                   (bufferp (window-buffer w)))
        (delete-window w) (kill-buffer b))))
  (let ((b (get-buffer-create " *pgtkmenu-probe-2*")))
    (with-current-buffer b (insert "x"))
    (prog1 (menu-or-popup-active-p) (kill-buffer b))))
 (x-menu-bar-open-internal
  (let ((w (split-window)))
    (prog1 (condition-case e (x-menu-bar-open-internal)
             (error e))
      (delete-window w)))
  (let ((b (get-buffer-create " *pgtkmenu-probe-frame*")))
    (with-current-buffer b (insert "frame argument"))
    (prog1 (condition-case e (x-menu-bar-open-internal (selected-frame))
             (error e))
      (kill-buffer b)))
  (condition-case e (x-menu-bar-open-internal 'bad-frame)
    (error e)))
