(external-debugging-output (condition-case e (external-debugging-output 65) (error e))
                            (condition-case e (external-debugging-output "x") (error e)))
(flush-standard-output (flush-standard-output)
                       (let ((standard-output nil)) (flush-standard-output)))
(print--preprocess (let* ((x (list 'changed)) (object (list x x)) (print-circle t))
                     (print--preprocess object)
                     (list (null (print--preprocess object)) (eq (car object) x)))
                   (let ((print-circle nil)) (print--preprocess (list 'plain)))
                   (let ((print-circle nil)) (null (print--preprocess (list 'other)))))
(redirect-debugging-output (redirect-debugging-output nil)
                           (condition-case e (redirect-debugging-output 42) (error e)))
