(continue-process (condition-case e (continue-process) (error e))
                  (condition-case e (continue-process "c-core-no-such-process") (error e)))
(internal-default-interrupt-process (condition-case e (internal-default-interrupt-process) (error e))
                                    (condition-case e (internal-default-interrupt-process "c-core-no-such-process") (error e)))
(internal-default-process-filter (let* ((b (get-buffer-create " *cc-p1-filter*"))
                                        (p (start-process "cc-p1-filter" b "true")))
                                   (with-current-buffer b (erase-buffer) (insert "state"))
                                   (unwind-protect
                                       (progn (condition-case nil (internal-default-process-filter p "changed") (error nil))
                                              (with-current-buffer b (equal (buffer-string) "statechanged")))
                                     (delete-process p) (kill-buffer b)))
                                 (condition-case e (internal-default-process-filter nil "x") (error e)))
(internal-default-process-sentinel (let ((b (get-buffer-create " *cc-p1-sentinel*")))
                                     (with-current-buffer b (erase-buffer) (insert "state"))
                                     (condition-case e (internal-default-process-sentinel nil "msg") (error e)))
                                   (condition-case e (internal-default-process-sentinel nil "msg") (error e)))
(internal-default-signal-process (condition-case e (internal-default-signal-process "c-core-no-such-process" 2) (error e))
                                 (condition-case e (internal-default-signal-process "c-core-no-such-process" 9 t) (error e)))
(interrupt-process (let ((b (get-buffer-create " *cc-p1-interrupt*")))
                     (with-current-buffer b
                       (condition-case e (interrupt-process) (error e))))
                   (condition-case e (interrupt-process "c-core-no-such-process" t) (error e)))
(list-system-processes (listp (list-system-processes))
                       (listp (list-system-processes)))
(make-serial-process (condition-case nil (make-serial-process) (error nil))
                     (condition-case nil (make-serial-process :port "/no/such/c-core-port" :speed 9600) (error t)))
(network-interface-info (condition-case e (network-interface-info nil) (error e))
                        (let ((x (network-interface-info "lo"))) (or (null x) (listp x))))
(network-interface-list (let ((x (network-interface-list))) (or (null x) (listp x)))
                        (let ((x (network-interface-list t 'ipv4))) (or (null x) (listp x))))
(network-lookup-address-info (progn (network-lookup-address-info "127.0.0.1" 'ipv4 'numeric) t)
                             (condition-case e (network-lookup-address-info nil) (error e)))
(process-datagram-address (condition-case e (process-datagram-address nil) (error e))
                          (let ((p (start-process "cc-p1-dgram" nil "true")))
                            (unwind-protect (condition-case nil (progn (process-datagram-address p) t) (error t))
                              (delete-process p))))
