(function-equal (function-equal 'car 'car)
               (function-equal '(lambda (x) x) '(lambda (x) x))
               (function-equal '(lambda (x) x) '(lambda (y) y))
               (function-equal 7 7)
               (function-equal nil t))
(profiler-cpu-log (null (profiler-cpu-log))
                  (let ((started (profiler-cpu-start 1000000)))
                    (unwind-protect
                        (let ((a (profiler-cpu-log)) (b (profiler-cpu-log)))
                          (list (hash-table-p a) (hash-table-p b)
                                (profiler-cpu-running-p)))
                      (profiler-cpu-stop))))
(profiler-cpu-running-p (null (profiler-cpu-running-p))
                        (let ((w (split-window))
                              (b (get-buffer-create " *profiler-probe*")))
                          (unwind-protect
                              (progn
                                (with-current-buffer b
                                  (erase-buffer)
                                  (insert "sample")
                                  (add-text-properties 1 7 '(face bold)))
                                (profiler-cpu-start 2000000)
                                (prog1 (list (profiler-cpu-running-p)
                                             (bufferp b)
                                             (get-text-property 1 'face b))
                                       (profiler-cpu-stop)))
                            (delete-window w)
                            (kill-buffer b))))
(profiler-cpu-start (condition-case e (profiler-cpu-start 0) (error (list (car e) (cdr e))))
                    (let ((result (profiler-cpu-start 3000000)))
                      (profiler-cpu-stop) result)
                    (condition-case e (profiler-cpu-start "bad") (error (list (car e) (cdr e)))))
(profiler-cpu-stop (profiler-cpu-stop)
                   (progn (profiler-cpu-start 4000000)
                          (list (profiler-cpu-stop) (profiler-cpu-stop))))
(profiler-memory-log (null (profiler-memory-log))
                     (progn (profiler-memory-start)
                            (unwind-protect
                                (let ((a (profiler-memory-log)) (b (profiler-memory-log)))
                                  (list (hash-table-p a) (hash-table-p b)
                                        (profiler-memory-running-p)))
                              (profiler-memory-stop))))
(profiler-memory-running-p (null (profiler-memory-running-p))
                           (progn (profiler-memory-start)
                                  (prog1 (profiler-memory-running-p)
                                    (profiler-memory-stop))))
(profiler-memory-start (progn (profiler-memory-start)
                              (prog1 (profiler-memory-running-p)
                                (profiler-memory-stop)))
                       (progn (profiler-memory-start)
                              (profiler-memory-start)
                              (prog1 (profiler-memory-running-p)
                                (profiler-memory-stop))))
(profiler-memory-stop (profiler-memory-stop)
                      (progn (profiler-memory-start)
                             (list (profiler-memory-stop) (profiler-memory-stop))))
