(read-char-exclusive
 (let ((unread-command-events '(65)) (unread-post-input-method-events nil)
       (emacs-command-loop--unread-events nil))
   (list (read-char-exclusive nil nil 0) unread-command-events))
 (let ((unread-command-events '(f1 mouse-1 66)) (unread-post-input-method-events nil)
       (emacs-command-loop--unread-events nil))
   (list (read-char-exclusive nil nil 0) unread-command-events))
 (let ((unread-command-events '(return tab escape))
       (unread-post-input-method-events nil) (emacs-command-loop--unread-events nil))
   (list (read-char-exclusive nil nil 0) (read-char-exclusive nil nil 0)
         (read-char-exclusive nil nil 0)))
 (let ((unread-command-events '(#x4000061 #x2000061 #x8000061))
       (unread-post-input-method-events nil) (emacs-command-loop--unread-events nil))
   (list (read-char-exclusive nil nil 0) (read-char-exclusive nil nil 0)
         (read-char-exclusive nil nil 0)))
 (let ((unread-command-events nil) (unread-post-input-method-events nil)
       (emacs-command-loop--unread-events nil))
   (read-char-exclusive nil nil 0))
 (let ((unread-command-events '(f1)) (unread-post-input-method-events nil)
       (emacs-command-loop--unread-events nil))
   (list (read-char-exclusive nil nil 0) unread-command-events))
 (let ((unread-command-events '(97)) (unread-post-input-method-events nil)
       (emacs-command-loop--unread-events nil)
       (input-method-function (lambda (key) (list (+ key 1)))))
   (read-char-exclusive nil t 0))
 (let ((unread-command-events '(97)) (unread-post-input-method-events nil)
       (emacs-command-loop--unread-events nil)
       (input-method-function (lambda (key) (list (+ key 1)))))
   (read-char-exclusive nil nil 0))
 (let ((unread-command-events '(97)) (unread-post-input-method-events nil)
       (emacs-command-loop--unread-events nil)
       (input-method-function (lambda (_key) '(120 121))))
   (list (read-char-exclusive nil t 0) unread-post-input-method-events
         (read-char-exclusive nil t 0)))
 (let ((unread-command-events '(97 98)) (unread-post-input-method-events nil)
       (emacs-command-loop--unread-events nil)
       (input-method-function (lambda (key) (if (= key 97) nil (list key)))))
   (read-char-exclusive nil t 0))
 (let ((unread-command-events '(65)) (unread-post-input-method-events '(66))
       (emacs-command-loop--unread-events nil))
   (list (read-char-exclusive nil nil 0) unread-command-events
         unread-post-input-method-events))
 (let ((inhibit-interaction t) (unread-command-events '(65)))
   (condition-case err (read-char-exclusive nil nil 0) (error err)))
 (condition-case err (read-char-exclusive nil nil 0 nil) (error err)))

(read-char
 (let ((unread-command-events '(97)) (unread-post-input-method-events nil)
       (emacs-command-loop--unread-events nil)
       (input-method-function (lambda (_key) '(120 121))))
   (list (read-char-exclusive nil t 0) (read-char nil t 0)
         unread-post-input-method-events)))

(read-event
 (let ((unread-command-events '(97)) (unread-post-input-method-events nil)
       (emacs-command-loop--unread-events nil)
       (input-method-function (lambda (_key) '(120 121))))
   (list (read-char-exclusive nil t 0) (read-event nil t 0)
         unread-post-input-method-events)))
