(all-threads (> (length (all-threads)) 0)
             (let ((th (make-thread (lambda () nil) "probe-thread"))) (and th (consp (all-threads)))))
(condition-mutex (let* ((m (make-mutex "cm")) (c (make-condition-variable m))) (eq (condition-mutex c) m))
                 (condition-case e (condition-mutex nil) (error (list (car e) (cdr e)))))
(condition-name (let* ((m (make-mutex)) (c (make-condition-variable m "named"))) (equal (condition-name c) "named"))
                (condition-name (make-condition-variable (make-mutex)))
                (condition-case e (condition-name nil) (error (list (car e) (cdr e)))))
(condition-notify (let* ((m (make-mutex)) (c (make-condition-variable m))) (condition-case e (condition-notify c) (error (car e))))
                   (let* ((m (make-mutex)) (c (make-condition-variable m))) (condition-case e (condition-notify c t) (error (car e))))
                   (condition-case e (condition-notify nil) (error (list (car e) (cdr e)))))
(condition-wait (let* ((m (make-mutex)) (c (make-condition-variable m))) (condition-case e (condition-wait c) (error (car e))))
                 (condition-case e (condition-wait nil) (error (list (car e) (cdr e)))))
(current-thread (eq (current-thread) (current-thread)) (consp (all-threads)))
(make-condition-variable (let* ((m (make-mutex "associated")) (c (make-condition-variable m "x"))) (and (eq (condition-mutex c) m) (null (condition-name c))))
                         (condition-case e (make-condition-variable nil) (error (list (car e) (cdr e)))))
(make-mutex (let ((m (make-mutex "changed-name"))) (equal (mutex-name m) "changed-name"))
            (let ((m (make-mutex))) (null (mutex-name m))))
(make-thread (let ((called nil) (th (make-thread (lambda () (setq called t)) "named" t))) (and called (eq (thread--blocker th) nil)))
             (condition-case e (make-thread (lambda () nil) 7) (error (list (car e) (cdr e))))
             (condition-case e (make-thread (lambda () nil) 7) (error (list (car e) (cdr e)))))
(mutex-name (equal (mutex-name (make-mutex "named")) "named")
            (mutex-name (make-mutex))
            (condition-case e (mutex-name nil) (error (list (car e) (cdr e)))))
(thread--blocker (thread--blocker (current-thread))
                 (condition-case e (thread--blocker nil) (error (list (car e) (cdr e)))))
(thread-buffer-disposition (thread-buffer-disposition (current-thread))
                            (condition-case e (thread-buffer-disposition nil) (error (list (car e) (cdr e)))))
