(bare-symbol-p
 (list (bare-symbol-p 'plain)
       (bare-symbol-p nil)
       (bare-symbol-p t)
       (bare-symbol-p :keyword)
       (bare-symbol-p (make-symbol "uninterned")))
 (list (bare-symbol-p 17)
       (bare-symbol-p 1.5)
       (bare-symbol-p "text")
       (bare-symbol-p '(plain))
       (bare-symbol-p [plain])
       (bare-symbol-p (make-hash-table :test 'eq)))
 (condition-case err (bare-symbol-p)
   (error (list (car err)
                (and (consp (cdr err)) (symbolp (cadr err)) (cadr err)))))
 (condition-case err (bare-symbol-p 'plain 'extra)
   (error (list (car err)
                (and (consp (cdr err)) (symbolp (cadr err)) (cadr err))))))
(byteorder
 (byteorder)
 (condition-case err (byteorder 'extra)
   (error (list (car err)
                (and (consp (cdr err)) (symbolp (cadr err)) (cadr err))))))
(signal-names
 (signal-names)
 (condition-case err (signal-names 'extra)
   (error (list (car err)
                (and (consp (cdr err)) (symbolp (cadr err)) (cadr err))))))
