;;; generate-native-real-corpus.el --- GNU 31.1 fixture recipe -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
;; Usage: F3_HOST_DIR=target/f3-host emacs -Q --batch -L lisp -L src
;;   -L scripts -l test/support/generate-native-real-corpus.el
;; Compile whole, unmodified GNU source files, never reconstructed function bodies.
;; GNU for Windows defaults to CRLF/cp1252; fixtures must be byte-identical to Linux.
(when (eq system-type 'windows-nt)
  (prefer-coding-system 'utf-8-unix)
  (setq coding-system-for-write 'utf-8-unix))
(require 'cl-lib)
(require 'bytecomp)
(require 'nelisp-bytecode-native-consumer)
(require 'nelisp-bytecode-ir)
(require 'nelisp-bytecode-coverage-audit)
(load (expand-file-name "native-real-corpus-exclusions.el"
                        (file-name-directory (or load-file-name buffer-file-name))) nil t t)
(load (expand-file-name "native-real-corpus-inputs.el"
                        (file-name-directory (or load-file-name buffer-file-name))) nil t t)
(defun f3-host-print (object)
  (let ((print-length nil) (print-level nil) (print-circle nil)
        (print-escape-newlines t) (print-escape-nonascii t)
        (print-escape-multibyte t) (print-quoted t))
    (prin1-to-string object)))
(defun f3-host-observe (function args)
  "Record values or complete structured error conditions."
  (f3-real-corpus-observe function args))
(defun f3-host-tree (depth &optional first)
  "Build distinct leaves so every car/cdr path has a different witness."
  (setq first (or first 1))
  (if (= depth 0) first
    (cons (f3-host-tree (1- depth) first)
          (f3-host-tree (1- depth) (+ first (expt 2 (1- depth)))))))
(let* ((work (file-name-as-directory (expand-file-name (or (getenv "F3_HOST_DIR") "target/f3-host"))))
       (destination (or (getenv "F3_FIXTURE_OUT") "test/support/native-real-corpus-fixtures.el"))
       (tree (f3-host-tree 4))
       (position '(window 42 (10 . 20) 123 ("text" . 2) 43 (3 . 4) (image sample) (1 . 2) (30 . 40)))
       (specs nil) (libraries '("subr" "subr-x" "seq" "cl-lib" "cl-extra" "ring" "calendar"))
       (definitions nil) (sources nil) (rows nil)
       (audit (plist-get (nelisp-bytecode-coverage-audit-run) :opcodes)))
  (unless (equal emacs-version "31.1") (error "GNU Emacs 31.1 required"))
  (make-directory work t)
  (dolist (library libraries)
    (let* ((installed (locate-library library))
           (source (concat (file-name-sans-extension installed) ".el"))
           (copy (expand-file-name (concat library ".el") work)))
      (unless (file-exists-p source) (setq source (concat source ".gz")))
      (with-temp-buffer (insert-file-contents source)
                        (write-region (point-min) (point-max) copy nil 'silent)
                        (push (list library (secure-hash 'sha256 (current-buffer))) sources))
      (let ((byte-compile-dynamic-docstrings nil) (byte-compile-warnings nil))
        (unless (byte-compile-file copy) (error "GNU compile failed: %s" library)))
      (dolist (entry (nelisp-bytecode-native-consumer-read-elc-functions (concat copy "c")))
        (push (list (car entry) library (cdr entry)) definitions))))
  (dolist (name '(caar cadr cdar cddr caaar caadr cadar caddr cdaar cdadr cddar cdddr
                 caaaar caaadr caadar caaddr cadaar cadadr caddar cadddr
                 cdaaar cdaadr cdadar cdaddr cddaar cddadr cdddar cddddr))
    (push (list name (list (list tree) '(nil) '(17))) specs))
  (dolist (name '(zerop plusp minusp oddp evenp fixnump bignump))
    (push (list name (append '((0) (3) (-4) (bad))
                            (when (memq name '(fixnump bignump))
                              (list (list (1+ most-positive-fixnum))
                                    (list (1- most-negative-fixnum)))))) specs))
  (dolist (name '(posn-window posn-area posn-point posn-x-y posn-actual-col-row
                 posn-timestamp posn-string posn-image posn-object posn-object-x-y
                 posn-object-width-height))
    (push (list name (list (list position) '(nil) '(17))) specs))
  (setq specs
        (append (nreverse specs)
                '((xor ((nil nil) (t nil) (nil token) (left right)))
                  (ignore (() (1) (a b))) (always (() (1) (a b)))
                  (ensure-list ((nil) (a) ((a b)) ([1 2])))
                  (ensure-proper-list ((nil) (a) ((a b)) ((a . b))))
                  (syntax-class (((0)) ((13)) ((65537)) (bad)))
                  (mouse-movement-p (((mouse-movement where)) ((mouse-1 where)) (nil) (7)))
                  (event-click-count (((mouse-1 where 3)) ((mouse-1 where)) (nil) ((a . 3))))
                  (event-line-count (((wheel-up where 0 4)) ((wheel-up where)) (nil) ((a . 3))))
                  (event-start (((mouse-1 (window 42))) ((touchscreen-begin (id window 7)))))
                  (event-end (((drag-mouse-1 (window 42) (window 80))) ((mouse-1 (window 42)))))
                  (string-greaterp (("b" "a") ("a" "b") ("a" "a") (17 "a")))
                  (string-prefix-p (("ab" "abcd") ("bc" "abcd") ("AB" "abcd" t) (17 "abc")))
                  (string-suffix-p (("cd" "abcd") ("bc" "abcd") ("CD" "abcd" t) (17 "abc")))
                  (string-chop-newline (("abc\n") ("abc") ("\n") (17)))
                  (string-truncate-left (("abcdef" 3) ("abc" 10) (17 2)))
                  (string-limit (("abcdef" 3) ("abc" 10) (17 2)))
                  (seq-first (((a b)) ([3 4]) ("abc") (nil) (17)))
                  (seq-rest (((a b)) ([3 4]) ("abc") (nil) (17)))
                  (seq--elt-safe (((a b) 1) ((a b) 8) (nil 0)))
                  (seq--into-list (([1 2]) ("ab") ((a b)) (nil) (17)))
                  (seq--into-vector (((1 2)) ("ab") ([1 2]) (17)))
                  (seq--into-string (((65 66)) ([65 66]) ("ab") ((bad))))
                  (cl-values-list (((1 2)) (nil) (17)))
                  (cl-multiple-value-list (((1 2)) (17) (nil)))
                  (cl-multiple-value-apply ((+ (1 2 3)) (list (a b)) (car (17))))
                  (cl-digit-char-p ((?3) (?a 16) (?z 36) (?z 10) (bad)))
                  (cl-copy-list (((a b)) ((a . b)) (nil) (17)))
                  (cl-pairlis (((a b) (1 2)) (nil nil) ((a) (1) ((z . 0))) (17 nil)))
                  (cl-signum ((3) (-4) (0) (bad)))
                  (cl-revappend (((a b) (c d)) (nil (c)) (17 nil)))
                  (cl-nreconc (((a b) (c d)) (nil (c)) (17 nil)))
                  (cl-list-length (((a b c)) (nil) (17)))
                  (cl-tailp (((b c) (a b c)) (nil (a b)) (17 (a b))))
                  (progress-reporter-text (((0 . [a b c "working" e f g context])) ((0 . [])) (17)))
                  (progress-reporter-context (((0 . [a b c "working" e f g context])) ((0 . [])) (17)))
                  (subr-primitive-p (((:f3-subr car)) (17) (nil) ((lambda (x) x))))
                  (primitive-function-p (((:f3-subr car)) (17) (nil) ((lambda (x) x))))
                  (string-equal-ignore-case (("Ab" "aB") ("a" "b") (17 "a")))
                  (ring-p (((0 0 . [nil nil])) (nil) (17)))
                  (make-ring ((0) (3) (bad)))
                  (ring-length (((0 2 . [a b nil])) ((0 0 . [])) (17)))
                  (ring-empty-p (((0 2 . [a b nil])) ((0 0 . [])) (17)))
                  (ring-size (((0 2 . [a b nil])) ((0 0 . [])) (17)))
                  (ring-copy (((0 2 . [a b nil])) ((0 0 . [])) (17)))
                  (ring-plus1 ((0 3) (2 3) (bad 3)))
                  (ring-minus1 ((0 3) (2 3) (bad 3)))
                  (ring-index ((0 1 3 5) (4 1 3 5) (-1 2 3 5) (0 1 0 5)))
                  (calendar-extract-month (((10 5 2026)) ((1 1 2000)) (nil) (17)))
                  (calendar-extract-day (((10 5 2026)) ((1 1 2000)) (nil) (17)))
                  (calendar-extract-year (((10 5 2026)) ((1 1 2000)) (nil) (17))))))
  (dolist (spec specs)
    (let* ((name (car spec)) (entry (assq name definitions))
           (library (nth 1 entry)) (function (nth 2 entry))
           (decoded (and function (nelisp-bytecode-ir-decode-result (aref function 1) (aref function 2))))
           (opcodes (and decoded (delete-dups (mapcar (lambda (instruction) (aref instruction 1))
                                                    (append (plist-get decoded :instructions) nil)))))
           (pending (cl-remove-if
                     (lambda (opcode)
                       (let ((row (aref audit opcode)))
                         (and (memq (plist-get row :status) '(native-raw-i64-slice legacy-jit-only frame-represented structurally-decoded))
                              (eq (plist-get (plist-get row :valid-fixture) :frame-status) 'complete)))) opcodes)))
      (push (list :name name :source (concat (cond ((equal library "subr") "lisp/")
                                                              ((equal library "calendar") "lisp/calendar/")
                                                              (t "lisp/emacs-lisp/"))
                                                       (or library "missing") ".el")
                  :source-sha256 (cadr (assoc library sources))
                  :bytecode-sha256 (and function (secure-hash 'sha256 (f3-host-print function)))
                  :function function :opcodes opcodes
                  :excluded (cond ((null function) "GNU .elc definition missing")
                                  (pending (format "coverage audit pending opcodes %S" pending))
                                  (t (cdr (assq name f3-real-corpus-exclusions))))
                  :cases (and function (mapcar (lambda (args) (list :args args :gnu (f3-host-observe function args))) (cadr spec)))) rows)))
  (with-temp-file destination
    (insert ";;; native-real-corpus-fixtures.el --- Unmodified GNU Emacs 31.1 byte code -*- lexical-binding: t; -*-\n"
            ";; SPDX-License-Identifier: GPL-3.0-or-later\n"
            ";; Generated by test/support/generate-native-real-corpus.el.\n"
            ";; GNU source copyright and GPLv3+ apply to these byte-code objects.\n"
            ";; Errors retain their condition symbol and complete structured data.\n"
            "(defconst f3-real-corpus\n  '")
    (insert "(\n  " (mapconcat #'f3-host-print (reverse rows) "\n  ") "\n  ))\n(provide 'native-real-corpus-fixtures)\n"))
  (princ (format "F3-HOST candidates=%d admitted=%d\n" (length rows) (cl-count nil rows :key (lambda (row) (plist-get row :excluded))))))
