;;; generate-native-corpus-u10.el --- GNU oracle and audited cohort -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
;; GNU for Windows defaults to CRLF/cp1252; fixtures must be byte-identical to Linux.
(when (eq system-type 'windows-nt)
  (prefer-coding-system 'utf-8-unix)
  (setq coding-system-for-write 'utf-8-unix))
(require 'json)
(require 'nelisp-bytecode-coverage-audit)
(load (expand-file-name "test/support/native-corpus-u10-projection.el") nil t t)
(load (expand-file-name "test/support/native-corpus-u10-fixtures.el") nil t t)
(defun u10-mixed-function (fixture)
  "Retain the advertised slot; add a rooted GC call on every return edge.
Buffer/marker descriptor loads become varrefs of fresh live test objects.
These process-local objects are deliberately outside the artifact recipe.
All branch/handler/table addresses are relocated; all other bytes are kept."
  (let* ((constants (u10-materialize fixture))
         (code (apply #'unibyte-string (append (alist-get 'bytecode fixture) nil)))
         (instructions (append (plist-get (nelisp-bytecode-ir-decode-result code constants) :instructions) nil))
         (gc-index (length constants)) (offsets (make-hash-table :test 'eql))
         (position 0) chunks)
    (dolist (instruction instructions)
      (puthash (aref instruction 0) position offsets)
      (setq position (+ position (- (aref instruction 2) (aref instruction 0))
                        (if (= (aref instruction 1) 135) 5 0))))
    (dolist (instruction instructions)
      (let* ((opcode (aref instruction 1)) (start (aref instruction 0))
             (bytes (append (substring code start (aref instruction 2)) nil))
             (index (plist-get (aref instruction 4) :constant-index)))
        (when (memq opcode '(130 131 132 133 134 49 50))
          (let ((target (gethash (aref instruction 3) offsets)))
            (u10-assert target "relocation target exists")
            (setq bytes (list opcode (logand target 255) (ash target -8)))))
        (when (and index (listp (aref (alist-get 'constants fixture) index))
                   (member (alist-get 'kind (aref (alist-get 'constants fixture) index))
                           '("current-buffer" "marker")))
          (u10-assert (< index 6) "compact object varref")
          (setq bytes (list (+ 8 index)))
          (aset constants index (intern (format "u10-object-%d" index))))
        (when (= opcode 135)
          (setq bytes (append (list 129 (logand gc-index 255) (ash gc-index -8) 32 136) bytes)))
        (push bytes chunks)))
    ;; Switch values are byte offsets, not instruction ids.
    (dotimes (index (length constants))
      (when (hash-table-p (aref constants index))
        (let ((table (aref constants index)))
          (maphash (lambda (key value) (puthash key (gethash value offsets) table)) table))))
    (make-byte-code 0 (apply #'unibyte-string
                            (apply #'append (nreverse chunks)))
                    (vconcat constants [u10-gc])
                    (+ 1 (alist-get 'declared_stack_depth fixture)))))
(defun u10-constant-cohort (first)
  "Eight actual compact constant slots in one straight-line mixed-family body."
  (make-byte-code 0
                  (apply #'unibyte-string
                         (append (number-sequence first (+ first 7))
                                 '(175 8 129 64 0 32 136 135)))
                  (vconcat (make-vector 64 42) [u10-gc]) 9))
(unless (equal emacs-version "31.1") (error "GNU 31.1 oracle required"))
(let* ((report (nelisp-bytecode-coverage-audit-run))
       (audit (plist-get report :opcodes))
       (fixtures (nelisp-bytecode-coverage-audit--valid-fixtures nelisp-bytecode-coverage-audit--root))
       rows pending metadata projections)
  (dolist (fixture fixtures)
    (let* ((opcode (alist-get 'opcode fixture))
           (status (plist-get (plist-get (aref audit opcode) :valid-fixture) :frame-status))
           (first (and (>= opcode 192) (+ 192 (* 8 (/ (- opcode 192) 8)))))
           (fn (if first (u10-constant-cohort first) (u10-mixed-function fixture)))
           (unit (if first (format "constants-%d" first) (number-to-string opcode)))
           (live (cl-some (lambda (value)
                            (and (listp value)
                                 (member (alist-get 'kind value) '("current-buffer" "marker"))))
                          (append (alist-get 'constants fixture) nil)))
           (row (append (list :opcode opcode :unit unit :fixture fixture :function fn :frame-status status)
                        (when live (list :relocation-refusal 'unreadable-live-constant))
                        (when first (list :result-index (- opcode first))))))
      ;; The GNU for Windows zip ships without libgccjit; the Linux U10 run
      ;; proves this GNU-side refusal, and the slot keeps its refusal mark.
      (when (and live (native-comp-available-p))
        ;; GNU cannot spill #<buffer ...> or #<marker ...> into an .eln.
        ;; Check the actual relocation failure, not anonymous bytecode admission.
        (let ((value (cl-find-if (lambda (v) (or (bufferp v) (markerp v)))
                                 (append (u10-materialize fixture) nil)))
              refused)
          (condition-case condition
              (native-compile (list 'lambda nil (list 'quote value))
                              (concat (getenv "U10_FIXTURE") ".eln"))
            (native-compiler-error
             (setq refused (string-match-p "Invalid read syntax.*#<" (error-message-string condition)))))
          (u10-assert refused "GNU unreadable relocation refused")))
      (unless (eq status 'complete)
        (u10-assert (memq opcode '(48 49 50)) "unexpected pending fixture")
        (push opcode pending))
      (let ((expected (u10-observe row nil t)))
        (u10-assert (equal (car expected)
                           (pcase (alist-get 'result_kind fixture)
                             ("current-buffer" '(buffer t))
                             ("marker" '(marker t 1 t))
                             ("function" '(function t))
                             (_ (read (alist-get 'expected fixture)))))
                    (format "pinned GNU fixture %d" opcode))
        (u10-assert (equal expected (u10-observe row fn nil))
                    (format "mixed GNU fixture %d" opcode))
        (setq row (plist-put row :gnu expected)))
      ;; Live hash constants are reconstructed on each invocation.
      (dotimes (index (length (aref fn 2)))
        (when (hash-table-p (aref (aref fn 2) index)) (aset (aref fn 2) index nil)))
      (push row rows)
      (push `((opcode . ,opcode) (unit . ,unit) (status . ,(symbol-name status))
              (relocation_refusal . ,(if live t :json-false))) metadata)))
  (let ((protected (byte-compile #'u10-protected)) observations)
    (dolist (mode '(error quit))
      (dolist (debug '(nil t))
        (let ((expected (u10-protected-observe protected mode debug)))
          (u10-assert (equal expected
                             (u10-protected-observe
                              (u10-protected-cache-function protected) mode debug))
                      "GNU named cleanup preserves exceptional ordering")
          (push (list mode debug expected) observations))))
    (setq rows (nreverse rows) observations (nreverse observations))
    (when (getenv "U10_PROJECTION_DIR")
      (setq projections (u10-projection-write (getenv "U10_PROJECTION_DIR") rows protected observations)))
    (with-temp-file (getenv "U10_FIXTURE")
      (insert ";;; Generated GNU 31.1 inputs and oracle -*- lexical-binding: t; -*-\n")
      (let ((print-length nil) (print-level nil) (print-circle nil) (print-escape-newlines t))
        (prin1 (list 'setq 'u10-fixtures (list 'quote rows)) (current-buffer))
        (insert "\n")
        (prin1 (list 'setq 'u10-protected-function (list 'quote protected)
                     'u10-protected-oracle (list 'quote observations)) (current-buffer)))))
  (with-temp-file (getenv "U10_METADATA")
    (insert (json-encode `((fixtures . ,(vconcat (nreverse metadata)))
                          (pending . ,(vconcat (nreverse pending)))
                          (valid . 230) (excluded . 26)
                          (projections . ,projections)
                          (audit . ,(nelisp-bytecode-coverage-audit--json-object report)))))))
