;;; native-buffer-u4c-fixtures.el --- GNU buffer opcode oracles -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(defconst native-buffer-u4c-family
  '((119 skip-chars-forward 2) (120 skip-chars-backward 2) (121 forward-line 1)
    (122 char-syntax 1) (123 buffer-substring 2) (124 delete-region 2)
    (125 narrow-to-region 2) (126 widen 0) (127 end-of-line 1)))
(defun native-buffer-u4c-function (row)
  (let ((n (nth 2 row)))
    (make-byte-code (+ n (* n 256)) (unibyte-string (car row) 135) [] (max 1 n))))
(defun native-buffer-u4c-cases (opcode)
  (pcase opcode
    ((or 119 120) '(("a-zé中" nil) ("^\\n" nil) ("" nil) ("a-é" 4)
                    ("é中" marker) ("a-z" -99) ("^x" 99) ("a" unset-marker)
                    ("a" bad) ("a" 2.5) (bad nil) (nil nil)))
    (121 '((nil) (0) (1) (-1) (2) (-2) (99) (-99) (bad) (2.5)))
    (122 '((97) (32) (10) (233) (20013) (40) (nil) (bad) (-1) (4194304) (2.5)))
    ((or 123 124 125) '((2 5) (5 2) (2 2) (1 9) (0 3) (2 99) (-1 -2)
                       (marker 5) (2 marker) (unset-marker 3) (2 unset-marker)
                       (bad 3) (2 bad) (nil 3) (2 nil) (2.5 3)))
    (126 '(nil))
    (127 '((nil) (0) (1) (-1) (2) (-2) (99) (-99) (bad) (2.5)))))
(defconst native-buffer-u4c-settings '((3 nil) (2 t) (8 t)))
(defun native-buffer-u4c-normalize (value buffer left)
  "Retain exact condition/data while removing per-invocation buffer identity."
  (cond ((eq value buffer) 'current-buffer)
        ((markerp value) (list 'marker (eq value left) (marker-position value)))
        ((consp value) (cons (native-buffer-u4c-normalize (car value) buffer left)
                            (native-buffer-u4c-normalize (cdr value) buffer left)))
        (t value)))
(defun native-buffer-u4c-observe (function arguments position narrow)
  "Observe character-indexed text, bounds, point and marker effects."
  (with-temp-buffer
    (insert "aé中\n\tbé\nz")
    (set-syntax-table (standard-syntax-table))
    (when narrow (narrow-to-region 2 8))
    (goto-char position)
    (let* ((left (copy-marker (point))) (right (copy-marker (point) t))
           (args (mapcar (lambda (value)
                           (cond ((eq value 'marker) left)
                                 ((eq value 'unset-marker) (make-marker))
                                 (t value))) arguments))
           (result (condition-case err (list 'return (apply function args))
                     (error (list 'signal err))))
           (bounds (list (point) (point-min) (point-max)
                         (marker-position left) (marker-position right))))
      (setq result (native-buffer-u4c-normalize result (current-buffer) left))
      (widen)
      (list result (buffer-string) bounds))))
(defun native-buffer-u4c-error-function (opcode)
  "Insert first, invoke OPCODE with two args, and stop before a later insertion."
  (make-byte-code 514 (unibyte-string 192 99 136 1 1 opcode 136 193 99 136 194 135)
                  ["先" "forbidden" finished] 4))
(defun native-buffer-u4c-oracle ()
  "Write one GNU 31.1 interpreter oracle for the native smoke driver."
  (let (rows)
    (dolist (row native-buffer-u4c-family)
      (let ((fn (native-buffer-u4c-function row)))
        (dolist (setting native-buffer-u4c-settings)
          (dolist (args (native-buffer-u4c-cases (car row)))
            (push (list (car row) setting args
                        (native-buffer-u4c-observe fn args (car setting) (cadr setting))) rows)))))
    (dolist (opcode '(123 124 125))
      (dolist (args '((0 99) (bad 3)))
        (push (list opcode 'error args
                    (native-buffer-u4c-observe (native-buffer-u4c-error-function opcode) args 3 nil)) rows)))
    (with-temp-file (getenv "U4C_ORACLE")
      (let ((print-length nil) (print-level nil)) (prin1 (nreverse rows) (current-buffer))))))
(provide 'native-buffer-u4c-fixtures)
