;;; native-switch-u6-fixtures.el --- GNU switch oracle corpus -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(defvar u6-effects nil)
(defvar u6-gc nil)
(defvar u6-custom-mode nil)
(defvar u6-left 0)
(defun u6-custom-equal (a b)
  (when (eq u6-custom-mode 'signal) (signal 'error '("u6 custom equality")))
  (when (eq u6-custom-mode 'throw) (throw 'u6-custom 'custom-exit))
  (push (list a b) u6-effects)
  (when u6-gc (garbage-collect))
  (equal (downcase a) (downcase b)))
(defun u6-custom-hash (value) (length (downcase value)))
(defun u6-step ()
  (push u6-left u6-effects)
  (when (> u6-left 0) (setq u6-left (1- u6-left)) 'again))
(defun native-switch-u6-fixture (name)
  "Return (FUNCTION TABLE KEYS) with genuine GNU switch bytecode."
  (define-hash-table-test 'u6-case-fold #'u6-custom-equal #'u6-custom-hash)
  (let* ((test (cond ((eq name 'eql) 'eql) ((eq name 'equal) 'equal)
                     ((eq name 'custom) 'u6-case-fold) (t 'eq)))
         (table (make-hash-table :test test))
         (keys (cond ((eq name 'custom) '("ONE" "two" "absent"))
                     ((eq name 'equal) (list (copy-sequence "one") (copy-sequence "two") "absent"))
                     ((eq name 'eql) '(1.5 2.5 3.5)) (t '(one two absent))))
         (fn (if (eq name 'dynamic)
                 (make-byte-code 514 (unibyte-string 183 192 135 193 135 194 135)
                                 [miss first second] 2)
               (if (eq name 'backedge)
                   (make-byte-code 0 (unibyte-string 192 32 193 183 194 135)
                                   (vector 'u6-step table 'done) 2)
                 (make-byte-code 257 (unibyte-string 192 183 193 135 194 135 195 135)
                                 (vector table 'miss 'first 'second) 2)))))
    (if (eq name 'backedge)
        (puthash 'again 0 table)
      ;; Make the table test observable: equality must work across identity.
      (let ((stored (mapcar (lambda (key)
                             (cond ((eq name 'eql) (+ key 0.0))
                                   ((eq name 'equal) (copy-sequence key))
                                   ((eq name 'custom) (downcase key))
                                   (t key))) (list (car keys) (cadr keys)))))
        (puthash (car stored) (if (eq name 'dynamic) 3 4) table)
        (puthash (cadr stored) (if (eq name 'dynamic) 5 6) table)))
    (list fn table keys)))
(provide 'native-switch-u6-fixtures)
