;;; native-handlers-u8-fixtures.el --- Shared GNU/VM/native oracle -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(defvar u8b-effects nil)
(defvar u8b-mode nil)
(defvar u8b-object-tag (vector 'u8b-object))
(defvar u8b-inner nil)
(defvar u8b-native-catch nil)
(defvar u8b-native-condition nil)
(defvar u8b-use-native-inner nil)
(define-error 'u8b-child "U8 child" 'arith-error)
(defun u8b-callback ()
  (push 'callback u8b-effects)
  (garbage-collect)
  (cond ((eq u8b-mode 'throw) (throw 'u8b-tag 'caught))
        ((eq u8b-mode 'inherited) (signal 'u8b-child '(payload)))
        ((eq u8b-mode 'quit) (signal 'quit '(payload)))
        ((eq u8b-mode 'reenter) (funcall u8b-inner))
        (t 'returned)))
(defun u8b-object-callback ()
  (push 'callback u8b-effects)
  (garbage-collect)
  (throw u8b-object-tag 'object-caught))
(defun u8b-loop-step (n)
  (push n u8b-effects)
  (garbage-collect)
  (throw 'u8b-tag n))
(defun u8b-fixture-catch () (catch 'u8b-tag (u8b-callback)))
(defun u8b-fixture-condition ()
  (condition-case e (u8b-callback)
    (arith-error (car e)) (quit (car e))))
(defun u8b-fixture-nested ()
  (catch 'u8b-tag (condition-case e (u8b-callback) (error (car e)))))
(defun u8b-fixture-nil ()
  (condition-case e (catch nil (throw nil 'value)) (no-catch e)))
(defun u8b-fixture-missing ()
  (condition-case e (throw 'missing 'value) (no-catch e)))
(defun u8b-cleanup ()
  (push 'cleanup u8b-effects)
  (garbage-collect)
  (throw 'outer 'replacement))
(defun u8b-fixture-cleanup ()
  (catch 'outer
    (catch 'inner
      (unwind-protect (throw 'inner 'discarded)
        (push 'cleanup u8b-effects)
        (garbage-collect)
        (throw 'outer 'replacement)))))
(defun u8b-fixture-loop (n)
  (while (> n 0)
    (catch 'u8b-tag (setq n (1- n)) (u8b-loop-step n)))
  n)
(defun u8b-fixture-outer () (catch 'u8b-tag (funcall u8b-inner)))
(defun u8b-function (name)
  (cond
   ((eq name 'object)
    ;; The thrown vector is the exact live constant, across cache load and GC.
    (make-byte-code 0 (unibyte-string 192 50 8 0 193 32 48 135 135)
                    (vector u8b-object-tag 'u8b-object-callback) 1))
   ((eq name 'cleanup)
    ;; GNU accepts an eval-forms cleanup as well as a compiled thunk. This
    ;; keeps the public cache recipe data-only while exercising opcode 142.
    (make-byte-code 0 (unibyte-string 192 50 17 0 193 50 16 0 194 142 195 193 196 34 41 48 48 135)
                    [outer inner ((u8b-cleanup)) throw discarded] 3))
   ((eq name 'stackset)
    (make-byte-code 0 (unibyte-string 192 193 50 13 0 194 178 1 195 32 136 48 135 66 135)
                    [old u8b-tag changed u8b-callback] 2))
   (t (symbol-function (intern (concat "u8b-fixture-" (symbol-name name)))))))
(defun u8b-observe (function name mode)
  "Observe exact exit data and ordered effects on all three substrates."
  (let* ((u8b-effects nil)
         (outer (eq name 'outer))
         (condition-inner (memq mode '(native-condition interpreted-condition native-quit interpreted-quit native-cross interpreted-cross)))
         (native-inner (memq mode '(native-catch native-condition native-quit native-cross)))
         (u8b-mode (if outer
                       (cond ((memq mode '(native-condition interpreted-condition)) 'inherited)
                             ((memq mode '(native-quit interpreted-quit)) 'quit)
                             (t 'throw)) mode))
         (u8b-inner
          (if outer
              (if native-inner
                  (if u8b-use-native-inner
                      (if condition-inner u8b-native-condition u8b-native-catch)
                    (symbol-function (if condition-inner 'u8b-fixture-condition 'u8b-fixture-catch)))
                (if condition-inner
                    (lambda () (condition-case e (u8b-callback)
                                 (arith-error (car e)) (quit (car e))))
                  (lambda () (catch 'u8b-tag (u8b-callback)))))
            u8b-inner)))
    (list (if (eq name 'loop) (funcall function 3) (funcall function))
          (reverse u8b-effects))))
(defun u8b-cases (name)
  (cond ((eq name 'outer) '(native-catch interpreted-catch native-condition interpreted-condition native-quit interpreted-quit native-cross interpreted-cross))
        ((eq name 'condition) '(nil inherited quit))
        ((memq name '(catch nested stackset)) '(nil throw))
        (t '(nil))))
(defun u8b-oracle (names)
  "Print deterministic GNU reference records, also emitted by the reader."
  (dolist (name names)
    (dolist (mode (u8b-cases name))
      (princ (format "U8B-OBSERVE %S %S %S\n" name mode
                     (u8b-observe (u8b-function name) name mode)))))
  (princ (format "U8B-VM-COMPLETE fixtures=%d\n" (length names))))
(provide 'native-handlers-u8-fixtures)
