;;; native-frame-u7a-fixtures.el --- Dynamic frame parity corpus -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(defvar u7a-special 'outside)
(defvar u7a-mode nil)
(defvar u7a-effects nil)
(defvar u7a-inner nil)
(defvar u7a-other-buffer nil)
(defun u7a-callback ()
  (push (symbol-value 'u7a-special) u7a-effects)
  (garbage-collect)
  (when (eq u7a-mode 'switch-read)
    (with-current-buffer u7a-other-buffer
      (push (symbol-value 'u7a-special) u7a-effects)
      (set 'u7a-special 'other-changed)
      (push (symbol-value 'u7a-special) u7a-effects)))
  (cond ((eq u7a-mode 'throw) (throw 'u7a-exit (symbol-value 'u7a-special)))
        ((eq u7a-mode 'signal) (signal 'error (list "u7a" (symbol-value 'u7a-special))))
        ((eq u7a-mode 'reenter)
         (let ((u7a-mode nil)) (funcall u7a-inner 'inner))
         (push (symbol-value 'u7a-special) u7a-effects)))
  (symbol-value 'u7a-special))
(defun native-frame-u7a-function (name &optional symbol)
  "Use the same GNU bytecode body for the interpreter and both native backends."
  (cond
   ((eq name 'constant)
    (make-byte-code 257 (unibyte-string 24 193 32 41 135) [t u7a-callback] 1))
   ((eq name 'alias)
    (make-byte-code 257 (unibyte-string 24 193 32 41 135) [u7a-alias u7a-alias-callback] 1))
   ((eq name 'nested) (make-byte-code 514 (unibyte-string 24 24 8 41 8 41 66 135)
                                    (vector (or symbol 'u7a-special)) 2))
   ((eq name 'implicit) (make-byte-code 257 (unibyte-string 24 8 135)
                                      (vector (or symbol 'u7a-special)) 1))
   ((eq name 'set) (make-byte-code 257 (unibyte-string 24 193 16 8 41 135)
                                 (vector (or symbol 'u7a-special) 'changed) 1))
   ((eq name 'zero) (make-byte-code 0 (unibyte-string 40 192 135) [zero] 1))
   ((integerp name)
    (make-byte-code 0 (apply #'unibyte-string
                            (append (apply #'append (make-list name '(193 24)))
                                    (list (+ 40 name) 194 135)))
                    (vector (or symbol 'u7a-special) 'inside 'result) 1))
   (t (make-byte-code 257 (unibyte-string 24 193 32 41 135)
                      (vector (or symbol 'u7a-special) 'u7a-callback) 1))))
(defun native-frame-u7a-observe (function args)
  "Observe result, exact signal/throw, effects and the binding after exit."
  (setq u7a-effects nil)
  (let ((result (condition-case err
                    (catch 'u7a-exit (list 'returned (apply function args)))
                  (error (list 'signal err)))))
    (list result (reverse u7a-effects)
          (if (boundp 'u7a-special) (symbol-value 'u7a-special) 'void))))
(provide 'native-frame-u7a-fixtures)

(defvar u7a-target 'outside)
(defun u7a-alias-callback ()
  (garbage-collect)
  (cons (symbol-value 'u7a-alias) (symbol-value 'u7a-target)))
