;;; native-prims-u2b-fixtures.el --- Exact U2b fixtures -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(defconst native-prims-u2b-family
  '((147 set-marker 3) (148 match-beginning 1) (149 match-end 1)
    (150 upcase 1) (151 downcase 1) (152 string-equal 2) (153 string-lessp 2)
    (154 equal 2) (155 nthcdr 2) (156 elt 2) (157 member 2) (158 assq 2)
    (159 nreverse 1) (160 setcar 2) (161 setcdr 2)))
(defun native-prims-u2b-function (row)
  "Execute the precise opcode without public calls or compiler optimization."
  (let ((argc (nth 2 row)))
    (make-byte-code (+ argc (lsh argc 8)) (unibyte-string (car row) 135) [] argc)))
(defun native-prims-u2b-reset ()
  (if (fboundp 'set-match-data)
      (set-match-data '(1 4 2 3))
    (setq nlre--last-caps (vector (cons 1 4) (cons 2 3)))))
(defun native-prims-u2b-cases (opcode)
  "Return fresh normal, improper, mutation and wrong-type operands."
  (pcase opcode
    (147 (list (list (make-marker) 1 nil) (list (make-marker) nil nil)
               (list (make-marker) 999999 nil) (list 7 1 nil)
               (list (make-marker) 'bad nil) (list (make-marker) 1 'bad)
               (list (make-marker) (cons 'bad 'tail) nil)))
    ((or 148 149) (list (list 0) (list 1) (list 2) (list -1)
                         (list 'bad) (list (cons 'bad 'tail))))
    ((or 150 151) (list (list "aBc12") (list ?a) (list ?Z) (list "")
                         (list nil) (list 'bad) (list (cons 'bad 'tail))))
    (152 (list (list "ab" "ab") (list 'ab "ab") (list "ab" "ac")
               (list nil "nil") (list 7 "ab") (list "ab" 7)
               (list (cons 'a 'tail) "ab")))
    (153 (list (list "ab" "ac") (list 'ab "ac") (list "ab" "ab")
               (list "b" "a") (list nil "z") (list 7 "ab")
               (list "ab" (cons 'a 'tail))))
    (154 (list (list (list 'a 'b) (list 'a 'b))
               (list (cons 'a 'tail) (cons 'a 'tail))
               (list (cons 'a 'tail) (cons 'a 'other))
               (list [1 2] [1 2]) (list "ab" "ab") (list 7 nil)))
    (155 (list (list 1 (list 'a 'b 'c)) (list 0 (cons 'a 'tail))
               (list 1 (cons 'a 'tail)) (list 2 (cons 'a 'tail))
               (list -1 (cons 'a 'tail)) (list 0 nil)
               (list 'bad '(a)) (list 1 7)))
    (156 (list (list (list 'a 'b) 1) (list [a b] 0) (list "ab" 1)
               (list (cons 'a 'tail) 0) (list (cons 'a 'tail) 2)
               (list nil 0) (list [a] 5) (list [a] 'bad) (list 7 0)))
    (157 (list (list '(b) (list '(a) '(b))) (list 'a (cons 'a 'tail))
               (list 'z (cons 'a 'tail)) (list nil nil) (list 'x 7)))
    (158 (list (list 'b (list (cons 'a 1) (cons 'b 2)))
               (list 'a (cons (cons 'a 1) 'tail))
               (list 'z (cons (cons 'a 1) 'tail))
               (list 'z (list 7 (cons 'z 3))) (list nil nil) (list 'x 7)))
    (159 (list (list (list 'a 'b 'c)) (list (cons 'a 'tail))
               (list (vector 'a 'b 'c)) (list (copy-sequence "abc"))
               (list "αβ") (list "éø") (list "aα界")
               (list (unibyte-string 200 201))
               (list (bool-vector t nil t nil)) (list nil) (list 7)))
    (160 (list (list (cons 'a 'b) 'changed) (list (list 'a 'b) nil)
               (list nil 1) (list 7 1)))
    (161 (list (list (cons 'a 'b) 'changed) (list (list 'a 'b) (list 'c))
               (list nil 1) (list 7 1)))))
(defun native-prims-u2b-observe (function args)
  "Observe exact conditions, operand mutations and result identity."
  (let* ((answer (condition-case err (list 'value (apply function args))
                   (error (cons 'signal err))))
         (result (cadr answer))
         (identity (when (eq (car answer) 'value)
                     (list (eq result (car args)) (eq result (cadr args))
                           (and (consp (cadr args)) (eq result (cdr (cadr args))))))))
    ;; Markers are independent per case; normalize their observable state.
    (when (= (length args) 3)
      (when (markerp (car args))
        (setq args (cons (list 'marker (marker-position (car args))
                               (and (marker-buffer (car args)) t)) (cdr args))))
      (when (and (eq (car answer) 'value) (markerp result))
        (setq answer (list 'value (car args)))))
    (list answer args identity)))
(defun native-prims-u2b-observe-cycle (function cycle)
  "Bounded cycle observations avoid recursively printing cyclic error data."
  (condition-case err
      (list 'value (eq (funcall function cycle) cycle))
    (error (list 'signal (car err) (eq (cadr err) cycle)
                 (eq (cdr cycle) cycle)))))
(provide 'native-prims-u2b-fixtures)
