;;; native-legacy-u9-fixtures.el --- GNU 31.1 wrapper oracles -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(defvar u9-mode nil)
(defvar u9-events nil)
(defvar u9-original nil)
(defvar u9-other nil)
(defvar u9-special 'outside)
(defvar u9-condition 'outside)
(defun u9-event (event) (setq u9-events (append u9-events (list event))))
(defun u9-body ()
  (u9-event (list 'body u9-special))
  (garbage-collect)
  (set-buffer u9-other)
  (cond ((eq u9-mode 'error) (error "body"))
        ((eq u9-mode 'throw) (throw 'outer 'body))
        ((eq u9-mode 'inner) (throw 'inner 'caught))
        (t '(result boxed))))
(defun u9-temp-body ()
  (u9-event (list 'body (eq standard-output (get-buffer " *u9-output*"))
                  (eq (current-buffer) u9-original)))
  (princ "payload" standard-output)
  (garbage-collect)
  (cond ((eq u9-mode 'error) (error "body"))
        ((eq u9-mode 'throw) (throw 'outer 'body))
        (t '(result boxed))))
(defun native-legacy-u9-function (opcode)
  (let ((body '(let ((u9-special 'inside)) (u9-body))))
    (pcase opcode
      (139 (make-byte-code 0 (unibyte-string 192 139 135) (vector (list body)) 4))
      (141 (make-byte-code 0 (unibyte-string 192 193 141 135) (vector 'inner body) 4))
      (143 (make-byte-code 0 (unibyte-string 192 193 194 143 135)
                          (vector 'u9-condition body
                                  '((error (u9-event (list 'handler (car u9-condition) u9-special))
                                           '(handled boxed)))) 4))
      (144 (make-byte-code 0 (unibyte-string 192 144 136 193 32 41 135)
                          [" *u9-output*" u9-temp-body] 4))
      (145 (make-byte-code 0 (unibyte-string 192 144 193 32 145 135)
                          [" *u9-output*" u9-temp-body] 4)))))
(defun native-legacy-u9-observe (function opcode mode)
  (let* ((u9-mode mode) (u9-events nil)
         (u9-original (get-buffer-create " *u9-original*"))
         (u9-other (get-buffer-create " *u9-other*"))
         (output (get-buffer-create " *u9-output*"))
         (standard-output t) (u9-special 'outside) (u9-condition 'outside)
         (temp-buffer-setup-hook
          (list (lambda ()
                  (u9-event (list 'setup (eq (current-buffer) output)
                                  (eq standard-output t)))
                  (when (eq u9-mode 'setup-error) (error "setup")))))
         (temp-buffer-show-hook (list (lambda () (u9-event 'unexpected-show-hook))))
         (temp-buffer-show-function
          (unless (eq mode 'batch)
            (lambda (buffer)
              (u9-event (list 'show (eq buffer output) (eq standard-output output)
                              (eq (current-buffer) u9-original)))
              (when (eq u9-mode 'show-error) (error "show"))
              (when (eq u9-mode 'show-throw) (throw 'outer 'show)))))
         result)
    (set-buffer output) (widen) (erase-buffer) (insert "stale")
    (set-buffer u9-original) (widen) (erase-buffer) (insert "abcdef") (goto-char 2)
    (setq result (catch 'outer
                   (condition-case condition (funcall function)
                     (error (list 'signal condition)))))
    (list result u9-events (cond ((eq (current-buffer) u9-original) 'original)
                                ((eq (current-buffer) u9-other) 'other) (t 'output))
          (eq standard-output t) u9-special u9-condition
          (when (memq opcode '(144 145))
            (with-current-buffer output (list (buffer-string) (point)))))))
(defun native-legacy-u9-modes (opcode)
  (append '(nil error throw) (when (= opcode 141) '(inner))
          (when (memq opcode '(144 145)) '(setup-error batch))
          (when (= opcode 145) '(show-error show-throw))))
(defun native-legacy-u9-oracle ()
  (unless (equal emacs-version "31.1") (error "GNU 31.1 required"))
  (let ((rows
         (mapcar (lambda (opcode)
                   (cons opcode (mapcar (lambda (mode)
                                          (cons mode (native-legacy-u9-observe
                                                      (native-legacy-u9-function opcode) opcode mode)))
                                        (native-legacy-u9-modes opcode))))
                 '(139 141 143 144 145))))
    (with-temp-file (getenv "U9_ORACLE") (prin1 rows (current-buffer)))))
