;;; native-cleanup-u7b-fixtures.el --- Ordered cleanup parity -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(defvar u7b-special 'outside)
(defvar u7b-mode nil)
(defvar u7b-effects nil)
(defvar u7b-original nil)
(defvar u7b-other nil)
(defvar u7b-kind nil)
(defvar u7b-object nil)
(defvar u7b-inner nil)
(defun u7b-clean-one ()
  (push (list 'one u7b-special) u7b-effects)
  (garbage-collect)
  (cond ((eq u7b-mode 'last-error) (error "last cleanup"))
        ((eq u7b-mode 'last-throw) (throw 'u7b-exit 'last))))
(defun u7b-clean-two ()
  (push (list 'two u7b-special) u7b-effects)
  (garbage-collect)
  (cond ((memq u7b-mode '(cleanup-error last-error)) (error "cleanup"))
        ((memq u7b-mode '(cleanup-throw last-throw)) (throw 'u7b-exit 'cleanup))))
(defun u7b-body ()
  (push (list 'body u7b-special) u7b-effects)
  (cond
   ((memq u7b-kind '(97 114))
    (set-buffer u7b-other)
    (when (eq u7b-mode 'kill) (kill-buffer u7b-original)))
   ((eq u7b-kind 138)
    (goto-char 1) (insert "ZZ") (goto-char 2) (set-buffer u7b-other))
   ((eq u7b-kind 140)
    (widen) (goto-char 1) (insert "ZZ") (narrow-to-region 1 2)
    (set-buffer u7b-other)))
  (garbage-collect)
  (when (eq u7b-mode 'reenter)
    (let ((u7b-mode nil)) (funcall u7b-inner))
    (push (list 'after-inner u7b-special) u7b-effects))
  (cond ((memq u7b-mode '(body-error cleanup-throw last-throw)) (error "body"))
        ((memq u7b-mode '(body-throw cleanup-error last-error)) (throw 'u7b-exit 'body)))
  u7b-object)
(defun native-cleanup-u7b-function (kind)
  (cond
   ((eq kind 'ordered)
    ;; cleanup-one < binding < cleanup-two: UNBIND counts all three.
    (make-byte-code 0 (unibyte-string 192 142 193 28 194 142 195 32 43 135)
                    [u7b-clean-one inside u7b-clean-two u7b-body u7b-special] 1))
   ((eq kind 'forms)
    (make-byte-code 0 (unibyte-string 192 142 193 32 41 135)
                    [((u7b-clean-one)) u7b-body] 1))
   ((eq kind 'implicit)
    (make-byte-code 0 (unibyte-string 192 142 193 28 194 142 195 32 135)
                    [u7b-clean-one inside u7b-clean-two u7b-body u7b-special] 1))
   (t (make-byte-code 0 (unibyte-string kind 192 32 41 135) [u7b-body] 1))))
(defun native-cleanup-u7b-observe (function kind mode)
  "Use fresh buffers on each side; report state and exact exit data."
  (let* ((u7b-kind kind) (u7b-mode mode) (u7b-effects nil)
         (u7b-original (generate-new-buffer " u7b-original"))
         (u7b-other (generate-new-buffer " u7b-other"))
         (u7b-object (cons 'retained (vector "α" 42)))
         (caller (current-buffer)) result identity active state)
    (unwind-protect
        (progn
          (set-buffer u7b-original) (insert "aαbcdefghi") (goto-char 4)
          (when (eq kind 140) (narrow-to-region 3 7))
          (setq result (condition-case err
                           (catch 'u7b-exit
                             (let ((value (funcall function)))
                               (setq identity (eq value u7b-object))
                               (list 'returned value)))
                         (error (list 'signal err))))
          (setq active (cond ((eq (current-buffer) u7b-original) 'original)
                             ((eq (current-buffer) u7b-other) 'other) (t 'unexpected)))
          (setq state (when (buffer-live-p u7b-original)
                        (with-current-buffer u7b-original
                          (list (point) (point-min) (point-max)))))
          (list result (reverse u7b-effects) u7b-special active state identity))
      (when (buffer-live-p caller) (set-buffer caller))
      (when (buffer-live-p u7b-original) (kill-buffer u7b-original))
      (kill-buffer u7b-other))))
(provide 'native-cleanup-u7b-fixtures)
