;;; native-prims-u2a-fixtures.el --- Exact U2a bytecode fixtures -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(defconst native-prims-u2a-family
  '((56 nth 2) (62 memq 2) (71 length 1) (72 aref 2) (73 aset 3)
    (74 symbol-value 1) (75 symbol-function 1) (76 set 2) (77 fset 2)
    (78 get 2) (79 substring 3)))
(defun native-prims-u2a-function (row)
  "Use the precise opcode, without byte-compiler optimization or public calls."
  (let ((argc (nth 2 row)))
    (make-byte-code (+ argc (lsh argc 8)) (unibyte-string (car row) 135) [] argc)))
(defun native-prims-u2a-cases (opcode)
  "Return fresh, bounded ordinary, nil, dotted, mutation and error operands."
  (pcase opcode
    (56 (list (list 1 (list 'a 'b)) (list 0 (cons 'a 'tail))
              (list 2 (cons 'a 'tail)) (list -1 (cons 'a 'tail))
              (list 127 (cons 'a 'tail)) (list 128 (cons 'a 'tail)) (list 0 nil) (list 'bad '(a))))
    (62 (list (list 'b (list 'a 'b 'c)) (list 'a (cons 'a 'tail))
              (list 'z (cons 'a 'tail)) (list nil nil) (list 'x 7)))
    (71 (list (list (list 'a 'b)) (list (cons 'a 'tail)) (list nil)
              (list (vector 1 2)) (list "text") (list 7)))
    (72 (list (list (vector 'a 'b) 1) (list "ab" 0) (list [] 0)
              (list (vector 1) -1) (list nil 0) (list (vector 1) 'bad)))
    (73 (list (list (vector 'a 'b) 1 'changed) (list (copy-sequence "ab") 0 99)
              (list [] 0 1) (list (vector 1) -1 2) (list nil 0 1)
              (list (vector 1) 'bad 2)))
    (74 (list (list 'u2a-value) (list nil) (list 'u2a-void) (list 7)))
    (75 (list (list 'u2a-function) (list nil) (list t) (list 'u2a-void) (list 7)))
    (76 (list (list 'u2a-value 'changed) (list 'u2a-void 9)
              (list nil 9) (list t 9) (list :constant 9) (list :constant :constant) (list 7 9)))
    (77 (list (list 'u2a-function '(lambda (x) 'changed)) (list 'u2a-void nil)
              (list 'u2a-void '(lambda (x) 'new-cell)) (list nil nil) (list 7 nil)))
    (78 (list (list 'u2a-value 'key) (list 'u2a-value 'absent)
              (list nil 'key) (list 7 'key)))
    (79 (list (list "abcd" 1 3) (list (vector 1 2 3) 1 nil)
              (list "ab" -1 nil) (list "ab" 3 nil) (list nil 0 nil)
              (list "ab" 'bad nil)))))
(defun native-prims-u2a-oracle (opcode args)
  "Independent GNU Emacs expectations for dispatch and constant boundaries."
  (cond ((and (= opcode 75) (equal args '(7)))
         '(signal wrong-type-argument symbolp 7))
        ((and (= opcode 75) (or (equal args '(nil)) (equal args '(t))))
         '(value nil))
        ((and (= opcode 76) (equal args '(:constant :constant)))
         '(value :constant))
        ((and (= opcode 76) (memq (car args) '(nil t :constant)))
         (list 'signal 'setting-constant (car args)))))
(defun native-prims-u2a-reset ()
  (set 'u2a-value 'original)
  (fset 'u2a-function '(lambda (x) x))
  (makunbound 'u2a-void)
  (fmakunbound 'u2a-void)
  (setplist 'u2a-value '(key present)))
(defun native-prims-u2a-observe (function args)
  "Record precise condition/data and observable stores as well as the result."
  (let ((answer (condition-case err (list 'value (apply function args))
                  (error (cons 'signal err)))))
    (list answer args (symbol-value 'u2a-value) (symbol-function 'u2a-function)
          (get 'u2a-value 'key)
          (if (boundp 'u2a-void) (list 'bound (symbol-value 'u2a-void)) 'void)
          (if (fboundp 'u2a-void) (list 'bound (symbol-function 'u2a-void)) 'void))))
(provide 'native-prims-u2a-fixtures)
