;;; nelisp-native-template.el --- Ordinary linear rooted compiler -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'cl-lib)
(require 'nelisp-native-template-stencils)
(require 'nelisp-native-template-pin)
(require 'nelisp-bytecode-native-rooted-cfg-contract)
(defconst nelisp-native-template-proof-version "template-proof-v3")
(defconst nelisp-native-template-entry "nl_native_template_probe_v1")
(defvar nelisp-native-template--validation-count 0)
(defvar nelisp-native-template--compile-count 0)
(defvar nelisp-native-template--entry-count 0)
(defvar nelisp-native-template--fallback-count 0)
(defvar nelisp-native-template--phase-trace nil
  "Optional measurement callback receiving decode-begin/decode-end markers.")
(defvar nelisp-native-template--abi :unset)
(defvar nelisp-native-template--build-abi nil)
(defvar nelisp-native-cache--addresses)
(defvar nelisp-native-cache-mode)
(defvar nelisp-native-cache-guard-mode)
(defvar nelisp-native-cache--build-source-identity)
(defvar nelisp-native-template--source-fence nil)
(defvar nelisp-native-template--serialization-receiver nil
  "Call-local receiver of a signed manifest and its complete serialized bytes.")
(declare-function nelisp-native-cache--function "nelisp-native-cache" (function))
(declare-function nelisp-native-cache-file "nelisp-native-cache" (function))
(declare-function nelisp-native-cache-abi-hash "nelisp-native-cache" ())
(declare-function nelisp-native-cache--input-hash "nelisp-native-cache" (function))
(declare-function nelisp-native-cache--publish "nelisp-native-cache" (temporary final))
(declare-function nelisp-native-windows-temporary "nelisp-native-windows" (prefix))
(defun nelisp-native-template-recipe (function)
  "Freeze readable input, retaining live switch tables only as constant roots."
  (unless (byte-code-function-p function) (error "Template requires materialized bytecode"))
  (unless (<= 4 (length function) 6) (error "Template function metadata refused"))
  (let ((constants (copy-sequence (aref function 2))) (live nil) (targets nil))
    (dotimes (i (length constants))
      (when (hash-table-p (aref constants i))
        (unless (<= (hash-table-count (aref constants i)) 4096)
          (error "Template switch table bound refused"))
        (maphash (lambda (_key target) (push target targets)) (aref constants i))
        (push i live) (aset constants i nil)))
    (let ((recipe (list :descriptor (aref function 0) :code-base64 (base64-encode-string (aref function 1) t)
                        :constants constants :stack-depth (aref function 3)
                        :function-length (length function)
                        :metadata (and (> (length function) 4) (aref function 4))
                        :interactive (and (> (length function) 5) (aref function 5)))))
      (when live (setq recipe (append recipe (list :live-hash-constants (nreverse live)
                                                  :switch-targets targets))))
      (unless (nelisp-native-template-bounded-data-p recipe)
        (error "Template relocation refused: unreadable constant/metadata; bytecode retained"))
      recipe)))
(defconst nelisp-native-template-compiler-modules
  '("lisp/nelisp-native-template.el" "lisp/nelisp-native-template-stencils.el"
    "lisp/nelisp-bytecode-native-rooted-cfg-contract.el" "lisp/nelisp-native-cache.el"
    "lisp/nelisp-native-load.el" "lisp/nelisp-runtime-reload-abi.el"
    "lisp/nelisp-native-poll.el" "lisp/nelisp-bytecode-native-switch.el"
    "lisp/nelisp-bytecode-compiler-input-dialect.el"))
(defun nelisp-native-template-prepare-source-fence ()
  "Freeze source, ABI and dialect identities before the first template lookup."
  (nelisp-native-template-select-target)
  (require 'nelisp-native-template-source-pin)
  (unless nelisp-native-template--source-fence
    (let* ((root (file-name-directory (directory-file-name
                                      (file-name-directory (locate-library "nelisp-native-template.el" t)))))
           (files (unless nelisp-native-cache--build-source-identity
                    (mapcar (lambda (name)
                              (cons name (with-temp-buffer
                                           (set-buffer-multibyte nil)
                                           (insert-file-contents-literally (expand-file-name name root))
                                           (buffer-string)))) nelisp-native-template-compiler-modules)))
           (identity (lambda ()
                       (list (nelisp-native-template-stencil-abi)
                             nelisp-native-template-library-sha256
                             nelisp-native-template-current-compiler-source-key
                             nelisp-native-template-library-inventory
                             (and (boundp 'nelisp-bytecode-runtime-dialect-id) nelisp-bytecode-runtime-dialect-id)
                             (and (boundp 'nelisp-bytecode-runtime-opcode-inventory) nelisp-bytecode-runtime-opcode-inventory))))
           (frozen (car (read-from-string (nelisp-native-template--print (funcall identity))))))
      (when files
        (unless (equal (nelisp-native-template--hash
                        (mapcar (lambda (f) (cons (car f) (secure-hash 'sha256 (cdr f)))) files))
                       nelisp-native-template-current-compiler-source-key)
          (error "Template compiler source receipt changed; regenerate")))
      (when (boundp 'nelisp-bytecode-runtime-opcode-inventory)
        (unless (and (stringp nelisp-bytecode-runtime-opcode-inventory)
                     (equal (secure-hash 'sha256 nelisp-bytecode-runtime-opcode-inventory)
                            nelisp-native-template-library-inventory))
          (error "Template opcode inventory changed")))
      (setq nelisp-native-template--source-fence
            (lambda ()
              (unless (and (let ((current (funcall identity)))
                             (and (nelisp-native-template-bounded-data-p current)
                                  (equal frozen current)))
                           (or (null files)
                               (cl-every (lambda (file)
                                           (with-temp-buffer
                                             (set-buffer-multibyte nil)
                                             (insert-file-contents-literally (expand-file-name (car file) root))
                                             (equal (cdr file) (buffer-string)))) files)))
                (error "Template source/ABI/dialect identity changed; rebuild")) t)))))
(defun nelisp-native-template-abi-hash ()
  "Bind template sources separately from optimizers, once per process."
  (require 'nelisp-native-template-pin)
  (nelisp-native-template-select-target)
  (require 'nelisp-native-template-source-pin)
  (when (eq nelisp-native-template--abi :unset)
    (nelisp-native-template-prepare-source-fence)
    (funcall nelisp-native-template--source-fence)
    (setq nelisp-native-template--abi
          (or nelisp-native-template--build-abi
              (nelisp-native-template--hash
               (list (let ((binary (nelisp-native-load-running-binary-sha256)))
                       (unless (and (stringp binary) (= 64 (length binary)))
                         (error "Template running binary identity unavailable")) binary)
                     (nelisp-native-template-stencil-abi)
                     nelisp-native-template-library-sha256
                     nelisp-native-template-current-compiler-source-key
                     nelisp-native-template-library-inventory
                     (nelisp-native-load--raw-v2-contract-hash)
                     (nelisp-native-load--raw-v2-import-contract-hash
                      (nelisp-native-load--raw-v2-symbols)))))))
  (unless nelisp-native-cache--addresses
    (setq nelisp-native-cache--addresses (nelisp-native-load-root-v2-addresses)))
  (unless (fboundp 'nelisp--native-pin-copy-v2) (error "Template pin-copy unavailable"))
  nelisp-native-template--abi)
(defun nelisp-native-template-frame-states (rows table arity maximum)
  "Validate interned typed handler/unwind chains including every entry poll.
States contain only chain IDs; no path copies a chain. The 4096-state bound
is an admission limit, never an execution limit."
  (let ((handlers (make-hash-table :test 'equal)) (unwinds (make-hash-table :test 'equal))
        (nodes (make-hash-table :test 'eql)) (seen (make-hash-table :test 'equal))
        (next-id 0) (pending nil) (max-handlers 0) (targets nil))
    (cl-labels
        ((intern-node (key index)
           (or (gethash key index)
               (let ((id (setq next-id (1+ next-id))))
                 (puthash id key nodes) (puthash key id index) id)))
         (unwind-depth (id) (if id (nth 3 (gethash id nodes)) 0))
         (handler-depth (id) (if id (nth 6 (gethash id nodes)) 0))
         (enqueue (pc depth handler unwind)
           (let ((row (and (integerp pc) (<= 0 pc) (< pc (length table)) (aref table pc))))
             (unless row (error "Template frame target is not an instruction"))
             (when (and (aref row 7) (/= depth (aref row 7)))
               (error "Template inconsistent frame stack join pc=%d" pc))
             (unless (<= (aref row 5) depth maximum) (error "Template frame operand depth refused"))
             (aset row 7 depth)
             (let ((key (list pc depth handler unwind)))
               (unless (gethash key seen)
                 (when (>= (hash-table-count seen) 4096) (error "Template handler state admission limit"))
                 (puthash key t seen) (push key pending)))))
         (push-unwind (kind pc unwind)
           (intern-node (list kind pc unwind (1+ (unwind-depth unwind))) unwinds)))
      (enqueue 0 arity nil nil)
      (while pending
        (let* ((state (pop pending)) (pc (nth 0 state)) (depth (nth 1 state))
               (handler (nth 2 state)) (unwind (nth 3 state)) (row (aref table pc))
               (op (aref row 1)) (kind (aref row 4)) (arg (aref row 3))
               (after (+ depth (aref row 6))))
          (unless (<= 0 after maximum) (error "Template frame maximum depth refused"))
          ;; A poll can exit even at CONST/RETURN/POP-HANDLER. Selection
          ;; consumes the chosen handler, preserving its saved unwind tail.
          (let ((chain handler))
            (while chain
              (let ((node (gethash chain nodes)))
                (enqueue (nth 3 node) (1+ (nth 2 node)) (nth 5 node) (nth 4 node))
                (setq chain (nth 5 node)))))
          (cond
           ((memq op '(49 50))
            (unless (and (integerp arg) (<= 0 arg) (< arg (length table)) (aref table arg))
              (error "Template handler landing boundary refused"))
            (cl-pushnew arg targets)
            (setq handler (intern-node (list op pc after arg unwind handler
                                             (1+ (handler-depth handler))) handlers))
            (setq max-handlers (max max-handlers (handler-depth handler))))
           ((= op 48)
            (unless handler (error "Template handler pop underflow"))
            (setq handler (nth 5 (gethash handler nodes)))))
          (cond
           ((or (eq kind 'bind) (eq kind 'frame) (= op 144))
            (setq unwind (push-unwind (if (= op 144) 'bind kind) pc unwind)))
           ((or (eq kind 'unbind) (= op 145))
            (dotimes (_ (if (= op 145) 1 arg))
              (unless unwind (error "Template unbind underflow"))
              (setq unwind (nth 2 (gethash unwind nodes))))))
          (let ((chain handler))
            (while chain
              (let ((node (gethash chain nodes)))
                (when (> (unwind-depth (nth 4 node)) (unwind-depth unwind))
                  (error "Template unbind crosses active handler watermark"))
                (setq chain (nth 5 node)))))
          (cond ((= op 135) nil)
                ((= op 130) (enqueue arg depth handler unwind))
                ((memq op '(131 132 133 134))
                 (enqueue (aref row 2) (1- depth) handler unwind)
                 (enqueue arg (if (memq op '(133 134)) depth (1- depth)) handler unwind))
                (t (enqueue (aref row 2) after handler unwind)))))
      (list :states (hash-table-count seen) :max-handlers max-handlers
            :targets (sort targets #'<)))))
(defun nelisp-native-template-validate (recipe)
  "Decode and solve ordinary depth/type constraints in one bounded worklist pass.
Dense PC slots and equality edges include back edges and asymmetric branches.
Switch components use the established minimum-depth landing domain. Dynamic
Lisp types remain the gateway's responsibility. Typed unwind and handler states
include poll exits before every instruction."
  (unless (nelisp-native-template-bounded-data-p recipe) (error "Template bounded input refused"))
  (setq nelisp-native-template--validation-count (1+ nelisp-native-template--validation-count)
        nelisp-bytecode-native-rooted-cfg-contract--validation-count
        (1+ nelisp-bytecode-native-rooted-cfg-contract--validation-count))
  (when nelisp-native-template--phase-trace
    (funcall nelisp-native-template--phase-trace 'decode-begin))
  (let* ((descriptor (plist-get recipe :descriptor)) (code (if (plist-member recipe :code-base64)
                    (base64-decode-string (plist-get recipe :code-base64))
                  (plist-get recipe :code)))
         (constants (plist-get recipe :constants)) (maximum (plist-get recipe :stack-depth))
         (arity (and (integerp descriptor) (logand descriptor 127)))
         (pc 0) (rows nil) (providers nil) (maxargc 3) (switch-p nil) (frame-p nil) (handler-p nil) (frame-analysis nil))
    (unless (and arity (<= 0 descriptor) (= 0 (logand descriptor 128))
                 (= arity (ash descriptor -8)) (vectorp constants)
                 (stringp code) (not (multibyte-string-p code)) (< 0 (length code) 65536)
                 (integerp maximum) (<= arity maximum 240))
      (error "Template argument/code/depth admission refused"))
    (let* ((size (length code)) (table (make-vector size nil))
           (graph (make-vector size nil)) (offsets (make-vector size nil))
           (depths (make-vector size nil)) (switch-depth nil))
      (cl-labels
          ((read-n (n)
             (unless (<= (+ pc n) size) (error "Truncated template operand"))
             (prog1 (if (= n 1) (aref code pc) (+ (aref code pc) (* 256 (aref code (1+ pc)))))
               (setq pc (+ pc n))))
           (operand (op base)
             (let ((short (- op base))) (if (< short 6) short (read-n (if (= short 6) 1 2)))))
           (edge (from to delta)
             (unless (and (integerp to) (<= 0 to) (< to size) (aref table to))
               (error "Template non-instruction jump target %S" to))
             (push (cons to delta) (aref graph from))
             (push (cons from (- delta)) (aref graph to))))
        ;; Row: PC, opcode, next, operand, kind, min inputs, delta, depth.
        (while (< pc size)
          (let* ((start pc) (op (aref code pc)) arg kind need delta
                 (primitive (nelisp-native-funcall-v2-primitive op)))
            (setq pc (1+ pc))
            (cond
             ((or (>= op 192) (= op 129))
              (setq arg (if (= op 129) (read-n 2) (- op 192)) kind 'constant need 0 delta 1)
              (unless (< arg (length constants)) (error "Template constant index refused")))
             ((<= 1 op 7) (setq arg (operand op 0) kind 'copy need (1+ arg) delta 1))
             ((<= 8 op 23)
              (let ((set-p (>= op 16)))
                (setq arg (operand op (if set-p 16 8)) kind (if set-p 'varset 'varref)
                      need (if set-p 1 0) delta (if set-p -1 1))
                (unless (and (< arg (length constants)) (symbolp (aref constants arg)))
                  (error "Template variable operand refused"))
                (cl-pushnew (if set-p 'set 'symbol-value) providers)))
             ((<= 24 op 31)
              (setq arg (operand op 24) kind 'bind need 1 delta -1 frame-p t)
              (unless (and (< arg (length constants)) (symbolp (aref constants arg)))
                (error "Template binding operand refused")))
             ((<= 40 op 47)
              (setq arg (operand op 40) kind 'unbind need 0 delta 0 frame-p t))
             ((memq op '(48 49 50))
              (setq arg (and (/= op 48) (read-n 2)) kind 'handler
                    need (if (= op 48) 0 1) delta (- need) frame-p t handler-p t))
             ((memq op '(97 114 138 140 142))
              (setq kind 'frame need (if (= op 142) 1 0) delta (- need) frame-p t))
             ((= op 137) (setq arg 0 kind 'copy need 1 delta 1))
             ((= op 136) (setq kind 'discard need 1 delta -1))
             ((= op 135) (setq kind 'return need 1 delta 0))
             ((memq op '(178 179))
              (setq arg (read-n (if (= op 178) 1 2)) kind 'stack-set need (1+ arg) delta -1))
             ((= op 182)
              (setq arg (read-n 1) kind 'discard-n delta (- (logand arg 127))
                    need (+ (- delta) (if (/= 0 (logand arg 128)) 1 0))))
             ((<= 32 op 39)
              (setq arg (operand op 32) kind 'call need (1+ arg) delta (- arg)
                    maxargc (max maxargc arg)))
             ((memq op '(130 131 132 133 134))
              (setq arg (read-n 2) kind 'branch need (if (= op 130) 0 1)
                    delta (if (= op 130) 0 -1)))
             ((= op 183) (setq kind 'switch need 2 delta -2 switch-p t))
             ((and primitive (progn (when (memq op '(144 145)) (setq frame-p t)) t))
              (setq arg (if (eq (nth 2 primitive) 'operand) (read-n 1) (nth 2 primitive))
                    kind 'primitive need arg delta (- 1 arg) maxargc (max maxargc arg))
              (cl-pushnew (nth 1 primitive) providers))
             (t (error "Template unsupported frame/handler/opcode=%d pc=%d; bytecode retained" op start)))
            (let ((row (vector start op pc arg kind need delta nil)))
              (aset table start row) (push row rows))))
        (setq rows (nreverse rows))
        (when nelisp-native-template--phase-trace
          (funcall nelisp-native-template--phase-trace 'decode-end))
        (dolist (row rows)
          (let ((start (aref row 0)) (op (aref row 1)) (next (aref row 2)) (delta (aref row 6)))
            (cond ((= op 135) nil)
                  ((= op 130) (edge start (aref row 3) 0))
                  ((memq op '(131 132 133 134))
                   (edge start next -1) (edge start (aref row 3) (if (memq op '(133 134)) 0 -1)))
                  (t (edge start next delta)))))
        (if frame-p
            (progn
              (when switch-p (error "Template handler/switch combination refused"))
              (setq frame-analysis (nelisp-native-template-frame-states rows table arity maximum))
              (setq rows (cl-remove-if-not (lambda (row) (aref row 7)) rows)))
        ;; Each vertex is assigned once. Inverse equality edges establish safe
        ;; disconnected switch arms without copying stack states or building IR.
        (dolist (row rows)
          (let ((start (aref row 0)))
            (when (null (aref offsets start))
              (let ((pending (list start)) (component nil) (minimum 0) anchor)
                (aset offsets start 0)
                (while pending
                  (let* ((at (pop pending)) (offset (aref offsets at)) (ins (aref table at)))
                    (push at component)
                    (setq minimum (max minimum (- (aref ins 5) offset)))
                    (when (= at 0) (setq anchor (- arity offset)))
                    (dolist (e (aref graph at))
                      (let* ((to (car e)) (expected (+ offset (cdr e))) (old (aref offsets to)))
                        (if (null old) (progn (aset offsets to expected) (push to pending))
                          (unless (= old expected) (error "Template inconsistent stack join pc=%d" to)))))))
                
                (let ((base (or anchor (max minimum (or switch-depth 0)))))
                  (unless (>= base minimum) (error "Template stack underflow"))
                  (dolist (at component)
                    (let* ((depth (+ base (aref offsets at))) (ins (aref table at))
                           (after (+ depth (aref ins 6))))
                      (unless (and (<= 0 depth maximum) (<= 0 after maximum))
                        (error "Template declared maximum depth refused"))
                      (aset depths at depth) (aset ins 7 depth)
                      (when (= (aref ins 1) 183)
                        (setq switch-depth (if switch-depth (min switch-depth after) after))))))))))
)
        (dolist (index (plist-get recipe :live-hash-constants))
          (unless (and switch-p (integerp index) (<= 0 index) (< index (length constants))
                       (null (aref constants index))) (error "Template live switch constant refused")))
        (let ((landing-depths (make-vector (1+ maximum) nil)))
          (dolist (row rows)
            (when (= (aref row 1) 183) (aset landing-depths (- (aref row 7) 2) t)))
          (dolist (target (plist-get recipe :switch-targets))
            (unless (and (integerp target) (<= 0 target) (< target size) (aref table target)
                         (aref landing-depths (aref depths target)))
              (error "Template invalid switch target %S" target))))
        (let* ((constant-base (1+ maximum)) (providers (nreverse providers))
               (provider-base (+ constant-base (length constants)))
               (poll-root (+ provider-base (length providers))) (quit-base (1+ poll-root))
               (switch-root (+ quit-base 3)) (targets-base (1+ switch-root))
               (switches (cl-remove-if-not (lambda (row) (= (aref row 1) 183)) rows))
               (immediate-base (+ targets-base (length switches)))
               (immediate-count (if frame-p (+ 2 (length rows)) 0))
               (frame-state (+ immediate-base immediate-count))
               (handler-pairs (1+ frame-state))
               (pair-count (* 2 (or (plist-get frame-analysis :max-handlers) 0)))
               (staging (+ frame-state (if frame-p (+ 1 pair-count) 0)))
               (result (+ staging maxargc))
               ;; Landing owns two staging cells beyond its result/exit quartet.
               (frame-result (+ result 4))
               (count (+ result (if frame-p 10 4))) (initializers nil) (switch-targets nil))
          (unless (< count 256) (error "Template root frame limit refused"))
          (dotimes (i (length constants)) (push (list :root (+ constant-base i) :constant-index i) initializers))
          (cl-loop for p in providers for i from provider-base do
                   ;; GNU Binteractive_p observes the current public function
                   ;; cell; it is the sole dynamic provider in this inventory.
                   (push (if (eq p 'interactive-p) (list :root i :value p)
                           (list :root i :primitive p)) initializers))
          (when frame-p
            (push (list :root frame-state :frame t) initializers)
            (push (list :root immediate-base :value 1) initializers)
            (push (list :root (1+ immediate-base) :value maximum) initializers)
            (cl-loop for row in rows for root from (+ immediate-base 2) do
                     (let ((op (aref row 1)))
                       (push (list :root root :value
                                   (cond ((memq op '(49 50))
                                          (vector (if (= op 50) 2 1) (aref row 3)
                                                  (1- (aref row 7)) handler-pairs
                                                  (plist-get frame-analysis :max-handlers) 1))
                                         ((eq (aref row 4) 'unbind) (aref row 3))
                                         ((= op 144) 'standard-output) ((= op 145) 1))) initializers))))
          (push (list :root poll-root :poll t) initializers)
          (cl-loop for value in '(1 quit nil) for i from quit-base do (push (list :root i :value value) initializers))
          (when switch-p (push (list :root switch-root :switch t) initializers))
          (cl-loop for row in switches for i from targets-base do
                   (let* ((after (- (aref row 7) 2))
                          (targets (cl-loop for r in rows when (= after (aref r 7)) collect (aref r 0))))
                     (push (list :root i :value targets) initializers)
                     (push (list (aref row 0) i targets) switch-targets)))
          (list :rows rows :code-size size :arity arity :root-count count :constant-base constant-base
                :provider-roots (cl-loop for p in providers for i from provider-base collect (cons p i))
                :frame-p frame-p :handler-p handler-p :frame-state frame-state
                :frame-result frame-result :immediate-base immediate-base :frame-analysis frame-analysis
                :frame-immediates (cl-loop for row in rows for root from (+ immediate-base 2)
                                           collect (cons (aref row 0) root))
                :poll-root poll-root :quit-base quit-base :switch-root switch-root :switch-targets (nreverse switch-targets)
                :staging staging :result result :exit-root-base (1+ result) :initializers (nreverse initializers)))))))
(defun nelisp-native-template-assemble (certificate library)
  "Copy trusted fragments in PC order, then patch branches and jump tables."
  (let ((chunks nil) (position 0) (fixups nil) (relocs nil) (ranges nil)
        (labels (make-hash-table :test 'equal)) (tables nil)
        (fragments (plist-get library :fragments)))
    (cl-labels
        ((label (name) (puthash name position labels))
         (emit (family values)
           (let* ((fragment (cdr (assq family fragments)))
                  (bytes (copy-sequence (plist-get fragment :bytes))) (start position))
             (unless fragment (error "Template missing fragment %S" family))
             (setq nelisp-native-template--copy-count (1+ nelisp-native-template--copy-count))
             (dolist (hole (plist-get fragment :holes))
               (let* ((offset (plist-get hole :offset)) (name (plist-get hole :name)) (pair (assq name values)))
                 (pcase (plist-get hole :kind)
                   ('import-rel32 (push (list :section 'text :offset (+ start offset) :type 'plt32
                                             :symbol (symbol-name name) :addend -4) relocs))
                   ('rel32 (push (list (+ start offset) (if pair (cdr pair) name)) fixups))
                   (_ (unless pair (error "Template missing typed patch %s" name))
                      (nelisp-native-template-patch32 bytes offset (cdr pair))))))
             (push bytes chunks) (setq position (+ position (length bytes)))))
         (frame (action arguments result failure)
           (emit 'frame (list (cons 'state (plist-get certificate :frame-state))
                             (cons 'action action) (cons 'arguments arguments)
                             (cons 'result result) (cons 'failure failure))))
         (raw-copy (source destination)
           (unless (= source destination)
             (emit 'copy (append (list (cons 'source source) (cons 'destination destination))
                                (cl-loop for i below 4 append
                                         (list (cons (intern (format "read%d" i)) (+ (* source 32) (* i 8)))
                                               (cons (intern (format "write%d" i)) (+ (* destination 32) (* i 8)))))))))
         (copy-slot (source destination)
           (unless (= source destination)
             (if (plist-get certificate :handler-p)
                 (frame 12 source destination 'finish)
               (raw-copy source destination))))
         (frame-call (action inputs &optional entering)
           (cl-loop for source in inputs for destination from (plist-get certificate :staging)
                    do (if entering (raw-copy source destination) (copy-slot source destination)))
           (frame action (plist-get certificate :staging) (plist-get certificate :frame-result)
                  (if entering 'epilogue 'frame-failure)))
         (call (function inputs &optional poll)
           (cl-loop for source in inputs for destination from (plist-get certificate :staging)
                    do (copy-slot source destination))
           (emit (if poll 'poll 'call) (list (cons 'function function) (cons 'arguments (plist-get certificate :staging))
                            (cons 'argc (length inputs)) (cons 'result (plist-get certificate :result))
                            (cons 'epilogue (if (plist-get certificate :frame-p) 'finish 'epilogue))))))
      (emit 'prologue nil)
      (when (plist-get certificate :frame-p)
        (frame-call 0 (list (plist-get certificate :immediate-base)
                            (1+ (plist-get certificate :immediate-base))) t))
      (dolist (row (plist-get certificate :rows))
        (let* ((pc (aref row 0)) (op (aref row 1)) (kind (aref row 4))
               (arg (aref row 3)) (depth (aref row 7)) (after (+ depth (aref row 6)))
               (start position))
          (label pc)
          ;; The pre-operation bank remains rooted across ordinary poll exits.
          (call (plist-get certificate :poll-root) nil t)
          (emit 'nonnull-branch (list (cons 'source (plist-get certificate :result))
                                     (cons 'tag-offset 0) (cons 'target 'quit)))
          (pcase kind
            ('bind (frame-call 1 (list (+ (plist-get certificate :constant-base) arg) depth)))
            ('unbind (frame-call 2 (list (cdr (assq pc (plist-get certificate :frame-immediates))))))
            ('frame (frame-call (pcase op (142 4) ((or 97 114) 5) (138 6) (140 7))
                                (and (= op 142) (list depth))))
            ('handler (frame-call (if (= op 48) 9 8)
                                  (and (/= op 48)
                                       (list depth (cdr (assq pc (plist-get certificate :frame-immediates)))))))
            ('constant (copy-slot (+ (plist-get certificate :constant-base) arg) after))
            ('copy (copy-slot (- depth arg) after))
            ((or 'varref 'varset)
             (call (cdr (assq (if (eq kind 'varset) 'set 'symbol-value)
                              (plist-get certificate :provider-roots)))
                   (append (list (+ (plist-get certificate :constant-base) arg))
                           (and (eq kind 'varset) (list depth))))
             (when (eq kind 'varref) (copy-slot (plist-get certificate :result) after)))
            ('stack-set (copy-slot depth (- depth arg)))
            ('discard-n (when (/= 0 (logand arg 128)) (copy-slot depth after)))
            ((or 'primitive 'call)
             (let ((inputs (number-sequence (if (eq kind 'call) (+ (- depth arg) 1)
                                             (+ (- depth arg) 1)) depth)))
               ;; GNU Bindent_to supplies its optional MINIMUM as nil.
               ;; The existing exit triple already owns an authenticated nil.
               (when (= op 106)
                 (setq inputs (append inputs (list (+ (plist-get certificate :quit-base) 2)))))
               (when (and (eq kind 'primitive) (not (plist-get certificate :handler-p))
                          (memq op '(83 84 85 86 87 88 89 90 91 92 95)))
                 (let ((left (car inputs)) (right (or (cadr inputs) (car inputs))))
                   (emit (pcase op (83 'fixnum-dec) (84 'fixnum-inc) (85 'fixnum-eq)
                                  (86 'fixnum-gt) (87 'fixnum-lt) (88 'fixnum-le) (89 'fixnum-ge)
                                  (90 'fixnum-sub) (91 'fixnum-neg) (92 'fixnum-add) (95 'fixnum-mul))
                         (list (cons 'left-tag (* left 32)) (cons 'left-value (+ (* left 32) 8))
                               (cons 'right-tag (* right 32)) (cons 'right-value (+ (* right 32) 8))
                               (cons 'output-tag (* after 32)) (cons 'output-value (+ (* after 32) 8))
                               (cons 'output-pad1 (+ (* after 32) 16)) (cons 'output-pad2 (+ (* after 32) 24))
                               (cons 'slow (list 'arithmetic-slow pc)) (cons 'done (list 'arithmetic-done pc))))
                   (label (list 'arithmetic-slow pc))))
               (call (if (eq kind 'call) (- depth arg)
                       (cdr (assq (nth 1 (nelisp-native-funcall-v2-primitive op))
                                  (plist-get certificate :provider-roots)))) inputs)
               (copy-slot (plist-get certificate :result) after)
               (label (list 'arithmetic-done pc))
               (when (memq op '(144 145))
                 (frame-call (if (= op 144) 1 2)
                             (append (list (cdr (assq pc (plist-get certificate :frame-immediates))))
                                     (and (= op 144) (list after)))))))
            ('branch
             (if (= op 130) (emit 'jump (list (cons 'target arg)))
               (emit (if (memq op '(131 133)) 'nil-branch 'nonnull-branch)
                     (list (cons 'source depth) (cons 'tag-offset 0) (cons 'target arg)))))
            ('switch
             (let* ((info (assq pc (plist-get certificate :switch-targets)))
                    (table-name (list 'table pc)))
               (call (plist-get certificate :switch-root) (list (1- depth) depth (nth 1 info)))
               (emit 'switch (list (cons 'source (plist-get certificate :result)) (cons 'payload-offset 8)
                                   (cons 'target (aref row 2)) (cons 'table table-name)))
               (push (list table-name (nth 2 info)) tables)))
            ('return (emit 'return (list (cons 'status (+ 512 depth))
                                          (cons 'epilogue (if (plist-get certificate :frame-p) 'finish 'epilogue))))))
          (push (list pc start position) ranges)))
      ;; All ordinary quit edges share one rooted exit materialization.
      (label 'quit)
      (dotimes (i 3) (copy-slot (+ (plist-get certificate :quit-base) i)
                                (+ (plist-get certificate :exit-root-base) i)))
      (emit 'return (list (cons 'status (+ 1024 (plist-get certificate :exit-root-base)))
                               (cons 'epilogue (if (plist-get certificate :frame-p) 'finish 'epilogue))))
      (label 'bad) (emit 'bad nil)
      (when (plist-get certificate :frame-p)
        (label 'finish) (emit 'status-save nil)
        (when (plist-get certificate :handler-p)
          (emit 'status-branch (list (cons 'status (+ 1024 (plist-get certificate :exit-root-base)))
                                    (cons 'target 'leave)))
          (frame 11 (plist-get certificate :exit-root-base) (plist-get certificate :frame-result) 'landing-failure)
          (emit 'switch (list (cons 'source (plist-get certificate :frame-result)) (cons 'payload-offset 8)
                              (cons 'target 'bad) (cons 'table 'handler-table)))
          (push (list 'handler-table (plist-get (plist-get certificate :frame-analysis) :targets)) tables))
        (label 'leave)
        (frame 3 (plist-get certificate :staging) (plist-get certificate :frame-result) 'leave-failure)
        (emit 'status-restore nil) (emit 'jump (list (cons 'target 'epilogue)))
        (when (plist-get certificate :handler-p)
          (label 'landing-failure) (emit 'status-save nil) (emit 'jump (list (cons 'target 'leave))))
        (dolist (failure '(frame-failure leave-failure))
          (label failure) (emit 'status-save nil)
          (emit 'status-branch (list (cons 'status (+ 1024 (1+ (plist-get certificate :frame-result))))
                                    (cons 'target (if (eq failure 'frame-failure) 'finish 'epilogue))))
          (dotimes (i 3)
            (raw-copy (+ (plist-get certificate :frame-result) 1 i)
                      (+ (plist-get certificate :exit-root-base) i)))
          (emit 'return (list (cons 'status (+ 1024 (plist-get certificate :exit-root-base)))
                              (cons 'epilogue (if (eq failure 'frame-failure) 'finish 'epilogue))))))
      (label 'epilogue) (emit 'epilogue nil)
      (setq tables (nreverse tables))
      (dolist (table tables)
        (label (car table))
        (let ((bytes (make-string (* 4 (plist-get certificate :code-size)) 0)))
          (push bytes chunks) (setq position (+ position (length bytes)))))
      (let ((text (apply #'concat (nreverse chunks))))
        (dolist (fix fixups)
          (let ((offset (car fix)) (target (gethash (cadr fix) labels)))
            (unless target (error "Template unresolved label %S" (cadr fix)))
            (nelisp-native-template-patch32 text offset (- target (+ offset 4)))))
        (dolist (table tables)
          (let ((base (gethash (car table) labels)) (allowed (make-vector (plist-get certificate :code-size) nil)))
            (dolist (pc (cadr table)) (aset allowed pc t))
            (dotimes (pc (length allowed))
              (nelisp-native-template-patch32 text (+ base (* pc 4))
                                              (- (gethash (if (aref allowed pc) pc 'bad) labels) base)))))
        (list :text text :relocs (nreverse relocs) :pc-ranges (nreverse ranges))))))
(defun nelisp-native-template-manifest (recipe certificate assembled)
  "Publish an ordinary raw-v2 container with explicit template proof semantics."
  (let* ((text (plist-get assembled :text)) (size (length text))
         (gc (nelisp-native-load--raw-v2-contract)) (symbols (nelisp-native-load--raw-v2-symbols))
         (imports
          (mapcar (lambda (name)
                    (list :name name :kind 'func :index
                          (if (equal name "nl_root_pin_slot_v2")
                              (nelisp-native-load--raw-v2-conditional-import-index name)
                            (cl-position name nelisp-native-load-bridgeable-symbols :test #'equal))
                          :address-mode (if (equal name "nl_root_pin_slot_v2") 'conditional-root-slot-v1 'native-bridgeable-v1)
                          :abi (nelisp-native-load--runtime-abi-v2) :arity 6
                          :params '(u64 u64 u64 u64 u64 u64) :return 'u64))
                  (sort (delete-dups (mapcar (lambda (r) (plist-get r :symbol)) (plist-get assembled :relocs))) #'string<)))
         (exports (list (list :name nelisp-native-template-entry :value 0 :size size :arity 4
                             :params '(u64 u64 u64 u64) :return 'u64 :type 'func :abi (nelisp-native-load--runtime-abi-v2))))
         (manifest
          (list :format nelisp-native-load-raw-artifact-format-v2 :kind 'raw-runtime
                :runtime-kind 'gc-arena :runtime-abi (nelisp-native-load--runtime-abi-v2)
                :layout-id nelisp-native-load-raw-layout-id-v2 :arch nelisp-native-load-raw-supported-arch
                :binary-sha256 (nelisp-native-load-running-binary-sha256) :runtime-opt-in t
                :gc-contract-hash (nelisp-native-load--raw-v2-contract-hash gc)
                :gc-address-mode 'runtime-bridge-v1
                :gc-entries (cl-loop for p in gc for i from 0 collect
                                     (list :name (car p) :arity (cdr p) :index i :return 'u64 :abi (nelisp-native-load--runtime-abi-v2)))
                :gc-table-magic nelisp-native-load-raw-gc-table-magic :gc-table-count (length gc)
                :resolver-contract-version nelisp-native-load-raw-v2-import-contract-version
                :resolver-contract-hash (nelisp-native-load--raw-v2-import-contract-hash symbols)
                :native-template-proof-version nelisp-native-template-proof-version
                :native-template-proof (list :library nelisp-native-template-library-sha256 :input recipe
                                             :certificate certificate :pc-ranges (plist-get assembled :pc-ranges))
                :native (list :raw-abi (nelisp-native-load--runtime-abi-v2) :object-format 'nelisp-aot-raw-unit-v2
                              :text-size size :text-base64 (base64-encode-string text t)
                              :object-sha256 (secure-hash 'sha256 text) :object-size size
                              :exports exports :symbols exports :imports imports :extern-symbols (mapcar (lambda (i) (plist-get i :name)) imports)
                              :relocs (plist-get assembled :relocs) :data-size 0 :bss-size 0))))
    (when (nelisp-native-load--windows-p)
      (setq manifest (append manifest (list :target (nelisp-native-load--target-v2)))))
    (let* ((unsigned (nelisp-native-template--print manifest))
           (digest (secure-hash 'sha256 unsigned))
           (signed (append manifest (list :artifact-sha256 digest))))
      (when nelisp-native-template--serialization-receiver
        (funcall nelisp-native-template--serialization-receiver signed
                 (concat (substring unsigned 0 -1) " :artifact-sha256 "
                         (prin1-to-string digest) ")")))
      signed)))
(defun nelisp-native-template-bounded-data-p (value)
  "Bound inert proof data before plist traversal, printing or copying."
  (let ((todo (list (cons value 0))) (budget 20000) (valid t))
    (while (and todo valid (> budget 0))
      (let* ((item (pop todo)) (node (car item)) (depth (cdr item)))
        (setq budget (1- budget))
        (cond ((> depth 256) (setq valid nil))
              ((or (null node) (symbolp node) (numberp node)) nil)
              ((stringp node) (unless (<= (length node) 1048576) (setq valid nil)))
              ((consp node) (push (cons (car node) (1+ depth)) todo)
               (push (cons (cdr node) depth) todo))
              ((vectorp node)
               (if (> (length node) 4096) (setq valid nil)
                 (dotimes (i (length node)) (push (cons (aref node i) (1+ depth)) todo))))
              (t (setq valid nil)))))
    (and valid (null todo))))
(defun nelisp-native-template-check (manifest)
  "Authenticate input, root and patch proof plus exact emission.
No SSA, AST, optimizer or AOT compiler is involved. Producer compilation calls
its validator once. Explicit checked loads reconstruct the proof."
  (condition-case err
      (progn
        (unless (and (nelisp-native-template-bounded-data-p manifest)
                     (equal (plist-get manifest :native-template-proof-version) nelisp-native-template-proof-version))
          (error "Template proof shape/version refused"))
        (let* ((library (nelisp-native-template-open-library))
               (recipe (plist-get (plist-get manifest :native-template-proof) :input))
               (certificate (nelisp-native-template-validate recipe))
               (assembled (nelisp-native-template-assemble certificate library))
               (expected (nelisp-native-template-manifest recipe certificate assembled)))
          (unless (equal manifest expected) (error "Template proof/emission refused")))
        nil)
    (error (list (list :template-refused err)))))
(defun nelisp-native-template-compile (function)
  "Compile, validate once and atomically publish with the common trusted mapper."
  (unless (and (eq nelisp-native-cache-mode 'shared-v2)
               (eq nelisp-native-cache-guard-mode 'off))
    (error "Unsupported template compilation mode"))
  (let ((file (nelisp-native-cache-file function)))
    (unless file (error "Template cache identity unavailable"))
    (unless (file-exists-p file)
      ;; Library authentication happens before validation, copying or mapping.
      (let* ((serialized nil)
             (nelisp-native-template--serialization-receiver
              (lambda (manifest bytes) (setq serialized (cons manifest bytes))))
             (library (nelisp-native-template-open-library))
             (recipe (nelisp-native-template-recipe (nelisp-native-cache--function function)))
             (certificate (nelisp-native-template-validate recipe))
             (assembled (nelisp-native-template-assemble certificate library))
             (manifest (nelisp-native-template-manifest recipe certificate assembled))
             (_bounded (unless (nelisp-native-template-bounded-data-p manifest)
                         (error "Template publication proof bound refused")))
             (header (list :nelisp-native-cache 1 :canonical-manifest 'prebuilt-v1 :backend 'template
                           :abi (nelisp-native-cache-abi-hash) :input (nelisp-native-cache--input-hash function)
                           :entry nelisp-native-template-entry :arity (plist-get certificate :arity)
                           :root-count (plist-get certificate :root-count) :exit-root-base (plist-get certificate :exit-root-base)
                           :initializers (plist-get certificate :initializers)))
             ;; As in-house: a Windows temporary carries the owner and
             ;; protected DACL from creation; a plain file inherits an
             ;; Administrators owner on elevated tokens and is refused.
             (temporary (funcall (if (nelisp-native-load--windows-p)
                                     #'nelisp-native-windows-temporary #'make-temp-file)
                                 (expand-file-name ".publish-" (file-name-directory file)))))
        (unwind-protect
            (let ((coding-system-for-write 'utf-8-unix))
              (write-region (concat (nelisp-native-template--print header) "\n"
                                    (if (eq manifest (car serialized)) (cdr serialized)
                                      (nelisp-native-template--print manifest)) "\n") nil temporary nil 'silent)
              (nelisp-native-cache--publish temporary file)
              (setq nelisp-native-template--compile-count (1+ nelisp-native-template--compile-count)))
          (when (file-exists-p temporary) (delete-file temporary)))))
    file))
(provide 'nelisp-native-template)
