;;; nelisp-cc-evalport-nonenv-char-table-map.el --- sparse map-char-table walker -*- lexical-binding: t; -*-
;;; Code:
(defconst nelisp-cc-evalport-nonenv-char-table-map--source
  '(seq
    (defun nl_ct_map_next_boundary (box cursor)
      (let* ((best 4194304) (walk box) (len 0) (entries 0)
             (i 0) (key 0) (candidate 0))
        (while (/= walk 0)
          (setq len (ptr-read-u64 (+ walk 80) 0))
          (setq entries (ptr-read-u64 (+ walk 64) 0))
          (setq i 0)
          (while (< i len)
            (setq key (ptr-read-u64 (+ entries (* i 40)) 0))
            (if (and (> key cursor) (< key best))
                (setq best key)
              0)
            (setq candidate (+ key 1))
            (if (and (> candidate cursor) (< candidate best))
                (setq best candidate)
              0)
            (setq i (+ i 1)))
          (setq walk (ptr-read-u64 (+ walk 88) 0)))
        best))
    (defun nl_ct_map_parent_next (box)
      (if (= box 0) 0 (ptr-read-u64 (+ box 88) 0)))
    (defun nl_ct_map_parent_cycle_p (box)
      (let* ((slow box) (fast box) (cycle 0))
        (while (and (/= fast 0) (= cycle 0))
          (setq slow (nl_ct_map_parent_next slow))
          (setq fast (nl_ct_map_parent_next fast))
          (if (/= fast 0)
              (setq fast (nl_ct_map_parent_next fast))
            0)
          (if (and (/= fast 0) (= slow fast))
              (setq cycle 1)
            0))
        cycle))
    (defun nl_ct_parent_chain_contains (box sought)
      (let* ((walk box) (found 0))
        (while (and (/= walk 0) (= found 0))
          (if (= walk sought)
              (setq found 1)
            (setq walk (nl_ct_map_parent_next walk)))
          0)
        found))
    (defun nl_ct_map_run_end (table box cursor value probe)
      (let* ((boundary (nl_ct_map_next_boundary box cursor))
             (done 0) (end 4194303))
        (while (and (< boundary 4194304) (= done 0))
          (nl_char_table_get_raw table boundary probe)
          (if (= (bf_eq2 value probe) 1)
              (seq
               (setq cursor boundary)
               (setq boundary (nl_ct_map_next_boundary box cursor)))
            (seq (setq end (- boundary 1)) (setq done 1))))
        (if (= done 0) 4194303 end)))
    (defun nl_ct_map_apply (fn key-slot value env)
      (let* ((mark (nl_root_mark env))
             (base (nl_root_reserve_checked env))
             (value-slot (nl_root_reserve_checked env))
             (out-slot (nl_root_reserve_checked env))
             (valid (if (= base 0) 0
                      (if (= value-slot (+ base 32))
                          (if (= out-slot (+ base 64))
                              1
                            0)
                        0))))
        (if (= valid 0)
            (seq (nl_root_release env mark) (wf_bytecode_root_exhausted))
          (seq
           (wf_copy32 base key-slot)
           (wf_copy32 value-slot value)
           (let* ((rc (wf_bytecode_call_gateway env fn base 0 2 out-slot)))
             (nl_root_release env mark)
             rc)))))
    (defun nl_ct_map_table (table fn env)
      (let* ((mark (nl_root_mark env))
             (table-slot (nl_root_reserve_checked env))
             (fn-slot (nl_root_reserve_checked env))
             (value-slot (nl_root_reserve_checked env))
             (probe-slot (nl_root_reserve_checked env))
             (range-slot (nl_root_reserve_checked env))
             (nil-slot (nl_root_reserve_checked env))
             (key-slot (nl_root_reserve_checked env))
             (start-slot (nl_root_reserve_checked env))
             (end-slot (nl_root_reserve_checked env))
             (cursor 0) (end 0) (rc 0) (done 0)
             (valid (if (= table-slot 0) 0
                      (if (= fn-slot (+ table-slot 32))
                          (if (= value-slot (+ table-slot 64))
                              (if (= probe-slot (+ table-slot 96))
                                  (if (= range-slot (+ table-slot 128))
                                      (if (= nil-slot (+ table-slot 160))
                                          (if (= key-slot (+ table-slot 192))
                                              (if (= start-slot (+ table-slot 224))
                                                  (if (= end-slot (+ table-slot 256)) 1 0)
                                                0)
                                            0)
                                        0)
                                    0)
                                0)
                            0)
                        0)))
             (box 0))
        (if (= valid 0)
            (seq (nl_root_release env mark) (wf_bytecode_root_exhausted))
          (seq
         (wf_copy32 table-slot table)
         (wf_copy32 fn-slot fn)
         (wf_write_nil nil-slot)
         (nelisp_cons_construct nil-slot nil-slot range-slot)
         (while (and (<= cursor 4194303) (= done 0) (= rc 0))
           ;; Reload from the rooted Sexp after every callback; this remains
           ;; correct if a future collector moves the table box.
           (setq box (ptr-read-u64 (+ table-slot 8) 0))
           (nl_char_table_get_raw table-slot cursor value-slot)
           (setq end (nl_ct_map_run_end table-slot box cursor value-slot probe-slot))
           (if (= cursor end)
               (wf_write_int key-slot cursor)
             (seq
             (wf_write_int start-slot cursor)
              (wf_write_int end-slot end)
              (wf_dirty)
              (cons-set-car range-slot start-slot)
              (cons-set-cdr range-slot end-slot)
              (wf_copy32 key-slot range-slot)))
           (if (= (ptr-read-u64 value-slot 0) 0)
               (setq cursor (+ end 1))
             (let* ((call-rc
                     (if (= (wf_mapcar_resolve_fn fn-slot env nil-slot) 1)
                         (nl_ct_map_apply nil-slot key-slot value-slot env)
                       (seq (nl_cons_stash_void_function env fn-slot) 1))))
               (if (= call-rc 0)
                   (setq cursor (+ end 1))
                 (seq (setq rc call-rc) (setq done 1))))))
         (nl_root_release env mark)
         rc)))))
  "Native sparse boundary traversal for effective char-table spans.")

(provide 'nelisp-cc-evalport-nonenv-char-table-map)
;;; nelisp-cc-evalport-nonenv-char-table-map.el ends here
