;;; nelisp-cc-evalport-nonenv-char-table.el --- lowered -*- lexical-binding: t; -*-
;;; Commentary:
;; CharTable storage kernel.  The entries array holds sorted, disjoint,
;; inclusive run-length intervals, 48 bytes each:
;;   +0  start  (i64)
;;   +8  value  (32-byte Sexp)
;;   +40 end    (i64)
;; Lookup is a binary search; `nl_ct_set_range' trims/splits/replaces the
;; overlapped intervals in one pass and coalesces `eq' neighbours, so a
;; set over any range (even 0..#x3FFFFF) is O(log n) plus one array shift.
;; Slot value nil (or no interval) falls through to the table default and
;; then to the parent chain, exactly like GNU `char_table_ref'.
;;; Code:
(defconst nelisp-cc-evalport-nonenv-char-table--source
  (quote
   (seq
    (defun nl_ct_copy_u64s (src dst i n)
      (if (= i n) 1
        (let* ((word_off (* i 8))
               (val (ptr-read-u64 (+ src word_off) 0)))
          (seq (ptr-write-u64 (+ dst word_off) 0 val)
               (nl_ct_copy_u64s src dst (+ i 1) n)))))
    (defun nl_ct_copy_entries (src_ptr dst_ptr i n)
      (if (= i n) 1
        (let* ((entry_off (* i 48)))
          (seq (nl_ct_copy_u64s (+ src_ptr entry_off) (+ dst_ptr entry_off) 0 6)
               (nl_ct_copy_entries src_ptr dst_ptr (+ i 1) n)))))
    (defun nl_ct_grow_entries (box old_ptr old_cap old_len)
      (let* ((new_cap (if (< (* old_cap 2) 4) 4 (* old_cap 2)))
             (new_ptr (nelisp_alloc_bytes (* new_cap 48) 8)))
        (seq (nl_ct_copy_entries old_ptr new_ptr 0 old_len)
             (if (> old_cap 0) (nelisp_dealloc_bytes old_ptr (* old_cap 48) 8) 1)
             (seq (ptr-write-u64 (+ box 64) 0 new_ptr)
                  (ptr-write-u64 (+ box 72) 0 new_cap))
             new_ptr)))
    ;; Ensure room for NEED entries; returns the (possibly new) array pointer.
    (defun nl_ct_reserve (box need)
      (let* ((eptr (ptr-read-u64 (+ box 64) 0))
             (ecap (ptr-read-u64 (+ box 72) 0))
             (elen (ptr-read-u64 (+ box 80) 0)))
        (if (<= need ecap) eptr (nl_ct_grow_entries box eptr ecap elen))))
    (defun nl_ct_start (eptr i) (ptr-read-u64 (+ eptr (* i 48)) 0))
    (defun nl_ct_end (eptr i) (ptr-read-u64 (+ eptr (+ (* i 48) 40)) 0))
    (defun nl_ct_val (eptr i) (+ eptr (+ (* i 48) 8)))
    ;; Move COUNT entries from index FROM to index TO (overlap safe).
    (defun nl_ct_move_entries (eptr from to count)
      (let* ((src (+ eptr (* from 48)))
             (dst (+ eptr (* to 48)))
             (nw (* count 6))
             (k 0))
        (if (< dst src)
            (while (< k nw)
              (ptr-write-u64 (+ dst (* k 8)) 0 (ptr-read-u64 (+ src (* k 8)) 0))
              (setq k (+ k 1)))
          (seq (setq k nw)
               (while (> k 0)
                 (setq k (- k 1))
                 (ptr-write-u64 (+ dst (* k 8)) 0 (ptr-read-u64 (+ src (* k 8)) 0)))))
        1))
    ;; First index whose end >= X (N if none).
    (defun nl_ct_lower_end (eptr n x)
      (let* ((lo 0) (hi n) (mid 0))
        (while (< lo hi)
          (setq mid (/ (+ lo hi) 2))
          (if (>= (nl_ct_end eptr mid) x)
              (setq hi mid)
            (setq lo (+ mid 1))))
        lo))
    ;; First index whose start > X (N if none).
    (defun nl_ct_upper_start (eptr n x)
      (let* ((lo 0) (hi n) (mid 0))
        (while (< lo hi)
          (setq mid (/ (+ lo hi) 2))
          (if (> (nl_ct_start eptr mid) x)
              (setq hi mid)
            (setq lo (+ mid 1))))
        lo))
    ;; Effective lookup: interval value, else default, else parent chain.
    (defun nl_ct_get_box (box idx out)
      (let* ((eptr (ptr-read-u64 (+ box 64) 0))
             (elen (ptr-read-u64 (+ box 80) 0))
             (i (nl_ct_lower_end eptr elen idx))
             (hit (if (< i elen) (if (<= (nl_ct_start eptr i) idx) 1 0) 0))
             (vslot (nl_ct_val eptr i)))
        (if (if (= hit 1) (/= (nelisp_ptr_read_u8 vslot 0) 0) 0)
            (seq (nl_sexp_clone_into vslot out) 0)
          (let* ((parent_ptr (ptr-read-u64 (+ box 88) 0)))
            (if (if (= (nelisp_ptr_read_u8 (+ box 32) 0) 0) (/= parent_ptr 0) 0)
                (nl_ct_get_box parent_ptr idx out)
              (seq (nl_sexp_clone_into (+ box 32) out) 0))))))
    ;; `char-table-range' on a (FROM . TO) cons: slot value, else default,
    ;; never the parent chain (verified against host Emacs).
    (defun nl_char_table_get_local_raw (arg idx out)
      (let* ((box (ptr-read-u64 (+ arg 8) 0))
             (eptr (ptr-read-u64 (+ box 64) 0))
             (elen (ptr-read-u64 (+ box 80) 0))
             (i (nl_ct_lower_end eptr elen idx))
             (hit (if (< i elen) (if (<= (nl_ct_start eptr i) idx) 1 0) 0))
             (vslot (nl_ct_val eptr i)))
        (if (if (= hit 1) (/= (nelisp_ptr_read_u8 vslot 0) 0) 0)
            (seq (nl_sexp_clone_into vslot out) 0)
          (seq (nl_sexp_clone_into (+ box 32) out) 0))))
    (defun nl_char_table_get_raw (arg idx out)
      (let* ((tag (nelisp_ptr_read_u8 arg 0)))
        (if (= tag 9)
            (nl_ct_get_box (ptr-read-u64 (+ arg 8) 0) idx out)
          1)))
    ;; Merge entry P with its right / left neighbour when adjacent and `eq'.
    (defun nl_ct_coalesce (box p)
      (let* ((eptr (ptr-read-u64 (+ box 64) 0))
             (n (ptr-read-u64 (+ box 80) 0)))
        (if (< (+ p 1) n)
            (if (= (nl_ct_start eptr (+ p 1)) (+ (nl_ct_end eptr p) 1))
                (if (= (bf_eq2 (nl_ct_val eptr p) (nl_ct_val eptr (+ p 1))) 1)
                    (seq (ptr-write-u64 (+ eptr (+ (* p 48) 40)) 0
                                        (nl_ct_end eptr (+ p 1)))
                         (nl_ct_move_entries eptr (+ p 2) (+ p 1) (- n (+ p 2)))
                         (setq n (- n 1))
                         (ptr-write-u64 (+ box 80) 0 n))
                  0)
              0)
          0)
        (if (> p 0)
            (if (= (+ (nl_ct_end eptr (- p 1)) 1) (nl_ct_start eptr p))
                (if (= (bf_eq2 (nl_ct_val eptr (- p 1)) (nl_ct_val eptr p)) 1)
                    (seq (ptr-write-u64 (+ eptr (+ (* (- p 1) 48) 40)) 0
                                        (nl_ct_end eptr p))
                         (nl_ct_move_entries eptr (+ p 1) p (- n (+ p 1)))
                         (setq n (- n 1))
                         (ptr-write-u64 (+ box 80) 0 n))
                  0)
              0)
          0)
        1))
    (defun nl_ct_write_entry (eptr i from to val)
      (let* ((ent (+ eptr (* i 48))))
        (seq (ptr-write-u64 ent 0 from)
             (nl_sexp_clone_into val (+ ent 8))
             (ptr-write-u64 (+ ent 40) 0 to)
             1)))
    ;; The interval at LO..HI overlaps [FROM,TO].  Trim/split the border
    ;; intervals, replace the fully covered ones with one new interval.
    (defun nl_ct_set_range2 (box eptr n lo hi from to val)
      (let* ((keepl (if (< lo hi) (if (< (nl_ct_start eptr lo) from) 1 0) 0))
             (keepr (if (< lo hi) (if (> (nl_ct_end eptr (- hi 1)) to) 1 0) 0))
             (eptr2 eptr) (pl lo) (pr hi) (r 0) (n2 n))
        (if (= (+ keepl keepr) 2)
            (if (= (- hi lo) 1)
                ;; One interval strictly contains the range: split in three.
                (seq
                 (setq eptr2 (nl_ct_reserve box (+ n 2)))
                 (nl_ct_move_entries eptr2 hi (+ hi 2) (- n hi))
                 (ptr-write-u64 (+ eptr2 (* (+ hi 1) 48)) 0 (+ to 1))
                 (nl_sexp_clone_into (nl_ct_val eptr2 lo)
                                     (nl_ct_val eptr2 (+ hi 1)))
                 (ptr-write-u64 (+ eptr2 (+ (* (+ hi 1) 48) 40)) 0
                                (nl_ct_end eptr2 lo))
                 (nl_ct_write_entry eptr2 hi from to val)
                 (ptr-write-u64 (+ eptr2 (+ (* lo 48) 40)) 0 (- from 1))
                 (ptr-write-u64 (+ box 80) 0 (+ n 2))
                 1)
              0)
          0)
        (if (if (= (+ keepl keepr) 2) (= (- hi lo) 1) 0)
            1
          (seq
           (if (= keepl 1)
               (ptr-write-u64 (+ eptr (+ (* lo 48) 40)) 0 (- from 1))
             0)
           (if (= keepr 1)
               (ptr-write-u64 (+ eptr (* (- hi 1) 48)) 0 (+ to 1))
             0)
           (setq pl (+ lo keepl))
           (setq pr (- hi keepr))
           (setq r (- pr pl))
           (if (= r 0)
               (seq (setq eptr2 (nl_ct_reserve box (+ n 1)))
                    (nl_ct_move_entries eptr2 pl (+ pl 1) (- n pl))
                    (setq n2 (+ n 1)))
             (seq (nl_ct_move_entries eptr pr (+ pl 1) (- n pr))
                  (setq n2 (- n (- r 1)))))
           (nl_ct_write_entry eptr2 pl from to val)
           (ptr-write-u64 (+ box 80) 0 n2)
           (nl_ct_coalesce box pl)
           1))))
    ;; Set every char in [FROM,TO] (FROM <= TO, both valid chars) to VAL.
    (defun nl_ct_set_range (box from to val)
      (let* ((eptr (ptr-read-u64 (+ box 64) 0))
             (n (ptr-read-u64 (+ box 80) 0))
             (lo (nl_ct_lower_end eptr n from))
             (hi (nl_ct_upper_start eptr n to))
             (same (if (= (- hi lo) 1)
                       (if (<= (nl_ct_start eptr lo) from)
                           (if (>= (nl_ct_end eptr lo) to)
                               (bf_eq2 (nl_ct_val eptr lo) val)
                             0)
                         0)
                     0)))
        (if (= same 1)
            1
          (nl_ct_set_range2 box eptr n lo hi from to val))))
    (defun nl_char_table_set_raw (arg idx val out)
      (let* ((tag (nelisp_ptr_read_u8 arg 0)))
        (if (= tag 9)
            (seq (nl_ct_set_range (ptr-read-u64 (+ arg 8) 0) idx idx val)
                 (nl_sexp_clone_into val out)
                 0)
          1)))
    (defun nl_char_table_set_range_raw (arg from to val out)
      (let* ((tag (nelisp_ptr_read_u8 arg 0)))
        (if (= tag 9)
            (seq (nl_ct_set_range (ptr-read-u64 (+ arg 8) 0) from to val)
                 (nl_sexp_clone_into val out)
                 0)
          1)))))
  "Interval-based CharTable get/set kernel.")
(provide (quote nelisp-cc-evalport-nonenv-char-table))
;;; nelisp-cc-evalport-nonenv-char-table.el ends here
