;;; nelisp-syscall-table.el --- Doc 84 §84.2 syscall nr table  -*- lexical-binding: t; -*-

;;; Commentary:

;; AUTO-GENERATED by build-tool/build.rs. DO NOT EDIT.

;;; Code:

(setq nelisp--syscall-nr-table
      '(
        (read . 0)
        (write . 1)
        (close . 3)
        (openat . 257)
        (exit_group . 231)
        (lseek . 8)
        (dup2 . 33)
        (getpid . 39)
        (kill . 62)
        (mmap . 9)
        (mprotect . 10)
        (munmap . 11)
        (fcntl . 72)
        (fork . 57)
        (socket . 41)
        (listen . 50)
        (wait4 . 61)
        (getppid . 110)
        (setpgid . 109)
        (pidfd_open . 434)
        (pidfd_send_signal . 424)
        (inotify_init1 . 294)
        (inotify_rm_watch . 255)
        (eventfd2 . 290)
        (timerfd_create . 283)
        ))

(fset 'nelisp--syscall-nr-resolve
      (lambda (name)
(if (integerp name)
            name
(let ((cell (assq name nelisp--syscall-nr-table)))
(if cell (cdr cell)
(signal 'arith-error (cons "nelisp--syscall-nr-resolve: unknown syscall" (cons name nil))))))))

;;; nelisp-syscall-table.el ends here
