;;; nelisp-bytecode-native-rooted-stack-call.el --- checked rooted stack caller -*- lexical-binding: t; -*-
(require 'cl-lib)
(require 'nelisp-native-load)

(defun nelisp-bytecode-native-rooted-stack-call--manifest-import-names (manifest)
  "Return canonical v2 import names after validating descriptor records."
  (let ((descriptors (plist-get (plist-get manifest :native) :imports)) names)
    (unless (listp descriptors)
      (error "rooted-stack-call: malformed import descriptors"))
    (dolist (descriptor descriptors)
      (let ((name (and (listp descriptor) (plist-get descriptor :name))))
        (unless (and (stringp name)
                     (equal (plist-get descriptor :kind) 'func)
                     (equal (plist-get descriptor :abi) (nelisp-native-load--runtime-abi-v2))
                     (eq (plist-get descriptor :address-mode) 'native-bridgeable-v1)
                     (integerp (plist-get descriptor :index))
                     (>= (plist-get descriptor :index) 0)
                     (member name '("nl_native_car_v2" "nl_native_cdr_v2"
                                    "nl_native_cons_v2")))
          (error "rooted-stack-call: malformed or unknown import descriptor"))
        (push name names)))
    (setq names (sort names #'string<))
    (when (/= (length names) (length (delete-dups (copy-sequence names))))
      (error "rooted-stack-call: duplicate import descriptor"))
    names))

(defun nelisp-bytecode-native-rooted-stack-call (result &rest arguments)
  "Execute authenticated rooted-stack RESULT on ARGUMENTS.
There is no interpreted fallback: stale producer metadata or an invalid
native status signals before a value is returned."
    (unless (fboundp 'nelisp-bytecode-native-rooted-stack-authenticated-result-p)
      (error "rooted-stack-call: unauthenticated producer result"))
  (let* ((input (plist-get result :input))
         (plan (plist-get result :plan))
         (count (plist-get result :argument-count))
         (root-count (plist-get plan :required-root-count))
         (constants (plist-get result :constants))
         (constant-roots (plist-get plan :constant-roots))
         (operations (plist-get plan :operations))
         (final (plist-get plan :final-root))
         (artifact (plist-get result :artifact-path))
         (entry-name "nl_native_stack_probe_v1"))
    (unless (and (eq (plist-get result :status) 'complete)
                 (eq (plist-get plan :status) 'complete)
                 (integerp count) (= count (length arguments))
                 (integerp root-count) (> root-count 0)
                 (integerp final) (> final 0) (< final root-count)
                 (vectorp constants)
                 (equal (plist-get plan :initial-roots) (number-sequence 1 count))
                 (equal constants (plist-get input :constants))
                 (equal (plist-get result :entry-name) entry-name)
                 (stringp artifact)
                 (listp operations) (listp constant-roots)
                 (cl-every (lambda (op)
                             (and (memq (plist-get op :operation) '(car cdr cons))
                                  (cl-every (lambda (i) (and (integerp i)
                                                             (> i 0) (< i root-count)))
                                            (plist-get op :inputs))
                                  (cl-every (lambda (i) (and (integerp i)
                                                             (> i 0) (< i root-count)))
                                            (plist-get op :outputs)))) operations)
                 (cl-every (lambda (pair)
                             (and (consp pair) (integerp (car pair))
                                  (<= 0 (car pair)) (< (car pair) (length constants))
                                  (integerp (cdr pair)) (> (cdr pair) 0)
                                  (< (cdr pair) root-count))) constant-roots))
      (error "rooted-stack-call: malformed producer result"))
    (unless (nelisp-bytecode-native-rooted-stack-authenticated-result-p result)
      (error "rooted-stack-call: producer result changed"))
    (unless (and (equal (plist-get result :runtime-binary-sha256)
                        (nelisp-native-load-running-binary-sha256))
                 (equal (sort (delete-dups
                               (mapcar (lambda (op)
                                         (format "nl_native_%s_v2"
                                                 (plist-get op :operation)))
                                       operations)) #'string<)
                        (sort (copy-sequence (plist-get result :gateway-imports)) #'string<))
                 (cl-every (lambda (name) (member name
                                      '("nl_native_car_v2" "nl_native_cdr_v2"
                                        "nl_native_cons_v2")))
                           (plist-get result :gateway-imports)))
      (error "rooted-stack-call: runtime or import contract mismatch"))
    (let* ((addresses (nelisp-native-load-root-v2-addresses))
           (env (plist-get addresses :environment))
           (manifest (nelisp-native-load-manifest artifact))
           (manifest-imports
            (nelisp-bytecode-native-rooted-stack-call--manifest-import-names manifest))
           (ticket (and (integerp env) (> env 0)
                        (ptr-call (plist-get addresses :begin) env 0 0 0 0 0)))
           mapping slots)
      (unwind-protect
          (progn
            (unless (and (integerp ticket) (> ticket 0))
              (error "rooted-stack-call: root frame begin failed"))
            (setq mapping (nelisp-native-load-raw-v2-artifact
                           artifact entry-name (plist-get result :runtime-binary-sha256)))
            (unless (and (memq mapping nelisp-native-load-raw-mappings)
                         (eq (plist-get mapping :kind) 'raw-runtime-v2)
                         (equal (plist-get mapping :entry-name) entry-name)
                         (= (or (plist-get mapping :arity) -1) 4)
                         (equal (plist-get mapping :runtime-abi)
                                (nelisp-native-load--runtime-abi-v2))
                         (equal (plist-get mapping :raw-abi)
                                (nelisp-native-load--runtime-abi-v2))
                         (equal manifest-imports
                                (sort (copy-sequence (plist-get result :gateway-imports)) #'string<)))
              (error "rooted-stack-call: mapped import contract mismatch"))
            (dotimes (_ root-count)
              (push (ptr-call (plist-get addresses :reserve) env ticket 0 0 0 0)
                    slots))
            (setq slots (nreverse slots))
            (unless (and (integerp ticket) (> ticket 0)
                         (cl-every (lambda (x) (and (integerp x) (> x 0))) slots))
              (error "rooted-stack-call: root frame reservation failed"))
            (dolist (slot slots) (nelisp-native-load-box slot nil env (car slots)))
            (cl-loop for arg in arguments for i from 1 do
                     (unless (= (nelisp-native-load-root-v2-copy env ticket i arg)
                                (nth i slots))
                       (error "rooted-stack-call: argument pin authentication failed")))
            (dolist (pair constant-roots)
              (unless (= (nelisp-native-load-root-v2-copy
                          env ticket (cdr pair) (aref constants (car pair)))
                         (nth (cdr pair) slots))
                (error "rooted-stack-call: constant pin authentication failed")))
            (cl-loop for expected in slots for index from 0 do
                     (unless (= expected (ptr-call (plist-get addresses :slot)
                                                   env ticket index 0 0 0))
                       (error "rooted-stack-call: root slot authentication failed")))
            (let ((status (ptr-call (nelisp-native-load-raw-export-address
                                     mapping entry-name)
                                    env ticket count root-count 0 0)))
              (garbage-collect)
              (cl-loop for expected in slots for index from 0 do
                       (unless (= expected (ptr-call (plist-get addresses :slot)
                                                     env ticket index 0 0 0))
                         (error "rooted-stack-call: post-call root authentication failed")))
              (cond ((= status 0) (nelisp-native-load-unbox (nth final slots) env (car slots)))
                    ((and (>= status 257) (< (- status 256) root-count))
                     (signal 'wrong-type-argument
                             (list 'listp (nelisp-native-load-unbox
                                           (nth (- status 256) slots) env (car slots)))))
                    (t (error "rooted-stack-call: native entry rejected request (%s)" status)))))
        (unwind-protect
            (when (and (integerp ticket) (> ticket 0))
              (unless (= (ptr-call (plist-get addresses :end) env ticket 0 0 0 0) 1)
                (error "rooted-stack-call: root frame ownership lost")))
          (when mapping (nelisp-native-load-unload mapping)))))))

(provide 'nelisp-bytecode-native-rooted-stack-call)
