;;; nelisp-dev-gc.el --- DEV GC adapter -*- lexical-binding: t; -*-
(require 'nelisp-dev-protocol)
(require 'nelisp-repl-gc)
(defconst nelisp-dev-gc--ttl 900)
(defconst nelisp-dev-gc--limit 64)
(defvar nelisp-dev-gc--snapshots (make-hash-table :test #'equal))
(defvar nelisp-dev-gc--epochs (make-hash-table :test #'equal))
(defvar nelisp-dev-gc--next-epoch 0)
(defun nelisp-dev-gc--reload-status ()
  (when (fboundp 'nelisp-runtime-reload-status)
    (condition-case nil (nelisp-runtime-reload-status) (error nil))))
(defun nelisp-dev-gc--wire (value)
  "Convert legacy measurements through the shared wire representation."
  (nelisp-dev-protocol-value value))
(defun nelisp-dev-gc--annotate (context snapshot)
  "Attach identity metadata to SNAPSHOT and advance its session epoch."
  (nelisp-dev-gc--purge-expired-epochs)
  (let* ((session (or (plist-get context :session-id) "host-session"))
         (reload (nelisp-dev-gc--reload-status))
         ;; Generation is read from the runtime status on every sample.  The
         ;; context is deliberately not trusted as a publication identity.
         (generation (and (eq (plist-get reload :status) 'ready)
                          (plist-get reload :generation)))
         (raw (plist-get snapshot :raw))
         (stats (plist-get raw :gc-stats))
         (total (plist-get stats :allocated-total))
         (abi (plist-get raw :abi-status))
         (old (gethash session nelisp-dev-gc--epochs))
         (epoch (if old (car old) (cl-incf nelisp-dev-gc--next-epoch))))
    (when (or (and old (not (equal generation (nth 1 old))))
              (and (numberp (nth 2 old)) (numberp total)
                   (< total (nth 2 old)))
              (and (numberp (nth 3 old))
                   (numberp (plist-get stats :collections))
                   (< (plist-get stats :collections) (nth 3 old))))
      (setq epoch (cl-incf nelisp-dev-gc--next-epoch)))
    ;; Keep session identity bounded like snapshot identity.
    (when (and (not old) (>= (hash-table-count nelisp-dev-gc--epochs) 64))
      (nelisp-dev-gc--purge-expired-epochs))
    (puthash session (list epoch generation total
                           (plist-get stats :collections) (float-time))
             nelisp-dev-gc--epochs)
    (list :snapshot snapshot :session-id session :generation generation
          :abi abi :reload-status (plist-get reload :status)
          :binary-identity :unknown :epoch epoch
          :field-semantics '(:cumulative-counters "epoch cumulative"
                             :gauges "current value"
                             :last-collection "last collection only"))))
(defun nelisp-dev-gc--purge-expired-epochs ()
  (let* ((now (float-time)) (oldest nil) (old-time now))
    (maphash (lambda (session entry)
               (if (> (- now (nth 4 entry)) nelisp-dev-gc--ttl)
                   (remhash session nelisp-dev-gc--epochs)
                 (when (<= (nth 4 entry) old-time)
                   (setq oldest session old-time (nth 4 entry)))))
             nelisp-dev-gc--epochs)
    (when (and oldest (>= (hash-table-count nelisp-dev-gc--epochs) 64))
      (remhash oldest nelisp-dev-gc--epochs))))
(defun nelisp-dev-gc--snapshot (context)
  (let* ((before (nelisp-dev-gc--reload-status))
         (record (nelisp-dev-gc--annotate context (nelisp-repl-gc-snapshot))))
    (unless (and (eq (plist-get before :status) 'ready)
                 (equal (plist-get before :generation) (plist-get record :generation)))
      (setq record (plist-put record :generation nil))
      (setq record (plist-put record :capture-continuity :unknown)))
    record))
(defun nelisp-dev-gc--purge-expired ()
  (let ((now (float-time)) (removed 0))
    (maphash (lambda (id entry)
               (when (> (- now (car entry)) nelisp-dev-gc--ttl)
                 (remhash id nelisp-dev-gc--snapshots)
                 (setq removed (1+ removed))))
             nelisp-dev-gc--snapshots)
    removed))
(defun nelisp-dev-gc--put (record)
  (nelisp-dev-gc--purge-expired)
  (when (< (hash-table-count nelisp-dev-gc--snapshots) nelisp-dev-gc--limit)
    (let (id)
      (while (or (null (setq id (format "gc-%x" (random most-positive-fixnum))))
                 (gethash id nelisp-dev-gc--snapshots)))
      (puthash id (cons (float-time) record) nelisp-dev-gc--snapshots)
      id)))
(defun nelisp-dev-gc--valid-entry (id context)
  (let ((entry (gethash id nelisp-dev-gc--snapshots)))
    (when (and entry (> (- (float-time) (car entry)) nelisp-dev-gc--ttl))
      (remhash id nelisp-dev-gc--snapshots)
      (setq entry nil))
    (when (and entry
               (equal (plist-get (cdr entry) :session-id)
                      (or (plist-get context :session-id) "host-session")))
      (cdr entry))))
(defun nelisp-dev-gc-clear (&optional session)
  "Clear retained GC snapshots, optionally only for SESSION; return count."
  (let ((removed 0))
    (maphash (lambda (id entry)
               (when (or (null session)
                         (equal session (plist-get (cdr entry) :session-id)))
                 (remhash id nelisp-dev-gc--snapshots)
                 (setq removed (1+ removed))))
             nelisp-dev-gc--snapshots)
    (if session (remhash session nelisp-dev-gc--epochs)
      (clrhash nelisp-dev-gc--epochs))
    removed))
(defun nelisp-dev-gc--cumulative-delta (delta)
  "Keep only counters whose subtraction has a documented meaning."
  (let ((raw (plist-get delta :raw)) (debug (plist-get delta :debug)))
    (let ((keep (lambda (plist)
                  (let (out)
                    (dolist (key '(:collections :allocated-total
                                   :reclaimed-bytes :reclaimed-chunks))
                      (when (plist-member plist key)
                        (setq out (plist-put out key (plist-get plist key)))))
                    out))))
      (list :raw (list :gc-stats (funcall keep (plist-get raw :gc-stats)))
            :debug (funcall keep debug)))))
(defun nelisp-dev-gc--monotonic-p (before after)
  "Refuse reversed samples and counter resets, rather than negative totals."
  (let ((known nil) (valid t))
    (dolist (path '((:raw :gc-stats :collections) (:raw :gc-stats :allocated-total)
                    (:debug :reclaimed-bytes) (:debug :reclaimed-chunks)))
      (let ((a (plist-get before :snapshot)) (b (plist-get after :snapshot)))
        (dolist (key path) (setq a (plist-get a key) b (plist-get b key)))
        (when (and (numberp a) (numberp b))
          (setq known t)
          (when (< b a) (setq valid nil)))))
    (and known valid)))
(defun nelisp-dev-gc-dispatch (request context)
  "Dispatch gc.snapshot, explicit gc.collect, or gc.compare."
  (let ((op (cdr (assoc "operation" request)))
        (id (cdr (assoc "request_id" request))))
    (cond
     ((equal op "gc.snapshot")
      (let* ((record (nelisp-dev-gc--snapshot context))
             (sid (nelisp-dev-gc--put record)))
        (nelisp-dev-protocol-envelope
         op id (cond ((null sid) "failed")
                     ((and (eq (plist-get record :abi) :available)
                           (integerp (plist-get record :generation))) "ok")
                     ((eq (plist-get record :abi) :available) "inconclusive")
                     (t "unsupported")) nil nil []
         (and sid (list (cons "snapshot_id" sid)
                        (cons "snapshot" (nelisp-dev-gc--wire record))))
         (if sid ["Binary identity is unknown; snapshot allocation is not atomic."
                  "Unavailable native measurements are not inferred from host counters."]
           ["snapshot store is full"]))))
     ((equal op "gc.collect")
      (let ((pre (nelisp-dev-gc--snapshot context)))
      (if (or (not (stringp (plist-get context :session-id)))
              (not (member (plist-get context :target)
                           '("native-linux-x86_64" "normal-standalone")))
              (null (plist-get pre :generation))
              (not (eq (plist-get pre :abi) :available)))
          (nelisp-dev-protocol-envelope op id "unsupported" nil nil [] nil
                                        ["host target does not expose an explicit DEV collector"])
        (let* ((result (nelisp-repl-gc-collect))
               (before (nelisp-dev-gc--annotate context (plist-get result :before)))
               (after (nelisp-dev-gc--annotate context (plist-get result :after)))
               (status (cond
                        ((eq (plist-get result :collector-result) :unavailable)
                         "unsupported")
                        ((equal (plist-get pre :generation)
                                (plist-get after :generation)) "ok")
                        (t "inconclusive"))))
          (nelisp-dev-protocol-envelope
           op id status nil nil []
           (list (cons "mutating" t)
                 (cons "before" (nelisp-dev-gc--wire before))
                 (cons "after" (nelisp-dev-gc--wire after))
                 (cons "collector_result"
                       (nelisp-dev-gc--wire (plist-get result :collector-result)))) [])))))
     ((equal op "gc.compare")
      (let* ((args (cdr (assoc "arguments" request)))
             (a (nelisp-dev-gc--valid-entry (cdr (assoc "before" args)) context))
             (b (nelisp-dev-gc--valid-entry (cdr (assoc "after" args)) context)))
        (if (or (null a) (null b) (null (plist-get a :generation))
                (null (plist-get b :generation))
                (not (eq (plist-get a :abi) :available))
                (not (eq (plist-get b :abi) :available))
                (not (eq (plist-get a :reload-status) 'ready))
                (not (eq (plist-get b :reload-status) 'ready))
                (not (nelisp-dev-gc--monotonic-p a b))
                (not (equal (plist-get a :epoch) (plist-get b :epoch)))
                (not (equal (plist-get a :generation) (plist-get b :generation))))
            (nelisp-dev-protocol-envelope op id "inconclusive" nil nil [] nil
                                          ["unknown or cross-epoch GC identity"])
          (nelisp-dev-protocol-envelope
           op id "ok" nil nil []
           (list
            (cons "delta"
                  (nelisp-dev-gc--wire
                   (nelisp-dev-gc--cumulative-delta
                    (nelisp-repl-gc-compare
                     (plist-get a :snapshot)
                     (plist-get b :snapshot))))))
           []))))
     (t nil))))
(provide 'nelisp-dev-gc)
