;;; nelisp-stdlib-search.el --- Sweep 9 G3 list search  -*- lexical-binding: t; -*-

(defun memq (elt list)
  (let ((found nil))
    (while (and list (not found))
      (if (eq elt (car list))
          (setq found list)
        (setq list (cdr list))))
    found))

(defun member (elt list)
  (let ((found nil))
    (cond
     ((stringp elt)
      (while (and list (not found))
        (let ((x (car list)))
          (if (and (stringp x) (string= elt x))
              (setq found list)
            (setq list (cdr list))))))
     ((symbolp elt)
      (while (and list (not found))
        (if (eq elt (car list))
            (setq found list)
          (setq list (cdr list)))))
     ((numberp elt)
      (while (and list (not found))
        (let ((x (car list)))
          (if (and (numberp x) (= elt x))
              (setq found list)
            (setq list (cdr list))))))
     (t
      (while (and list (not found))
        (if (equal elt (car list))
            (setq found list)
          (setq list (cdr list))))))
    found))

(defun assq (key alist)
  (let ((found nil))
    (while (and alist (not found))
      (let ((pair (car alist)))
        (if (and (consp pair) (eq (car pair) key))
            (setq found pair)
          (setq alist (cdr alist)))))
    found))

(defun assoc (key alist &optional testfn)
  (let ((found nil))
    (cond
     (testfn
      (while (and alist (not found))
        (let ((pair (car alist)))
          (if (and (consp pair) (funcall testfn (car pair) key))
              (setq found pair)
            (setq alist (cdr alist))))))
     ((stringp key)
      (while (and alist (not found))
        (let ((pair (car alist)))
          (if (and (consp pair)
                   (stringp (car pair))
                   (string= (car pair) key))
              (setq found pair)
            (setq alist (cdr alist))))))
     ((symbolp key)
      (while (and alist (not found))
        (let ((pair (car alist)))
          (if (and (consp pair) (eq (car pair) key))
              (setq found pair)
            (setq alist (cdr alist))))))
     ((numberp key)
      (while (and alist (not found))
        (let ((pair (car alist)))
          (if (and (consp pair)
                   (numberp (car pair))
                   (= (car pair) key))
              (setq found pair)
            (setq alist (cdr alist))))))
     (t
      (while (and alist (not found))
        (let ((pair (car alist)))
          (if (and (consp pair) (equal (car pair) key))
              (setq found pair)
            (setq alist (cdr alist)))))))
    found))

;; nelisp-stdlib-search.el ends here
