;;; nelisp-native-pe-symbols.el --- Final PE symbol ownership -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'cl-lib)
(defun nelisp-native-pe-symbols-u (bytes offset width)
  "Read a bounded little-endian field."
  (unless (<= 0 offset (+ offset width) (length bytes)) (error "PE field bounds"))
  (let ((value 0))
    (dotimes (index width value)
      (setq value (+ value (ash (aref bytes (+ offset index)) (* 8 index)))))))
(defun nelisp-native-pe-symbols-put (bytes offset width value)
  (dotimes (index width) (aset bytes (+ offset index) (logand 255 (ash value (- (* 8 index)))))))

(defun nelisp-native-pe-symbols-sections (read-window &optional live-base)
  "Decode actual PE32+ x64 sections via READ-WINDOW, never a metadata map."
  (let* ((dos (funcall read-window 0 64))
         (nt (nelisp-native-pe-symbols-u dos 60 4))
         (_bound (unless (and (equal (substring dos 0 2) "MZ") (<= 64 nt 1048576))
                   (error "PE DOS domain")))
         (header (funcall read-window nt 264))
         (count (nelisp-native-pe-symbols-u header 6 2))
         (optional (nelisp-native-pe-symbols-u header 20 2))
         (base (nelisp-native-pe-symbols-u header 48 8)) sections)
    (unless (and (equal (substring header 0 4) (unibyte-string 80 69 0 0))
                 (= (nelisp-native-pe-symbols-u header 4 2) #x8664)
                 (= (nelisp-native-pe-symbols-u header 24 2) #x20b)
                 (= optional 240) (<= 1 count 16)
                 (or (null live-base) (= base live-base)))
      (error "PE Win64 domain/base rejected"))
    (let ((table (funcall read-window (+ nt 24 optional) (* count 40))))
      (dotimes (index count)
        (let* ((offset (* index 40))
               (flags (nelisp-native-pe-symbols-u table (+ offset 36) 4))
               (rva (nelisp-native-pe-symbols-u table (+ offset 12) 4))
               (size (nelisp-native-pe-symbols-u table (+ offset 8) 4)))
          (unless (and (> size 0) (< (+ rva size) 134217728)) (error "PE section bound"))
          (push (list :type (if (/= 0 (logand flags #x80000000)) 8 1)
                      :flags (logior 2 (if (/= 0 (logand flags #x20000000)) 4 0)
                                     (if (/= 0 (logand flags #x80000000)) 1 0))
                      :address (+ base rva) :offset (nelisp-native-pe-symbols-u table (+ offset 20) 4)
                      :size size :raw-size (nelisp-native-pe-symbols-u table (+ offset 16) 4)) sections))))
    (list (vconcat (nreverse sections)) header)))

(defun nelisp-native-pe-symbols-read (read-window &optional live-base)
  "Read bounded COFF symbols from the actual PE, returning ELF-shaped records."
  (let* ((decoded (nelisp-native-pe-symbols-sections read-window live-base))
         (sections (car decoded)) (header (cadr decoded))
         (offset (nelisp-native-pe-symbols-u header 12 4))
         (count (nelisp-native-pe-symbols-u header 16 4))
         (symbols (make-hash-table :test #'equal)))
    (unless (and (> offset 0) (<= 1 count 20000)) (error "PE symbol table bound"))
    (let* ((entries (funcall read-window offset (* count 18)))
           (string-offset (+ offset (* count 18)))
           (size (nelisp-native-pe-symbols-u (funcall read-window string-offset 4) 0 4))
           (_bound (unless (<= 4 size 1048576) (error "PE strings bound")))
           (strings (funcall read-window string-offset size)))
      (dotimes (index count)
        (let* ((entry (* index 18))
               (section (nelisp-native-pe-symbols-u entries (+ entry 12) 2))
               (name-offset (nelisp-native-pe-symbols-u entries (+ entry 4) 4))
               (name (if (= 0 (nelisp-native-pe-symbols-u entries entry 4))
                         (progn
                           (unless (<= 4 name-offset (1- size)) (error "PE name offset"))
                           (let ((end (cl-position 0 strings :start name-offset)))
                             (unless (and end (<= (- end name-offset) 256)) (error "PE name bound"))
                             (substring strings name-offset end)))
                       (let ((end (or (cl-position 0 entries :start entry :end (+ entry 8)) (+ entry 8))))
                         (substring entries entry end)))))
          (unless (and (<= 1 section (length sections))
                       (= 0 (aref entries (+ entry 17))) (not (gethash name symbols)))
            (error "PE symbol ownership/auxiliary rejected"))
          (let* ((sec (aref sections (1- section)))
                 (value (nelisp-native-pe-symbols-u entries (+ entry 8) 4)))
            (unless (< value (plist-get sec :size)) (error "PE symbol outside section"))
            (puthash name (list :address (+ (plist-get sec :address) value)
                               :section (1- section)
                               :type (if (= #x20 (nelisp-native-pe-symbols-u entries (+ entry 14) 2)) 2 1)) symbols)))))
    (list sections symbols)))

(defun nelisp-native-pe-symbols-append (path symtab)
  "Append the final linker's COFF ownership table to the actual PE PATH."
  (let* ((bytes (with-temp-buffer (set-buffer-multibyte nil)
                                (insert-file-contents-literally path) (buffer-string)))
         (read-window (lambda (offset size) (substring bytes offset (+ offset size))))
         (sections (car (nelisp-native-pe-symbols-sections read-window)))
         (nt (nelisp-native-pe-symbols-u bytes 60 4))
         (strings (unibyte-string 0 0 0 0)) entries names)
    (maphash (lambda (name _symbol) (push name names)) symtab)
    (dolist (name (sort names #'string<))
      (let* ((symbol (gethash name symtab)) (address (plist-get symbol :value))
             (index 0) (section nil))
        (while (and (< index (length sections)) (null section))
          (let ((sec (aref sections index)))
            (when (<= (plist-get sec :address) address (1- (+ (plist-get sec :address) (plist-get sec :size))))
              (setq section index)))
          (setq index (1+ index)))
        (when section
          (let ((entry (make-string 18 0)) (encoded (encode-coding-string name 'utf-8)))
            (unless (<= 1 (length encoded) 256) (error "PE linker name bound"))
            (nelisp-native-pe-symbols-put entry 4 4 (length strings))
            (nelisp-native-pe-symbols-put entry 8 4 (- address (plist-get (aref sections section) :address)))
            (nelisp-native-pe-symbols-put entry 12 2 (1+ section))
            (nelisp-native-pe-symbols-put entry 14 2 (if (eq (plist-get symbol :type) 'func) #x20 0))
            (aset entry 16 2)
            (push entry entries)
            (setq strings (concat strings encoded (unibyte-string 0)))))))
    (unless (<= 1 (length entries) 20000) (error "PE linker symbol count"))
    (nelisp-native-pe-symbols-put bytes (+ nt 12) 4 (length bytes))
    (nelisp-native-pe-symbols-put bytes (+ nt 16) 4 (length entries))
    (nelisp-native-pe-symbols-put strings 0 4 (length strings))
    (let ((coding-system-for-write 'no-conversion))
      (write-region (concat bytes (apply #'concat (nreverse entries)) strings) nil path nil 'silent))))
(provide 'nelisp-native-pe-symbols)

(defun nelisp-native-pe-symbols-imports (read-window sections)
  "Decode kernel import names and their actual IAT RVAs from PE bytes."
  (let* ((dos (funcall read-window 0 64))
         (nt (nelisp-native-pe-symbols-u dos 60 4))
         (header (funcall read-window nt 264))
         (base (nelisp-native-pe-symbols-u header 48 8))
         (rva (nelisp-native-pe-symbols-u header 144 4))
         (size (nelisp-native-pe-symbols-u header 148 4))
         (windows (make-hash-table :test #'equal)) result)
    (cl-labels
        ((at (rva length)
           (let ((section (cl-find-if
                           (lambda (sec) (<= (- (plist-get sec :address) base) rva
                                             (- (+ (- (plist-get sec :address) base)
                                                   (plist-get sec :raw-size)) length)))
                           (append sections nil))))
             (unless section (error "PE import RVA bound"))
             (let* ((start (plist-get section :offset))
                    (offset (- (+ base rva) (plist-get section :address)))
                    (span (plist-get section :raw-size)))
               ;; Cache the bounded import section within this verification only.
               ;; Avoid a fresh file handle and scratch mapping for every name byte.
               (if (<= span 1048576)
                   (let ((bytes (or (gethash start windows)
                                    (let ((value (funcall read-window start span)))
                                      (unless (= (length value) span) (error "PE import window truncated"))
                                      (puthash start value windows) value))))
                     (substring bytes offset (+ offset length)))
                 (funcall read-window (+ start offset) length)))))
         (name-at (rva)
           (let ((bytes (at rva 1)) (index 0))
             (while (and (< index 256) (/= (aref bytes (1- (length bytes))) 0))
               (setq index (1+ index) bytes (concat bytes (at (+ rva index) 1))))
             (unless (< index 256) (error "PE import name bound"))
             (substring bytes 0 -1))))
      (unless (and (> rva 0) (<= 20 size 1048576)) (error "PE import directory bound"))
      (let ((index 0) done)
        (while (and (not done) (< (* index 20) size))
          (let* ((record (at (+ rva (* index 20)) 20))
                 (lookup (nelisp-native-pe-symbols-u record 0 4))
                 (dll-rva (nelisp-native-pe-symbols-u record 12 4))
                 (iat (nelisp-native-pe-symbols-u record 16 4)))
            (if (= dll-rva 0) (setq done t)
              (let ((dll (downcase (name-at dll-rva))) (slot 0) finished)
                (unless (and (> lookup 0) (> iat 0)) (error "PE named import owner missing"))
                (while (and (not finished) (< slot 4096))
                  (let ((hint (nelisp-native-pe-symbols-u (at (+ lookup (* slot 8)) 8) 0 8)))
                    (if (= hint 0) (setq finished t)
                      (unless (< hint #x80000000) (error "PE ordinal import refused"))
                      (push (list :name (name-at (+ hint 2)) :dll dll :address (+ base iat (* slot 8))) result)))
                  (setq slot (1+ slot)))
                (unless finished (error "PE import count bound")))))
          (setq index (1+ index)))
        (unless done (error "PE import directory unterminated"))))
    result))
