;;; nelisp-stdlib-match-state.el --- Public view of actual standalone match state -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'nelisp-bytecode-compiler-input)
(defvar nelisp-stdlib-match-state--dialect-owner
  (symbol-function 'nelisp-bytecode-compiler-input-dialect))
(defvar nelisp-stdlib-match-state--owners nil)
(defvar nelisp-stdlib-match-state--context-caps nil)
(defvar nelisp-stdlib-match-state--context-buffer nil)
(defun nelisp-stdlib-match-state--live-p ()
  "Refuse replacement of the real regex state getters captured at installation."
  (dolist (owner nelisp-stdlib-match-state--owners)
    (unless (eq (symbol-function (car owner)) (cdr owner))
      (error "Match state owner changed: %S" (car owner))))
  (unless (boundp 'nlre--last-caps) (error "Standalone match state unavailable")))
(defun nelisp-stdlib-match-state--position (value)
  (cond ((integerp value) value)
        ((markerp value) (or (marker-position value) 0))
        (t (signal 'wrong-type-argument (list 'integer-or-marker-p value)))))
(defun nelisp-stdlib-match-state--finite-list (value)
  "Validate VALUE's spine before changing capture state or caller-owned cells.
Circular REUSE is refused rather than reproducing GNU's nonterminating loop."
  (let ((slow value) (fast value))
    (while (consp fast)
      (setq fast (cdr fast))
      (when (consp fast)
        (setq fast (cdr fast) slow (cdr slow))
        (when (eq slow fast) (signal 'circular-list (list value)))))
    (when fast (signal 'wrong-type-argument (list 'listp fast))))
  value)
(defun nelisp-stdlib-match-state--set (data &optional reseat)
  "Set real NLRE capture slots from GNU match DATA, detaching markers for RESEAT."
  (nelisp-stdlib-match-state--live-p)
  (nelisp-stdlib-match-state--finite-list data)
  (let ((tail data) captures buffer)
    (while (consp tail)
      (let ((begin (car tail)))
        (setq tail (cdr tail))
        (cond
         ((and (bufferp begin) (null tail)) (setq buffer begin))
         ((consp tail)
          (let ((end (car tail)))
            (setq tail (cdr tail))
            (if (null begin)
                (push nil captures)
              (let ((start (nelisp-stdlib-match-state--position begin))
                    (finish (nelisp-stdlib-match-state--position end)))
                (when (and (markerp begin) (marker-buffer begin))
                  (setq buffer (marker-buffer begin)))
                (when (and (markerp end) (marker-buffer end))
                  (setq buffer (marker-buffer end)))
                (push (and (>= start 0) (cons start finish)) captures))))))))
    (when tail (signal 'wrong-type-argument (list 'listp tail)))
    ;; GNU ignores a final unpaired element and omits absent trailing groups.
    (while (and captures (null (car captures))) (setq captures (cdr captures)))
    (setq nlre--last-caps (and captures (vconcat (nreverse captures))))
    (setq nelisp-stdlib-match-state--context-caps nlre--last-caps
          nelisp-stdlib-match-state--context-buffer buffer)
    (when reseat
      (dolist (value data) (when (markerp value) (set-marker value nil))))
    nil))
(defun nelisp-stdlib-match-state--data (&optional integers reuse reseat)
  "Return a GNU-shaped view of the actual shared capture vector.
A buffer origin is reported only for the exact vector installed from real
markers or an explicit buffer; a subsequent regex write invalidates that view."
  (nelisp-stdlib-match-state--live-p)
  (nelisp-stdlib-match-state--finite-list reuse)
  (let ((buffer (and (eq nlre--last-caps nelisp-stdlib-match-state--context-caps)
                     nelisp-stdlib-match-state--context-buffer))
        (index 0) values)
    (while (< index (length nlre--last-caps))
      (let ((capture (aref nlre--last-caps index)))
        (push (and capture (car capture)) values)
        (push (and capture (cdr capture)) values))
      (setq index (1+ index)))
    (while (and values (null (car values)) (null (cadr values)))
      (setq values (cddr values)))
    (setq values (nreverse values))
    (when (and values buffer)
      (if integers
          (setq values (append values (list buffer)))
        (setq values (mapcar (lambda (position)
                              (and position (set-marker (make-marker) position buffer)))
                            values))))
    (if (null reuse) values
      (let ((tail reuse) (remaining values))
        (while (consp tail)
          (let ((old (car tail)) (new (car remaining)))
            (if (and (markerp old) (markerp new))
                (progn (set-marker old (marker-position new) (marker-buffer new))
                       (setcar tail old))
              (when (and reseat (markerp old)) (set-marker old nil))
              (setcar tail new)))
          (setq remaining (cdr remaining))
          (if (and remaining (null (cdr tail)))
              (progn (setcdr tail remaining) (setq tail nil remaining nil))
            (setq tail (cdr tail))))
        (when tail (signal 'wrong-type-argument (list 'listp tail)))
        reuse))))
(defun nelisp-stdlib-match-state-install ()
  "Install missing standalone match-state semantics, preserving genuine GNU hosts."
  (unless (eq (symbol-function 'nelisp-bytecode-compiler-input-dialect)
              nelisp-stdlib-match-state--dialect-owner)
    (error "Match state evidence owner changed"))
  (let ((evidence (nelisp-bytecode-compiler-input-dialect)))
    (unless (and (eq (plist-get evidence :status) 'pinned)
                 (equal (plist-get evidence :dialect) "GNU Emacs 31.1"))
      (error "Match state requires verified GNU31 dialect"))
    (if (not (eq (plist-get evidence :runtime-evidence) 'standalone-build-verified))
        'preserved
      (unless nelisp-stdlib-match-state--owners
        (unless (and (boundp 'nlre--last-caps)
                     (fboundp 'nlre-match-beginning) (fboundp 'nlre-match-end))
          (error "Real NLRE capture state unavailable"))
        (setq nelisp-stdlib-match-state--owners
              (mapcar (lambda (name) (cons name (symbol-function name)))
                      '(nlre-match-beginning nlre-match-end))))
      (nelisp-stdlib-match-state--live-p)
      (fset 'set-match-data #'nelisp-stdlib-match-state--set)
      (fset 'match-data #'nelisp-stdlib-match-state--data)
      'installed)))
(provide 'nelisp-stdlib-match-state)
