;;; nelisp-bytecode-native-rooted-cfg.el --- Bounded CFG topology -*- lexical-binding: t; -*-
;;; Code:
(require 'cl-lib)
(defconst nelisp-bytecode-native-rooted-cfg-max-blocks 256)
(defconst nelisp-bytecode-native-rooted-cfg-max-paths 256
  "Historical diagnostic bound; execution paths are not an admission limit.")
(defconst nelisp-bytecode-native-rooted-cfg-max-analysis-steps 65536)

(defun nelisp-bytecode-native-rooted-cfg-topology-check (frame)
  "Validate FRAME edges and reachability, then discover strongly connected sets.
The monotone reachability fixed point is bounded by an analysis work budget.
Existing frame transfer analysis supplies exact stack depths and effect facts."
  (let ((blocks (and (listp frame) (eq (plist-get frame :status) 'complete)
                     (plist-get frame :blocks)))
        (by-id (make-hash-table :test 'eql)) (reach (make-hash-table :test 'eql))
        (degree (make-hash-table :test 'eql)) (paths (make-hash-table :test 'eql))
        (dense-ids (make-hash-table :test 'eql))
        (order nil) (branches nil) (steps 0) (reason nil))
    (or
     (catch 'refuse
       (cl-labels ((refuse (why) (setq reason why) (throw 'refuse nil))
                   (singleton (id)
                     (let* ((index (gethash id dense-ids)) (set (make-vector 9 0)))
                       (aset set 0 (list id))
                       (aset set (1+ (/ index 32)) (ash 1 (% index 32)))
                       set))
                   (union-ids (left right)
                     ;; Each set keeps its legacy list order plus eight 32-bit
                     ;; membership words for at most 256 verified blocks.
                     ;; Preserve cl-union's longer-list selection and push
                     ;; order. Skip an already contained set in eight scalar
                     ;; operations, rather than probing each integer member.
                     (when (< (length (aref left 0)) (length (aref right 0)))
                       (let ((saved left)) (setq left right right saved)))
                     (let ((changed nil))
                       (dotimes (word 8)
                         (unless (= (logior (aref left (1+ word)) (aref right (1+ word)))
                                    (aref left (1+ word)))
                           (setq changed t)))
                       (if (not changed) left
                         (let ((result (copy-sequence left)) (ids (aref left 0)))
                           (dolist (id (aref right 0))
                             (let* ((index (gethash id dense-ids))
                                    (word (1+ (/ index 32))) (bit (ash 1 (% index 32))))
                               (when (= (logand (aref result word) bit) 0)
                                 (push id ids)
                                 (aset result word (logior (aref result word) bit)))))
                           (aset result 0 ids)
                           result)))))
         (unless (and (vectorp blocks) (> (length blocks) 0)
                      (<= (length blocks) nelisp-bytecode-native-rooted-cfg-max-blocks))
           (refuse "frame block count is outside analysis limit"))
         (dotimes (i (length blocks))
           (let* ((block (aref blocks i)) (id (and (listp block) (plist-get block :start))))
             (unless (and (integerp id) (>= id 0) (not (gethash id by-id))
                          (vectorp (plist-get block :instructions))
                          (vectorp (plist-get block :successors)))
               (refuse "duplicate or invalid block id"))
             (puthash id block by-id) (puthash id 0 degree) (puthash id 0 paths)
             (puthash id i dense-ids) (puthash id (singleton id) reach)))
         (dotimes (i (length blocks))
           (let* ((block (aref blocks i)) (id (plist-get block :start)))
             (dolist (edge (append (plist-get block :successors)
                                     (plist-get block :exceptional-successors) nil))
               (let* ((target (and (listp edge) (plist-get edge :target)))
                      (destination (gethash target by-id))
                      (slots (and (listp edge) (plist-get edge :slots)))
                      (target-slots (and (listp edge) (plist-get edge :target-slots)))
                      (depth (plist-get destination :entry-stack-depth)))
                 (unless (and destination (vectorp slots) (vectorp target-slots)
                              (= (length slots) (length target-slots))
                              (or (null depth)
                                  (and (integerp depth) (>= depth 0) (= depth (length slots))
                                       (equal target-slots
                                              (vconcat (cl-loop for j below depth
                                                                collect (list :entry target j)))))))
                   (refuse "edge target or stack-slot transfer is invalid"))
                 (puthash target (1+ (gethash target degree)) degree)
                 (puthash id (union-ids (gethash id reach) (singleton target)) reach)))
             (dolist (ins (append (plist-get block :instructions) nil))
               (unless (listp ins) (refuse "invalid instruction record"))
               (when (memq (plist-get ins :opcode) '(131 132 133 134))
                 (unless (= (length (plist-get block :successors)) 2)
                   (refuse "conditional branch lacks two successors"))
                 (push (list :pc (plist-get ins :pc) :opcode (plist-get ins :opcode)
                             :taken (if (memq (plist-get ins :opcode) '(131 133)) 'nilp 'not-nilp)) branches)))))
         (let ((changed t))
           (while changed
             (setq changed nil)
             (dotimes (i (length blocks))
               (let* ((id (plist-get (aref blocks i) :start)) (old (gethash id reach))
                      (new (copy-sequence old)))
                 (dolist (successor (aref old 0))
                   (setq steps (1+ steps))
                   (when (> steps nelisp-bytecode-native-rooted-cfg-max-analysis-steps)
                     (refuse "CFG analysis work budget exceeded"))
                   (setq new (union-ids new (gethash successor reach))))
                 (unless (= (length (aref old 0)) (length (aref new 0))) (setq changed t) (puthash id new reach))))))
         (let* ((entry (plist-get (aref blocks 0) :start)) (queue (list entry))
                (seen nil) (components nil) (assigned nil) (cyclic nil) (poll-edges nil))
           (unless (= (length (aref (gethash entry reach) 0)) (length blocks))
             (refuse "frame contains unreachable blocks"))
           ;; Prefer the legacy topological order on DAGs; cycles use source order.
           (while queue
             (let ((id (pop queue)))
               (unless (memq id seen)
                 (push id seen)
                 (setq queue (append queue (mapcar (lambda (e) (plist-get e :target))
                                                  (append (plist-get (gethash id by-id) :successors)
                                                          (plist-get (gethash id by-id) :exceptional-successors) nil)))))))
           (dotimes (i (length blocks))
             (let ((id (plist-get (aref blocks i) :start)))
               (unless (memq id assigned)
                 (let ((component (cl-remove-if-not
                                   (lambda (other) (memq id (aref (gethash other reach) 0)))
                                   (aref (gethash id reach) 0))))
                   (setq component (sort component #'<))
                   (push component components) (setq assigned (append component assigned))
                   (when (or (> (length component) 1)
                             (cl-some (lambda (e) (= (plist-get e :target) id))
                                      (append (plist-get (gethash id by-id) :successors)
                                                          (plist-get (gethash id by-id) :exceptional-successors) nil)))
                     (setq cyclic t))))))
           ;; Every directed cycle contains a DFS back edge. Poll that feedback
           ;; set, rather than expanding a callback on every SCC edge. This
           ;; also covers irreducible cycles and entry/self back edges.
           (let ((active nil) (done nil))
             (cl-labels ((visit (source)
                           (unless (memq source done)
                             (push source active)
                             (dolist (edge (append (plist-get (gethash source by-id) :successors)
                                                  (plist-get (gethash source by-id) :exceptional-successors) nil))
                               (let ((target (plist-get edge :target)))
                                 (if (memq target active)
                                     (push (cons source target) poll-edges)
                                   (visit target))))
                             (setq active (cdr active))
                             (push source done))))
               (visit entry)))
           (if cyclic (setq order (nreverse seen))
             (setq queue (list entry)) (puthash entry 1 paths)
             (while queue
               (let ((id (pop queue)))
                 (push id order)
                 (dolist (edge (append (plist-get (gethash id by-id) :successors)
                                                          (plist-get (gethash id by-id) :exceptional-successors) nil))
                   (let ((target (plist-get edge :target)))
                     (puthash target (min 257 (+ (gethash target paths) (gethash id paths))) paths)
                     (puthash target (1- (gethash target degree)) degree)
                     (when (= (gethash target degree) 0) (setq queue (append queue (list target))))))))
             (setq order (nreverse order)))
           (list :status 'complete :scope 'topology-only :block-order order
                 :branches (nreverse branches) :cyclic cyclic :sccs (nreverse components)
                 :poll-edges (nreverse poll-edges) :analysis-steps steps
                 :path-count (if cyclic 0 (cl-loop for id in order
                                                  when (= 0 (length (plist-get (gethash id by-id) :successors)))
                                                  sum (gethash id paths)))
                 :max-blocks nelisp-bytecode-native-rooted-cfg-max-blocks
                 :max-paths nelisp-bytecode-native-rooted-cfg-max-paths))))
     (list :status 'unsupported :scope 'topology-only :reason (or reason "invalid frame")))))
(provide 'nelisp-bytecode-native-rooted-cfg)
