;;; nelisp-hash-custom.el --- Lisp custom hash table tests -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
;; The standalone's native table owns storage and the standard three tests.
;; Custom tests use an ordinary Lisp scan; no handwritten native is added.
(when (and (fboundp 'nelisp--eval-source-string) (not (fboundp 'define-hash-table-test)))
  (let ((tests nil)
        (make (symbol-function 'make-hash-table))
        (lookup '(builtin gethash)) (store '(builtin puthash))
        (remove '(builtin remhash)) (scan (symbol-function 'maphash))
        (tablep (symbol-function 'hash-table-p))
        (same (symbol-function 'eq)))
    (cl-labels
        ((definition (name) (cdr (assq name tests)))
         (custom (table)
           (and (funcall tablep table) (> (length (car table)) 3) (car table)))
         (find-key (key table meta missing)
           (let ((found missing))
             (funcall (aref meta 4) key)
             (funcall scan (lambda (stored _value)
                             (when (and (funcall same found missing)
                                        (funcall (aref meta 3) stored key))
                               (setq found stored))) table)
             found)))
      (fset 'define-hash-table-test
            (lambda (name test hash)
              (let ((pair (cons (if (symbolp test) (symbol-function test) test)
                                (if (symbolp hash) (symbol-function hash) hash))))
                (setq tests (cons (cons name pair) tests))) nil))
      (fset 'make-hash-table
            (lambda (&rest keys)
              (let* ((name (plist-get keys :test)) (pair (definition name)))
                (if (not pair) (apply make keys)
                  (let* ((normalized (copy-sequence keys))
                         (_ (setq normalized (plist-put normalized :test 'equal)))
                         (table (apply make normalized)))
                    (setcar table (vector 'hash-table 0 name (car pair) (cdr pair)))
                    table)))))
      (fset 'gethash
            (lambda (key table &optional default)
              (let ((meta (custom table)))
                (if (not meta) (funcall lookup key table default)
                  (let* ((missing (cons nil nil)) (stored (find-key key table meta missing)))
                    (if (funcall same stored missing) default (funcall lookup stored table default)))))))
      (fset 'puthash
            (lambda (key value table)
              (let ((meta (custom table)))
                (if (not meta) (funcall store key value table)
                  (let* ((missing (cons nil nil)) (stored (find-key key table meta missing)))
                    (funcall store (if (funcall same stored missing) key stored) value table))))))
      (fset 'remhash
            (lambda (key table)
              (let ((meta (custom table)))
                (if (not meta) (funcall remove key table)
                  (let* ((missing (cons nil nil)) (stored (find-key key table meta missing)))
                    (unless (funcall same stored missing) (funcall remove stored table))))))))))
(provide 'nelisp-hash-custom)
