;;; 11-phase5-gap-audit.data.el --- raw audit output -*- lexical-binding: t; -*-
;;
;; Generated: 2026-04-24 14:49:11+0900
;; Host subr count: 5646
;; NeLisp-referenced subrs: 118
;; Scope files: 13
;;
;;; Code:

(defconst nelisp-gap-audit-data
  '(
    (quote :arity (1 . unevalled) :ref-count 489 :sites (("src/nelisp-actor.el" . 1) ("src/nelisp-actor.el" . 39) ("src/nelisp-actor.el" . 40)))
    (list :arity (0 . many) :ref-count 341 :sites (("src/nelisp-actor.el" . 267) ("src/nelisp-actor.el" . 308) ("src/nelisp-actor.el" . 308)))
    (let :arity (1 . unevalled) :ref-count 294 :sites (("src/nelisp-actor.el" . 104) ("src/nelisp-actor.el" . 116) ("src/nelisp-actor.el" . 123)))
    (setq :arity (0 . unevalled) :ref-count 184 :sites (("src/nelisp-actor.el" . 104) ("src/nelisp-actor.el" . 104) ("src/nelisp-actor.el" . 116)))
    (signal :arity (2 . 2) :ref-count 167 :sites (("src/nelisp-actor.el" . 267) ("src/nelisp-actor.el" . 308) ("src/nelisp-actor.el" . 308)))
    (car :arity (1 . 1) :ref-count 142 :sites (("src/nelisp-actor.el" . 131) ("src/nelisp-actor.el" . 167) ("src/nelisp-actor.el" . 545)))
    (cdr :arity (1 . 1) :ref-count 138 :sites (("src/nelisp-actor.el" . 131) ("src/nelisp-actor.el" . 131) ("src/nelisp-actor.el" . 167)))
    (cond :arity (0 . unevalled) :ref-count 101 :sites (("src/nelisp-actor.el" . 167) ("src/nelisp-actor.el" . 351) ("src/nelisp-actor.el" . 545)))
    (nth :arity (2 . 2) :ref-count 100 :sites (("src/nelisp-actor.el" . 449) ("src/nelisp-bytecode.el" . 68) ("src/nelisp-bytecode.el" . 70)))
    (cons :arity (2 . 2) :ref-count 95 :sites (("src/nelisp-actor.el" . 545) ("src/nelisp-bytecode.el" . 326) ("src/nelisp-bytecode.el" . 352)))
    (let* :arity (1 . unevalled) :ref-count 64 :sites (("src/nelisp-actor.el" . 167) ("src/nelisp-actor.el" . 267) ("src/nelisp-actor.el" . 449)))
    (if :arity (2 . unevalled) :ref-count 62 :sites (("src/nelisp-actor.el" . 104) ("src/nelisp-actor.el" . 123) ("src/nelisp-bytecode.el" . 728)))
    (defconst :arity (2 . unevalled) :ref-count 59 :sites (("src/nelisp-bytecode.el" . 75) ("src/nelisp-bytecode.el" . 212) ("src/nelisp-bytecode.el" . 218)))
    (1+ :arity (1 . 1) :ref-count 58 :sites (("src/nelisp-bytecode.el" . 352) ("src/nelisp-bytecode.el" . 352) ("src/nelisp-bytecode.el" . 941)))
    (aref :arity (2 . 2) :ref-count 56 :sites (("src/nelisp-actor.el" . 167) ("src/nelisp-bytecode.el" . 1323) ("src/nelisp-bytecode.el" . 1323)))
    (cadr :arity (1 . 1) :ref-count 55 :sites (("src/nelisp-bytecode.el" . 352) ("src/nelisp-bytecode.el" . 393) ("src/nelisp-bytecode.el" . 393)))
    (eq :arity (2 . 2) :ref-count 52 :sites (("src/nelisp-actor.el" . 308) ("src/nelisp-actor.el" . 383) ("src/nelisp-actor.el" . 449)))
    (puthash :arity (3 . 3) :ref-count 47 :sites (("src/nelisp-actor.el" . 167) ("src/nelisp-actor.el" . 167) ("src/nelisp-actor.el" . 167)))
    (- :arity (0 . many) :ref-count 42 :sites (("src/nelisp-bytecode.el" . 606) ("src/nelisp-bytecode.el" . 659) ("src/nelisp-bytecode.el" . 821)))
    (1- :arity (1 . 1) :ref-count 41 :sites (("src/nelisp-bytecode.el" . 1323) ("src/nelisp-bytecode.el" . 1323) ("src/nelisp-bytecode.el" . 1323)))
    (aset :arity (3 . 3) :ref-count 41 :sites (("src/nelisp-actor.el" . 167) ("src/nelisp-bytecode.el" . 187) ("src/nelisp-bytecode.el" . 187)))
    (function :arity (1 . unevalled) :ref-count 41 :sites (("src/nelisp-actor.el" . 409) ("src/nelisp-bytecode.el" . 1120) ("src/nelisp-bytecode.el" . 1120)))
    (while :arity (1 . unevalled) :ref-count 36 :sites (("src/nelisp-actor.el" . 237) ("src/nelisp-actor.el" . 383) ("src/nelisp-actor.el" . 449)))
    (< :arity (1 . many) :ref-count 34 :sites (("src/nelisp-bytecode.el" . 476) ("src/nelisp-bytecode.el" . 533) ("src/nelisp-bytecode.el" . 606)))
    (and :arity (0 . unevalled) :ref-count 33 :sites (("src/nelisp-actor.el" . 335) ("src/nelisp-actor.el" . 449) ("src/nelisp-actor.el" . 545)))
    (plist-get :arity (2 . 3) :ref-count 32 :sites (("src/nelisp-actor.el" . 449) ("src/nelisp-actor.el" . 449) ("src/nelisp-actor.el" . 449)))
    (cddr :arity (1 . 1) :ref-count 29 :sites (("src/nelisp-bytecode.el" . 393) ("src/nelisp-bytecode.el" . 393) ("src/nelisp-bytecode.el" . 393)))
    (or :arity (0 . unevalled) :ref-count 27 :sites (("src/nelisp-actor.el" . 141) ("src/nelisp-actor.el" . 449) ("src/nelisp-bytecode.el" . 206)))
    (> :arity (1 . many) :ref-count 25 :sites (("src/nelisp-bytecode.el" . 318) ("src/nelisp-bytecode.el" . 339) ("src/nelisp-bytecode.el" . 476)))
    (require :arity (1 . 3) :ref-count 24 :sites (("src/nelisp-actor.el" . 1) ("src/nelisp-actor.el" . 39) ("src/nelisp-actor.el" . 40)))
    (defvar :arity (1 . unevalled) :ref-count 22 :sites (("src/nelisp-actor.el" . 64) ("src/nelisp-actor.el" . 71) ("src/nelisp-actor.el" . 76)))
    (nreverse :arity (1 . 1) :ref-count 21 :sites (("src/nelisp-actor.el" . 449) ("src/nelisp-bytecode.el" . 352) ("src/nelisp-bytecode.el" . 1044)))
    (consp :arity (1 . 1) :ref-count 19 :sites (("src/nelisp-actor.el" . 141) ("src/nelisp-bytecode.el" . 58) ("src/nelisp-bytecode.el" . 393)))
    (throw :arity (2 . 2) :ref-count 19 :sites (("src/nelisp-bytecode.el" . 1270) ("src/nelisp-bytecode.el" . 1323) ("src/nelisp-bytecode.el" . 1323)))
    (>= :arity (1 . many) :ref-count 18 :sites (("src/nelisp-bytecode.el" . 1323) ("src/nelisp-bytecode.el" . 1323) ("src/nelisp-bytecode.el" . 1323)))
    (catch :arity (1 . unevalled) :ref-count 18 :sites (("src/nelisp-bytecode.el" . 1270) ("src/nelisp-bytecode.el" . 1323) ("src/nelisp-bytecode.el" . 1323)))
    (gethash :arity (2 . 3) :ref-count 18 :sites (("src/nelisp-actor.el" . 167) ("src/nelisp-bytecode.el" . 313) ("src/nelisp-bytecode.el" . 1323)))
    (message :arity (1 . many) :ref-count 18 :sites (("src/nelisp-actor.el" . 398) ("src/nelisp-gc.el" . 174) ("src/nelisp-gc.el" . 196)))
    (not :arity (1 . 1) :ref-count 17 :sites (("src/nelisp-actor.el" . 141) ("src/nelisp-actor.el" . 335) ("src/nelisp-actor.el" . 545)))
    (<= :arity (1 . many) :ref-count 16 :sites (("src/nelisp-bytecode.el" . 1323) ("src/nelisp-bytecode.el" . 1323) ("src/nelisp-bytecode.el" . 1323)))
    (append :arity (0 . many) :ref-count 16 :sites (("src/nelisp-actor.el" . 545) ("src/nelisp-actor.el" . 545) ("src/nelisp-actor.el" . 545)))
    (length :arity (1 . 1) :ref-count 16 :sites (("src/nelisp-actor.el" . 435) ("src/nelisp-bytecode.el" . 352) ("src/nelisp-bytecode.el" . 606)))
    (mapcar :arity (2 . 2) :ref-count 15 :sites (("src/nelisp-bytecode.el" . 1120) ("src/nelisp-bytecode.el" . 1120) ("src/nelisp-eval.el" . 511)))
    (symbolp :arity (1 . 1) :ref-count 15 :sites (("src/nelisp-bytecode.el" . 533) ("src/nelisp-bytecode.el" . 941) ("src/nelisp-bytecode.el" . 1044)))
    (apply :arity (1 . many) :ref-count 13 :sites (("src/nelisp-bytecode.el" . 1120) ("src/nelisp-bytecode.el" . 1286) ("src/nelisp-bytecode.el" . 1771)))
    (memq :arity (2 . 2) :ref-count 13 :sites (("src/nelisp-actor.el" . 104) ("src/nelisp-actor.el" . 308) ("src/nelisp-actor.el" . 335)))
    (provide :arity (1 . 2) :ref-count 13 :sites (("src/nelisp-actor.el" . 678) ("src/nelisp-bytecode.el" . 1842) ("src/nelisp-eval.el" . 824)))
    (null :arity (1 . 1) :ref-count 12 :sites (("src/nelisp-actor.el" . 237) ("src/nelisp-actor.el" . 545) ("src/nelisp-actor.el" . 545)))
    (progn :arity (0 . unevalled) :ref-count 12 :sites (("src/nelisp-actor.el" . 237) ("src/nelisp-actor.el" . 619) ("src/nelisp-actor.el" . 638)))
    (+ :arity (0 . many) :ref-count 11 :sites (("src/nelisp-bytecode.el" . 352) ("src/nelisp-bytecode.el" . 606) ("src/nelisp-bytecode.el" . 1092)))
    (unwind-protect :arity (1 . unevalled) :ref-count 11 :sites (("src/nelisp-bytecode.el" . 606) ("src/nelisp-bytecode.el" . 659) ("src/nelisp-bytecode.el" . 941)))
    (condition-case :arity (2 . unevalled) :ref-count 9 :sites (("src/nelisp-actor.el" . 351) ("src/nelisp-actor.el" . 398) ("src/nelisp-bytecode.el" . 1247)))
    (define-error :arity (2 . 3) :ref-count 9 :sites (("src/nelisp-actor.el" . 41) ("src/nelisp-bytecode.el" . 54) ("src/nelisp-bytecode.el" . 56)))
    (= :arity (1 . many) :ref-count 8 :sites (("src/nelisp-bytecode.el" . 772) ("src/nelisp-bytecode.el" . 772) ("src/nelisp-bytecode.el" . 772)))
    (make-hash-table :arity (0 . many) :ref-count 8 :sites (("src/nelisp-actor.el" . 64) ("src/nelisp-actor.el" . 209) ("src/nelisp-eval.el" . 106)))
    (error :arity (0 . many) :ref-count 7 :sites (("src/nelisp-actor.el" . 351) ("src/nelisp-actor.el" . 398) ("src/nelisp-bytecode.el" . 1323)))
    (intern :arity (1 . 2) :ref-count 7 :sites (("src/nelisp-actor.el" . 97) ("src/nelisp-read.el" . 74) ("src/nelisp-read.el" . 83)))
    (remhash :arity (2 . 2) :ref-count 7 :sites (("src/nelisp-bytecode.el" . 1323) ("src/nelisp-bytecode.el" . 1323) ("src/nelisp-bytecode.el" . 1771)))
    (clrhash :arity (1 . 1) :ref-count 6 :sites (("src/nelisp-actor.el" . 667) ("src/nelisp-eval.el" . 811) ("src/nelisp-eval.el" . 811)))
    (funcall :arity (1 . many) :ref-count 6 :sites (("src/nelisp-actor.el" . 267) ("src/nelisp-eval.el" . 138) ("src/nelisp-gc.el" . 174)))
    (interactive :arity (0 . unevalled) :ref-count 6 :sites (("src/nelisp-actor.el" . 409) ("src/nelisp-actor.el" . 419) ("src/nelisp-gc.el" . 227)))
    (maphash :arity (2 . 2) :ref-count 6 :sites (("src/nelisp-actor.el" . 167) ("src/nelisp-actor.el" . 426) ("src/nelisp-actor.el" . 516)))
    (max :arity (1 . many) :ref-count 6 :sites (("src/nelisp-bytecode.el" . 1120) ("src/nelisp-bytecode.el" . 1286) ("src/nelisp-bytecode.el" . 1771)))
    (setcdr :arity (2 . 2) :ref-count 6 :sites (("src/nelisp-actor.el" . 104) ("src/nelisp-actor.el" . 123) ("src/nelisp-actor.el" . 167)))
    (float-time :arity (0 . 1) :ref-count 5 :sites (("bench/nelisp-actor-bench.el" . 22) ("bench/nelisp-actor-bench.el" . 39) ("bench/nelisp-actor-bench.el" . 70)))
    (keywordp :arity (1 . 1) :ref-count 5 :sites (("src/nelisp-bytecode.el" . 299) ("src/nelisp-bytecode.el" . 533) ("src/nelisp-bytecode.el" . 592)))
    (stringp :arity (1 . 1) :ref-count 5 :sites (("src/nelisp-actor.el" . 141) ("src/nelisp-bytecode.el" . 299) ("src/nelisp-read.el" . 446)))
    (assq :arity (2 . 2) :ref-count 4 :sites (("src/nelisp-bytecode.el" . 533) ("src/nelisp-eval.el" . 420) ("src/nelisp-macro.el" . 233)))
    (format :arity (1 . many) :ref-count 4 :sites (("src/nelisp-actor.el" . 97) ("bench/nelisp-gc-bench.el" . 22) ("bench/nelisp-gc-bench.el" . 22)))
    (make-vector :arity (2 . 2) :ref-count 4 :sites (("src/nelisp-actor.el" . 167) ("src/nelisp-bytecode.el" . 187) ("src/nelisp-bytecode.el" . 187)))
    (nthcdr :arity (2 . 2) :ref-count 4 :sites (("src/nelisp-bytecode.el" . 393) ("src/nelisp-bytecode.el" . 393) ("src/nelisp-bytecode.el" . 1092)))
    (vector :arity (0 . many) :ref-count 4 :sites (("src/nelisp-bytecode.el" . 1120) ("src/nelisp-bytecode.el" . 1286) ("src/nelisp-bytecode.el" . 1771)))
    (zerop :arity (1 . 1) :ref-count 4 :sites (("src/nelisp-bytecode.el" . 1323) ("src/nelisp-read.el" . 340) ("bench/nelisp-bench.el" . 81)))
    (caddr :arity (1 . 1) :ref-count 3 :sites (("src/nelisp-macro.el" . 153) ("src/nelisp-macro.el" . 203) ("src/nelisp-tramp.el" . 58)))
    (fboundp :arity (1 . 1) :ref-count 3 :sites (("src/nelisp-eval.el" . 138) ("src/nelisp-eval.el" . 523) ("src/nelisp-eval.el" . 709)))
    (functionp :arity (1 . 1) :ref-count 3 :sites (("src/nelisp-actor.el" . 267) ("src/nelisp-eval.el" . 523) ("src/nelisp-gc.el" . 156)))
    (plist-put :arity (3 . 4) :ref-count 3 :sites (("src/nelisp-bytecode.el" . 187) ("src/nelisp-bytecode.el" . 352) ("src/nelisp-gc.el" . 227)))
    (* :arity (0 . many) :ref-count 2 :sites (("src/nelisp-read.el" . 250) ("bench/nelisp-bench.el" . 31)))
    (/ :arity (1 . many) :ref-count 2 :sites (("bench/nelisp-bench.el" . 81) ("bench/nelisp-bench.el" . 81)))
    (ash :arity (2 . 2) :ref-count 2 :sites (("src/nelisp-bytecode.el" . 352) ("src/nelisp-bytecode.el" . 1120)))
    (boundp :arity (1 . 1) :ref-count 2 :sites (("src/nelisp-bytecode.el" . 313) ("src/nelisp-gc.el" . 32)))
    (called-interactively-p :arity (0 . 1) :ref-count 2 :sites (("src/nelisp-gc.el" . 227) ("src/nelisp-gc.el" . 280)))
    (cdddr :arity (1 . 1) :ref-count 2 :sites (("src/nelisp-macro.el" . 153) ("src/nelisp-macro.el" . 203)))
    (current-time :arity (0 . 0) :ref-count 2 :sites (("bench/nelisp-actor-bench.el" . 39) ("bench/nelisp-actor-bench.el" . 70)))
    (equal :arity (2 . 2) :ref-count 2 :sites (("bench/nelisp-bench.el" . 81) ("bench/nelisp-bench.el" . 81)))
    (hash-table-count :arity (1 . 1) :ref-count 2 :sites (("src/nelisp-gc.el" . 133) ("bench/nelisp-gc-bench.el" . 37)))
    (identity :arity (1 . 1) :ref-count 2 :sites (("src/nelisp-eval.el" . 666) ("src/nelisp-tramp.el" . 58)))
    (logand :arity (0 . many) :ref-count 2 :sites (("src/nelisp-bytecode.el" . 352) ("src/nelisp-bytecode.el" . 352)))
    (mapconcat :arity (2 . 3) :ref-count 2 :sites (("src/nelisp-eval.el" . 666) ("src/nelisp-tramp.el" . 58)))
    (min :arity (1 . many) :ref-count 2 :sites (("bench/nelisp-bench.el" . 157) ("bench/nelisp-bench.el" . 157)))
    (substring :arity (1 . 3) :ref-count 2 :sites (("src/nelisp-read.el" . 115) ("src/nelisp-read.el" . 250)))
    (symbol-function :arity (1 . 1) :ref-count 2 :sites (("src/nelisp-eval.el" . 709) ("src/nelisp-eval.el" . 709)))
    (symbol-value :arity (1 . 1) :ref-count 2 :sites (("src/nelisp-gc.el" . 32) ("src/nelisp.el" . 45)))
    (vectorp :arity (1 . 1) :ref-count 2 :sites (("src/nelisp-actor.el" . 141) ("src/nelisp-bytecode.el" . 299)))
    (add-hook :arity (2 . 4) :ref-count 1 :sites (("src/nelisp-gc.el" . 208)))
    (advice-add :arity (3 . 4) :ref-count 1 :sites (("src/nelisp-jit.el" . 307)))
    (advice-remove :arity (2 . 2) :ref-count 1 :sites (("src/nelisp-jit.el" . 315)))
    (buffer-string :arity (0 . 0) :ref-count 1 :sites (("src/nelisp-load.el" . 53)))
    (butlast :arity (1 . 2) :ref-count 1 :sites (("src/nelisp-tramp.el" . 58)))
    (cancel-timer :arity (1 . 1) :ref-count 1 :sites (("src/nelisp-actor.el" . 419)))
    (car-safe :arity (1 . 1) :ref-count 1 :sites (("src/nelisp-gc.el" . 210)))
    (concat :arity (0 . many) :ref-count 1 :sites (("src/nelisp-read.el" . 250)))
    (file-readable-p :arity (1 . 1) :ref-count 1 :sites (("src/nelisp-load.el" . 53)))
    (float :arity (1 . 1) :ref-count 1 :sites (("src/nelisp-read.el" . 115)))
    (garbage-collect :arity (0 . 0) :ref-count 1 :sites (("bench/nelisp-bench.el" . 58)))
    (hash-table-p :arity (1 . 1) :ref-count 1 :sites (("src/nelisp-actor.el" . 141)))
    (ignore :arity (0 . many) :ref-count 1 :sites (("bench/nelisp-actor-bench.el" . 39)))
    (insert-file-contents :arity (1 . 5) :ref-count 1 :sites (("src/nelisp-load.el" . 53)))
    (integerp :arity (1 . 1) :ref-count 1 :sites (("src/nelisp-read.el" . 115)))
    (last :arity (1 . 2) :ref-count 1 :sites (("src/nelisp-tramp.el" . 58)))
    (logior :arity (0 . many) :ref-count 1 :sites (("src/nelisp-bytecode.el" . 1120)))
    (make-symbol :arity (1 . 1) :ref-count 1 :sites (("src/nelisp-eval.el" . 130)))
    (numberp :arity (1 . 1) :ref-count 1 :sites (("src/nelisp-bytecode.el" . 299)))
    (prog1 :arity (1 . unevalled) :ref-count 1 :sites (("src/nelisp-gc.el" . 169)))
    (run-with-idle-timer :arity (3 . many) :ref-count 1 :sites (("src/nelisp-actor.el" . 409)))
    (setcar :arity (2 . 2) :ref-count 1 :sites (("src/nelisp-actor.el" . 167)))
    (string :arity (0 . many) :ref-count 1 :sites (("src/nelisp-read.el" . 137)))
    (string-to-number :arity (1 . 2) :ref-count 1 :sites (("src/nelisp-read.el" . 250)))
    ))

(provide '11-phase5-gap-audit.data)
;;; 11-phase5-gap-audit.data.el ends here
