;;; gui-daily-state.el --- Read-only GUI acceptance observations -*- lexical-binding: t; -*-
;; No editing, keymap, selection or command replacements live in this observer.
(defun gui-daily-state-snapshot ()
  "Return editor state and renderer geometry, without changing editor state."
  (let* ((standalone (fboundp 'nelisp--write-stdout-bytes))
         (selected (if standalone (emacs-window-selected-window) (selected-window)))
         (windows (if standalone (emacs-window-window-list) (window-list)))
         (windows (sort windows (lambda (a b)
                                 (< (nth 1 (if standalone (emacs-window-window-edges a) (window-edges a)))
                                    (nth 1 (if standalone (emacs-window-window-edges b) (window-edges b)))))))
         (pos (if (and standalone (nelisp-gui-frontend--pure-buffer-p))
                  (nelisp-ec-point) (point)))
         (mark-pos (if (and standalone (nelisp-gui-frontend--pure-buffer-p))
                       (emacs-mouse-mark) (mark t)))
         (text (if (and standalone (nelisp-gui-frontend--pure-buffer-p))
                   (nelisp-ec-buffer-string) (buffer-string)))
         (active (and mark-pos mark-active))
         (index 0) (selected-index -1) (views nil))
    (dolist (window windows)
      (when (eq window selected) (setq selected-index index))
      (let* ((buffer (if standalone (emacs-window-window-buffer window) (window-buffer window)))
             (pure (and standalone (nelisp-ec-buffer-p buffer)))
             (edges (if standalone (emacs-window-window-edges window) (window-edges window)))
             (cw (if standalone nelisp-gui-pango-cell-width (frame-char-width)))
             (ch (if standalone nelisp-gui-pango-line-height (frame-char-height)))
             (glyphs (unless standalone
                       (with-current-buffer buffer
                         (let ((p (window-start window)) (rows 0) (items nil))
                           (while (and (< p (point-max)) (< rows 4))
                             (let ((char (char-after p)) (posn (posn-at-point p window)))
                               (when (and posn (/= char ?\n))
                                 (push `((char . ,(string char)) (row . ,rows)
                                         (x . ,(car (posn-x-y posn))) (y . ,(cdr (posn-x-y posn)))
                                         (width . ,(car (posn-object-width-height posn)))
                                         (height . ,(cdr (posn-object-width-height posn)))) items))
                               (when (= char ?\n) (setq rows (1+ rows))))
                             (setq p (1+ p)))
                           (vconcat (nreverse items))))))
             (body (if standalone (list (* cw (car edges)) (* ch (nth 1 edges)))
                     (window-body-pixel-edges window))))
        (push `((buffer . ,(if pure (nelisp-ec-buffer-name buffer) (buffer-name buffer)))
                (point . ,(if (eq window selected) pos
                            (if standalone (emacs-window-window-point window) (window-point window))))
                (start . ,(if standalone (emacs-window-window-start window) (window-start window)))
                (x . ,(car body)) (y . ,(cadr body)) (cw . ,cw) (ch . ,ch)
                (glyphs . ,glyphs)) views))
      (setq index (1+ index)))
    `((point . ,pos) (mark . ,(or mark-pos 0)) (active . ,(if active 1 0))
      (region . ,(if active (substring text (1- (min pos mark-pos)) (1- (max pos mark-pos))) ""))
      (buffer . ,(if (and standalone (nelisp-gui-frontend--pure-buffer-p))
                      (nelisp-ec-buffer-name (nelisp-ec-current-buffer)) (buffer-name)))
      (text . ,text) (selected . ,selected-index) (windows . ,(vconcat (nreverse views)))
      (minibuffer . ,(if (if standalone (> emacs-minibuffer--depth 0) (minibufferp)) 1 0))
      (input . ,(if standalone (if (> emacs-minibuffer--depth 0) (emacs-minibuffer-minibuffer-contents) "")
                  (if (minibufferp) (minibuffer-contents-no-properties) "")))
      (search_active . ,(if (if standalone emacs-isearch--active (and (boundp 'isearch-mode) isearch-mode)) 1 0))
      (search . ,(if standalone (if emacs-isearch--active emacs-isearch--query "")
                   (if (and (boundp 'isearch-mode) isearch-mode) (or isearch-string "") "")))
      (error . ,(if standalone
                    (if emacs-command-loop--last-error (prin1-to-string emacs-command-loop--last-error) "")
                  (if (get-buffer "*Backtrace*") "GNU debugger entered" "")))
      (messages . ,(if (get-buffer "*Messages*")
                       (with-current-buffer "*Messages*" (buffer-string)) "")))))

;; GNU's observer runs after real commands and during recursive readers.
;; Presentation and error diagnostics are configured only on GNU.
(unless (fboundp 'nelisp--write-stdout-bytes)
  (require 'json)
  (setq debug-on-error t)
  (defvar gui-daily-state-last nil)
  (defun gui-daily-state-observe ()
    (let ((snapshot (json-encode (gui-daily-state-snapshot))))
      (unless (equal snapshot gui-daily-state-last)
        (setq gui-daily-state-last snapshot)
        (let ((coding-system-for-write 'utf-8-unix))
          (write-region (concat snapshot "\n") nil (getenv "GNU_GUI_STATE_FILE") t 'silent)))))
  (set-frame-parameter nil 'menu-bar-lines 0)
  (set-frame-parameter nil 'tool-bar-lines 0)
  (set-frame-parameter nil 'internal-border-width 0)
  (set-frame-parameter nil 'vertical-scroll-bars nil)
  (run-with-timer 0.1 0.1 #'gui-daily-state-observe))
