;;; nelisp-native-funcall-startup-regenerate.el --- Regenerate loader provenance -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'cl-lib)
(require 'json)
(require 'nelisp-native-compiler-startup-evidence)
(let* ((root (expand-file-name ".." (file-name-directory (or load-file-name buffer-file-name))))
       (source (expand-file-name "lisp/nelisp-native-load.el" root))
       (template (expand-file-name "templates/nelisp-native-load-constructor-startup.el.in" root))
       (identity (expand-file-name "templates/nelisp-native-load-constructor-startup.el.identity.json" root))
       (owner (expand-file-name "lisp/nelisp-native-compiler-startup-evidence.el" root))
       (names '(nelisp-native-load-root-v2-addresses nelisp-native-load-root-v2-copy nelisp-native-load-raw-v2-artifact))
       (originals (nelisp-native-compiler-startup-evidence--forms source))
       (derived (nelisp-native-compiler-startup-evidence--forms template))
       (count 0))
  (cl-labels ((gate (node)
                (cond ((equal node '(nelisp-runtime-reload-contract-matches-p))
                       '(or (nelisp-runtime-reload-contract-matches-p) (manifest-runtime-p manifest)))
                      ((consp node) (cons (gate (car node)) (gate (cdr node)))) (t node)))
              (rewrite (node)
                (cond ((and (consp node) (eq (car node) 'defun) (memq (cadr node) names))
                       (setq count (1+ count))
                       (gate (cl-find (cadr node) originals :key #'cadr)))
                      ((consp node) (cons (rewrite (car node)) (rewrite (cdr node)))) (t node))))
    (setq derived (mapcar #'rewrite derived)))
  (unless (= count 3) (error "Loader regeneration definition drift"))
  (with-temp-file template
    (insert ";;; nelisp-native-compiler-constructor-loader.el --- Trusted startup publication -*- lexical-binding: t; -*-\n")
    (let ((print-length nil) (print-level nil) (print-quoted t))
      (dolist (form derived) (pp form (current-buffer)))))
  (let* ((source-hash (nelisp-native-rooted-build-evidence-source-hash source 4194304))
         (template-hash (nelisp-native-rooted-build-evidence-source-hash template 4194304))
         (json-object-type 'alist) (json-array-type 'list) (json-key-type 'symbol)
         (declaration (json-read-file identity)))
    (setf (alist-get 'source_sha256 declaration) source-hash
          (alist-get 'output_sha256 declaration) template-hash)
    (with-temp-file identity (insert (json-encode declaration) "\n"))
    ;; These literals are checked by the structural provenance consumer below.
    (with-temp-buffer
      (insert-file-contents owner)
      (goto-char (point-min))
      (let ((start (search-forward "(defun nelisp-native-compiler-startup-evidence--loader-template-valid"))
            (end (save-excursion (search-forward "(defun nelisp-native-compiler-startup-evidence--emit") (point))))
        (narrow-to-region start end)
        (goto-char (point-min))
        (let ((index 0))
          (while (re-search-forward "\"[0-9a-f]\\{64\\}\"" nil t)
            (replace-match (format "%S" (if (memq index '(0 2)) source-hash template-hash)) t t)
            (setq index (1+ index)))
          (unless (= index 4) (error "Loader provenance literal count drift")))
        (widen))
      (write-region (point-min) (point-max) owner nil 'silent))
    (load owner nil t)
    (unless (nelisp-native-compiler-startup-evidence--loader-template-valid root)
      (error "Regenerated loader failed its structural consumer"))
    (princ (format "LOADER-PROVENANCE-PASS source=%s output=%s\n" source-hash template-hash))))
