;;; c-core-case-data.el --- Generate the default GNU casing reference -*- lexical-binding: t; -*-
;; Run with GNU Emacs 31.1; output is portable Lisp data, not native code.
(unless (string-match "\\`31\\.1" emacs-version)
  (error "The casing reference must be GNU Emacs 31.1"))
(let ((character 0) (entries nil)
      (output (or (getenv "C_CORE_CASE_DATA")
                  (expand-file-name
                   "../packages/nelisp-emacs-foundation/src/emacs-cc-case-data.el"
                   (file-name-directory load-file-name)))))
  (while (< character #x110000)
    (when (or (/= character (upcase character))
              (/= character (downcase character)))
      (let ((text (char-to-string character)))
        (setq entries (cons (list character (capitalize text) (downcase text)) entries))))
    (setq character (1+ character)))
  (with-temp-file output
    (insert ";;; emacs-cc-case-data.el --- GNU 31.1 default Unicode casing data -*- lexical-binding: t; -*-\n")
    (insert ";; Generated by tools/c-core-case-data.el from GNU Emacs 31.1.\n")
    (insert "(defconst emacs-cc-case--unicode-data '\n (")
    (dolist (entry (nreverse entries))
      (prin1 entry (current-buffer))
      (insert "\n"))
    (insert "))\n(provide 'emacs-cc-case-data)\n")))
