#!/usr/bin/env bash
# Source-command evaluator substrate artifact gate for Doc 154 Stage B.
#
# This gate uses the exact source-command substrate generated by
# scripts/nelisp-standalone-build.el, without the final command dispatch.  The
# default mode proves the substrate boundary is stable and cheap to inspect.
# --heavy additionally attempts eval-only .nelc materialization through
# target/nelisp, which currently exposes the Doc 154 Stage B compiler/reader
# bottleneck.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

EMACS="${EMACS:-emacs}"
NELISP="${NELISP:-$REPO_ROOT/target/nelisp}"
BUILD=1
HEAVY=0
HEAVY_TIMEOUT_SECONDS="${NELISP_SUBSTRATE_HEAVY_TIMEOUT_SECONDS:-180}"
TMP_DIR="$(mktemp -d)"

cleanup() {
  rm -rf "$TMP_DIR"
}
trap cleanup EXIT

while [ "$#" -gt 0 ]; do
  case "$1" in
    --no-build) BUILD=0; shift ;;
    --heavy) HEAVY=1; shift ;;
    --emacs) EMACS="$2"; shift 2 ;;
    --nelisp) NELISP="$2"; shift 2 ;;
    *)
      echo "usage: $0 [--no-build] [--heavy] [--emacs EMACS] [--nelisp PATH]" >&2
      exit 2
      ;;
  esac
done

if [ "$BUILD" -eq 1 ]; then
  make standalone-reader
fi

if [ "$HEAVY" -eq 1 ] && [ ! -x "$NELISP" ]; then
  echo "substrate_gate_fail reason=missing-nelisp path=$NELISP" >&2
  exit 1
fi

if [ "$HEAVY" -eq 1 ] && ! command -v timeout >/dev/null 2>&1; then
  echo "substrate_gate_fail reason=missing-timeout-command" >&2
  exit 1
fi

FULL_SRC="$TMP_DIR/source-command-full.el"
SUBSTRATE_SRC="$TMP_DIR/source-command-substrate.el"
SUBSTRATE_ART="$SUBSTRATE_SRC.nelc"
PROFILE_SRC="$TMP_DIR/profile-smoke.el"
PROFILE_ART="$PROFILE_SRC.nelc"

run_timed() {
  local label="$1"; shift
  local out_file="$TMP_DIR/$label.out"
  local err_file="$TMP_DIR/$label.err"
  local start end rc
  start="$(date +%s%3N)"
  set +e
  "$@" >"$out_file" 2>"$err_file"
  rc=$?
  set -e
  end="$(date +%s%3N)"
  printf 'substrate_gate_result label=%s rc=%s ms=%s out=%s\n' \
    "$label" "$rc" "$((end - start))" \
    "$(tr '\n' ' ' <"$out_file" | sed 's/[[:space:]]*$//')"
  if [ "$rc" -ne 0 ]; then
    sed 's/^/substrate_gate_stderr /' "$err_file" >&2
    exit "$rc"
  fi
}

expect_out() {
  local label="$1" expected="$2"
  local actual
  actual="$(cat "$TMP_DIR/$label.out")"
  if [ "$actual" != "$expected" ]; then
    printf 'substrate_gate_fail label=%s reason=output-mismatch expected=%s actual=%s\n' \
      "$label" "$expected" "$actual" >&2
    exit 1
  fi
}

run_timed dump_sources \
  "$EMACS" -Q --batch -L lisp -L src -L scripts \
  --eval "(progn (require 'nelisp-standalone-build) (with-temp-file \"$FULL_SRC\" (insert (nelisp-standalone--artifact-source-command-cache-src))) (with-temp-file \"$SUBSTRATE_SRC\" (insert (nelisp-standalone--artifact-source-command-substrate-src))))"

full_bytes="$(wc -c <"$FULL_SRC" | tr -d ' ')"
substrate_bytes="$(wc -c <"$SUBSTRATE_SRC" | tr -d ' ')"
full_sha="$(sha256sum "$FULL_SRC" | awk '{print $1}')"
substrate_sha="$(sha256sum "$SUBSTRATE_SRC" | awk '{print $1}')"
printf 'substrate_gate_metric full_bytes=%s substrate_bytes=%s full_sha256=%s substrate_sha256=%s\n' \
  "$full_bytes" "$substrate_bytes" "$full_sha" "$substrate_sha"

if grep -q '^(if (string= (car nelisp-standalone-argv)' "$SUBSTRATE_SRC"; then
  echo "substrate_gate_fail reason=substrate-source-still-has-command-dispatch" >&2
  exit 1
fi

if ! grep -q 'nelisp-standalone-source-cache-load-artifact' "$SUBSTRATE_SRC"; then
  echo "substrate_gate_fail reason=missing-source-cache-load-artifact-helper" >&2
  exit 1
fi

cat >"$PROFILE_SRC" <<'EOF'
(defun substrate-profile-smoke (x) x)
(provide 'substrate-profile-smoke)
EOF

if [ -x "$NELISP" ]; then
  run_timed profile_smoke \
    "$NELISP" compile-elisp-artifact --kind nelc --module-policy eval-only \
    --profile-stages --profile-forms --input "$PROFILE_SRC" --output "$PROFILE_ART"
  if ! grep -q '^artifact_profile stage=read-forms ' "$TMP_DIR/profile_smoke.err"; then
    echo "substrate_gate_fail reason=missing-profile-read-forms" >&2
    exit 1
  fi
  if ! grep -q '^artifact_profile_form ' "$TMP_DIR/profile_smoke.err"; then
    echo "substrate_gate_fail reason=missing-profile-form" >&2
    exit 1
  fi
  if ! grep -q '^artifact_profile stage=total ' "$TMP_DIR/profile_smoke.err"; then
    echo "substrate_gate_fail reason=missing-profile-total" >&2
    exit 1
  fi
else
  echo "substrate_gate_result label=profile_smoke rc=77 skipped=1 reason=missing-nelisp"
fi

if [ "$HEAVY" -eq 1 ]; then
  run_timed compile_substrate_artifact_eval_only \
    timeout "$HEAVY_TIMEOUT_SECONDS" \
    "$NELISP" compile-elisp-artifact --kind nelc --module-policy eval-only \
    --input "$SUBSTRATE_SRC" --output "$SUBSTRATE_ART"

  if [ ! -f "$SUBSTRATE_ART" ] || [ ! -f "$SUBSTRATE_ART.manifest.el" ]; then
    echo "substrate_gate_fail reason=missing-substrate-artifact" >&2
    exit 1
  fi

  run_timed load_substrate_artifact \
    timeout "$HEAVY_TIMEOUT_SECONDS" \
    "$NELISP" eval-elisp-artifact "$SUBSTRATE_ART" \
    '(nelisp-standalone-source-cache--skip-ws "  x" 0)'
  expect_out load_substrate_artifact "2"

  if ! grep -q ':source' "$SUBSTRATE_ART.manifest.el"; then
    echo "substrate_gate_fail reason=manifest-missing-source-record" >&2
    exit 1
  fi
else
  echo "substrate_gate_result label=compile_substrate_artifact_eval_only rc=77 skipped=1 reason=heavy-opt-in"
fi

echo "substrate_gate_result label=source_command_substrate_gate rc=0"
