#!/usr/bin/env bash
# Which functions does GNU Emacs implement in C, and what does the standalone
# do with each of them?
#
#   tools/nelisp-c-primitive-census.sh [--bin target/nelisp] [--out FILE]
#
# Three columns per row: the name, what the standalone does with it
# (native | interpreted | absent), and a call-site score weighted towards the
# corpus we actually run (the nelisp-agent tree counts triple, vendored GNU
# Emacs Lisp counts once).  Everything is measured, nothing is declared: the
# C-primitive set comes from the host Emacs the script is run against, and the
# native set from the reader's own dispatch table.
#
# Why this exists: on 2026-09-21 eight list functions were made native after a
# hand-picked benchmark, and the obvious next question -- "which others are
# Emacs C primitives that we still interpret?" -- had no answer.  This gives
# one, and regenerates it as the work lands.
set -u
LC_ALL=C; export LC_ALL
here=$(cd "$(dirname "$0")/.." && pwd)
BIN="$here/target/nelisp"; OUT="$here/tools/nelisp-c-primitive-inventory.txt"
AGENT=${AGENT_DIR:-$(cd "$here/../nelisp-agent" 2>/dev/null && pwd || true)}
VENDOR=${VENDOR_DIR:-$here/vendor/emacs-lisp}
EMACS=${EMACS:-emacs}
while [ $# -gt 0 ]; do
  case "$1" in
    --bin) BIN=$2; shift 2;;
    --out) OUT=$2; shift 2;;
    -h|--help) sed -n '2,18p' "$0"; exit 0;;
    *) echo "unknown argument: $1" >&2; exit 2;;
  esac
done
[ -x "$BIN" ] || { echo "census: not executable: $BIN" >&2; exit 2; }
tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT

# 1. Emacs's own C primitives: subrp and not a native-compiled Lisp function.
# Special forms are excluded: they are the evaluator's own business, not
# functions anything can call, and the standalone answers `cons' or nil for
# their function cell, which is neither `subr' nor an interpreted defun.
"$EMACS" -Q --batch --eval '(let (r) (mapatoms (lambda (s) (when (and (fboundp s) (subrp (symbol-function s)) (not (subr-native-elisp-p (symbol-function s))) (not (special-form-p s))) (push (symbol-name s) r)))) (dolist (n (sort r (function string<))) (princ n) (princ "\n")))' 2>/dev/null > "$tmp/c.txt"

# 2. What the standalone answers for each of them.  The runtime classifies
# itself: `type-of' on the function cell is `subr' for a compiled primitive
# and `function' for an interpreted prelude `defun'.  Asking the runtime is
# the point -- the first version of this script intersected name lists out of
# the build script, which counted special forms as interpreted and missed
# primitives registered anywhere but the table it knew about.
"$BIN" --eval "(let ((names (with-temp-buffer (insert-file-contents \"$tmp/c.txt\") (split-string (buffer-string) \"\n\" t))) (subr nil) (fn nil)) (dolist (n names) (let ((s (intern n))) (when (fboundp s) (if (eq (type-of (symbol-function s)) 'subr) (push n subr) (push n fn))))) (with-temp-buffer (dolist (n (sort subr (function string<))) (insert n \"\n\")) (write-region (point-min) (point-max) \"$tmp/native.txt\" nil 'quiet)) (with-temp-buffer (dolist (n (sort fn (function string<))) (insert n \"\n\")) (write-region (point-min) (point-max) \"$tmp/interp.txt\" nil 'quiet)) (with-temp-buffer (dolist (n (sort (append subr fn) (function string<))) (insert n \"\n\")) (write-region (point-min) (point-max) \"$tmp/have.txt\" nil 'quiet)))" >/dev/null 2>&1
[ -s "$tmp/native.txt" ] || { echo "census: the standalone answered nothing -- is $BIN this tree's build?" >&2; exit 1; }

{
  printf '# Generated by tools/nelisp-c-primitive-census.sh -- do not hand-edit.\n'
  printf '# %s | standalone=%s | emacs=%s\n' "$(date '+%Y-%m-%d')" "$BIN" "$("$EMACS" --version 2>/dev/null | head -1)"
  printf '# c-primitives=%s present=%s native=%s interpreted=%s absent=%s\n' \
    "$(wc -l < "$tmp/c.txt")" "$(wc -l < "$tmp/have.txt")" \
    "$(wc -l < "$tmp/native.txt")" "$(wc -l < "$tmp/interp.txt")" \
    "$(comm -23 "$tmp/c.txt" "$tmp/have.txt" | wc -l)"
  printf '#\n# name\tstate\tscore\tagent\tvendor\n'
  while read -r n; do
    if grep -qxF "$n" "$tmp/native.txt"; then state=native
    elif grep -qxF "$n" "$tmp/interp.txt"; then state=interpreted
    else state=absent; fi
    a=0; v=0
    [ -n "$AGENT" ] && a=$(grep -rhoE "\($n[ )]" "$AGENT/lisp" "$AGENT/../nelisp-llm/lisp" "$AGENT/../nelisp-photon/lisp" 2>/dev/null | wc -l)
    [ -d "$VENDOR" ] && v=$(grep -rhoE "\($n[ )]" "$VENDOR" 2>/dev/null | wc -l)
    printf '%s\t%s\t%s\t%s\t%s\n' "$n" "$state" "$((a*3+v))" "$a" "$v"
  done < "$tmp/c.txt"
} > "$OUT"
printf 'wrote %s (%s rows)\n' "$OUT" "$(grep -vc '^#' "$OUT")"
grep -vE '^#' "$OUT" | awk -F'\t' '$2=="interpreted"' | sort -t"$(printf '\t')" -k3 -rn | head -15 |
  awk -F'\t' '{printf "  %-26s score=%-5s agent=%-4s vendor=%s\n", $1, $3, $4, $5}'
