;;; user-init-audit-discover.el --- source metadata only -*- lexical-binding: t; -*-
;; Never serialize the user's forms, strings, or variable values.
(require 'json)
(require 'cl-lib)
(let (rows (id 0))
  (dolist (name '("early-init.el" "init.el"))
    (with-temp-buffer
      (emacs-lisp-mode)
      (insert-file-contents (expand-file-name name (getenv "USER_INIT_SOURCE")))
      (let ((lexical (save-excursion
                       (goto-char (point-min))
                       (re-search-forward "lexical-binding: *t" (line-end-position 2) t))))
        (goto-char (point-min))
        (while (progn (forward-comment (point-max)) (not (eobp)))
          (let* ((start (point)) (line (line-number-at-pos))
                 (form (read (current-buffer))) (requires nil))
            (cl-labels ((walk (x)
                          (when (consp x)
                            (when (and (eq (car x) 'require)
                                       (eq (car-safe (cadr x)) 'quote)
                                       (symbolp (cadadr x)))
                              (push (symbol-name (cadadr x)) requires))
                            (unless (memq (car x) '(quote defun defmacro))
                              (walk (car x))
                              (walk (cdr x))))))
              (walk form))
            (push `((id . ,(setq id (1+ id))) (file . ,name) (line . ,line)
                    (start . ,(1- (position-bytes start)))
                    (end . ,(1- (position-bytes (point))))
                    (lexical . ,(if lexical t json-false))
                    (head . ,(if (and (consp form) (symbolp (car form)))
                                 (symbol-name (car form)) "literal"))
                    (requires . ,(vconcat (delete-dups (nreverse requires))))) rows))))))
  (princ (json-encode (nreverse rows))))
