;;; user-init-audit-runtime.el --- isolated form evaluation -*- lexical-binding: t; -*-
(defvar user-init-audit--sources nil)
(defvar user-init-audit-home nil)
(define-error 'user-init-audit-policy "Package network operation disabled by audit")
(defvar user-init-audit--original-load (symbol-function 'load))
(defvar user-init-audit--original-load-file (symbol-function 'load-file))
(defvar user-init-audit--original-require (symbol-function 'require))
(defvar user-init-audit--missing-feature nil)
(defvar user-init-audit--current-id 0)
(defun user-init-audit--load (file &rest args)
  (let* ((began (float-time))
         (label (if (stringp file) (file-name-nondirectory file) "<object>")))
    (unless (string-match "\\`[a-zA-Z0-9_.-]+\\'" label)
      (setq label "<redacted>"))
    (user-init-audit--emit (format "LOAD-BEGIN|%d|%s" user-init-audit--current-id label))
    (unwind-protect
        (apply user-init-audit--original-load file args)
      (user-init-audit--emit (format "LOAD-END|%d|%s|%.6f"
                                   user-init-audit--current-id label (- (float-time) began))))))
(defun user-init-audit--load-file (file)
  (let* ((began (float-time)) (label (file-name-nondirectory file)))
    (unless (string-match "\\`[a-zA-Z0-9_.-]+\\'" label)
      (setq label "<redacted>"))
    (user-init-audit--emit (format "LOAD-BEGIN|%d|%s" user-init-audit--current-id label))
    (unwind-protect
        (funcall user-init-audit--original-load-file file)
      (user-init-audit--emit (format "LOAD-END|%d|%s|%.6f"
                                   user-init-audit--current-id label (- (float-time) began))))))
(defun user-init-audit--require (feature &optional filename noerror)
  (let ((began (float-time)) (traced (not (featurep feature)))
        (label (symbol-name feature)))
    (unless (string-match "\\`[a-zA-Z0-9_.-]+\\'" label)
      (setq label "<redacted>"))
    (when traced
      (user-init-audit--emit (format "LOAD-BEGIN|%d|%s" user-init-audit--current-id label)))
    (unwind-protect
        (condition-case err
            (funcall user-init-audit--original-require feature filename noerror)
          (error
           (unless user-init-audit--missing-feature
             (setq user-init-audit--missing-feature feature))
           (signal (car err) (cdr err))))
      (when traced
        (user-init-audit--emit (format "LOAD-END|%d|%s|%.6f"
                                     user-init-audit--current-id label (- (float-time) began)))))))
(defvar user-init-audit--emit-function (symbol-function 'princ))
(defun user-init-audit--emit (text)
  (funcall user-init-audit--emit-function (concat "\nUINIT|" text "\n")))
(defun user-init-audit--redact (data &optional depth)
  "Keep condition structure and symbols, never private string contents."
  (let ((depth (or depth 0)))
    (cond ((> depth 5) '<depth-limit>)
          ((stringp data) "<redacted-string>")
          ((or (symbolp data) (numberp data)) data)
          ((consp data)
           (cons (user-init-audit--redact (car data) (1+ depth))
                 (user-init-audit--redact (cdr data) (1+ depth))))
          ((vectorp data) '<vector>) (t '<object>))))
(defun user-init-audit--paths ()
  "Reassert audit state paths after init forms change their defaults."
  (let* ((home user-init-audit-home) (state (concat home "/state/")))
    (setq user-emacs-directory (concat home "/.emacs.d/")
          default-directory (concat home "/")
          custom-file (concat state "custom.el")
          savehist-file (concat state "savehist")
          recentf-save-file (concat state "recentf")
          bookmark-default-file (concat state "bookmarks")
          auto-save-list-file-prefix (concat state "auto-save/list-")
          auto-save-file-name-transforms `((".*" ,(concat state "auto-save/") t))
          backup-directory-alist `(("." . ,(concat state "backups/")))
          temporary-file-directory (concat home "/tmp/")
          server-auth-dir (concat state "server/")
          server-socket-dir (concat state "server/")
          package-user-dir (concat home "/.emacs.d/elpa/")
          package-enable-at-startup nil package-quickstart nil
          package-check-signature nil
          native-comp-eln-load-path (list (concat state "eln/"))
          native-comp-jit-compilation nil native-comp-deferred-compilation nil
          native-comp-enable-subr-trampolines nil
          emacs-load-auto-native-compile nil emacs-load-artifact-max-source-size 0
          no-littering-var-directory (concat state "var/")
          no-littering-etc-directory (concat state "etc/")
          url-configuration-directory (concat state "url/")
          tramp-persistency-file-name (concat state "tramp")
          org-id-locations-file (concat state "org-id-locations")
          projectile-cache-file (concat state "projectile-cache")
          projectile-known-projects-file (concat state "projectile-projects")
          undo-tree-history-directory-alist `(("." . ,(concat state "undo/")))
          abbrev-file-name (concat state "abbrev_defs"))
    (setenv "XDG_CACHE_HOME" (concat home "/cache"))))
(defun user-init-audit--setup ()
  ;; A cold heap retains the build process's environment overlay. Refresh it
  ;; before consulting HOME or starting any subprocess from the user's init.
  (when (fboundp 'emacs-callproc-populate-process-environment)
    (setq process-environment nil)
    (emacs-callproc-populate-process-environment))
  (setenv "HOME" user-init-audit-home)
  (dolist (entry '(("XDG_CACHE_HOME" . "/cache") ("XDG_CONFIG_HOME" . "/config")
                   ("XDG_DATA_HOME" . "/data") ("XDG_RUNTIME_DIR" . "/runtime")
                   ("TMPDIR" . "/tmp") ("TMP" . "/tmp") ("TEMP" . "/tmp")))
    (setenv (car entry) (concat user-init-audit-home (cdr entry))))
  (user-init-audit--paths)
  (fset 'load #'user-init-audit--load)
  (fset 'load-file #'user-init-audit--load-file)
  (fset 'require #'user-init-audit--require)
  ;; The OS sandbox denies sockets and writes outside fixture HOME as well.
  (dolist (fn '(package-refresh-contents package-install package-vc-install
                package-install-from-archive))
    (fset fn (lambda (&rest _args) (signal 'user-init-audit-policy '(network-package-operation)))))
  (dolist (name '("early-init.el" "init.el"))
    (let ((path (concat user-emacs-directory name)))
      (push (cons name (if (fboundp 'emacs-load--read-file-string)
                          (string-as-unibyte (emacs-load--read-file-string path))
                        (with-temp-buffer
                          (set-buffer-multibyte nil)
                          (insert-file-contents-literally path)
                          (buffer-string)))) user-init-audit--sources)))
  (user-init-audit--emit "SETUP"))
(defun user-init-audit--one (id name line start end lexical)
  (setq user-init-audit--current-id id)
  (setq user-init-audit--missing-feature nil)
  (user-init-audit--paths)
  (let* ((load-file-name (concat user-emacs-directory name))
         (buffer-file-name load-file-name)
         (lexical-binding lexical)
         (source (string-as-multibyte
                  (substring (cdr (assoc name user-init-audit--sources)) start end)))
         (began (float-time)) (caught nil) (missing ""))
    (user-init-audit--emit (format "BEGIN|%d" id))
    (condition-case err
        (let ((form (car (read-from-string source))))
          (user-init-audit--emit (format "READ|%d" id))
          (eval form lexical))
      (error (setq caught err))
      (quit (setq caught '(quit))))
    (when (memq (car-safe caught) '(void-function void-variable))
      (setq missing (if (symbolp (cadr caught)) (symbol-name (cadr caught)) "")))
    (when (and (memq (car-safe caught) '(file-missing file-error))
               (equal (cadr caught) "Cannot open load file")
               (stringp (car (last caught)))
               (string-match "\\`[a-zA-Z0-9_-]+\\(?:\\.elc?\\)?\\'" (car (last caught))))
      (setq missing (car (last caught))))
    (when (and caught (equal missing "") user-init-audit--missing-feature)
      (setq missing (symbol-name user-init-audit--missing-feature)))
    (user-init-audit--emit
     (format "END|%d|%.6f|%s|%s|%S" id (- (float-time) began)
             (if caught (car caught) 'ok) missing
             (user-init-audit--redact (cdr caught))))
    nil))
(user-init-audit--setup)
