;;; Direct GNU/native load-reader escape comparison.  -*- lexical-binding: t; -*-
(princ (format "L|0|%S\n" ?\0))
(princ (format "L|1|%S\n" (list (string-to-list "\0") (multibyte-string-p "\0"))))
(princ (format "L|2|%S\n" ?\00))
(princ (format "L|3|%S\n" (list (string-to-list "\00") (multibyte-string-p "\00"))))
(princ (format "L|4|%S\n" ?\000))
(princ (format "L|5|%S\n" (list (string-to-list "\000") (multibyte-string-p "\000"))))
(princ (format "L|6|%S\n" ?\1))
(princ (format "L|7|%S\n" (list (string-to-list "\1") (multibyte-string-p "\1"))))
(princ (format "L|8|%S\n" ?\12))
(princ (format "L|9|%S\n" (list (string-to-list "\12") (multibyte-string-p "\12"))))
(princ (format "L|10|%S\n" ?\040))
(princ (format "L|11|%S\n" (list (string-to-list "\040") (multibyte-string-p "\040"))))
(princ (format "L|12|%S\n" ?\377))
(princ (format "L|13|%S\n" (list (string-to-list "\377") (multibyte-string-p "\377"))))
(princ (format "L|14|%S\n" ?\400))
(princ (format "L|15|%S\n" (list (string-to-list "\400") (multibyte-string-p "\400"))))
(princ (format "L|16|%S\n" ?\777))
(princ (format "L|17|%S\n" (list (string-to-list "\777") (multibyte-string-p "\777"))))
(princ (format "L|18|%S\n" (list (string-to-list "\0400") (multibyte-string-p "\0400"))))
(princ (format "L|19|%S\n" ?\8))
(princ (format "L|20|%S\n" (list (string-to-list "\8") (multibyte-string-p "\8"))))
(princ (format "L|21|%S\n" ?\x0))
(princ (format "L|22|%S\n" (list (string-to-list "\x0") (multibyte-string-p "\x0"))))
(princ (format "L|23|%S\n" ?\x20))
(princ (format "L|24|%S\n" (list (string-to-list "\x20") (multibyte-string-p "\x20"))))
(princ (format "L|25|%S\n" ?\xff))
(princ (format "L|26|%S\n" (list (string-to-list "\xff") (multibyte-string-p "\xff"))))
(princ (format "L|27|%S\n" ?\x100))
(princ (format "L|28|%S\n" (list (string-to-list "\x100") (multibyte-string-p "\x100"))))
(princ (format "L|29|%S\n" ?\x1f600))
(princ (format "L|30|%S\n" (list (string-to-list "\x1f600") (multibyte-string-p "\x1f600"))))
(princ (format "L|31|%S\n" ?\u0041))
(princ (format "L|32|%S\n" (list (string-to-list "\u0041") (multibyte-string-p "\u0041"))))
(princ (format "L|33|%S\n" ?\u00ff))
(princ (format "L|34|%S\n" (list (string-to-list "\u00ff") (multibyte-string-p "\u00ff"))))
(princ (format "L|35|%S\n" ?\u3042))
(princ (format "L|36|%S\n" (list (string-to-list "\u3042") (multibyte-string-p "\u3042"))))
(princ (format "L|37|%S\n" ?\U0001F600))
(princ (format "L|38|%S\n" (list (string-to-list "\U0001F600") (multibyte-string-p "\U0001F600"))))
(princ (format "L|39|%S\n" ?\N{U+0041}))
(princ (format "L|40|%S\n" (list (string-to-list "\N{U+0041}") (multibyte-string-p "\N{U+0041}"))))
(princ (format "L|41|%S\n" ?\N{U+3042}))
(princ (format "L|42|%S\n" (list (string-to-list "\N{U+3042}") (multibyte-string-p "\N{U+3042}"))))
(princ (format "L|43|%S\n" ?\^A))
(princ (format "L|44|%S\n" (list (string-to-list "\^A") (multibyte-string-p "\^A"))))
(princ (format "L|45|%S\n" ?\^?))
(princ (format "L|46|%S\n" (list (string-to-list "\^?") (multibyte-string-p "\^?"))))
(princ (format "L|47|%S\n" ?\C-a))
(princ (format "L|48|%S\n" (list (string-to-list "\C-a") (multibyte-string-p "\C-a"))))
(princ (format "L|49|%S\n" ?\C- ))
(princ (format "L|50|%S\n" (list (string-to-list "\C- ") (multibyte-string-p "\C- "))))
(princ (format "L|51|%S\n" ?\M-a))
(princ (format "L|52|%S\n" (list (string-to-list "\M-a") (multibyte-string-p "\M-a"))))
(princ (format "L|53|%S\n" ?\S-a))
(princ (format "L|54|%S\n" (list (string-to-list "\S-a") (multibyte-string-p "\S-a"))))
(princ (format "L|55|%S\n" ?\H-a))
(princ (format "L|56|%S\n" ?\s-a))
(princ (format "L|57|%S\n" (list (string-to-list "\s-a") (multibyte-string-p "\s-a"))))
(princ (format "L|58|%S\n" ?\A-a))
(princ (format "L|59|%S\n" ?\d))
(princ (format "L|60|%S\n" (list (string-to-list "\d") (multibyte-string-p "\d"))))
(princ (format "L|61|%S\n" ?\e))
(princ (format "L|62|%S\n" (list (string-to-list "\e") (multibyte-string-p "\e"))))
(princ (format "L|63|%S\n" ?\s))
(princ (format "L|64|%S\n" (list (string-to-list "\s") (multibyte-string-p "\s"))))
(princ (format "L|65|%S\n" ?\a))
(princ (format "L|66|%S\n" (list (string-to-list "\a") (multibyte-string-p "\a"))))
(princ (format "L|67|%S\n" ?\b))
(princ (format "L|68|%S\n" (list (string-to-list "\b") (multibyte-string-p "\b"))))
(princ (format "L|69|%S\n" ?\f))
(princ (format "L|70|%S\n" (list (string-to-list "\f") (multibyte-string-p "\f"))))
(princ (format "L|71|%S\n" ?\n))
(princ (format "L|72|%S\n" (list (string-to-list "\n") (multibyte-string-p "\n"))))
(princ (format "L|73|%S\n" ?\r))
(princ (format "L|74|%S\n" (list (string-to-list "\r") (multibyte-string-p "\r"))))
(princ (format "L|75|%S\n" ?\t))
(princ (format "L|76|%S\n" (list (string-to-list "\t") (multibyte-string-p "\t"))))
(princ (format "L|77|%S\n" ?\v))
(princ (format "L|78|%S\n" (list (string-to-list "\v") (multibyte-string-p "\v"))))
(princ (format "L|79|%S\n" ?\C-\M-a))
(princ (format "L|80|%S\n" (list (string-to-list "\C-\M-a") (multibyte-string-p "\C-\M-a"))))
(princ (format "L|81|%S\n" ?\M-\C-a))
(princ (format "L|82|%S\n" (list (string-to-list "\M-\C-a") (multibyte-string-p "\M-\C-a"))))
(princ (format "L|83|%S\n" ?\C-\040))
(princ (format "L|84|%S\n" (list (string-to-list "\C-\040") (multibyte-string-p "\C-\040"))))
(princ (format "L|85|%S\n" ?\M-\040))
(princ (format "L|86|%S\n" (list (string-to-list "\M-\040") (multibyte-string-p "\M-\040"))))
(princ (format "L|87|%S\n" ?\S-\040))
(princ (format "L|88|%S\n" ?\C-\u0041))
(princ (format "L|89|%S\n" (list (string-to-list "\C-\u0041") (multibyte-string-p "\C-\u0041"))))
(princ (format "L|90|%S\n" ?\M-\u3042))
(princ (format "L|91|%S\n" ?\H-\M-a))
(princ (format "L|92|%S\n" ?\S-\C-a))
(princ (format "L|93|%S\n" ?\x000ff))
(princ (format "L|94|%S\n" (list (string-to-list "\x000ff") (multibyte-string-p "\x000ff"))))
(princ (format "L|95|%S\n" ?\u0000))
(princ (format "L|96|%S\n" (list (string-to-list "\u0000") (multibyte-string-p "\u0000"))))
(princ (format "L|97|%S\n" ?\U000000FF))
(princ (format "L|98|%S\n" (list (string-to-list "\U000000FF") (multibyte-string-p "\U000000FF"))))
(princ (format "L|99|%S\n" ?\N{U+00FF}))
(princ (format "L|100|%S\n" (list (string-to-list "\N{U+00FF}") (multibyte-string-p "\N{U+00FF}"))))
(princ (format "L|101|%S\n" ?\C-\C-a))
(princ (format "L|102|%S\n" ?\C-\M-\040))
(princ (format "L|103|%S\n" ?\M-\C-\040))
(princ (format "L|104|%S\n" ?\S-A))
(princ (format "L|105|%S\n" (list (string-to-list "\S-A") (multibyte-string-p "\S-A"))))
(princ (format "L|106|%S\n" ?\M-\S-a))
(princ (format "L|107|%S\n" (list (string-to-list "\M-\S-a") (multibyte-string-p "\M-\S-a"))))
(princ (format "L|108|%S\n" ?\S-\M-a))
(princ (format "L|109|%S\n" (list (string-to-list "\S-\M-a") (multibyte-string-p "\S-\M-a"))))
(princ (format "L|110|%S\n" ?\C-\M-\S-a))
(princ (format "L|111|%S\n" ?\C-\[))
(princ (format "L|112|%S\n" (list (string-to-list "\C-\[") (multibyte-string-p "\C-\["))))
(princ (format "L|113|%S\n" ?\M-\u00e9))
(princ (format "L|114|%S\n" ?\M-é))
(princ (format "L|115|%S\n" ?\x110000))
(princ (format "L|116|%S\n" (list (string-to-list "\x110000") (multibyte-string-p "\x110000"))))
(princ (format "L|117|%S\n" ?\uD800))
(princ (format "L|118|%S\n" (list (string-to-list "\uD800") (multibyte-string-p "\uD800"))))
(princ (format "L|119|%S\n" ?\U0010FFFF))
(princ (format "L|120|%S\n" (list (string-to-list "\U0010FFFF") (multibyte-string-p "\U0010FFFF"))))
(princ (format "L|121|%S\n" (list (string-to-list "\C-xz") (multibyte-string-p "\C-xz"))))
(progn (princ "L-DONE\n") (kill-emacs 0))
