;;; Standalone FFI capability probe; no native compilation.
(load "/home/madblack-21/Cowork/Notes/dev/nelisp-emacs-lib/.worktrees/ccore-runtime-20261002/packages/nl-ffi/src/nl-ffi.el" nil t)
(require 'nl-ffi-memory)
(defun g1-call (name sig &rest args)
  (apply #'nl-ffi-compat-call nil name sig args))
(defun g1-report (tag value) (princ (format "%s=%S\n" tag value)))
(defun g1-refusal (tag expected thunk)
  (let ((condition (condition-case e (progn (funcall thunk) nil) (error e))))
    (g1-report tag condition)
    (unless (eq (car condition) expected) (error "Wrong refusal for %s: %S" tag condition))))
(dolist (lib '("libX11.so.6" "libxcb.so.1" "libcairo.so.2" "libfreetype.so.6"
               "libharfbuzz.so.0" "libfontconfig.so.1" "libgtk-4.so.1"
               "libpangocairo-1.0.so.0" "libm.so.6"))
  (ffi:library lib)
  (g1-report lib (list 'handle (nl-ffi-library-handle lib)
                       'elf-fallback (nl-ffi-loader-handle-p (nl-ffi-library-handle lib)))))
(g1-report "type-vocabulary" nl-ffi-types)
(let ((h (nl-ffi--dlopen "libfreetype.so.6")))
  (g1-report "direct-dlopen-freetype" (list h (nl-ffi--dlsym h "FT_Init_FreeType")))
  (nl-ffi-call "dlclose" h))
(let* ((o (nl-ffi-memory-allocate 8)) (p (nl-ffi-memory-address o))
       (rc (g1-call "FT_Init_FreeType" [:sint32 :pointer] p))
       (ft (ptr-read-u64 p 0)))
  (g1-report "FT_Init_FreeType" (list rc ft))
  (unless (and (= rc 0) (> ft 0)) (error "FreeType initialization failed"))
  (g1-report "FT_Done_FreeType" (g1-call "FT_Done_FreeType" [:sint32 :pointer] ft))
  (nl-ffi-memory-release o))
(let ((config (g1-call "FcInitLoadConfigAndFonts" [:pointer])))
  (g1-report "FcInitLoadConfigAndFonts" config)
  (unless (> config 0) (error "Fontconfig initialization failed"))
  (g1-call "FcConfigDestroy" [:void :pointer] config))
(let* ((o (nl-ffi-memory-allocate 4))
       (display-owner (and (getenv "DISPLAY") (nl-ffi-memory-cstring (getenv "DISPLAY"))))
       (display-p (if display-owner (nl-ffi-memory-address display-owner) 0))
       (xcb (g1-call "xcb_connect" [:pointer :pointer :pointer] display-p (nl-ffi-memory-address o))))
  (let ((err (g1-call "xcb_connection_has_error" [:sint32 :pointer] xcb)))
    (g1-report "xcb_connect" (list xcb err (g1-call "xcb_get_file_descriptor" [:sint32 :pointer] xcb)))
    (g1-report "xcb-display" (getenv "DISPLAY")))
  (g1-call "xcb_disconnect" [:void :pointer] xcb)
  (when display-owner (nl-ffi-memory-release display-owner))
  (nl-ffi-memory-release o))
(g1-report "double-cos" (g1-call "cos" [:double :double] 0.0))
(g1-report "double-hypot" (g1-call "hypot" [:double :double :double] 3.0 4.0))
(g1-report "hb-version" (nl-ffi-get-string (g1-call "hb_version_string" [:pointer])))
(g1-report "cairo-version" (g1-call "cairo_version" [:sint32]))
(g1-report "gtk-major-version" (g1-call "gtk_get_major_version" [:uint32]))
(g1-report "integer-abs" (g1-call "abs" [:sint32 :sint32] -7))
(g1-report "sint32-return-minus1" (g1-call "cairo_format_stride_for_width" [:sint32 :sint32 :sint32] 0 -1))
(g1-refusal "float-refused" 'nl-ffi-dlsym-float-unsupported (lambda () (g1-call "cosf" [:float :float] 0.0)))
(g1-refusal "struct-refused" 'nl-ffi-unknown-type (lambda () (g1-call "xcb_get_input_focus" [:struct :pointer] 0)))
(g1-refusal "double-position5-refused" 'nl-ffi-dlsym-float-unsupported (lambda () (g1-call "nonexistent_g1" [:void :pointer :pointer :pointer :pointer :double] 0 0 0 0 1.0)))
(g1-refusal "XCreateSimpleWindow-9args-refused" 'nl-ffi-too-many-arguments (lambda () (g1-call "XCreateSimpleWindow" [:uint64 :pointer :uint64 :sint32 :sint32 :uint32 :uint32 :uint32 :uint64 :uint64] 0 0 0 0 640 480 0 0 0)))
(princ "FFI-DONE\n")
t
