;;; Actual standalone FreeType/HarfBuzz/Fontconfig rendering, without a socket.
;;; Cairo is an offscreen probe instrument, not the recommended backend.
(load "/home/madblack-21/Cowork/Notes/dev/nelisp-emacs-lib/.worktrees/ccore-runtime-20261002/packages/nl-ffi/src/nl-ffi.el" nil t)
(require 'nl-ffi-memory)
(dolist (lib '("libfreetype.so.6" "libharfbuzz.so.0" "libfontconfig.so.1" "libcairo.so.2")) (ffi:library lib))
(defun g1-call (name sig &rest args) (apply #'nl-ffi-compat-call nil name sig args))
(defun g1-u32 (p o)
  (+ (ptr-read-u8 p o) (ash (ptr-read-u8 p (+ o 1)) 8)
     (ash (ptr-read-u8 p (+ o 2)) 16) (ash (ptr-read-u8 p (+ o 3)) 24)))
(defun g1-s32 (p o) (let ((v (g1-u32 p o))) (if (>= v 2147483648) (- v 4294967296) v)))
(defun g1-f64-fixed-bits (n)
  ;; Encode nonnegative 26.6 fixed point exactly as IEEE binary64, in Lisp.
  (if (= n 0) 0
    (let ((power 0))
      (while (>= n (ash 1 (1+ power))) (setq power (1+ power)))
      (+ (ash (+ 1023 (- power 6)) 52) (ash (- n (ash 1 power)) (- 52 power))))))
(defun g1-store-f64-fixed (p offset n)
  ;; ptr-write-u64 cannot carry bignums above most-positive-fixnum.
  (let ((bits (g1-f64-fixed-bits n)))
    (ptr-write-u32 p offset (logand bits #xffffffff))
    (ptr-write-u32 p (+ offset 4) (logand (ash bits -32) #xffffffff))))
(defun g1-match-font ()
  (let* ((config (g1-call "FcInitLoadConfigAndFonts" [:pointer]))
         (name (nl-ffi-memory-cstring "monospace:lang=ja"))
         (pattern (g1-call "FcNameParse" [:pointer :pointer] (nl-ffi-memory-address name)))
         (result (nl-ffi-memory-allocate 8)) (ptr (nl-ffi-memory-address result)))
    (nl-ffi-memory-release name)
    (unless (= (g1-call "FcConfigSubstitute" [:sint32 :pointer :pointer :sint32] config pattern 0) 1) (error "Fc substitute failed"))
    (g1-call "FcDefaultSubstitute" [:void :pointer] pattern)
    (let* ((matched (g1-call "FcFontMatch" [:pointer :pointer :pointer :pointer] config pattern ptr))
           (key (nl-ffi-memory-cstring "file")))
      (unless (> matched 0) (error "Fc match failed"))
      (unless (= (g1-call "FcPatternGetString" [:sint32 :pointer :pointer :sint32 :pointer]
                          matched (nl-ffi-memory-address key) 0 ptr) 0) (error "Fc file failed"))
      (let ((file (nl-ffi-get-string (ptr-read-u64 ptr 0))))
        (princ (format "Fontconfig-file=%S\n" file))
        (nl-ffi-memory-release key) (nl-ffi-memory-release result)
        (g1-call "FcPatternDestroy" [:void :pointer] matched)
        (g1-call "FcPatternDestroy" [:void :pointer] pattern)
        (g1-call "FcConfigDestroy" [:void :pointer] config)
        file))))
(defun g1-font-open (ft file out)
  (let ((name (nl-ffi-memory-cstring file)))
    (unless (= (g1-call "FT_New_Face" [:sint32 :pointer :pointer :sint64 :pointer]
                        ft (nl-ffi-memory-address name) 0 out) 0) (error "FT open failed"))
    (nl-ffi-memory-release name)
    (ptr-read-u64 out 0)))
(let* ((output (nl-ffi-memory-allocate 8)) (out (nl-ffi-memory-address output))
       (ft nil) (face nil) (ascii nil) (hb nil) (buffer nil)
       (canvas nil) (cr nil) (cache (make-hash-table)) (owners nil) (surfaces nil))
  (unwind-protect
      (progn
        (unless (= (g1-call "FT_Init_FreeType" [:sint32 :pointer] out) 0) (error "FT init failed"))
        (setq ft (ptr-read-u64 out 0)
              ascii (g1-font-open ft "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf" out))
        (princ (format "ASCII-font-Japanese-glyph=%d\n" (g1-call "FT_Get_Char_Index" [:uint32 :pointer :uint64] ascii #x65e5)))
        (setq face (g1-font-open ft (g1-match-font) out))
        (unless (> (g1-call "FT_Get_Char_Index" [:uint32 :pointer :uint64] face #x65e5) 0) (error "Japanese fallback missing"))
        (unless (= (g1-call "FT_Set_Pixel_Sizes" [:sint32 :pointer :uint32 :uint32] face 0 28) 0) (error "FT size failed"))
        (setq hb (g1-call "hb_ft_font_create_referenced" [:pointer :pointer] face)
              buffer (g1-call "hb_buffer_create" [:pointer])
              canvas (g1-call "cairo_image_surface_create" [:pointer :sint32 :sint32 :sint32] 0 800 500)
              cr (g1-call "cairo_create" [:pointer :pointer] canvas))
        (g1-call "cairo_set_source_rgb" [:void :pointer :double :double :double] cr 1.0 1.0 1.0)
        (g1-call "cairo_paint" [:void :pointer] cr)
        (g1-call "cairo_set_source_rgb" [:void :pointer :double :double :double] cr 0.0 0.0 0.0)
        (let* ((text (encode-coding-string "NeLisp 日本語 SKK あいうえお" 'utf-8))
               (o (nl-ffi-memory-cstring text)))
          (g1-call "hb_buffer_add_utf8" [:void :pointer :pointer :sint32 :uint32 :sint32]
                   buffer (nl-ffi-memory-address o) (length text) 0 (length text))
          (nl-ffi-memory-release o))
        (g1-call "hb_buffer_guess_segment_properties" [:void :pointer] buffer)
        (g1-call "hb_shape" [:void :pointer :pointer :pointer :uint32] hb buffer 0 0)
        (let* ((count (g1-call "hb_buffer_get_length" [:uint32 :pointer] buffer))
               (infos (g1-call "hb_buffer_get_glyph_infos" [:pointer :pointer :pointer] buffer 0))
               (positions (g1-call "hb_buffer_get_glyph_positions" [:pointer :pointer :pointer] buffer 0))
               (codes nil) (i 0) (x 20) (start (float-time)))
          (princ (format "hb-shaped=%d\n" count))
          (while (< i count)
            (let* ((gid (g1-u32 infos (* i 20))) (advance (/ (g1-s32 positions (* i 20)) 64)))
              (when (= gid 0) (error "Missing glyph at index %d" i))
              (unless (gethash gid cache)
                (unless (= (g1-call "FT_Load_Glyph" [:sint32 :pointer :uint32 :sint32] face gid 0) 0) (error "FT load failed"))
                (let ((slot (ptr-read-u64 face 152)))
                  (unless (= (g1-call "FT_Render_Glyph" [:sint32 :pointer :sint32] slot 0) 0) (error "FT render failed"))
                  (let* ((h (g1-u32 slot 152)) (w (g1-u32 slot 156)) (pitch (g1-s32 slot 160))
                         (data (ptr-read-u64 slot 168)) (left (g1-s32 slot 192)) (top (g1-s32 slot 196))
                         (levels (make-hash-table)) (y 0)
                         (stride (* 4 (/ (+ w 3) 4)))
                         (owner (nl-ffi-memory-allocate (max 4 (* stride h))))
                         (p (nl-ffi-memory-address owner)) (mask nil))
                    (unless (= (ptr-read-u8 slot 178) 2) (error "Not FT gray bitmap"))
                    (while (< y h)
                      (let ((col 0))
                        (while (< col w)
                          (let ((value (ptr-read-u8 data (+ (* y pitch) col))))
                            (puthash value t levels) (ptr-write-u8 p (+ (* y stride) col) value))
                          (setq col (1+ col))))
                      (setq y (1+ y)))
                    (setq mask (g1-call "cairo_image_surface_create_for_data" [:pointer :pointer :sint32 :sint32 :sint32 :sint32] p 2 w h stride))
                    (unless (= (g1-call "cairo_surface_status" [:sint32 :pointer] mask) 0) (error "Mask surface failed"))
                    (push owner owners) (push mask surfaces)
                    (puthash gid (list mask left top) cache)
                    (princ (format "glyph=%d bitmap=%dx%d gray-levels=%d advance=%d\n" gid w h (hash-table-count levels) advance)))))
              (push (list gid x) codes)
              (setq x (+ x advance)))
            (setq i (1+ i)))
          (setq codes (nreverse codes))
          (princ (format "cold-raster-and-cache-seconds=%.6f unique-glyphs=%d\n" (- (float-time) start) (hash-table-count cache)))
          (let ((row 0) (start2 (float-time)))
            (while (< row 12)
              (dolist (code codes)
                (let ((g (gethash (car code) cache)))
                  (g1-call "cairo_mask_surface" [:void :pointer :pointer :double :double]
                           cr (car g) (+ (nth 1 code) (nth 1 g)) (- (+ 65 (* row 32)) (nth 2 g)))))
              (setq row (1+ row)))
            (g1-call "cairo_surface_flush" [:void :pointer] canvas)
            (princ (format "offscreen-12row-frame-ms=%.3f\n" (* 1000 (- (float-time) start2)))))
          (let ((o (nl-ffi-memory-cstring (expand-file-name "probes/results/fonts.png"))))
            (unless (= (g1-call "cairo_surface_write_to_png" [:sint32 :pointer :pointer] canvas (nl-ffi-memory-address o)) 0) (error "PNG write failed"))
            (nl-ffi-memory-release o))
          ;; B's alternative: a pointer to an array of structs, never structs by value.
          (let* ((cairo-face (g1-call "cairo_ft_font_face_create_for_ft_face" [:pointer :pointer :sint32] face 0))
                 (glyph-owner (nl-ffi-memory-allocate (* count 12 24)))
                 (glyphs (nl-ffi-memory-address glyph-owner)) (row 0) (idx 0)
                 (pack-start (float-time)))
            (while (< row 12)
              (dolist (code codes)
                (ptr-write-u64 glyphs (* idx 24) (car code))
                (g1-store-f64-fixed glyphs (+ (* idx 24) 8) (* (nth 1 code) 64))
                (g1-store-f64-fixed glyphs (+ (* idx 24) 16) (* (+ 65 (* row 32)) 64))
                (setq idx (1+ idx)))
              (setq row (1+ row)))
            (princ (format "cairo-batch-glyph-pack-ms=%.3f glyphs=%d\n" (* 1000 (- (float-time) pack-start)) idx))
            (princ (format "cairo-glyph0-fields=%S expected20.0bits=%S\n"
                           (list (ptr-read-u64 glyphs 0) (ptr-read-u64 glyphs 8) (ptr-read-u64 glyphs 16))
                           (g1-f64-fixed-bits 1280)))
            (g1-call "cairo_set_font_face" [:void :pointer :pointer] cr cairo-face)
            (g1-call "cairo_set_font_size" [:void :pointer :double] cr 28.0)
            (let ((n 0) (start3 (float-time)))
              (while (< n 20)
                (g1-call "cairo_show_glyphs" [:void :pointer :pointer :sint32] cr glyphs idx)
                (setq n (1+ n)))
              (g1-call "cairo_surface_flush" [:void :pointer] canvas)
              (princ (format "cairo-batch-mean-ms=%.3f frames=20 glyphs-per-frame=%d\n" (* 50 (- (float-time) start3)) idx)))
            ;; Restore one clean draw for AA/pixel verification.
            (g1-call "cairo_set_source_rgb" [:void :pointer :double :double :double] cr 1.0 1.0 1.0)
            (g1-call "cairo_paint" [:void :pointer] cr)
            (g1-call "cairo_set_source_rgb" [:void :pointer :double :double :double] cr 0.0 0.0 0.0)
            (g1-call "cairo_show_glyphs" [:void :pointer :pointer :sint32] cr glyphs idx)
            (unless (= (g1-call "cairo_status" [:sint32 :pointer] cr) 0) (error "Cairo batch failed"))
            (let ((o (nl-ffi-memory-cstring (expand-file-name "probes/results/fonts-batch.png"))))
              (unless (= (g1-call "cairo_surface_write_to_png" [:sint32 :pointer :pointer] canvas (nl-ffi-memory-address o)) 0) (error "Batch PNG failed"))
              (nl-ffi-memory-release o))
            ;; cairo-face remains referenced by CR until CR destruction below.
            (g1-call "cairo_font_face_destroy" [:void :pointer] cairo-face)
            (nl-ffi-memory-release glyph-owner))))
    (when cr (g1-call "cairo_destroy" [:void :pointer] cr))
    (when canvas (g1-call "cairo_surface_destroy" [:void :pointer] canvas))
    (dolist (s surfaces) (g1-call "cairo_surface_destroy" [:void :pointer] s))
    (dolist (o owners) (nl-ffi-memory-release o))
    (when buffer (g1-call "hb_buffer_destroy" [:void :pointer] buffer))
    (when hb (g1-call "hb_font_destroy" [:void :pointer] hb))
    (when face (g1-call "FT_Done_Face" [:sint32 :pointer] face))
    (when ascii (g1-call "FT_Done_Face" [:sint32 :pointer] ascii))
    (when ft (g1-call "FT_Done_FreeType" [:sint32 :pointer] ft))
    (nl-ffi-memory-release output)))
(princ "FONTS-DONE\n")
t
