;;; Existing scalar FFI -> system libffi -> seven-argument XKB call.
;;; No compiled shim, added primitive, Rust, callback or display connection.
(load "/home/madblack-21/Cowork/Notes/dev/nelisp-emacs-lib/.worktrees/ccore-runtime-20261002/packages/nl-ffi/src/nl-ffi.el" nil t)
(require 'nl-ffi-memory)
(ffi:library "libffi.so.8")
(ffi:library "libxkbcommon.so.0")
(defun g1-call (name sig &rest args) (apply #'nl-ffi-compat-call nil name sig args))
(defun g1-u32 (p o)
  (+ (ptr-read-u8 p o) (ash (ptr-read-u8 p (+ o 1)) 8)
     (ash (ptr-read-u8 p (+ o 2)) 16) (ash (ptr-read-u8 p (+ o 3)) 24)))
(defun g1-libffi-mask (state mods group)
  (let* ((h (nl-ffi-library-handle "libffi.so.8"))
         (type-ptr (nl-ffi--dlsym h "ffi_type_pointer"))
         (type-u32 (nl-ffi--dlsym h "ffi_type_uint32"))
         (cif-o (nl-ffi-memory-allocate 32)) (cif (nl-ffi-memory-address cif-o))
         (types-o (nl-ffi-memory-allocate 56)) (types (nl-ffi-memory-address types-o))
         (args-o (nl-ffi-memory-allocate 56)) (args (nl-ffi-memory-address args-o))
         (values-o (nl-ffi-memory-allocate 56)) (values (nl-ffi-memory-address values-o))
         (ret-o (nl-ffi-memory-allocate 8)) (ret (nl-ffi-memory-address ret-o))
         (i 0) (items (list state mods 0 0 0 0 group)))
    (unwind-protect
        (progn
          (while (< i 7)
            (ptr-write-u64 types (* i 8) (if (= i 0) type-ptr type-u32))
            (ptr-write-u64 args (* i 8) (+ values (* i 8)))
            (ptr-write-u64 values (* i 8) (nth i items))
            (setq i (1+ i)))
          (unless (= (g1-call "ffi_prep_cif" [:sint32 :pointer :sint32 :uint32 :pointer :pointer]
                              cif 2 7 type-u32 types) 0) (error "ffi_prep_cif failed"))
          (g1-call "ffi_call" [:void :pointer :pointer :pointer :pointer] cif
                   (nl-ffi--dlsym (nl-ffi-library-handle "libxkbcommon.so.0") "xkb_state_update_mask") ret args)
          (g1-u32 ret 0))
      (dolist (o (list cif-o types-o args-o values-o ret-o)) (nl-ffi-memory-release o)))))
(let* ((ctx (g1-call "xkb_context_new" [:pointer :uint32] 0))
       (names-o (nl-ffi-memory-allocate 40)) (names (nl-ffi-memory-address names-o))
       (layout-o (nl-ffi-memory-cstring "us,de")) (keymap nil) (state nil))
  (unwind-protect
      (progn
        (ptr-write-u64 names 16 (nl-ffi-memory-address layout-o))
        (setq keymap (g1-call "xkb_keymap_new_from_names" [:pointer :pointer :pointer :uint32] ctx names 0))
        (unless (> keymap 0) (error "XKB keymap failed"))
        (setq state (g1-call "xkb_state_new" [:pointer :pointer] keymap))
        (princ (format "XKB-baseline-q=%d\n" (g1-call "xkb_state_key_get_one_sym" [:uint32 :pointer :uint32] state 24)))
        (let* ((name-o (nl-ffi-memory-cstring "Mod5"))
               (mod-index (g1-call "xkb_keymap_mod_get_index" [:uint32 :pointer :pointer] keymap (nl-ffi-memory-address name-o)))
               (mods (ash 1 mod-index)))
          (nl-ffi-memory-release name-o)
          (princ (format "libffi-seven-args-update-mask=%d\n" (g1-libffi-mask state mods 1)))
          (let ((symbol (g1-call "xkb_state_key_get_one_sym" [:uint32 :pointer :uint32] state 24))
                (group (g1-call "xkb_state_serialize_layout" [:uint32 :pointer :uint32] state 128)))
            (princ (format "XKB-German-AltGr-q=%d effective-group=%d\n" symbol group))
            (unless (and (= symbol 64) (= group 1)) (error "Wrong XKB symbol/mask result")))))
    (when state (g1-call "xkb_state_unref" [:void :pointer] state))
    (when keymap (g1-call "xkb_keymap_unref" [:void :pointer] keymap))
    (g1-call "xkb_context_unref" [:void :pointer] ctx)
    (nl-ffi-memory-release names-o) (nl-ffi-memory-release layout-o)))
(defun g1-libffi-invoke (fn ret-type arg-types arg-cells ret-cell)
  (let* ((n (length arg-types))
         (cif-o (nl-ffi-memory-allocate 32)) (cif (nl-ffi-memory-address cif-o))
         (types-o (nl-ffi-memory-allocate (* 8 n))) (types (nl-ffi-memory-address types-o))
         (args-o (nl-ffi-memory-allocate (* 8 n))) (args (nl-ffi-memory-address args-o)) (i 0))
    (unwind-protect
        (progn
          (while (< i n)
            (ptr-write-u64 types (* i 8) (nth i arg-types))
            (ptr-write-u64 args (* i 8) (nth i arg-cells))
            (setq i (1+ i)))
          (unless (= (g1-call "ffi_prep_cif" [:sint32 :pointer :sint32 :uint32 :pointer :pointer]
                              cif 2 n ret-type types) 0) (error "CIF rejected aggregate"))
          (g1-call "ffi_call" [:void :pointer :pointer :pointer :pointer] cif fn ret-cell args))
      (dolist (o (list cif-o types-o args-o)) (nl-ffi-memory-release o)))))
(let* ((h (nl-ffi-library-handle "libffi.so.8"))
       (int (nl-ffi--dlsym h "ffi_type_sint32"))
       (type-o (nl-ffi-memory-allocate 24)) (type (nl-ffi-memory-address type-o))
       (elements-o (nl-ffi-memory-allocate 24)) (elements (nl-ffi-memory-address elements-o))
       (values-o (nl-ffi-memory-allocate 8)) (values (nl-ffi-memory-address values-o))
       (result-o (nl-ffi-memory-allocate 8)) (result (nl-ffi-memory-address result-o))
       (libc (nl-ffi--dlopen "libc.so.6")))
  (unwind-protect
      (progn
        (ptr-write-u8 type 10 13) ; FFI_TYPE_STRUCT
        (ptr-write-u64 type 16 elements)
        (ptr-write-u64 elements 0 int) (ptr-write-u64 elements 8 int)
        (ptr-write-u32 values 0 17) (ptr-write-u32 values 4 5)
        (g1-libffi-invoke (nl-ffi--dlsym libc "div") type (list int int) (list values (+ values 4)) result)
        (let ((quot (g1-u32 result 0)) (rem (g1-u32 result 4)))
          (princ (format "libffi-struct-return-div17by5=quot:%d rem:%d size:%d align:%d\n" quot rem
                         (ptr-read-u64 type 0) (+ (ptr-read-u8 type 8) (ash (ptr-read-u8 type 9) 8))))
          (unless (and (= quot 3) (= rem 2) (= (ptr-read-u64 type 0) 8)) (error "Wrong struct return"))))
    (nl-ffi-call "dlclose" libc)
    (dolist (o (list type-o elements-o values-o result-o)) (nl-ffi-memory-release o))))
(princ "LIBFFI-DONE\n")
t
