;;; Callback-free native font fallback + batched viewport drawing in standalone.
(load "/home/madblack-21/Cowork/Notes/dev/nelisp-emacs-lib/.worktrees/ccore-runtime-20261002/packages/nl-ffi/src/nl-ffi.el" nil t)
(require 'nl-ffi-memory)
(dolist (lib '("libcairo.so.2" "libpangocairo-1.0.so.0" "libgobject-2.0.so.0")) (ffi:library lib))
(defun g1-call (name sig &rest args) (apply #'nl-ffi-compat-call nil name sig args))
(defun g1-native-string-call (name sig text)
  (let ((o (nl-ffi-memory-cstring text)))
    (unwind-protect (g1-call name sig (nl-ffi-memory-address o)) (nl-ffi-memory-release o))))
(let* ((canvas (g1-call "cairo_image_surface_create" [:pointer :sint32 :sint32 :sint32] 0 800 500))
       (cr (g1-call "cairo_create" [:pointer :pointer] canvas))
       (layout (g1-call "pango_cairo_create_layout" [:pointer :pointer] cr))
       (desc (g1-native-string-call "pango_font_description_from_string" [:pointer :pointer] "DejaVu Sans Mono"))
       (families (make-hash-table :test 'equal))
       (line "NeLisp 日本語 SKK あいうえお") (lines nil) (text nil) (owner nil) (rects (nl-ffi-memory-allocate 32)))
  (unwind-protect
      (progn
        (g1-call "pango_font_description_set_absolute_size" [:void :pointer :double] desc 28672.0)
        (g1-call "pango_layout_set_font_description" [:void :pointer :pointer] layout desc)
        (g1-call "pango_layout_set_spacing" [:void :pointer :sint32] layout 2048)
        (dotimes (_ 12) (push line lines))
        (setq text (encode-coding-string (mapconcat #'identity lines "\n") 'utf-8)
              owner (nl-ffi-memory-cstring text))
        (let ((start (float-time)))
          (g1-call "pango_layout_set_text" [:void :pointer :pointer :sint32] layout (nl-ffi-memory-address owner) (length text))
          (g1-call "pango_layout_get_pixel_extents" [:void :pointer :pointer :pointer] layout
                   (nl-ffi-memory-address rects) (+ (nl-ffi-memory-address rects) 16))
          (princ (format "pango-cold-layout-ms=%.3f\n" (* 1000 (- (float-time) start)))))
        (let ((n (g1-call "pango_layout_get_unknown_glyphs_count" [:sint32 :pointer] layout)))
          (princ (format "pango-unknown-glyphs=%d\n" n))
          (unless (= n 0) (error "Pango missing glyphs")))
        (let ((iterator (g1-call "pango_layout_get_iter" [:pointer :pointer] layout)) (go t))
          (while go
            (let ((run (g1-call "pango_layout_iter_get_run_readonly" [:pointer :pointer] iterator)))
              (when (> run 0)
                ;; Public PangoGlyphItem.item -> PangoItem.analysis.font, x86-64.
                (let* ((item (ptr-read-u64 run 0)) (font (ptr-read-u64 item 32))
                       (d (g1-call "pango_font_describe" [:pointer :pointer] font))
                       (family (nl-ffi-get-string (g1-call "pango_font_description_get_family" [:pointer :pointer] d))))
                  (puthash family t families)
                  (g1-call "pango_font_description_free" [:void :pointer] d))))
            (setq go (= (g1-call "pango_layout_iter_next_run" [:sint32 :pointer] iterator) 1)))
          (g1-call "pango_layout_iter_free" [:void :pointer] iterator))
        (princ (format "pango-font-families=%S\n" (hash-table-keys families)))
        (unless (>= (hash-table-count families) 2) (error "Mixed fallback runs not observed"))
        (g1-call "cairo_set_source_rgb" [:void :pointer :double :double :double] cr 1.0 1.0 1.0)
        (g1-call "cairo_paint" [:void :pointer] cr)
        (g1-call "cairo_set_source_rgb" [:void :pointer :double :double :double] cr 0.0 0.0 0.0)
        (g1-call "cairo_move_to" [:void :pointer :double :double] cr 20.0 35.0)
        (when (equal (getenv "G1_PANGO_BENCH") "draw")
        (garbage-collect)
        (let ((n 0) (start (float-time)))
          (while (< n 20)
            (g1-call "pango_cairo_show_layout" [:void :pointer :pointer] cr layout)
            (setq n (1+ n)))
          (g1-call "cairo_surface_flush" [:void :pointer] canvas)
          (princ (format "pango-cached-draw-mean-ms=%.3f frames=20 lines=12\n" (* 50 (- (float-time) start))))))
        ;; Re-layout changed text each time, measuring native layout/invalidation.
        (when (not (equal (getenv "G1_PANGO_BENCH") "draw"))
        (g1-call "pango_cairo_show_layout" [:void :pointer :pointer] cr layout)
        (garbage-collect)
        (let* ((edit (encode-coding-string (concat "X" (substring text 1)) 'utf-8))
               (edit-owner (nl-ffi-memory-cstring edit)) (n 0) (start (float-time)))
          (unwind-protect
              (progn
                (while (< n 20)
                  (g1-call "pango_layout_set_text" [:void :pointer :pointer :sint32] layout
                           (if (= (mod n 2) 0) (nl-ffi-memory-address edit-owner) (nl-ffi-memory-address owner)) (length text))
                  (g1-call "pango_cairo_show_layout" [:void :pointer :pointer] cr layout)
                  (setq n (1+ n)))
                (g1-call "cairo_surface_flush" [:void :pointer] canvas)
                (princ (format "pango-edit-relayout-and-draw-mean-ms=%.3f frames=20 lines=12\n" (* 50 (- (float-time) start)))))
            (nl-ffi-memory-release edit-owner))))
        (g1-call "pango_layout_set_text" [:void :pointer :pointer :sint32] layout (nl-ffi-memory-address owner) (length text))
        (g1-call "cairo_set_source_rgb" [:void :pointer :double :double :double] cr 1.0 1.0 1.0)
        (g1-call "cairo_paint" [:void :pointer] cr)
        (g1-call "cairo_set_source_rgb" [:void :pointer :double :double :double] cr 0.0 0.0 0.0)
        (g1-call "pango_cairo_show_layout" [:void :pointer :pointer] cr layout)
        (unless (= (g1-call "cairo_status" [:sint32 :pointer] cr) 0) (error "Cairo error"))
        (let ((o (nl-ffi-memory-cstring (or (getenv "G1_PROBE_PNG") (expand-file-name "probes/results/pango.png")))))
          (unless (= (g1-call "cairo_surface_write_to_png" [:sint32 :pointer :pointer] canvas (nl-ffi-memory-address o)) 0) (error "PNG error"))
          (nl-ffi-memory-release o)))
    (when owner (nl-ffi-memory-release owner))
    (nl-ffi-memory-release rects)
    (g1-call "pango_font_description_free" [:void :pointer] desc)
    (g1-call "g_object_unref" [:void :pointer] layout)
    (g1-call "cairo_destroy" [:void :pointer] cr)
    (g1-call "cairo_surface_destroy" [:void :pointer] canvas)))
(princ "PANGO-DONE\n")
;; Diagnostic only: Linux SYS_exit60 kills one thread; SYS_exit_group231
;; kills native font workers too.  Production quit remains a separate gate.
(when (getenv "G1_EXPLICIT_EXIT_GROUP") (syscall-direct 231 0 0 0 0 0 0))
t
