;;; Feasibility spike: existing wire client + system FreeType/HarfBuzz + XRender.
;;; Linux x86_64 ABI only; offsets taken from installed public FT headers.
;;; This is evidence, not a production frontend or command loop.
(load "/home/madblack-21/Cowork/Notes/dev/nelisp-emacs-lib/.worktrees/ccore-runtime-20261002/packages/nl-ffi/src/nl-ffi.el" nil t)
(require 'nl-ffi-memory)
(load "/home/madblack-21/Cowork/Notes/dev/nelisp-emacs-lib/.worktrees/ccore-resume-20261002/packages/nelisp-x11/src/nelisp-x11.el" nil t)
(ffi:library "libharfbuzz.so.0")
(ffi:library "libfreetype.so.6")
(defun g1-call (name sig &rest args) (apply #'nl-ffi-compat-call nil name sig args))
(defun g1-u16 (p o) (nelisp-x11--u16 p o))
(defun g1-u32 (p o) (nelisp-x11--u32 p o))
(defun g1-s32 (p o) (let ((v (g1-u32 p o))) (if (>= v 2147483648) (- v 4294967296) v)))
(defun g1-le (value n)
  (let ((r nil) (i 0))
    (while (< i n) (push (logand (ash value (* -8 i)) 255) r) (setq i (1+ i)))
    (nreverse r)))
(defvar g1-dpy nil)
(defvar g1-sequence 0)
(defvar g1-request-count 0)
(defvar g1-wire-bytes 0)
(defun g1-send (bytes)
  (let* ((n (length bytes)) (owner (nl-ffi-memory-allocate n))
         (p (nl-ffi-memory-address owner)) (i 0))
    (unwind-protect
        (progn
          (dolist (byte bytes) (ptr-write-u8 p i byte) (setq i (1+ i)))
          (unless (= (nelisp-x11--write (aref g1-dpy 0) p n) n) (error "X write failed"))
          (setq g1-sequence (1+ g1-sequence) g1-request-count (1+ g1-request-count)
                g1-wire-bytes (+ g1-wire-bytes n)))
      (nl-ffi-memory-release owner))))
(defun g1-request (opcode minor payload)
  (let* ((n (+ 4 (length payload))) (pad (mod (- n) 4)))
    (g1-send (append (list opcode minor) (g1-le (/ (+ n pad) 4) 2) payload (make-list pad 0)))))
(defun g1-reply ()
  (let ((p (alloc-bytes 32 8)) (found nil))
    (while (not found)
      (unless (= (nelisp-x11--read-n (aref g1-dpy 0) p 32) 32) (error "X read failed"))
      (cond ((= (ptr-read-u8 p 0) 0)
             (error "X error=%d sequence=%d major=%d minor=%d" (ptr-read-u8 p 1) (g1-u16 p 2)
                    (ptr-read-u8 p 10) (g1-u16 p 8)))
            ((= (ptr-read-u8 p 0) 1) (setq found t))))
    (let* ((extra (* 4 (g1-u32 p 4))) (all (alloc-bytes (+ 32 extra) 8)) (i 0))
      (while (< i 32) (ptr-write-u8 all i (ptr-read-u8 p i)) (setq i (1+ i)))
      (when (> extra 0)
        (unless (= (nelisp-x11--read-n (aref g1-dpy 0) (+ all 32) extra) extra) (error "X reply tail failed")))
      all)))
(defun g1-sync () (g1-request 43 0 nil) (g1-reply)) ; GetInputFocus
(defun g1-raster-glyph (face gid)
  (unless (= (g1-call "FT_Load_Glyph" [:sint32 :pointer :uint32 :sint32] face gid 0) 0) (error "FT load failed"))
  (let ((slot (ptr-read-u64 face 152)))
    (unless (= (g1-call "FT_Render_Glyph" [:sint32 :pointer :sint32] slot 0) 0) (error "FT render failed"))
    (let ((h (g1-u32 slot 152)) (w (g1-u32 slot 156)) (pitch (g1-s32 slot 160))
          (data (ptr-read-u64 slot 168)) (left (g1-s32 slot 192)) (top (g1-s32 slot 196))
          (pixels nil) (y 0) (levels (make-hash-table)))
      (unless (= (ptr-read-u8 slot 178) 2) (error "Expected FT gray bitmap"))
      (while (< y h)
        (let ((x 0))
          (while (< x (nelisp-x11--pad4 w))
            (let ((v (if (< x w) (ptr-read-u8 data (+ (* y pitch) x)) 0)))
              (puthash v t levels) (push v pixels))
            (setq x (1+ x))))
        (setq y (1+ y)))
      (list w h left top (nreverse pixels) (hash-table-count levels)))))
(let* ((display (getenv "DISPLAY")) (colon (string-match ":" display))
       (num (string-to-number (substring display (1+ colon))))
       (ft-owner (nl-ffi-memory-allocate 8)) (face-owner (nl-ffi-memory-allocate 8))
       (ft-out (nl-ffi-memory-address ft-owner)) (face-out (nl-ffi-memory-address face-owner)))
  (setq g1-dpy (nelisp-x11-connect num))
  (unless (vectorp g1-dpy) (error "wire connection failed %S" g1-dpy))
  (princ (format "wire-handshake=%S\n" g1-dpy))
  (g1-request 98 0 (append (g1-le 6 2) '(0 0) (string-to-list "RENDER")))
  (let* ((ext (g1-reply)) (op (ptr-read-u8 ext 9)) (a8 nil) (rgb nil))
    (unless (= (ptr-read-u8 ext 8) 1) (error "XRender missing"))
    (g1-request op 0 (append (g1-le 0 4) (g1-le 11 4)))
    (let ((r (g1-reply))) (princ (format "XRender=%d.%d opcode=%d\n" (g1-u32 r 8) (g1-u32 r 12) op)))
    (g1-request op 1 nil)
    (let* ((r (g1-reply)) (n (g1-u32 r 8)) (i 0))
      (while (< i n)
        (let ((off (+ 32 (* i 28))))
          (when (and (= (ptr-read-u8 r (+ off 4)) 1) (= (ptr-read-u8 r (+ off 5)) 8)
                     (= (g1-u16 r (+ off 22)) 255)) (setq a8 (g1-u32 r off)))
          (when (and (= (ptr-read-u8 r (+ off 4)) 1) (= (ptr-read-u8 r (+ off 5)) 24)
                     (= (g1-u16 r (+ off 10)) 255) (= (g1-u16 r (+ off 22)) 0)) (setq rgb (g1-u32 r off))))
        (setq i (1+ i))))
    (unless (and a8 rgb) (error "Missing A8/RGB24 formats"))
    (princ (format "formats=A8:%d RGB24:%d\n" a8 rgb))
    (unless (= (g1-call "FT_Init_FreeType" [:sint32 :pointer] ft-out) 0) (error "FT init failed"))
    (let* ((ft (ptr-read-u64 ft-out 0))
           (font-owner (nl-ffi-memory-cstring "/usr/share/fonts/truetype/vlgothic/VL-Gothic-Regular.ttf")))
      (unless (= (g1-call "FT_New_Face" [:sint32 :pointer :pointer :sint64 :pointer]
                           ft (nl-ffi-memory-address font-owner) 0 face-out) 0) (error "FT face failed"))
      (nl-ffi-memory-release font-owner)
      (let* ((face (ptr-read-u64 face-out 0)) (win (nelisp-x11-create-window g1-dpy 20 20 800 500))
             (dst (nelisp-x11-gen-id g1-dpy)) (src (nelisp-x11-gen-id g1-dpy))
             (set (nelisp-x11-gen-id g1-dpy)) (hb nil) (buffer nil) (uploaded (make-hash-table)))
        (setq g1-sequence (1+ g1-sequence))
        (g1-request 18 0 (append (g1-le win 4) (g1-le 39 4) (g1-le 31 4) '(8 0 0 0)
                                 (g1-le 16 4) (string-to-list "g1-xrender-probe")))
        (g1-request op 4 (append (g1-le dst 4) (g1-le win 4) (g1-le rgb 4) (g1-le 0 4)))
        (g1-request op 33 (append (g1-le src 4) (g1-le 0 2) (g1-le 0 2) (g1-le 0 2) (g1-le 65535 2)))
        (g1-request op 17 (append (g1-le set 4) (g1-le a8 4)))
        (nelisp-x11-map-window g1-dpy win) (setq g1-sequence (1+ g1-sequence))
        (unless (= (g1-call "FT_Set_Pixel_Sizes" [:sint32 :pointer :uint32 :uint32] face 0 28) 0) (error "FT size failed"))
        (setq hb (g1-call "hb_ft_font_create_referenced" [:pointer :pointer] face)
              buffer (g1-call "hb_buffer_create" [:pointer]))
        (let* ((text (encode-coding-string "NeLisp 日本語 SKK あいうえお" 'utf-8))
               (text-owner (nl-ffi-memory-cstring text)))
          (g1-call "hb_buffer_add_utf8" [:void :pointer :pointer :sint32 :uint32 :sint32]
                   buffer (nl-ffi-memory-address text-owner) (length text) 0 (length text))
          (nl-ffi-memory-release text-owner))
        (g1-call "hb_buffer_guess_segment_properties" [:void :pointer] buffer)
        (g1-call "hb_shape" [:void :pointer :pointer :pointer :uint32] hb buffer 0 0)
        (let* ((count (g1-call "hb_buffer_get_length" [:uint32 :pointer] buffer))
               (infos (g1-call "hb_buffer_get_glyph_infos" [:pointer :pointer :pointer] buffer nil))
               (positions (g1-call "hb_buffer_get_glyph_positions" [:pointer :pointer :pointer] buffer nil))
               (i 0) (x 20) (y 65) (codes nil) (start (float-time)))
          (princ (format "hb-shaped=%d\n" count))
          (while (< i count)
            (let* ((gid (g1-u32 infos (* i 20))) (cluster (g1-u32 infos (+ (* i 20) 8)))
                   (advance (/ (g1-s32 positions (* i 20)) 64)))
              (when (= gid 0) (error "Missing glyph for cluster %d" cluster))
              (unless (gethash gid uploaded)
                (let* ((g (g1-raster-glyph face gid)) (w (nth 0 g)) (h (nth 1 g))
                       (left (nth 2 g)) (top (nth 3 g)))
                  (g1-request op 20 (append (g1-le set 4) (g1-le 1 4) (g1-le gid 4)
                                            (g1-le w 2) (g1-le h 2) (g1-le (- left) 2)
                                            (g1-le top 2) (g1-le 0 2) (g1-le 0 2) (nth 4 g)))
                  (princ (format "glyph=%d cluster=%d bitmap=%dx%d gray-levels=%d advance=%d\n"
                                 gid cluster w h (nth 5 g) advance)))
                (puthash gid t uploaded))
              (push (list gid x y) codes)
              (setq x (+ x advance)))
            (setq i (1+ i)))
          (setq codes (nreverse codes))
          (dolist (code codes)
            (g1-request op 25 (append '(3 0 0 0) (g1-le src 4) (g1-le dst 4) (g1-le a8 4)
                                      (g1-le set 4) '(0 0 0 0) '(1 0 0 0)
                                      (g1-le (nth 1 code) 2) (g1-le (nth 2 code) 2) (g1-le (car code) 4))))
          (g1-sync)
          (princ (format "cold-font-upload-and-first-draw-seconds=%.6f glyphs=%d\n" (- (float-time) start) (hash-table-count uploaded)))
          (let ((frames 0) (start2 (float-time)) (before g1-wire-bytes))
            ;; One CompositeGlyphs32 request per row, 12 rows, ten frames.
            (while (< frames 10)
              (nelisp-x11-clear-area g1-dpy win 0 0 800 500)
              (let ((row 0))
                (while (< row 12)
                  (let ((elts nil) (lastx 0) (lasty 0))
                    (dolist (code codes)
                      (let ((xx (nth 1 code)) (yy (+ 65 (* row 32))))
                        (setq elts (append elts '(1 0 0 0) (g1-le (- xx lastx) 2)
                                           (g1-le (- yy lasty) 2) (g1-le (car code) 4))
                              lastx xx lasty yy)))
                    (g1-request op 25 (append '(3 0 0 0) (g1-le src 4) (g1-le dst 4)
                                              (g1-le a8 4) (g1-le set 4) '(0 0 0 0) elts)))
                  (setq row (1+ row))))
              (g1-sync) (setq frames (1+ frames)))
            (princ (format "warm-draw-ms-per-frame=%.3f rows=12 chars-per-row=%d wire-bytes-per-frame=%d\n"
                           (* 100 (- (float-time) start2)) count (/ (- g1-wire-bytes before) 10))))
          (princ (format "WINDOW-READY=%d\n" win))
          (let ((go t))
            (while go
              (let ((ev (nelisp-x11-poll-event g1-dpy 10000)))
                (unless ev (error "No injected key within 10 seconds"))
                (let ((kind (logand (ptr-read-u8 ev 0) 127)))
                  (when (= kind 0) (error "X error during event poll"))
                  (when (= kind 2) (princ (format "key-event=keycode:%d state:%d\n" (ptr-read-u8 ev 1) (g1-u16 ev 28)))
                        (setq go nil)))))))
        (g1-call "hb_buffer_destroy" [:void :pointer] buffer)
        (g1-call "hb_font_destroy" [:void :pointer] hb)
        (g1-call "FT_Done_Face" [:sint32 :pointer] face))
      (g1-call "FT_Done_FreeType" [:sint32 :pointer] ft))
    (nelisp-x11-close g1-dpy))
  (nl-ffi-memory-release ft-owner) (nl-ffi-memory-release face-owner))
(princ "XRENDER-DONE\n")
t
